package com.daasui.pages;

import java.io.IOException;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;

import com.basesource.action.CommonMethod;

/**
 * This class contains method(s) for validating data in datalayer.
 *
 */
public class GoogleAnalyticsPage extends CommonMethod {

	private GoogleAnalyticsPage instance;
	public JavascriptExecutor js = (JavascriptExecutor) getDriver();

	public GoogleAnalyticsPage getInstance() throws IOException {
		if (instance == null) {
			synchronized (WhatsNewPage.class) {
				if (instance == null) {
					instance = new GoogleAnalyticsPage(DRIVER);
				}
			}
		}
		return instance;
	}

	public GoogleAnalyticsPage(WebDriver driver) throws IOException {
	}

	/**
	 * This method is used to validate pagename of dashboard which is generated by pageView event of Datalayer object.
	 * 
	 * @return
	 * @throws Exception
	 */
	public final boolean getDataLayer() throws Exception {
		boolean flag = false;
		try {
			String pageName = jsDriver().executeScript("return dataLayer[3].pageNameL5").toString();
			if (pageName.equalsIgnoreCase("dashboard")) {
				flag = true;
			}
			return flag;
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			return false;

		}
	}

}
