status = info
name = Selenium_DaaS_Automation
 
appenders = console, file 
 
appender.console.type = Console
appender.console.name = LogToConsole
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{MM-dd-yyyy HH:mm:ss} %F %-5p [%t] %c{2} %L - %m%n

appender.file.type = File
appender.file.name = FileLogger
appender.file.fileName = ./log/applog.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{ISO8601} %5p [%t] %c{1}:%L - %m%n
 
loggers = file
 
logger.file.name = Selenium_DaaS_Automation
logger.file.level = info
logger.file.additivity = false
logger.file.appenderRef.file.ref = FileLogger

# Root logger
rootLogger.level=info
rootLogger.appenderRef.console.ref=LogToConsole
rootLogger.appenderRef.file.ref=FileLogger