signinwithamazon= [xpath]://button[@class='welcome-signin-button vn-button css-vt1kjq']
enteramazonemail= [xpath]://input[@type='email']
enteramazonpassowrd= [xpath]://input[@type='password']
amazonsigninbutton= [id]:signInSubmit
agreeTNCCheckbox= [xpath]://input[@name='agree-tnc-chck']
tandCAcceptButton=[xpath]://button[@class='accept-button css-vt1kjq']
tandCCancelButton=[xpath]://button[@class='cancel-button css-1ql8biu']
tandCCancelModal=[xpath]://h4[normalize-space()='Are you sure you want to cancel?']
signOutbutton=[xpath]://span[normalize-space()='Yes, Sign Out']