benchmarkTab = [css]:#menu_benchmarks a
benchmarkPage = [xpath]://*[@id='dui-container']//div[contains(@class,'benchmark-list')]
benchmarkTitleOnBreadcrumbs = [css]:#benchmarks li
benchmarkAdd = [css]:#btn_benchmark_add
addBenchmarkForm = [id]:newBenchmark
benchmarkTable = [xpath]://table[@class]//tr[1]
benchmarkNameField = [css]:#benchmark
categoryDropdown = [xpath]://*[@id="category"]//div/button
categoryList = [xpath]://*[@id='category']//div[@role='listbox']/div
subCategoryList = [xpath]://div[contains(@id,'subCategory')]
selectSubCategory = [xpath]://*[contains(@id,'subCategory')]//div[@role='listbox']//a
openCalenderStartDate = [xpath]://input[@name='startDate']
openCalenderEndDate = [xpath]://input[@name='endDate']
subCategoryNoData = [xpath]://*[@id="subCategory1"]/div[contains(@class,'disabled')]
potentialProgressBar = [xpath]://*[@class="benchmark-progress-bar"]/div/div[2]/div[1]
selectToday = [css]:#button
monthList = [xpath]://*[contains(@class,'CalendarMonth')]//div[@role='listbox']//a
dateList = [xpath]://div[contains(@class,'CalendarMonth')][@data-visible='true']/table//td[@role]
saveButton = [css]:#save-button
benchmarkNameColumn = [css]:#benchmark-name
benchmarkNameInList = [xpath]://table[@class]//tr[1]/td[3]
tableConfig = [xpath]://button[@title='Table Configuration']
resetButton = [css]:#reset
tableConfigColumncheckboxList = [xpath]://li[contains(@class,'multiselect')]//input[not(@checked)]
tableConfiglistOfColumns = [css]:div[class$='tableconfiguration'] span[class$=checkbox__span]+span
saveColulmns = [css]:#save
selectBenchmarkInList = [xpath]://table[@class]//tr[1]/td[2]
duplicateButton = [css]:#btn_benchmark_duplicate
disabledCategory = [xpath]://*[@id="category"]//div[contains(@class,'disabled')]
disabledSubCategory = [xpath]://*[@id="subCategory1"]//div[contains(@class,'disabled')]
endBenchmark = [css]:#end-benchmark-button
deleteBenchmark = [css]:#btn_benchmark_delete
deleteConfirmation = [css]:#modal-submit
benchmarkListcolumns = [css]:th div div[class*='tableheader__label']
benchmarkName = [xpath]://table[@class]//tr[1]/td[3]//a
tabByModel = [xpath]://div[@role='tablist']//a[2]
tabByOS = [xpath]://div[@role='tablist']//a[3]
tabDetails = [xpath]://div[@role='tablist']//a[5]
tabOverview = [xpath]://div[@role='tablist']//a[1]
tabTop10 = [xpath]://div[@role='tablist']//a[4]
healthMetricTitle = [css]:div[class*='overview-health-metrics'] div[class*='title']
healthMetric = [css]:div[class*='health-metrics'] div[class*='metrics-seprator']
overviewBenchtitle = [css]:div[class*='benchmark-info']>div>div>div[class*='title']
top10TableTitles = [css]:div[class='benchmark-top10'] button
filterCriteria = [css]:div[class='filter-criteria'] div label[class='title-font']
closeLevel = [xpath]://div[@class='benchmark-progess-bar-status']
#Location changes and company selection 
globalLocationFilterDropdownBenchmark = [xpath]://*[@id='gf-open-button']
globalLocationFilterClearIconBenchmark = [xpath]://*[@id='gf-clear-button']

globalLocationFilter = [xpath]://*[@id='app-location-filter']//p
filterMenuCompaniesSearch = [xpath]://*[@id='company']//div/input

selectCompanyOnSearch = [xpath]://*[@id='company']//li[1]//span//label//span
filterMenuCompaniesHeader = [xpath]://*[@id='company']/div[1]/div[1]

locatFilterCompanyName = [xpath]://*[@id='app-location-filter']//div/span[1]
applyCompanyLocationFilter = [xpath]://*[@id='apply-global-filter']
clearGlobalFilter = [xpath]://*[@id='clear-global-filter']