benchmarkTab = [css]:#menu_benchmarks a
benchmarkPage = [xpath]://*[@id='dui-container']//div[contains(@class,'benchmark-list')]
benchmarkTitleOnBreadcrumbs = [css]:#benchmarks li
benchmarkAdd = [css]:#btn_benchmark_add
addBenchmarkForm = [id]:newBenchmark
benchmarkTable = [xpath]://table[@class]//tr[1]
benchmarkNameField = [css]:#benchmarkName
categoryDropdown = [css]:#category
categoryList = [css]:#category-listbox li
subCategoryList = [xpath]://div[contains(@id,'subCategory')]
selectSubCategory = [xpath]://*[contains(@id,'subCategory')]/li[1]
openCalenderStartDate = [xpath]://input[@name='startDate']
openCalenderEndDate = [xpath]://input[@name='endDate']
subCategoryNoData = [xpath]://div[@aria-disabled='true'][contains(@id,'subCategory1')]
potentialProgressBar = [xpath]://*[@class="benchmark-progress-bar"]
selectToday = [xpath]://table[contains(@class,'CalendarMonth_table')]//td[contains(@class,'CalendarDay__today')]
monthList = [xpath]:(.//div[contains(@class,'CalendarMonth_caption')])[2]//button[@name]
dateList = [xpath]:(.//div[contains(@class,'CalendarMonth_caption')])[2]//following::table[1]/tbody/tr/td
saveButton = [css]:#save-button
benchmarkNameColumn = [xpath]://input[contains(@id,'name')]
benchmarkNameInList = [xpath]:(//div[contains(@class,'benchmark-list')]//td/a)[1]
tableConfig = [xpath]://button[@aria-label='Column Options']
resetButton = [css]:#column-options-label+div+button
tableConfigColumncheckboxList = [css]:#column-options-label+div div[role=option] input[aria-checked=false]
tableConfiglistOfColumns = [xpath]://span[@id='column-options-label']//parent::div//ul//input[@aria-checked='false']/following::span[1]
saveColulmns = [css]:#column-options-label+div+button+div button:nth-child(1)
selectBenchmarkInList = [xpath]://input[@aria-label='0']
duplicateButton = [xpath]://div[contains(@class,'dui-table-horizontal')]/button[2]
disabledCategory = [xpath]://div[@aria-disabled='true'][@id='category']
disabledSubCategory = [xpath]://div[@aria-disabled='true'][contains(@id,'subCategory')]
endBenchmark = [css]:#end-benchmark-button
deleteBenchmark = [xpath]://div[@class='dui-table-horizontal-group dui-one-line']//button[@id='btn_benchmark_delete']
deleteConfirmation = [css]:#modal-submit
benchmarkListcolumns = [xpath]://*[@id="dui-container"]//thead/tr[1]/th/button
benchmarkName = [xpath]://table[@class]//tr[1]/td[2]/a
tabByModel = [xpath]://div[@role='tablist']/div[2]
tabByOS = [xpath]://div[@role='tablist']/div[3]
tabDetails = [xpath]://div[@role='tablist']/div[5]
tabOverview = [xpath]://div[@role='tablist']/div[1]
tabTop10 = [xpath]://div[@role='tablist']/div[4]
healthMetricTitle = [xpath]://div[@class='dui-panel-header']
healthMetric = [css]:div[class*='health-metrics'] div[class*='metrics-seprator']
overviewBenchtitle = [xpath]://span[@aria-current='page']
top10TableTitles = [xpath]://div[contains(@class,'benchmark-top10')]//div[@aria-controls]
popOver = [xpath]://*[@data-popover-backdrop="true"]
clearSelection = [css]:button[aria-label='Clear selection']
firstCheckbox = [css]:tbody>tr:nth-of-type(1) div[class*='avatar']
filterCriteria = [css]:div[class='filter-criteria'] div label[class='title-font']
duration= [css]:div[class='duration-label'] label[class='title-font']
#Location changes and company selection 
globalLocationFilterDropdownBenchmark = [id]:global-filter
globalLocationFilterClearIconBenchmark = [xpath]://*[@id='gf-clear-button']

globalLocationFilter = [xpath]://*[@id='app-location-filter']//p
filterMenuCompaniesSearch = [css]:#company-search
selectCompanyOnSearch = [css]:#company label:nth-child(1) span:nth-child(2)
filterMenuCompaniesHeader = [css]:#company div[class*=global-location-panel-header] span:first-child

locatFilterCompanyName = [xpath]://*[@id='app-location-filter']//div/span[1]
applyCompanyLocationFilter = [css]:div.dui-global-location-buttons button:first-child
clearGlobalFilter = [xpath]://*[@id='clear-global-filter']
informationPanel = [xpath]://button[@aria-label='Close']