campaignsTab = [id]:menu_campaign
campaignListTab = [id]:campaignListTab
campaignsTitle = [css]:#dui-breadcrumbs li
campaignDetailsTitle = [xpath]://ul[@id='dui-breadcrumbs']/li[2]
clearfilter = [xpath]://button[@title='Clear']
tableOverlay = [xpath]:div[class*='table__overlay--loading']
noDataAvailableText = [css]:div.vn-table__wrapper table tbody tr td
firstCampaignOnListPage = [css]:tr:nth-child(1) td[headers*=col-id-name] a
addCampaignButton = [id]:btn_campaign_add
deleteCampaignButton = [id]:btn_campaign_delete
stateSearchBox = [id]:campaign-state
campaignDashboardTab = [id]:dashboardTab
addCampaignButtonOnDashboard = [id]:btn_campaign_add_campaign
viewListButtonOnDashboard = [id]:btn_campaign_view_list
listTable = [css]:table[class*=table]
nameHeader = [id]:col-id-name
totalCampaignsTitle = [css]:#dui-container [class*=panel-small] [class*=panel__header] div
keyPerformanceTitle = [css]:#dui-container [class*=panel-big] [class*=panel__header] div
averageSatisfactionTitle = [xpath]:(//*[@id="dui-container"]//*[contains(@class,'panel-medium')]//*[contains(@class,'panel__title')])[1]
satisfactionAverageChartTitle = [xpath]:(//*[@id="dui-container"]//*[contains(@class,'panel-medium')]//*[contains(@class,'panel__title')])[2]
campaignsCommencedByStateTitle = [xpath]:(//*[@id="dui-container"]//*[contains(@class,'panel-medium')]//*[contains(@class,'panel__title')])[3]
campaignsByMedalliaChartTitle = [xpath]:(//*[@id="dui-container"]//*[contains(@class,'panel-medium')]//*[contains(@class,'panel__title')])[4]
noOfCampaignsOnDashboard = [xpath]:(//*[contains(@class, 'response-title')])[5]
targetedUsersTitle = [xpath]:(//*[contains(@class, 'response-title')])[6]
categoryColumnHeader = [id]:col-id-category
categoryColumnSearchBox = [id]:campaign-category
noElementsDisplayText = [css]:td[class*="no-items"]
#firstCampaignOnListPage = [css]:tr:nth-of-type(1) td[headers=col-id-name] a
responsesColumnData = [css]:tr:nth-of-type(1) td[headers=col-id-responses]
firstIdLogo = [css]:tr:nth-child(1) div[class*=avatar]
firstIdCheckBox = [css]:tr:nth-of-type(1) td:nth-of-type(2) span
duplicateButton = [id]:btn_campaign_duplicate