campaignsTab = [id]:menu_campaign
campaignListTab = [xpath]://div[@id="campaignList"]
campaignsTitle = [xpath]://div[@id="campaign"]//li/span
campaignDetailsTitle = [xpath]://*[@id='campaignDetails']//li[2]/span
newCampaignTitle = [xpath]://*[@id='newCampaign']//li[2]/span
duplicateCampaignTitle = [xpath]://*[@id='duplicateCampaign']//li[2]/span
campaignDetailsTitleHeader = [xpath]://div[@class='card-title']//div
clearfilter = [css]:button[aria-label="Clear Filters"]
tableOverlay = [xpath]://div[class*='table__overlay--loading']
noDataAvailableText = [xpath]://div[@id="extended-campaignList"]//table//tr/td//span
firstCampaignOnListPage = [xpath]://div[@id="extended-campaignList"]//tr[1]/td[2]/a
addCampaignButton = [id]:btn_campaign_add
deleteCampaignButton = [id]:btn_campaign_delete
stateSearchBox = [xpath]://input[@id="state"]
statecolumnheader = [id]:state
campaignDashboardTab = [xpath]://div[@id="campaignDashboard"]
addCampaignButtonOnDashboard = [id]:btn_campaign_add_campaign
viewListButtonOnDashboard = [id]:btn_campaign_view_list
listTable = [css]:div[class*=campaign-list] table thead
okdeletebutton = [xpath]://div[@id='confirmationModalDelete-desc']/following-sibling::div//button[1]
nameHeader = [xpath]://*[@id="extended-campaignList"]//table/tbody/tr[1]/td[1]
totalCampaignsTitle = [xpath]:(//*[@id='extended-campaignDashboard']//*[contains(@class, 'card-title')])[1]
keyPerformanceTitle = [xpath]:(//*[@id='extended-campaignDashboard']//*[contains(@class, 'card-title')])[2]
averageSatisfactionTitle = [xpath]:(//*[@id='extended-campaignDashboard']//*[contains(@class, 'card-title')])[3]
satisfactionAverageChartTitle = [xpath]:(//*[@id='extended-campaignDashboard']//*[contains(@class, 'card-title')])[4]
campaignsCommencedByStateTitle = [xpath]:(//*[@id='extended-campaignDashboard']//*[contains(@class, 'card-title')])[5]
campaignsByMedalliaChartTitle = [xpath]:(//*[@id='extended-0']//*[contains(@class, 'card-title')])[6]
responseColumnHeader = [id]:responses
responseColumnSearchBox = [name]:responses
categoryColumnHeader = [id]:category
categoryColumnSearchBox = [name]:category
noOfCampaignsOnDashboard = [xpath]:(//*[contains(@class, 'dui-campaign-response-title')])[5]
targetedUsersTitle = [xpath]:(//*[contains(@class, 'dui-campaign-response-title')])[4]
noElementsDisplayText = [css]:td[class*="no-items"]
responsesColumnData = [xpath]://*[@id="extended-campaignList"]//table/tbody/tr[1]/td[8]
firstIdLogo = [css]:tr:nth-child(1) div[class*=vn-table__avatar
firstIdCheckBox = [xpath]://*[@id="extended-campaignList"]//tr[1]/td[1]//input[@type='checkbox']
duplicateButton = [id]:btn_campaign_duplicate
firstCampaignAfterSearch=[xpath]://*[@id="extended-campaignList"]//td[2]/a
globalLocationFilterDropDown = [css]:button[class*='global-location-link']
campaignNameTextBoxOnListPage = [xpath]:(//*[@id="name"])[2]
closeInformationPanel = [css]:#dui-table-sidebar button