overviewTab = [css]:#dui-container [role = tablist] > nav a:nth-child(1)
responseResultsTab = [css]:#dui-container [role = tablist] > nav a:nth-child(2)
deviceHealthTab = [css]:#dui-container [role = tablist] > nav a:nth-child(3)
saveButton = [id]:save-button
discardButton = [id]:discard-or-details-button
endCampaignButton = [id]:end-campaign-now
campaignNameOnDetailsPage = [css]:[class*=campaign-details] div[class*=panel__title]
campaignNameTextBox = [id]:campaign
campaignDescriptionTextBox = [id]:description
categoryDropDown = [css]:[class*=panel__content] > div > div:nth-child(2) svg
subCategoryDropDown = [css]:[class*=panel__content] > div > div:nth-child(3) svg
startDateField = [xpath]:(//*[contains(@name, 'campaign-start-date')])[1]
endDatePicker = [xpath]:(//*[contains(@name, 'campaign-end-date')])[1]
userSatisfactionType = [css]:[class*=campaign-questionList] [class*=select__title] > div:first-child
userSatisfactionRating = [css]:[class*=campaign-questionList] input
categoryList = [css]:[class*=select-content] div > [class*=option]
firstElementOnSubcategoryDropDown = [css]:[class*=select-content] div > [class*=option]:first-child
monthKeyCurrent = [css]:div[class*=DayPicker_transitionContainer] div:nth-child(2) div[class*=datepicker__caption] div:nth-child(1) div[class*=select__title] div:nth-child(1)
endDateDialogRightArrow = [css]:div[class*=DayPickerNavigation] div:nth-child(2)  svg
todayButton = [css]:#button
toastNotification = [xpath]://div[contains(@class,'toast-enter-done')]//p
endDateDialogRightArrow = [css]:div[class*=DayPickerNavigation] div:nth-child(2)  svg
daysOnCurrentMonthKey=[css]:div[class*=DayPicker_transitionContainer] div:nth-child(2) tbody tr td[class*=CalendarDay]
satisfactionRatingTextbox = [xpath]://*[@id="0"]
addQuestionsLink = [css]:[class*=add-ques] label
typeDropDown = [css]:[class*='new-campaign-input'] [id*=question-list-select-input] 
firstElementOnTypeDropDown = [css]:[role*='listbox'] [id*=question-list]:first-child
nameList = [css]:td[headers*=name]
nameSearchBox = [id]:campaign-name
responseResultsTab = [css]:#dui-container [role = tablist] > nav a:nth-child(2)
deviceHealthTab = [css]:#dui-container [role = tablist] > nav a:nth-child(3)
noDataAvailableText = [css]:tbody [class*=no-items]
exportButton = [css]:[class*=export-button] button
toastNotification = [xpath]://div[contains(@class,'toast-enter-done')]//p
closeToastNotification = [xpath]://*[contains(@class,'container--bottom')]/div/button
notificationBellIcon = [xpath]://*[contains(@class,'bell-button')]//div/button
downloadLink = [xpath]://div[contains(@class, 'notification-center-item__extra')]//a
tableOverLay = [xpath]://div[@class='vn-table__overlay']
firstCompanyOnDropDown = [xpath]:(//*[contains(@class,'options-list')]//a)[1]
categoryDropDownForMSP = [css]:[class*=panel__content] > div > div:nth-child(3) svg
subcategoryDropDownMSP = [css]:[class*=panel__content] > div > div:nth-child(4) svg
endDatePickerForCampaignUpdate = [css]:[class*=form-field] [class*=datepicker] svg:nth-child(3)
calendarPopup = [css]:div ul[class*=datepicker__calendar]
categoryDropDownOptions = [css]:[class*=options-list]
firstDeviceInList = [css]:td[headers='col-id-deviceSn'] a
deviceDetailsSection = [css]:[class=campaign-tech-pules-graph-panel]

#company Logo
companyLogoTitle = [css]:div[class*=company-logo-label]
addCompanyLogoOnCompanySetting = [css]:div[class*=add-company-logo]
showCompanyLogoOnEndUserCheckboxText = [css]:div[class*=company-logo-checkbox] span:nth-child(2)
showCompanyLogoOnEndUserCheckbox = [css]:div[class*=company-logo-checkbox] span:nth-child(1) input
selectLogoImageIcon = [xpath]://*[@id="camera"]
browseButton = [xpath]://*[@id="profile_photo_radio"]//button
selectImageRadioButtonOnPopup = [xpath]://*[@id="profile_photo_radio-file"]
saveButtonOnPopUp = [xpath]:(//*[contains(@class,'modal__footer')]//*[contains(@class,'group--horizontal')])/button[1]
logoImage = [xpath] : //*[@id="dui-container"]//img
okButtonFromPopUp = [xpath]:(//*[contains(@class,'modal--footer')])[2]/div/button[1]
youAreAboutToLeaveCampaignPagePopUpText = [xpath]:(//*[contains(@class,'modal--body')])[3]