overviewTab = [id]:0
responseResultsTab = [xpath]://*[@id="1"]
deviceHealthTab = [xpath]://*[@id="2"]
saveButton = [id]:save-button
discardButton = [id]:discard-or-details-button
endCampaignButton = [id]:end-campaign-now
campaigncreationnewtext = [xpath]:(//*[@class='dui-updated-ui-new-campaign']//div)[1]/div
newcampaigntab = [xpath]://*[@id='campaignDetails']//li[1]/a
campaignNameOnDetailsPage = [css]:[class*=campaign-details-container-tab] div[class*=card-title] div
campaignNameOnDetailsPagenewUI = [css]:[class*=campaign-details-container-tab] div[class*=page-header] div:first-child
campaignNameTextBox = [xpath]://*[@id="campaign-name-id"]
campaignDescriptionTextBox = [id]:campaign-description-down-id
medalliacampaignDescriptionTextBox = [id]:campaign-desc-medallia
categoryDropDown = [id]:category-select-input
showcompanylogosection=[xpath]://div[@Class='company-logo-checkbox']/*
companylogocheckbox=[xpath]://div[@Class='company-logo-checkbox']//span[1]
citeriaheaderold = [xpath]:(//*[@id='dui-container']//div[@class='title-margin']//div)[2]/../../../*[1]
addcriteria = [xpath]://div[contains(@class,'add-criteria')]/div
criteriadd = [xpath]:(//*[@id='dui-container']//div[@class='title-margin']//div//div[contains(@class,'label')])[3]
valuedd = [xpath]:((//*[@id='dui-container']//div[contains(@class,'criteria-header')])/..//div[contains(@class,'value-dropdown')]//div)[position()=last()-2]
filtercriteriatile = [xpath]:(//div[contains(@class,'dui-updated-ui-new-campaign')])[2]//div[contains(@class,'section-label')]
filteroption = [xpath]://ul[contains(@id,'listbox')]//li[6]
filteroptionslist = [xpath]: //ul[contains(@id,'listbox')]//li
groupsvaluelist = [css]:div[class*=option]>*
filtervalue1 = [xpath]://ul[contains(@id,'listbox')]//li[1]
filtervalue2 = [xpath]://ul[contains(@id,'listbox')]//li[1]
groupsvalue = [xpath]://ul[contains(@id,'listbox')]//li[12]
firstciteriaheader = [xpath]://div[contains(@class,'filter-criteria-header')][1]
secondcriteriaheader = [xpath]://div[contains(@class,'filter-criteria-header')][2]
overlay = [css]:div[class*=css-n]
calculateaudience = [xpath]://div[contains(@class,'potential-audience')]//button
subcategorytext = [xpath]:(//*[contains(@class,'campaign-input-label')])[3]
campaignslist = [xpath]://*[@id='campaignDetails']//a
subCategoryDropDown = [id]:sub-category-select-input
calculateAudience = [xpath]://*[@id="dui-container"]//*[contains(@class,'potential-audience-wrapper')]//span
startDateField =[css]:#start-date-input
endDatePicker = [css]:#end-date-input
userSatisfactionType = [id]:satesfaction-type-select-input
userSatisfactionRating = [id]:question-name-id
detailsheader = [xpath]://*[contains(@class,'details-divider')][1]
detailsheaderongoing = [xpath]:(//div[@class='question-title'])[2]
criteriaheader = [xpath]://*[contains(@class,'details-divider')][2]
criteria1headercreateampaignpage = [xpath]://*[contains(@class,'filter-criteria')]/div
targetaudienceheader = [xpath]://*[contains(@class,'details-divider')][3]
durationheadernewUI = [xpath]://*[contains(@class,'details-divider')][4]
questionheadernewUI = [xpath]://*[contains(@class,'details-divider')][5]
targetaudiencemessage = [css]:div [class='tooltip-text']
criteriainnerheader = [xpath]://div[contains(@class,'filter-criteria')]
criteriafieldheader = [xpath]://div[contains(@class,'filter-criteria')]/following-sibling::div[1]/div[1]
campaignNameTextBoxdetail = [xpath]://div[contains(@class,'completed-campaign')]//div[contains(@class,value)][2]/div[1]/div[2]
criteriaValue = [xpath]://div[contains(@class,'filter-criteria')]/following-sibling::div[2]/div[1]
criteriaOperator = [xpath]://div[contains(@class,'filter-criteria')]/following-sibling::div[3]/div[1]
campaignnameongoing = [xpath]://div[contains(@class,'new-campaign-input css')]/div/*[@id='campaign-name-id']
campaigndescriptionongoing = [xpath]://div[contains(@class,'new-campaign-input css')]/div/*[@id='campaign-desc-details-page']
categoryongoing = [xpath]://div[contains(@class,'new-campaign-input css')]/div/*[@id='category-select-input']
subcategoryongoing = [xpath]://div[contains(@class,'new-campaign-input css')]/div/*[@id='sub-category-select-input']
criteriaheaderongoing = [xpath]://*[contains(@class,'campaign-section-label')]
filterfieldongoing = [xpath]:(//div[contains(@class,'label')])[8]/*
criteriainnerheaderongoing = [xpath]:(//*[contains(@class,'filter-criteria-header')])[2]
locationongoing = [xpath]:(//*[contains(@class,'title-font')])[2]
durationongoing = [xpath]:(//*[contains(@class,'title-font')])[3]
reqquesheaderongoing = [xpath]:(//*[contains(@class,'title-font')])[4]
additionalquesongoing = [xpath]:(//*[contains(@class,'title-font')])[5]
categoryTextBox = [xpath]://div[contains(@class,'completed-campaign')]//div[contains(@class,value)][2]/div[3]/div[2]
categoryTextBoxnoLogo = [xpath]://div[contains(@class,'completed-campaign')]//div[contains(@class,value)][2]/div[2]/div[2]
subcategoryTextBox = [xpath]://div[contains(@class,'completed-campaign')]//div[contains(@class,value)][2]/div[5]/div[2]
subcategoryTextBoxnoLogo = [xpath]://div[contains(@class,'completed-campaign')]//div[contains(@class,value)][2]/div[4]/div[2]
campaignParticpationtitlenewUI = [xpath]:(//div[@class='question-title'])[1]
campaignquestionnewUI = [xpath]:(//div[@class='card-title'])[2]/div
editbuttonongoing = [xpath]:(//div[contains(@class,'detail-page-header')])/div[2]/button[1]
deletebuttonnewUI = [xpath]:(//div[contains(@class,'detail-page-header')])/div[2]/button[1]
exportbuttonnewUI = [xpath]:(//div[contains(@class,'detail-page-header')])/div[2]/button[2]
devicehealthtitlenewUI = [xpath]:(//div[@class='card-title'])[1]/div
nodataongoing = [xpath://*[name()='g' and contains(@class, 'highcharts-no-data')]
userSatisfactionRatingnewUI = [xpath]:(//div[@class='details-divider'][5]/following-sibling::div/div)[1]/div
categoryList = [xpath]://*[@id="category-select-input-listbox"]/li
firstElementOnSubcategoryDropDown = [xpath]://*[@id="sub-category-select-input-listbox"]/li[1]
secondElementOnSubcategoryDropDown = [xpath]://*[@id="sub-category-select-input-listbox"]/li[2]
customCampaignUrlText = [xpath]:(//*[@id="dui-container"]//*[contains(@class,"campaign-input-label")])[4]
customCampaignUrl = [xpath]://*[@id="campaign-custom-url-id"]
previewButton = [xpath]:(//*[@id="dui-container"]//button)[3]
accampaignpreviewButton = [xpath]:(//*[@id="dui-container"]//button)[2]
duppreviewButton = [xpath]:(//*[@id="dui-container"]//button)[2]
currentDateOnCalender = [xpath]://*[contains(@class,'CalendarMonth_table')]//tr//td[contains(@class,'CalendarDay__highlighted')]
monthKeyCurrent = [css] : div[class*=DayPicker_transitionContainer] div:nth-child(2) div div div div button
endDateDialogRightArrow = [css]:div[class*=DayPickerNavigation] div:nth-child(2) button
campaignurlerrormsg = [css]:#campaign-custom-url-id-helper-text > *:nth-child(2)
subcategoryvaluetext = [css]:#sub-category-select-input > *
daysOnCurrentMonthKey=[css]:div[class*=DayPicker_transitionContainer] div:nth-child(2) tbody tr td[class*=CalendarDay]
todayButton = [css]:#button
Duration = [xpath]:((//div[contains(@class,'dui-updated-ui-new-campaign')])[2]//label[contains(@class,'title-font')])[2]
toastNotification = [xpath]://*[@id="dui-app-scroll"]/div[4]/div/div
headerdismiss = [xpath]://div[contains(@class,'notification-actions')]/*
satisfactionRatingTextbox = [id]:question-name-id
calculateAudience  = [xpath]://*[@id="dui-container"]//*[contains(@class,'potential-audience-wrapper')]//span
additionalquestions = [xpath]:((//div[contains(@class,'dui-updated-ui-new-campaign')])[2]//label[contains(@class,'title-font')])[5]
addQuestionsLink = [css]:[class*=add-ques] label
welcomegreeting = [css]:((//div[contains(@class,'dui-updated-ui-new-campaign')])[2]//*[contains(@class,'title-font')])[4]
requiredusersatisfaction = [css]:((//div[contains(@class,'dui-updated-ui-new-campaign')])[2]//label[contains(@class,'title-font')])[4]
secondtypeDropDown = [xpath]:(//*[contains(@class,'new-campaign')]//*[contains(@id,'question-list-select')])[1]
thirdtypeDropDown = [xpath]:(//*[contains(@class,'new-campaign')]//*[contains(@id,'question-list-select')])[2]
fourthtypeDropDown = [xpath]:(//*[contains(@class,'new-campaign')]//*[contains(@id,'question-list-select')])[3]
firstquestionlabel = [css]:[class*='new-campaign'] [id*=question-label]
secondquestionlabel = [css]:[class*='new-campaign'] [id*=question-label][name*='2']
thirdquestionlabel = [css]:[class*='new-campaign'] [id*=question-label][name*='3']
fourthquestionlabel = [css]:[class*='new-campaign'] [id*=question-label][name*='4']
firstElementOnTypeDropDown = [css]:[id*='question-list'] [role*=option]:nth-child(1)
secondElementOnTypeDropDown = [css]:[id*='question-list'] [role*=option]:nth-child(2)
thirdElementOnTypeDropDown = [css]:[id*='question-list'] [role*=option]:nth-child(3)
fourthElementOnTypeDropDown = [css]:[id*='question-list'] [role*=option]:nth-child(4)
multifirstoption = [css]:[class*='new-campaign'] [id=answer-option-id-1][name*='0']
multisecondoption = [css]:[class*='new-campaign'] [id=answer-option-id-1][name*='1']
multithirdoption = [css]:[class*='new-campaign'] [id=answer-option-id-1][name*='2']
singlefirstoption = [css]:[class*='new-campaign'] [id=answer-option-id][name*='0']
singlesecondoption = [css]:[class*='new-campaign'] [id=answer-option-id][name*='1']
singlethirdoption = [css]:[class*='new-campaign'] [id=answer-option-id][name*='2']
optioncheckboxes = [css]:[class*='pull-right new-campaign-question-input css-xm5md6']:first-child
nameList = [xpath]://*[@id="extended-campaignList"]//tbody/tr/td[2]
firstcampaignlist [xpath]:(//a[contains(@class,'dui-hyperlink')])[1]
previewsurveylinkerrormessage = [xpath]://*[@id='campaign-custom-url-id-helper-text']/*[last()]
noDataAvailableText = [css]:[class*=no-data]
exportButton = [css]:[class*=detail-page-header] button:nth-child(2)
notificationBellIcon  = [xpath]://*[contains(@class,'notification-center-content')]//button
downloadlink = [xpath]:(//div[contains(@class,'welcome-popup-model')]/following-sibling::div//ul/*[@role='menuitem'])[last()-1]
latestNotification = [xpath]:((//*[contains(@id,'dui-notifications')]//div)[1]//li[1]//span)[3]
hamburgerMenuOnNotification = [xpath]:(//*[contains(@id, 'notifications')]//button//span)[1]
toastNotification = [xpath]://*[@id="dui-app-scroll"]/div[4]/div/div
closeToastNotification = [xpath]://div[@id="dui-app-scroll"]/div[4]/div/button
notificationButton =[css]:[class*=vertical-center] button:nth-child(2)
downloadCampaignReport =[css]:[data-popper-placement="bottom-end"] ul li[data-value="DOWNLOAD"]
firstNotification = [xpath]://*[@id='dui-notifications']//ul//li[2]
hamburgerMenuOnNotification = [xpath]://*[@id='dui-notifications']//ul//li[1]//button
nameSearchBox = [xpath]://input[@id="name"]
tableOverLay = [xpath]://div[@class='vn-table__overlay']
firstCompanyOnDropDown = [xpath]:(//*[contains(@class,'options-list')]//a)[1]
categoryDropDownForMSP = [id]:category-select-input
subcategoryDropDownMSP = [id]:sub-category-select-input
filtercriteria1valuedd = [xpath]:((//*[@id='dui-container']//div[contains(@class,'criteria-header')])/..//div[contains(@class,'value-dropdown')]//div)[3]
filtercriteria2valuedd = [xpath]:((//*[@id='dui-container']//div[contains(@class,'criteria-header')])/..//div[contains(@class,'value-dropdown')]//div)[6]
endDatePickerForCampaignUpdate = [css]:[class*=form-field] [class*=datepicker] svg:nth-child(3)
calendarPopup = [css]:div ul[class*=datepicker__calendar]
categoryDropDownOptions = [css]:#category-select-input-listbox>li
firstDeviceInList = [xpath]://div[@id="extended-2"]//tr/td[2]/a
deviceDetailsSection = [css]:[class=campaign-tech-pules-graph-panel]
descriptionhelpertext = [css]:#campaign-description-down-id-helper-text > span:nth-child(2)
questionhelpertext = [css]:#question-name-id-helper-text > span:nth-child(2)
categoryDD = [xpath]:(//div[@id='category-select-input'])[1]
#company Logo
companyLogoTitle = [css]:div[class*=company-logo-label]
addCompanyLogoOnCompanySetting = [css]:div[class*=add-company-logo]
logopresent=[xpath]://div[@class='add-company-logo-img']//div/*
showCompanyLogoOnEndUserCheckboxText = [css]:div[class*=company-logo-checkbox] span:nth-child(2)
showCompanyLogoOnEndUserCheckbox = [css]:div[class*=company-logo-checkbox] span:nth-child(1) input
selectLogoImageIcon = [css]:[class*=summary-card-desc-icon] svg
selectLogoImage = [css]:#dui-summary-card [class*=profile-tile] [class*=image-container]
browseButton = [xpath]://*[@id="profile_photo_radio"]//div
selectImageRadioButtonOnPopup = [xpath]://*[@id="profile_photo_radio-file"]
saveButtonOnPopUp = [css]:[class*=profile-modal] button:nth-child(1)
logoImage = [xpath] : //*[@id="dui-container"]//img
okButtonFromPopUp = [xpath]:(//*[contains(@class,'modal--content')])[last()]//button[1]
youAreAboutToLeaveCampaignPagePopUpText = [xpath]:(//*[contains(@class,'modal--content')])[last()]//p
satisfactionQuestionGraph=[xpath]:(//div[contains(@class,'campaign-report-ques-panel')][1]//*[contains(@class,'highcharts-label highcharts-no')]/*[name()='text'])
singleSelectQuestionGraph = [xpath]:(//div[contains(@class,'campaign-report-ques-panel')][2]//*[contains(@class,'highcharts-label highcharts-no')]/*[name()='text'])
multiSelectQuestionGraph = [xpath]:(//div[contains(@class,'campaign-report-ques-panel')][3]//*[contains(@class,'highcharts-label highcharts-no')]/*[name()='text'])
starRatingQuestionGraph = [xpath]:(//div[contains(@class,'campaign-report-ques-panel')][4]//*[contains(@class,'highcharts-label highcharts-no')]/*[name()='text'])
satisfactionRatingWithDeviceHealth = [xpath]://*[@id="extended-2"]//*[contains(@class,'highcharts-label highcharts-no-')]//*[name()='text']
blankArea = [xpath]://html
reponsesPieChart= [css]:div[class*=highcharts-container] svg g:nth-child(2) text
