#Battery Replacement
batteryReplacementData = [css]:#dashboard-tile-bRep
batteryReplacementNoData = [css]:#batteryRepIncidentKpi0
batteryReplacementNoDataTitle = [css]:#batteryRepIncidentKpi0  div[class*='dashboard-error-title']
batteryReplacementNoDataDesc = [css]:#batteryRepIncidentKpi0  div[class*='description']
batteryReplacementDataTileCount = [css]:#batteryRepIncidentKpi0 div[class='kpi-widget-count']
batteryReplacementDataTileTitle = [css]:#batteryRepIncidentKpi0  div[class*='kpi-widget-title']
batteryReplacementViewDetailButton = [css]:#batteryRepIncidentKpi0 [type*='button']

#Healthy Disk
healthyDiskData = [css]:#dashboard-tile-dRep
healthyDiskNoData = [css]:#diskRepIncidentKpi0
healthyDiskNoDataTitle = [css]:#diskRepIncidentKpi0 div[class*='dashboard-error-title']
healthyDiskNoDataDesc = [css]:#diskRepIncidentKpi0 div[class*='description']
healthyDiskDataTileCount = [css]:#diskRepIncidentKpi0 div[class='kpi-widget-count'] 
healthyDiskDataTileTitle = [css]:#diskRepIncidentKpi0 div[class*='kpi-widget-title']
healthyDiskViewDetailButton = [css]:#diskRepIncidentKpi0 [type*='button']

#Disk Capacity
diskCpacityWidget = [id]:diskCapacityIncidentKpi0
diskCapacityData = [css]:#dashboard-tile-dCap
diskCapacityNoData = [css]:#diskCapacityIncidentKpi0
diskCapacityNoDataTitle = [css]:#diskCapacityIncidentKpi0 div[class*='nodata-title']
diskCapacityNoDataDesc = [css]:#diskCapacityIncidentKpi0 div[class*='description']
diskCapacityDataTileCount = [xpath]://div[@id='diskCapacityIncidentKpi0']//div[@class='kpi-widget-count']
diskCapacityDataTileTitle = [xpath]://div[@id='diskCapacityIncidentKpi0']//div[@class='kpi-widget-title']
diskCapacityViewDetailButton = [xpath]://div[@id = 'diskCapacityIncidentKpi0']//button

#Thermal Grading
thermalGradeWidget = [id]:thermalGradingIncidentKpi0
thermalGradingData = [css]:#dashboard-tile-tGra
thermalGradingNoData = [css]:#thermalGradingIncidentKpi0
thermalGradingNoDataTitle = [css]:#thermalGradingIncidentKpi0 div[class*='nodata-title']
thermalGradingNoDataDesc = [css]:#thermalGradingIncidentKpi0 div[class*='description']
thermalGradingDataTileCount = [xpath]://div[@id='thermalGradingIncidentKpi0']//div[@class='kpi-widget-count']
thermalGradingDataTileTitle = [xpath]://div[@id='thermalGradingIncidentKpi0']//div[@class='kpi-widget-title']
thermalGradingViewDetailButton = [xpath]://div[@id = 'thermalGradingIncidentKpi0']//button


tableColumnList = [xpath]://div[@id='reportGrid0']//thead//th
tableNoOfRows = [xpath]://div[@id = 'reportGrid0']//tbody//tr
tableCountOnFooter = [xpath]://div[@id = 'reportGrid0']//div[@role='menu']/following-sibling::span
insightSideBarCollapse = [xpath]://button[@aria-label = 'Collapse']