deviceTab = [xpath]:(//*[@id='menu_assets'])|(//*[@id='menu_devices'])
deviceTitle = [css]:h4.dui-app-bar-title
founddeviceinsearchresult = [xpath]://tr[contains(@class,'tablerow')]//a[contains(@href,'devices')][1]
submitcasebuttonid = [id]:show_add_incident
iframeIdOfSubmitcasePopUp = [id]:iframe_element
typeOfIncident = [xpath]://div[contains(@class,'incident-type')]/label/following-sibling::div[contains(@class,'dropdown')]
typeOfIncidentOption = [xpath]://div[contains(@class,'incident-type')]//li[contains(@class,'dropdown_options')]
subTypeOfIncident = [xpath]://div[contains(@class,'incident-subtype')]/label/following-sibling::div[contains(@class,'dropdown')]
subTypeOfIncidentOption = [xpath]://div[contains(@class,'incident-subtype')]//li[contains(@class,'dropdown_options')]
titleOfIncident = [id]:title
commentOfIncident = [id]:comment
submitcase = [id]:incident-submit
succesfullSubmitCase = [xpath]://*[@id="main-container"]/div/div/h4
incidentId = [xpath]://*[@id='main-container']/div/div/div[2]/div/p[1]
deviceListType = [xpath]://*[@id = "devices_list_wrapper"]//td[2]//i
deviceListTable = [xpath]://*[@id = "devices_list_wrapper"]//tr
devicesLink = [xpath]://a[contains(@class,'breadcrumb')]
warrantyField = [xpath]://*[@id = "device_overview"]//div[2]//tr[4]
warrantyFieldValue = [xpath]://*[@id = "device_overview"]//div[2]//tr[4]//td//span
warrantyTile = [xpath]://*[@data-tab = 'tab_support']
remainingWarranty = [xpath]://*[@id = "warranty_container"]//tr
allWarranties = [xpath]://*[@id = "warranty_container"]//tr//th[normalize-space(text())="Remaining Days"]
deviceList = [id]:devices_page
warrantyTitle = [xpath]://*[@id = "warranty_container"]//tr[2]//th
warranties = [xpath]://*[@id = "warranty_container"]//tr//td
doneButtonOfIncident = [xpath]://button[contains(@class,'done')]
cancelButton = [id]:incident-cancel
deviceSearchField = [id]:devices_list_search
deviceInTable = [xpath]://table[@id='devices_list']//tr[1]/td[3]//a
incidentIDColumnValue = [id]:#incidents_list>tbody>tr>td:nth-child(2)
incidentIdText = [xpath]://*[@id=\"incidents_list\"]/tbody/tr[1]/td[2]/span[2]
osValue = [xpath]://*[@id="device_overview"]/div/div[1]/table/tbody/tr[2]/td
bromiumIntegrationLabel = [xpath]://*[@id="device_overview"]/div/div[2]/table/tbody/tr[2]/th
hardwareTab = [xpath]://li[@data-tab="tab_hardware"]
deviceMfg = [xpath]://*[@id="device_overview"]/div/div[1]/table/tbody/tr[3]/td
biosVersion = [xpath]://*[@id="tab_hardware"]/table/tbody/tr[9]/th
incidentCreatedOn = [xpath]://table[@id='incidents_list']/tbody/tr[1]/td[4]
deviceType = [xpath]:(//div[@class='device-description']/p/span[@title])[1]
incidentIDInBottomTable = [xpath]:(//td[@class='hidden-phone sorting_1']/span/a[contains(@href,'/incidents/')])[1]
incidentPriorityInBottomTable = [xpath]:(//table[@id='incidents_list']/tbody/tr/td[1])[1]
incidentStatusInBottomTable = [xpath]://table[@id='incidents_list']/tbody/tr/td[2]/span[@class='sub-head']
successfullSubmitCaseIcon = [xpath]://div[@class='app_notification_page--icon']/*[contains(@class,'status-green')]
deviceUserName = [xpath]://div[@class='device-description']/p[4]/span
deviceVisibility = [xpath]://tr[1]/th[2]/div[1]
deviceNameSearchField = [xpath]://input[@id='devices-name'][@name='devices-name']
DeviceSerialNumber = [xpath]://tbody/tr[1]/td[2]//a[1]
FirstRowAfterSearch = [xpath]://table[contains(@class,'table__table')]/tbody//tr[1]
deviceAlias = [id]:devices-alias
tableOverlaySiteUp = [xpath]://div[contains(@class,'dui-tl')]//div[contains(@class,'table__overlay') and not (contains(@class,'loading')) and not (contains(@class,'spinner'))]