#Battery Replacement
batteryReplacementData = [css]:#dashboard-tile-bRep
batteryReplacementNoData = [css]:#batteryRepIncidentKpi0
batteryReplacementNoDataTitle = [css]:#batteryRepIncidentKpi0  div[class*='nodata-title']
batteryReplacementNoDataDesc = [css]:#batteryRepIncidentKpi0  div[class*='description']
batteryReplacementDataTileCount = [css]:#batteryRepIncidentKpi0 div[class='number-count'] span
batteryReplacementDataTileTitle = [css]:#batteryRepIncidentKpi0 div[class*='tile-title'] h4
batteryReplacementViewDetailButton = [css]:#batteryRepIncidentKpi0 [type*='button']


#Healthy Disk
healthyDiskData = [css]:#dashboard-tile-dRep
healthyDiskNoData = [css]:#diskRepIncidentKpi0
healthyDiskNoDataTitle = [css]:#diskRepIncidentKpi0 div[class*='nodata-title']
healthyDiskNoDataDesc = [css]:#diskRepIncidentKpi0 div[class*='description']
healthyDiskDataTileCount = [css]:#diskRepIncidentKpi0 div[class='number-count'] span
healthyDiskDataTileTitle = [css]:#diskRepIncidentKpi0 div[class*='tile-title'] h4
healthyDiskViewDetailButton = [css]:#diskRepIncidentKpi0 [type*='button']

#Disk Capacity
diskCapacityData = [css]:#dashboard-tile-dCap
diskCapacityNoData = [css]:#diskCapacityIncidentKpi0
diskCapacityNoDataTitle = [css]:#diskCapacityIncidentKpi0 div[class*='nodata-title']
diskCapacityNoDataDesc = [css]:#diskCapacityIncidentKpi0 div[class*='description']
diskCapacityDataTileCount = [css]:#diskCapacityIncidentKpi0 div[class='number-count'] span
diskCapacityDataTileTitle = [css]:#diskCapacityIncidentKpi0 div[class='tile-title'] h4
diskCapacityViewDetailButton = [css]:#diskCapacityIncidentKpi0 [type*='button']

#Thermal Grading
thermalGradingData = [css]:#dashboard-tile-tGra
thermalGradingNoData = [css]:#thermalGradingIncidentKpi0
thermalGradingNoDataTitle = [css]:#thermalGradingIncidentKpi0 div[class*='nodata-title']
thermalGradingNoDataDesc = [css]:#thermalGradingIncidentKpi0 div[class*='description']
thermalGradingDataTileCount = [css]:#thermalGradingIncidentKpi0 div[class='number-count'] span
thermalGradingDataTileTitle = [css]:#thermalGradingIncidentKpi0 div[class*='tile-title'] h4
thermalGradingViewDetailButton = [css]:#thermalGradingIncidentKpi0 [type*='button']


tableColumnList = [css]:tr[class*='tableheader__row'] th