
dicoverypagetitle = [id]:unlockUpgrades
Alertstab = [id]:menu_alertsListView
scriptstab = [id]:menu_scripts
Pulsestab = [id]:menu_pulses
Labstab = [id]:menu_labs

#Alrts page webelement

Alertsdiscoverypagetitle = [id]:alertsDiscoveryTitle
Alertsdiscoverypagesubtitle = [id]:alertsDiscoveryDescription

Alertsdicoverypagecard1image = [id]:alertsDiscoveryCard1Image
Alertsdicoverypagecard1title = [id]:alertsDiscoveryCard1Title
Alertsdicoverypagecard1description = [id]:alertsDiscoveryCard1Description

Alertsdicoverypagecard2image = [id]:alertsDiscoveryCard2Image
Alertsdicoverypagecard2title = [id]:alertsDiscoveryCard2Title
Alertsdicoverypagecard2description = [id]:alertsDiscoveryCard2Description

Alertsdicoverypagecard3image = [id]:alertsDiscoveryCard3Image
Alertsdicoverypagecard3title = [id]:alertsDiscoveryCard3Title
Alertsdicoverypagecarddescription = [id]:alertsDiscoveryCard3Description

learnmorebutton = [id]:alertsDiscoveryLearnMoreBtn

#Scripts page webelements
scriptsdiscoverypagetitle = [id]:scriptsDiscoveryTitle
scriptsdiscoverypagesubtitle = [id]:scriptsDiscoveryDescription

scriptsdicoverypagecard1image = [id]:scriptsDiscoveryCard1Image
scriptsdicoverypagecard1title = [id]:scriptsDiscoveryCard1Title
scriptsdicoverypagecard1description = [id]:scriptsDiscoveryCard1Description

scriptsdicoverypagecard2image = [id]:scriptsDiscoveryCard2Image
scriptsdicoverypagecard2title = [id]:scriptsDiscoveryCard2Title
scriptsdicoverypagecard2description = [id]:scriptsDiscoveryCard2Description

scriptsdicoverypagecard3image = [id]:scriptsDiscoveryCard3Image
scriptsdicoverypagecard3title = [id]:scriptsDiscoveryCard3Title
scriptsdicoverypagecarddescription = [id]:scriptsDiscoveryCard3Description

scriptslearnmorebutton = [id]:scriptsDiscoveryLearnMoreBtn

#Pulses page webelements
Pulsesdiscoverypagetitle = [id]:pulseDiscoveryTitle
Pulsesdiscoverypagesubtitle = [id]:pulseDiscoveryDescription

Pulsesdicoverypagecard1image = [id]:pulseDiscoveryCard1Image
Pulsesdicoverypagecard1title = [id]:pulseDiscoveryCard1Title
Pulsesdicoverypagecard1description = [id]:pulseDiscoveryCard1Description

Pulsesdicoverypagecard2image = [id]:pulseDiscoveryCard2Image
Pulsesdicoverypagecard2title = [id]:pulseDiscoveryCard2Title
Pulsesdicoverypagecard2description = [id]:pulseDiscoveryCard2Description

Pulsesdicoverypagecard3image = [id]:pulseDiscoveryCard3Image
Pulsesdicoverypagecard3title = [id]:pulseDiscoveryCard3Title
Pulsesdicoverypagecarddescription = [id]:pulseDiscoveryCard3Description

Pulseslearnmorebutton = [id]:pulseDiscoveryLearnMoreBtn

#Labs page webelements
Labsdiscoverypagetitle = [id]:labsDiscoveryTitle
Labsdiscoverypagesubtitle = [id]:labsDiscoveryDescription

Labsdicoverypagecard1image = [id]:labsDiscoveryCard1Image
Labsdicoverypagecard1title = [id]:labsDiscoveryCard1Title
Labsdicoverypagecard1description = [id]:labsDiscoveryCard1Description

Labsdicoverypagecard2image = [id]:labsDiscoveryCard2Image
Labsdicoverypagecard2title = [id]:labsDiscoveryCard2Title
Labsdicoverypagecard2description = [id]:labsDiscoveryCard2Description

Labsdicoverypagecard3image = [id]:labsDiscoveryCard3Image
Labsdicoverypagecard3title = [id]:labsDiscoveryCard3Title
Labsdicoverypagecarddescription = [id]:labsDiscoveryCard3Description

Labslearnmorebutton = [id]:labsDiscoveryLearnMoreBtn

#Standard plan dashboard sequence
experiencescorestandardplan = [xpath]:(//h2[@class='wexcard-header-title'])[1]
experienceovertimestandardplan = [xpath]:(//h2[@class='wexcard-header-title'])[2]
recommendedactionsliststandardplan = [id]:home-recommended-actions-list
fleetinventorystandardplan = [xpath]:(//h2[@class='wexcard-header-title'])[3]
appwithmostcrashesstandardplan = [xpath]:(//h2[@class='wexcard-header-title'])[4]
appwithmostcrashessampledatastandardplan = [xpath]://div[@class='progress-bar-widget-header-sample']
sampledatatooltip = [id]:sample_data_tooltip

#Pro/Elite plan dashboard sequence
experiencescoreProplan = [xpath]:(//h2[@class='wexcard-header-title'])[1]
experienceovertimeproplan = [xpath]:(//h2[@class='wexcard-header-title'])[2]
recommendedactionslistproplan = [id]:home-recommended-actions-list
fleetinventoryproplan = [xpath]:(//h2[@class='wexcard-header-title'])[3]
appwithmostcrashesproplan = [xpath]:(//h2[@class='wexcard-header-title'])[4]

#Starter plan dashboard sequence
Bannercontentheading = [xpath]://h6[@class='content-heading']
Bannercontentheadingdescription = [xpath]://p[@class='content-description']
hardwaresupportincident = [id]:hardware-support-incidents
fleetinventorywidget = [id]:fleet-inventory-label

