host = email-smtp.us-west-2.amazonaws.com
port = 587
smtp = smtp
starttls = true
starttlsReq = true
auth = true
debug = true
socketFactoryClass = javax.net.ssl.SSLSocketFactory
fallback = false
subject = Selenium Test Automation Execution Report For 
mailTo = 
sendEmail = false