emmToolTab = [id]:menu_emmToggle
chromeEnterpriseTab = [id]:menu_chrome
airwatchIntuneTab = [id]:menu_emmTools
emmToolClick = [xpath]://*[@id='menu_emmToggle']//*[contains(@class,"menu__item-col-toggle")]
emmToolSubTabPopUpHeader = [xpath]://*[@class="emm-modal"]//*[contains(@class,'modal__header')]/h4
selectCompanyDropdownButton = [xpath]://*[@id="mstelemetry-company-filter-parent"]//button
selectCompanyDropdown = [id]:mstelemetry-company-filter-parent
selectCompanySearch = [xpath]://*[@id="mstelemetry-company-filter"]//input
selectCompanyNoResultsMatched = [xpath]://*[@id="mstelemetry-company-filter"]//*[contains(@class,'no-results')]
EMMToolNotConfigured = [xpath]://*[@id="mstelemetry-company-filter"]/following::p
companyDropdownItems = [xpath]://*[@id='mstelemetry-company-filter']//*[contains(@role,'listbox')]
emmToolRestApiLabel = [xpath]://*[@class='emm-details']/p
emmToolRestApiUrlLabel = [xpath]://*[@class='emm-details']/p/span
emmToolBtnClick=[id]:emm-device
chromeEnterpriseBtn=[xpath]://a[contains(text(),'Google Chrome Enterprise')]
intuneBtn =[xpath]://a[contains(text(),'Microsoft Intune')]
airwatchBtn =[xpath]://a[contains(text(),'VMware Workspace ONE')]
emmModalDialog = [xpath]://div[contains(@class,'modal__dialog')]//h4
emmCloseButton= [xpath]://div[contains(@class,'modal__dialog')]//*[contains(@class,'modal__close')]
emmConfigureURL=[css]:div.emm-details span