# WEX Environment URL

#WEX(Workforce Experience Platform) Stable
Stable_USWEP = https://usdevms-workforce.hppipeline.com
Stable_EUWEP = https://eudevms-workforce.hppipeline.com

#WEX(Workforce Experience Platform) Staging
Staging_USWEP = https://usstagingms.workforceexperience.hp.com
Staging_EUWEP = https://eustagingms.workforceexperience.hp.com

#WEX(Workforce Experience Platform) Production
Prod_USWEP = https://workforceexperience.hp.com/ui/idplogin/
Prod_EUWEP = https://eu.workforceexperience.hp.com/ui/idplogin/


######################### Techpulse Environment Url ######################################
#LATEST
Latest = https://latest.lightaria.com/
Latest_status = http://status.lightaria.com/latest

#STABLE
StableUS = https://usdevms.daas.hppipeline.com/
StableUSSS = https://usdevms.catalyst.hppipeline.com/
StableUSADDROLEURL = https://usdev.daas.hppipeline.com/

StableEU = https://eudevms.daas.hppipeline.com/
StableEUSS = https://eudev.dev.hpicatalyst.com/
StableEUADDROLEURL = https://eudev.daas.hppipeline.com/

StableUS_status = http://status.lightaria.com/stable
StableEU_status = http://status.lightaria.com/eudev

#WORKFLOW_STABLE
Workflow_StableUS = https://stable.hpworkflows.com/

#PEM Testpemtest.lightaria.com
PEMUS = https://pemtest.lightaria.com/

#STAGING
StagingUS  = https://usstagingms.hpdaas.com/
StagingUSSS = https://usstagingms.prod.hpicatalyst.com/
StagingUSADDROLEURL  = https://usstaging.hpdaas.com/

StagingEU = https://eustagingms.hpdaas.com/
StagingEUSS = https://eustagingms.prod.hpicatalyst.com/
StagingEUADDROLEURL = https://eustaging.hpdaas.com/

StagingUS_status = http://status.lightaria.com/usstagingms
StagingEU_status = http://status.lightaria.com/eustagingms

#WORKFLOW_STAGING
Workflow_StagingUS = https://staging.hpworkflows.com/

#PRODUCTION
ProdUS = https://www.hpdaas.com/
ProdUSSS = https://usprodms.prod.hpicatalyst.com/
ProdUSADDROLEURL = https://usprod.hpdaas.com/

ProdEU = https://eu.hpdaas.com/
ProdEUSS = https://euprodms.prod.hpicatalyst.com/
ProdEUADDROLEURL = https://euprod.hpdaas.com/

ProdUS_status = http://status.lightaria.com/usprodms
ProdEU_status = http://status.lightaria.com/euprodms

#WORKFLOW_PRODUCTION
Workflow_ProdUS = https://www.hpworkflows.com/
 
#HPID
HpId_Staging = https://myaccount.stg.cd.id.hp.com/uaa
HpId_Prod = https://myaccount.id.hp.com/uaa

#Performance
Perf_Environment = https://usperfms.daas.hppipeline.com/

Pentest_Environment = https://uspentestms.daas.hppipeline.com/
ProactiveInsights = Proactive Insights
Connect = Connect
WolfProtectTrace = Wolf Protect & Trace
ActiveCare = Active Care


#WEX(Workforce Experience Platform) Ldk_Production
LDKProd_WEP = https://workforceexperience.hp.com/ui/idplogin/

#WEX(Workforce Experience Platform) Veneer upgrade Environment
Veneer_USWEP = https://ustestms.workforceexperience.hp.com

#WEX(Workforce Experience Platform) Performance Environment
Perf_USWEP = https://usperfms-workforce.hppipeline.com/ui/idplogin