PRODUCTION_TEST_COMPANY = Automation company - DoNotDelete
LHADMIN_PORTAL_URL = https://admin.hpdaas.com/
WINDOWSSOFTWAREJSONDATA = https://dcefh8tp1pusz.cloudfront.net/PROD/%7bE5FB98E0-0784-44F0-8CEC-95CD4690C43F%7d/Archive/versioncatalog.json
MACSOFTWAREJSONDATA = 	  http://downloads.hpdaas.com/production/macos/APMAgentAppcast.xml
ANDROIDSOFTWAREDATA = https://play.google.com/store/apps/details?id=com.hp.apmagent
DEVICE_IMPORT_COMPANY = Automation Company-Do Not Delete
IMPORT_DEVICE_COMPANY_CSV = Automation Company-Do Not Delete
STATIC_COMPANY = Automation Company-Do not Delete
ASSIGNED_PARTNER_NAME =  Reseller Sales Admin
ASSIGNED_PARTNER_NAME_EMAIL = Reseller Sales Admin
CAMPAIGN_COMPANY = Automation company - DoNotDelete
INVITED_ADDUSER_EMAIL_SUBJECT = HP Active Care Service Activation
APP_NAME = HP Insights