ROLE_ID_URL = https://eudev.daas.hppipeline.com/
ASSIGNED_PARTNER_NAME = PartnerAutoReseller
PARTNER_ID = partnerautoresellerdonotdelete
CUSTOMER_ID = C-bergXPRh
DEVICE_NAME_SUBSCRIPTION = AutomationDevice0
COMPANY_NAME = PartnerAutoCompany - DoNotDelete
COMPANY_NAME_EMAIL = PartnerAutoCompany DoNotDelete
COMPANY_COUNTRY = India
ASSIGNED_PARTNER_NAME_EMAIL = PartnerAutoReseller DoNotDelete
TEST_USER = eustable@hpmsqa.mailinator.com
IDENTITY_USER = EUStable DoNotDelete
ROLE_USER = EUStable DoNotDelete
USER_IMPORT_COMPANY = EUStableCompany
MULTI_SUBS_COMP = February15
ZTE_DEVICE_SNR = 5WH81659SD
MSP_EMAIL = supportteamautomspdonotdelete
DAAS_API_BASE_URL_AUTH = https://eudev.daas.hppipeline.com/
DAAS_API_BASE_URL = https://eudevms.daas.hppipeline.com/
PARTNER_EMAIL_NOTIFICATION_EMAIL=hptpm.multipass.cc.supportmail

#MEM
AZURE_EMAIL_ID = vijayk@vividemmdev.onmicrosoft.com
AZURE_PASSWORD = N0P3eking
MSP_ID_AZURE = 58f2a35c-afb4-49cf-a6fd-433743e8ff9f
PARTNER_ID_AZURE = 81b46eaa-a379-46c6-9c97-606588cf4544
MEM_URL = https://usdevms.daas.hppipeline.com/ui/view/devices
USER_NAME = Vijay!
MEM_COUNTRY = United States
MEM_CITY = Testcity

#subscription contract
ADD_COMPANY_THROUGH_ROOT_COUNTRY_CONTRACT = Albania
CURRENCY_CONTRACT = ALL
PARTNER_COUNTRY_CONTRACT = Denmark

PBM_EMAIL_SUBJECT = LOE 4 Partner Contract Setup is complete
PBM_MANGER_EMAIL_SUBJECT = LOE 4 Partner Contract Setup
VIEW_CAMPAIGN_URL = https://hpdx-monitoring.demo.nexthink.cloud/
HP_DEX_USERNAME = hpadmin
HP_DEX_PASSWORD = HPDX@2021
HP_DEX_ACCOUNT_URL = https://hpdx-monitoring.demo.nexthink.cloud
HP_DEX_ENGINE_URL = https://hpdx-monitoring.demo.nexthink.cloud

MultiPlanCOMPANY = eulicense_activeplan@yopmail.com
MULTIPLAN_ORDERS = multiPlanOrdersEU.csv

#FLIP
FLIP_COMPANY = FlipEUAutomation
VIRTUAL_AGENT = https://virtualagent.hpcloud.hp.com/?botclient=hpc&BotSubClient=hpdaas&Template=hpdaas&query=&SerialNumber=&P%E2%80%8CL=&ProductNumber=&ProductName=&ProductNameOID=&ProductSeriesName=&ProductSeriesNameOID=&CC=us&LC=en

BORN_ON_DATE_DEVICEID = LKgRKTTplHUORyEh9gN_JNB_Nh7JMvBIJUHRpW9jyY8
DeviceName_BornOnDate = 5CD9270V4B
TenantID_BornOnDate = 	f036a663-83d7-4a67-b992-cb6b9ac70e0c

#ITSM
ITSMCompanyName = TestAccountcd3b6f6f
CompanyNameForEditITSM = AutomationCOmpany


#Logs Message
IMPORT_COUNT_DESCRIPTION_LOG_MESSAGE = 1 number of device imported
LEVEL_LOG_VALUE= Information
TYPE_LOG_VALUE= Devices
IMPORT_SUBTYPE_LOG_VALUE= Import
ADD_DESCRIPTION_LOG__MESSAGE =CND13563YH added under holding tank
ADD_SUBTYPE_LOG_VALUE= Add
DELETE_DESCRIPTION_LOG_MESSAGE= 5CG725O1234 deleted from HP TechPulse Active Care
DELETE_SUBTYPE_LOG_VALUE= Delete
ERROR_DESCRIPTION_LOG_MESSAGE= 5CG791011138 failed due to FCPKServiceStartDate is required for serial no.: 5CG791011138 at record: 6
ERROR_LEVEL_LOG_VALUE= Error
BIOS_POLICY_REMOVE_DESCRIPTION_LOG_MESSAGE = BIOS Policy Removed.
BIOS_SUBTYPE_LOG_VALUE= BIOS
BIOS_POLICY_APPLIED_DESCRIPTION_LOG_MESSAGE = BIOS Policy Applied.
EMM_ADD_DESCRIPTION_LOG_MESSAGE = MEM Integration has been added successfully.
EMM_REMOVE_DESCRIPTION_LOG_MESSAGE = MEM Integration has been removed successfully.
EMM_TYPE_LOG_VALUE= EMM Provider
REMOVE_SUBTYPE_LOG_VALUE= Remove

#Incident ID
INCIDENT_ID_ACTIVE_CARE_POWER = 3d8
INCIDENT_ID_INVALID_TYPE      = fd2654
INCIDENT_ID_NON_HP_DEVICE     = fd25bc
INCIDENT_ID_PRE_EXISTING_CASE = fd269b
DEVICE_SERIAL_NO              = 5THGDFLOGS2


#Existing Device Order
EXISTING_DEVICE = startDateEndDateEU.csv

#Existing Pending Enrollment Device
PENDING_ENROLL_EXISTING_DEVICE = verifyUpdateStartDatePendingEnrollmentEU.csv

#OrdersMAndatory
ORDERS_MANDATORY = ordersMandatoryEU.csv

#OrdersInvalid
ORDERS_INVALID = ordersEUInvalid.csv

#OrdersAddTocustomer
ORDERS_ADDTOCUSTOMERTENANT_COLUMN = orderAddCustomerTenantEU.csv

#OrdersLessThan255
ORDERS_LESS_THAN_255 = ORDERS_LESS_THAN_255_EU.csv

#OrdersGreaterThan255
ORDERS_GREATER_THAN_255 = ORDERS_GREATER_THAN_255_EU.csv

#Active Care
IOTDiscoveryURL = https://dev-discovery.daas.hppipeline.com/v2/services


#CSDP_TEST_PARTNER_NAME
PARTNER_DETAILS_CSDP_TEST_USER = testpartnercsdp2023
VALID_CRS_ID = 0500141343
CSDP_PARTNER_EMAIL=testpartnercsdp2023@yopmail.com

