PULSE_FILTERS_LASTLOGGED_FILTER_VALUE = chromebook14g4@salesdemo-edu-hp.info
PULSE_FILTERS_FIELD_DEVICE_TYPE_VALUE = Notebook

WEX_ACTIVE_CUSTOMER_NAME = WEPAutomationActiveCustomer-
WEXCOMPANY_ACTIVE = WEPAutomationNewActiveCustomer-
PENDING_INVITE_CUSTOMER_NAME = WEPAutomationPendingInviteCustomer-
PENDING_REQUEST_CUSTOMER = WEPAutomationPendingRequestCustomer
ACTIVE_CUSTOMER_NAME = DeviceListPageTest
PENDING_REQUEST_CUSTOMER_NAME = automationpendingrequestcustomer
CATALOG_CUSTOMER1_NAME = EU WEP Automation Stage
HAS_LOCATION_CUSTOMER_NAME = AutoPartnerActiveCustomer DND
Pending_Invite_Customer = AutomationPendingInviteCustomer2
UPDATE_LOCATION_CUSTOMER = compeustageadminxsneha14aug
CATALOG_CUSTOMER1_TENANTID = 987708e4-231b-488d-87b1-e7002493ed5f
CATALOG_CUSTOMER2_NAME = WEPAutomationCustomer Stage
CATALOG_CUSTOMER2_TENANTID = 4b76634d-2862-446d-a801-57fec273ab4e
CUSTOMER_NAME_ASSET = AccountAutomationCustomer

INVITED_USER_EMAIL_SUBJECT = invites you to the Workforce Experience Platform (WXP)!
WEX_USER_EMAIL_SEARCH = inviteuser12invitenpg@hpmsqa.mailinator
USER_FN = inviteuser15
USER_LN = invite
COMPANY_FULLNAME = EU WEP Automation Stage
COMPANY_NAME = AccountAutomationCustomer
CUSTOMER_NAME = AccountAutomationCustomer
INVITE_CUSTOMER_EMAIL_WEP = uiautomationinviteita

#Devices regression Data
VIRTUAL_MACHINE_SERIAL_NUMBER = 0000-0009-2241-5187-9387-6607-02
TEST_DEVICE_SERIAL_NUM = 0002770YDL
WPT_TEST_DEVICE_SERIAL_NUM = 0002770YDL
PARTNER_COMPANY_TO_SELECT = WEXMSP-1000

# IOT Device Enrollment JSON
IOTDiscoveryURL = https://staging-discovery.hpdaas.com/v2/services
IOT_ENROLL_DEVICE = IOTEnrollDevice.json

# Scripts enrollment data
SCRIPTS_COMPANY_NAME = AccountAutomationCustomer
SCRIPTS_CPIN = fX8egV5K
SCRIPTS_COMPANY_EMAIL = euwepautomationstage@workforceqa.ext.hp.com
SCRIPTS_SERIAL_NO = DYNGRPAUTOMATION2652
SCRIPTS_DEVICE_ID = qPSd31eas2cI3TRWoAr7TjX0kTr4q1DwUp0fvVKbYFw
SCRIPTS_TENANT_ID = 987708e4-231b-488d-87b1-e7002493ed5f
IOT_JOB_ID = 6530
AWS_ROLE_ARN = arn:aws:iam::614310738423:role/wxp-qa-iot-automation
AWS_EXTERNAL_ID = 123e4567-e89b-12d3-a456-426614174000
TEST_DEVICE_SERIAL_NUM = 0002770YDL

MSP_ID = mspauto
PULSE_ENTRAID_GROUP_VALUE = Engineering US-STAGE SW_ORG
WEX_COMPANY_NAME = wexautoprodcustomer
WEX_COMPANY_FN = wexocautostable
WEX_COMPANY_LN = customer
WEX_COMPANY_ADDRESS = 123, xyz street
WEX_COMPANY_CITY = Hyderabad
WEX_COMPANY_ZIPCODE = 500081
WEX_COMPANY_STATE = Telangana
WEX_PHONE_NO = 12345
ROLE1 = IT Admin
ROLE2 = Connector Admin
ROLE3 = Lost Device Admin
PARTNER_NAME = Eustagewfcpartnernew
MSP_NAME = EUMSPSTAG
PULSE_FILTERS_LASTLOGGED_FILTER_VALUE = HPAUTO54155376@hp.com
PULSE_FILTERS_SERIAL_NUMBER_VALUE = HPDYNGRPTEST2652
PULSE_FILTERS_FIELD_DEVICE_MANUFACTURER_VALUE = HP
PULSE_FILTERS_FIELD_OPERATING_SYSTEM_VALUE = Microsoft Windows 10 Pro
PULSE_FILTERS_FIELD_DEVICE_TYPE_VALUE = Notebook
WEX_OLD_PULSES_LIST_URL = https://eustagingms.workforceexperience.hp.com/ui/employee-engagement/pulses
WEX_NEW_PULSES_LIST_URL = https://eustagingms.workforceexperience.hp.com/ui/view/pulses
WEX_OLD_PULSES_CREATION_CONTENT = https://eustagingms.workforceexperience.hp.com/ui/view/pulses/create/custompulse/tab-content
WEX_OLD_PULSES_CREATION_SCHEDULE = https://eustagingms.workforceexperience.hp.com/ui/view/pulses/create/custompulse/tab-schedule
WEX_OLD_PULSES_CREATION_AUDIENCE = https://eustagingms.workforceexperience.hp.com/ui/view/pulses/create/custompulse/tab-audience
WEX_NEW_PULSES_CREATION_CONTENT = https://eustagingms.workforceexperience.hp.com/ui/view/pulses/create/custompulse/content
WEX_NEW_PULSES_CREATION_SCHEDULE = https://eustagingms.workforceexperience.hp.com/ui/view/pulses/create/custompulse/schedule
WEX_NEW_PULSES_CREATION_AUDIENCE = https://eustagingms.workforceexperience.hp.com/ui/view/pulses/create/custompulse/audience
WEX_OLD_PULSES_CREATION_SENTIMENT_CONTENT = https://eustagingms.workforceexperience.hp.com/ui/view/pulses/createSentimentPulse/tab-content
WEX_OLD_PULSES_CREATION_SENTIMENT_SCHEDULE = https://eustagingms.workforceexperience.hp.com/ui/view/pulses/createSentimentPulse/tab-schedule
WEX_OLD_PULSES_CREATION_SENTIMENT_AUDIENCE = https://eustagingms.workforceexperience.hp.com/ui/view/pulses/createSentimentPulse/tab-audience
WEX_NEW_PULSES_CREATION_SENTIMENT_CONTENT = https://eustagingms.workforceexperience.hp.com/ui/view/pulses/create/sentimentpulse/content
WEX_NEW_PULSES_CREATION_SENTIMENT_SCHEDULE = https://eustagingms.workforceexperience.hp.com/ui/view/pulses/create/sentimentpulse/schedule
WEX_NEW_PULSES_CREATION_SENTIMENT_AUDIENCE = https://eustagingms.workforceexperience.hp.com/ui/view/pulses/create/sentimentpulse/audience
WEX_NEW_EE_DASHBOARD_REPORT_NEW = https://eustagingms.workforceexperience.hp.com/ui/view/analytics/dashboard/6777497d9088ff3bbfc86bab
WEX_NEW_PULSES_RESULTS = https://eustagingms.workforceexperience.hp.com/ui/view/pulses
PARTNER_FULLNAME2 = euwexautomation stagepartner
WEX_NEW_EE_DASHBOARD_OLD = https://eustagingms.workforceexperience.hp.com/ui/employee-engagement/dashboard
WEX_NEW_EE_DASHBOARD_NEW = https://eustagingms.workforceexperience.hp.com/ui/view/analytics/dashboard
WEX_NEW_EE_DASHBOARD_REPORT_NEW = https://eustagingms.workforceexperience.hp.com/ui/view/analytics/employee-engagement

EntraID_GroupName = Automation testing pulse engg grp - dont delete the grp
Membership_Type = Entra ID
Operating_Systems = Windows, Mac
Selected_GroupName = Automation testing pulse engg grp - dont delete the grp
Selected_Member_Devices = 1
ImportedGroupName = Automation Testing Pulse
Device_Count_OverviewTab = 1
Device_Name_MembershipTab = DESKTOP-6G1OKB6
EntraID_ErrorMessage = Field is required

# Groups
Groups_FILTERS_SERIAL_NUMBER_VALUE = 5CG73732FH
Groups_FILTERS_DEVICE_NAME_VALUE = DESKTOP-MUJR4GG
Groups_FILTERS_MANUFACTURER_VALUE = HP
Groups_FILTERS_OPERATING_SYSTEM_VALUE = Microsoft Windows 10 Pro
Groups_FILTERS_DEVICE_MODEL_VALUE = HP ZBook 14u G4
WEX_ASSIGNMTN_LIST_POLICY_URL = https://eustagingms.workforceexperience.hp.com/ui/view/remediations/pc-policies
WEX_ASSIGNMTN_LIST_SCRIPTS_URL = https://eustagingms.workforceexperience.hp.com/ui/view/remediations/scripts/assignments


#CRON job end points
hostURL = http://internal.eustaging.hpdaas.com
hostEnviroment = eustagingms
cronJobEndPointToProcessOrders=/services/carepack-service/internal/1.0/cronjob/process-new-orders
cronJobEndPointToMakeSNREntry=/services/ccc-snr/internal/1.0/snr
cronJobEndPointToDeleteSNREntry=/services/ccc-snr/internal/1.0/serialNo/

WPT_DEVICE_SERIALNUMBER= 9CG47702W7
USER_INVITE_FIRSTNAME=inviteuserfirst
USER_INVITE_LASTNAME=inviteuserlast
USER_INVITE_EMAIL=inviteusertest1@hpmsqa.mailinator.com
USER_RESEND_INVITE_EMAIL=pulsea1@hpmsqa.mailinator.com
WPT_SELECT_DOMAINS=gmail.com; workforceqa.ext.hp.com

#User Onboarding Details
TENANT_INIT = EU W

WEX_LEARN_MORE_URL = https://usstagingms.workforceexperience.hp.com/platform-overview/

#Policy Group creation device serial number
Groups_Device_serial_number = 0002770YDL
Groups_Device_Inactive_serial_number = HPDYNGRPTEST2652

#ActiveCare Users used in Device Transfer
ACTIVE_CARE_NAME_TENANT= DoNotDeleteActiveCareOnlyTenantEU
ACTIVE_CARE_PI_TENANT_ID=bc305f72-fd8e-43a7-b534-974daacc33a6
ACTIVE_CARE_NAME_TENANT_TN_DISPLAY_ID = C-RVy5whA7
ACTIVE_CARE_NAME_TENANT_CPIN = fX8egV5K
ACTIVE_CARE_PI_TENANT_CPIN= H5MUct4p
AC_PLUS_PI_NAME_TENANT=subodhactivecare21042025EU
AC_PLUS_PI_NAME_TENANT_TN_DISPLAY_ID=C-vC2gBU7y
AC_PLUS_PI_NAME_TENANT_CPIN=iXP26Huv
AC_PLUS_PI_NAME_TENANT_ID=090cf390-80cf-4254-8a77-9b957f138506
ACOnlyTenantName_EU = DoNotDeleteActiveCareOnlyTenantEU
INVALID_TENANT= InvalidTenantEU
INVALID_TENANT_TN_DISPLAY_ID = 101010
ACOnlyTenantName_US = DoNotDeleteActiveCareOnlyTenantEU
ACOnlyTenantId_US = a5dc0908-6f92-4df6-a9c4-39ca9b9238ce
optional-pc-refactor = PCE_CAMS_DATA
PlanId_RemoteCare = 8fc9e078-e8a8-4d39-b425-40d2d38ab41e
PlanId_ActiveCare = 61b196c4-3f37-435c-ad17-62b77744fd82
deviceReportLambdaEndPointUrl=https://internal-eustaging-api.hpdaas.com