EntraID_GroupName = Automation testing pulse engg grp - dont delete the grp
Membership_Type = Entra ID
Operating_Systems = Windows, Mac
Selected_GroupName = Automation testing pulse engg grp - dont delete the grp
Selected_Member_Devices = 1
ImportedGroupName = Automation Testing Pulse
Device_Count_OverviewTab = 1
Device_Name_MembershipTab = DESKTOP-6G1OKB6
EntraID_ErrorMessage = Field is required

#CRON job end points
cronJobEndPointToProcessOrders=/services/carepack-service/internal/1.0/cronjob/process-new-orders
cronJobEndPointToMakeSNREntry=/services/ccc-snr/internal/1.0/snr
cronJobEndPointToDeleteSNREntry=/services/ccc-snr/internal/1.0/serialNo/

WEX_LEARN_MORE_URL = https://usstagingms.workforceexperience.hp.com/platform-overview/

deviceReportLambdaEndPointUrl=https://internal-api.eudev.daas.hppipeline.com
hostURL=http://internal.eudev.daas.hppipeline.com
hostEnviroment=eudevms
INVALID_TENANT= InvalidTenantEU