gmailEmail = [xpath]://input[@type='email']
gmailNext = [xpath]://div[@id='identifierNext']
gmailPassword = [xpath]://input[@type='password']
GmailPassNext = [xpath]://div[@id='passwordNext']
fbEmail = [xpath]://input[@id='email']
fbPassword = [xpath]://input[@id='pass']
fbLogin = [xpath]://button[@id='loginbutton']
