hpDexTab = [id]:menu_experienceManagement
digitalExpUsername  = [xpath]://*[@id='LS_username_input']
digitalExpPassword  = [id]:LS_password_input
digitalLoginBtn = [id]:LS_login_button
hpDexLogo = [xpath]: //*[contains(@id,'global_container')]//li//img
hp-dex-pop-up-title = [xpath]://*[@id ='hpdx-noconfig-modal-label']
hp-dex-pop-up-desc1 = [xpath]://*[@id ='hpdx-noconfig-desc-title']
hp-dex-pop-up-desc2 = [xpath]://span[@id ='hpdx-noconfig-desc-message']

experianceManagementDashboard = [css]:#dui-container [class*=exp-management]
devicesByExperienceCard = [css]:#hpdxUserExperience [class*=experience-kpi-header] span[class*=title]
devicesByExperienceCardNoData = [xpath]:(//*[@id='hpdxUserExperience']//*[contains(@class,'message1')])[1]
digitalExpScoreOverTimeCard = [css]:#hpdxDETimeline [class*=highcharts-title]
digitalExpScoreOverTimeCardNoDta = [css]:#hpdxDETimeline div[class*=message1]
digitalExpeScoreByCategoryCard = [css]:#hpdxDECategory [class*=highcharts-title]
digitalExpeScoreByCategoryCardNoData = [css]:#hpdxDECategory div[class*=message1]
digitalExperienceOverviewCard = [css]:[class*=dashboard-section]:nth-child(1) span[class*=title]
digitalExperienceOverviewCardNoData = [xpath]:(//*[@id='hpdxDEOverview']//*[contains(@class, 'no-data-container-message1')])
overallScoreTitle = [xpath]:(//*[@id='hpdxDEOverview']//*[contains(@class, 'title')])[1]
enrolledDevicesTitle = [xpath]:(//*[@id='hpdxDEOverview']//*[contains(@class, 'title')])[2]
dataUpdatedField = [css]:#dui-container [class*=kpi-footer]
goodExperienceTitle = [xpath]:(//*[@id='hpdxUserExperience']//div[2]//*[contains(@class, 'title')])[1]
averageExperienceTitle = [xpath]:(//*[@id='hpdxUserExperience']//div[2]//*[contains(@class, 'title')])[2]
badExperienceTitle = [xpath]:(//*[@id='hpdxUserExperience']//div[2]//*[contains(@class, 'title')])[3]
addCampaignButton = [id]:hpdxAddButton
viewCampaignListButton = [id]:hpdxListButton

#PIXM 2.0
summaryTab=[xpath]://div[@aria-label='Tab Navigation']//span
viewFinder=[xpath]://button[@id='hpdxAddButton']
frustatingExperience=[xpath]://div[normalize-space()='Frustrating Experience']
pixmNoConfigtab= [id]:hpdx-noconfig-desc-message
pixmNoConfigtabCancelbutton= [id]:cancel-hpdx