hpDexTab = [id]:menu_hpdx
digitalExpUsername  = [xpath]://*[@id='LS_username_input']
digitalExpPassword  = [id]:LS_password_input
digitalLoginBtn = [id]:LS_login_button
hpDexLogo = [xpath]: //*[contains(@id,'global_container')]//li//img
hp-dex-pop-up-title = [xpath]://*[contains(@class,'hpdx-modal')]//h4
hp-dex-pop-up-desc1 = [xpath]://*[contains(@class,'hpdx-modal')]//p
hp-dex-pop-up-desc2 = [xpath]://*[contains(@class,'hpdx-modal')]//span