hpidProfileTitle = [xpath]://div[@id='root']//h4
menu = [xpath]://div[@id='root']//div[contains(@class,'menu')]
logoutIcon = [css]:.logout-part-wrapper svg
signOut = [xpath]://div[@class='sign-out']//div[contains(@class,'sign-out-clickable')]
editAddress = [xpath]://div[@id='accountInfo']//ul/li[6]/div[contains(@class,'edit')]//*[name()='svg']
editLink = [css]:.address-edit-modal.editAdressBtn
selectCountry = [classname]:vn-dropdown__title-text
selectType = [xpath]://div[@id='typeField-id']/div[@class='vn-dropdown']
selectTypeSelected = [xpath]://div[@id='typeField-id']/div/div[2]/ul/li[2]/a
selectRoleSelected = [xpath]://a[contains(@class, 'vn-dropdown__title-text') and text() ="Billing"]
selectRole = [xpath]://a[contains(@class, 'vn-dropdown_options__option-link') and text() ="Billing"]
hpidState = [css]:#state
hpidCity = [id]:city
hpidAddressLine1 = [css]:#addressLine1
hpidAddressLine2 = [css]:#addressLine2
hpidPostalCode = [id]:postalCode
selectOK = [xpath]://button[contains(@id, 'primary-id') and text() = 'OK']
myAccountLink = [xpath]://a[@class='vn-breadcrumb__link']
userStateDaaS = user_address_state_show
userCityDaaS = user_address_city_show
userCountryDaaS = user_address_country_show
userAddressLine1DaaS = user_address_street_line1_show
userAddressLine2DaaS = user_address_street_line2_show
userPostalCodeDaaS = user_address_postal_code_show
hpidFirstName = [xpath]://div[@id='personalInfo']//ul/li[2]/div[1]/div[2]
hpidLastName = [xpath]://div[@id='personalInfo']//ul/li[4]/div[1]/div[2]
hpidEmail = [xpath]://div[@id='accountInfo']//ul/li[2]/div[1]/div[2]
hpidCountry = [xpath]://div[@id='countryField-id']//div[contains(@class,'title')]/a
editFirstNameIcon = [xpath]://div[@id='personalInfo']//ul/li[2]/div[contains(@class,'edit')]//*[name()='svg']
editLastNameIcon = [xpath]://div[@id='personalInfo']//ul/li[4]/div[contains(@class,'edit')]//*[name()='svg']
name = [css]:#name
languageLable = [xpath]://label[@for='user_settings_language']
HPIDLanguage = [xpath]://div[@id='personalInfo']//ul/li[7]/div[1]/div[2]