incidentTab = [id]:menu_incidents
incidentTitle = [css]:#dui-breadcrumbs li
incidentTitleOnBreadcrumbs = [css]:#incidentList li
clearAllIncidentSearch = [css]:button[title='Clear']
table = [css]:div.page_list__section.page_list__item-lists
allCheckBoxOfPage = [css]:table>tbody>tr input.vn-checkbox
listOfColumnsOnTable = [css]:th[class*='cell-title']>div:nth-of-type(1)
filterBoxesOfTable = [css]:tr:nth-of-type(2)>th.vn-tableheader__cell
generateXlsButton = [id]:export_exl
selectAllCheckBox = [xpath]://*[@name="SelectAllPage"]
allLogoOfPage = [css]:tbody td:nth-child(1)
firstIdCheckBox = [css]:tbody div[class*='checkbox'] span
firstIdLogo = [css]:tbody>tr:nth-of-type(1) div[class*='avatar']
firstIdAssignTo = [css]:tr:nth-of-type(1) td[headers*=col-id-assigneeDetails] div div[class*=content]
firstIdCompany = [css]:tbody>tr:nth-of-type(1)>td:nth-of-type(10)>div>div
firstIdDeviceName = [css]:table>tbody>tr:nth-of-type(1)>td:nth-of-type(10)>div>div a
firstIdStatus = [css]:table>tbody>tr:nth-of-type(1)>td:nth-of-type(8)>div
firstIdPriority = [css]:table>tbody>tr:nth-of-type(1)>td:nth-of-type(9)>div
noElementsDisplayText = [css]:td[class*='no-items']
dropDownCheckBoxes = [css]:div[class*='select'] div[class*='options-list'] div[class*='option'] a
dropDownElementListLabels = [css]:div.vn-select-content div.vn-options-list.vn-options-list a
singleDropDownElementList = [xpath]:.//a[@class='vn-dropdown_options__option-link']
selectedIncidentTitle = [css]:tr:nth-child(1) td[headers*=displayId] a
incidentId = [css]:tr:nth-child(1) td[headers*=displayId]
incidentType = [css]:tr:nth-child(1) td[headers=col-id-type] div[class*=cell__content]
incidentSubType = [css]:tr:nth-child(1) td[headers*=subtype] div[class*=cell__content]
incidentPriority = [css]:tr:nth-child(1) td[headers*=priority] div[class*=status]
incidentTitleColumn = [css]:tr:nth-child(1) td[headers*=title] div[class*=cell__content]
incidentAssignedTo =  [xpath]://table[@class="vn-table__table"]//tr[1]//td[8]
incidentDeviceName =  [xpath]://table[@class="vn-table__table"]//tr[1]//td[@headers='col-id-deviceName']
incidentCreatedAt = [css]:tr:nth-child(1) td[headers*=col-id-createdAt] div[class*=cell__content]
dropDownList = [css]:div.vn-option.vn-option__multiple
incidentIdLink = [xpath]://table[contains(@class,'table')]//*/div/a[contains(@href,'incidents')]
incidentTableHeaders = [xpath]: //div[contains(@class,'tableheader__wrapper')]/div[contains(@class,'tableheader__label')]
incidentTableValues = [xpath]:  //div[contains(@class,'tablecell__wrapper--content')]/div/div[contains(@class,'tablecell__content')]
selectAllIncidentsChecked = [xpath]://input[@name='SelectAllPage']//ancestor::label//span[contains(@class,'checked')]
selectAllIncident = [xpath]://*[@id="dui-app-scroll"]//table/thead/tr[1]//label/span
clearFiltersButton = [css]:button[class*='clear-button']
listTable = [css]:table[class*=table]
idHeader = [id]:col-id-displayId
detailsPageHeading = [css]:#dui-breadcrumbs li:nth-child(2)
supportTeamMembersNameList = [css]:td[headers=col-id-name] a
clearfilter=[xpath]://button[@title='Clear']
allDetailsOfSelectedIncidents = [css]: tr:nth-child(1).vn-tablerow td
detailsTitle = [css]:#IncidentDetailsSection div[class*=title]

#table configuration
tableConfigurationButton = [css]:button[title='Table Configuration'] svg
tableConfigurationTitle = [css]:div[class*=header] h4

#assign to pop-up
assignToButton = [id]:assign_to
assignToPopupHeading = [css]:div[class*=header] h4
assignToPopupCancelButton = [id]:cancel-assign-to
assignToPopupSaveButton = [xpath]: //button[text()='Submit']
assignToPopupSearchBox = [css]:#icm-assign-to-popup input#search
assignToPopupSearchList = [css]:#icm-assign-to-popup div[role=option]
assignToEmptySearch = [css]:#icm-assign-to-popup div[class*="no-results"]
assignToDropDownArrow = [css]:#icm-assign-to-popup div[class*=select__button] svg
assignToDropDownUpdated = [xpath]://div[contains(@class,'select__button')]/button
assignToDropDownUpdatedd = [xpath]://div[contains(@class,'select__button')]/button[2]
assignToOnPopup = [css]:#icm-assign-to-popup div[class*='title-text']:nth-child(1)
assignToOnPopupBeforeAssignment = [css]:#icm-assign-to-popup>div>div>a:nth-of-type(1)
assignToOnPopupAfterDeselect = [css]:#icm-assign-to-popup>div>div>a:nth-of-type(1)
currentAssignTo = [css]:tr:nth-child(1)>td[headers*=col-id-assigneeDetails]
currentAssignTohref=[css]:tr:nth-child(1)>td[headers*=col-id-assigneeDetails] a
deselectAssignToButton = [css]:#icm-assign-to-popup div[class*=select__button] svg[class*=neutral]
assignSearchList = [css]:td[headers*=col-id-assigneeDetails]
assignToPopupDropDownFirstOption = [xpath]://div[contains(@class,'vn-options-list')]/div[2]/a[1]
#assign priority pop-up
assignPriorityButton = [id]:assign_priority
assignPriorityHeader = [css]:div[class*=header] h4
assignPriorityDropDown = [css]:#icm-assign-priority-popup div.vn-dropdown__title
assignPrioritySubmitButton = [id]:submit-assign-priority
assignPriorityCancelButton = [id]:cancel-assign-priority
priorityDropDownArrow = [css]:#select-priority svg
changePriorityDropDown = [css]:#select-priority div[class*=options-list]
dropDownList = [css]:div.vn-select-content.vn-select-content--downwards li div
priorityValueOnPopup = [css]:#icm-assign-priority-popup div[class*='title-text']:nth-child(1)
currentPriority = [css]:tr:nth-child(1)>td[headers*=col-id-priority]
deselectPriorityButton = [css]:#icm-assign-priority-popup div[class*=select__button] svg[class*=neutral]
prioritySearchList = [css]:td[headers*=col-id-priority]
assignPriorityDropDownOnPopup = [css]:#select-priority a
assignToDropdown=[xpath]: //th[9]//div[@class='vn-select__button-group']//button

#change status pop-up
changeStatusButton = [id]:change_status
changeStatusHeader = [css]:div[class*=header] h4
changeStatusSubmitButton = [id]:submit-change-status
changeStatusCancelButton = [id]:cancel-change-status
changeStatusDropDown = [css]:#select-status div[class*=options-list]
statusValueOnPopup = [css]:#icm-change-status-popup div[class*='title-text']:nth-child(1)
statusDropDownArrow = [css]:#select-status svg
deselectStatusButton = [css]:#icm-change-status-popup div[class*=select__button] svg[class*=neutral]
currentStatus = [css]:tr:nth-child(1)>td[headers*=col-id-status]
statusSearchList = [css]:td[headers*=col-id-status]
changeStatusDropDownOnPopup = [css]:#select-status a

#idcolumn		
idSearchBox = [id]:incident-id-search
idList = [css]:td[headers*=col-id-displayId]
	 
#typecolumn
typeBoxBefore = [css]:#incident-type button:nth-of-type(1) svg
typeList = [css]:td[headers*=col-id-type]
typeBoxTitle = [css]:table thead tr th:nth-of-type(3) div
typeListOptions = [xpath]://div[contains(@class,'option')]
checkBoxOption = [xpath]://div[contains(@class,'select-content')]
clearFilterIcon = [xpath]://a[contains(@class,'select__button')]/*[contains(@class,'select__button-clear-icon')]
typeValueOnFilter = [css]:#incident-type div[role=button]
				
#sub type column		
subTypeBoxBefore = [css]:#incident-subtype button:nth-of-type(1) svg
subTypeList = [css]:td[headers*=col-id-subtype]
subTypeBoxTitle = [css]:table thead tr th:nth-of-type(4) div
subTypeListNew = [xpath]://div[contains(@class,'--downwards')]//div//a

#createdoncolumn		
createdOnBox = [css]:#incident-created-at input
createdOnList = [css]:td[headers*=col-id-createdAt]
createdOnBoxTitle = [css]:table thead tr th:nth-of-type(5) div
todaysDateButton = [xpath]://td[contains(@class,'CalendarDay__today')]
	
#priority column		
priorityBoxBefore = [css]:#incident-priority button:nth-of-type(1) svg
priorityList = [css]:td[headers*=col-id-priority]
priorityBoxTitle = [css]:table thead tr th:nth-of-type(6) div

#status column		
statusBoxBefore = [css]:#incident-status button:nth-of-type(1) svg
statusList = [css]:td[headers*=col-id-status]
statusBoxTitle = [css]:table thead tr th:nth-of-type(7) div
statusDropDownList = [css]:#incident-status a
		
#assignedTocolumn		
assignedToBoxBefore = [css]:#incident-assignee button:nth-of-type(1) svg
assignedToSearchBox = [css]:#incident-assignee div.vn-select-content__search>input
assignedToList = [css]:td[headers*=col-id-assigneeDetails]
noElementsDisplayTextForComboBoxColumn = [xpath]://div[@class="vn-select-content__no-results"]
assignedToListOnPopup = [css]:#incident-assignee div[class*='options-list'] div[class*='option__multiple']
assignToDropDown = [css]:#incident-assignee ul
assignToBoxTitle = [css]:table thead tr th:nth-of-type(8) div
		
#company column
companySearchBox = [css]:#incident-company div.vn-select-content__search input
companyBoxBefore = [css]:#incident-company button:nth-of-type(1) svg
companyList = [css]:td[headers*=col-id-company]
companyListOnPopup = [css]:#incident-company div[class*='options-list'] div[class*='option__multiple']
companyBoxTitle = [xpath]://*[@id ='col-id-companyName']
companyBox = [id]:devices-company

#locationcolumn
locationTitle = [id]:col-id-location
locationSearchBox = [id]:devices-location
locationList = [css]:td[headers*="location"]

#device name column
deviceNameSearchBox = [id]:incident-device-search
deviceNameList = [css]:td[headers*=col-id-deviceName]
deviceNameBoxTitle = [css]:table thead tr th:nth-of-type(10) div
			
#device serial number		
deviceSerialNumberSearchBox = [id]:incident-device-serial-search
deviceSerialNumberList = [css]:td[headers*=col-id-deviceSerial]
deviceSerialNumberBoxTitle = [id]:col-id-deviceSerial
		
#device manufacturer		
deviceManufacturerSearchBox = [css]:#incident-device-manufacturer div.vn-select-content__search input
deviceManufacturerList = [css]:td[headers*=col-id-deviceManufacturer]
deviceManufactureBefore = [css]:#incident-device-manufacturer button:nth-of-type(1) svg
deviceManufacturerListOnPopup = [css]:#incident-device-manufacturer div[class*='options-list'] div[class*='option__multiple']
noElementsDisplayTextForDeviceManufacturerColumn = [css]:#incident-device-manufacturer div.vn-select-content__no-results
deviceManufactureTitle = [id]:col-id-deviceManufacturer

#title column		
titleSearchBox = [id]:incident-title-search
titleList = [css]:td[headers*=col-id-title]
titleBoxTitle = [id]:col-id-title
		
#created by column		
createdBySearchBox = [css]:#incident-created-by div.vn-select-content__search input
createdByList = [css]:td[headers*=col-id-createdByUserDetails]
createdByBefore = [css]:#incident-created-by button:nth-of-type(1) svg
createdByListOnPopup = [css]:#incident-created-by div[class*='options-list'] div[class*='option__multiple']
noElementsDisplayTextForCreatedByColumn = [css]:#incident-created-by div.vn-select-content__no-results
createdByBoxTitle = [id]:col-id-createdByUserDetails
createdByColumnValue = [css]: td[headers*="col-id-createdByUserDetails"] [class*='vn-tablecell__content']

#occured at column
occuredAtBox = [css]:#incident-occured-at input
occuredAtList = [css]:td[headers*=col-id-occuredAt]
occuredAtTitle = [id]:col-id-occuredAt
		
#updated on column
updatedOnBox = [css]:#incident-updated-at input
updatedOnList = [css]:td[headers*=col-id-updatedAt]
updatedOnBoxTitle = [id]:col-id-updatedAt

#OccurredAt
occurredAtBox=[css]: #incident-occured-at input
		
#device model name		
deviceModelNameSearchBox = [id]:incident-device-model-search
deviceModelNameList = [css]:td[headers*=col-id-deviceModel]
deviceModelNameBoxTitle = [id]:col-id-deviceModel

#device os
deviceOSTitle = [id]:col-id-deviceOs
deviceOSList = [css]:td[headers*=col-id-deviceOs]
deviceOSSearchBox = [id]:incident-device-os-search

#CaseId
caseIdTitle= [id]:col-id-caseId
caseIdData= [xpath]://td[@headers='col-id-caseId']/div


#CaseStatus
caseStatusTitle= [id]:col-id-caseStatus
caseStatusData=[xpath]://td[@headers='col-id-caseStatus']/div

#totalincidentsafterdashboardre-direction
totalIncidentsOnPage = [css]:ul.vn-pagination__navigation>div>a
incidentTable = [css]:table.vn-table__table>tbody

#calendar
calenderIcon = [xpath]://div[@id="incident-created-at"]//*[name()='svg']
monthYearLeft = [css]:div[class*=DayPicker]:last-child div[class*=CalendarMonth]:nth-child(2) strong
monthYearRight = [css]:div[class*=DayPicker]:last-child div[class*=CalendarMonth]:nth-child(3) strong
prvArrow = [css]:svg[class*=arrow--prev]
totalDaysLeftSide = [css]:div[class*=CalendarMonth]:nth-of-type(2) td[class*=CalendarDay]
totalDaysRightSide = [css]:div[class*=CalendarMonth]:nth-of-type(3) td[class*=CalendarDay]
totalDays = [xpath]:(.//div[@id='CalendarMonth__caption'])[2]//following::table[1]/tbody/tr/td
companyColumn = [xpath]://*[@id="incident-company"]/div/div/a[1]

#pagination
paginationOptionAvailable = [xpath]://div[@id="dui-pagination"]//ul//li[@class="vn-menu__item"][1] 
showingText = [xpath]://span[@class='vn-pagination__information__showing']
paginationDropdownMenu = [xpath]://a[contains(@class,'vn-popover__target--down')]
paginationDropdownOptionList = [xpath]://div[contains(@class,'options-list')]//div
paginationDropdownOptionListText = [xpath]://div[contains(@class,'options-list')]//div[contains(@class,'option')]
showingPaginationTotalCount = [xpath]://*[@class='vn-pagination__information']//a//span
paginationOptionList = [xpath]://div[contains(@class,'options-list')]//div
 
navigationItemDiv = [xpath]://*[@class='vn-pagination__navigation']
navigationItemList = [xpath]://*[@class='vn-pagination__navigation']//li
navigationItemNext = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()]/*[contains(@class,'navigation-item')]
navigationItemPrevious = [xpath]:(//*[@class='vn-pagination__navigation']//li)[1]/*[contains(@class,'navigation-item')]
navigationItemFrist = [xpath]:(//*[@class='vn-pagination__navigation']//li)[2]
navigationItemLast = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()-1]
navigationItemDisabled = [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'disabled')]
navigationItemActivePage =  [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'page--active')]
tableOverlay = [xpath]://div[@class='dui-page-spinner']//*[name()='svg']
tableOverlaySiteUp = [xpath]://div[contains(@class,'dui-tl')]//div[contains(@class,'table__overlay') and not (contains(@class,'loading')) and not (contains(@class,'spinner'))]

#table
tableRow =[xpath]://tbody//tr

#filters
selectedFilter = [xpath]://table//thead//tr[2]//th//a[@style="visibility: hidden;"]
storeFilter = [css]:table thead tr:nth-of-type(2) th
filterTitle = [css]:table thead tr:nth-of-type(1) th
firstTypeOptionFromFiltersDropDown = [css]:#incident-type div[class*=options-list] div:nth-of-type(1) a
firstSubtypeOption = [css]:#incident-subtype div[class*=options-list] div:nth-of-type(1) a
filter = [css]:th div>input:not([value=''])[placeholder=''],th div svg[class*='clear-icon']

#sorting
idArrow	= [xpath]://table//thead//tr[1]//th[2]
typeArrow = [xpath]://table//thead//tr[1]//th[3]
subtypeArrow = [xpath]://table//thead//tr[1]//th[4]
createdOnArrow = [xpath]://table//thead//tr[1]//th[5]
priorityArrow = [xpath]://table//thead//tr[1]//th[6]
statusArrow = [xpath]://table//thead//tr[1]//th[7]
assignedToArrow	= [xpath]://table//thead//tr[1]//th[8]
companyArrow = [xpath]://table//thead//tr[1]//th[9]
deviceNameArrow = [xpath]://table//thead//tr[1]//th[10]
deviceSerialNumberArrow	= [xpath]://table//thead//tr[1]//th[11]
deviceManufacturerArrow	= [xpath]://table//thead//tr[1]//th[12]
titleArrow	= [xpath]://table//thead//tr[1]//th[13]
createdByArrow = [xpath]://table//thead//tr[1]//th[14]
occurredAtArrow	= [xpath]://table//thead//tr[1]//th[15]
updatedOnArrow	= [xpath]://table//thead//tr[1]//th[16]
deviceModelNameArrow = [xpath]://table//thead//tr[1]//th[17]
firstPageNavigation = [css]:div.vn-table__pagination ul.vn-pagination__navigation li:nth-of-type(2) a
paginationArea = [css]:div.vn-pagination div.vn-pagination__information

#Company and Assignto Hyperlink
unassignedText=[xpath]: //div[@class='vn-options-list']//div[@data-value='Unassigned']/a
assignedToDropdown=[xpath]://div[@id='incident-assignee']//div[@class='vn-select__button-group']//button
assignmentDropdown=[xpath]://div[@id='icm-assign-to-popup']//button[@class='vn-select__button']
clickIncidentCheckbox= [xpath]: //tr[@class='vn-tablerow']//input[@class='vn-checkbox']
assignToSubmit=[id]:submit-assign-to
tableRowSeclecterAvatar=[xpath]://div[@class='vn-tablerowselector__avatar']
dropdownOption=[xpath]: //div[@class='vn-select-content vn-select-content--downwards']/div[2]/div[1]/a
companyIncidentListHref=[xpath]: //td[contains(@headers,'id-company')]//a

#updateIncident
incidentIdHeader=[css]: th[id*=col-id-displayId]
incidentIdSelect=[xpath]://td[@headers='col-id-displayId']//child::a
hpTechPulseIncidentClick =[xpath] : //tr[1]//td[@headers='col-id-displayId']//a
hpTechpulseSubtype= [xpath]: //div[@data-value="HP TechPulse Incident Integration"]

incidentStatus=[xpath]://tr[1]//td[contains(@headers,"status")]//div[contains(@class,"cell__content")]
verifyincidentStatus=[xpath]: //*[@id="incident-status"]//div[@class='vn-select__title-text vn-select__title-text--two-buttons'][1]
verifyincidentStatusDismiss=[xpath]: //*[@id="incident-status"]//div[@class='vn-options-list vn-options-list__scroll']/div[6]
IncidentStatusChecksCreate= [xpath]: //*[@id="incident-status"]//div[contains(@class,'option--selected')]/a
dropdownStatus=[xpath]: //div[@id="incident-status"]//button[2]