toastNotification = [css]:div[class*='vn-toast__type']
incidentInformationTitle = [xpath]://div[@class='dui-information-title']
incidentdetailTab = [id]:IncidentDetailsTab
tableOverlay = [xpath]://div[@class='dui-page-spinner']//*[name()='svg']
detailsTitle = [css]:#IncidentDetailsSection div[class*=title]


#change status button
statusDropdownArrow = [css]:div.vn-select__button-group :nth-of-type(2) svg
statusClearButton = [css]:div.vn-select__button-group :nth-of-type(1) svg
editStatusButton = [css]:#dui-incident-status div.dui-epr-edit svg
statusValueOnPopup = [css]:#select-status div[role=button]
submitStatusButton = [id]:submit-change-status
currentIncidentStatus = [xpath]://div[@id="dui-incident-status"]//h6
cancelChangeStatusButton = [id]:cancel-change-status
changeStatusTitle = [xpath]://div[@class="icm-modal"][3]//div[@class="vn-modal__header"]//h4
changeStatusDropdown = [css]:#select-status a
editStatus = [xpath]://div[@id="dui-incident-status"]//button/*[name()='svg']
editStatusPopup = [xpath]://div[@id="select-status"]//button[2]//*[name()='svg']
selectInverstigationStatus =[xpath]://div[@id="select-status"]/div[2]/div/div[2]

#incident details
dropdownArrow = [css]:div.vn-select__button-group :nth-of-type(2) svg
dropdownArrowAfterDeselect = [css]:div.vn-select__button-group :nth-of-type(1) svg
incidentLink = [css]:a[class*='breadcrumb__link']
incidentId = [css]:#IncidentIdNo span
incidentTitle = [xpath]://div[@class="col-xs-12 col-md-10"]//div[@class="dui-information-title"]
currentIncidentCompany = [xpath]://div[@class="dui-epr"][1]//p[1]
incidentDetailsPageTitle = [css]:#dui-breadcrumbs li:nth-of-type(2)
breadcrumbId = [xpath]://ul[@class="vn-breadcrumb"]//li[2]
generateXlsButton = [id]:export_exl
detailsTable = [id]:IncidentDetailsSection
dropdownList = [css]:div[class*=options-list] div[role=option]
currentCreatedBy = [css]:#dui-incident-createdby div.dui-epr-value.text-lg p:nth-of-type(1)
currentCreatedOn = [css]:#IncidentOccuredRow span
createdBy = [xpath]://*[@id="dui-incident-createdby"]/div[1] 
createdByValue = [xpath]://*[@id="dui-incident-createdby"]/div[2]
editAssignedToPencilIcon = [xpath]://div[@class='dui-epr-edit-padding']/*[contains(@class,'icon')]
updatedAssignedToUserName = [xpath]://div[@id='dui-incident-assignee']//*/p/a[contains(@href,'users')]
incidentAddedComment = [xpath]://div[@class='comment_text']/div[@class='txt-pre_line']
incidentUpdatedOnText = [xpath]://tbody[@class='vn-table-body']//td[@headers='col-id-updatedAt']//div[@class='vn-tablecell__content']
tagFieldLabel = [css]:#dui-device-tags div[class*=label]
tags = [css]:#dui-device-tags span
assetLocation = [xpath]://*[@id="incident-details-asset-location"]
assetLocationValue = [xpath]://*[@id="incident-details-asset-location"]/div[2]

#edit type button
editTypeButton = [css]:#dui-incident-type svg
typeButtonDropdownArrow = [css]:#select-type button:nth-child(2) svg
currentIncidentType = [xpath]://div[@id="dui-incident-type"]//h6
typeValueOnPopup = [css]:#select-type div div
cancelChangeTypeButton = [xpath]:cancel-change-type
submitTypeButton = [id]:submit-change-type
changeTypeTitle = [xpath]://div[@class="icm-modal"][5]//h4
changeTypeDropdown = [css]:#icm-change-type-popup a
cancelChangeTypeButton = [id]:cancel-change-type
deselectTypeButton = [css]:#select-type button:nth-child(1) svg
typeButtonDropdownArrowAfterDeselect = [css]:#select-type button svg
selectType = [xpath] : //div[@id="select-type"]/div[2]/div/div[2]

#edit subtype button
currentIncidentSubType = [css]:#dui-incident-type h6+p
subTypeValueOnPopup = [css]:#select-subtype div div
subTypeButtonDropdownArrow = [css]:#select-subtype button:nth-child(2) svg
subTypeButtonDropdownArrowAfterDeselect = [css]:#select-subtype button:nth-child(1) svg
changeSubTypeDropdown = [css]:#select-subtype div[class*=content--downwards]
deselectSubTypeButton =[css]:#select-subtype button:nth-child(1) svg
selectSubType = [xpath] : //div[@id="select-type"]/div[2]/div/div[2]
subtypeExpand = [xpath]: //div[@id="select-subtype"]/div/div[3]/button/*[name()='svg']
selectSubType =[xpath] : //div[@id="select-subtype"]/div[2]/div/div[1]

#add comment button
submitCommentButton = [id]:submit-add-comment
addCommentButton = [id]:add-comment
commentArea = [xpath]://textarea[@id="comment"]
commentText = [xpath]://div[@class="vn-panel"]//div[@class="row dui-margin-bottom-25"][1]//div[@class="comment_text"]//div
cancelAddComment = [id]:cancel-add-comment
commentTab = [id]:IncidentsCommentsTab
commentTileHeader = [css]:#IncidentCommentsSection div[class*=title]

#edit priority button
currentIncidentPriority = [css]:#dui-incident-priority h6 span
editPriorityButton = [css]:#dui-incident-priority div.dui-epr-edit svg
priorityValueOnPopup = [css]:#select-priority div div:nth-of-type(1)
cancelChangePriorityButton = [id]:cancel-assign-priority
submitPriorityButton = [id]:submit-assign-priority
changePriorityTitle =[xpath]: //div[@class="icm-modal"][4]//div[@class="vn-modal__header"]//h4
changePriorityDropdown = [css]:#select-priority a
changePriorityExpandDropdown = [xpath] : //div[@id="select-priority"]//button[2]/*[name()='svg']
selectCriticalPriority = [xpath]://div[@id="select-priority"]/div[2]/div/div[2]

#edit device button
editDeviceButtonEnable = [css]:#dui-incident-device div[class*=edit] button
changeDeviceTitle =  [xpath]://div[@class="icm-modal"][2]//h4
submitDeviceButton = [id]:submit-assign-device
cancelChangeDeviceButton = [id]:cancel-assign-device
deselectButton = [css]:div.vn-select__button-group :nth-of-type(1) svg
currentDeviceName = [css]:#dui-incident-device h6 a
editDeviceSearchbox = [css]:#search
deviceOnPopup = [css]:#icm-assign-device-popup div.vn-select__title>div:nth-of-type(1)
deselectDeviceButton = [css]:#icm-assign-device-popup button.vn-select__button:nth-of-type(1) svg
assignDeviceDropdownArrow = [css]:#icm-assign-device-popup svg
assignDeviceEmptySearch = [css]:#icm-assign-device-popup div.vn-select-content__no-results
assignDeviceList = [css]:#icm-assign-device-popup span
deviceName = [xpath] ://*[@id="dui-app-scroll"]//div[9]//p[1]
editDevieIcon=[xpath]://*[@id="dui-app-scroll"]/div[1]//div[9]//div[3]//button/*[name()='svg']

#edit assignto button
assignToDropdownArrowBeforeSelect =[css]:#icm-assign-to-popup button:nth-of-type(1) svg
assignToDropdownArrowAfterSelect = [css]:#icm-assign-to-popup button:nth-of-type(2) svg
currentAssignTo = [xpath]://div[@id="dui-incident-assignee"]//div[@class="dui-epr-value text-lg"]//p[1]
editAssignToButton = [css]:#dui-incident-assignee div.dui-epr-edit svg
changeAssignToTitle = [xpath]://div[@class="icm-modal"][1]//div[@class="vn-modal__header"]//h4
assignToPopupSearchBox =  [css]:#icm-assign-to-popup input
submitAssigntoButton = [id]:submit-assign-to
cancelChangeAssignToButton = [css]:#cancel-assign-to
assignToEmptySearch = [xpath]://*[@id="icm-assign-to-popup"]//div[@class="vn-select-content__no-results"]
assignToPopupSearchList = [css]:#icm-assign-to-popup ul li
assignToOnPopup =[css]:#icm-assign-to-popup>div>div>div>div:nth-of-type(1)
deselectAssignToButton = [css]:#icm-assign-to-popup button:nth-of-type(1) svg
firstDropDownValue = [css]:#icm-assign-to-popup div.vn-options-list.vn-options-list>div:nth-of-type(1) a
errorMessage = [css]:#icm-assign-to-popup p
assignToPopupDropDownFirstOption = [xpath] ://div[contains(@class,'option')]/a[1]
expandAssigntoDropdown = [xpath] ://div[@id="icm-assign-to-popup"]//button/*[name()='svg']

#incident comment
firstComment = [xpath] :(//div[@class='comment_text']/label)[1]
secondComment = [xpath]:(//div[@class='comment_text']/label)[2]
thirdComment = [xpath] :(//div[@class='comment_text']/label)[3]
fourthComment = [xpath]:(//div[@class='comment_text']/label)[4]

#description tile
descriptionTileHeader = [css]:#IncidentDecriptionSection div[class*=title]
descriptionOnDescriptionTile = [css]:#DescriptionPanel span

#identity tile
titleOnIdentityTile = [css]:div[class*=identity-name]
priorityOnIdentityTile = [css]:div[class*=primary-data] p
createdOnOnIdentityTile = [css]:div[class*=created-on] p:nth-child(2)
statusOnIdentityTile = [css]:#incident-status p:nth-child(2)
idOnIdentityTile = [css]:#incident-id-number p:nth-child(2)
createdOnLabelOnIdentityTile = [css]:div[class*=created-on] p:nth-child(1)
statusLabelOnIdentityTile = [css]:#incident-status p:nth-child(1)
idNumberLabelOnIdentityTile = [css]:#incident-id-number p:nth-child(1)
tagsOnIdentityTile =  [css]:#IncidentTags div
repeatedLabel = [css]:#incident-id-occurrence p:nth-child(1)
repeatedValue = [css]:#incident-id-occurrence p:nth-child(2)

#Company and Assignto Hyperlink
companyIncidentDetailPageHref= [xpath]: //div[@id='incident-company']//a
assignToHref= [xpath]: //div[contains(@id,'incident-assignee')]//a

#update incident status
incidentStatusButton =[xpath]: //div[@id='dui-incident-status']//button
dropdownbutton =[xpath]: //button[2][@class='vn-select__button']
dropdownElements = [xpath]: //div[@class='vn-options-list vn-options-list__scroll']/child::div/a
currentStatus= [xpath]: //div[@id='dui-incident-status']/div[@class='dui-epr-value text-lg ']
dropdownHilighted=[xpath]://div[contains(@class,'option--selected')]
dropDownSelectText=[xpath]: //div[@class='vn-option']/a
dropdown= [xpath] : //div[@id='select-status']
clickDissmissButton =[xpath] ://div[contains(@class,"options-list__scroll")]//div[6]/a

#CaseCreation
createCaseButton = [id]:dui-create-case

userCommentForSCAUnprotectedIncident = [css]:#DescriptionPanel span
threatEventDetailsLinkIncidentDescription = [css]:#DescriptionPanel a