toastNotification = [xpath]://div[@role='alert']//div/span
incidentInformationTitle = [id]:overview
incidentdetailTab = [id]:IncidentDetailsTab
tableOverlay = [xpath]://div[@class='dui-page-spinner']//*[name()='svg']
detailsTitle = [css]:#dui-incident-details-panel div[class*=header]


#change status button
statusDropdownArrow = [xpath]:(//*[@id='icm-change-status-popup-desc'])//*[@aria-label='Open']
statusClearButton = [css]:div[role='presentation']:nth-of-type(8) div[aria-label="Clear"]
editStatusButton = [css]:#dui-incident-event svg
statusValueOnPopup = [xpath]:(//*[@id='icm-change-status-popup-select-box']/span)
submitStatusButton = [xpath]:(//*[@id='icm-change-status-popup-submit'])
currentIncidentStatus = [css]:#dui-incident-event span[class*=title]
cancelChangeStatusButton = [xpath]:(//*[@id='icm-change-status-popup-cancel'])
changeStatusTitle = [xpath]:(//h4[@id="icm-change-status-popup-label"])
changeStatusDropdown = [css]:#icm-change-status-popup-select-box-listbox li
editStatus = [xpath]://div[@id="dui-incident-status"]//button/*[name()='svg']
editStatusPopup = [xpath]://div[@id="select-status"]//button[2]//*[name()='svg']
selectInverstigationStatus =[xpath]://div[@id="select-status"]/div[2]/div/div[2]

#incident details
dropdownArrow2 = [css]:div[role='presentation']:nth-of-type(8) div[aria-label="Open"]
dropdownArrow = [xpath]: //*[@aria-controls="icm-assign-priority-popup-select-box-listbox"]/following-sibling::span//div
dropdownArrowAfterDeselect = [css]:div[role='presentation']:nth-of-type(8) div[aria-label="Open"]
incidentLink = [css]:#incidentDetails nav[class*=breadcrumbs] a
incidentId = [xpath]://div[@id="dui-incident-code"]//span
incidentTitle = [xpath]://div[@class="col-xs-12 col-md-10"]//div[@class="dui-information-title"]
currentIncidentCompany = [xpath]://div[@class="dui-epr"][1]//p[1]
incidentDetailsPageTitle = [css]:#incidentDetails nav[class*=breadcrumbs] li span
breadcrumbId = [xpath]://ul[@class="vn-breadcrumb"]//li[2]
generateXlsButton = [id]:export_exl
detailsTable = [id]:dui-incident-details-panel
dropdownList = [css]:#dui-select-type-listbox li
currentCreatedBy = [css]:#dui-incident-createdby div.dui-epr-value.text-lg p:nth-of-type(1)
currentCreatedOn = [css]:#dui-incident-occured-at span
createdBy = [xpath]://*[@id="dui-incident-createdby"]/div[1] 
createdByValue = [xpath]://*[@id="dui-incident-createdby"]/div[2]
editAssignedToPencilIcon = [xpath]://div[@class='dui-epr-edit-padding']/*[contains(@class,'icon')]
updatedAssignedToUserName = [xpath]://div[@id='dui-incident-assignee']//*/p/a[contains(@href,'users')]
incidentAddedComment = [xpath]://div[@class='comment_text']/div[@class='txt-pre_line']
incidentUpdatedOnText = [xpath]://tbody[@class='vn-table-body']//td[@headers='col-id-updatedAt']//div[@class='vn-tablecell__content']
tagFieldLabel = [css]:#dui-incident-tags div[class*=label]
tags = [css]:#dui-incident-tags div[class*=value]:nth-of-type(1)
assetLocation = [xpath]://*[@id="dui-incident-location"]
assetLocationValue = [xpath]://*[@id="dui-incident-location"]//div[@class='dui-epr-value']

#edit type button
editTypeButton = [css]:#dui-incident-type svg
typeButtonDropdownArrow = [xpath]://*[@id="dui-select-type"]//ancestor::div/span/div[2]
currentIncidentType = [xpath]://div[@id="dui-incident-type"]//span
typeValueOnPopup = [css]:#dui-select-type
cancelChangeTypeButton = [id]:dui-form-modal-cancel
submitTypeButton = [id]:dui-form-modal-submit
changeTypeTitle = [xpath]://div[@role="presentation"][7]//h2
changeTypeDropdown = [css]:#dui-select-type-listbox li
deselectTypeButton = [xpath]://*[@id="dui-select-type"]//ancestor::div/span/div[1]
typeButtonDropdownArrowAfterDeselect = [xpath]://*[@id="dui-select-type"]//ancestor::div/span/div
selectType = [xpath] : //div[@id="select-type"]/div[2]/div/div[2]

#edit subtype button
currentIncidentSubType = [xpath]://div[@id="dui-incident-type"]//p
subTypeValueOnPopup = [css]:#dui-select-subtype
subTypeButtonDropdownArrow = [css]:#select-subtype button:nth-child(2) svg
subTypeButtonDropdownArrowAfterDeselect = [xpath]://*[@id="dui-select-subtype"]//ancestor::div/span/div
changeSubTypeDropdown = [css]:#dui-select-subtype-listbox li
deselectSubTypeButton =[xpath]://*[@id="dui-select-subtype"]//ancestor::div/span/div[1]
selectSubType = [xpath] : //div[@id="select-type"]/div[2]/div/div[2]
subtypeExpand = [xpath]: //div[@id="select-subtype"]/div/div[3]/button/*[name()='svg']
selectSubType =[xpath] : //div[@id="select-subtype"]/div[2]/div/div[1]

#add comment button
submitCommentButton = [id]:submit-add-comment
addCommentButton = [id]:add-comment
commentArea = [css]:#icm-add-comment-popup textarea
commentText = [xpath]://div[contains(@class,"comment_text")]//span
cancelAddComment = [id]:cancel-add-comment
commentTab = [css]:#comments span
commentTileHeader = [css]:#dui-incident-comments-panel div[class*=header]

#edit priority button
currentIncidentPriority = [css]:#dui-incident-priority span
editPriorityButton = [css]:#dui-incident-priority svg
priorityValueOnPopup = [xpath]:(//div[@id='icm-assign-priority-popup-select-box'])
cancelChangePriorityButton = [xpath]:(//*[@id='icm-assign-priority-popup-cancel'])
submitPriorityButton = [xpath]:(//*[@id='icm-assign-priority-popup-submit'])
changePriorityTitle =[xpath]:(//h4[@id='icm-assign-priority-popup-label'])
changePriorityDropdown = [xpath]://*[@id='icm-assign-priority-popup-select-box-listbox']/li
changePriorityExpandDropdown = [xpath] : //div[@id="select-priority"]//button[2]/*[name()='svg']
selectCriticalPriority = [xpath]://div[@id="select-priority"]/div[2]/div/div[2]

#edit device button
editDeviceButtonEnable = [css]:#dui-incident-device div[class*=edit] svg
changeDeviceTitle =  [xpath]://div[@role="presentation"][4]//h2
submitDeviceButton = [xpath]://div[@role="presentation"][4]//button[1]
cancelChangeDeviceButton = [xpath]://div[@role="presentation"][4]//button[2]
deselectButton = [css]:div[role='presentation']:nth-of-type(8) div[aria-label="Clear"]
currentDeviceName = [css]:#dui-incident-device h6 a
editDeviceSearchbox = [css]:#search
deviceOnPopup = [css]:#icm-assign-device-popup div.vn-select__title>div:nth-of-type(1)
deselectDeviceButton = [css]:#icm-assign-device-popup button.vn-select__button:nth-of-type(1) svg
assignDeviceDropdownArrow = [css]:#icm-assign-device-popup svg
assignDeviceEmptySearch = [css]:#icm-assign-device-popup div.vn-select-content__no-results
assignDeviceList = [css]:#icm-assign-device-popup span
deviceName = [xpath] ://*[@id="dui-app-scroll"]//div[9]//p[1]
editDevieIcon=[xpath]://*[@id="dui-app-scroll"]/div[1]//div[9]//div[3]//button/*[name()='svg']

#edit assignto button
assignToDropdownArrowBeforeSelect =[css]:#icm-assign-to-popup button:nth-of-type(1) svg
assignToDropdownArrowAfterSelect = [css]:#icm-assign-to-popup button:nth-of-type(2) svg
#if it works I will remove the commented one
currentAssignTo = [xpath]:(//div[@class='dui-incident-list']//tbody//tr[2]//td[8])[1]//a
#currentAssignTo = [xpath]://div[@id="dui-incident-assignee"]//div[@class="dui-epr-value text-lg"]//p[1]
editAssignToButton = [css]:#dui-incident-assignee div.dui-epr-edit svg
changeAssignToTitle = [xpath]://div[@class="icm-modal"][1]//div[@class="vn-modal__header"]//h4
assignToPopupSearchBox =  [css]:#icm-assign-to-popup input
submitAssigntoButton = [id]:submit-assign-to
cancelChangeAssignToButton = [css]:#cancel-assign-to
assignToEmptySearch = [xpath]://*[@id="icm-assign-to-popup"]//div[@class="vn-select-content__no-results"]
assignToPopupSearchList = [css]:#icm-assign-to-popup ul li
assignToOnPopup =[css]:#icm-assign-to-popup>div>div>div>div:nth-of-type(1)
deselectAssignToButton = [css]:#icm-assign-to-popup button:nth-of-type(1) svg
firstDropDownValue = [css]:#icm-assign-to-popup div.vn-options-list.vn-options-list>div:nth-of-type(1) a
errorMessage = [css]:#icm-assign-to-popup p
assignToPopupDropDownFirstOption = [xpath] ://div[contains(@class,'option')]/a[1]
expandAssigntoDropdown = [xpath] ://div[@id="icm-assign-to-popup"]//button/*[name()='svg']

#incident comment
firstComment = [xpath] :(//div[@class='comment_text']/label)[1]
secondComment = [xpath]:(//div[@class='comment_text']/label)[2]
thirdComment = [xpath] :(//div[@class='comment_text']/label)[3]
fourthComment = [xpath]:(//div[@class='comment_text']/label)[4]

#description tile
descriptionTileHeader = [css]:#dui-incident-description-panel div[class*=header]
descriptionOnDescriptionTile = [css]:#dui-incident-description-panel span

#identity tile
titleOnIdentityTile = [css]:span[class=dui-summary-card-title
priorityOnIdentityTile = [css]:#dui-dsummary-card p[class*=priority]
createdOnOnIdentityTile = [xpath]:(//div[@class='dui-dsummary-card-desc-content-value'])[2]
statusOnIdentityTile = [xpath]:(//div[@class='dui-dsummary-card-desc-content-value'])[3]
idOnIdentityTile = [xpath]:(//div[@class='dui-dsummary-card-desc-content-value'])[4]
createdOnLabelOnIdentityTile = [xpath]:(//div[@class='dui-dsummary-card-desc-content-title'])[2]
statusLabelOnIdentityTile = [xpath]:(//div[@class='dui-dsummary-card-desc-content-title'])[3]
idNumberLabelOnIdentityTile = [xpath]:(//div[@class='dui-dsummary-card-desc-content-title'])[4]
tagsOnIdentityTile =  [css]:#IncidentTags div
repeatedLabel = [css]:#incident-id-occurrence p:nth-child(1)
repeatedValue = [css]:#incident-id-occurrence p:nth-child(2)

#Company and Assignto Hyperlink
companyIncidentDetailPageHref= [xpath]: //div[contains(@id,'incident-company')]//a
assignToHref= [xpath]: (//span/a)[3]

#update incident status
incidentStatusButton =[xpath]: //*[@id="dui-incident-event"]//*[@name="IconPencil"]
dropdownbutton =[xpath]: (//div[@aria-label="Open"])[3]
dropdownElements = [xpath]: //ul[@id="dui-select-modal-select-box-listbox"]//li
currentStatus= [xpath]: //div[@id='dui-incident-status']/div[@class='dui-epr-value text-lg ']
dropdownHilighted=[xpath]://li[@data-focus="true"]
dropDownSelectText=[xpath]: //div[@class='vn-option']/a
dropdown= [xpath] : //div[@id='select-status']
clickDissmissButton =[xpath] ://li[@id="dui-select-modal-select-box-option-5"]

#CaseCreation
createCaseButton = [id]:dui-create-case

userCommentForSCAUnprotectedIncident = [xpath]:(//*[@id="dui-incident-description-panel"]//span)[1]
threatEventDetailsLinkIncidentDescription = [css]:#dui-incident-description-panel a


createCaseButtonDisabled =[xpath] ://*[@label='Create a Case' and contains(@class,'disabled')]
