subscriptionsTab = [css]:#menu_subscriptions
subscriptionsPageTitle = [css]:#add-new-subscription-key h4
planTab = [css]:a[class*='tab']:nth-child(1)
usersTitle = [css]:#rootUsers h4
logsTitle = [css]:#logs h4
subKeyBox = [css]:#subscription-licenseKey
#Subscription KeyTab
subscriptionKeyTab = [css]:a[class*='tab']:nth-child(2)
subscriptionKeyTabTitle = [css]:#key-management h4
addButton = [css]:#btn_sku_add
importButton = [css]:#browse
actionBar = [xpath]://div[@class = 'dui-action-bar']//div[contains(@class,'select__title')]//*[name()='svg']
addModalTitle = [css]:#modal_add_license_info h4
orderId = [css]:#orderNumber
subKey = [css]:#licenseKey
subTypeHeading = [css]:#modal_add_license_info h5
skulist = [css]:#skuName svg
skuSearch = [xpath]://div[@id='skuName']//input
firstSKU = [css]:#skuName div[class*='options-list'] div:nth-child(1)
numberOfSeats = [css]:#numberOfSeats
nextButton = [css]:#btn_next
startDate = [css]:#startDate
bufferDays = [css]:#buffer
partnerId = [css]:#partnerId
subKeyAddButtonModal = [css]:#btn_create
importModalHeader = [css]:#import_license h4
sampleFileLink = [css]:#download_sample
uploadButton = [css]:#btn_save
unassignedButton = [css]:.dui-action-bar div[class*='options-list'] div:nth-child(2)
assignedButton = [css]:.dui-action-bar div[class*='options-list'] div:nth-child(1)
toastNotification = [xpath]://*[contains(@class,'toast-enter-done')]//p
fileImport = [css]:a[class*='filepicker__link'] input
firstSubKeyListPage = [xpath]://td[@headers = 'col-id-licenseKey']//a

#SKUs tab
sKUsTab = [css]:a[class*='tab']:nth-child(3)
skuTabTitle = [css]:#sku-management h4
skuModalHeader = [css]:.sku-management h4
skuAdd = [css]:#btn_sku_add
sku = [css]:#id
planList = [css]:#planList
planListValues = [css]:#planList [class*=options-list] a
planSearch = [xpath]://div[@id='planList-parent']//input
firstplanSelect = [css]:#planList div[class*='options-list'] div:nth-child(1)
term = [xpath]://div[contains(@class,'select') and @id='term']
firstTermList = [css]:#term div[class*='options-list'] div:nth-child(1)
mustStartIn = [css]:#mustStartIn
firstmustStartIn = [css]:#mustStartIn div[class*='options-list'] div:nth-child(1)
description = [css]:#description
skuAddModal = [css]:#btn_next
firstSKUListPage = [xpath]://td[@headers = 'col-id-skuID']//span
successNotificationClose = [css]:#dui-app-scroll div.vn-toast-container button.vn-toast__close
appUsersTab = [id]:menu_appUsers
skuListBox = [css]:#skus-skuID
spinnerSKU = [css]:.vn-spinner
planID = [css]:#planId
termEditModal = [xpath]://input['disabled' and @id='term']
mustStartInEditModal = [xpath]://div[@id="mustStartIn"]/div/div[1]