subscritionTitle = [css]:#license_key h4
subscriptionNumber = [xpath]://div[contains(@class,'primary-data')]//p[2]
orderNumber = [xpath]://div[contains(@class,'footer')]//p[2]
removeLicenseButton = [css]:#remove-license
removeOkButton = [css]:div[class*='modal__dialog'] button[class*='primary']
revoke = [xpath]://*[@id="remove-license"]

#detailstile
detailsTile = [css]:#details
detailsTileTitle = [css]:#details div[class*='panel__title']
skuValue = [css]:#sku span
productValue = [css]:#product_name span

#userCountTile
userCountTile = [css]:#user_count
userCountTileTitle = [css]:#user_count div[class*='panel__title']
noOfSeats = [css]:#numberOfSeats span
editButtonUserCountTile = [css]:#numberOfSeats div[class='dui-epr-edit'] button
noOfUserBox = [xpath]://*[@id="key__numberOfSeats"]//*[@id="numberOfSeats"]
saveButton = [css]:#btn_save

#date_time_definitions
dateTimeTile = [css]:#date_time_definitions
dateTimeTileTitle = [css]:#date_time_definitions div[class*='panel__title']
termValue = [css]:#term span
expirationDateValue = [css]:#endDate span
purchaseDateValue = [css]:#creationDate span
startDateValue = [css]:#startDate span
editButtonStartDate = [css]:#startDate

#subscription_details
subscriptionDetailsTile = [css]:#subscription_details
subscriptionDetailsTileTitle = [css]:#subscription_details div[class*='panel__title']
statusValue = [css]:#status span
companyValue = [css]:#company span
primaryContactEmailValue = [css]:#primary_contact_email span

#partner_details
partnerDetailsTile = [css]:#partner_details
partnerDetailsTileTitle = [css]:#partner_details div[class*='panel__title']
editPartnerButton = [css]:#partnerId
toastNotification = [xpath]://*[contains(@class,'toast-enter-done')]//p
spinnerDetailsPage = [css]:.vn-spinner