subscriptionsTab = [css]:#menu_subscriptions
subscriptionsPageTitle = [css]:#add-new-subscription-key h4
planTab = [xpath]://div[@id="0"]
usersTitle = [css]:#rootUsers h4
logsTitle = [css]:#logs h4
subKeyBox = [xpath]://*[@name='licenseKey']

#Subscription KeyTab
subscriptionKeyTab = [xpath]://div[@id="1"]
subscriptionKeyTabTitle = [css]:#key-management h4
addButton = [xpath]:(//*[@id="btn_sku_add"])[2]
addSKUButton = [css]:#btn_sku_add
importButton = [xpath]://div[@class='row']//button[@id='browse']
actionBar = [xpath]:(//*[contains(@class,"select__open-button")])[2]
addModalTitle = [css]:#modal_add_license_info-label 
orderId = [xpath]://div[@id="modal_add_license_info-desc"]//input[@name='orderNumber']
subKey = [xpath]://div[@id="modal_add_license_info-desc"]//input[@name='licenseKey']
subTypeHeading = [css]:#modal_add_license_info-desc h5
skulist = [xpath]://*[@id="skuName"]//following-sibling::span//*[contains(@class,"select__open-button")]
skuSearch = [xpath]:(//input[@placeholder="Search"])[4]
firstSKU = [css]:#skuName-option-0
numberOfSeats = [xpath]://input[@name='numberOfSeats']
nextButton = [css]:#btn_next
startDate = [css]:#startDate
bufferDays = [css]:#buffer
partnerId = [xpath]://*[@name='partnerId']
subKeyAddButtonModal = [css]:#btn_create
importModalHeader = [css]:#import_license-label
sampleFileLink = [css]:#download_sample
uploadButton = [css]:#btn_save
unassignedButton = [xpath]://*[@id="SKU-data-center-listbox"]//li[2]
assignedButton = [xpath]://*[@id="SKU-data-center-listbox"]//li[1]
toastNotification = [xpath]:(//*[@role="alert"]//span)[1]
fileImport = [xpath]://*[contains(@class,"input__icon")]//div[@role="button"]
firstSubKeyListPage = [xpath]://div[contains(@class,'table-container')]//tbody//a
skuSelect =[css]:#skuName-option-0
browseInput = [xpath]: //input[@id="file"] 

#SKUs tab
sKUsTab = [xpath]://div[@id="2"]
skuTabTitle = [css]:#sku-management h4
skuModalHeader = [css]:#add_sku-label
skuAdd = [css]:#btn_sku_add
sku = [css]:#skuId
planList = [css]:#planList
planSearch = [xpath]:(//input[@placeholder='Search'])[4]
firstplanSelect = [xpath]://*[@id="planList-option-0"]
term = [css]:#SKU-term
firstTermList = [css]:#SKU-term-option-0
mustStartIn = [css]:#SKU-must-start-in
firstmustStartIn = [css]:#SKU-must-start-in-option-0
description = [xpath]://*[@name='description']
skuAddModal = [css]:#btn_next
firstSKUListPage = [xpath]:(//div[contains(@class,'table-container')]//tbody//td[2]//span)[1]
successNotificationClose = [xpath]://*[@role="alert"]//button
appUsersTab = [id]:menu_appUsers
skuListBox = [xpath]://input[@id='skuID']
spinnerSKU = [css]:.vn-spinner
planID = [xpath]://input[@name="planId"]
termEditModal = [xpath]:(//input['disabled' and @name='term'])[2]
mustStartInEditModal = [xpath]://div[@id="mustStartIn"]/div/div[1]
settingleftMenu = [xpath]://*[@id="menu_appSettings"]/a
settingdetailstile = [xpath]://*[@id="dui-container"]//div[contains(@class,'dui-panel-header')]



#SKU Tab, Plans list
planListValues = [xpath]://*[contains(@id,'planList-listbox')]//li