subscriptionOrdersTab = [css]:#menu_subscriptionOrders a
subscriptionOrdersTitle = [css]:#subscriptionOrders h4
subscriptionOrdersTitleBreadcrumb = [css]:#subscriptionOrders li
firstOrderNumber = [css]:tr:first-child td[headers*=order-number]
noElementsDisplayText = [css]:td[class*='no-items']
dropDownCheckBoxes = [css]:div[class*='select'] div[class*='options-list'] div[class*='option']:nth-of-type(1) a
dropDownElementListLabels = [css]:div.vn-select-content div.vn-options-list.vn-options-list>div:nth-of-type(1)>a
clearFiltersButton = [css]:button[class*='clear-button']
tableOverlay = [xpath]://div[@class='vn-table__overlay']
noElementsDisplayTextForComboBoxColumn = [xpath]://div[@class="vn-select-content__no-results"]
firstKeyCountry = [css]:tr:first-child td[headers*=country]
firstKeyState = [css]:tr:first-child td[headers*=state]
firstKeyCity = [css]:tr:first-child td[headers*=city]
firstKeyCompany = [css]:tr:first-child td[headers*=company] a

orderNumberTitle = [css]:#col-id-order-number div[class*=label]
skuTitle = [css]:#col-id-sku div[class*=label]
subscriptionKeyTitle = [css]:#col-id-ssubscription-key div[class*=label]
planTitle = [css]:#col-id-subscription-plan div[class*=label]
totalSeatsTitle = [css]:#col-id-total-seats div[class*=label]
termTitle = [css]:#col-id-term div[class*=label]
companyTitle = [css]:#col-id-company div[class*=label]
purchaseDateTitle = [css]:#col-id-purchase-date div[class*=label]
requiredStartDateTitle = [css]:#col-id-start-date div[class*=label]
activationDateTitle = [css]:#col-id-activation-date div[class*=label]
subscriptionStatusTitle = [css]:#col-id-subscription-status div[class*=label]
countryTitle = [css]:#col-id-country div[class*=label]
stateTitle = [css]:#col-id-state div[class*=label]

orderNumberTextBox = [id]:order-number
skuTextBox = [id]:sku
subscriptionKeyTextBox = [id]:subscription-key
subscriptionPlanDropdown = [id]:subscription-plan
subscriptionPlanDropdownOptions = [css]:#subscription-plan div[role=option]
totalSeatsTextBox = [id]:total-seats
termTextBox = [id]:term
companyDropdown = [id]:users-company
companyDropdownList = [css]:#users-company div[role=option]
companySearchBox = [css]:#users-company #search
purchaseDateDropdown = [id]:purchase-date
requiredStartDateDropdown = [id]:start-date
activationdateDropdown = [id]:activation-date
statusDropdown = [id]:subscription-status
statusDropdownList = [css]:#subscription-status div[role=option]
countryDropdown = [id]:country
cuntryDropdownList = [css]:#country div[role=option]
countrySearchTextBox = [css]:#country #search
stateTextBox = [id]:state

orderNumberList = [css]:td[headers*=order-number]
skuList = [css]:td[headers*=sku]
subscriptionKeyList = [css]:td[headers*=ssubscription-key]
planList = [css]:td[headers*=plan]
totalSeatsList = [css]:td[headers*=total-seats]
termList = [css]:td[headers*=term]
companyList = [css]:td[headers*=company]
purchaseDateList = [css]:td[headers*=purchase-date]
requiredStartDateList = [css]:td[headers*=start-date]
activationDateList = [css]:td[headers*=activation-date]
statusList = [css]:td[headers*=subscription-status]
countryList = [css]:td[headers*=country]
stateList = [css]:td[headers*=state]

#calendar
calenderIcon = [xpath]://div[@id="incident-created-at"]//*[name()='svg']
monthYearLeft = [css]:div[class*=DayPicker]:last-child div[class*=CalendarMonth]:nth-child(2) strong
monthYearRight = [css]:div[class*=DayPicker]:last-child div[class*=CalendarMonth]:nth-child(3) strong
prvArrow = [css]:svg[class*=arrow--prev]
totalDaysLeftSide = [css]:div[class*=CalendarMonth]:nth-of-type(2) td[class*=CalendarDay]
totalDaysRightSide = [css]:div[class*=CalendarMonth]:nth-of-type(3) td[class*=CalendarDay]
totalDays = [xpath]:(.//div[@id='CalendarMonth__caption'])[2]//following::table[1]/tbody/tr/td
companyColumn = [xpath]://*[@id="incident-company"]/div/div/a[1]

#table configuration
tableConfigurationButton = [css]:button[title='Table Configuration'] svg
tableConfigurationTitle = [css]:div[class*=header] h4

#pagination
paginationOptionAvailable = [xpath]://div[@id="dui-pagination"]//ul//li[@class="vn-menu__item"][1]
showingText = [xpath]://span[@class='vn-pagination__information__showing']
paginationDropdownMenu = [xpath]://a[contains(@class,'vn-popover__target--down')]
paginationDropdownOptionList = [xpath]://div[contains(@class,'options-list')]//div
paginationDropdownOptionListText = [xpath]://div[contains(@class,'options-list')]//div[contains(@class,'option')]
showingPaginationTotalCount = [xpath]://*[@class='vn-pagination__information']//a//span
paginationOptionList = [xpath]://div[contains(@class,'options-list')]//div
 
navigationItemDiv = [xpath]://*[@class='vn-pagination__navigation']
navigationItemList = [xpath]://*[@class='vn-pagination__navigation']//li
navigationItemNext = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()]/*[contains(@class,'navigation-item')]
navigationItemPrevious = [xpath]:(//*[@class='vn-pagination__navigation']//li)[1]/*[contains(@class,'navigation-item')]
navigationItemFrist = [xpath]:(//*[@class='vn-pagination__navigation']//li)[2]
navigationItemLast = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()-1]
navigationItemDisabled = [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'disabled')]
navigationItemActivePage =  [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'page--active')]
tableOverlay = [xpath]://div[@class='vn-table__overlay']
uniquelist_subord = [css]:td[headers='col-id-subscription-plan'] div[class*='tablecell__content']