subscritionTitle = [xpath]:(//*[@id="license_key"]//span)[1]
subscriptionNumber = [xpath]:(//div[contains(@class,'summary-card-desc-content-value')])[2]
orderNumber = [xpath]:(//div[contains(@class,'summary-card-desc-content-value')])[3]
removeLicenseButton = [xpath]://*[contains(@class,'dui-dsummary-card-button')]//button
removeOkButton = [xpath]:(//div[contains(@class,'modal--footer')]//button)[2]
revoke = [xpath]://*[@class='dui-dsummary-card-buttons']//button

#detailstile
detailsTile = [css]:#details
detailsTileTitle = [css]:#details div[class*='panel-header']
skuValue = [css]:#sku span
productValue = [css]:#productName span

#userCountTile
userCountTile = [css]:#user_count
userCountTileTitle = [css]:#user_count div[class*='panel-header']
noOfSeats = [css]:#numberOfSeats span
editButtonUserCountTile = [xpath]://div[contains(@class,'dui-depr-edit-icon')]
noOfUserBox = [xpath]://input[@id="numberOfSeats"]
saveButton = [css]:#btn_save

#date_time_definitions
dateTimeTile = [css]:#date_time_definitions
dateTimeTileTitle = [css]:#date_time_definitions div[class*='panel-header']
termValue = [css]:#term span
expirationDateValue = [xpath]:(//div[@class='dui-depr-value-wrapper'])[5]/div
purchaseDateValue = [css]:#creationDate span
startDateValue = [css]:#startDate span
editButtonStartDate = [css]:#startDate div[class*='dui-icon-button']

#subscription_details
subscriptionDetailsTile = [css]:#subscription_details
subscriptionDetailsTileTitle = [css]:#subscription_details div[class*='panel-header']
statusValue = [css]:#workflowState span
companyValue = [xpath]:(//div[@class='dui-depr-value-wrapper'])[9]/div
primaryContactEmailValue = [xpath]:(//div[@class='dui-depr-value-wrapper'])[10]/div
addPlan = [xpath]://*[@id="company-subscription"]


#partner_details
partnerDetailsTile = [css]:#partner_details
partnerDetailsTileTitle = [css]:#partner_details div[class*='panel-header']
editPartnerButton = [css]:#partnerId div[class*='dui-icon-button']
toastNotification = [xpath]://*[contains(@class,'ToastNotification')]//span
spinnerDetailsPage = [css]:.vn-spinner