subscriptionOrdersTab = [css]:#menu_subscriptionOrders a
subscriptionOrdersTitle = [css]:#subscriptionOrders h4
subscriptionOrdersTitleBreadcrumb = [css]:#subscriptionOrders li
firstOrderNumber = [xpath]://*[@id="dui-container"]//div[2]//tbody/tr[1]/td[1]
noElementsDisplayText = [xpath]://tbody//tr/td//span
dropDownCheckBoxes = [css]:#subscription-plan-listbox li
dropDownElementListLabels = [css]:#subscription-plan-listbox li
clearFiltersButton = [css]:button[aria-label="Clear selection"] svg
tableOverlay = [xpath]://div[@class='vn-table__overlay']
noElementsDisplayTextForComboBoxColumn = [xpath]://div[@class="vn-select-content__no-results"]
firstKeyCountry = [xpath]://tr[1]//td[11]
firstKeyState = [css]:tr:nth-child(1) > td:nth-child(12)
firstKeyCity = [css]:tr:nth-child(1) > td:nth-child(13)
firstKeyCompany = [xpath]://tr[1]//td[7]
CompanyDropDownArrowOpen = [xpath]: //input[@name='company']//following-sibling::span
CompanySearchBox = [xpath]: //ul[@id='company-listbox']//preceding-sibling::div//input[@placeholder='Search']
SelectedElement = [xpath]:  //li[@data-option-index='0']
orderNumberTitle = [css]:#col-id-order-number div[class*=label]
skuTitle = [css]:#col-id-sku div[class*=label]
subscriptionKeyTitle = [css]:#col-id-ssubscription-key div[class*=label]
planTitle = [css]:#col-id-subscription-plan div[class*=label]
totalSeatsTitle = [css]:#col-id-total-seats div[class*=label]
termTitle = [css]:#col-id-term div[class*=label]
companyTitle = [css]:#col-id-company div[class*=label]
purchaseDateTitle = [css]:#purchase-date
requiredStartDateTitle = [css]:#col-id-start-date div[class*=label]
activationDateTitle = [css]:#col-id-activation-date div[class*=label]
subscriptionStatusTitle = [css]:#col-id-subscription-status div[class*=label]
countryTitle = [css]:#col-id-country div[class*=label]
stateTitle = [css]:#col-id-state div[class*=label]

orderNumberTextBox = [id]:order-number
skuTextBox = [id]:sku
subscriptionKeyTextBox = [id]:subscription-key
subscriptionPlanDropdown = [xpath]://*[@id="subscription-plan"]//parent::div/span/div
subscriptionPlanDropdownOptions = [xpath]://*[contains(@class,"SelectContent")]//li
totalSeatsTextBox = [id]:total-seats
termTextBox = [id]:term
companyDropdown = [xpath]://*[@id="company"]//parent::div//span/div
companyDropdownList = [css]:#users-company div[role=option]
companySearchBox = [xpath]://div[@role="presentation"][5]//input
purchaseDateDropdown = [xpath]://tr[2]//th[8]//div[2]/input
requiredStartDateDropdown = [xpath]://table/thead/tr[2]/th[5]//div[contains(@class,'FormControl')]
activationdateDropdown = [id]:activation-date
statusDropdown = [id]:subscription-status
statusDropdownList = [css]:#subscription-status div[role=option]
countryDropdown = [id]:country
cuntryDropdownList = [css]:#country div[role=option]
countrySearchTextBox = [css]:#country #search
stateTextBox = [id]:state

orderNumberList = [css]:td[headers*=order-number]
skuList = [css]:td[headers*=sku]
subscriptionKeyList = [css]:td[headers*=ssubscription-key]
planList = [xpath]://*[@id="dui-container"]//div[2]//tbody/tr/td[4]
totalSeatsList = [css]:td[headers*=total-seats]
termList = [css]:td[headers*=term]
companyList = [css]:td[headers*=company]
purchaseDateList = [xpath]://div[2]//tbody//tr//td[8]
requiredStartDateList = [css]:td[headers*=start-date]
activationDateList = [css]:td[headers*=activation-date]
statusList = [css]:td[headers*=subscription-status]
countryList = [css]:td[headers*=country]
stateList = [css]:td[headers*=state]

#calendar
calenderIcon = [css]:th:nth-of-type(8) div svg
monthYearLeft = [css]:div[class*=DayPicker]:last-child div[class*=CalendarMonth]:nth-child(2) strong
monthYearRight = [css]:div[class*=DayPicker]:last-child div[class*=CalendarMonth]:nth-child(3) strong
prvArrow = [css]:svg[aria-label="Last Month"]
totalDaysLeftSide = [css]:div[class*=CalendarMonth]:nth-of-type(2) td[class*=CalendarDay]
totalDaysRightSide = [css]:div[class*=CalendarMonth]:nth-of-type(3) td[class*=CalendarDay]
totalDays = [xpath]:(.//div[@id='CalendarMonth__caption'])[2]//following::table[1]/tbody/tr/td
companyColumn = [xpath]://*[@id="incident-company"]/div/div/a[1]

#table configuration
tableConfigurationButton = [css]:button[title='Table Configuration'] svg
tableConfigurationTitle = [css]:div[class*=header] h4

#pagination
paginationOptionAvailable = [xpath]://div[@id="dui-pagination"]//ul//li[@class="vn-menu__item"][1]
showingText = [xpath]://span[@class='vn-pagination__information__showing']
paginationDropdownMenu = [css]:button[aria-label="Select page size"]
paginationDropdownOptionList = [css]:div[class*=Pagination] div[role=menu] ul li
paginationDropdownOptionListText = [xpath]://div[contains(@class,'options-list')]//div[contains(@class,'option')]
showingPaginationTotalCount = [xpath]://*[@class='vn-pagination__information']//a//span
paginationOptionList = [xpath]://div[contains(@class,'options-list')]//div
 
navigationItemDiv = [css]:nav[aria-label="Pagination Navigation"]
navigationItemList = [xpath]://*[@class='vn-pagination__navigation']//li
navigationItemNext = [css]:nav[aria-label="Pagination Navigation"] li:last-child
navigationItemPrevious = [css]:nav[aria-label="Pagination Navigation"] li:first-child
navigationItemFrist = [xpath]:(//*[@class='vn-pagination__navigation']//li)[2]
navigationItemLast = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()-1]
navigationItemDisabled = [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'disabled')]
navigationItemActivePage =  [css]:nav[aria-label="Pagination Navigation"] li:nth-child(2)
tableOverlay = [xpath]://div[@class='vn-table__overlay']
uniquelist_subord = [xpath]://div[2]//tbody//tr//td[4]