emailInputField = [id]:email
nextbuttonNewUI = [id]:sign-in-button
usePasswordButton = [xpath]://*[@id="use-password-button"]
passwordInputField = [id]:password
signInButton = [id]:btn-idplogin-signin
welcomePageTitle = [css]:div.intro-txt h1
cookieAccept = [xpath]://*[@id='onetrust-close-btn-container']/button
submitButtonNewUI = [id]:sign-in
pageTitle = [xpath]://div[@aria-label='User Profile']
pleaseWaitTextPage = [xpath]://div[@role="progressbar"]
Languagedropdown = [id]:vn-select-floating-ui-tek91
Termsandconditionheader = [id]:tnc-header-1
printbuttontncpage = [id]:printButtton
privacylinkontermsandcodnitionpage = [xpath]://div[@class='agreement-section']//a
acceptbutton = [xpath]:(//div[@class='agreement-section']//button[@type="button"])[1]
termsandcondtioncheckbox = [xpath]://div[@class='agreement-section']//input[@type="checkbox"]


#new login page
Newsigninbutton = [id]:sign-in-button