loginTitle = [xpath]://div[@class='panel-item-body']/h4
emailInputField = [id]:username
nextbuttonNewUI = [id]:user-name-form-submit
passwordTitleNewUI = [xpath]://div[contains(@class,'ui-panel-content')]/p
passwordInputField = [id]:password
submitButtonNewUI = [id]:sign-in
eyeicon = [xpath]://div[@id='passwordContainer']/*[name()='svg']
back = [xpath]://div[@class='text-center back-link']/a
gmailIcon = [xpath]://div[@class='social-login-buttons']/a[2]
facebookIcon = [xpath]://div[@class='social-login-buttons']/a[1]
pageTitle = [xpath]://*[contains(@class,'dui-app-bar--mixed')]/header
nextbutton = [id]:next_button
passwordTitle = [xpath]://div[@class='panel-item-body']/p
submitButton = [xpath]://button[@type='submit']

#Localization
save_language_change=[id]:modal_save_button
changeLanuageButton =[id]:btn_change_language
languageContent=languages
ENGLISH = language_en
FRENCH = language_fr
JAPANESE = language_ja
GERMAN = language_de
SPANISH = language_es
PORTUGUES_BRASIL = language_pt_BR
PORTUGUES_PORTUGAL = language_pt_PT
CHINESE = language_zh_CN
DUTCH = language_nl
SWEDISH = language_sv
ITALIAN = language_it
DANISH = language_da
FINNISH = language_fi

#Sign in locators
signInWithMicrosoftButton = [id]:azure
emailInputFieldAzureID = [css]:[name="loginfmt"]
nextButtonAzureID = [xpath]:(//input[contains(@class, 'button')])[2]
passwordTitleMicrosoftAccount = [id]:loginHeader
passwordInputFieldAzureAccount = [css]:[name="passwd"]
signInButtonAzureAccount = [xpath]:(//input[contains(@class, 'button')])
staySignedInYesButton = [xpath]:(//input[contains(@class, 'button')])[2]
acceptPermissionsButton = [id]:idBtn_Accept
nextButtonMicrosoft = [xpath]://*[@id='idSIButton9']
termsCondCheckbox = [css]:[class*=checkbox__span] input
acceptbtn = [css]:[class*='accept-button']