logTab = [id]:menu_logs
logTitle = [xpath]://*[@id="logsList"]//h4
logTitleOnBreadcrumbs = [css]:#logsList li
noLogsDisplayText = [css]:div.dui-tl tbody td[class*="no-items"]
dropdownCheckboxes = [css]:div[class*='option__multiple']
dropdownElementListLabels = [css]:div[class*='option__multiple'] a
typeList = [css]:tbody tr td:nth-child(4)
filterBoxesOfTable = [css]:tr:nth-of-type(2)>th[class*="filter"]
listOfColumnsOnTable = [css]:div.dui-tl th[class*='title']
clearSelectionOfFilters = [css]:th div svg[class*='neutral'],th div>input:not([value=''])[placeholder=''],th div svg[class*='clear-icon']
expandLogs = [css]:button[class$='vn-expand-button']
expandedLogDesc = [css]:table[class*='table__table'] tbody>tr:nth-of-type(2)
defaultcolumn = [xpath]://*[@id="createdAt"]
userList = [css]:.log-user-link
deviceList = [xpath]://a[contains(@href,'/devices')]
listTable = [css]:table[class*=table]
dateAndTimeHeader = [css]:#col-id-createdAt
clearfilter=[xpath]://button[@title='Clear']

#table configuration
tableConfigurationButton = [xpath]:.//div[@class='vn-tableconfiguration']//*[@type='button']
tableConfigurationTitle = [css]:div.vn-modal__header>h4
showAdvanceFilterButton = [xpath]://div[@class='vn-tableconfiguration__modal--showFilters']/div/a

#dateandtimecolumn		
dateAndTimeBox = [id]:createdAt
dateAndTimeList = [css]:td[headers*=col-id-createdAt]

#type column
typeBox = [id]:type
clearTypeField = [xpath]:.//div[@class='vn-select__button-group']/a/svg
typeList= [css]:td[headers*=col-id-type]
typeBoxText = [xpath]://div[@title='Devices']

#subtype column
subtypeBoxText = [xpath]://div[@title='Enrollment']

#source column
subTypeBox = [id]:source
subTypeList = [css]:td[headers*=col-id-source]

#descriptioncolumn
descriptionSearchBox = [id]:description
descriptionList = [css]:td[headers*=col-id-description]

#companycolumn
companySearchBox = [id]:company
companyList = [css]:td[headers*=col-id-company]

#severity column
severityBox = [id]:severity
severityList = [css]:td[headers*=col-id-severity]

#deviceNameColumn
assetNameSearchBox = [id]:deviceName
assetNameSearchList = [css]:td[headers*=col-id-deviceName]

#deviceSerialNumberColumn
assetSerialNumberSearchBox = [id]:logs-deviceSerialNumber
assetSerialNumberSearchList = [css]:td[headers*=col-id-deviceSerialNumber]

#deviceType column
assetTypeBox = [id]:deviceType
assetTypeList = [css]:td[headers*=col-id-deviceType]

#user column
userNameSearchBox = [id]:userName
userNameList = [css]:td[headers*=col-id-userName]
userColumn = [xpath]: //*[@id="col-id-userName"]/div[1]
userColumnValue = [css]: td[headers*="col-id-lastLoggedUser"] [class*='tablecell__content']

#sorting
dateAndTimeSortArrow = [xpath]://table//thead//tr[1]//th[1]
typeSortArrow =[xpath]://table//thead//tr[1]//th[2]
subTypeSortArrow = [xpath]://table//thead//tr[1]//th[3]
descriptionSortArrow = [xpath]://table//thead//tr[1]//th[4]
companySortArrow = [xpath]://table//thead//tr[1]//th[5]
severitySortArrow = [xpath]://table//thead//tr[1]//th[6]
assetNameSortArrow = [xpath]://table//thead//tr[1]//th[7]
assetSerialNumberSortArrow = [xpath]://table//thead//tr[1]//th[8]
assetTypeSortArrow = [xpath]://table//thead//tr[1]//th[9]
userNameSortArrow = [xpath]://table//thead//tr[1]//th[10]

titleSortArrow = [xpath]://table//thead//tr[1]//th[13]
createdBySortArrow = [xpath]://table//thead//tr[1]//th[14]
deviceModelNameSortArrow =[xpath]://table//thead//tr[1]//th[16]
updatedOnSortArrow = [xpath]://table//thead//tr[1]//th[15]
navigationItemNext = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()]/*[contains(@class,'navigation-item')]
firstPageNavigation = [css]:div.vn-table__pagination ul.vn-pagination__navigation li:nth-of-type(2) a
paginationArea = [css]:div.vn-pagination div.vn-pagination__information
tableOverlay = [xpath]://div[@class='vn-table__overlay']
tableOverlaySiteUp = [xpath]://div[contains(@class,'dui-tl')]//div[contains(@class,'table__overlay') and not (contains(@class,'loading')) and not (contains(@class,'spinner'))]

#pagination
paginationOptionAvailable = [xpath]://div[@id="dui-pagination"]//ul//li[@class="vn-menu__item"][1] 
showingText = [xpath]://span[@class='vn-pagination__information__showing']
paginationDropdownMenu = [xpath]://a[contains(@class,'vn-popover__target--down')]
paginationDropdownOptionList = [xpath]://div[contains(@class,'options-list')]//div[contains(@class,'option')]
showingPaginationTotalCount = [xpath]://*[@class='vn-pagination__information']//a//span
paginationOptionList = [xpath]://div[contains(@class,'options-list')]//div

navigationItemDiv = [xpath]://*[@class='vn-pagination__navigation']
navigationItemList = [xpath]://*[@class='vn-pagination__navigation']//li
navigationItemNext = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()]/*[contains(@class,'navigation-item')]
navigationItemPrevious = [xpath]:(//*[@class='vn-pagination__navigation']//li)[1]/*[contains(@class,'navigation-item')]
navigationItemFrist = [xpath]:(//*[@class='vn-pagination__navigation']//li)[2]
navigationItemLast = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()-1]
navigationItemDisabled = [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'disabled')]
navigationItemActivePage =  [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'page--active')]

#table
tableRow =[xpath]://tbody//tr
firstRecordOnLogsPage = [xpath]:(//button[contains(@class,'expand-button')])[1]
logsPageDescription = [xpath]:(//td[@headers='col-id-description'])[1]

logTabWorkflow = [css]:#menu_logs a

selectAllCheckbox = [xpath]://div[contains(@class,'tableheader__checkbox--expand')]//input
exportButton = [xpath]: //button[@id='export-device']
exportNotification =[xpath]: //div[contains(@class, 'toast-container vn-toast-container--bottom')]//p
notificationButton =[xpath]: //*[@id="logsList"]//div[contains(@class, 'notification-center__bell-button')]//button
downloadLogFile =[xpath]: //div[contains(@class, 'notification-center-item__extra')]//a
deviceColumnName = [id]:col-id-deviceName

#FLIP LOGS
lockeraseenableStatus= [xpath]:(//table/tbody/tr[2]/td[3]//div)[2]
expandButton= [xpath]: //*[@id="dui-container"]//table/tbody/tr[1]//td[2]//button[contains(@class,'expand-button')]