logTab = [id]:menu_logs
logTitle = [xpath]://*[@id="logsList"]//h4
logTitleOnBreadcrumbs = [css]:#logsList [class*="label"] span
noLogsDisplayText = [xpath]://tbody/tr/td/div/span
dropdownCheckboxes = [css]:[role=presentation] ul li
dropdownfortypes =[xpath]://ul[@role="listbox"]/li
dropdownElementListLabels = [css]:[role=presentation] ul li div
typeList = [xpath]:(//tbody//tr//td[3])[position() < last()]
filterBoxesOfTable = [xpath]://table/thead/tr[2]//th
listOfColumnsOnTable = [xpath]://table/thead/tr[1]/th[preceding::th]//button
clearSelectionOfFilters = [css]:[class*=clear-button]
expandLogs = [css]:[class*=table-buttons] svg
expandedLogDesc = [css]:#dui-table-sidebar
defaultcolumn = [xpath]://*[@id="createdAt"]
userList = [css]:.log-user-link
deviceList = [xpath]://a[contains(@href,'/devices')]
listTable = [xpath]:(//*[contains(@class, 'table-container')]//div)[2]
dateAndTimeHeader = [css]:#createdAt
dateAndTimedropdown = [css]:th[aria-sort='ascending']
dateAndTimedropdownclick = [css]:th[aria-sort='ascending'] button svg
clearfilter = [xpath]:(//tr//*[contains(@class,'iconButton')])[1]
firstCheckbox = [xpath]://tbody//tr[1]//td[1]//div
firstCheckboxFail = [xpath]:(//tbody//tr[1]//td[1]//div)[2]
infoIcon = [css]:button[aria-label="show-info"]
closeInformationPanel = [css]:#dui-table-sidebar button
selectFirstCheckbox = [xpath]:(//tbody//tr[1]//*[contains(@class, 'checkbox')])[2]
clearSearchBoxFilter = [css]:[class*=trailing_button]

#table configuration
tableConfigurationButton = [xpath]://*[@aria-label='Column Options']
tableConfigurationTitle = [css]:#column-options-label
showAdvanceFilterButton = [xpath]://div[@class='vn-tableconfiguration__modal--showFilters']/div/a

#dateandtimecolumn		
dateAndTimeBox = [xpath]://table/thead/tr[2]//th[2]
dateAndTimeList = [css]:tbody tr td:nth-child(2)

#type column
typeBox = [css]:div#type
clearTypeField = [css]:[class*="clear-button"]
typeListSearch= [xpath]://*[@id="type-listbox"]/..//input[@placeholder='Search']
typeBoxText = [xpath]:(//*[@id="logs"]//tbody//td[3])[1]
typeDropdownOptions = [xpath]://li[contains(@id,'type-option')]//div
typeListSearch =[xpath]://*[@id="type-listbox"]/..//input[@placeholder='Search']

#subtype column
subtypeBoxText = [xpath]:(//*[@id="logs"]//tbody//td[4])[1]
subtypeDropdownOptions = [xpath]://li[contains(@id,'source-option')]//div
subTypeListSearch= [xpath]://*[@id="source-listbox"]/..//input[@placeholder='Search']
#source column
subTypeBox = [css]:#source:nth-child(1)
subTypeList = [xpath]:(//table/tbody/tr/td[4])[position() < last()]
subTypeListSearch =[xpath]://*[@id="source-listbox"]/..//input[@placeholder='Search']

#descriptioncolumn
descriptionSearchBox = [css]:#description:nth-child(1)
descriptionList = [xpath]:(//table/tbody/tr/td[5])[position() < last()]
descriptionFirstRow = [xpath]:(//table/tbody/tr/td[5])/div
#companycolumn
companySearchBox = [css]:th div#company
companyList = [xpath]:(//table/tbody/tr/td[6])[position() < last()]
companyDropdownOptions = [xpath]://li[contains(@id,'company-option')]//div
companyBox = [css]:#company:nth-child(1)
companySearch = [xpath]://*[@id="company-listbox"]/..//input[@placeholder='Search']
#severity column
severityBox = [css]:#severity:nth-child(1)
severityList = [xpath]:(//table/tbody/tr/td[7])[position() < last()]

#deviceNameColumn
assetNameSearchBox = [css]:#deviceName:nth-child(1)
assetNameSearchList = [xpath]:(//table/tbody/tr/td[8])[position() < last()]

#deviceSerialNumberColumn
assetSerialNumberSearchBox = [css]:input#newValue
assetSerialNumberSearchList = [xpath]:(//table/tbody/tr/td[9])[position() < last()]
objectIdentifier = [xpath]://input[@id='identifier']
#deviceType column
assetTypeBox = [css]:#deviceType:nth-child(1)
assetTypeList = [xpath]:(//table/tbody/tr/td[10])[position() < last()]

#user column
userNameSearchBox = [css]:#userName:nth-child(1)
userNameList = [css]:[class*=user-link]
userColumn = [xpath]: //th[@id="userInfo"]
userColumnValue = [css]: td[headers*="col-id-lastLoggedUser"] [class*='tablecell__content']
#sorting
dateAndTimeSortArrow = [css]:#createdAt svg
typeSortArrow =[css]:#type svg
subTypeSortArrow = [css]:#source svg
descriptionSortArrow = [css]:#description svg
companySortArrow = [css]:#company  button svg
severitySortArrow = [css]:#severity svg
assetNameSortArrow = [css]:#deviceName svg
assetSerialNumberSortArrow = [css]:#deviceSerialNumber svg
assetTypeSortArrow = [css]:#deviceType svg
userNameSortArrow = [css]:#userName svg

titleSortArrow = [xpath]://table//thead//tr[1]//th[13]
createdBySortArrow = [xpath]://table//thead//tr[1]//th[14]
deviceModelNameSortArrow =[xpath]://table//thead//tr[1]//th[16]
updatedOnSortArrow = [xpath]://table//thead//tr[1]//th[15]
navigationItemNext = [xpath]:(//*[contains(@class,'TablePagination')]//li)[last()]
firstPageNavigation = [css]:div.vn-table__pagination ul.vn-pagination__navigation li:nth-of-type(2) a
paginationArea = [css]:[class*="TablePagination"] > div > div:nth-child(1)
tableOverlay = [css]:[class*="table-list "]
tableOverlaySiteUp = [xpath]://div[contains(@class,'dui-tl')]//div[contains(@class,'table__overlay') and not (contains(@class,'loading')) and not (contains(@class,'spinner'))]

#pagination
paginationOptionAvailable = [xpath]://div[@id="dui-pagination"]//ul//li[@class="vn-menu__item"][1] 
showingText = [xpath]://span[@class='vn-pagination__information__showing']
paginationDropdownMenu = [xpath]:[class*="TablePagination"] > div > div > button
paginationDropdownOptionList = [css]:[class*=TablePagination] [class*=ContextualMenu] ul li
showingPaginationTotalCount = [css]:[class*="TablePagination"] > div > div:nth-child(1)
paginationOptionList = [css]:[class*=TablePagination] [class*=ContextualMenu] ul li

navigationItemDiv = [css]:[class*="TablePagination"] nav
navigationItemList = [css]:[class*="TablePagination"] nav li
navigationItemNext = [xpath]:(//*[contains(@class,'TablePagination')]//li)[last()]
navigationItemPrevious = [css]:[class*="TablePagination"] nav li:nth-child(1)
navigationItemFrist = [css]:[class*="TablePagination"] nav li:nth-child(2)
navigationItemLast = [xpath]:(//*[contains(@class,'TablePagination')]//li)[last()-1]
navigationItemDisabled = [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'disabled')]
navigationItemActivePage =  [css]:[class*="TablePagination"] [aria-label*="Current Page"]

#table
tableRow =[xpath]://tbody//tr
firstRecordOnLogsPage = [css]://*[contains(@class,'dui-es-table-container')]//tbody/tr[1]/td[2]/a
logsPageDescription = [xpath]:(//*[contains(@class,'dui-es-row-info-container')]//div[contains(@class,'dui-word-break')])[1]
logTabWorkflow = [css]:#menu_logs a

selectAllCheckbox = [css]:[class*=table__checkbox]:first-child input
exportButton = [xpath]://*[contains(@class,'table')]/button[@id='export-device']
exportNotification = [xpath]://*[@id="dui-app-scroll"]/div[4]/div/div
notificationButton = [css]:[class*=help-support]+button
notificationButtonforlogs = [xpath]:(//*[contains(@class,'dui-margin-right')])[2]
downloadLogFile = [xpath]:(//*[@role='listbox']//li[2])[last()]
downloadLogsFile = [xpath]: //div[@class="css-1wvkna1"]/ul/li[2]
deviceColumnName = [css]:th#deviceName
firstNotification = [xpath]://*[@id='dui-notifications']//ul/li[1]
hamburgerMenuOnNotification = [xpath]://*[@id='dui-notifications']//ul/li[1]//button
openLogsHyperlink = [xpath]:(//*[@role='listbox']//li[3])[2]

#FLIP LOGS

checkBox=[xpath]: (//tbody/tr/td//input[@type="checkbox"])[1]
iIcon= [xpath]: //div[contains(@class,'table-right-buttons')]/button
lockeraseenableStatus= [xpath]: (//div[@id='dui-table-sidebar']//div[contains(@class,'info-wrapper')]/div[2])[2]



#LOG ROW OBJECTS
logsPageDescriptionFirstRow = [xpath] : //*[contains(@class,'dui-table-list dui-es-table-with-config')]//tr[1]//div[contains(@class,'dui-word-break')][1]
clearSelectionButton = [xpath]: //*[@aria-label='Clear Filters']
logsPageTypeFirstRow = [xpath] : //*[contains(@class,'dui-table-list dui-es-table')]//table//tr[1]/td[3]
logsPageSubTypeFirstRow = [xpath] : //*[contains(@class,'dui-table-list dui-es-table')]//table//tr[1]/td[4]
logsPageLevelFirstRow = [xpath] : //*[contains(@class,'dui-table-list dui-es-table')]//table//tr[1]/td[7]
