selectCheckBox = [xpath]://input[@name='agree-tnc-ru']
learnMoreText = [xpath]:(//button[contains(@class,'welcome-button')]/span)[1]
tryItFree = [xpath]://div[contains(@class,'welcome-action')]/button[1]
consentCheckBox = [xpath]://*[@id='upgradeConsentCheckbox']
acceptButton = [xpath]://*[@id='idSIButton9'] 
checkboxesOnWidget = [xpath]://*[@class='req-list']/div//span/input[contains(@id,'checkbox')]
harddiskhealthCheckbox = [xpath]:(//*[@id='azure_onboarding']//div[@class='widget-screen']//input)[2]
labelsOfCheckboxesinWidget = [xpath]://div[@class='req-list']/div//span[2]
nextButton = [xpath]://div[@id='azure_onboarding']//div[2]//button
videolink = [css]:[src='https://player.vimeo.com/video/463032646']
bannerSubHeading = [xpath]:(//*[@id='azure_onboarding']/div/div[2]//p)[1]
bannerHeading = [xpath]:(//*[@id='azure_onboarding']/div/div[2]//p)[2]
hangonMessage = [xpath]://*[@id='azure_onboarding']//p
bannerDescription = [xpath]://*[@id='azure_onboarding']/div/div[2]//div[contains(@class,'title')]/../div[2]/span
message = [xpath]://*[@id='azure_onboarding']/div/div[2]//div[contains(@class,'note')]/div/p
privacyLink = [xpath]://a[contains(@href,'privacy')]
termslink = [xpath]://a[contains(@href,'terms-and-conditions')]
agreementMessage = [xpath]://*[@id='azure_onboarding']/div/div[2]//div[contains(@class,'agreement')]//span[2]/span
termsCondtext = [css]:[class*=checkbox__span]+span
termsCondCheckbox = [css]:[class*=checkbox__span] input
acceptbtn = [css]:[class*='accept-button']
cancelbtn = [css]:[class*='cancel-button']
yesSignOutbtn = [css]:[class*='cancel-modal-action'] [class*='accept-button']
noBtn = [css]:[class*='cancel-modal-action'] [class*='cancel-button']
cancelheading = [css]:[class*='modal--content'] h4
signOutMsg = [css]:[class*='terms-modal-content'] span
termsConditionsHeading = [css]:[class*='tnc-modal'] h3
termsCondRussiaText = [xpath]:(//*[@class='dui-service-level-agreement']/div/div//p)[51]
russiaHeading = [xpath]:(//*[@class='dui-service-level-agreement']/div/div//h5)[27]
russiaText = [xpath]:(//*[@class='dui-service-level-agreement']/div/div//p)[59]
russiaLinkText = [xpath]://*[@class='dui-service-level-agreement']/div/div//p[59]//a
companyTitle = [css]:#dui-app-container h5
companyScreenDescription = [css]:#dui-app-container h5+span
companyNameLabel = [css]:[id=company-name-label]
companyNameText = [css]:[id=company-name-label]+div input
companySizeLabel = [css]:[class=company-size-dropdown] label
companySizedropdown = [css]:[class=company-size-dropdown] span:nth-child(1)
companySizelistvalues = [css]:[role='presentation'] ul li
industryLabel = [css]:[class=industry-dropdown] label
industrydropdown = [css]:[class=industry-dropdown] span:nth-child(1)
industrylistValues = [css]:[role='listbox'] li
countryLabel = [css]:[class=country-list-dropdown] label
countrydropdown = [css]:[class=country-list-dropdown] [id=countryList] span
countrylistValues = [css]:[role='listbox'] li
companyNextbtn = [css]:[id=submit-company-form]
companyBackbtn = [css]:[id=cancel-company-form]
companyCity = [css]:[id=company-city]
companyCityLabel = [css]:[id=company-city-label]
userNameAzure = [xpath]://*[@name='loginfmt']
passwordAzure = [xpath]://*[@name='passwd']
nextButtonAzure = [id]:idSIButton9
signInButton = [xpath]://div[contains(@class,'dui-welcome-header')]//button[contains(@class,'signin')]
signInMicrosoftButton = [xpath]://div[contains(@class,'dui-welcome-header')]//button[1]

#New Marketing Page
bannerTile = [xpath] : (//*[@class='bannertitle'])[1]
signUpCard = [xpath] : (//*[@class='bannerheading'])[1]
footerText = [xpath] : (//*[@id='azure_onboarding']/div/div[2]//p)[2]/span
tryitNowButton = [xpath] : (//*[@id='azure_onboarding']//button)[1]
learnmoreTitle = [xpath] : //*[@class='learmoretitle']
learmoreButton = [css] : [class*='learnmore'] button
hardwareText = [css] : [class*='hardware'] h6
applicationInsightsText = [css] : [class*='application insight'] h6
employeeInsightsText = [css] : [class*='employee insight'] h6
supportedPlatformsText = [css] : [class*='supported-platforms'] h3
windowsheadingText = [xpath] : (//*[contains(@class,'supported-platforms')]//h6)[1]
macOSheadingText = [xpath] : (//*[contains(@class,'supported-platforms')]//h6)[2]
chromeOSheadingText = [xpath] : (//*[contains(@class,'supported-platforms')]//h6)[3]
mobileheadingText = [xpath] : (//*[contains(@class,'supported-platforms')]//h6)[4]
windowsText = [xpath] : (//*[contains(@class,'supported-platforms')]//p)[1]
macOSText = [xpath] : (//*[contains(@class,'supported-platforms')]//p)[2]
chromeOSText = [xpath] : (//*[contains(@class,'supported-platforms')]//p)[3]
mobileText = [xpath] : (//*[contains(@class,'supported-platforms')]//p)[4]
privacyLinkNew = [css] : #footer-terms-n-conditions a
termslinkNew = [xpath] : (//*[contains(@class,'bannerfooter')]//a)[1]
bannerTextNew1 = [xpath] : (//*[contains(@class,'bannerdescription')])[1]
bannerTextNew2 = [xpath] : (//*[contains(@class,'bannerdescription')])[2]
bannerTextNew3 = [xpath] : (//*[contains(@class,'bannerdescription')])[3]
signUpNowText = [xpath] : (//*[@class='bannerheading'])[3]
tryItNowbtn = [xpath] : (//*[contains(@class,'tryitfree-button')])[2]