#step 1 properties
hpIcon = [xpath]://div[@id = 'dui-side-icon']//*[name()='svg']
language = [xpath]://div[@id='country_dropdown']
welcomeText = [css]:h4.welcome-text
welcomeIcon = [xpath]://div[@id='dui-welcome-icon-container']/img
accountSetupDescription = [xpath]:(//div[contains(@class,'dui-registration-description ')]//div[@class='stepper_data'])[1]
accountSetupTitle = [xpath]://div[@class="stepper_data"]/h5
signupTextLine1 = [css]:h6[class*=line-1]
signupTextLine2 = [css]:h6[class*=line-2]
accountSteupNext = [xpath]://div[contains(@class,'main-circle-dark--start')]//*[name()='svg']
startButton = [id]:btn_start

#Common properties
stepImage = [css]:.img-container
stepBannerDescription = [css]:.dui-info-left-panel h6

label1 = [xpath]://label[@class="form_label"][1]
label2 = [xpath]://label[@class="form_label"][2]
label3 = [xpath]://label[@class="form_label"][3]
label4 = [xpath]://label[@class="form_label"][4]
label5 = [xpath]://label[@class="form_label"][5]
label6 = [xpath]://label[@class="form_label"][6]
label7 = [xpath]://label[@class="form_label"][7]
stepHeader = [css]:.dui-info-right-panel h4
nextButton = [id]:btn_next
FirstName = [id]:first-name
LastName = [id]:last-name
EmailName = [id]:email
PhoneName = [id]:phone-number
subscriptionKeyTextBox = [id]:subscription-key
completeIcon = [id]:dui-complete-icon-container
completeText = [css]:.completed-text
retryButton = [id]:btn_retry
skipButton = [id]:btn_skip


#Add user step properties
helperText = [css]:.txt-description
helperCount = [css]:.count-remaining
addUsers = [xpath]://*[@id="add_user_form"]


#Company Information Properties
companyNameTextBox = [id]:company-name
dropDown = [id]:select-country
dropDownList = [xpath]://div[contains(@class,'options-list__scroll')]/div
acknowledgeCheckbox = [xpath]://input[@name='agree-tnc']
acknowledgeCheckboxRussia = [xpath]://input[@name='agree-tnc-ru']
acknowledgeText = [css]:span[class*=checkbox__span-text]


#Add partner step properties
partnerContactInformation = [xpath]://p[@class="txt-default"]

completeLineOneMessage = [xpath]://div[contains(@class,'completed-screen')]//h6[@class='completed-line1']
completeLineTwoMessage = [xpath]://div[contains(@class,'completed-screen')]//h6[@class='completed-line2']
subscriptionKeyError = [xpath]://div[contains(@class,'form-field')][1]/p
companyNameError = [xpath]://div[contains(@class,'form-field')][2]/p
termsAndConditionError = [xpath]://div[contains(@class,'form-field')][4]/p

firstNameError = [xpath]://div[contains(@class,'form-field')][1]/p
lastNameError = [xpath]://div[contains(@class,'form-field')][2]/p
emailError = [xpath]://div[contains(@class,'form-field')][3]/p
phoneNumberError = [xpath]://div[contains(@class,'form-field')][4]/p
hpTermsAndConditionLinkWf = [id]:link_tnc
hpPrivacyStatement = [id]:link-pvs
hpPrivacyStatementPageHeading = [xpath]://h2[@class='font-lh3']
printButtonTermsAndConditionsPage = [id]:printButtton
hpTermsAndConditionPageHeading = [xpath]://h4[@class='title']
spinner = [xpath]://div[contains(@class,'spinner')]//*[name()='svg']

compName = [xpath]://div[@class="dui-info-right-panel"]//div[1]/div[1]/input
lastName = [xpath]://div[@class="dui-info-right-panel"]//div[2]/div/input
compEmail = [xpath]://div[@class="dui-info-right-panel"]//div[3]/div/input
phoneNumber = [xpath]://div[@class="dui-info-right-panel"]//div[4]/div/input

country_list= [xpath]://*[@id="select-country-option-1"]
partnerName = [xpath]://div[@class="dui-info-right-panel"]//div[1]/div/input
partnerFirstName1= [xpath]://div[@class="dui-info-right-panel"]//div[2]/div/input
partnerLastName=[xpath]://div[@class="dui-info-right-panel"]//div[3]/div/input
partnerEmail=[xpath]://div[@class="dui-info-right-panel"]//div[4]/div/input
partnerPhoneNumber=[xpath]://div[@class="dui-info-right-panel"]//div[5]/div/input

it_admin_header= [xpath]:(//div[contains(@class,'dui-registration-description ')]//div[@class='stepper_data'])[2]/h5
it_admin_description= [xpath]:(//div[contains(@class,'dui-registration-description ')]//div[@class='stepper_data'])[2]/p[1]
user_header=[xpath]:(//div[contains(@class,'dui-registration-description ')]//div[@class='stepper_data'])[3]/h5
user_decription=[xpath]:(//div[contains(@class,'dui-registration-description ')]//div[@class='stepper_data'])[3]/p[1]
channel_partner_header=[xpath]:(//div[contains(@class,'dui-registration-description ')]//div[@class='stepper_data'])[4]/h5
channer_partner_decription=[xpath]:(//div[contains(@class,'dui-registration-description ')]//div[@class='stepper_data'])[4]/p[1]
subscription_key= [xpath]://*[@name='subscription-key']
companyNameOnPopup = [xpath]://*[@name='company-name']
addressOnPopup= [xpath]://*[@name='address']
cityOnPopup= [xpath]://*[@name='city']
stateOnCompPopup= [xpath]://*[@name='state']
zipCodeOnCompPopup= [xpath]://*[@name='postal-code']
countrySelectOnPopup = [xpath]://*[@id="select-country"][1]