#Onboarding Button
Onboardingbutton = [xpath]://div[contains(@class, 'wex-checklist-toggle-btn')]

#onboarding checklist header
onboardingchecklistheader = [xpath]://div[contains(@class, 'wex-checklist-menu-section-header')]

#First mandatory section
firstsectiontitle = [xpath]://div[contains(@class,'wex-checklist-menu-section-title')]//li[text()='First steps']

#All coachmarks
coachmarksclosebutton = [xpath]:(//button[contains(@aria-label,'Close coachmark')])[2]
coachmarknextbutton = [xpath]://button[contains(@aria-label,'Next')]
coachmarkspreviousbutton = [xpath]://button[contains(@aria-label,'Previous')]
coachmarkscloseontick = [xpath]://div[contains(@class,'css-n4uj7i')]//button[@aria-label='Close coachmark']
Coachmarkpagenumber = [id]:pcs-pagination


# Add devices section flow
Coachmarkheaderadddevices = [id]:add-device-title
coachmarkstextadddevices = [id]: add-device-desc
coachmarktextnextclickadddevices = [id]:add-device-next-step
letsaddfirstdevice = [css]:#wex_checklist_item_addDevices > li > span:first-child > div > div:last-child
letsaddfirstdevicecheckmark = [css]:#wex_checklist_item_addDevices > li > span:last-child .icon-checkmark
letsadddevicesclick = [id]:wex_checklist_item_addDevices

adddevicescoachmarksheader = [id]:addDeviceNew-addDevices
adddevicescoachmarksdescription = [xpath]:(//div[@id='addDevicesNew-pcs']//p)[1]
adddevicescoachmarksnextstepdescription = [xpath]:(//div[@id='addDevicesNew-pcs']//p)[2]
adddevicescoachmarksfirstcoachmarkscount = [xpath]://div[contains(text(),'1 of 4')]
devicesextensionbutton = [xpath]://*[@role="Devices"]/div/button[2]
pcsclick = [xpath]:(//*[contains(@id,'menu')]/span[contains(text(),'PCs')])[1]
pcpegination = [id]:pcs-pagination

addnewdevicescoachmarksdescription = [id]:add-device-desc
addnewdevicescoachmarksnextstepdescription = [id]:add-device-next-step
adddevicescoachmarkssecoundcoachmarkscount = [xpath]://div[contains(text(),'2 of 4')]
adddevicepegination = [id]:addDevice-pagination

addbuttonclick = [xpath]://div[@id='action_button']//button[@id='download-client-software']
adddevicestelemetrycoachmarksdescription = [xpath]:(//div[@id='addDevicesNew-pcs-telemetry']//p)[1]
adddevicestelemetrycoachmarksnextstepdescription = [xpath]:(//div[@id='addDevicesNew-pcs-telemetry']//p)[2]
adddevicescoadddevicescoachmarksthirdcoachmarkscount = [xpath]://div[contains(text(),'3 of 4')]
telemetrycardclick = [id]:card-TELEMETRY
telemetrypegination = [id]:telemetry-pagination

telemetricdescription = [id]:addDevicesNew-agent
adddevicescoachmarklastcoachmarkscount = [xpath]://div[contains(text(),'4 of 4')]
agentpegination = [id]:agent-pagination


#invite you team section
coachmarkheaderadduser= [id]:add-user-title
coachmarktextadduser = [id]:addUser-next-step
inviteyouteam = [css]:#wex_checklist_item_addUser > li > span:first-child > div > div:last-child
inviteyourteamcheckmark = [css]:#wex_checklist_item_addUser > li > span:last-child .icon-checkmark
inviteuserclick = [id]:wex_checklist_item_addUser
Adduserclick = [id]:users
inviteuserbuttonclick = [id]:btn_user_add
Cancelbuttononadduserpopup = [id]:btn_cancel
coachmarkheaderadduserbutton= [id]:add-user-btn-title
coachmarktextadduserbutton = [id]:addUser-add-next-step

inviteuserheadercoachmark= [id]:addUser-title
inviteuserdescription = [xpath]:(//div[@id='addUser-accountManagement']//p)[1]
inviteuserdescriptionstep = [xpath]:(//div[@id='addUser-accountManagement']//p)[2]
inviteuserdescriptionstepcount = [xpath]:[xpath]://div[contains(text(),'1 of 3')]
Accountmanagementpegination = [id]:accountManagement-pagination

addinviteuserdescription = [xpath]:(//div[@id='addUser-usersList']//p)[1]
addinviteuserdescriptionstepcount = [xpath]:[xpath]://div[contains(text(),'2 of 3')]
userlistpegination = [id]:usersList-pagination

addinviteuserbuttondescription = [xpath]:(//div[@id='addUser-add-next-step']//p)[1]
addinviteuserbuttonnextdescription = [xpath]:(//div[@id='addUser-add-next-step']//p)[2]
addinviteuserbuttondescriptionstepcount = [xpath]:[xpath]://div[contains(text(),'2 of 3')]
adduserpegination = [id]:addUser-pagination

#company profile 
coachmarkheaderaccountmanagement = [id]:complete-profile-title
coachmarktextaccountmanagement  =  [id]:complete-profile-desc
coachmarknextclickaccountmanagement =  [id]:complete-profile-next-step
completeCompanyProfile = [css]:#wex_checklist_item_completeCompanyProfile > li > span:first-child > div > div:last-child
completeCompanyProfilecheckmark = [css]:#wex_checklist_item_completeCompanyProfile > li > span:last-child .icon-checkmark
companyprofileclick = [id]:wex_checklist_item_completeCompanyProfile
accountmanagementtab = [id]:menu_accountManagement
coachmarkheadercompanyprofile = [id]:complete-profile-title
coachmarktextcompanyprofile = [id]:set-up-profile-desc

companyprofileheader = [id]:complete-profile-title
companyprofiledescription = [id]:complete-profile-desc

#Setup integration
coachmarkheaderintegration = [id]:integration-title
coachmarkstextintegration = [id]:integrations-desc1
coachmarksnextintegration = [id]:integrations-desc2
setupIntegrations = [css]:#wex_checklist_item_setupIntegrations > li > span:first-child > div > div:last-child
setupIntegrationscheckmark = [css]:#wex_checklist_item_setupIntegrations > li > span:last-child .icon-checkmark
setupintergationclick = [id]:wex_checklist_item_setupIntegrations
setupintegrationtab = [id]:menu_integrations
coachmarksheaderintegrationpage = [id]:integrations-browse-title
coachmarkstextintegrationpage = [id]:integrations-browse-desc

integrationcoachmarksheader = [id]:setupIntegrations-title
integrationcoachmarksdesc = [id]:integrations-desc1
integrationcoachmarksdesc2 =[id]:integrations-desc2
setupintegrationpegination = [id]:setupIntegrations-pagination
integrationsecondcoachmarkdesc = [id]:integrations-browse-desc
browsepegintaion = [id]:browseIntegrations-pagination

#discover more onboarding checklist
discovermoretitle = [xpath]://div[contains(@class,'wex-checklist-menu-section-title')]//li[text()='Discover more']

#imporve Expericene score
coachmarkheadersystemhealth = [id]:	improve-score-title
coachmarkstextsystemhealth = [id]:improve-score-desc
coachmarksnextsystemhealth = [id]:system-health-next-step
improveExpScore = [css]:#wex_checklist_item_improveExpScore > li > span:first-child > div > div:last-child
improveExpScorecheckmark = [css]:#wex_checklist_item_improveExpScore > li > span:last-child .icon-checkmark
systemhealthclick = [xpath]://div[contains(@class,'cat-systemHealth')]//li//button
imporveexperincedisbaled = [xpath]://div[@id='wex_checklist_item_improveExpScore']//li[@role='menuitem']
coachmarksheadersystemhealthscore = [id]:health-score-title
coachmarkstextsystemhealthscore = [id]:system-health-desc

improveexperiencescoreclick = [id]:wex_checklist_item_improveExpScore
improverexpcoachmarksheader = [id]:improveExpScore-title
improveexpcoachmarksdesc1 = [id]:improve-score-desc
improvenextstepcoachmarks = [id]:system-health-next-step
improvescroepegination = [id]:improveYourScore-pagination

systeamhealthdesc = [xpath]:(//div[@id='improveExpScore-systemHealthScore']//p)[1]
systemhealthnextstepcoachmarks=[id]:system-health-next-step
systemhealythpegination = [id]:systemHealthScore-pagination

recomendedactiondesc = [id]:recommended-actions-desc
recomendedactiondescnextstep = [id]:recommended-actions-next-step
recomendedactionlist [id]:home-recommended-actions-list
recomendedactionpegination = [id]:recommendedActions-pagination

#custom pulse
coachmarkfmtitle= [id]:survey-&-pulses-title
coachmarksfmtext= [id]:survey-pulses-desc
coachmarkspulseheader = [id]:survey-&-pulses-title-2
coachmarksoulsetext = [id]:emp-dashboard-desc
coachmarkscreatbuttontitle: [id]:create-custom-pulses-title
coachmarkscreatebuttontext: [id]:create-pulses-desc
coachmarkscustompulsetitle : [id]:custom-pulses-title
coachmarkscustomerpulsetext : [id]:custom-pulses-next-step
createCustomPulse = [css]:#wex_checklist_item_createCustomPulse > li > button > span:first-child > div > div:last-child
createCustomPulsecheckmark = [css]:#wex_checklist_item_createCustomPulse > li > span:last-child .icon-checkmark
createcustomepulseclick = [id]:wex_checklist_item_createCustomPulse
employeeengagementtab = [xpath]://li[@id='menu_employeeEngagement']//button[@aria-label='Action Button']
pulseclick = [id]:menu_employeeEngagement_pulses
createbuttonpulseclick = [xpath]:(//div[@class='pulse-surveys-list-card']//button)[1]

custompulseclick = [xpath]:(//div[@id='custom_pulse']//div)[1]
customepulsecoachmarkheader = [id]:createCustomPulse-title
customerpulsefirstcoachmarkdesc = [id]:emp-dashboard-desc
customerpulsenextstep = [id]:pulses-next-step
pulselistpegination = [id]:pulseList-pagination

createbuttoncoachmarknextstep = [id]:wcm-createCustomPulse-createCustomPulse
createbuttoncoachmarksdesc = [id]:createPulse-body
createpulsepegination = [id]:createPulse-pagination
createcustomepulsepegination = [id]:createCustomPulse-pagination

pulsecontentdesc =[id]:createCustomPulse-pulseContent
pulseschduledesc = [id]:createCustomPulse-pulseSchedule
pulsescedulepegination = [id]:pulseSchedule-pagination
pulseaudiencedesc = [xpath]:(//div[@id='createCustomPulse-pulseAudience']//p)[1]
pulsaudiencecochmarkslist = [xpath]://p[@class='coachmark-list ']
pulseaudiencepegination = [id]:pulseAudience-pagination
pulsepublichbutton = [id]:createCustomPulse-pulsePublish
pulsecoachmarknumber = [xpath]:(//div[contains(@class, "label-small")])[8]
pulsecontentpegintaion = [id]:pulseContent-pagination
pulsepublishpegination = [id]:pulsePublish-pagination

#sentiment pulse
coachmarkssentimentpulsetitle : [id]:create-pulse-text
coachmarkssentimentpulsetext : [id]:sentiment-pulse-next-step
createSentimentPulse = [css]:#wex_checklist_item_createSentimentPulse > li > button > span:first-child > div > div:last-child
createSentimentPulsecheckmark = [css]:#wex_checklist_item_createSentimentPulse > li > span:last-child .icon-checkmark
cretesentimentpulseclick  = [id]:wex_checklist_item_createSentimentPulse

Sentimentcoachmarksheader = [id]:createSentimentPulse-title
sentimentfirstcoachmarksdesc = [id]:sentiment-emp-dashboard-desc
createbuttondesc = [id]:wcm-createSentimentPulse-createPulse
sentimentpulsecoachmarknextstep = [id]:wcm-createSentimentPulse-createSentimentPulse
sentimentpulseclick = [xpath]:(//div[@id='sentiment_pulse']//div)[1]
sentimentpulsepegination = [id]:createSentimentPulse-pagination

sentimentpulsecontentdesc = [id]:wcm-createSentimentPulse-pulseContent
sentimentpulseschduledesc = [id]:wcm-createSentimentPulse-pulseSchedule

sentimentpulseaudiencedesc = [id]:wcm-createSentimentPulse-pulseAudience
sentimentpulsepublishbutton = [id]:wcm-createSentimentPulse-pulsePublish

sentimentpulsenextbutton = [xpath]:(//button[contains(@aria-label,'Next')])[2]
sentimentpulsepreviousbutton = [xpath]:(//button[contains(@aria-label,'Previous')])[2]

#pulse overview
coachmarkspulseoverviewtitle: [id]:pulse-survey-overview-title
coachmarkspulseoverviewtext : [id]:pulse-survey-overview-desc
understandPulseResults = [css]:#wex_checklist_item_understandPulseResults  > li > span:first-child > div > div:last-child
understandPulseResultscheckmark = [css]:#wex_checklist_item_understandPulseResults  > li > span:last-child .icon-checkmark
understandpulseclick = [id]:wex_checklist_item_understandPulseResults

#help and support
coachmarkfeedbacktitle = [id]:provide-feedback-title
coachmarksfeedbacktext = [id]:provide-feedback-desc
checklist_item_getHelp = [css]:#wex_checklist_item_getHelp > li > button > span:first-child > div > div:last-child
checklist_item_getHelpcheckmark = [css]:#wex_checklist_item_getHelp > li > span:last-child .icon-checkmark
helpandsupportclick = [id]:wex_checklist_item_getHelp
coachmarkhelpandsupporttitleonappbar = [id]:help-and-support-title
coachmarkhelpandsupportdescriptiononappbar = [id]:help-desc

gethelpsupportonbardingtitle = [id]:getHelp-title
helpandsupportfirstcoachmarkdesc = [xpath]:(//div[@id='getHelp-helpSupport']//p)[1]
getsupportcoachmarkheader1 = [xpath]://div[@id='helpSupport-title']//span
getsupportcoachmarkheader2 = [xpath]://div[@id='support-title']//span
helpandsupportfirstcoachmarknextstep = [xpath]:(//div[@id='getHelp-helpSupport']//p)[2]
helpandsupportnextbutton = [xpath]:(//button[contains(@aria-label,'Next')])[2]
helpandsupportpegination = [id]:helpSupport-pagination
supportpegination = [id]:support-pagination
helpandsupportcoachmarksdesc = [id]:getHelp-support
closecoachmarkhelpandsupport = [xpath]://button[contains(@aria-label,'Close coachmark')]

#Stay Up To date Alerts

noalertstile = [xpath]://div[@class='partner-ra-empty-state home-no-alerts-container']
Recommendedactiontile = [xpath]://div[@class='recommended-actions']
stayuptodatealertsonboarding = [id]:wex_checklist_item_customizeAlerts
stayuptodatealertsonboardingtitle = [css]:#wex_checklist_item_customizeAlerts > li > span:first-child > div > div:last-child

stayuptodatetitle = [id]:customizeAlerts-title
stayuptodatecoachmarkdesc = [xpath]:(//div[@id='customizeAlerts-viewActive']//p)[1]
stayuptodatecoachmarknextstep = [xpath]:(//div[@id='customizeAlerts-viewActive']//p)[2]
alertstabexpandbutton = [xpath]://li[@role='Alerts']//button[1]

activealertslink = [id]:menu_alerts_alertsListView
stayuptodatealertselectcoachmarkdesc = [xpath]:(//div[@id='customizeAlerts-activeAlerts']//p)[1]
stayuptodatealertselectcoachmarknextstep = [xpath]:(//div[@id='customizeAlerts-activeAlerts']//p)[2]

alertsclick = [xpath]:(//div[@class='aa-alert-title']//div)[1]
alertslaststepcoachmarksdesc = [id]:customizeAlerts-alertDetails


#Add a script

Addscriptonboardongtitle = [id]:addScripts-title
onboardingchecklistaddscriptclick = [id]:wex_checklist_item_addScripts
Addscriptcoachmarksheader = [id]:script-title


Addscriptselectcoachmarkdesc = [xpath]:(//div[@id='script-body']//p)[1]
Addscriptselectcoachmarknextstep = [xpath]:(//div[@id='script-body']//p)[2]
scriptpegination = [id]:script-pagination

remediationstoggle = [xpath]://li[@role='Remediations']//button[1]
remediationclick = [id]:menu_remediations_remediationsScripts

addscripttitle = [id]:add-title
addscriptbuttonselectcoachmarkdesc = [xpath]:(//div[@id='addScripts-add']//p)[1]
addscriptbuttonselectcoachmarknextstep = [xpath]:(//div[@id='addScripts-add']//p)[2]
addpegintaion = [id]:add-pagination

addscriptsbutton = [xpath]://div[@id='action_button']//button[@id='add-script']

filuploadtitle = [id]:upload-title
PS1fileuploadselectcoachmarkdesc = [xpath]:(//div[@id='addScripts-upload']//p)[1]
PS1fileuploadselectcoachmarknextstep = [xpath]:(//div[@id='addScripts-upload']//p)[2]
uploadpegination = [id]:upload-pagination

browseInputaddscript = [xpath]://*[@name='scriptFile']
nextButtonaddscript = [xpath]://button[@id='btn_next']
propspegination = [id]:props-pagination
infopegination = [id]:info-pagination
listpegination = [id]:list-pagination
actionpagination = [id]:action-pagination
activitypagination = [id]:activity-pagination


proptitle = [id]:props-title
propsselectcoachmarkdesc = [xpath]:(//div[@id='addScripts-props']//p)[1]
propsselectcoachmarknextstep = [xpath]:(//div[@id='addScripts-props']//p)[2]

infotitle = [id]:info-title
infosselectcoachmarkdesc = [xpath]:(//div[@id='addScripts-info']//p)[1]
infosselectcoachmarknextstep = [xpath]:(//div[@id='addScripts-info']//p)[2]

scriptNameonboarding = [xpath]://input[@aria-label='script-name']
scriptSynopsisonboarding = [xpath]: //input[@aria-label='script-synopsis']
scriptDescriptiononboarding = [xpath]://textarea[@aria-label='script-description']

Addbuttonsciptpage = [id]:btn_finish

listtitle = [id]:list-title
listsselectcoachmarkdesc = [xpath]:(//div[@id='addScripts-list']//p)[1]
listsselectcoachmarknextstep = [xpath]:(//div[@id='addScripts-list']//p)[2]

scriptdetailsclick = [xpath]:(//div[@class='wex-value-field-truncated']//div//a)[1]

actiontitle = [id]:action-title
actionsselectcoachmarkdesc = [xpath]:(//div[@id='action-body']//p)[1]
actionsselectcoachmarknextstep = [xpath]:(//div[@id='action-body']//p)[2]

activitytitle = [id]:activity-title
activitysselectcoachmarkdesc = [xpath]:(//div[@id='addScripts-activity']//p)[1]


#Troubleshoot devices Issue
Troubleshootdevicetitle = [id]:deviceIssues-title
troubleshootonoardingchecklist = [id]:wex_checklist_item_deviceIssues

troubleshootpcstitle = [id]:pcs-title
troubleshootdeviespcssselectcoachmarkdesc = [xpath]:(//div[@id='deviceIssues-pcs']//p)[1]
troubleshootdeviespcssselectcoachmarknextstep = [xpath]:(//div[@id='deviceIssues-pcs']//p)[2]

troubleserialtitle = [id]:serial-title
troubleserialselectcoachmarkdesc = [xpath]:(//div[@id='deviceIssues-serial']//p)[1]
troubleserialselectcoachmarknextstep = [xpath]:(//div[@id='deviceIssues-serial']//p)[2]
pcsserialnumberclick = [xpath]:(//div[@class='wex-value-field-truncated']//div//a)[1]
Serialpagination = [id]:serial-pagination


timelinetitle = [id]:timeLine-title
timelineselectcoachmarkdesc = [xpath]:(//div[@id='deviceIssues-timeline']//p)[1]
timelineselectcoachmarknextstep = [xpath]:(//div[@id='deviceIssues-timeline']//p)[2]
timelineclick = [id]:timeline
timelinepegination = [id]:timeLine-pagination

healthprotectiontitle = [id]:health-title
healthprotectionselectcoachmarkdesc = [xpath]:(//div[@id='deviceIssues-health']//p)[1]
healthprotectionselectcoachmarknextstep = [xpath]:(//div[@id='deviceIssues-health']//p)[2]
healthclick= [id]:health-protection
healthpagination = [id]:health-pagination

softwaretitle = [id]:software-title
softwareselectcoachmarkdesc = [xpath]:(//div[@id='deviceIssues-software']//p)[1]
softwareselectcoachmarknextstep = [xpath]:(//div[@id='deviceIssues-software']//p)[2]
softwarepegination = [id]:software-pagination









