#step 1 properties
hpIcon = [xpath]://div[@id = 'dui-side-icon']//*[name()='svg']
language = [xpath]://div[@id='country_dropdown']/div
welcomeText = [css]:h4.welcome-text
welcomeIcon = [xpath]://div[@id='dui-welcome-icon-container']/img
accountSetupDescription = [css]:span[class*=main-description]
accountSetupTitle = [css]:span[class*=main-label]
signupTextLine1 = [css]:h6[class*=line-1]
signupTextLine2 = [css]:h6[class*=line-2]
accountSteupNext = [xpath]://div[contains(@class,'main-circle-dark--start')]//*[name()='svg']
startButton = [id]:btn_start

#Common properties
stepImage = [css]:.img-container
stepBannerDescription = [css]:.dui-info-left-panel h6

label1 = [xpath]://div[contains(@class,'form-field')][1]/label
label2 = [xpath]://div[contains(@class,'form-field')][2]/label
label3 = [xpath]://div[contains(@class,'form-field')][3]/label
label4 = [xpath]://div[contains(@class,'form-field')][4]/label
label5 = [xpath]://div[contains(@class,'form-field')][5]/label
label6 = [xpath]://div[contains(@class,'form-field')][6]/label
stepHeader = [css]:.dui-info-right-panel h4
nextButton = [id]:btn_next
FirstName = [id]:first-name
LastName = [id]:last-name
EmailName = [id]:email
PhoneName = [id]:phone-number
subscriptionKeyTextBox = [id]:subscription-key
completeIcon = [id]:dui-complete-icon-container
completeText = [css]:.completed-text
retryButton = [id]:btn_retry
skipButton = [id]:btn_skip


#Add user step properties
helperText = [css]:.txt-description
helperCount = [css]:.count-remaining
addUsers = [id]:user-emails


#Company Information Properties
companyNameTextBox = [id]:company-name
dropDown = [id]:select-country
dropDownList = [xpath]://div[contains(@class,'options-list__scroll')]/div
acknowledgeCheckbox = [xpath]://input[@name='agree-tnc']
acknowledgeCheckboxRussia = [xpath]://input[@name='agree-tnc-ru']
acknowledgeText = [css]:span[class*=checkbox__span-text]


#Add partner step properties
partnerName = [id]:partner-name
partnerContatcInformation = [xpath]://div[contains(@class,'form-field')][2]/p

completeLineOneMessage = [xpath]://div[contains(@class,'completed-screen')]//h6[@class='completed-line1']
completeLineTwoMessage = [xpath]://div[contains(@class,'completed-screen')]//h6[@class='completed-line2']
subscriptionKeyError = [xpath]://div[contains(@class,'form-field')][1]/p
companyNameError = [xpath]://div[contains(@class,'form-field')][2]/p
termsAndConditionError = [xpath]://div[contains(@class,'form-field')][4]/p

firstNameError = [xpath]://div[contains(@class,'form-field')][1]/p
lastNameError = [xpath]://div[contains(@class,'form-field')][2]/p
emailError = [xpath]://div[contains(@class,'form-field')][3]/p
phoneNumberError = [xpath]://div[contains(@class,'form-field')][4]/p
hpTermsAndConditionLinkWf = [id]:link_tnc
hpPrivacyStatement = [id]:link-pvs
hpPrivacyStatementPageHeading = [xpath]://h2[@class='font-lh3']
printButtonTermsAndConditionsPage = [id]:printButtton
hpTermsAndConditionPageHeading = [xpath]://h4[@class='title']
spinner = [xpath]://div[contains(@class,'spinner')]//*[name()='svg']