orderListPageLink = [xpath]://div[@class='action-area']/button
allColumnHeadersText = [xpath]://table//th[@id]//span
allRowData = [xpath]://div[@class='root-layout']//table//tbody//tr//span[@title]
allRowCount = [xpath]://div[@class='root-layout']//table//tbody//tr
eachRowWiseData = [xpath]://div[@class='root-layout']//table//tbody//tr[%s]
eachRowCellData = [xpath]://div[@class='root-layout']//table//tbody//tr[%s]/td[%s]//span[@title]
defaultPaginationButton = [xpath]://button[@aria-label='Select page size']
PaginationOptions = [xpath]://div[@class="root-layout"]//div[@role='presentation']//ul[@role='menu']/li
paginationNextButton = [xpath]://nav[@aria-label='Pagination Navigation']//li/button[@aria-label="Next"]
paginationPreviousButton = [xpath]://nav[@aria-label='Pagination Navigation']//li/button[@aria-label="Previous"]


