addButton = [xpath]://div[@class='action-area']/button
addOrderTitle = [xpath]://div[@aria-modal="true"]/h4[contains(text(), "Add Orders")]
addOrderSubtitle = [xpath]://div[@aria-modal="true"]//div[@class="add-orders"]/p[1]
addOrderDescription = [xpath]://div[@aria-modal="true"]//div[@class="add-orders"]/p[2]
downloadSampleFileLink = [id]:download-sample
cancelOrderButton = [id]:cancel-order
importOrderButton = [id]:import-order
fileImport = [xpath]://input[@accept=".csv"]
columnHeaderNames = [xpath]://table//tr/th/div
allRowCount = [xpath]://div[@class="orders-list-table"]//table//tbody/tr
eachRowValues = [xpath]://table//tbody/tr[%s]/td
eachRowFileName = [xpath]://table//tbody/tr[%s]/td/a
eachRowDateTime = [xpath]://div[@class='orders-list-table']//table//tbody/tr[%s]/td[2]
eachRowNumberOfOrders = [xpath]://div[@class='orders-list-table']//table//tbody/tr[%s]/td[3]
eachRowStatus = [xpath]://div[@class='orders-list-table']//table//tbody/tr[%s]/td[4]
eachRowSource = [xpath]://div[@class='orders-list-table']//table//tbody/tr[%s]/td[5]
eachRowSummaryFile = [xpath]://div[@class='orders-list-table']//table//tbody/tr[%s]/td[6]/span
defaultPaginationButton = [xpath]://button[@aria-label='Select page size']
PaginationOptions = [xpath]://div[@class='orders-list-table']//div[@role='presentation']//ul[@role='menu']/li
paginationNextButton = [xpath]://nav[@aria-label='Pagination Navigation']//li/button[@aria-label="Next"]
paginationPreviousButton = [xpath]://nav[@aria-label='Pagination Navigation']//li/button[@aria-label="Previous"]
orderssummary =[xpath]:(//table//tbody/tr/td[text()='Completed'])[1]//following-sibling::td[2]
eachrowOrderSummaryFile =[xpath]://tr[%s]//span[contains(@class,"table-item-button")]
downloadToastMessage = [xpath]://div[@role='alert']
searchField = [xpath]://input[@id="search"]
dateTimeField = [xpath]://input[@id="date_picker"]
statusDropdown =[xpath]://div[@id="vn-select-1"]
sourceDropdwon =[xpath]://div[@id="vn-select-2"]
clearfilters =[xpath]://button[@aria-label="Clear Filters"]