tableOverlay = [css]://div[@class='vn-table__overlay-spinner--loading']//*[name()='svg']
noElementsDisplayText = [css]:td[class*='no-items']
paginationOptionAvailable = [xpath]://div[@id="dui-pagination"]//ul//li[@class="vn-menu__item"][1] 
showingText = [xpath]://span[@class='vn-pagination__information__showing']
paginationDropdownMenu = [xpath]://*[@id='dui-pagination']//a[contains(@class,'popover')]
paginationDropdownOptionList = [xpath]://*[@id='dui-pagination']//div[contains(@class,'options-list')]//div
paginationDropdownOptionListText = [xpath]://*[@id='dui-pagination']//div[contains(@class,'options-list')]//div[contains(@class,'option')]
showingPaginationTotalCount = [xpath]://*[@class='vn-pagination__information']//a//span
paginationOptionList = [xpath]://*[@id='dui-pagination']//div[contains(@class,'options-list')]//div

navigationItemDiv = [xpath]://*[@class='vn-pagination__navigation']
navigationItemList = [xpath]://*[@class='vn-pagination__navigation']//li
navigationItemNext = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()]/*[contains(@class,'navigation-item')]
navigationItemPrevious = [xpath]:(//*[@class='vn-pagination__navigation']//li)[1]/*[contains(@class,'navigation-item')]
navigationItemFrist = [xpath]:(//*[@class='vn-pagination__navigation']//li)[2]
navigationItemLast = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()-1]
navigationItemDisabled = [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'disabled')]
navigationItemActivePage =  [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'page--active')]