tableOverlay = [css]://div[@class='vn-table__overlay-spinner--loading']//*[name()='svg']
noElementsDisplayText = [css]:*[class*='state-title']
paginationOptionAvailable = [xpath]://div[@id="dui-pagination"]//ul//li[@class="vn-menu__item"][1] 
showingText = [xpath]://span[@class='vn-pagination__information__showing']
paginationDropdownMenu = [xpath]://button[@aria-label="Select page size"]
paginationDropdownOptionList = [xpath]://ul[@role='menu']
paginationDropdownOptionListText = [xpath]://ul[@role='menu']/li/button
showingPaginationTotalCount = [xpath]://*[contains(@id,'floating') and contains(@aria-label,'page size')]/following-sibling::*[text()]
paginationOptionList = [xpath]://div[contains(@class,'options-list')]//div
paginationCountSetTo100 = [xpath]:(//*[@id="dui-container"]//*[contains(@class,'dui-es-table-container')]//div[3]//div//li)[3]
paginationCountSetTo50 = [xpath]:(//*[@id="dui-container"]//*[contains(@class,'dui-es-table-container')]//div[3]//div//li)[2]

navigationItemDiv = [xpath]://*[contains(@aria-label,"Table pagination")]
navigationItemList = [xpath]://ul[@role='menu']//li
navigationItemNext = [xpath]://button[@aria-label="Next"]
navigationItemPrevious = [xpath]://button[@aria-label="Previous"]
navigationItemFirst = [xpath]://*[contains(@aria-label,"Page 1")]
navigationItemLast = [xpath]:(//button[@class='page'])[last()]
navigationItemDisabled = [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'disabled')]
navigationItemActivePage =  [xpath]://*[contains(@aria-label,"Page 1")]
