partnerDetailsTitle = [css]:h4[class*=title]
breadcrumbLink = [css]:#dui-breadcrumbs a
breadcrumbText = [css]:#dui-breadcrumbs li[class*=item]:nth-of-type(2)
toastNotification = [xpath]://div[contains(@class,'toast-enter-done')]//p
closeToastNotification = [xpath]://*[contains(@class,'container--bottom')]/div/button
noItemsDisplayText = [css]:td[class*="no-items"]
tableOverlay=[css]:div[class*='table__overlay--loading']
editIconsDetailsPage = [xpath]://*[contains(@class,'edit-padding')]//button//*[name()='svg']
editIconId = [xpath]://*[@id='displayId']//button//*[name()='svg']
editName = [xpath]://*[@id='name']//button//*[name()='svg']
editPhoneNumber = [xpath]://*[@id='phone-number']//button//*[name()='svg']
editAddress = [xpath]://*[@id='address']//button//*[name()='svg']
editPrimaryAdministrator = [xpath]://*[@id='primary-administrator']//button//*[name()='svg']
impersonateIcon = [id]:impersonate-user

#administrators tile
administratorsTitle = [css]:#pd_dt_admin div[class*=title]
nameColumn = [id]:col-id-displayName
emailColumn = [id]:col-id-email
phoneNumberColumn = [id]:col-id-PhoneNumber
primaryAdministratorColumn = [id]:col-id-primary_administrator
administratorsNameList = [css]:td[headers=col-id-displayName]
primaryAdministratorsList = [css]:td[headers=col-id-primary_administrator]

#companies managed by partner tile
companiesTitle = [css]:#managed-companies div[class*=title]
companyNameColumn = [id]:col-id-companyName
primaryAccountNameColumn = [id]:col-id-userDisplayName
primaryAccountEmailColumn = [id]:col-id-userName
primaryAccountPhoneColumn = [id]:col-id-phoneNumber
noItemsOnCompaniesTile = [css]:#pd_dt_partner td[class*=no-items]
companiesList = [css]:td[headers*=col-id-companyName]

#details tile
detailsTitle = [css]:#profile div[class*=panel__title]
nameLabel = [css]:#name div[class*=label]
nameEdit = [css]:#name button
nameValue = [css]:#name span
phoneLabel = [css]:#phone-number div[class*=label]
phoneEdit = [css]:#phone-number button
phoneValue = [css]:#phone-number span
addressLabel = [css]:#address div[class*=label]
addressEdit = [css]:address button
primaryAdministratorPhoneNumber = [css]:#primary-administrator p:nth-child(2)
primaryAdministratorLabel = [css]:div.dui-shr div.row.dui-epr:nth-child(5) div[class*=label]
primaryAdministratorEdit = [css]:#primary-administrator button
primaryAdministratorName = [css]:div.dui-shr div.row.dui-epr:nth-child(5) div[class*=value] div>div
primaryAdministratorEmail = [css]:div[class*=primary_admin] div[class*=value] div:nth-child(2)
primaryAdministratorDropdown = [css]:#ownerDisplayName svg
primaryAdministratorHeader = [css]:div[class*=primary_admin] h4
primaryAdministratorSubtitle = [css]:#key__ownerDisplayName label
primaryAdministratorSaveButton = [css]:div[class*=primary_admin] button[class*=save-btn]
primaryAdministratorCancelButton = [css]:div[class*=primary_admin] button[class*=cancel-btn]
primaryAdministratorList = [css]:#ownerDisplayName div[role=option]
emptyResults = [css]:div[class*=no-results]
partnerIDLabel = [css]:#displayId div[class*=label]
partnerIDValue= [css]:#displayId div[class*=value] span
partnerIDEdit = [css]:#displayId button
partnerIDTitle = [css]:#displayId-modal h4
partnerIDTextBox = [css]:#displayId-modal input
partnerIDSaveButton = [id]:editSaveBtn
partnerIDCancelButton = [id]:editCancelBtn

#name popup
nameTitle = [css]:div[class*=modal__header] h4
nameTextBox = [id]:edit_modal_name
saveName = [id]:editSaveBtn
cancelName = [id]:editCancelBtn

#phone popup
phoneTitle = [css]:div[class*=modal__header] h4
phoneTextBox = [id]:edit_modal_phoneNumber
savePhone = [id]:editSaveBtn
cancelPhone = [id]:editCancelBtn

#address popup
addressLine1Label = [css]:#key__address1 label
addressStreetLine1TextBox = [id]:edit_modal_streetAddressLine1
addressLine2Label = [css]:#key__address2 label
addressStreetLine2TextBox = [id]:edit_modal_streetAddressLine2
countryLabel = [css]:#key__country label
countryDropDown = [css]:#address-modal div[class*=select] button
countryValueOnDropDown = [css]:#key__country div[class*=text]
countryList = [css]:#address-modal div[role=option]
stateLabel = [css]:#key__region label
stateTextBox = [id]:edit_modal_region
cityLabel = [css]:#key__city label
cityTextBox = [id]:edit_modal_locality
saveAddress = [css]:div[class*=button-group] button[class*=save]
cancelAddress = [css]:div[class*=button-group] button[class*=cancel]
addressEditButton = [css]:#address button
addressPopupHeader = [css]:#address-modal h4
addressSaveButton = [id]:editSaveBtn
addressCancelButton = [id]:editCancelBtn
currentAddressCountry = [css]:#address span
currentAddress = [css]:#address p[class*=hyphenate]
zipCodeTextBox = [id]:edit_modal_postalCode

#primary administrator
primaryAdministratorTitle = [css]:div[class*=modal__header] h4

#identity tile
partnerNameIdentity = [css]:div.identity-name p
primaryAdministratorNameIdentity = [css]:div[class*=primary-data]:nth-of-type(3) p:nth-child(1)
primaryAdministratorEmailIdentity = [css]:div[class*=primary-data]:nth-of-type(3) p:nth-child(2)
primaryAdministratorContactNumberIdentity = [css]:div[class*=primary-data] p:nth-child(3)
partnerAdministratorEmail = [css]:div[class*=primary-data] span

#remove partner admin
removeButton = [id]:removePartner
removeTitle = [css]:div[class*=header]  h4
removeSubTitle = [css]:div.remove-partner-modal > p:nth-of-type(1)
companiesTextKey = [css]:div[class*=partner-details] > div:nth-child(3) div.remove-partner-modal > div h5
companiesListOnRemovePartnerAdminPopup = [css]:div[class*=associated-companies] p
noCompanyOnRemovePartnerAdminPopup = [css]:div[class*=associated-companies]
removeConfirmationText = [css]:div[class*=remove-partner-modal] p[class*=dui]
yes = [id]:BtnRemoveYes
no = [id]:BtnRemoveNo

#onbaord authorized partner
onboardPartnerTitle = [css]:#onboard-partner div[class*=title]
onboardPartnerSubTitle = [css]:#onboard-partner div[class*=warning]
onboardPartnerLabel = [css]:#onboard-partner-toggle div[class*=label]
onboardPartnerValue = [css]:#onboard-partner-toggle span
onboardPartnerToggle = [id]:toggle-onboard-authorized
firstPartnerCertified = [css]:td[headers*=partnerType] div[class*=_content]
authorizationLegend = [css]:div[class*=identity-tile] div:nth-child(1)> div> span

#MSP
serviceNowTitle = [css]:#service-now div[class*=title]
callBackTitle = [css]:#callback div[class*=title]
directSupportTitle = [css]:#direct-support div[class*=title]
emailSupportTitle = [css]:#email-support div[class*=title]
hoursOfOperationTitle = [css]:#hours-of-operation div[class*=title]
preferencesTab = [id]:service
helpAndSupportTab = [id]:help-and-support

#MSPDetailsTile
primaryAdministratorDropdownMSP = [css]:#primaryAdministrator-modal button[title=Open]
primaryAdministratorHeaderMSP = [css]:#primaryAdministrator-modal h4
primaryAdministratorSubTitleMSP = [css]:#primaryAdministrator-modal div[class*=body] label
primaryAdministratorListMSP = [css]:#primaryAdministrator-modal div[role=option]
primaryAdministratorLabelMSP = [css]:#primary-administrator div[class*=label]
primaryAdministratorEditMSP = [css]:#primary-administrator button
primaryAdministratorNameMSP = [css]:#primary-administrator span
primaryAdministratorEmailMSP = [xpath]:(//*[@id='primary-administrator']//p[1])
primaryAdministratorCancelButtonMSP = [id]:editCancelBtn
primaryAdministratorSaveButtonMSP = [id]:editSaveBtn

#Subscription Authorized Partner
subscriptionAuthorizedToggle = [id]:toggle-contract-authorized
subscriptionSettingsTitle = [css]:#subscription-settings div[class*=panel__title]
subscriptionContractsTitle = [css]:#subscription-contracts div[class*=panel__title]
addNewContractBtn = [id]:add-new-contract
contractModelTitle = [css]:#contract-add-modal div[class*=modal__header] h4
addcontracModelLabel = [css]:#contract-add-modal div[class*=modal__body] h4
contractIDLabel = [css]:#contract-add-modal  div:nth-child(1) > div > label
expiresLabel = [css]:#contract-add-modal  div:nth-child(1) > div > label
countryLabel = [css]:#contract-add-modal  div:nth-child(1) > div > label
currencyLabel = [css]:#contract-add-modal  div:nth-child(1) > div > label
contractIdInput = [xpath]://*[@id="contract-add-modal"]//div[contains(@class,'plan-row')]/div[1]//input
paymentTerms = [xpath]://*[@id="contract-add-modal"]//div[contains(@class,'plan-row')]/div[5]//input
monthlyCostPerSeat = [xpath]://*[@id="contract-add-modal"]//div[contains(@class,'plan-row')]/div[2]//input
editMonthlyCostperSeat = [xpath]://*[@id="contract-edit-modal"]//div[contains(@class,'plan-row')]/div[2]//input
startDataPicker = [xpath]://div[@class='plan-row row']/div[3]//div[contains(@class,'vn-datepicker')]
expiresDatepicker= [xpath]://div[@class='plan-row row']/div[4]//div[contains(@class,'vn-datepicker')]
todayButton = [css]:#button
monthKeyCurrent =[css]:div[class*=DayPicker_transitionContainer] div:nth-child(2) div[class*=datepicker__caption] div:nth-child(1) div[class*=select__title] div:nth-child(1)
endDateDialogRightArrow= [css]:div[class*=DayPickerNavigation] div:nth-child(2)  svg
daysOnCurrentMonthKey=[css]:div[class*=DayPicker_transitionContainer] div:nth-child(2) tbody tr td[class*=CalendarDay]
countryDropdown = [css]: #contract-add-modal  div[class*=select__button-group]  svg
contractCountryList = [css]: #contract-add-modal div[class*=options-list] div
contractSaveBtn = [id]:contract-save
subscriptionDesc = [css]:#contract-add-modal  div[class*=modal__body] h4
planSearchOnPopup=[xpath]://*[@id="contract-add-modal"]//div[contains(@class,'select-content__search')]//input
planSelectOnPopup=[xpath]://*[@id="contract-add-modal"]//div[contains(@class,'options-list')][1]
createdContractList = [css]:#subscription-contracts  tr td:nth-child(2)
contractIDColumn = [css]:#col-id-contractId > div div
countryColumn = [css]:#col-id-country > div div
expiresColumn = [css]:#col-id-endDate > div div
planColumn = [css]:#col-id-plans > div  div
emptyContractMsg=[css]:#subscription-contracts  p
firstContract=[css]:#subscription-contracts tbody tr:nth-child(1)
hamburgerIcon = [css]:a.vn-popover__target button
editContract=[css]:#subscription-contracts div[class*=options-list] div:nth-child(1)
editContractLabel=[css]:#contract-edit-modal div[class*=modal__header] h4
subscriptionAuthorizedToggle = [id]:toggle-contract-authorized
subscriptionAuthorizedLabel = [css]:#subscription-authorize-toggle [class*=label]
subscriptionContractTile = [id]:subscription-contracts
subscriptionAuthorizedPartnerValue = [css]:#subscription-authorize-toggle span
paymentTermColumn = [css]:#col-id-paymentTerms
startDateColumn = [css]:#col-id-startDate

#Authentication tile
authenticationTitle = [css]:#sign_in [class*='title']

#notifications tab
notificationsTab = [id]:notifications
deviceNotificationsTItle = [css]:#device-notifications [class*=title]
deviceNotificationDescription = [css]:#device-notifications [class*='panel-warning']

#currency dropdown open
btnCurrencyDropdown = [css]:#contract-add-modal  div:nth-child(6) > div > label + div > div > div > button
USDCurrencyDropdown = [xpath]://*[@id="contract-add-modal"]//div[contains(@class,"option")][4]/a

#active care tile
activeCareTitle = [css]:#enable-active-care div[class*=title]
activeCareLabel = [css]:#enable-active-care div[class*=label]
activeCareToggle = [css]:#enable-active-care a 