partnersTab = [id]:menu_partners
partnersListTab = [id]:menu_partnersList
partnerUsersTab = [id]:menu_partnerUsers
mspTab = [id]:menu_msp
mspListTab = [id]:menu_mspList
mspUsersTab = [id]:menu_mspUsers
customersTab = [id]:menu_partnerCompanies
customersListTab = [id]:menu_partnerCompaniesList
customerUsersTab = [id]:menu_customerUsers
administrativeTab = [id]:menu_administrator
administrativeUsersTab = [id]:menu_rootUsers
partnersTitle = [css]:#partnerList h4
partnersTitleOnBreadcrumbs = [css]:#partnerList li
tableOverlay = [css]:[class*=ProgressIndicator] svg
firstRowPartner= [css]:tr:nth-child(1) td a
firstRowPartnerUser= [css]: tr td:nth-child(2) a
partnerAllDetails = [xpath]://tbody//tr[1]//td
listOfColumnsOnTable = [css]:table tr:first-child th
firstPartnerName = [css]:table tr:first-child a
listTable = [css]:[class*=table-container] table
nameHeader = [css]:#name button
administrativeTab = [id]:menu_administrator
administrativeUsersTab = [id]:menu_rootUsers
clearfilter=[css]:button[aria-label="Clear selection"]
onboardCertifiedColumn = [css]:#col-id-partnerType

#table configuration
tableConfigurationButton = [css]:[aria-label*="Column Options"] svg
tableConfigurationTitle = [css]:#column-options-label

#filter functionality
nameSearchBox = [xpath]:(//*[@id="name"])[2]
typeDropdown = [id]:partners-type
primaryAdministratorDropdown = [css]:[name="primaryAdministrator"]+span div
emailSearchBox = [xpath]:(//*[@id="email"])[2]
phoneSearchBox = [xpath]:(//*[@id="phone"])[2]
addressSearchBox = [xpath]:(//*[@id="address"])[2]
nameList = [xpath]:(//table/tbody/tr/td[2])[position() < last()]
typeList = [css]:td[headers*=type]
primaryAdministratorList = [xpath]:(//table/tbody/tr/td[3])[position() < last()]
emailList = [css]:table tr td:nth-child(4)
phoneList = [css]:table tr td:nth-child(6)
addressList = [css]:table tr td:nth-child(7)
typeDropdownList = [css]:#partners-type div[class*=options-list] a
primaryAdministratorDropdownList = [css]:[class*="SelectContent"] li
primaryAdministratorSearchBox = [xpath]://*[@role='presentation']/div/div/input
noItemsDisplayText = [xpath]://tbody/tr/td/div/span
dropdownElementListLabels = [css]:#logs-company-select a
clearFilter = [css]:button[aria-label=Clear]
primaryAdministratorColumnTitle = [css]:#primaryAdministrator button
primaryAdministratorListOnDropdown = [css]:#primaryAdministrator-listbox li
dropdownCheckBoxes = [css]:#logs-company-select div[class*="option__multiple"]
noElementsDisplayTextForComboBoxColumn = [css]:[role=presentation]:last-child div> div:last-child
certifiedDropdown = [css]:#partners-partnerType div[role=button]
dropDownCheckBoxes = [css]:[class*=SelectContent] ul li
dropDownElementListLabels = [css]:[role=presentation] ul[role=listbox] li div
certifiedList = [css]:td[headers*=partnerType]
clearSearchBoxFilter = [xpath]://*[@aria-label="Clear Filters"]
userRolesBoxTitle= [css]:#roles button
userRolesBox = [xpath]:(//*[@id="roles"])[2]
userRolesList= [css]:table tr td:nth-child(4)
dropdownRolesCheckboxes = [css]:table tr:nth-child(2) th:nth-child(4) svg
dropdownRolesElementListLabels = [xpath]://*[@id='logs-company-select']//*[contains(@class, 'option__multiple')]
clearRolesField = [css]:#users-roles button:nth-of-type(1)
navOnPartnerListPage =[xpath]://*[@id="settings"]/header/div[1]/div/nav/ol/li[1]/a
							  
#Subscription Authorized Partner
subscriptionAuthorizedToggle = [css]:#contract-authorized span:nth-child(2)

#add partner
addPartnerButton = [css]:[class*=table] > button
addPartnerTitle = [css]:[class*=modal--dialog] h4
partnerNameSearchBox = [css]:[name=name]
compPartnerNameSearch =[css]:[name=partner_name]
partnerFirstNameSearchBox = [css]:[name=primary_admin_fname]
partnerLastNameSearchBox = [css]:[name=primary_admin_lname]
partnerEmailSearchBox = [css]:[name=primary_admin_email]
partnerPhoneSearchBox = [css]:[name=primary_admin_phone]
save = [css]:button[id*=save-btn]
cancel = [css]:button[id*=btn_cancel]
next = [css]:button[id*=btn_next]
previous = [css]:button[id*=btn_prev]
btnSaveLoader = [css]:#save-btn > svg
pbmTitle = [css]:[class*=modal--dialog] h6:first-of-type
pbmTitleText = [xpath]://*[@class="dui-add_model-title pbm"]
pbmFirstNameSearchBox = [css]:[name=pbm_fname]
pbmLastNameSearchBox = [css]:[name=pbm_lname]
pbmEmailSearchBox = [css]:[name=pbm_email]
obmTitle = [css]:[class*=modal--dialog] h6:last-of-type
obmTitleText = [xpath]://*[@class="dui-add_model-title obm"]
obmFirstNameSearchBox = [css]:[name=obm_fname]
obmLastNameSearchBox = [css]:[name=obm_lname]
obmEmailSearchBox = [css]:[name=obm_email]
pbmobmCheckBox = [css]:[name='pbm_obm_email_Check']
pbmFirstNameLabel = [xpath]://*[@class="dui-add_model-title pbm"]/following::span[1]
pbmLastNameLabel = [xpath]://*[@class="dui-add_model-title pbm"]/following::span[2]
pbmEmailLabel = [xpath]://*[@class="dui-add_model-title pbm"]/following::span[3]
obmFirstNameLabel = [xpath]://*[@class="dui-add_model-title obm"]/following::span[1]
obmLastNameLabel = [xpath]://*[@class="dui-add_model-title obm"]/following::span[2]
obmEmailLabel = [xpath]://*[@class="dui-add_model-title obm"]/following::span[3]
notifyUserText = [xpath]:(//*[contains(@class,'checkbox__span--text')])[1]
pbmEmailNotificationCheckbox = [css]:[name=edit_modal_partnerBusinessManagerSendEmail]
obmEmailNotificationCheckbox = [css]:[name=edit_modal_onboardingBusinessManagerSendEmail]
onboardBusinessManagerLabel = [css]: #onboardingBusinessManager [class*="label"]

toastNotification = [xpath]://*[@id="dui-app-scroll"]/div[4]/div/div
partnerAddedSuccessfullyToastNotification = [xpath]://*[contains(@id,"toast-title")]
firstRowName = [xpath]:(//tbody//tr//td[2])[1]
radioButtonForReseller = [css]:div[class*=radio-buttons]:nth-of-type(2) svg
radioButtonForMSP = [css]:div[class*=radio-buttons]:nth-of-type(1) svg
errorValidationMessageForPhoneField = [css]:div[class*=modal__body] div:nth-child(7) p
errorValidationMessageForEmailField = [xpath]:(//*[contains(@class, 'caption')])[6]
addPartnerID = [css]:[name=partner_id]
countryDropdown = [css]:[class*=modal--content] [class*=open-button] svg
countrySearchBox = [xpath]:(//*[@id='select-country-listbox']/preceding::input)[last()]
countryList = [id]:select-country-option-0
countryOnDropdown = [css]:[class*=modal--content] [class*=select__button]

#pagination
showingText = [xpath]://span[@class='vn-pagination__information__showing']
paginationDropdownMenu = [xpath]://button[@aria-label="Select page size"]
paginationDropdownOptionList = [css]:[class*=TablePagination] [class*=ContextualMenu] ul li
showingPaginationTotalCount = [css]:[class*="TablePagination"] > div > div:nth-child(1)
paginationOptionList = [css]:[class*=TablePagination] [class*=ContextualMenu] ul li
navigationItemDiv = [xpath]://nav[@aria-label="Pagination Navigation"]
navigationItemList = [css]:[class*="TablePagination"] nav li
navigationItemNext = [xpath]:(//*[contains(@class,'TablePagination')]//li)[last()]
navigationItemPrevious = [css]:[class*="TablePagination"] nav li:nth-child(1)
navigationItemFrist = [css]:[class*="TablePagination"] nav li:nth-child(2)
navigationItemLast = [xpath]:(//*[contains(@class,'TablePagination')]//li)[last()-1]
navigationItemDisabled = [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'disabled')]
navigationItemActivePage =  [xpath]://nav[@aria-label="Pagination Navigation"]//button[@aria-current="true"]
clearSelectionOfFilters = [css]:[class*="clear-button"]

#PartnerMSPUserListPage
nameSearchBoxUser = [css]:#name:nth-child(1)
roleDropdownButton = [css]:table tr:nth-child(2) th:nth-child(4) svg
roleClearfilter = [xpath]:(//*[@id='logs-company-select']//button[1]//*[name()='svg'])[1]

#Onbaord Authorized Partner
authorizationLegend = [css]:[class*=labeled-icon] span
onboardToggleLoader = [xpath]://*[@id='onboard-authorized-new']//*[contains(@class,'dui-epr-loader')]

#Authorization column
authorizationColumnHeader = [css]:#authorization button
authorizationValue = [css]:tbody tr td:nth-child(9)
authorizationDropDown = [xpath]:(//*[@id="dui-container"]//table/thead/tr[2]/th[7]//div[1]//span)[2]
authorizationList = [xpath]:(//table/tbody/tr/td[9])[position() < last()]
authorizationDropDownOptions = [css]:#authorization-listbox li
onboardPartnerLabel = [css]:#onboard-authorized-new div[class*=label]
partnerBusinessManagerLabel = [css]: #partnerBusinessManager [class*="label"]

addMSPUserButton = [css]:#btn_user_add
chooseMSPUserTitle = [xpath]:(//*[contains(@class,'modal--dialog')]//h4[contains(@class,'modal--title')])[3]
mspdropdown = [css]:#assignment-msp+input+span svg
listOfMSPs = [css]:#assignment-msp-listbox div
mspdropdownafterclick = [xpath]://*[@data-popover-backdrop="true"]
mspNext = [css]:#root-createMSP-mspSelect-next
roledropdown = [css]:#MSP-User-Infor+input+span svg
mspRoleList = [css]:#MSP-User-Infor-listbox div
mspFirstNameSearchBox = [css]:[name="firstName"]
mspLastNameSearchBox = [css]:[name="lastName"]
mspEmailSearchBox = [css]:[class*=modal--content] [name="email"]
mspPhoneSearchBox = [css]:[class*=modal--content] [name="phone"]
addUserButton = [css]:#root-createMSP-userDetails-add
mspEmailSearch = [css]:input#email
listOfUsers = [xpath]://tbody/tr/td[2]/a
listPageCheckbox = [xpath]://table//tr/th/span
deleteUsers = [id]:btn_user_remove
removeUserTitle = [xpath]:(//*[contains(@class,'modal--dialog')]//h4[contains(@class,'modal--title')])[3]
removeUserMessage = [css]:#dui-remove-user p
deleteButton = [css]:#modal-submit

preferenceTab = [id]:service

#active care tile
activeCareTitle = [css]:#enable-active-care div[class*=header]
activeCareLabel = [css]:#enable-active-care div[class*=label]
activeCareToggle = [css]:#enable-active-care #dui-epr-icon-0

onboardPartnerLabel = [css]:#onboard-authorized-new div[class*=label]
notificationBellIcon = [css]:[class*=dui-header] span span:nth-child(1)
unreadNotificationText = [css]:[id=dui-notifications] ul div:nth-child(3)
unreadNotificationinsideText = [xpath]:(//*[@id='dui-notifications']//ul/li/div[2]/span)[1]
hamburgerOnNotifications = [css]:#dui-notifications  li:first-child button
openPartnerPage = [xpath]://div[@role="menu" and @data-popper-placement="bottom-end" ]//li[@data-value="OPEN PARTNER PAGE"]

#Billing Banner
billingWelcomeTitle1 = [css]:#billing_admin_notification  h6:nth-child(1)
billingWelcometext1 = [css]:#billing_admin_notification  p:nth-child(2)
billingWelcomeTitle2 = [css]:#billing_admin_notification  p:nth-child(4)
billingWelcometext2 = [css]:#billing_admin_notification p:nth-child(5)
billingWelcomeTitle3 = [css]:#billing_admin_notification p:nth-child(6)
billingWelcometext3 = [css]:#billing_admin_notification p:nth-child(7)
billingWelcomeTitle4 = [css]:#billing_admin_notification p:nth-child(8)
billingWelcometext4 = [css]:#billing_admin_notification p:nth-child(9)
assignAdminTitle = [css]:#billing_admin_notification > div > div > div > h5
welcomeStepDesc = [xpath]:(//*[@id="billing_admin_notification"]//div[2])[1]
assignStepDesc = [xpath]:(//*[@id="billing_admin_notification"]//div[2])[3]
verifyStepDesc = [xpath]:(//*[@id="billing_admin_notification"]//div[2])[4]
billingCancelbtn =[css]:#btn_back
billingStartBtn =[css]:#btn_next
assignBillingStepTitle =[css]:#billing_admin_notification  div > div > div div:nth-child(1) > h6
addAdminStepDesc =[css]:#billing_admin_notification  div > div > div div:nth-child(1) > p
userTypeTitle =[css]:#billing_admin_notification  div > div > div div:nth-child(2) > p
existingUserRadioBtnText =[css]:#billing_admin_notification label:nth-child(1) span:nth-child(2)
newUserRadioBtnText =[css]:#billing_admin_notification label:nth-child(2) span:nth-child(2)
newUserRadioBtn =[css]:#billing_admin_notification label:nth-child(2) span:nth-child(1)
existingUserMsg =[css]:#billing_admin_notification  div > div:nth-child(3) > p
userSelectionDropdwn =[css]:#billing_admin_notification > div  div:nth-child(3) > div > div > span
existingUserListbox =[css]:#add-users-filter-listbox li
userSearchBox = [xpath]://*[@role="presentation"]/div/div/input
firstOptionUserDropdown=[css]:#add-users-filter-option-0 > div
closeUserDropdown=[xpath]://*[@data-popover-backdrop="true"]
userNameCol=[css]:#name
userEmailCol=[css]:#email
nameValue = [xpath]://*[@id="billing_admin_notification"]//table/tbody/tr/td[1]
emailValue = [xpath]://*[@id="billing_admin_notification"]//table/tbody/tr/td[2]
billingBanner =[css]: #add_billing_admin_notification
userRoleSearchValue = [xpath]: //*[@id="dui-container"]//td[4]//div
accountsPanelHeader =[css]:#dui-accountAndRoles  div.dui-panel-header
roleSearchBar =[css]:#search
billingCheckbox = [xpath]://input[@aria-checked='true']
billingCheckboxSelect = [xpath]://input[@aria-checked='false']
billingBannerHeader=[css]: #add_billing_admin_notification div  div  span:nth-child(1)
billingBannerDesc=[css]:#add_billing_admin_notification [class*=notification__description]
billingSetupButtonText=[css]:#add_billing_admin_notification > div > button span
billingSetupButton=[css]:#add_billing_admin_notification > div > button
newUserFirstname=[css]:#new_user_first_name_0
newUserLastname=[css]:#new_user_last_name_0
newUserEmailname=[css]:#new_user_email_0
addAnotherUserLink=[css]:#add_new_user
notifyUserByEmailLink=[css]:#billing_admin_new_users  [class*=checkbox__span--text]
notifyUserByEmailCheckbox=[css]:#notify_by_mail

#csdp status
partnerCsdpStatusText=[xpath]://tbody/tr[1]//div[@class='dui-status-success']/..//following-sibling::td[2]
csdpStatusFilterDropdown=[id]:csdpStatus
csdpStatusFilterDropdownOptions=[xpath]://ul[@id='csdpStatus-listbox']/li//span

#First time Login
passowrdTextBox=[id]:password
createButton=[xpath]://*[@id="oobe-sign-up-submit"]
codeTextBox=[id]:code
verifyButton=[id]:submit-code
partnerDashboardTourTitle=[id]:partner-optin-modal-heading1
partnerDashboardTourSubTitle=[id]:partner-optin-modal-heading2
viewGuidedTourButton=[xpath]://*[contains(@class,"sign-in-btn")]
cancelTourButton=[xpath]://*[contains(@class,"cancel-in-btn")]
nextButton=[xpath]://*[@aria-label="Next"]
tooltipViewedButton=[xpath]:(//*[@aria-label="Close coachmark"])[2]
termsAndConditionsCheckboxTnC = [xpath]://*[@id="terms-agreement-checkbox"]/following-sibling::span[1]
termsAndConditionsLinkTnC = [xpath]://*[@id="terms-agreement-desc"]/preceding-sibling::a
privacyPolicyTnC = [xpath]://*[@id="terms-agreement-desc"]/following-sibling::a
acceptButtonTnC = [xpath]://*[contains(@class,"accept-button")]/span
cancelButtonTnC = [xpath]://*[contains(@class,"cancel-button")]/span
printButtonTnC = [xpath]://*[@id="printButtton"]
clearSearchBoxFilterForRoot = [xpath]://*[@aria-label="Clear Filters"]/span[2]
emptyStateDashboardBannerTitle = [xpath]://*[@class="wex-onboarding-banner-title"]
emptyStateDashboardBannerDescription= [xpath]://*[@class="wex-onboarding-banner-description wx-font-body-large"]
emptyStateDashboardGuidedTourButton= [id]:onboardingTour_btn
emptyStateDashboardCustomizeCardTitle= [xpath]://div[@id='wex-onboarding-customize-tile']//p
emptyStateDashboardCustomizeCardDescription= [xpath]://div[@id='wex-onboarding-customize-tile']//div[@class="wex-card-description caption"]
CustomizeButton= [id]:onboarding__tour_btn__customize
emptyStateDashboardAddMemberTitle= [xpath]://*[@id="wex-onboarding-addCompanyUser-tile"]//p
emptyStateDashboardAddMemberDescription= [xpath]://*[@id="wex-onboarding-addCompanyUser-tile"]//div[@class="wex-card-description caption"]
AddMemberButton= [id]:onboarding__tour_btn__addCompanyUser
emptyStateDashboardCertificationsTitle= [xpath]://*[@id="wex-onboarding-certifications-tile"]//p
emptyStateDashboardCertificationsDescription= [xpath]://*[@id="wex-onboarding-certifications-tile"]//div[@class="wex-card-description caption"]
LearnMoreButton_1= [id]:onboarding__tour_btn__certifications
emptyStateDashboardWatchActionCardTitle_1= [xpath]://div[@id="wex-onboarding-watchAction-tile"]//p
emptyStateDashboardWatchActionCardDescription= [xpath]://div[@id="wex-onboarding-watchAction-tile"]//div[@class="wex-card-description caption"]
WatchButton=[id]:onboarding__tour_btn__watchAction
emptyStateDashboardStayInKnowTitle= [xpath]://div[@id="wex-onboarding-stayInKnow-tile"]//p
emptyStateDashboardStayInKnowCardDescription= [xpath]://div[@id="wex-onboarding-stayInKnow-tile"]//div[@class="wex-card-description caption"]
LearnMoreButton_2=[id]:onboarding__tour_btn__stayInKnow
emptyStateDashboardLatestPostsTitle= [xpath]://div[@id="wex-onboarding-latestPosts-tile"]//p
emptyStateDashboardLatestPostsCardDescription= [xpath]://div[@id="wex-onboarding-latestPosts-tile"]//div[@class="wex-card-description caption"]
LearnMoreButton_3=[id]:onboarding__tour_btn__latestPosts