partnersTab = [id]:menu_partners
partnersListTab = [id]:menu_partnersList
partnerUsersTab = [id]:menu_partnerUsers
mspTab = [id]:menu_msp
mspListTab = [id]:menu_mspList
mspUsersTab = [id]:menu_mspUsers
customersTab = [id]:menu_partnerCompanies
customersListTab = [id]:menu_partnerCompaniesList
customerUsersTab = [id]:menu_customerUsers
administrativeTab = [id]:menu_administrator
administrativeUsersTab = [id]:menu_rootUsers
partnersTitle = [css]:#partnerList h4
partnersTitleOnBreadcrumbs = [css]:#partnerList li
tableOverlay = [xpath]://div[@class='dui-page-spinner']//*[name()='svg']
firstRowPartner= [css]:td[headers=col-id-name] a
partnerAllDetails = [xpath]://tbody//tr[1]//td
listOfColumnsOnTable = [css]:th[class*='cell-title']>div:nth-of-type(1)
firstPartnerName = [css]:td[headers*=col-id-name] a
listTable = [css]:table[class*=table]
nameHeader = [css]:#col-id-name
administrativeTab = [id]:menu_administrator
administrativeUsersTab = [id]:menu_rootUsers
clearfilter=[xpath]://button[@title='Clear']
onboardCertifiedColumn = [css]:#col-id-partnerType

#table configuration
tableConfigurationButton = [css]:div.vn-tableconfiguration>button>svg
tableConfigurationTitle = [css]:div.vn-modal__header>h4

#filter functionality
nameSearchBox = [id]:partners-name
typeDropdown = [id]:partners-type
primaryAdministratorDropdown = [css]:#partners-primaryAdministrator button
emailSearchBox = [id]:partners-email
phoneSearchBox = [id]:partners-phone
addressSearchBox = [id]:partners-address
nameList = [css]:td[headers*=name]
typeList = [css]:td[headers*=type]
primaryAdministratorList = [css]:td[headers*=primaryAdministrator]
emailList = [css]:td[headers*=email]
phoneList = [css]:td[headers*=phone]
addressList = [css]:td[headers*=address]
typeDropdownList = [css]:#partners-type div[class*=options-list] a
primaryAdministratorDropdownList = [css]:#partners-primaryAdministrator div[class*=options-list] a
primaryAdministratorSearchBox = [css]:input#search
noItemsDisplayText = [css]:td[class*='no-items']
dropdownElementListLabels = [css]:#logs-company-select a
clearFilter = [css]:button[title='Clear']
primaryAdministratorColumnTitle = [css]:col-id-primaryAdministrator div[class*=label]
primaryAdministratorListOnDropdown = [css]:#partners-primaryAdministrator div[class*=option__multiple]
dropdownCheckBoxes = [css]:#logs-company-select div[class*="option__multiple"]
noElementsDisplayTextForComboBoxColumn = [css]:div[class*="no-results"]
certifiedDropdown = [css]:#partners-partnerType div[role=button]
dropDownCheckBoxes = [css]:div[class*='select'] div[class*='options-list'] div[class*='option']:nth-of-type(1) a
dropDownElementListLabels = [css]:div.vn-select-content div.vn-options-list.vn-options-list>div:nth-of-type(1)>a
certifiedList = [css]:td[headers*=partnerType]

userRolesBoxTitle= [xpath]://*[@id='col-id-roles']
userRolesBox = [id]:users-roles
userRolesList= [css]:td[headers*=col-id-roles]
dropdownRolesCheckboxes = [css]:#users-roles button:nth-of-type(1) svg
dropdownRolesElementListLabels = [xpath]://*[@id='logs-company-select']//*[contains(@class, 'option__multiple')]
clearRolesField = [css]:#users-roles button:nth-of-type(1)

#add partner
addPartnerButton = [id]:btn_company_add
addPartnerTitle = [css]:h5[class*="title"]
partnerNameSearchBox = [id]:partner_name
partnerFirstNameSearchBox = [id]:primary_admin_fname
partnerLastNameSearchBox = [id]:primary_admin_lname
partnerEmailSearchBox = [id]:primary_admin_email
partnerPhoneSearchBox = [id]:primary_admin_phone
save = [css]:button[class*=save-btn]
cancel = [css]:button[class*=cancel-btn]
toastNotification = [xpath]://div[contains(@class,'toast-enter-done')]//p
firstRowName = [css]:tr:nth-child(1) td[headers*=name]
radioButtonForReseller = [css]:div[class*=radio-buttons]:nth-of-type(2) svg
radioButtonForMSP = [css]:div[class*=radio-buttons]:nth-of-type(1) svg
errorValidationMessageForPhoneField = [css]:div[class*=modal__body] div:nth-child(7) p
errorValidationMessageForEmailField = [css]:div[class*=modal__body] div:nth-child(6) p
addPartnerID = [id]:partner_id
countryDropdown = [css]:div[class*=form-field]:nth-of-type(3) button
countrySearchBox = [css]:div[class*=form-field]:nth-of-type(3) #search
countryList = [css]:div[class*=form-field]:nth-of-type(3) div[role=option]
countryOnDropdown = [css]:div[class*=form-field]:nth-of-type(3) div[class*=title-text]:nth-of-type(1)

#pagination
showingText = [xpath]://span[@class='vn-pagination__information__showing']
paginationDropdownMenu = [xpath]://div[contains(@class,'pagination')]//a[@role='button']
paginationDropdownOptionList = [xpath]://div[contains(@class,'options-list')]//div[contains(@class,'option')]
showingPaginationTotalCount = [xpath]://*[@class='vn-pagination__information']//a//span
paginationOptionList = [xpath]://div[contains(@class,'options-list')]//div
navigationItemDiv = [xpath]://*[@class='vn-pagination__navigation']
navigationItemList = [xpath]://*[@class='vn-pagination__navigation']//li
navigationItemNext = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()]/*[contains(@class,'navigation-item')]
navigationItemPrevious = [xpath]:(//*[@class='vn-pagination__navigation']//li)[1]/*[contains(@class,'navigation-item')]
navigationItemFirst = [xpath]:(//*[@class='vn-pagination__navigation']//li)[2]
navigationItemLast = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()-1]
navigationItemDisabled = [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'disabled')]
navigationItemActivePage =  [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'page--active')]
clearSelectionOfFilters = [css]:th div>input:not([value=''])[placeholder=''],th div svg[class*='clear-icon']

#PartnerMSPUserListPage
nameSearchBoxUser = [id]:users-name
roleDropdownButton = [xpath]:(//*[@id='logs-company-select']//button//*[name()='svg'])[1]
roleClearfilter = [xpath]:(//*[@id='logs-company-select']//button[1]//*[name()='svg'])[1]

#Onbaord Authorized Partner
authorizationLegend = [css]:div[class*=identity-tile] div:nth-child(1)> div> span

#Authorization column
authorizationColumnHeader = [id]:col-id-authorization
authorizationValue = [css]:td[headers*=col-id-authorization] div[class*=_content]
authorizationDropDown = [css]:#select-partners-authorization div[role=button]
authorizationList = [css]:td[headers*=col-id-authorization
authorizationDropDownOptions = [css]:#select-partners-authorization div[class*=option__multiple]

addMSPUserButton = [css]:#btn_user_add
chooseMSPUserTitle = [xpath]://*[contains(@class,'modal__header')]//h4
mspdropdown = [xpath]://*[@id="root-createMSP-MSPSelectDropdown"]//*[name()='svg']
listOfMSPs = [xpath]://*[contains(@class,'options-list__scroll')]//a
mspdropdownafterclick = [xpath]:(//*[@id="root-createMSP-MSPSelectDropdown"]//*[name()='svg'])[2]
mspNext = [css]:#root-createMSP-mspSelect-next
roledropdown = [xpath]://*[@id="add_msp_root__type"]//*[name()='svg']
mspRoleList = [xpath]://*[contains(@class,"select-content")]//a
mspFirstNameSearchBox = [css]:#firstName
mspLastNameSearchBox = [css]:#lastName
mspEmailSearchBox = [css]:#email
mspPhoneSearchBox = [css]:#phone
addUserButton = [css]:#root-createMSP-userDetails-add
mspEmailSearch = [css]:#users-email
listOfUsers = [xpath]://*[@headers="col-id-name"]//div[contains(@class,'tablecell__content')]
listPageCheckbox = [xpath]:(//*[contains(@class,"checkbox__label")]//span)[1]
deleteUsers = [id]:btn_user_remove
removeUserTitle = [css]:#dui-remove-user h4
removeUserMessage = [css]:#dui-remove-user p
deleteButton = [css]:#modal-submit
