partnerDetailsTitle = [css]:#settings h4[class*=title]
breadcrumbLink = [css]:#settings a
breadcrumbText = [css]:#settings li:nth-child(2) > span
toastNotification = [xpath]://*[@id="dui-app-scroll"]/div[4]/div/div
closeToastNotification = [xpath]://*[@id="dui-app-scroll"]/div[4]/div/button
noItemsDisplayText = [css]:[class*='container'] td span
tableOverlay=[css]:div[class*='table__overlay--loading']
editIconsDetailsPage = [xpath]://*[contains(@class,'edit-icon')]//div
editIconId = [xpath]://*[@id='displayId']//*[name()='svg']
editName = [xpath]://*[@id='name']//*[name()='svg']
editPhoneNumber = [xpath]://*[@id='phoneNumber']//*[name()='svg']
editAddress = [xpath]://*[@id='address']//*[name()='svg']
editPrimaryAdministrator = [xpath]://*[@id='primaryAdministrator']//*[name()='svg']
impersonateIcon = [id]:impersonate-user

#administrators tile
administratorsTitle = [css]:#pd_dt_admin div[class*=title]
nameColumn = [xpath]:(//*[@id = "name"])[1]
emailColumn = [xpath]:(//*[@id = "email"])[1]
phoneNumberColumn = [xpath]:(//*[@id = "phone"])[1]
primaryAdministratorColumn = [xpath]:(//*[@id = "primaryAdministrator"])[1]
administratorsNameList = [css]:[class*=table-list] tbody td > a
primaryAdministratorsList = [css]:[class*=table-list] tbody td:nth-child(2)

#companies managed by partner tile
companiesTitle = [css]:#managed-companies div[class*=title]
companyNameColumn = [xpath]:(//*[@id = "name"])[1]
primaryAccountNameColumn = [xpath]:(//*[@id = "primaryAccount"])[1]
primaryAccountEmailColumn = [xpath]:(//*[@id = "primaryAccountEmail"])[1]
primaryAccountPhoneColumn = [xpath]:(//*[@id = "phoneNumber"])[1]
noItemsOnCompaniesTile = [css]:[class*='container'] td span
companiesList = [css]:[class*=table-list] tbody td > a

#details tile
detailsTitle = [css]:#profile div[class*=panel-header]
nameLabel = [css]:#name div[class*=label]
nameEdit = [css]:#name [class*=icon-button]
nameValue = [css]:#name span
phoneLabel = [css]:#phoneNumber div[class*=label]
phoneEdit = [css]:#phoneNumber [class*=icon-button]
phoneValue = [css]:#phoneNumber span
addressLabel = [css]:#address div[class*=label]
addressEdit = [css]:#address [class*=icon-button]
primaryAdministratorPhoneNumber = [css]:#primaryAdministrator p:nth-child(3)
primaryAdministratorLabel = [css]:#primaryAdministrator div[class*=label]
primaryAdministratorEdit = [css]:#primaryAdministrator svg
primaryAdministratorName = [css]:#primaryAdministrator span
primaryAdministratorEmail = [css]:#primaryAdministrator p:nth-child(2)
primaryAdministratorDropdown = [css]:#primaryAdministrator-modal-desc svg
primaryAdministratorHeader = [css]:#primaryAdministrator-modal-label
primaryAdministratorSubtitle = [css]:#key__ownerDisplayName label
primaryAdministratorSaveButton = [id]:editSaveBtn
primaryAdministratorCancelButton = [id]:editCancelBtn
primaryAdministratorList = [css]:[class*=options-list]  div[role=option]
emptyResults = [css]:[class*='container'] td span
partnerIDLabel = [css]:#displayId div[class*=label]
partnerIDValue= [css]:#displayId div[class*=value] span
partnerIDEdit = [css]:#displayId svg
partnerIDTitle = [xpath]://h4[@id='displayId-modal-label']
partnerIDTextBox = [css]:#displayId-modal-desc input
partnerIDSaveButton = [id]:editSaveBtn
partnerIDCancelButton = [id]:editCancelBtn

#name popup
nameTitle = [xpath]://h4[@id='name-modal-label']
nameTextBox = [css]:#name-modal-desc input
saveName = [id]:editSaveBtn
cancelName = [id]:editCancelBtn

#phone popup
phoneTitle = [id]:phoneNumber-modal-label
phoneTextBox = [css]:#phoneNumber-modal-desc input
savePhone = [id]:editSaveBtn
cancelPhone = [id]:editCancelBtn

#address popup
addressLine1Label = [css]:#key__address1 label
addressStreetLine1TextBox = [css]:[name*=edit_modal_streetAddressLine1]
addressLine2Label = [css]:#key__address2 label
addressStreetLine2TextBox = [css]:[name*=edit_modal_streetAddressLine2]
countryLabel = [css]:#key__country label
countryDropDown = [css]:#address-modal-desc div[class*=select] svg
countryValueOnDropDown = [css]:#address-modal-desc [class*=button-title]
countryList = [css]:#edit_modal_undefined-listbox li
stateLabel = [css]:#key__region label
stateTextBox = [css]:[name=edit_modal_region]
cityLabel = [css]:#key__city label
cityTextBox = [css]:[name=edit_modal_locality]
saveAddress = [id]:editSaveBtn
cancelAddress = [id]:editCancelBtn
addressEditButton = [css]:#address [class*=icon-button]
addressPopupHeader = [xpath]://h4[@id='address-modal-label']
addressSaveButton = [id]:editSaveBtn
addressCancelButton = [id]:editCancelBtn
currentAddressCountry = [css]:#address span
currentAddress = [css]:#address p[class*=hyphenate]
zipCodeTextBox = [css]:[name=edit_modal_postalCode]

#primary administrator
primaryAdministratorTitle = [css]:#primaryAdministrator-modal-label

#identity tile
partnerNameIdentity = [css]:[class*=summary-card-title]
primaryAdministratorNameIdentity = [css]:[class*=desc-content-row]:nth-of-type(2) div:nth-child(2) > div:nth-of-type(2)
primaryAdministratorEmailIdentity = [css]:[class*=desc-content-row]:nth-of-type(2) div:nth-child(3) > div:nth-of-type(2)
primaryAdministratorContactNumberIdentity = [css]:[class*=desc-row]:nth-of-type(1) div:nth-child(2)
partnerAdministratorEmail = [css]:[class*=card-desc] span[class]

#remove partner admin
removeButton = [id]:removePartner
removeTitle = [css]:div[class*=header]  h4
removeSubTitle = [css]:[class*=remove-partner] > p
companiesTextKey = [css]:div[class*=partner-details] > div:nth-child(3) div.remove-partner-modal > div h5
companiesListOnRemovePartnerAdminPopup = [css]:div[class*=associated-companies] p
noCompanyOnRemovePartnerAdminPopup = [css]:div[class*=associated-companies]
removeConfirmationText = [css]:div[class*=remove-partner-modal] p[class*=dui]
yes = [id]:BtnRemoveYes
no = [id]:BtnRemoveNo

#onbaord authorized partner
onboardPartnerTitle = [css]:#onboard-partner div[class*=header]
onboardPartnerSubTitle = [css]:#onboard-partner div[class*=warning]
onboardPartnerLabel = [css]:#onboard-authorized-new div[class*=label]
onboardPartnerValue = [css]:#onboard-authorized-new span:first-child
onboardPartnerToggle = [css]:#onboard-authorized-new span:nth-child(2)
firstPartnerCertified = [css]:td[headers*=partnerType] div[class*=_content]
authorizationLegend = [xpath]:(//*[contains(@class,'icon-labeled')]//*[contains(@class, 'icon-label')])[2]


#MSP
serviceNowTitle = [css]:#ServiceNow div[class*=header]
callBackTitle = [css]:#callback div[class*=header]
directSupportTitle = [css]:#direct-support div[class*=header]
emailSupportTitle = [css]:#email-support div[class*=header]
hoursOfOperationTitle = [css]:#hours-of-operation div[class*=header]
preferencesTab = [xpath]://*[@aria-controls="extended-service"]
helpAndSupportTab = [id]:help-and-support

#MSPDetailsTile
primaryAdministratorDropdownMSP = [css]:#primaryAdministrator-modal-desc svg
primaryAdministratorHeaderMSP = [xpath]://h4[@id='primaryAdministrator-modal-label']
primaryAdministratorSubTitleMSP = [css]:#primaryAdministrator-modal-desc label
primaryAdministratorListMSP = [css]:#edit_modal_undefined-listbox li
primaryAdministratorLabelMSP = [css]:#primaryAdministrator div[class*=label]
primaryAdministratorEditMSP = [css]:#primaryAdministrator [class*=icon-button]
primaryAdministratorNameMSP = [css]:#primaryAdministrator span
primaryAdministratorEmailMSP = [xpath]:(//*[@id='primaryAdministrator']//p[1])
primaryAdministratorCancelButtonMSP = [id]:editCancelBtn
primaryAdministratorSaveButtonMSP = [id]:editSaveBtn

#Service Delivery Partner
serviceDeliveryToggle = [css]:#serviceDeliveryPartner-authorized span:nth-child(2)
serviceDeliveryTitle = [css]:#serviceDeliveryPartner-authorized div[class*=label]

#Subscription Authorized Partner
subscriptionAuthorizedToggle = [css]:#contract-authorized span:nth-child(2)
subscriptionSettingsTitle = [css]:#subscription-settings div[class*=panel__title]
subscriptionContractsTitle = [css]:#subscription-contracts div[class*=panel-header]
addNewContractBtn = [id]:add-new-contract
subscriptionContractAllow = [xpath]://*[contains(@id,'contract-authorized-modal-desc')]//following::button[1]
contractModelTitle = [css]:#contract-add-modal-label
addcontracModelLabel = [css]:#contract-add-modal-desc h4
contractIDLabel = [id]:#text-label
expiresLabel = [id]:expires-label
countryLabel = [id]:country-label
currencyLabel = [id]:currency-label
contractIdInput = [id]:text
paymentTerms = [xpath]://label[contains(@id,'paymentTerms-label')]//following::div//input[@name = 'paymentTerms']
monthlyCostPerSeat = [id]:costPerSeat
editMonthlyCostperSeat = [css]:#costPerSeat
startDataPicker = [css]:#startDate:first-child
expiresDatepicker= [css]:#expires
autoRenewText= [css]:#contract-add-modal-desc label > span:nth-child(2)
todayButton = [xpath]://*[contains(@class,'CalendarMonth_table')]//tr//td[contains(@class,'CalendarDay__highlighted')]
monthKeyCurrent = [xpath]:(//*[contains(@class,'CalendarMonth_caption')]//strong)[2]
endDateDialogRightArrow= [css]:div[class*=DayPickerNavigation] div:nth-child(2)  svg
daysOnCurrentMonthKey=[css]:div[class*=DayPicker_transitionContainer] div:nth-child(2) tbody tr td[class*=CalendarDay]
countryDropdown = [css]:#contract-add-modal-desc [class*=select__open] svg
contractCountryList = [xpath]://*[@aria-labelledby='country-label']//li
contractCurrencyDropdown = [xpath]://*[@id = 'currency']
currencyDropdownInput = [xpath]://div[@id='currency']
countryDropdownValueLabel = [css]:#country span
currencyDropdownArrow = [xpath]://*[@name='currency']//following::span//div
currencyList = [xpath]://ul[@id='currency-listbox']//li
contractSaveBtn = [id]:contract-save
subscriptionDesc = [css]:#contract-add-modal-desc h4
plandropdownArrow = [xpath]://input[@name='planId']//following::span//div
planSearchOnPopup=[xpath]:(//ul[contains(@id,'planId-listbox')])//ancestor::div//div//input
planSelectOnPopup=[xpath]://*[@aria-labelledby='planId-label']
createdContractList = [css]:#subscription-contracts  tr td:nth-child(1)
contractIDColumn = [css]:#contractId
countryColumn = [id]:country
expiresColumn = [id]:endDate
planColumn = [id]:plans
emptyContractMsg=[css]:#subscription-contracts  p
firstContract=[css]:#subscription-contracts tbody tr:nth-child(1)
hamburgerIcon = [css]:#subscription-contracts tbody > tr:nth-child(1) > td:nth-child(7) > button
editContract=[xpath]://ul//li[@data-value='Edit']
editContractLabel = [xpath]://h2[@id='contract-edit-modal-label']
subscriptionAuthorizedLabel = [css]:#contract-authorized [class*=label]
subscriptionContractTile = [id]:subscription-contracts
subscriptionAuthorizedPartnerValue = [css]:#contract-authorized span:first-child
paymentTermColumn = [css]:#paymentTerms
startDateColumn = [id]:startDate
autoRenewContractTxt= [css]:#contract-add-modal-desc  label  span:nth-child(2)
autoRenewContractCheckbox= [css]:#contract-add-modal-desc  label  span:nth-child(1)
expiredColValue =[css]: #subscription-contracts  table  tbody  tr:nth-child(1)  td:nth-child(4)

#Authentication tile
authenticationTitle = [css]:#sign_in [class*=header]

#notifications tab
notificationsTab = [id]:notifications
deviceNotificationsTItle = [css]:#device-notifications [class*=header]
deviceNotificationDescription = [css]:#device-notifications [class*='panel-warning']

#currency dropdown open
btnCurrencyDropdown = [css]:#currency+input+span
USDCurrencyDropdown = [id]:currency-option-3
currencyDropdownOption = [id]:currency-option-0

#Billing History Tab
billingHistoryTab=[xpath]://*[@id="partner-billing"]/span
billingPanelHeader=[xpath]://*[@id="billing-history"]//div[contains(@class,'panel-header')]
billingPanelWarning=[xpath]://*[@id="billing-history"]//div[contains(@class,'panel-warning')]
billingYearLabel=[xpath]://*[@id="billing-history"]//div[contains(@class,'billing-drop-label')]//h5
billingPeroidLable=[xpath]://*[@id="billPeriod"]//span
billingAnchorMenu=[xpath]://*[@id="dui-dp-tab-partner-billing"]//a/div
billingPeroidMonth=[xpath]://*[@id="billing-history"]//table//tbody//tr[1]//span
billingPeroidNoReportMonth=[xpath]://*[@id="billing-history"]//table//tbody//tr[3]//span
billingPeroidDownloadIcon=[xpath]://*[@id="billing-history"]//table/tbody/tr[1]/td[2]
billingSideMenu=[xpath]://*[@id="menu_billing"]
settingsSideMenu=[xpath]://*[@id="menu_mspSettings"]
logsSideMenu=[xpath]://*[@id="menu_logs"]
helpSupportSideMenu=[xpath]://*[@id="menu_support"]
whatsNewSideMenu=[xpath]://*[@id="menu_whatsNew"]
billingAdminReportHeader=[xpath]://*[@id="billingReport"]/header/div[1]
billingAdminPanelHeader=[xpath]://*[contains(@class,'dui-billing-container')]//*[contains(@class, 'dui-panel-header')]
billingAdminPanelWarning=[xpath]://*[contains(@class,'dui-billing-container')]//*[contains(@class, 'panel-warning')]
billingAdminYearLabel=[xpath]://*[contains(@class,'dui-billing-container')]//*[contains(@class, 'billing-drop-label')]//h5
billingAdminPeroidMonth=[xpath]://*[@id="dui-container"]//table/tbody/tr[1]/td[1]/span
billingAdminPeroidNoReportMonth=[xpath]://*[@id="dui-container"]//table/tbody/tr[3]/td[1]/span
overviewTab=[xpath]://*[@id="overview"]

#NFR_Story_837206_Automation_of_Add_HP_Partner_Business_Manager_(PBM)_field_(Name/Email)_to_Partner_Overview
allowEmailNotification= [id]:dui-confirm-save
emailNotificationText =  [xpath]://*[contains(@id,'dui-contract-authorized-modal-desc')]//div[@class='dui-modal-content']
emailToastnotification = [xpath]://*[@id="dui-app-scroll"]/div[4]/div/div/span
allowbtnLoader = #dui-confirm-save > svg

#PBM
partnerBusinessManagerHeader = [css]:#partnerBusinessManager-modal-label
onboardBusinessManagerHeader = [css]:#onboardingBusinessManager-modal-label
partnerBusinessManagerLabel = [css]: #partnerBusinessManager [class*="label"]
onboardBusinessManagerLabel = [css]: #onboardingBusinessManager [class*="label"]
parnterBusinessManagerEdit = [css]:#partnerBusinessManager svg
onboardBusinessManagerEdit = [css]:#onboardingBusinessManager svg
onboardingBusinessManagerEdit = [css]:#onboardingBusinessManager svg
pbmFirstNameEditSearchBoxLabel = [css]:#partnerBusinessManager-modal-desc  div:nth-child(1)  > label:nth-child(1)
pbmLastNameEditSearchBoxLabel = [css]:#partnerBusinessManager-modal-desc  div:nth-child(2)  > label:nth-child(1)
pbmEmailEditSearchBoxLabel = [css]:#partnerBusinessManager-modal-desc  div:nth-child(3)  > label:nth-child(1)
pbmFirstNameEditSearchBox = [css]:[name=edit_modal_partnerBusinessManagerFirstName]
pbmLastNameEditSearchBox = [css]:[name=edit_modal_partnerBusinessManagerLastName]
pbmEmailEditSearchBox = [css]:[name=edit_modal_partnerBusinessManagerEmailAddress]
obmFirstNameEditSearchBoxLabel = [css]:#onboardingBusinessManager-modal-desc  div:nth-child(1)  > label:nth-child(1)
obmLastNameEditSearchBoxLabel = [css]:#onboardingBusinessManager-modal-desc  div:nth-child(2)  > label:nth-child(1)
obmEmailEditSearchBoxLabel = [css]:#onboardingBusinessManager-modal-desc  div:nth-child(3)  > label:nth-child(1)
obmFirstNameEditSearchBox = [css]:[name=edit_modal_onboardingBusinessManagerFirstName]
obmLastNameEditSearchBox = [css]:[name=edit_modal_onboardingBusinessManagerLastName]
obmEmailEditSearchBox = [css]:[name=edit_modal_onboardingBusinessManagerEmailAddress]
pbmEmailNotificationMsg = [css]:#partnerBusinessManager-modal-desc  label  span:nth-child(2)
obmEmailNotificationMsg = [css]:#onboardingBusinessManager-modal-desc  label  span:nth-child(2)
pbmEmailNotificationCheckboxValue = [css]:#partnerBusinessManager-modal-desc  label  span:nth-child(1)
obmEmailNotificationCheckboxValue = [css]:#onboardingBusinessManager-modal-desc label  span:nth-child(1)
pbmObmEditSaveBtn= [id]:editSaveBtn
pbmEditCancelBtn= = [id]:editCancelBtn
pbmObmtoastNotification = [xpath]://div[@role='alert']/div/span
pbmObmtoastNotificationCloseBtn = [xpath]://div[@role='alert']//button
obmTitle = [css]:[class*=modal--dialog] h6:last-of-type
obmFirstNameSearchBox = [css]:[name=obm_fname]
obmLastNameSearchBox = [css]:[name=obm_lname]
obmEmailSearchBox = [css]:[name=obm_email]
partnerBusinessManagerName = [css]:#partnerBusinessManager span
onboardBusinessManagerName = [css]:#onboardingBusinessManager span
partnerBusinessManagerEmail = [css]:#partnerBusinessManager p
onboardBusinessManagerEmail = [css]:#onboardingBusinessManager p
emailNotificationHeader = [css]:#dui-contract-authorized-modal-label
onboardToggleLoader = [xpath]://*[@id='onboard-authorized-new']//*[contains(@class,'dui-epr-loader')]
clearSearchBoxFilter = [css]:[class*=table-container] > div:nth-child(1) button:nth-last-child(3)

#customer reference id
crsIdLabelText =[xpath]://div[@id='crsId']/div[contains(@class,'label')]
crsIdText= [xpath]://div[@id='crsId']//div[@class='dui-depr-value']//p
crsIdStateText=[xpath]://div[@id='crsId']//div[@class='dui-depr-value']//span
crsIdErrorReasonText=[xpath]://div[@id='crsId']//div[@class='dui-depr-value']//div[@class='display-center']/p[3]
crsIdRefreshIcon=[xpath]://div[@id='crsId']//div[@class='dui-icon dui-icon-button']/*[@name='IconReload']
crsIdEditIcon=[xpath]://div[@id='crsId']//div[@class='dui-icon dui-icon-button']/*[@name='IconPencil']
crsIdAddModalWindowHeaderText=[xpath]://h4[@id='crsId-modal-label']
crsIdAddModalWindowLabelText=[xpath]://div[@class='dui-modal-content']/span
crsIdAddModalWindowTextbox=[xpath]://input[@name='edit_modal_crsId']
crsIdAddModalWindowSaveButton=[xpath]://button[@id='editSaveBtn']/span[text()='Save']
crsIdAddModalWindowCancelButton=[xpath]://button[@id='editCancelBtn']/span[text()='Cancel']
crsIdStringLengthErrorMessageLabel=[xpath]://span[text()='Maximum 40 characters allowed']
partnerDetailsUpArrowIcon=[xpath]://div[@aria-controls='dui-dsummary-card']//span[contains(@class,'dsummary-card-title-view')]
partnerSettingsPageCrsIdLabel=[xpath]://div[@id='crsId']/div
partnerSettingsPageCrsIdText=[xpath]://div[@id='crsId']//p
dashCRSIdText=[xpath]://div[@id='crsId']//div[@class='dui-depr-value']//span
partnerDetailsEmailLink=[xpath]://span[@class='dui-link']