ResourceCenterInAppBar= [id]:pendo-resource-center-icon
Resourcecentertext = [xpath]://div[@id='pendo-resource-center-main-module-container']//h2
closearrowbutton = [xpath]://button[contains(@class,'pendo-close') or contains(@aria-label,'close')]

ResourceCenterCloseButton = [xpath]:(//button[@aria-label='close' or contains(@class, 'close')])[3]

nextbutton = [xpath]://button[contains(text(),'Next')]
backbutton = [xpath]://button[contains(text(),'Back')]
donebutton = [xpath]://button[contains(text(),'Done')]

EnrollYourFleetTitle = [xpath]://div[text()='Enroll Your Fleet']
EnrollYourFleetDescription = [xpath]://div[text()='Add devices, then enroll to monitor']
EnrollYourFleetArrowButton = [xpath]:(//button[contains(@id, 'pendo-right-caret')])[1]
EnrollYourFleetBackButton = [xpath]://button[@aria-label='Back to Resource Center Home']

# Enroll Your Fleet Sub-options
AddPCsOption = [xpath]://div[text()='Add PCs']
AddPCsDescription = [xpath]:(//button[@id='pendo-a11y-list-item-button-block-0']//div)[2]
AddVirtualMachinesOption = [xpath]://div[text()='Add Virtual Machines']
AddVirtualMachinesDescription = [xpath]:(//button[@id='pendo-a11y-list-item-button-block-1']//div)[2]
AddPhysicalAssetsOption = [xpath]://div[text()='Add Physical Assets']
AddPhysicalAssetsDescription = [xpath]:(//button[@id='pendo-a11y-list-item-button-block-2']//div)[2]


# Onboarding completion status
OnboardingCompletionStatus = [xpath]:(//div[contains(@id,'pendo-progress-bar')]//div)[4]

DiscoverMoreTitle = [xpath]://div[text()='Discover More']
DiscoverMoreDescription = [xpath]://div[text()='Value-adds in WXP']
DiscoverMoreArrowButton = [xpath]:(//button[contains(@id, 'pendo-right-caret')])[2]

PrintersTitle = [xpath]://div[text()='Printers']
PrintersDescription = [xpath]://div[text()='Get your printers ready']
PrintersArrowButton = [xpath]:(//button[contains(@id, 'pendo-right-caret')])[3]

#Add PC
# Header Section
AddPCTitle = [xpath]://h2[text()='Add PCs']

# Content Sections
OnboardDesktopsText = [xpath]://h3[contains(text(),'Onboard desktops')]

# Good to Know Section
GoodToKnowTitle = [xpath]://strong[contains(text(),'Good to know')]
GoodToKnowBullet1 = [xpath]://li[contains(text(), 'Onboard at least 10% of your license seats so WXP can begin to generate valuable insights.')]
GoodToKnowBullet2 = [xpath]://span[contains(text(), 'Make sure HP domains are allow-listed. Get more info in')]

# Navigation Buttons
StartTourButton = [xpath]://button[contains(text(),'Start tour')]
KnowledgeBaseLink = [xpath]://a[contains(text(), 'Knowledge Base') or contains(@href, 'knowledge')]

# Navigate to PCs Guide Popup
NavigateToPCsStepNumber = [xpath]://p[contains(text(),'1 / 4')]
NavigateToPCsTitle = [xpath]://h2[contains(text(),'Navigate to PCs')]
NavigateToPCsMainDescription = [xpath]://h3[contains(text(),'View your fleet, add new PCs, and keep everything organized.')]
NavigateToPCsSubDescription = [xpath]://span[contains(text(),' menu to continue.')]
Addpcslink = [xpath]://a[@id='menu_devices_pcs']

# Manage PCs Guide Popup (Step 2/4)
ManagePCsStepNumber = [xpath]://p[contains(text(),'2 / 4')]
ManagePCsTitle = [xpath]://h2[contains(text(),'Manage PCs')]
ManagePCsMainDescription = [xpath]://h3[contains(text(),'View and manage your PCs in one place. Use search and filters to find what you need. To onboard your fleet, start here.')]
ManagePCsSubDescription = [xpath]:(//p[contains(@id,'pendo-text')])[2]
ManagePCsAddButton = [id]:download-client-software

# Choose Device Type Guide Popup (Step 3/4)
ChooseDeviceTypeStepNumber = [xpath]://p[contains(text(),'3 / 4')]
ChooseDeviceTypeTitle = [xpath]://h2[contains(text(),'Choose device type')]
ChooseDeviceTypeSubDescription = [xpath]://h3[contains(@id,'pendo-text')]
ChooseDeviceTypeCloseButton = [xpath]://button[contains(@class,'pendo-close') or contains(@aria-label,'close')]
TelemetryDevicesOption = [id]:card-TELEMETRY

# Choose Method Guide Popup (Step 4/4)
ChooseMethodStepNumber = [xpath]://p[contains(text(),'4 / 4')]
ChooseMethodTitle = [xpath]://h2[contains(text(),'Choose method')]
ChooseMethodMainDescription1 = [xpath]://h3[contains(text(),'Put an HP agent on each device or just ')]
ChooseMethodMainDescription2 = [xpath]://h3[contains(text(),'sync Microsoft Intune to import existing device data.')]
ChooseMethodDoneButton = [xpath]://button[contains(text(),'Done')]

#Add Virtual Machines
# Header Section
AddVirtualMachinesTitle = [xpath]://p[contains(text(),'Add Virtual Machines')]

# Content Sections
OnboardVirtualMachinesText = [xpath]://h3[contains(text(),'Onboard virtual machines into your fleet via manual installation or automated enrollment.')]

# Navigate to Virtual Machines Guide Popup (Step 1/4)
NavigateToVirtualMachinesStepNumber = [xpath]://p[contains(text(),'1 / 4')]
NavigateToVirtualMachinesTitle = [xpath]://h2[contains(text(),'Navigate to Virtual Machines')]
NavigateToVirtualMachinesMainDescription = [xpath]://h3[contains(text(),'View your fleet, add new virtual machines, and keep everything organized.')]
NavigateToVirtualMachinesSubDescription = [xpath]:(//span[contains(@id,'pendo-text')])[3]
AddVirtualMachinesLink = [xpath]://a[@id='menu_devices_virtualMachines']

# Manage Virtual Machines Guide Popup (Step 2/4)
ManageVirtualMachinesStepNumber = [xpath]://p[contains(text(),'2/ 4')]
ManageVirtualMachinesTitle = [xpath]://h2[contains(text(),'Manage virtual machines')]
ManageVirtualMachinesMainDescription = [xpath]://h3[contains(text(),'Manage all your virtual machines from this central hub. Use search and filters to find what you need.')]
ManageVirtualMachinesSubDescription = [xpath]:(//p[contains(@id,'pendo-text')])[2]
ManageVirtualMachinesAddButton = [id]:download-client-software

#Add Physical Assets
# Header Section
AddPhysicalAssetsTitle = [xpath]://h2[contains(text(),'Add Physical Assets')]

# Content Sections
OnboardPhysicalAssetsText = [xpath]://h3[contains(text(),'Track everything in one spot')]


# Navigation Buttons
AddPhysicalAssetsStartTourButton = [xpath]://button[contains(text(),'Start tour')]

# Navigate to Physical Assets Guide Popup (Step 1/4)
NavigateToPhysicalAssetsStepNumber = [xpath]://p[contains(text(),'1 / 3')]
NavigateToPhysicalAssetsTitle = [xpath]://h2[contains(text(),'Navigate to Physical Assets')]
NavigateToPhysicalAssetsMainDescription = [xpath]://h3[contains(text(),'View your fleet, add new physical assets, and keep everything organized.')]
NavigateToPhysicalAssetsSubDescription = [xpath]://p[contains(@id,'pendo-text-fcf743e8')]
AddPhysicalAssetsLink = [xpath]://a[@id='menu_devices_physicalAssets']

# Manage Physical Assets Guide Popup (Step 2/4)
ManagePhysicalAssetsStepNumber = [xpath]://p[contains(text(),'2 / 3')]
ManagePhysicalAssetsTitle = [xpath]://h2[contains(text(),'Manage Physical Assets')]
ManagePhysicalAssetsMainDescription = [xpath]://h3[contains(text(),'Manage all your physical assets from this central hub.')]
ManagePhysicalAssetsSubDescription = [xpath]://h3[contains(text(),'To onboard physical assets, start here.')]
ManagePhysicalAssetsAddButton = [id]:add-device

# Additional Choose Method descriptions for Physical Assets
CSVTemplatestepnumber = [xpath]://p[contains(text(),'3 / 3')]
CSVTemplateheader = [xpath]://h2[contains(text(),'Use the CSV template')]
ChooseMethodPhysicalAssetsDescription1 = [xpath]://h3[contains(text(),'Download the template')]

ManageyourAccount = [xpath]://div[contains(text(),'Manage your company account')]
GatherEmployeeFeedback = [xpath]://div[contains(text(),'Gather employee feedback')]
ImproveExperienceScore = [xpath]://div[contains(text(),'Improve Experience Score')]
ManageScripts = [xpath]://div[contains(text(),'Manage scripts')]
TroubleshootPCIssues = [xpath]://div[contains(text(),'Troubleshoot PC issues')]
UnderstandWorkforceSentiment = [xpath]://div[contains(text(),'Understand Workforce Sentiment')]


# Manage your company account Journey
ManageAccountTitle = [xpath]://h2[contains(text(),'Manage your company account')]
ManageAccountDescription = [xpath]://h3[contains(text(),'Access and manage your organization')]
ManageAccountPermissionsBullet = [xpath]://li[contains(text(),'User must have appropriate permissions to modify account settings and roles')]
ManageAccountProfileBullet = [xpath]://li[contains(text(),'Keep your company profile and license data up-to-date')]

# Navigate to Account Guide Popup (Step 1/5)
NavigateToAccountStepNumber = [xpath]://p[contains(text(),'1 / 5')]
NavigateToAccountTitle = [xpath]://h2[contains(text(),'Navigate to Account')]
NavigateToAccountDescription = [xpath]://h3[contains(text(),'Access your organization')]
NavigateToAccountSubDescription = [xpath]:(//p[contains(@id,'pendo-text')])[2]
AccountMenuLink = [xpath]://a[@id='menu_accountManagement']

NavigateToOverviewStepNumber = [xpath]://p[contains(text(),'2 / 5')]
NavigateToAccountoverviewTitle = [xpath]://h2[contains(text(),'Manage basic details')]
NavigateToAccountoverviewDescription = [xpath]://h3[contains(text(),'Update your company profile')]

NavigateToRolesStepNumber = [xpath]://p[contains(text(),'3 / 5')]
NavigateToAccountRolesTitle = [xpath]://h2[contains(text(),'Manage Roles & Permissions')]
NavigateToAccountrolesDescription = [xpath]://h3[contains(text(),'Easily assign and manage WXP users')]

NavigateToadminStepNumber = [xpath]://p[contains(text(),'4 / 5')]
NavigateToAccountadminTitle = [xpath]://h2[contains(text(),'Manage WXP admins')]
NavigateToAccountadminDescription = [xpath]://h3[contains(text(),'Invite team members to access WXP')]

NavigateTolicensesStepNumber = [xpath]://p[contains(text(),'5 / 5')]
NavigateToAccountlicensesTitle = [xpath]://h2[contains(text(),'Monitor licenses and usage')]
NavigateToAccountlicensesDescription = [xpath]://h3[contains(text(),'Review active licenses and monitor seat usage')]


#Gather Your feedback Journey
GatherYourfeedbackTitle = [xpath]://h2[contains(text(),'Gather employee feedback')]
GatherYourfeedbackDescription = [xpath]://h3[contains(text(),'Launch a targeted Pulse to collect')]
GatheryourfeedbackPermissionsBullet = [xpath]://li[contains(text(),'Pulses are designed for quick')]
GatherYourfeedbackProfileBullet = [xpath]://li[contains(text(),'Align surveys with your internal ')]

NavigateToPulseStepNumber = [xpath]://p[contains(text(),'1 / 8')]
NavigateTopulseadminTitle = [xpath]://h2[contains(text(),'Navigate to Pulses')]
NavigateTopulseDescription = [xpath]://h3[contains(text(),'Use Pulses to gather employee')]
pulselink = [xpath]://a[@id='menu_pulses']

NavigateToaddPulseStepNumber = [xpath]://p[contains(text(),'2 / 8')]
NavigateToaddpulseadminTitle = [xpath]://h2[contains(text(),'Create Pulses')]
NavigateToaddpulseDescription = [xpath]://h3[contains(text(),'You can create different types of')]
Addcustompulses = [xpath]://span[contains(text(),'Create')]

NavigateTocustomPulseStepNumber = [xpath]://p[contains(text(),'3 / 8')]
NavigateTocustompulseadminTitle = [xpath]://h2[contains(text(),'Create Custom Pulse')]
NavigateTocustompulseDescription = [xpath]://h3[contains(text(),'Pulses are delivered as device pop-ups')]
custompulses = [xpath]://div[@id='custom_pulse']//button

osToastniotification =[xpath]://div[@id='delivery_method_btn_os_toast_notification']

NavigateToscratchPulseStepNumber = [xpath]://p[contains(text(),'4 / 8')]
NavigateToscratchpulseadminTitle = [xpath]://h2[contains(text(),'Templates')]
NavigateToscratchpulseDescription = [xpath]://h3[contains(text(),'Start from scratch or pick from ready')]
scratchpulses = [xpath]:(//div[@id='pulse_template_btn_create_from_scratch']//div)[1]

NavigateTocontentPulseStepNumber = [xpath]://p[contains(text(),'5 / 8')]
NavigateTocontentpulseadminTitle = [xpath]://h2[contains(text(),'Build your content')]
NavigateTocontentpulseDescription = [xpath]://h3[contains(text(),'Choose from various question formats')]

NavigateToschdulePulseStepNumber = [xpath]://p[contains(text(),'6 / 8')]
NavigateToschdulepulseadminTitle = [xpath]://h2[contains(text(),'Schedule Pulse')]
NavigateToschdulepulseDescription = [xpath]://h3[contains(text(),'Configure options to specify when your Pulse will be sent.')]

NavigateToaudiencePulseStepNumber = [xpath]://p[contains(text(),'7 / 8')]
NavigateToaudiencepulseadminTitle = [xpath]://h2[contains(text(),'Pulse Audience')]
NavigateToaudiencepulseDescription = [xpath]://h3[contains(text(),'Choose the audience from Entra ID')]

NavigateTopublishPulseStepNumber = [xpath]://p[contains(text(),'8 / 8')]
NavigateTopublishpulseadminTitle = [xpath]://h2[contains(text(),'Publish Pulse')]
NavigateTopublishpulseDescription = [xpath]://h3[contains(text(),'Select Publish to let the Pulse run as ')]

#Improve Experience score Journey
GatherYourexperienceTitle = [xpath]://h2[contains(text(),'Improve Experience Score')]
GatherYourexperienceDescription = [xpath]://h3[contains(text(),"Gain insights")]
GatheryourexperiencePermissionsBullet = [xpath]://li[contains(text(),'The Experience Score is updated regularly')]
GatherYourexperienceProfileBullet = [xpath]://li[contains(text(),'When you follow recommended actions')]

NavigateToUnderstandimproveStepNumber = [xpath]://p[contains(text(),'1 / 3')]
NavigateToUnderstandimproveTitle = [xpath]://h2[contains(text(),"Understand employees' experiences")]
NavigateToUnderstandimproveDescription = [xpath]://h3[contains(text(),"Your Experience Score is a complete view")]

NavigateTosystem-wideimproveStepNumber = [xpath]://p[contains(text(),'2 / 3')]
NavigateTosystem-wideimproveTitle = [xpath]://h2[contains(text(),'Check system-wide issues')]
NavigateTosystem-wideimproveDescription = [xpath]://h3[contains(text(),'Review top issues affecting system')]


NavigateTorecommendedimproveStepNumber = [xpath]://p[contains(text(),'3 / 3')]
NavigateTorecommendedimproveTitle = [xpath]://h2[contains(text(),'View recommended actions')]
NavigateTorecommendedimproveDescription = [xpath]://h3[contains(text(),'These actions are based on your Experience score')]

#manage Scripts:

#Troubleshoot PC issues Journey:
#Improve Experience score Journey
GatherTroubleshootTitle = [xpath]://h2[contains(text(),'Troubleshoot PC issues')]
GatherTroubleshootDescription = [xpath]://h3[contains(text(),"Quickly identify and resolve PC")]
GatherTroubleshootBullet = [xpath]://li[contains(text(),'This tour focuses on individual device diagnostics')]
GatherTroubleshootBullet2 = [xpath]://li[contains(text(),'Data points are based on actual reported issues ')]

NavigatePCStepNumber = [xpath]://p[contains(text(),'1 / 7')]
NavigatePCTitle = [xpath]://h2[contains(text(),"Navigate to PCs")]
NavigatePCDescription = [xpath]://h3[contains(text(),"Navigate to PCs for a list of all devices.")]

NavigateselectPCStepNumber = [xpath]://p[contains(text(),'2 / 7')]
NavigateselectPCTitle = [xpath]://h2[contains(text(),"Select this PC")]
NavigateselectPCDescription = [xpath]://h3[contains(text(),"View comprehensive info for a specific device.")]
Serialnumberpclick = [xpath]:(//a[contains(@class,'device-serial-number')])[1]

NavigatePCoverviewStepNumber = [xpath]://p[contains(text(),'3 / 7')]
NavigatePCoverviewTitle = [xpath]://h2[contains(text(),"Get an overview")]
NavigatePCoverviewDescription = [xpath]://h3[contains(text(),"View essential data for this PC")]

NavigatePCtimelineStepNumber = [xpath]://p[contains(text(),'4 / 7')]
NavigatePCtimelineTitle = [xpath]://h2[contains(text(),"Check the Timeline")]
NavigatePCtimelineDescription = [xpath]://h3[contains(text(),"It tracks errors, events, and anomalies")]

NavigatePChealthStepNumber = [xpath]://p[contains(text(),'5 / 7')]
NavigatePChealthTitle = [xpath]://h2[contains(text(),"Check Health and Protection")]
NavigatePChealthDescription = [xpath]://h3[contains(text(),"Dive deeper into the device?s health and security status")]

NavigatePCBIODStepNumber = [xpath]://p[contains(text(),'6 / 7')]
NavigatePCBIOSTitle = [xpath]://h2[contains(text(),"Check BIOS and Drivers")]
NavigatePCBIOSDescription = [xpath]://h3[contains(text(),"These insights and analytics can help")]

NavigatePCsoftwareStepNumber = [xpath]://p[contains(text(),'7 / 7')]
NavigatePCsoftwareTitle = [xpath]://h2[contains(text(),"Check Software")]
NavigatePCsoftwareDescription = [xpath]://h3[contains(text(),"Explore insights and analytics around")]

#Understand Workforce Sentiment Journey:
GatherSentimentTitle = [xpath]://h2[contains(text(),'Understand workforce sentiment')]
GatherSentimentDescription = [xpath]://h3[contains(text(),"Use this guided experience to launch a Sentiment Pulse")]
GatherSentimentBullet = [xpath]://li[contains(text(),'Sentiment data is anonymous and aggregated')]
GatherSentimentBullet2 = [xpath]://li[contains(text(),'Align surveys with your internal communication')]

NavigateTosentientPulseStepNumber = [xpath]://p[contains(text(),'1 / 7')]
NavigateTosentimentpulseadminTitle = [xpath]://h2[contains(text(),'Navigate to Pulses')]
NavigateTosentimentpulseDescription = [xpath]://h3[contains(text(),'Use Pulses to gauge your')]

NavigateToaddsentimentPulseStepNumber = [xpath]://p[contains(text(),'2 / 7')]
NavigateToaddsentimentpulseadminTitle = [xpath]://h2[contains(text(),'Create Sentiment Pulse')]
NavigateToaddsentimentpulseDescription = [xpath]://h3[contains(text(),'Start building a Pulse to measure')]

NavigateTocreatesentimentPulseStepNumber = [xpath]://p[contains(text(),'3 / 7')]
NavigateTocreatesentimentpulseadminTitle = [xpath]://h2[contains(text(),'Create Sentiment Pulse')]
NavigateTocreatesentimentpulseDescription = [xpath]://h3[contains(text(),'Select Sentiment Pulse to launch')]
sentimentpulses = [xpath]://div[@id='sentiment_pulse']//button


NavigateTocreatesentimentPulsecontentStepNumber = [xpath]://p[contains(text(),'4  / 7')]
NavigateTocreatesentimentpulsecontentTitle = [xpath]://h2[contains(text(),'Pulse Content')]
NavigateTocreatesentimentpulsecontentDescription = [xpath]://h3[contains(text(),'Each Pulse includes three predefined')]

NavigateTocreatesentimentPulseschduleStepNumber = [xpath]://p[contains(text(),'5 / 7')]
NavigateTocreatesentimentpulseschduleTitle = [xpath]://h2[contains(text(),'Set schedule for Pulses')]
NavigateTocreatesentimentpulseschduleDescription = [xpath]://h3[contains(text(),'Decide when recipients will receive the')]

NavigateTocreatesentimentPulseaudienceStepNumber = [xpath]://p[contains(text(),'6 / 7')]
NavigateTocreatesentimentpulseaudienceTitle = [xpath]://h2[contains(text(),'Select audience')]
NavigateTocreatesentimentpulseaudienceDescription = [xpath]://h3[contains(text(),'Choose the audience from Entra ID')]

NavigateTocreatesentimentPulsepublishStepNumber = [xpath]://p[contains(text(),'7 / 7')]
NavigateTocreatesentimentpulsepublishTitle = [xpath]://h2[contains(text(),'Publish Pulse')]
NavigateTocreatesentimentpulsepublishDescription = [xpath]:(//div[contains(@id,'pendo-text')])[6]



