#staging environment device details
DEVICE_NAME = 000804022X
DEVICE_NAME_BIOSDRIVER = 5CD7162GB0
DEVICE_NAME_BIOSDRIVER_ID = 93Aa817uP1a603O-hwSLzM4jlSVoKnhIFw6GWEIksgE
BIOS_TENANT_ID = 278ca331-c848-43ee-918d-85c179aefd6b
LDA_DEVICE_NAME = 000804022X
UPI_DEVICE_NAME = HPQA031709174253302700
ROLE_USER = auto test
IDENTITY_USER = Device LIST
GLOBAL_FILTER_COMPANY_DO_NOT_DELETE = sgfcomp1usst
GLOBAL_FILTER_LOCATION1_DO_NOT_DELETE = Ghaziabad
GLOBAL_FILTER_LOCATION2_DO_NOT_DELETE = Sahibabad
GLOBAL_FILTER_LOCATION3_DO_NOT_DELETE = SMG2
GLOBAL_FILTER_LOCATION4_DO_NOT_DELETE = A181
DEVICE_ID = UFF5NK9ArgrJ1f1bh3Rii5N9xCrKQJUKdkR9iGfU5aE
TENANT_ID = fdacf4e1-5bf6-406d-82cb-29dbc0879f97
PROACTIVE_SECURITY_COMANY = UI Automation- Do not delete
CONTROLLER_HOSTNAME = ProActiveTest.hp.com
GROUP_ID = ProActiveTestGroup1
PROACTIVE_COMPANY_TENANT_ID = 01167fde-69ef-4ba2-8d20-15d96c29fc54
CATALYST_API_BASE_URL = https://usstagingms.prod.hpicatalyst.com/
DEVICE_IMPORT_COMPANY = DeviceListAuto Do not delete
DEVICE_IMPORT_COMPANY_SNOW = Company Automation - Do Not Delete
AZURE_USERS = manjiri.abhijit.nargunde@eusandboxqa.com,murari.kumar@eusandboxqa.com,pushpendu.sitoke@eusandboxqa.com,radhika.nawhal@eusandboxqa.com
ROOT_ADMIN_TEST_COMPANY = CompanyListAuto-Do not delete
TENANT_ID_DEVICELISTAUTO_DONOTDELETE = 1207dc51-5a8b-44f8-b480-0b06444ea9f2
DEVICE_DETAILS_COMPANY = UI Automation- Do not delete
DEVICE_LOCATION = 10300 Energy Dr, Spring, TX 77389, USA
USER_IMPORT_COMPANY = Invite flow
AZURE_IMPORT_EMAIL = pushpendu.sitoke@hpfeatureteam.com
AZURE_IMPORT_PASSWORD = N0P3eking05
PRODUCTION_TEST_COMPANY = Automation Company - Do Not Delete
EMAIL_SEARCH_FOR_DEVICE = devicelistcomp
WORKFLOW_URLCHECK_DASHBOARD = "https://staging.hpworkflows.com/ui/dashboard";
WORKFLOW_URLCHECK_REPORT = "https://staging.hpworkflows.com/services/reporting/1.0/reporting?page=standard";
WINDOWSSOFTWAREJSONDATA = https://dcefh8tp1pusz.cloudfront.net/STAGING/%7bE5FB98E0-0784-44F0-8CEC-95CD4690C43F%7d/Archive/versioncatalog.json
MACSOFTWAREJSONDATA = 	  http://downloads.hpdaas.com/staging/macos/APMAgentAppcast.xml
ANDROIDSOFTWAREDATA = https://play.google.com/store/apps/details?id=com.hp.apmagent
WORKFLOW_URLCHECK_DASHBOARD = https://staging.hpworkflows.com/ui/view/dashboard
WORKFLOW_URLCHECK_REPORT = https://staging.hpworkflows.com/ui/view/reports/type/standard
TENANT_ID_INCIDENTTAGS_DONOTDELETE = 2a4f4ff8-dff0-4184-ae28-d2c54685b236
WORKFLOW_CHILD_COMPANY = TestChild1
WORKFLOW_REPORT_DETAILS_API = https://usstagingms.prod.hpicatalyst.com
LHADMIN_PORTAL_URL = https://lhadminportal-usstagingms.lh201.com/
WORKFLOW_USER_EMAIL = wfstagetest07@yopmail.com
ROOT_ADMIN_NAME = RootF RootL
USER_IMPERSONATION_TEST_USER_PRIMARY_ADMIN_NAME = userimpersonation testmspus
COMPANY_ID = C-KbjtAjw3
NONENGLISHCOMPANY = CompanyListAutoDo not delete
NONENGLISHCOMPANY_TENANTID = b9297914-d5de-4511-a741-442b4c3ce74e
WORKFLOW_TERMSCOND_URL = https://staging.hpworkflows.com/terms-and-conditions
WORKFLOW_URLCHECK_SETTINGS = https://staging.hpworkflows.com/ui/view/settings
ASSIGNED_PARTNER_NAME = PartnerAutoReseller - DoNotDelete
ASSIGNED_PARTNER_NAME_EMAIL = PartnerAutoReseller DoNotDelete
COMPANY_USER_NAME = invite company
ASSIGNED_PARTNER_PRIMARY_ADMIN_NAME = Partner Invite
COMPANY_COUNTRY = India
PARTNER_COUNTRY = Afghanistan
CUSTOMER_ID = C-VA4LcMst
COMPANY_NAME = PartnerAutoCompany - DoNotDelete
COMPANY_NAME_EMAIL = PartnerAutoCompany DoNotDelete
PARTNER_ID = PartnerAutoResellerDoNotDeleteID
ASSIGNED_MSP_TWO_NAME = 1AutomationMSP
ASSIGNED_MSP_ONE_NAME = uiautomationmspdonotdelete
COUNTRY = Marshall Islands
MSP_ID = MSP US
ASSIGNED_PARTNER_NAME_ADD = Partner US
PARTNER_ID_ADD = partner id add 1
STATIC_COMPANY = UI Automation- Do not delete
STATIC_COMPANY_TENANT_ID = 1207dc51-5a8b-44f8-b480-0b06444ea9f2
STATIC_COMPANY_DOMAIN_NAME = Company Automation - Do Not Delete
STATIC_COMPANY_DOMAIN_NAME_TENANT_ID = 3159dc90-05b9-442a-851c-9d8ddea9e35a
USER_COMPANY_TENANT_ID = 534fdac2-8ee4-4b3f-8254-ddf9f9f5fcd9
CUSTOMER_ID_LIMITED = C-VA4LcMst
TENANT_ID_BIOS = b3793db4-f604-49e9-a10f-fc6f4c075380
DEVICE_NAME_BIOS = 0008060039
USER_DEVICE_TAB_DETAIL = Device LIST
AUTOMATION_DEVICE_NAME = Automationdevicedonotdelete
AUTH_COMPANY_DO_NOT_DELETE = Company Auth Automation do not delete
AUTH_COMPANY_API_DO_NOT_DELETE = Invite flow
AUTHENTICATION_COMPANY_DO_NOT_DELETE = Azure Comp Auto Do not delete
AUTH_COMPANY_TENANT_ID = 4f010520-05b4-4cbd-a9a9-8884f86b7e3f
AUTH_COMPANY_ROOT_TENANT_ID = 0dfa4678-ab13-4524-b44a-296f0957ead0
RESELLER_COMPANY_NAME = CompanyAuto Do Not Delete
PARTNER_DEVICE_ID = 75960P13ME1
CHROME_DEVICE_NAME = CND9172573
CHROME_DEVICE_ID = xNPJZcAzxePZCDFVgnN6qZzfPa6x46E4Z6r2iL0AHWw
SUPPORT_EMAIL_SUBJECT = Support Request
AUTOMATION_MSP=Staging MSP US Partner new
AUTOMATION_MSP_NEW = QA Staging Partner US MSPNew
AUTOMATION_PARTNER=Automation US Resellar
AUTOMATION_PARTNER_ID=testAuto
AUTOMATION_DEVICE_NAME_BROMIUM = AutomationDeviceDoNotDelete0
INCIDENT_ID = b10cd
AUTOMATION_DEVICE_NAME_BROMIUM = AutomationDeviceDoNotDelete0
INSTANCE_URL = https://dev63341.service-now.com/
COMPANY_NAME_EMAIL_NOTIFY = EmailnotifyCompany
COMPANY_NAME_BLACKBOX = EmailnotifyCompany
STANDARD_COMPANY = StandardCompany
USERSEARCHFORWFROLE=WorkflowStageCompany00@hpmsqa.mailinator.com
AUTOMATION_DEVICE_NAME_BROMIUM = AutomationDeviceDoNotDelete0
COUNTRY_NAME_ADD = India
AUTO_AUTH_COMPANY=Auto Auth Comp - Do Not Delete
EMM_COMPANY_TENANT_ID=b8222a45-96c8-48d6-b3cf-a1307bcb760b
EMM_ADMIN_COMPANY_TENANT_ID = 81db6629-6d62-44e1-a859-4e67909eee89

#Companies
AUTOMATION_COMPANY = CompanyAutoCompany - DoNotDelete
AUTOMATION_COMPANY_TENANT_ID = 1a7a4d49-36b9-4830-acf3-fcc728956e3b
DETAILS_COMPANY = CompanyAutoDetailsCompany - DoNotDelete
DETAILS_COMPANY_TENANT_ID = 7095472e-29a8-4cd4-86a3-1277d75fa836
ADD_COMPANY_THROUGH_ROOT_EMAIL = companyautodetailsitainviteflowusstag@hpmsqa.mailinator.com
ADD_COMPANY_THROUGH_ROOT_COUNTRY = Afghanistan
ADD_COMPANY_THROUGH_ROOT_COUNTRY_CODE = AF
ADD_COMPANY_THROUGH_ROOT_NAME = InviteFlowCheck
ADD_COMPANY_THROUGH_ROOT_MSP_NAME = CompanyAutoDetailsMSPInviteFlow - DoNotDelete
ADD_COMPANY_THROUGH_ROOT_MSP_NAME_ID = d326df06-7526-42bb-ad53-f49eaa0b2b70
ADD_COMPANY_THROUGH_ROOT_PARTNER_NAME = CompanyAutoDetailsResellerInviteFlow - DoNotDelete
ADD_COMPANY_THROUGH_ROOT_PARTNER_NAME_ID = 80227d7c-e0f4-485c-82e0-c39735312f70
ADD_COMPANY_THROUGH_ROOT_ITA_FIRST_NAME = CompanyAutoDetailsITAInviteFlow
ADD_COMPANY_THROUGH_ROOT_ITA_LAST_NAME = DoNotDelete
ADD_COMPANY_THROUGH_ROOT_PARTNER_ID = CompanyAutoDetailsResellerInviteFlowDoNotDeleteID
RESELLER_COMPANY_ID = C-afKphrWh

ROLE_ID_URL = https://usstaging.hpdaas.com/
CLIENT_ID = 07a56485-10a5-4563-af84-dccb827bac6d
CLIENT_SECRET = Ysaq5UvRLTktLo+H9P8wvmlLlVGT3HicX32e2DcZRe0=
GRANT_TYPE = client_credentials
ZTE_DEVICE_OA3_HASH_INVALID = T0GvAwEAHAAAAAoADwRjRQAACgAPBGNF4tgWJngCCQMCABAACQABAAQACAABAAAABQAZABAAAAAAAAAAIAAAAAAAAAACAAEAAwMAEQBHZW51aW5lSW50ZWwABAA0AEludGVsKFIpIENvcmUoVE0pIGk1LTgyNTBVIENQVSBAIDEuNjBHSHoAAAAAAAAAAAYAEADoAwAAAAAAAAsAAQAHACwAICAgICAgICAgICA5N1RYVDIyU1R8VE9TSElCQSBNUTA0QUJGMTAwfAgAGgAOAAAArOLTZoOCCAAAAFAAQwBJAAAACAAaAAkAAAAoxj9GVYwIAAAAUABDAEkAAAAIABoACgAAACjGP0ZVkAgAAABCAFQASAAAAAkAEAA1Aa0AVgUAAwAAAIAbAAgAHwARAAoACQAKAgAAAA0AUgBUUE0tVmVyc2lvbjoyLjAgLUxldmVsOjAtUmV2aXNpb246MS4xNi1WZW5kb3JJRDonSUZYICctRmlybXdhcmU6NDU4ODE0LjgwMDI1NgAZAAQBiDZDsK9tsnQZhVUNqLy1ULQb7uVqxDZk5drb/vTU3rYC05bXZX+wzSslbpkPHea9gtZKYgmqpl7OHjQBXbJfTiHRsh/lX78xoENExHCoxfFCi5q7ctEbtnrBXk2zumV/dO7+6jvSzlJCAkK5nryl+bFhz0oeRrEw9G5qaCxQKKoLQHn2Ilf6W0dETT2BtaPYZt7oj/U+DB0OkDBl9eKQ+/CZ9SZttH61dexB4AQhPK0FH1e5LX2rzsV/j+57r+AJHmmGnztEGcAGgOyzB5pcVY7Dt63P5kivkfBM3tGrf0G1xKy+6Pu+/JAbns41Wp/cGglVgYk/exBfdr++v5KvqwsALgAAAAAAAQAgAAAARboOFBRPDUCbAl8+Q0n9NiRKKiIs6gw5rYZY7QyLEkgMABQAyNZHSMwMLWh/cUW9nUm38Q4ADwA1Q0Q3NDgzTlJGAA8ABwBIUAAQAAcASFAAEQAWAEhQIFByb0Jvb2sgNDQwIEc1ABIAEAAyWEY1N1BBI0FDSgATABsAMTAzQ181MzM2QU4gSFAgUHJvQm9vawAXAAYAIAAUAAcASFAAFQAJADgzN0IAFgAZAEtCQyBWZXJzaW9uIDAyLjM1LjAwABgAEgAzMzA1MDExMzUyOTcxABoAEgBbVEhdWDE5LTk5NDgxABwALQAgICAgICAgICAgIDk3VFhUMjJTVHxUT1NISUJBIE1RMDRBQkYxMDB8AENTJADzogn64lGoV/DsAEq3b5rZRRj6+LJVhsUPvz7iFnp5wQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ZTE_COMPANY_TENANT_ID = 5f4eb639-2fbf-44d9-b1ab-9a826a32c87e
ZTE_DEVICE = 5CD7483NRF
ZTE_DEVICE_ID = WMCJzk07pl7ysD6cfplS-qoNGIFD0oejkwzm-15ZVFI
ZTE_DEVICE_OA3_HASH_VALID = T0GvAwEAHAAAAAoADwRjRQAACgAPBGNF4tgWJngCCQMCABAACQABAAQACAABAAAABQAZABAAAAAAAAAAIAAAAAAAAAACAAEAAwMAEQBHZW51aW5lSW50ZWwABAA0AEludGVsKFIpIENvcmUoVE0pIGk1LTgyNTBVIENQVSBAIDEuNjBHSHoAAAAAAAAAAAYAEADoAwAAAAAAAAsAAQAHACwAICAgICAgICAgICA5N1RYVDIyU1R8VE9TSElCQSBNUTA0QUJGMTAwfAgAGgAOAAAArOLTZoOCCAAAAFAAQwBJAAAACAAaAAkAAAAoxj9GVYwIAAAAUABDAEkAAAAIABoACgAAACjGP0ZVkAgAAABCAFQASAAAAAkAEAA1Aa0AVgUAAwAAAIAbAAgAHwARAAoACQAKAgAAAA0AUgBUUE0tVmVyc2lvbjoyLjAgLUxldmVsOjAtUmV2aXNpb246MS4xNi1WZW5kb3JJRDonSUZYICctRmlybXdhcmU6NDU4ODE0LjgwMDI1NgAZAAQBiDZDsK9tsnQZhVUNqLy1ULQb7uVqxDZk5drb/vTU3rYC05bXZX+wzSslbpkPHea9gtZKYgmqpl7OHjQBXbJfTiHRsh/lX78xoENExHCoxfFCi5q7ctEbtnrBXk2zumV/dO7+6jvSzlJCAkK5nryl+bFhz0oeRrEw9G5qaCxQKKoLQHn2Ilf6W0dETT2BtaPYZt7oj/U+DB0OkDBl9eKQ+/CZ9SZttH61dexB4AQhPK0FH1e5LX2rzsV/j+57r+AJHmmGnztEGcAGgOyzB5pcVY7Dt63P5kivkfBM3tGrf0G1xKy+6Pu+/JAbns41Wp/cGglVgYk/exBfdr++v5KvqwsALgAAAAAAAQAgAAAARboOFBRPDUCbAl8+Q0n9NiRKKiIs6gw5rYZY7QyLEkgMABQAyNZHSMwMLWh/cUW9nUm38Q4ADwA1Q0Q3NDgzTlJGAA8ABwBIUAAQAAcASFAAEQAWAEhQIFByb0Jvb2sgNDQwIEc1ABIAEAAyWEY1N1BBI0FDSgATABsAMTAzQ181MzM2QU4gSFAgUHJvQm9vawAXAAYAIAAUAAcASFAAFQAJADgzN0IAFgAZAEtCQyBWZXJzaW9uIDAyLjM1LjAwABgAEgAzMzA1MDExMzUyOTcxABoAEgBbVEhdWDE5LTk5NDgxABwALQAgICAgICAgICAgIDk3VFhUMjJTVHxUT1NISUJBIE1RMDRBQkYxMDB8AENTJADzogn64lGoV/DsAEq3b5rZRRj6+LJVhsUPvz7iFnp5wQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DEVICE_IMPORT_COMPANY_ZTE = Mac12

HELP_LIGHTNING_ID = HPUMTEST
HP_FORMS_ID = HPUMTEST
WORKFLOW_COMPNAME = Testing Account
SUUPORT_TEAM_USER_EMAIL= hptpm.testusernew_usstag@hpmsqa.mailinator.com
DAAS_API_BASE_URL = https://usstagingms.hpdaas.com/
DAAS_API_BASE_URL_AUTH = https://usstaging.hpdaas.com/
COMPANY_AUTO_MSP = CompanyAutoMSP - DoNotDelete
HELP_AND_SUPPORT_PARTNER_NAME=Maneesh ResellerPlus
HELP_AND_SUPPORT_MSP_NAME= Maneesh MSP
HELP_AND_SUPPORT_MSP_EMAIL=testapi23@hpmsqa.mailinator.com
HELP_AND_SUPPORT_PARTNER_EMAIL=testapi23partner@hpmsqa.mailinator.com
INTUNE_DEVICE_NAME=CCQSW22ZGGK9
INTUNE_USER_NAME=hptmqa
AIRWATCH_USER_NAME=siddhi.admintest
CHROME_USER_NAME=praveen@daas.ext.hp.com
MSP_ID = e271c711-5252-4d7e-9d64-6b0379df1b93
MSP_ID1 = b625e62e-75d7-4616-b96b-af4cdd02dd06
MSP_ID2 = 9a9fb9ec-2c5c-4a3b-a679-a93cb17530be
EMM_MSP_ID=4ac7345f-d028-449d-a7be-3c8999c68e3f
EMM_PARTNER_ID=b3b180cb-0acb-459b-801c-dd60ed3cf210
COUNTRY_CODE = IN
TEST_USER = emmcompanyteststag1@hpmsqa.mailinator.com
EMM_COMPANY_NAME= Emm Automation Us-Stage
VISIBLE_BASE_ROLE_ID_HPADMIN = f0964633-c332-45f5-a573-18b33008312e
VISIBLE_BASE_ROLE_ID_MSP = fa22c738-1758-4193-905d-67d6b76f61d0
VISIBLE_BASE_ROLE_ID_RESELLER = b038d25d-d50a-4194-b686-b968859b7180
VISIBLE_BASE_ROLE_ID_ITA = 47d09b01-1280-4b7a-b2c3-8bb52da41de5
VISIBLE_BASE_ROLE_ID_RESELLERPLUS = 3c636daf-6c67-4034-89b5-b2f707f65391
SHARE_DASHBOARD_USER_NAME = 29aug ssUS
SHARE_DASHBOARD_USER_NAME_PARTNER = Service 3julyspecialist
SHARE_DASHBOARD_USER_NAME_RA = 3july ra
DEVICE_NONHP = SEDRYFGHJ0
DEVICE_ID_NONHP = JXJ7XvhFRegTpO0qfsYaX7Gjvo5sTypiFwZxN5Z0Svs
SHARE_DASHBOARD_USER_NAME_RA = Report Admin 3July
MSP_ONE_MSP_ID = uiautomationmspdonotdeleteus
SUBSCRIPTION_COMPANY = Company Automation - Do Not Delete
DEVICE_ID_CASE_CREATION_PC_COMPANY = xgiTlu4J53hSwA442A6k-kg1lG6fzgo81f7dKm5dZOE
DEVICE_ID_CASE_CREATION_PM_COMPANY = hUaIvyO8UnF1VmKL9nRx4LNZWViL96jO52x-1IusrTk
INCIDENT_PCCOMPANY = pccompanyus
INCIDENT_PMCOMPANY = pmcompanyus

INCIDENT_ID_CASE = d0bfa

ORDERS_VALID = ordersUS.csv
DEVICE_NAME_LAST_RESTART_DATE = MXL9504MWK
LAST_RESTART_DATE_ID = 278ca331-c848-43ee-918d-85c179aefd6b
PARTNER_ID1 = 86d202cd-d1d1-4e41-a755-617894229868
COMPANY_EMAIL_ONBOARDING = hptpm.testcomponboard@hpmsqa.mailinator.com
AUTOMATION_PARTNER_PRIMARY_ADMIN_NAME = Automation US Resellar
PARTNER_EMAIL_ID = staging_automation_reseller_us@mailinator.com

COMPANY_ARCHIVED_DEVICE = CompanyAuto Do Not Delete
FAKE_DEVICE_ENROLL_COMPANY = DeviceListAuto Do not delete

#RPOS
MultiTenancy_LOCATION1_DO_NOT_DELETE = India
MultiTenancy_LOCATION2_DO_NOT_DELETE = Pune
MultiTenancy_LOCATION3_DO_NOT_DELETE = AmarApex
MultiTenancy_LOCATION4_DO_NOT_DELETE = HP

ZTE_DEVICE_SNR = 5CD91639HW
SNR_COMPANY_TENANT_ID = 5f4eb639-2fbf-44d9-b1ab-9a826a32c87e

SEARCH_DASHBOARD_NAME = Search Automation Dashboard