userMenuButtonWithImage = [xpath]://button[@title][img]
userMenuButtonWithoutImage = [xpath]://button[contains(@class,'--primary')][@title]//*[name()='svg']
userMenuButtonWorkflowNew = [xpath]://button[@title='My Profile']
loggedUser = [xpath]://div[contains(@class, 'profile__content-name')]
loggedUserNew = [xpath]://div[@class='vn-user-profile__content']/div/div[1]
reportTab = [id]:menu_reports
reportTitle = [css]:#reportList h4
reportTitleOnBreadcrumbs = [css]:#reportList li
addReportButton = [id]:add_report
addReportForm = [id]:add-report
tableOverlay = [xpath]://div[@class='vn-table__overlay']
generateReportDashboard = [xpath]://*[@id="business-review-modal-holder"]//div[contains(@class,'right-section')]//button
generateReportButtonOnPopup = [xpath]://*[@id='generate_report']
allCompaniesDropdown = [xpath]://div[@class='vn-select__button-group']
startDateDropdownDashboard = [xpath]://div[@class='date-range-picker']/div/div[1]//button[@title='Open']//*[name()='svg']//*[name()='g']
endDateDropdownDashboard = [xpath]://div[@class='date-range-picker']/div/div[2]//button[@title='Open']//*[name()='svg']//*[name()='g']
companySelectionDropdownAtReviewPopup = [xpath]:(//*[@id="business-review-modal-holder"]//div[contains(@class,'select__button-group')]//button)[5]
startDateList = [xpath]://*[@id="business-review-modal-holder"]//div[contains(@class,'options-list')]//div
endDateList = [xpath]://*[@id="business-review-modal-holder"]//div[contains(@class,'options-list')]//div
pdfCheckboxDashboard = [xpath]:(//div[@class="checkbox-container"]//*[name()='svg'])[2]
imgCheckboxDashboard = [xpath]:(//div[@class="checkbox-container"]//*[name()='svg'])[1]
messageBox = [xpath]://div[@role="presentation"]//p[contains(@class,'toast__text')]
toastNotificationClose = [xpath]://div[@role="presentation"]//button[contains(@class,'toast__close')]
reportSuccessMsg = [xpath]://div[@class='vn-modal__body']
messageClose = [xpath]://a[@class='vn-modal__close']
allCompaniesListDashboard = [xpath]://ul[@class='vn-select-content__list vn-select-content__list--scroll']/li
selectCompanyButton = [id]:select-company
paginationDropdownMenu = [xpath]://div[contains(@class,'pagination')]//a[@role='button']
selectPageOption = [xpath]://div[contains(@class,'vn-contextual-menu')]/div/div[4]
standardButton = [css]:#standardTabList
reportList = [css]:.report-title a
reportListSortOpts = [id]:sortByOption
sortByAlphabetical = [css]:#sortByOption div[data-value]:last-child
chartTypeTree = [css]:div[data-value='Tree Map'] a
barGraph = [xpath]://*[@id="qwebhistorySiteVisits0"]//div[1]//div[contains(@class,'panel__title')]
discardButton = [id]:discard-button
treeMapGraph = [css]:#qwebhistory0
chartTypeButton = [css]:div[title='Bar']
chatTypeFilter = [css]:div[title='Bar']
blankArea = [xpath]://html
filtervalueYes = [css]:div.flx-filter-row:nth-child(3) div.row div.col-md-6.pr-10.pl-10.value-dropdown:nth-child(3) div[role='option']:nth-child(1)
datedimestionfilterbutton = [xpath]://div[@title='No']//following::button[@title='Open'][1]//*[name()='svg']
datedimensionfilter = [css]:div[title='No']
datedimensionYes = [css]:div[data-value='Yes']




#Company selection new UI
companyDropdown = [xpath]://*[@id='report-company-filter']//*[name()='svg']
selectCompanyInList = [xpath]://*[@id='report-company-filter']//div[contains(@class,'list')]//div
companySearchBox = [id]:search
companyNameList = [xpath]:*//div[@id='report-company-filter']//div[contains(@class,'options-list')]/div/a
deleteReportWindow = [xpath]://div[@id='templateListId']//div[contains(@class,'modal__content')]

createButton = [id]:createReportBtn
browseTab = [css]:div#reportsTab a#customTabList
reportName = [xpath]://*[@id='reportName']//*[@type='text'][@value]
categoryDropdown = [xpath]://*[@id='categoryOption']//div//div[1]
subcategoryDropdown = [xpath]://*[@id='subCategoryOption']//div//div[1]
optionDropdown = [xpath]://*[@id='subCategoryOptionDropdown']//div//div[1]
showReplacementDevice = [xpath]://label[contains(@for,'checkbox_name_recomondation')]//span[1]
recommendedDeviceGraph = [xpath]://div[@id ='recommandeddevices']
saveButton = [id]:add-button
customReportsCreatedList = [xpath]://*[@id='templateListId']/div[2][contains(@class,'list')]
category_value = [xpath]://*[@id='categoryOption']//div//div[1][contains(@class, 'title-text--two-buttons')]
subCategory_value = [xpath]://*[@id='subCategoryOption']//div//div[1][contains(@class, 'title-text--two-buttons')]
options_value = [xpath]://*[@id='subCategoryOptionDropdown']//div//div[1][contains(@class, 'title-text--two-buttons')]
categoryList = [xpath]://*[@id='categoryOption']//*[contains(@class, 'options-list')]//div//a
subCategoryList = [xpath]://*[@id='subCategoryOption']//*[contains(@class,'options-list')]//div//a
optionList = [xpath]://*[@id='subCategoryOptionDropdown']//*[contains(@class,'options-list')]//div//a
categorySelectHardware = [xpath]://ul[@class='vn-dropdown_options--scroll']/li/a
categorySelectSecurity = [xpath]://ul[@class='vn-dropdown_options--scroll']/li[2]/a
categorySelectSoftware = [xpath]://ul[@class='vn-dropdown_options--scroll']/li[3]/a
categorySelectUser = [xpath]://ul[@class='vn-dropdown_options--scroll']/li[4]/a
subcategorySelect = [xpath]://div[@id='reportTypeOptionBlock']//a
optionSelect = [xpath]://div[@id='subReportOptionBlock']//a
deleteFilter = //div[@class='flx-filter-row']//*[name()='g'][@id='delete']/ancestor::button//*[name()='svg']
filtercriteria = [xpath]://*[contains(@class,"filter-row")]//div[contains(@class,"flx-filter-row")]
mandateFilter = [xpath]://*[contains(@id,"field")]//div[contains(@class,'select__title--disabled')]
selectOption = [xpath]://*[contains(@id,"filterValue")]//*[@title='Select an option']
selectOptionDisabled = [xpath]://*[contains(@id,"filterValue")]//button//*[contains(@class,'disabled')]
selectFilterValueButton = [xpath]://*[contains(@id,"filterValue")]//button[@title='Open']//*[name()='svg']
selectOptionList =  [xpath]://*[contains(@id,"filterValue")]/div[2]/div[2]/div
selectOptionValue = [xpath]://*[contains(@id,"filterValue")]/div[2]/div[2]/div[1]/a
runReport = [id]:reportPreview
reportOption = [xpath]://div[@id='templateListId']//div[@class='vn-list-item__last-block']
deleteButton = [xpath]://*[@id='templateListId']//*[contains(@class, 'options-list')]/div[3]/a
okButtonInPopup = [xpath]://*[@id='templateListId']//*[contains(@class, 'button-group--responsive')]/button[1]
runReportHTMLPage = [xpath]://div[@class = 'reports-content']
runReportCategory = [xpath]://div[@class = 'col-md-6']/div[2]/div[2][@class = 'col-md-10']
runReportCompany = [xpath]://div[@class = 'col-md-6']/div[1]/div[2][@class = 'col-md-10']
runReportsubCategory = [xpath]://div[@class = 'col-md-6']/div[3]/div[2][@class = 'col-md-10']
runReportOption = [xpath]://div[@class = 'col-md-6']/div[4]/div[2][@class = 'col-md-10']
runReportCreatedBy = [xpath]://div[@class = 'col-md-6']/div[5]/div[2][@class = 'col-md-10']
reportPageAllReportsList = [xpath]://*[@id='templateListId']/div[2][contains(@class,'list')]
subcategoryEnabledDropdown = [xpath]://div[@id="reportTypeOptionBlock"]/div/div[not(contains(@class,'disabled'))]
subcategoryDisabledLink = [xpath]://div[@id="reportTypeOptionBlock"]//div/a[(contains(@class,'disabled'))]
filterSection = [xpath]://div[contains(@class,'filter-criteria ')]
filterTypeLabel = [css]:div[class*='fileType-options-label']>div:nth-child(1)>label
showHideButton = [id]:secondary-id
showHideClose = [xpath]://button[contains(@title,'Close')]//*[name()='svg']
showHideSaveButton = [xpath]://button[@id='primary-id']
showHideColumnList = [xpath]://div[contains(@class,'show-hide')]//ul/li//*[name()='span'][2]
showHideCheckboxList = [css]:li.vn-multiselect__component--li label>input
maintainenceGridTitle0 = [xpath]://div[@id='reportGrid0']//div[@class='panel_content']
maintainenceGridTitle1 = [xpath]://div[@id='reportGrid1']//div[@class='panel_content']
maintainenceGridTitle2 = [xpath]://div[@id='reportGrid2']//div[@class='panel_content']

#report HTML
#repprtTabslist = [xpath]://div[@class='reports-content-data-section']//div//nav//a
repprtTabslist = [css]:.reports-content-data-sectionGeneralScroll a[role='tab']
reportHTMLReportContainerGraph = [id]:reportHtmlViewIframe0
reportHTMLReportContainerGrid = [id]:reportHtmlViewIframe1
chartsNoData = [xpath]://*[name()='g'][@class='highcharts-label highcharts-no-data']//*[name()='text']//*[name()='tspan']
chartsData = [xpath]://*[name()='rect'][@class='highcharts-background']
chartsDataHrdwareHealthNewResHlth = [xpath]://div[@class='col-md-3 whiteBG'][@id='hwHealthresNew01']
chartsNoDataBromium = [xpath]://div[@class='highcharts-label highcharts-no-data']/span/div
gridNoData = [xpath]://td[contains(@class,'no-items--scrollable')]
gridNoDataBromium = [xpath]://td[contains(@class,'no-items')]
gridElementsList = [xpath]://div[@class='reportContainer']//ul[@class='grid']//li
gridElementsListBromium = [xpath]://table[@class = 'report-table']/tbody/tr
gridTitleList = [xpath]://div[@id='Details']//ul[@class='grid']//li[1]/div
gridTitleListBromium = [xpath]://table[@class = 'report-table']/tbody/tr[1]/th
reportsList= [id]:templateListId
deleteReportButton = [xpath]://div[@id='templateListId']//div[@class='vn-list-item__last-block']//li[3]//a
okButtonPopup = [xpath]://div[contains(@class,'modal__footer')]//button[1]
reportMoreDetails = [xpath]://span[@class='showreportdetails']
reportDescription = [xpath]://div[@class='col-md-12']//div[@class='report-info-label-desc']
hardwareHealthSummaryTabDesc = [xpath]://div[@id='replsummtxt0']
spinner = [xpath]://div[contains(@class,'spinner--loading')]//*[name()='svg']
selectCompany = [id]:select-company
companySelectionBar = [xpath]://ul[@name = 'radio-buttons-name']
seemore = [id]:see-all-company
companysearchboxreports = [id]:asset-search
companySelectRadioButtonSeemore = [xpath]://div[@id = 'filter-items-container']//span[contains(@class, 'filter-box__item-label-text')]
applyButton = [id]:update-selection
companylist = [xpath]://ul[@name =  'radio-buttons-name' ]//span[contains(@class , 'item-label-text')]

#Workflow chart redirection to details page
reportNameWf = [xpath]://div[@id='reportHtmlView']//h4
labelListLeftWf = [xpath]://div[@id='reportHtmlView']//div[@class='col-md-6']//div[@class='col-md-3 report-info-label']
valueListLeftWf = [xpath]://div[@id='reportHtmlView']//div[@class='col-md-6']//div[@class='col-md-9 report-info-label-desc']
labelListRightWf = [xpath]://div[@id='reportHtmlView']//div[@class='report-info-label-desc']//div[@class='col-md-4']
valueListRightWf = [xpath]://div[@id='reportHtmlView']//div[@class='report-info-label-desc']//div[@class='col-md-8 filter-criteria-value wordwrap']
filterCriteriaLabel = [xpath]://div[@id='reportHtmlView']//div[@class='col-md-6']//div[@class='report-info-label']
columnHeaderList = [xpath]://div[@id='reportGrid0']//tr[@class='vn-tableheader__row']/th
pdfFormatRadioButton = [xpath]:(//label[contains(@class,'radio-button-box')])[2]
xlsxFormatRadioButton = [xpath]:(//label[contains(@class,'radio-button-box')])[3]
schedulePeriodicReports = [xpath]://label[@for='chk_scheduleReports']
recurrenceDropDownBox = [id]:reportRecurrenceOption
recurrenceDropDownList = [xpath]://div[@id='reportRecurrenceOption']//div[@role='option']
reportPasswordCheckbox = [xpath]://label[@for='chk_password_required_for_file']
reportPassword = [id]:filePassword
allowEmailNotification = [xpath]://label[@for='chk_email_notification']
reportNameOnCustomTab = [xpath]:(//h6[@class='report-title'])[1]
categoryOnCustomTab = [xpath]:(//div[@class='custom-oval']/span)[1]
subCategoryOnCustomTab = [xpath]:(//div[@class='custom-oval']/span)[2]
optionsOnCustomTab = [xpath]:(//div[@class='custom-oval']/span)[3]
reportFormatOnCustomTab = [xpath]:(//div[@class='custom-oval'])[4]
recurrenceOnCustomTab = [xpath]:(//div[@class='custom-oval']/span)[5]
lastAccessOn = [xpath]:(//div[contains(@class,'last-access-on')])[1]
dayDropDown = [id]:recurranceDayOption
timeDropDown = [id]:recurrenceTime
runReportLinkOnCustomTab = [xpath]:(//button[contains(@id,'run_report')])[1]
datePicker = [xpath]://div[contains(@class,'datepicker')]//input
historyTab = [xpath]://a[contains(@class,'tabs__tab')][3]
reportNameHistoryTab = [xpath]:(//td[contains(@headers,'name')])[1]
categoryHistoryTab = [xpath]:(//td[contains(@headers,'category')])[1]
subCategoryHistoryTab = [xpath]:(//td[contains(@headers,'subCategory')])[1]
optionsHistoryTab = [xpath]:(//td[contains(@headers,'label')])[1]
reportFormatHistoryTab = [xpath]:(//td[contains(@headers,'format')])[1]
reportTypeHistoryTab = [xpath]:(//td[contains(@headers,'defaultTemplate')])[1]
dateHistoryTab = [xpath]:(//td[contains(@headers,'date')])[1]
deleteFilterWorkflow = [xpath]://div[contains(@id,'closeFilterCriteria')]
paginationDropdown = [xpath]:(//div[contains(@class,'pagination__information')]//a)[1]
paginationDropdownOptions = [xpath]://div[contains(@class,'pagination__information')]//div[contains(@class,'popover__content')]//a[(contains(@class,'disabled'))=0]
reportNameListStandardTab = [xpath]://h6[@class='report-title']//a
reportElementForHovering = [xpath]:(//div[contains(@class,'report-description')])[1]
addFilterCriteria = [id]:addCriteria
filterFieldForCompanyPreference = [xpath]:(//div[contains(@id,'filterName')])[2]
filterFieldOptionList = [xpath]://div[contains(@id,'filterName')]//div[@role='option']
filterFieldForCompanyPreferenceValue = [xpath]:(//div[contains(@id,'filterValue')])[2]
filterFieldValueOptionList = [xpath]://div[contains(@id,'filterValue')]//div[@role='option']
categoryOnReportDetails = [xpath]:(//div[contains(@class,'report-info-label-desc')])[3]
subcategoryOnReportDetails = [xpath]:(//div[contains(@class,'report-info-label-desc')])[4]
optionOnReportDetails = [xpath]:(//div[contains(@class,'report-info-label-desc')])[5]
createdByOnReportDetails = [xpath]:(//div[contains(@class,'report-info-label-desc')])[6]
companyReferenceKeyReportDetails = [xpath]:(//div[contains(@class,'filter-criteria-value')])[2]
reportTabWorkflow = [css]:#menu_reports a

#pdf and xlsx report
optionDropdownClick = [xpath]://div[@id='subCategoryOptionDropdown']//*[@class='vn-icon vn-icon--display-inline-block vn-icon--size-24']
PDF = [xpath]://*[@for='radFileTypePdf']//span
XLSX = [xpath]://*[@for='radFileTypeXlsx']//span
pdfandxlsx = [xpath]://*[@class="vn-radio-buttons"]//div
closeSubCatDropDown = [css]:div#subCategoryOption>div[class*='title--open'] button[title='Open']
reportPreviewButton = [id]:runReportPreview
subCategoryList = [xpath]://*[@id="subCategoryOption"]/div[2]//div
subCategoryOptionCrossButton= [css]:#subCategoryOptionDropdown button:nth-child(1)
spinnerForPDFDownload = [xpath]://div[@class='dui-page-spinner']//*[local-name()='svg']
subcategoryDropdownWorkflow=[xpath]://div[@id='subCategoryOption']//div[@role='button']
subcategoryDropdownListWorkflow=[xpath]://div[@id='subCategoryOption']//div[@role='option']

repprtTabslistWorkflow=[xpath]://div[@role='tablist']//a[@role='tab']

#RPOS - Add Criteria Filter
criteriaFieldDropdown = [xpath]:(//div[contains(@id,'filterName')])[1]
criteriaValueDropdown = [xpath]:(//div[contains(@id,'filterValue')])[1]
deleteCriteriaFilter= [xpath]://div[@class = 'close-filter-criteria']//*[name()='svg']

#RPOS - New Tab -"Key Change Activity"
keyChangeActivityTab = [xpath]://div[@class='reports-content-data-sectionGeneralScroll']//a[text()='Key Change Activity']

#Location changes
globalLocationFilterDropdownReports = [xpath]://*[@id='gf-open-button']
globalLocationFilterClearIconReports = [xpath]://*[@id='gf-clear-button']

globalLocationFilter = [xpath]://*[@id='app-location-filter']//p
filterMenuCompaniesSearch = [xpath]://*[@id='company']/div[2]/div[1]/div/input

selectCompanyOnSearch = [xpath]://*[@id='company']//li[1]//span//label//span
filterMenuCompaniesHeader = [xpath]://*[@id='company']/div[1]/div[1]

locatFilterCompanyName = [xpath]://div[@id='app-location-filter']/div/div[2]/span[1]
applyCompanyLocationFilter = [xpath]://*[@id='apply-global-filter']
clearGlobalFilter = [xpath]://*[@id='clear-global-filter']

#Multi-Level Location Hierarchy

FilterMenuLocationLevel1Header = [xpath]://*[@id="location1"]/div[1]/div[1]
filterLocation1Search = [xpath]://*[@id='location1']/div[2]/div[1]/div/input
location1OnListSearch = [xpath]://*[@id="location1"]//span[2]
clearLocation = [xpath]://div[@id='location1']//div[text()='Clear']

FilterMenuLocationLevel2Header = [xpath]://*[@id="location2"]/div[1]/div[1]
filterLocation2Search = [xpath]://*[@id='location2']/div[2]/div[1]/div/input
location2OnListSearch = [xpath]://*[@id="location2"]//span[2]

FilterMenuLocationLevel3Header = [xpath]://*[@id="location3"]/div[1]/div[1]
filterLocation3Search = [xpath]://*[@id='location3']/div[2]/div[1]/div/input
location3OnListSearch = [xpath]://*[@id="location3"]//span[2]

FilterMenuLocationLevel4Header = [xpath]://*[@id="location4"]/div[1]/div[1]
filterLocation4Search = [xpath]://*[@id='location4']/div[2]/div[1]/div/input
location4OnListSearch = [xpath]://*[@id="location4"]//span[2]


SelectOptionList1 = [xpath]://*[contains(@id,"filterValue")]//div[2]//div//div

#graph drill down
deploymentGraphElementHover = [xpath]://*[@id='deploymentAnalyticsStatus0']//*[name()='g'][@class='highcharts-legend']//*[name()='text']//*[name()='tspan'][1]
deploymentGraphElementClick = [xpath]://*[name()='g'][contains(@class,'highcharts-series')]//*[name()='path'][contains(@class,'point-hover')]
hwGraphElementHover = [xpath]://*[@id='hwInvSumm0']//*[name()='g'][@class='highcharts-series-group']//*[name()='rect'][1]
reportTab = [css]:#menu_reports
drillDownTabname = [xpath]://div[@role='tablist']//a[@role='tab'][2]
detailsTable = [xpath]://*[@id="Details"]//div[1]/table/tbody/tr

#Self Service
selfServiceTab = [id]:menu_selfReporting
selfRTableList = [xpath]://div[@class = 'ssr-table-list-container']/ul/li/div/div[2]
selfEmail = [xpath]://input[@id='email']
selfCyberSec = [xpath]://div[@class ='ssr-footer']//span[1]
selfStartDate = [xpath]://input[@id='date_picker-start-input']
selfEndtDate = [xpath]://input[@id='date_picker-end-input']
selfDateList = [xpath]://*[contains(@class,'CalendarDay')][@aria-disabled ='false']
selfBrowse = [xpath]://div[@role ='none']/div/div/div/div[@role ='button']
selfSubmit = [xpath]://span[contains(text(),'Submit')]
selfDone = [xpath]://button[@type ='button'] /span[contains(text(),'Done')]
