RoomsDetailsPage.properties
#Room details locator

RoomDetailsTitle = [xpath]://span[@aria-current="page"]
RoomName = [xpath]://span[@class="dui-dsummary-card-title-view dui-dsummary-card-title"]
RoomAssistantTab = [xpath]://span[contains(text(),'Room Assistant')]
SettingsTab = [xpath]://div[@id='getSettingsDetails']
IncidentsTab = [xpath]://div[@id='getIncidentDetails']
MeetingsTab = [xpath]://span[contains(text(),'Meetings')]
HardwareTab = [xpath]://span[contains(text(),'Hardware')]
OverviewTab = [xpath]://span[contains(text(),'Overview')]
roomsTab =[css]:#menu_rooms a
roomsTitleOnBreadcrumbs = [css]:#roomsList li
RoomsTitle = [css]:#roomsList h4
addRoomButton=[xpath]://*[@id='btn_user_add']
roomNameSearch=[xpath]://input[@id='name']
roomNameLink=[xpath]://*[@title='Rajesh Room']
linkDeviceBtn=[xpath]://*[@label='Link Device']
deviceSearch=[xpath]://input[@id='deviceName']
selectDevice=[xpath]://tr[1]/td/span/span/span/input
linkButton=[xpath]://button[@id='cancel']/span
deviceName=[xpath]://div[text()='Compute Device']//following::div[1]
deviceNameOnSummary=[xpath]://div[text()='Compute Device']//following::div[1]
navigationItemDiv = [xpath]://*[@aria-label="Pagination Navigation"]
RoomDetailsComputeDevice=[xpath]://div[contains(text(),'Compute Device')]
RoomDetailsSize=[xpath]://div[contains(text(),'Size')]
RoomDetailsCapacity=[xpath]://div[contains(text(),'Capacity')]
RoomDetailsCompany=[xpath]://div[@class='dui-dsummary-card-desc-content-title' and contains(text(),'Company')]
RoomDetailsLocation=[xpath]://div[@class='dui-dsummary-card-desc-content-title' and contains(text(),'Location')]
RoomDetailsBuilding=[xpath]://div[@class='dui-dsummary-card-desc-content-title' and contains(text(),'Building')]
RoomDetailsFloor=[xpath]://div[@class='dui-dsummary-card-desc-content-title' and contains(text(),'Floor')]
RoomDetailsSizeValue=[xpath]://div[@class='dui-dsummary-card-desc-content-title' and contains(text(),'Size')]/following-sibling::div
RoomDetailsCapacityValue=[xpath]://div[@class='dui-dsummary-card-desc-content-title' and contains(text(),'Capacity')]/following-sibling::div
RoomDetailsCompanyValue=[xpath]://div[@class='dui-dsummary-card-desc-content-title' and contains(text(),'Company')]/following-sibling::div
RoomDetailsLocationValue=[xpath]://div[@class='dui-dsummary-card-desc-content-title' and contains(text(),'Location')]/following-sibling::div
RoomDetailsComputeDeviceValue=[xpath]://div[contains(text(),'Compute Device')]/following-sibling::div
RoomDetailsHealthStatus=[xpath]://div[contains(text(),'Health Status')]
RoomDetailsHealthStatusValue=[xpath]://div[@class='dui-icon-label']
RoomSubTypesNotAvailable=[xpath]://p[contains(text(),'No data available.')]
RoomDetailsSummaryPanelColumns=[xpath]://div[@class='dui-dsummary-card-desc-content-view']/div
RoomDetailsSummaryPanelHeader=[xpath]://div[@aria-controls='dui-dsummary-card' and @aria-expanded='true']
RoomDetailsHardwareTab=[xpath]://div[@aria-controls='extended-getHardwareDetails']
RoomDetailsHardwareTabHeader=[xpath]://div[@class='dui-dpanel-header']
RoomDetailsHardwareTabDeviceColumn=[xpath]://div[@class='css-1qgenj']//div//table//thead//tr[1]//th[1]
RoomDetailsHardwareTabTypeColumn=[xpath]://div[@class='css-1qgenj']//div//table//thead//tr[1]//th[2]
RoomDetailsHardwareTabActionColumn=[xpath]://div[@class='css-1qgenj']//div//table//thead//tr[1]//th[3]
RoomDetailsHardwareTabConfPCDeviceValue=[xpath]://div[@class='css-1qgenj']//div//table//tbody//tr[1]//td[1]
RoomDetailsHardwareTabConfPCTypeValue=[xpath]://div[@class='css-1qgenj']//div//table//tbody//tr[1]//td[2]
RoomDetailsHardwareTabConfPCActionValue=[xpath]://div[@class='css-1qgenj']//div//table//tbody//tr[1]//td[3]
RoomDetailsHardwareTabActionValueIcon=[xpath]://*[name ()='svg' and @aria-label='Reload']
RoomDetailsHardwareTabPresenceControlDeviceValue=[xpath]://div[@class='css-1qgenj']//div//table//tbody//tr[2]//td[1]
RoomDetailsHardwareTabPresenceControlTypeValue=[xpath]://div[@class='css-1qgenj']//div//table//tbody//tr[2]//td[2]
RoomDetailsHardwareTabPresenceControlActionValue=[xpath]://div[@class='css-1qgenj']//div//table//tbody//tr[2]//td[3]
RebootScreenHeader=[xpath]://div[@aria-modal='true']//h4//h5
RebootScreenText1=[xpath]://div[@aria-hidden='false']//div//div//div//div//div//b
RebootScreenText2=[xpath]://div[@aria-hidden='false']//div//div//div//div//div//p[1]
RebootScreenText3=[xpath]://div[@aria-hidden='false']//div//div//div//div//div//p[2]
RebootScreenRebootButton=[xpath]://div[@class='col-md-3 text-left']
RebootScreenCancelButton=[xpath]://div[@class="col-md-6"]//div
RebootToasterMessage=[xpath]://div[@role='alert']
Status=[xpath]://div[@class='dui-dsummary-card-desc-content-title' and text()='Status']
StatusValue=[xpath]://div[@class='dui-icon-label' and text()='Successful']
Identifier=[xpath]://div[@class='dui-dsummary-card-desc-content-title' and text()='Identifier']
IdentifierValueConfPC=[xpath]://div[@class='dui-dsummary-card-desc-content-value' and text()='Restart Device']
IdentifierValueCORC=[xpath]://div[@class='dui-dsummary-card-desc-content-value' and text()='Reboot CoRC Device']
TaskDetailsSummaryPanelHeader=[xpath]://div[@aria-controls='dui-dsummary-card' and @aria-expanded='true']
TaskStatus=[xpath]://th[@id='taskStatus']
ConnectionStatus=[xpath]://th[@id='connectionStatus']
TaskStatusValue=[xpath]://tbody//td[3]
ConnectionStatusValue=[xpath]://tbody//td[4]
DeviceName=[xpath]://th[@id='name']
DeviceNameValue=[xpath]://tbody//td[2]
StatusValueUnknown=[xpath]://div[@class='dui-icon-label' and text()='Unknown']
IdentifierValueBios=[xpath]://div[@class='dui-dsummary-card-desc-content-value' and text()='Deploy bios update HP BIOS and System Firmware (S21) 02.14.00']

AutoRoomNameLink=[xpath]://tr/td[2]/a
RoomNameTitle = [xpath]://span[@class="dui-dsummary-card-title-view dui-dsummary-card-title"]
linkSubmitButton=[xpath]://button[@id='submit']/span
linkCancelButton=[xpath]://button[@id='cancel']/span
RoomName_header=[xpath]://div[@class='dui-depr-label' and contains(text(),'Room Name')]
RoomNameOnSettingsTab=[xpath]://div[@class='dui-depr-label' and contains(text(),'Room Name')]/following-sibling::div/div/div/span
RoomNamesettingsPageCollapseIcon=[xpath]://div[@aria-controls='dui-dsummary-card']
UpdateRoomNameBtn=[xpath]:(//*[name()='svg'][@name='IconPencil'])[1]
RoomNameTextBox = [xpath]://label[@id='roomName-label' and contains(text(),'Name')]/following-sibling::div/input
SaveBtn_RoomName=[xpath]://*[@id='btn_save']

GotoIncidentList=[xpath]://a[@title='Jump to Incidents']
IncidentSubtypeSearch=[xpath]://div[@id="subtype"]

BellIcon=[xpath]://span[@class='dui-margin-right-10 notification-center-content-appbar']
Notification_header=[xpath]://span[@class='subtitle-regular']
RoomNameMismatchNotification=[xpath]://*[@actionType='Room Name Mismatch'][1]/div[2]/span/span
RoomNameMismatchFixedNotification=[xpath]://*[@actionType='Room Name Mismatch Fixed'][1]/div[2]/span/span

IncidentType=[xpath]:(//td[contains(text(),'Room Assistant')])[1]
IncidentSubTypeName=[xpath]:(//td[contains(text(),'Room Name Mismatch')])[1]