RoomsListPage.properties
#Rooms List
roomsTab =[css]:#menu_rooms a
roomsTitleOnBreadcrumbs = [css]:#roomsList li
RoomsTitle = [css]:#roomsList h4
roomNameSearchBox = [xpath]://*[@placeholder="Search" and @name="name"] 
noItemsAvailable = [xpath]://span[text()='No items available']
AutoRoomNameLink= [xpath]://tr/td[2]/a
floorSearchBox = [xpath]://*[@placeholder="Search" and @name="floor"] 
floorSearchList = [xpath]://tr/td[5]
locationSearchBox = [xpath]://*[@placeholder="Search" and @name="location"] 
locationSearchList = [xpath]://tr/td[6]
selectAllCheckBoxRoomList = [css]:th span[class*=table__checkbox] input
deviceSettings = [xpath]://div[@id='dui-es-list-more-button']//div//ul//li[2]
configureRoomAssistantBtn = [xpath]://button[@id='btn_user_delete']
configureRoomAssistant = [xpath]://div[@id='dui-es-list-more-button']//div//ul//li[1]
deleteButton = [xpath]://div[@id='dui-es-list-more-button']//div//ul//li[3]
roomList = [xpath]://tr/td[2]/a
roomPageCount = [xpath]://button[@aria-label='Select page size']
roomsSelectAllCount = [xpath]://span[contains(@role,'region') and contains(@aria-live,'polite')]
roomListCheckBox = [xpath]://input[@aria-label="0"]
closeButton = [xpath]://div[@id="dui-table-sidebar"]/button/span
idKey= [css]:#roomsList li
sortingArrowKey= [xpath]://*[@aria-label='Chevron Down']
listkey= [xpath]://tr/td[2]/a
selectAllCheckBox = [xpath]:"//*[@name='SelectAllPage']";
navigationItemDiv = [xpath]://*[@aria-label="Pagination Navigation"]
navigationItemList = [xpath]://*[@aria-label="Pagination Navigation"]//li
navigationItemNext = [xpath]://*[@aria-label="Pagination Navigation"]//button[@aria-label="Next"]
navigationItemPrevious = [xpath]://*[@aria-label="Pagination Navigation"]//button[@aria-label="Previous"]
navigationItemFrist = [xpath]://*[@aria-label="Pagination Navigation"]//li[2]
navigationItemLast = [xpath]:(//*[@aria-label="Pagination Navigation"]//li)[last()-1]
navigationItemActivePage =  [xpath]://*[contains(@aria-label,'Current Page')]
addRoomButton = [xpath]://button[@id='btn_user_add']
addRoomScreenTitle = [xpath]://p[@class='room-setting-content-title']
roomNameTextBox = [xpath]://input[@name='roomName']
roomSizeSmall = [xpath]://input[@index='Small']
roomSizeHuddle = [xpath]://span[contains(text(),'Huddle')]
roomSizeMedium = [xpath]://span[contains(text(),'Medium')]
roomSizeLarge = [xpath]://span[contains(text(),'Large')]
nextButtonGeneralScreen = [xpath]://button[@id='next-caseone']
floorTextBox = [xpath]://input[@name='floor' and @type='text']
buildingTextBox = [xpath]://input[@name='building']
locationTextBox = [xpath]://input[@name='site_city']
nextButtonLocationScreen =  [xpath]://button[@id='next-default']
deviceCheckBox = [xpath]://td[@class='css-42tqms']
summaryAddButton = [xpath]://button[@id='add']
addRoomConfirmation =[xpath]://span[contains(text(),'Room created successfully')]
addRoomCancelButton = [xpath]://button[@id='close-caseone']
addRoomBackButton = [xpath]://button[@id='save']
addRoomBackButtonSummaryScreen = [xpath]://button[@id='back']
summaryGENERAL = [xpath]://p[contains(text(),'GENERAL')]
summaryLOCATION = [xpath]://p[contains(text(),'LOCATION')]
summaryDEVICEDETAILS =[xpath]://p[contains(text(),'DEVICE DETAILS')]
roomName = [xpath]://p[contains(text(),'Room Name')]
roomSize = [xpath]://p[contains(text(),'Size')]
summaryCompany =[xpath]://p[contains(text(),'Company')]
building = [xpath]://p[contains(text(),'Building')]
location = [xpath]://p[contains(text(),'Location')]
floor =[xpath]://p[contains(text(),'Floor')]
buttonDeviceName = [xpath]://button[contains(text(),'Device Name')]
buttonSerialNumber = [xpath]://button[contains(text(),'Serial Number')]
buttonRoomName = [xpath]://button[contains(text(),'Room Name')]
buttonAssignmentStatus = [xpath]://button[contains(text(),'Assignment Status')]
buttonDeviceHealth = [xpath]://button[contains(text(),'Device Health')]
buttonUCPlatform = [xpath]://button[contains(text(),'UC Platform')]
buttonPeripherals = [xpath]://button[contains(text(),'Peripherals')]
summaryDevice = [xpath]://p[contains(text(),'Device')]
summarySerialNumber = [xpath]://p[contains(text(),'Serial Number')]
summaryUCPlatform =[xpath]://p[contains(text(),'UC Platform')]
roomNameExistingError = [xpath]://span[contains(text(),'Resource already exists for requested Tenant id and roomName.')]
fieldRequiredError = [xpath]://span[contains(text(),'Field is required')]
moreButton = [xpath]://span[contains(text(),'More')]//following-sibling::span
tasksTab = [css]:#menu_tasks a
tasksTitleOnBreadcrumbs = [css]:#tasksList li
firstTask = [xpath]://tbody//tr[1]//td[1]
notification = [xpath]://span[@class='dui-margin-right-10 notification-center-content-appbar']
notification_header=[xpath]://span[@class='subtitle-regular']
notification_firstItem=[xpath]://*[@id="HP-ARGON-notification-section-contextMenu-today"] 
notification_secondItem=[xpath]://ul[@tabindex='0']//li[2]   
notification_tickmark=[xpath]://ul[@tabindex='0']//li[2]//*[name ()='svg' and @aria-label='Checkmark Circle']
notification_warningIcon=[xpath]://ul[@tabindex='0']//li[2]//*[name ()='svg' and @aria-label='Warning Alt']
firstTaskInitiatedAt=[xpath]://tbody//tr[1]//td[5]
roomNameSearchList=[xpath]://table[@id='roomList']//tbody//tr//td[2]