salesTeamTab = [css]:#menu_salesTeam a
salesTeamTitle = [css]:nav[class*=breadcrumbs] span
salesTeamTitleOnBreadcrumbs = [css]:nav[class*=breadcrumbs] span
partnerTeamTab = [css]:#menu_salesTeam a
partnerAddButton = [id]:add
partnerRolesDropdown = [xpath]://select[@name='user_role']
partnerUserRolesList = [xpath]://select[@name='user_role']/option
selectAllCheckbox = [xpath]://thead//tr[1]//th[1]//input
firstIdLogo = [css]:tbody tr:nth-child(1) div[class*='avatar'] span
firstIdCheckboxDisabled = [css]:tbody tr:first-child span[aria-disabled="false"]
firstIdCheckbox = [css]:tbody tr:nth-child(1) span[class*='checkbox'] input
firstIdEmail = [css]:#dui-container tbody tr:nth-child(1) td:nth-child(3)
toastNotification = [xpath]://div[@role="alert"]
allDetailsOfSalesTeamMember = [css]:tbody tr:nth-child(1) td
firstIdName = [css]:#dui-container a
txtMobilePhone = [xpath]: //th[@id='mobilePhone']
firstIdRole = [css]:tbody tr:nth-child(1) td:nth-child(4)
listOfColumnsOnTable = [css]:th[class*='cell-title']>div:nth-of-type(1)
listTable = [xpath]://*[@id="dui-container"]//table
tableOverlay=[css]:[class*=ProgressIndicator] svg
nameHeader = [css]:#dui-container tr:first-child #name button
clearfilter=[xpath]://*[@id="dui-container"]//thead//tr[2]//th//button
firstRow = [css]:tbody tr:nth-child(1) td[headers*=col]
officePhoneText = [xpath]: //th[@id='officePhone']

#table configuration
tableConfigurationButton = [css]:div.vn-tableconfiguration>button>svg
tableConfigurationTitle = [css]:div.vn-modal__header>h4

breadCrumbLink = [xpath]://ul[@id='dui-breadcrumbs']/li[1]
breadCrumbName = [xpath]://ul[@id='dui-breadcrumbs']/li[2]
detailsNamePanel = [xpath]://div[@id='namePanel']/div[contains(@class,'value text')]/span
detailsEmailPanel = [xpath]://div[@id='emailPanel']/div[contains(@class,'value text')]
nameEditButton = [id]:nameEditBtn
firstNameTextBox = [id]:edit_modal_firstName
lastNameTextBox = [id]:edit_modal_lastName
saveButton = [id]:editSaveBtn
mobileEditButton = [id]:mobileEditBtn
officeEditButton = [id]:officeEditBtn
titleEditButton = [id]:jobTitleEditBtn
addressEditButton = [id]:addressEditBtn
languageEditButton = [id]:languageEditBtn
mobileTextBox = [id]:edit_modal_mobilePhone
officeTextBox = [id]:edit_modal_officePhone
titleTextBox = [id]:edit_modal_jobTitle
address1Textbox = [id]:edit_modal_address1
address2Textbox = [id]:edit_modal_address2
stateTextbox = [id]:edit_modal_region
cityTextbox = [id]:edit_modal_city
zipcodeTextbox = [id]:edit_modal_postalCode
dropDownBox = [css]:div[class*=select__title]
dropDownList = [xpath]://div[contains(@class,'option')]/div

detailsMobilePanel = [xpath]://div[@id='mobilePanel']/div[contains(@class,'value text')]/span
detailsOfficePanel = [xpath]://div[@id='officePanel']/div[contains(@class,'value text')]
detailsTitlePanel = [xpath]://div[@id='jobTitlePanel']/div[contains(@class,'value text')]
detailsAddressPanel = [xpath]://div[@id='addressPanel']/div[contains(@class,'value text')]
detailsLanguagePanel = [xpath]://div[@id='languagePanel']/div[contains(@class,'value text')]
detailsCountry = [css]:#addressPanel span > div> div:nth-child(1)
detailsAddress1 = [css]:#addressPanel span div:nth-child(2)
detailsAddress2 = [css]:#addressPanel span div:nth-child(3)
detailsStateCityZipcode = [css]:#addressPanel span div:nth-child(5)
detailsPassword = [xpath]://div[@id='passwordPanel']/div[contains(@class,'value text')]

namePanel = [xpath]://div[@id='namePanel']/div[1]
emailPanel = [xpath]://div[@id='emailPanel']/div[1]
mobilePanel = [xpath]://div[@id='mobilePanel']/div[1]
officePanel = [xpath]://div[@id='officePanel']/div[1]
jobTitlePanel = [xpath]://div[@id='jobTitlePanel']/div[1]
addressPanel = [xpath]://div[@id='addressPanel']/div[1]
languagePanel = [xpath]://div[@id='languagePanel']/div[1]
passwordPanel = [xpath]://div[@id='passwordPanel']/div[1]

accountTypeText = [css]:p.dui-user-account-title
hpAccountText = [css]:p[class*=user-account-title]
accountStatus = [xpath]://div[contains(@class,'user-status-container')]
avtarName = [css]:div[class*=identity-name] p
avtarEmail = [css]:div[class*=primary-data] p:nth-child(1)
avtarPhone =[css]:div[class*=primary-data] p:nth-child(2)
avtarImage = [xpath]:(//div[contains(@class,'dui-pf')])[1]
fileBrowse = [xpath]://span[contains(@class,'filepicker__placeholder')]
avtarSaveButton = [xpath]://div[contains(@class,'button-group--horizontal')]/button[1]
avtarImageNoPhoto = [css]:div[class*='dui-pf-placeholder'] svg
avtarImagePhoto = [css]:div[class*='dui-pf-image-container']
fileImport = [css]:a[class*='filepicker__link'] input
photoRadio = [css]:label[for*='profile_photo_radio-file'] svg
roleAssignmentHeader = [css]:#roleAssignmentPanel div[class*=title]
roleAssignmentDescription = [css]:#roleAssignmentPanel div[class*=panel-warning]
rolesLabel = [xpath]://div[@id='rolesPanel']/div[1]
role = [xpath]://div[@id='rolesPanel']/div[2]
noPhoto = [xpath]://label[contains(@for,'profile_photo_radio-none')]//*[name() = 'svg']

#remove functionality
salesRemoveButton = [css]:div[class*=table-container]>div>div>div>div:nth-child(2)>button:nth-of-type(2)
removeTitle = [css]:#dui-remove-user h4
removeMessage = [css]:#dui-remove-device p
cancelRemove = [id]:modal-cancel
submitRemove = [id]:modal-submit
hamburgerIcon = [css]:#dui-container tr:first-child td:last-child button
removeAction = [xpath]:(//ul[@role="menu"]/li[@role='menuitem' and @data-contextual-menu='true'])[6]

#add functionality
salesAddButton = [css]:[class*=table] > button
firstNameAddMember = [css]:input[name=firstName]
lastNameAddMember = [css]:input[name=lastName]
emailAddMember = [css]:div[class*=modal] input[name=email]
mobileAddMember = [css]:div[class*=modal] input[name=phone]
addMember = [id]:add-member
cancelAddMember = [id]:cancel-add-member
salesAdminAddMember = [id]:roles0
salesSpecialistAddMember = [id]:roles1
notificationMessage = [css]:div[class*="toast__type--positive"] p
addMemberTitle = [xpath]:(.//div[@role='presentation'])[last()]//h2
typeAddMemberLabel = [css]:#add_member__type>label
emailAddMemberLabel = [xpath]://input[@name='email']//preceding::label[1]
mobileAddMemberLabel = [xpath]://input[@name='phone']//preceding::label[1]
firstNameAddMemberLabel = [xpath]://input[@name='firstName']//preceding::label[1]
lastNameAddMemberLabel = [xpath]://input[@name='lastName']//preceding::label[1]
salesAdminAddMemberLabel = [xpath]://div[@role='presentation'][4]//h2
salesSpecialistAddMemberLabel = [css]:label[for="roles1"] span
roleTitle = [css]:#select-role-label
roleDropDown = [xpath]:(.//div[@role='presentation'])[last()]//div[@aria-label="Open"]
selectedRoleName = [xpath]://*[@id="add_member__type"]//*[@role='button']

#filter functionality
emailTextbox = [css]:th #email
nameTextbox = [id]:name
rolesFilter = [xpath]://div[@id='roles']/ancestor::div[1]//span//div
statusFilter = [id]:users-status
mobilePhoneTextbox = [id]:mobilePhone
officePhoneTextbox = [id]:users-officePhone
nameList = [css]://*[@id='dui-container']//tr//td[2]//a
emailList = [css]:td[headers*=col-id-email]
roleList = [xpath]://*[@id='dui-container']//tr//td[4]
statusList = [css]:td[headers*=col-id-status]
mobilePhoneList = [xpath]://*[@id='dui-container']//tr//td[6]
dropdowncheckboxes = [css]:#roles-listbox li
dropdownelementlistlabels = [css]:#roles-listbox li
clearRoleFilter = [css]:#users-roles div[class*="button-group"] button:nth-child(1)
dropdownList = [css]:#logs-company-select  div[class*="options-list"]>div
clearStatusFilter = [css]:#users-status div[class*="button-group"] button:nth-child(1)
clearEmailField = [css]:#primaryAccountEmail+div svg
noItemsDisplayText = [xpath]://*[@id="dui-container"]//table/tbody/tr/td/div/span
clearFilter = [css]:button[title='Clear']
tableOverlay=[xpath]://*[contains(@class,'skeleton')]

#table configuration functionality
tableConfigurationButton = [css]:button[title='Table Configuration']

#pagination
showingText = [xpath]://span[@class='vn-pagination__information__showing']
paginationDropdownMenu = [xpath]://div[contains(@class,"TablePagination")]//div//div[1]//button
paginationDropdownOptionList = [xpath]://div[contains(@class,"TablePagination")]//div[1]//div[1]//ul//li
showingPaginationTotalCount = [xpath]://*[@class='vn-pagination__information']//a//span
paginationOptionList = [xpath]://div[contains(@class,'options-list')]//div
navigationItemDiv = [xpath]://div[contains(@class,"TablePagination")]//nav
navigationItemList = [xpath]://*[@class='vn-pagination__navigation']//li
navigationItemNext = [xpath]://div[contains(@class,"TablePagination")]//nav//button[@class="next"]
navigationItemPrevious = [xpath]://div[contains(@class,"TablePagination")]//nav//button[@class="previous"]navigationItemFirst = [xpath]:(//*[@class='vn-pagination__navigation']//li)[2]
navigationItemLast = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()-1]
navigationItemDisabled = [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'disabled')]
navigationItemActivePage =  [xpath]://div[contains(@class,"TablePagination")]//nav//ul//li[2]//button
clearSelectionOfFilters = [css]:th div>input:not([value=''])[placeholder=''],th div svg[class*='clear-icon']

userFirstIdEmail = [css]:#dui-container tbody tr:nth-child(1) td:nth-child(2) a
rolesDropdown = [css]:[class*=-padding-bottom]  > div > span
unselectRolesOption=[id]:select-role-option-0
roleSearchBox = [xpath]://*[@role="presentation"]/div/div/input
firstOptionRoleDropdown=[css]:#select-role-option-0 > div
emailSearchBox=[css]:[class*=-search-input_container] #email
toastSuccessNotification=[xpath]://*[@role="alert"]//div//span
selectRoleDropdown=[xpath]://*[@id="select-role"]
closeRoleDropdown=[xpath]://*[@data-popover-backdrop="true"]