formFieldErrorMessage = [css]:p[class*="form-field__error-message"]
toastNotification = [xpath]://*[contains(@class,'ToastNotification')]/div/span
detailsTileHeader = [xpath]:(//*[@class="dui-dpanel-header"])[1]
tableOverlay=[xpath]://div[@class='dui-page-spinner']//*[name()='svg']

#details tile
detailsTitle = [css]:#dui-tab-panel-0-0 div[class*="header"]
nameLabel = [css]:#namePanel div[class*="label"]
nameValue = [css]:#namePanel span
emailLabel = [css]:#emailPanel div[class*="label"]
emailValue = [css]:#emailPanel span
mobileLabel = [css]:#mobilePanel div[class*="label"]
mobileValue = [css]:#mobilePanel span
officeLabel = [css]:#officePanel div[class*="label"]
officeValue = [css]:#officePanel span
titleLabel = [css]:#jobTitlePanel div[class*="label"]
titleValue = [css]:#jobTitlePanel span
addressLabel = [css]:#addressPanel div[class*="label"]
addressValue = [css]:#addressPanel span
languageLabel = [css]:#languagePanel div[class*="label"]
languageValue = [css]:#languagePanel span

#role popup
rolePopupHeader = [xpath]:(//*[@id="rolesModal-label"])[2]
roleValueOnPopup = [css]:#rolesModal div[class*="text"]:nth-child(1)
roleDropdownOpen = [css]:#rolesModal div[class*="form-field"] div[class*="button"] button[aria-label=Open]
roleDropdownClear = [css]:#rolesModal div[class*="form-field"] div[class*="button"] button[aria-label=Clear]
roleDropdown = [css]:#rolesModal div[class*="form-field"] div[class*="button"] button[aria-label="Open"]
roleOptions  = [css]:#rolesModal div[class*="options-list"] div[class*="option"]
rolesSave  = [xpath]:(//*[@id="rolesSaveBtn"])[2]
rolesCancel  = [xpath]:(//*[@id="rolesCancelBtn"])[2]

#role assignment tile

roleHeader = [css]:#dui-accountAndRoles div[class*="header"]
roleMessage = [css]:#dui-accountAndRoles div[class*="warning"]
roleLabel = [css]:#dui-accountAndRolesDetails div[class*="header"]
roleValue = [xpath]://*[@id="dui-accountAndRoles"]//div[contains(@class,"epr-label")]
roleButton = [xpath]:(//*[@id="dui-accountAndRoles"]//*[contains(@class,"icon-button")])
accountHeader = [css]:#dui-accountAndRoles div[class*="header"]

#identity tile
identityName = [xpath]:(//*[@class="dui-summary-card-desc-row"]//div[2])[1]
identityEmail = [xpath]:(//*[@class="dui-summary-card-desc-row"]//div[2])[2]
identityPhone = [xpath]:(//*[@class="dui-summary-card-desc-row"]//div[2])[3]
identityStatus = [xpath]://*[@class="dui-icon-label"]

#communicationpreferences tile
communicationPreferencesTab = [css]:div[id=communicationPreferencesPanel]
communicationPreferencesHeader = [css]:#systemCommunicationPanel div[class*='title']
deviceHealthNotificationTitle = [css]:#deviceHealthTile div[class*='label']
deviceHealthNotificationValue = [css]:#deviceHealthTile div[class*='value'] span
deviceHealthNotificationToggle = [id]:dui-epr-icon-0
incidentsNotificationTitle = [css]:#incidentsNotificationTile div[class*='label']
incidentsNotificationEdit = [xpath]://*[@id="incidentsNotificationTile"]//*[contains(@class,"dui-icon-button")]
incidentsNotificationValue = [css]:#incidentsNotificationTile div[class*='value'] span
incidentNotificationPreferencesTitle = [css]:#incidentModal-label
incidentNotificationPreferencesSubTitle = [css]:#incidentModal-desc p[class*='primary-text']
accountTitle = [css]:#Accountpanel div[class*='panel__title']
hardwareChangeTitle = [css]:#HardwareChangepanel div[class*='panel__title']
hardwareHealthTitle = [css]:#HardwareHealthpanel div[class*='panel__title']
softwareHealthTitle = [css]:#SoftwareHealthpanel div[class*='panel__title']
unassignedTitle = [css]:#Unassignedpanel div[class*='panel__title']
accountList = [css]:#Accountpanel ul li span[class*=text]
hardwareChangeList = [css]:#HardwareChangepanel ul li span[class*=text]
hardwareHealthList = [css]:#HardwareHealthpanel ul li span[class*=text]
osHealthList = [css]:#OSHealthpanel ul li span[class*=text]
securityList = [css]:#Securitypanel ul li span[class*=text]
softwareHealthList = [css]:#SoftwareHealthpanel ul li span[class*=text]
unassignedList = [css]:#Unassignedpanel ul li span[class*=text]
accountListDropdownArrow = [css]:#Accountpanel div[class*=title] svg
hardwareChangeListDropdownArrow = [css]:#HardwareChangepanel div[class*=title] svg
hardwareHealthListDropdownArrow = [css]:#HardwareHealthpanel div[class*=title] svg
osHealthListDropdownArrow = [css]:#OSHealthpanel div[class*=title] svg
securityListDropdownArrow = [css]:#Securitypanel div[class*=title] svg
softwareHealthListDropdownArrow = [css]:#SoftwareHealthpanel div[class*=title] svg
unassignedListDropdownArrow = [css]:#Unassignedpanel div[class*=title] svg
accountAllLocator = [css]:#Accountpanel li:nth-child(1) span:nth-of-type(1)
hardwareChangeAllLocator = [css]:#HardwareChangepanel li:nth-child(1) span:nth-of-type(1)
hardwareHealthAllLocator = [css]:#HardwareHealthpanel li:nth-child(1) span:nth-of-type(1)
osHealthAllLocator = [css]:#OSHealthpanel li:nth-child(1) span:nth-of-type(1)
securityAllLocator = [css]:#Securitypanel li:nth-child(1) span:nth-of-type(1)
softwareHealthAllLocator = [css]:#SoftwareHealthpanel li:nth-child(1) span:nth-of-type(1)
unassignedAllLocator = [css]:#Unassignedpanel li:nth-child(1) span:nth-of-type(1)
accountLocator = [css]:#Accountpanel li:nth-of-type(2) span:nth-of-type(1)
hardwareChangeLocator = [css]:#HardwareChangepanel li:nth-child(2) span:nth-of-type(1)
hardwareHealthLocator = [css]:#HardwareHealthpanel li:nth-child(2) span:nth-of-type(1)
osHealthLocator = [css]:#OSHealthpanel li:nth-child(2) span:nth-of-type(1)
securityLocator = [css]:#Securitypanel li:nth-child(2) span:nth-of-type(1)
softwareHealthLocator = [css]:#SoftwareHealthpanel li:nth-child(2) span:nth-of-type(1)
unassignedLocator = [css]:#Unassignedpanel li:nth-child(2) span:nth-of-type(1)
doNotReceiveEmailNotificationLocator = [css]:#email_notification div[class*='radio-button']:nth-child(1) span
ReceiveEmailNotificationWhenNewIncidentIsReportedLocator = [css]:#email_notification div[class*='radio-button']:nth-child(2) span
ReceiveAnEmailNotificationWithAllIncidentsThatAreOpenedInaDayLocator = [css]:#email_notification div[class*='radio-button']:nth-child(3) span
ReceiveEmailNotificationWhenNewIncidentIsReportedAndOneEmailWithAllIncidentsThatAreOpenedInaDayLocator = [css]:#email_notification div[class*='radio-button']:nth-child(4) span
ReceiveEmailNotificationWhenNewIncidentIsReportedRadioButton = [css]:#email_notification label[for="email_notification_option_1"] svg
doNotReceiveEmailNotificationRadioButton = [css]:#email_notification label[for="email_notification_option_0"] svg
incidentPreferencesSaveButton = [id]:incidentSaveBtn
incidentPreferencesCancelButton = [id]:incidentCancelBtn
dailyEmailNotificationTitle = [css]:#receiveEmailTimeTile div[class*="label"]
dailyEmailNotificationValue = [css]:#receiveEmailTimeTile div[class*="value"] *
dailyEmailNotificationEditButton = [id]:receiveEmailTimeEditBtn
timezoneDropdown = [id]:select-timezone
timezoneDropdownList = [css]:#select-timezone div[class*="options-list"] div[class*="option"]
timezoneCodeDropdown = [id]:timezone-code
timezoneCodeDropdownList = [css]:#timezone-code div[class*="options-list"] div[class*="option"]
dailyEmailNotificationSaveButton = [id]:emailsSaveBtn
dailyEmailNotificationCancelButton = [id]:emailsCancelBtn
validationErrorMessageOnIncidentPreferences = [css]:#incidentModal div[class*="body"] p[class*="red"]
currentTimeZone= [css]:#receiveEmailTimeTile span

searchRole = [xpath]://*[contains(@class,"search-attached")]//input[@type="search"]
listOfRoles = [xpath]://*[contains(@class,"roles-list")]//span[1]

#ToastNotification
toastNotificationAccountTile = [xpath]:(//div[@role='alert']//span)[1] 