salesTeamTab = [id]:menu_salesTeam
salesTeamTitle = [css]:#teamList h4
salesTeamTitleOnBreadcrumbs = [css]:#teamList li
partnerTeamTab = [id]:menu_salesTeam
partnerAddButton = [id]:add
partnerRolesDropdown = [xpath]://select[@name='user_role']
partnerUserRolesList = [xpath]://select[@name='user_role']/option
selectAllCheckbox = [xpath]://*[@name="SelectAllPage"]
firstIdLogo = [css]:tbody tr:nth-child(1) div[class*='avatar']
firstIdCheckboxDisabled = [css]:tbody span[class*='disabled']
firstIdCheckbox = [css]:tbody tr:nth-child(1) div[class*='checkbox'] label input
firstIdEmail = [css]:tbody tr:nth-child(1) td:nth-child(3) div[class*="tablecell__content"]
toastNotification = [xpath]://*[contains(@class,'container--bottom')]/div/p
allDetailsOfSalesTeamMember = [css]:tbody tr:nth-child(1) td
firstIdName = [xpath]://tbody//tr[1]//td[3]//a
firstIdRole = [css]:tbody tr:nth-child(1) td:nth-child(5) div[class*="tablecell__content"]
listOfColumnsOnTable = [css]:th[class*='cell-title']>div:nth-of-type(1)
listTable = [css]:table[class*=table]
tableOverlay=[xpath]:div[class*='table__overlay--loading']
nameHeader = [css]:#col-id-name
clearfilter=[xpath]://button[@title='Clear']
firstRow = [css]:tbody tr:nth-child(1) td[headers*=col]

#table configuration
tableConfigurationButton = [css]:div.vn-tableconfiguration>button>svg
tableConfigurationTitle = [css]:div.vn-modal__header>h4

breadCrumbLink = [xpath]://ul[@id='dui-breadcrumbs']/li[1]
breadCrumbName = [xpath]://ul[@id='dui-breadcrumbs']/li[2]
detailsNamePanel = [xpath]://div[@id='namePanel']/div[contains(@class,'value text')]/span
detailsEmailPanel = [xpath]://div[@id='emailPanel']/div[contains(@class,'value text')]
nameEditButton = [id]:nameEditBtn
firstNameTextBox = [id]:edit_modal_firstName
lastNameTextBox = [id]:edit_modal_lastName
saveButton = [id]:editSaveBtn
mobileEditButton = [id]:mobileEditBtn
officeEditButton = [id]:officeEditBtn
titleEditButton = [id]:jobTitleEditBtn
addressEditButton = [id]:addressEditBtn
languageEditButton = [id]:languageEditBtn
mobileTextBox = [id]:edit_modal_mobilePhone
officeTextBox = [id]:edit_modal_officePhone
titleTextBox = [id]:edit_modal_jobTitle
address1Textbox = [id]:edit_modal_address1
address2Textbox = [id]:edit_modal_address2
stateTextbox = [id]:edit_modal_region
cityTextbox = [id]:edit_modal_city
zipcodeTextbox = [id]:edit_modal_postalCode
dropDownBox = [css]:div[class*=select__title]
dropDownList = [xpath]://div[contains(@class,'option')]/div

detailsMobilePanel = [xpath]://div[@id='mobilePanel']/div[contains(@class,'value text')]/span
detailsOfficePanel = [xpath]://div[@id='officePanel']/div[contains(@class,'value text')]
detailsTitlePanel = [xpath]://div[@id='jobTitlePanel']/div[contains(@class,'value text')]
detailsAddressPanel = [xpath]://div[@id='addressPanel']/div[contains(@class,'value text')]
detailsLanguagePanel = [xpath]://div[@id='languagePanel']/div[contains(@class,'value text')]
detailsCountry = [css]:#addressPanel span > div> div:nth-child(1)
detailsAddress1 = [css]:#addressPanel span div:nth-child(2)
detailsAddress2 = [css]:#addressPanel span div:nth-child(3)
detailsStateCityZipcode = [css]:#addressPanel span div:nth-child(5)
detailsPassword = [xpath]://div[@id='passwordPanel']/div[contains(@class,'value text')]

namePanel = [xpath]://div[@id='namePanel']/div[1]
emailPanel = [xpath]://div[@id='emailPanel']/div[1]
mobilePanel = [xpath]://div[@id='mobilePanel']/div[1]
officePanel = [xpath]://div[@id='officePanel']/div[1]
jobTitlePanel = [xpath]://div[@id='jobTitlePanel']/div[1]
addressPanel = [xpath]://div[@id='addressPanel']/div[1]
languagePanel = [xpath]://div[@id='languagePanel']/div[1]
passwordPanel = [xpath]://div[@id='passwordPanel']/div[1]

accountTypeText = [css]:p.dui-user-account-title
hpAccountText = [css]:p[class*=user-account-title]
accountStatus = [xpath]://div[contains(@class,'user-status-container')]
avtarName = [css]:div[class*=identity-name] p
avtarEmail = [css]:div[class*=primary-data] p:nth-child(1)
avtarPhone =[css]:div[class*=primary-data] p:nth-child(2)
avtarImage = [xpath]:(//div[contains(@class,'dui-pf')])[1]
fileBrowse = [xpath]://span[contains(@class,'filepicker__placeholder')]
avtarSaveButton = [xpath]://div[contains(@class,'button-group--horizontal')]/button[1]
avtarImageNoPhoto = [css]:div[class*='dui-pf-placeholder'] svg
avtarImagePhoto = [css]:div[class*='dui-pf-image-container']
fileImport = [css]:a[class*='filepicker__link'] input
photoRadio = [css]:label[for*='profile_photo_radio-file'] svg
roleAssignmentHeader = [css]:#roleAssignmentPanel div[class*=title]
roleAssignmentDescription = [css]:#roleAssignmentPanel div[class*=panel-warning]
rolesLabel = [xpath]://div[@id='rolesPanel']/div[1]
role = [xpath]://div[@id='rolesPanel']/div[2]
noPhoto = [xpath]://label[contains(@for,'profile_photo_radio-none')]//*[name() = 'svg']

#remove functionality
salesRemoveButton = [id]:btn_user_remove
removeTitle = [css]:#dui-remove-user h4[class*=text]
removeMessage = [css]:#dui-remove-device p
cancelRemove = [id]:modal-cancel
submitRemove = [id]:modal-submit
hamburgerIcon = [css]:button[class*="menu-button-dropdown-icon"]
removeAction = [xpath]:(//*[contains(@class ,'contextual-menu')] //div)[3]

#add functionality
salesAddButton = [id]:btn_user_add
firstNameAddMember = [id]:firstName
lastNameAddMember = [id]:lastName
emailAddMember = [id]:email
mobileAddMember = [id]:phone
addMember = [id]:add-member
cancelAddMember = [id]:cancel-add-member
salesAdminAddMember = [id]:roles0
salesSpecialistAddMember = [id]:roles1
notificationMessage = [css]:div[class*="toast__type--positive"] p
addMemberTitle = [css]:div[class*="modal__header"]
typeAddMemberLabel = [css]:#add_member__type>label
emailAddMemberLabel = [css]:div[class*="modal"] div[class*="form-field"]:nth-child(4) label
mobileAddMemberLabel = [css]:div[class*="modal"] div[class*="form-field"]:nth-child(5) label
firstNameAddMemberLabel = [css]:div[class*="modal"] div[class*="form-field"]:nth-child(2) label
lastNameAddMemberLabel = [css]:div[class*="modal"] div[class*="form-field"]:nth-child(3) label
salesAdminAddMemberLabel = [css]:label[for="roles0"] span
salesSpecialistAddMemberLabel = [css]:label[for="roles1"] span
roleTitle = [css]:#add_member__type>label
roleDropDown = [css]:#add_member__type button
selectedRoleName = [xpath]://*[@id="add_member__type"]//*[@role='button']

#filter functionality
emailTextbox = [id]:users-email
nameTextbox = [id]:users-name
rolesFilter = [id]:users-roles
statusFilter = [id]:users-status
mobilePhoneTextbox = [id]:users-mobilePhone
officePhoneTextbox = [id]:users-officePhone
nameList = [css]:td[headers*=col-id-name]
emailList = [css]:td[headers*=col-id-email]
roleList = [css]:td[headers*=col-id-roles]
statusList = [css]:td[headers*=col-id-status]
mobilePhoneList = [css]:td[headers*=col-id-mobilePhone]
officePhoneList = [css]:td[headers*=col-id-officePhone]
dropdowncheckboxes = [css]:#logs-company-select div[class*="option__multiple"]
dropdownelementlistlabels = [css]:#logs-company-select a
clearRoleFilter = [css]:#users-roles div[class*="button-group"] button:nth-child(1)
dropdownList = [css]:#logs-company-select  div[class*="options-list"]>div
clearStatusFilter = [css]:#users-status div[class*="button-group"] button:nth-child(1)
noItemsDisplayText = [css]:td[class*='no-items']
clearFilter = [css]:button[title='Clear']
tableOverlay=[xpath]:div[class*='table__overlay--loading']

#table configuration functionality
tableConfigurationButton = [css]:button[title='Table Configuration']

#pagination
showingText = [xpath]://span[@class='vn-pagination__information__showing']
paginationDropdownMenu = [xpath]://div[contains(@class,'pagination')]//a[@role='button']
paginationDropdownOptionList = [xpath]://div[contains(@class,'options-list')]//div[contains(@class,'option')]
showingPaginationTotalCount = [xpath]://*[@class='vn-pagination__information']//a//span
paginationOptionList = [xpath]://div[contains(@class,'options-list')]//div
navigationItemDiv = [xpath]://*[@class='vn-pagination__navigation']
navigationItemList = [xpath]://*[@class='vn-pagination__navigation']//li
navigationItemNext = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()]/*[contains(@class,'navigation-item')]
navigationItemPrevious = [xpath]:(//*[@class='vn-pagination__navigation']//li)[1]/*[contains(@class,'navigation-item')]
navigationItemFirst = [xpath]:(//*[@class='vn-pagination__navigation']//li)[2]
navigationItemLast = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()-1]
navigationItemDisabled = [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'disabled')]
navigationItemActivePage =  [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'page--active')]
clearSelectionOfFilters = [css]:th div>input:not([value=''])[placeholder=''],th div svg[class*='clear-icon']