snowLoginPage =[xpath]://iframe[@id='gsft_main']
snowUserName = [xpath]://input[@id='username']
snowPassword = [xpath]://input[@id='password']
snowSignInButton =[xpath]://button[@id='submitButton']
snowWakeUpPage = [xpath]://div[@data-radial-indicator='indicatorOption']
snowRequestButton =[xpath]://button[@id='instanceReqBtn']
snowManageTab= [xpath]://a[@id='dp-hdr-br-manage-link']
snowInstanceTab= [xpath]://a[@id='dp-hdr-br-link-instance']
snowWakeupButton=[xpath]://button[@ng-click='wakeUpInstance()']
snowSigninNext=[xpath]://button[@id='usernameSubmitButton']