base.url=https://api.statuspage.io
api.key=ATCTT3xFfGN0T7b35_dOJR0BbIAzb33_C-CEmDq73XeW-BI_Xh1ooHQAWWthP8fumIqjDMhIL6MT5Gr_zWXcYgzRkX2LbTe06dv-PETildV4HevAngIXA8VzDrnFiPj9r3ncseFNA4fGSG970J2xcR7QM_2ICxu1w00IjZP2CCcP042t0FWvZkg=B8EF0B81
page.id=czzz0q0jkv7v
component.id.hardware_support=rd4vnmz5mscy
failure.status.hardware_support=major_outage