formFieldErrorMessage = [css]:p[class*="form-field__error-message"]
toastNotification = [xpath]://div[@role="alert"]
tableOverlay=[css]:div[class*='dui-page-spinner'] svg 
detailsTileHeader = [xpath]:(//*[@class="dui-dpanel-header"])[1]
              
#details tile
detailsTitle = [css]:#dui-tab-panel-0-0 div[class*="header"]
nameLabel = [css]:#namePanel div[class*="label"]
nameValue = [css]:#namePanel span
emailLabel = [css]:#emailPanel div[class*="label"]
emailValue = [css]:#emailPanel span
mobileLabel = [css]:#mobilePanel div[class*="label"]
mobileValue = [css]:#mobilePanel span
officeLabel = [css]:#officePanel div[class*="label"]
officeValue = [css]:#officePanel span
titleLabel = [css]:#jobTitlePanel div[class*="label"]
titleValue = [css]:#jobTitlePanel span
addressLabel = [css]:#addressPanel div[class*="label"]
addressValue = [css]:#addressPanel span
languageLabel = [css]:#languagePanel div[class*="label"]
languageValue = [css]:#languagePanel span

#role popup
rolePopupHeader = [xpath]:(//*[@id="rolesModal-label"])[2]
roleValueOnPopup = [css]:#rolesModal div[class*="text"]:nth-child(1)
roleDropdown = [css]:#rolesModal div[class*="form-field"] div[class*="button"] button[aria-label="Open"]
roleOptions  = [css]:#rolesModal div[class*="options-list"] div[class*="option"]
rolesSave  = [xpath]:(//*[@id="rolesSaveBtn"])[2]
rolesCancel  = [xpath]:(//*[@id="rolesCancelBtn"])[2]

#role assignment tile
roleHeader = [xpath]:(//*[@id="dui-accountAndRoles"]//div[contains(@class,"header")])[1]
roleMessage = [xpath]://*[@id="dui-accountAndRoles"]//div[contains(@class,"warning")]
roleLabel = [xpath]://*[@id="dui-accountAndRolesDetails"]//div[contains(@class,"header")]
roleValue = [xpath]://*[@id="dui-accountAndRoles"]//div[contains(@class,"epr-label")]
roleButton = [xpath]:(//*[@id="dui-accountAndRoles"]//*[contains(@class,"icon-button")])

#identity tile
identityName = [xpath]:(//*[@class="dui-summary-card-desc-row"]//div[2])[1]
identityEmail = [xpath]:(//*[@class="dui-summary-card-desc-row"]//div[2])[2]
identityPhone = [xpath]:(//*[@class="dui-summary-card-desc-row"]//div[2])[3]
identityStatus = [xpath]://*[@class="dui-icon-label"]
avatar = [css]:#usersProfilePanel img

#communicationpreferences tile
communicationPreferencesTab = [css]:div[id=communicationPreferencesPanel]
communicationPreferencesHeader = [css]:#systemCommunicationPanel div[class*='header']
deviceHealthNotificationTitle = [css]:#deviceHealthTile div[class*='label']
deviceHealthNotificationValue = [css]:#deviceHealthTile div[class*='value'] span
deviceHealthNotificationToggle = [id]:dui-epr-icon-0
incidentsNotificationTitle = [css]:#incidentsNotificationTile div[class*='label']
incidentsNotificationEdit = [xpath]://*[@id="incidentsNotificationTile"]//div[contains(@class,"dui-icon-button")]
incidentsNotificationValue = [css]:#incidentsNotificationTile div[class*='value'] span
incidentNotificationPreferencesTitle = [css]:#incidentModal-label
incidentNotificationPreferencesSubTitle = [css]:#incidentModal-desc p[class*='primary-text']
accountTitle = [xpath]://div[@aria-controls="dui_accordian_account"]//*[contains(@class,"label")]
genericTitle = [css]:#Genericpanel div[class*='panel__title']
hardwareChangeTitle = [css]:#HardwareChangepanel div[class*='panel__title']
hardwareHealthTitle = [xpath]://div[@aria-controls="dui_accordian_hardware change"]//*[contains(@class,"label")]
osHealthTitle = [xpath]://div[@aria-controls="dui_accordian_os health"]//*[contains(@class,"label")]
predictiveTitle = [css]:#Predictivepanel div[class*='panel__title']
securityTitle = [xpath]://div[@aria-controls="dui_accordian_security"]//*[contains(@class,"label")]
softwareHealthTitle = [xpath]://div[@aria-controls="dui_accordian_software health"]//*[contains(@class,"label")]
unassignedTitle = [xpath]://div[@aria-controls="dui_accordian_unassigned"]//*[contains(@class,"label")]
accountList = [xpath]://div[@id="dui_accordian_account"]//li/label/span[2]
genericList = [css]:#Genericpanel ul li span[class*=text]
hardwareChangeList = [xpath]://div[@id="dui_accordian_hardware change"]//li/label/span[2]
hardwareHealthList = [xpath]://div[@id="dui_accordian_hardware health"]//li/label/span[2]
osHealthList = [xpath]://div[@id="dui_accordian_os health"]//li/label/span[2]
predictiveList = [css]:#Predictivepanel ul li span[class*=text]
securityList = [xpath]://div[@id="dui_accordian_security"]//li/label/span[2]
softwareHealthList = [xpath]://div[@id="dui_accordian_software health"]//li/label/span[2]
unassignedList = [xpath]://div[@id="dui_accordian_unassigned"]//li/label/span[2]
accountListDropdownArrow = [xpath]://div[@aria-controls="dui_accordian_account"]
genericListDropdownArrow = [css]:#Genericpanel div[class*=title] svg
hardwareChangeListDropdownArrow = [xpath]://div[@aria-controls="dui_accordian_hardware change"]
hardwareHealthListDropdownArrow = [xpath]://div[@aria-controls="dui_accordian_hardware health"]
osHealthListDropdownArrow = [xpath]://div[@aria-controls="dui_accordian_os health"]
predictiveListDropdownArrow = [css]:#Predictivepanel div[class*=title] svg
securityListDropdownArrow = [xpath]://div[@aria-controls="dui_accordian_security"]
softwareHealthListDropdownArrow = [xpath]://div[@aria-controls="dui_accordian_software health"]
unassignedListDropdownArrow = [xpath]://div[@aria-controls="dui_accordian_unassigned"]
verifyincidentsNotificationTitle=[css]:#incidentsNotificationTile div[class*='label']

accountListDropdownArrowCollapsed = [xpath]://div[@aria-controls="dui_accordian_account"]
genericListDropdownArrowCollapsed = [css]:#Genericpanel div[class*=title] svg[class*=toggle-icon--collapsed]
hardwareChangeListDropdownArrowCollapsed = [xpath]://div[@aria-controls="dui_accordian_hardware change"]
hardwareHealthListDropdownArrowCollapsed = [xpath]://div[@aria-controls="dui_accordian_hardware health"]
osHealthListDropdownArrowCollapsed = [xpath]://div[@aria-controls="dui_accordian_os health"]
predictiveListDropdownArrowCollapsed = [css]:#Predictivepanel div[class*=title] svg[class*=toggle-icon--collapsed]
securityListDropdownArrowCollapsed = [xpath]://div[@aria-controls="dui_accordian_security"]
softwareHealthListDropdownArrowCollapsed = [xpath]://div[@aria-controls="dui_accordian_software health"]
unassignedListDropdownArrowCollapsed = [xpath]://div[@aria-controls="dui_accordian_unassigned"]

accountAllLocator = [css]:#dui_accordian_account li:nth-child(1) span:nth-of-type(1)
genericAllLocator = [css]:#Genericpanel li:nth-child(1) span:nth-of-type(1)
hardwareChangeAllLocator = [xpath]:(//*[@id="dui_accordian_hardware change"]//li//span[1])[1]
hardwareHealthAllLocator = [xpath]:(//*[@id="dui_accordian_hardware health"]//li//span[1])[1]
osHealthAllLocator = [xpath]:(//*[@id="dui_accordian_os health"]//li//span[1])[1]
predictiveAllLocator = [css]:#Predictivepanel li:nth-child(1) span:nth-of-type(1)
securityAllLocator = [xpath]:(//*[@id="dui_accordian_security"]//li//span[1])[1]
softwareHealthAllLocator = [xpath]:(//*[@id="dui_accordian_software health"]//li//span[1])[1]
unassignedAllLocator = [xpath]:(//*[@id="dui_accordian_unassigned"]//li//span[1])[1]
accountLocator = [css]:#dui_accordian_account li:nth-of-type(2) span:nth-of-type(1)
genericLocator = [css]:#Genericpanel li:nth-of-type(2) span:nth-of-type(1)
hardwareChangeLocator = [xpath]:(//*[@id="dui_accordian_hardware change"]//li//span[1])[2]
hardwareHealthLocator = [xpath]:(//*[@id="dui_accordian_hardware health"]//li//span[1])[2]
osHealthLocator = [xpath]:(//*[@id="dui_accordian_os health"]//li//span[1])[2]
predictiveLocator = [css]:#Predictivepanel li:nth-child(2) span:nth-of-type(1)
securityLocator = [xpath]:(//*[@id="dui_accordian_security"]//li//span[1])[2]
softwareHealthLocator = [xpath]:(//*[@id="dui_accordian_security"]//li//span[1])[2]
unassignedLocator = [xpath]:(//*[@id="dui_accordian_unassigned"]//li//span[1])[2]
doNotReceiveEmailNotificationLocator = [xpath]:(//*[@id="email_notification"]//span[contains(@class,'radio-button__span')])[1]
ReceiveEmailNotificationWhenNewIncidentIsReportedLocator = [xpath]:(//*[@id="email_notification"]//span[contains(@class,'radio-button__span')])[2]
ReceiveAnEmailNotificationWithAllIncidentsThatAreOpenedInaDayLocator = [xpath]:(//*[@id="email_notification"]//span[contains(@class,'radio-button__span')])[3]
ReceiveEmailNotificationWhenNewIncidentIsReportedAndOneEmailWithAllIncidentsThatAreOpenedInaDayLocator = [xpath]:(//*[@id="email_notification"]//span[contains(@class,'radio-button__span')])[4]
ReceiveEmailNotificationWhenNewIncidentIsReportedRadioButton = [xpath]:(//*[@id="email_notification"]//span[contains(@class,"radio-button")][1])[2]
doNotReceiveEmailNotificationRadioButton = [xpath]:(//*[@id="email_notification"]//span[contains(@class,"radio-button")][1])[1]
incidentPreferencesSaveButton = [id]:incidentSaveBtn
incidentPreferencesCancelButton = [id]:incidentCancelBtn
dailyEmailNotificationTitle = [xpath]:(//div[@id='receiveEmailTimeTile']//div[1])[1]
dailyEmailNotificationValue = [css]:#receiveEmailTimeTile div[class*="value"] span
dailyEmailNotificationEditButton = [xpath]://*[@id="receiveEmailTimeTile"]//*[contains(@class,"icon-button")]
timezoneDropdown =  [xpath]:(//div[@title='Open'])[1]
timezoneDropdownList = [css]:#select-timezone-listbox li
timezoneCodeDropdown = [id]:timezone-code
timezoneCodeDropdownList = [css]:#timezone-code-listbox li
currentTimeZone= [css]:#receiveEmailTimeTile span
dailyEmailNotificationSaveButton = [id]:emailsSaveBtn
dailyEmailNotificationCancelButton = [id]:emailsCancelBtn
validationErrorMessageOnIncidentPreferences = [xpath]://div[@id='email_notification']/../preceding-sibling::P
changeTimeZone=[xpath]: //*[@id="select-timezone-listbox"]//li[9]
communicationNotificationMessge=[xpath]://div[@role="alert"]
resetTimeZone=[xpath]: //*[@id="select-timezone-listbox"]//li[1]

searchRole = [xpath]://*[contains(@class,"search-attached")]//input[@type="search"]
listOfRoles = [xpath]://*[contains(@class,"roles-list")]//span[1]

#ToastNotification
toastNotificationAccountTile = [xpath]:(//div[@role='alert']//span)[1]
toastNotificationClose = [xpath]://div[@role="alert"]//button
