hpIcon = [css]:.row svg
hpTechPulse = [css]:.row span
language = [css]:div[role='button']
systemRequirementTitle=[css]:#requirements-description h4
systemRequirementSubtitle=[css]:#requirements-description p

#PC operating systems tile
pcOsText=[css]:#requirements-windows-os h5
pcOsDesc=[xpath]://*[@id="requirements-windows-os"]/div[2]/p
pcOsnote=[xpath]://*[@id="requirements-windows-os"]/div[5]//p
windowsLabel=[xpath]://div[@id='requirements-windows-os']/h6
windowsLine1=[xpath]://div[@id='requirements-windows-os']/ul/li[1]
windowsLine2=[xpath]://div[@id='requirements-windows-os']/ul/li[2]
windowsLine3=[xpath]://div[@id='requirements-windows-os']/ul/li[3]
macOSLabel=[xpath]://*[@id="requirements-windows-os"]/div[3]/h6
macOSLine=[xpath]://*[@id="requirements-windows-os"]/div[3]/ul/li
chromeOsLabel=[xpath]://*[@id="requirements-windows-os"]/div[4]/h6
chromeOsDesc=[xpath]://*[@id="requirements-windows-os"]/div[4]//p
chromeOsLine1=[xpath]://*[@id="requirements-windows-os"]/div[4]/ul/li[1]
chromeOsLine2=[xpath]://*[@id="requirements-windows-os"]/div[4]/ul/li[2]
chromeOsLine3=[xpath]://*[@id="requirements-windows-os"]/div[4]/ul/li[3]
supportRestrictionsLabel = [xpath]://*[@id="requirements-windows-os"]/div[5]/h6
supportRestrictionsText1 = [xpath]://*[@id="requirements-windows-os"]/div[5]/ul/li[1]
supportRestrictionsText2 = [xpath]://*[@id="requirements-windows-os"]/div[5]/ul/li[2]

#Mobile device operating systems
mobileDeviceOsText=[css]:#requirements-mobile-device h5
mobileDeviceOsDesc=[xpath]://*[@id="requirements-mobile-device"]/div[2]/p
mobileDeviceOsNote=[xpath]://*[@id="requirements-mobile-device"]/p
mobileDeviceLine1=[xpath]://*[@id="requirements-mobile-device"]/div[2]/ul/li[1]
mobileDeviceLine2=[xpath]://*[@id="requirements-mobile-device"]/div[2]/ul/li[2]

#HP Retail Point of Sale Systems
hpRposText=[css]:#requirements-rpos h5
hpRposPara=[css]:#requirements-rpos p
hpRposBullet1=[xpath]://div[@id='requirements-rpos']/ul/li[1]
hpRposBullet2=[xpath]://div[@id='requirements-rpos']/ul/li[2]
hpRposBullet3=[xpath]://div[@id='requirements-rpos']/ul/li[3]
hpRposBullet4=[xpath]://div[@id='requirements-rpos']/ul/li[4]
hpRposBullet5=[xpath]://div[@id='requirements-rpos']/ul/li[5]
hpRposBullet6=[xpath]://div[@id='requirements-rpos']/ul/li[6]
hpRposBullet7=[xpath]://div[@id='requirements-rpos']/ul/li[7]
hpRposBullet8=[xpath]://div[@id='requirements-rpos']/ul/li[8]
hpRposNote=[xpath]://*[@id="requirements-rpos"]/p[1]
hpRposNote2=[xpath]://*[@id="requirements-rpos"]/p[2]
hpRposNote3=[xpath]://*[@id="requirements-rpos"]/p[3]

#Network requirements
networkRequirementsText=[css]:#requirements-network h5
networkRequirementsPara=[css]:#requirements-network p

#Web Browsers
webBrowserText=[css]:#requirements-web-browsers h5
webBrowserDesc=[css]:#requirements-web-browsers p
pcLabel=[xpath]://*[@id="requirements-web-browsers"]/h6[1]
pcLine1=[xpath]://*[@id="requirements-web-browsers"]/ul[1]/li[1]
pcLine2=[xpath]://*[@id="requirements-web-browsers"]/ul[1]/li[2]
pcLine3=[xpath]://*[@id="requirements-web-browsers"]/ul[1]/li[3]
pcLine4=[xpath]://*[@id="requirements-web-browsers"]/ul[1]/li[4]
pcLine5=[xpath]://*[@id="requirements-web-browsers"]/ul[1]/li[5]
mobileLabel=[xpath]://*[@id="requirements-web-browsers"]/h6[2]
mobileLine1=[xpath]://*[@id="requirements-web-browsers"]/ul[2]/li[1]
mobileLine2=[xpath]://*[@id="requirements-web-browsers"]/ul[2]/li[2]
networkRequirementsHeader=[xpath]://*[@id="requirements-rpos"]//ul[2]/li
networkRequirementsDesc=[xpath]://*[@id="requirements-rpos"]/ul[2]/ul/li
webBrowserNote=[xpath]://*[@id="requirements-web-browsers"]/p

#Proactive Security
proactiveSecurityText = [xpath]://*[@id="dui-requirements-proactive"]/div[1]//p
windowsText1 = [xpath]://*[@id="requirements-sure-sense"]/ul/ul[1]/li[1]
windowstext2 = [xpath]://*[@id="requirements-sure-sense"]/ul/ul[1]/li[2]
macOSText = [xpath]://*[@id="requirements-sure-sense"]/ul/ul[2]/li
androidText = [xpath]://*[@id="requirements-sure-sense"]/ul/ul[3]/li
supportedProcessorTitle = [xpath]://*[@id="requirements-sure-click"]/ul/ul[1]/li[1]
supportedProcessorText1 = [xpath]://*[@id='requirements-sure-click']//ul[1]/ul[1]/ul/li[1]
supportedProcessorText2 = [xpath]://*[@id="requirements-sure-click"]/ul/ul[1]/ul/li[2]
deviceHardwareText2 = [xpath]://*[@id="requirements-sure-click"]/ul/ul[1]/li[2]
deviceHardwareText3 = [xpath]://*[@id="requirements-sure-click"]/ul/ul[1]/li[3]
deviceHardwareText4 = [xpath]://*[@id="requirements-sure-click"]/ul/ul[1]/li[4]
deviceHardwareText5 = [xpath]://*[@id="requirements-sure-click"]/ul/ul[1]/li[5]
windowsTiletext1 = [xpath]://*[@id="requirements-sure-click"]/ul/li[1]
windowsTiletext2 = [xpath]://*[@id="requirements-sure-click"]//*[contains(@class,'window_req')][1]//p
thirdPartySw = [xpath]://*[@id="requirements-sure-click"]//ul[4]/li
bromiumLink = [xpath]://*[@id="requirements-proSecurity"]//li[2]/a
bromiumHeader = [xpath]://*[contains(@class,'cBrandingLogo')]
networkRequirementsTitle = [xpath]://*[@id="requirements-sure-click"]/ul/li[4]
networkRequirementsDetails = [xpath]://*[@id="requirements-sure-click"]/ul/ul[4]/li
sureSenesAdvancedTitle = [css]:#requirements-sure-sense h5
sureClickAdvancedTitle = [css]:#requirements-sure-click h5
networkRequirementsTitle1 = [xpath]://*[@id="requirements-sure-sense"]/ul/li[4]
networkRequirementsDetails1 = [xpath]://*[@id="requirements-sure-sense"]/ul/ul[4]/li
proactiveSecurityTitle = [css]:#dui-requirements-proactive h4
windowsOSRequirementTitle = [xpath]://*[@id="requirements-sure-sense"]/ul/li[1]
macOSRequirementTitle = [xpath]://*[@id="requirements-sure-sense"]/ul/li[2]
androidOSRequirementTitle = [xpath]://*[@id="requirements-sure-sense"]/ul/li[3]
windowsVersion1 = [xpath]://*[@id="requirements-sure-click"]/ul/ul[2]/li[1]
windowsVersion2 = [xpath]://*[@id="requirements-sure-click"]/ul/ul[2]/li[2]
windowsVersion3 = [xpath]://*[@id="requirements-sure-click"]/ul/ul[2]/li[3]
windowsVersion4 = [xpath]://*[@id="requirements-sure-click"]/ul/ul[2]/li[4]
windowsRequirementsText = [css]:#requirements-sure-click > ul > div:nth-child(5)

#Support life cycle policy tile 
supportLifeCyclePolicyLink = [xpath]://*[@id="requirements-sure-click"]//div[3]/div
hideLifeCyclePolicyLink = [xpath]://*[@id="requirements-sure-click"]/ul/div[3]/div[1]
supportLifeCycleContent = [css]:#requirements-sure-click [class*="lifecycle-holder"]
windowsRealeaseInformationLink = [css]:#requirements-sure-click a
supportLifeCycleHeader = [css]:#requirements-sure-click [class*="lifecycle-holder"] strong
supportLifeCycleContent1 = [css]:#requirements-sure-click .support-lifecycle-holder p:nth-child(2)
supportLifeCycleContent2 = [css]:#requirements-sure-click .support-lifecycle-holder p:nth-child(4)
supportLifeCycleContent3 = [css]:#requirements-sure-click .support-lifecycle-holder p:nth-child(6)
supportLifeCycleContent5 = [css]:#requirements-sure-click .support-lifecycle-holder p:nth-child(5)
identityProtectionHeader = [css]:#requirements-sure-click ul li:nth-child(7)
identityProtectionDescription = [css]:#requirements-sure-click div:nth-child(8)>p
googleChromeVersionText = [xpath]://*[@id="requirements-sure-click"]/ul/ul[3]//li[1]
microsoftEdgeVersionText = [xpath]://*[@id="requirements-sure-click"]/ul/ul[3]//li[2]