hpIcon = [css]:.row:nth-child(1) svg
hpTechPulse = [css]:.row:nth-child(1) span
language = [css]:div[role='button']
systemRequirementTitle=[css]:#requirements-description h4
systemRequirementSubtitle=[css]:#requirements-description p
supportRestrictionsLabel = [xpath]://*[@id="requirements-windows-os"]/div[5]/h6
supportRestrictionsText1 = [xpath]://*[@id="requirements-windows-os"]/div[5]/ul/li[1]
supportRestrictionsText2 = [xpath]://*[@id="requirements-windows-os"]/div[5]/ul/li[2]
pcOsnoteSupport=[xpath]://*[@id="requirements-windows-os"]/div[5]//p


#PC operating systems tile
pcOsText=[css]:#requirements-windows-os h5
pcOsDesc=[xpath]://*[@id="requirements-windows-os"]/div/p
pcOsnote=[css]:#requirements-windows-os p.note
windowsLabel=[xpath]://div[@id='requirements-windows-os']//div[2]/h6
windowsLine1=[css]:#requirements-windows-os div:nth-child(4) ul li
windowsLine2=[xpath]://div[@id='requirements-windows-os']/ul/li[2]
windowsLine3=[xpath]://div[@id='requirements-windows-os']/ul/li[3]
macOSLabel=[xpath]://*[@id="requirements-windows-os"]/div[3]/h6
macOSLine=[xpath]://*[@id="requirements-windows-os"]/div[3]/ul/li
chromeOsLabel=[xpath]://*[@id="requirements-windows-os"]/div[4]/h6
chromeOsDesc=[xpath]://*[@id="requirements-windows-os"]/div[4]//p
chromeOsLine1=[xpath]://*[@id="requirements-windows-os"]/div[4]/ul/li[1]
chromeOsLine2=[xpath]://*[@id="requirements-windows-os"]/div[4]/ul/li[2]
chromeOsLine3=[xpath]://*[@id="requirements-windows-os"]/div[4]/ul/li[3]

#Mobile device operating systems
mobileDeviceOsText=[css]:#requirements-mobile-device h5
mobileDeviceOsDesc=[xpath]://*[@id="requirements-mobile-device"]/div/p
mobileDeviceOsNote=[xpath]://*[@id="requirements-mobile-device"]/p
mobileDeviceLine1=[xpath]://*[@id="requirements-mobile-device"]/div[2]/ul/li[1]
mobileDeviceLine2=[xpath]://*[@id="requirements-mobile-device"]/div[2]/ul/li[2]

#HP Retail Point of Sale Systems
hpRposText=[css]:#requirements-rpos h5
hpRposPara=[css]:#requirements-rpos [class*=os_box] p
hpRposBullet1=[xpath]://div[@id='requirements-rpos']/ul/li[1]
hpRposBullet2=[xpath]://div[@id='requirements-rpos']/ul/li[2]
hpRposBullet3=[xpath]://div[@id='requirements-rpos']/ul/li[3]
hpRposBullet4=[xpath]://div[@id='requirements-rpos']/ul/li[4]
hpRposBullet5=[xpath]://div[@id='requirements-rpos']/ul/li[5]
hpRposBullet6=[xpath]://div[@id='requirements-rpos']/ul/li[6]
hpRposBullet7=[xpath]://div[@id='requirements-rpos']/ul/li[7]
hpRposBullet8=[xpath]://div[@id='requirements-rpos']/ul/li[8]
hpRposNote=[xpath]://*[@id="requirements-rpos"]/p[1]
hpRposNote2=[xpath]://*[@id="requirements-rpos"]/p[2]
hpRposNote3=[xpath]://*[@id="requirements-rpos"]/p[3]

#Network requirements
networkRequirementsText=[css]:#requirements-network h5
networkRequirementsPara=[css]:#requirements-network p

#Web Browsers
webBrowserText=[css]:#requirements-web-browsers h5
webBrowserDesc=[css]:#requirements-web-browsers div p
pcLabel=[css]:#requirements-web-browsers h6:nth-child(1)
pcLine1=[css]:#requirements-web-browsers [class*=os_box] ul li:nth-child(1)
pcLine2=[css]:#requirements-web-browsers [class*=os_box] ul li:nth-child(2)
pcLine3=[css]:#requirements-web-browsers [class*=os_box] ul li:nth-child(3)
pcLine4=[css]:#requirements-web-browsers [class*=os_box] ul li:nth-child(4)
pcLine5=[css]:#requirements-web-browsers [class*=os_box] ul li:nth-child(5)
mobileLabel=[xpath]://*[@id="requirements-web-browsers"]/h6[1]
mobileLine1=[xpath]://*[@id="requirements-web-browsers"]/ul/li[1]
mobileLine2=[xpath]://*[@id="requirements-web-browsers"]/ul/li[2]
networkRequirementsHeader=[xpath]://*[@id="requirements-rpos"]//ul[2]/li
networkRequirementsDesc=[xpath]://*[@id="requirements-rpos"]/ul[2]/ul/li
webBrowserNote=[xpath]://*[@id="requirements-web-browsers"]/p

#Proactive Security
proactiveSecurityText = [xpath]://*[@id="dui-requirements-proactive"]/div[1]//p
windowsText1 = [xpath]://*[@id="requirements-sure-sense"]//ul/li[1]
windowstext2 = [xpath]://*[@id="requirements-sure-sense"]//ul/li[2]
macOSText = [xpath]://*[@id="requirements-sure-sense"]/ul/ul[2]/li
androidText = [xpath]://*[@id="requirements-sure-sense"]/ul/ul[3]/li

supportedProcessorTitle = [css]:#requirements-sure-click div:nth-child(2)>ul>li:nth-child(1)
supportedProcessorText1 = [css]:#requirements-sure-click div:nth-child(2)>ul>ul>li:nth-child(1)
supportedProcessorText2 = [css]:#requirements-sure-click div:nth-child(2)>ul>ul>li:nth-child(2)
deviceHardwareText2 = [css]:#requirements-sure-click div:nth-child(2) li:nth-child(3)
deviceHardwareText3 = [css]:#requirements-sure-click div:nth-child(2) li:nth-child(4)
deviceHardwareText4 = [css]:#requirements-sure-click div:nth-child(2) li:nth-child(5)
deviceHardwareText5 = [css]:#requirements-sure-click div:nth-child(2) li:nth-child(6)
windowsTiletext1 = [css]:#requirements-sure-click [class*=os_box]:nth-child(3) h6
windowsTiletext2 = [css]:#requirements-sure-click [class*=os_box]:nth-child(3)> p
thirdPartySw = [css]:#requirements-sure-click [class*=os_last_box] li

bromiumLink = [xpath]://*[@id="requirements-proSecurity"]//li[2]/a
bromiumHeader = [xpath]://*[contains(@class,'cBrandingLogo')]
networkRequirementsTitle = [xpath]://*[@id="requirements-sure-click"]/ul/li[4]
networkRequirementsDetails = [xpath]://*[@id="requirements-sure-click"]/ul/ul[4]/li
sureSenesAdvancedTitle = [css]:#requirements-sure-sense h5
sureClickAdvancedTitle = [css]:#requirements-sure-click h5
networkRequirementsTitle1 = [xpath]://*[@id="requirements-sure-sense"]/ul/li[4]
networkRequirementsDetails1 = [xpath]://*[@id="requirements-sure-sense"]/ul/ul[4]/li
proactiveSecurityTitle = [css]:#dui-requirements-proactive h4
windowsOSRequirementTitle = [css]:#requirements-sure-sense h6
macOSRequirementTitle = [xpath]://*[@id="requirements-sure-sense"]/ul/li[2]
androidOSRequirementTitle = [xpath]://*[@id="requirements-sure-sense"]/ul/li[3]

windowsVersion1 = [css]:#requirements-sure-click [class*=os_box]:nth-child(3) li:nth-child(1)
windowsVersion2 = [css]:#requirements-sure-click [class*=os_box]:nth-child(3) li:nth-child(2)
windowsVersion3 = [css]:#requirements-sure-click [class*=os_box]:nth-child(3) li:nth-child(3)
windowsVersion4 = [css]:#requirements-sure-click [class*=os_box]:nth-child(3) li:nth-child(4)
windowsRequirementsText = [css]:#requirements-sure-click [class*=window_req]

#Support life cycle policy tile 
supportLifeCyclePolicyLink = [css]:#requirements-sure-click [class*=os_box]:nth-child(3) div:nth-child(1)
hideLifeCyclePolicyLink = [css]:#requirements-sure-click [class*=os_box]:nth-child(3) div:nth-child(1)
supportLifeCycleContent = [css]:#requirements-sure-click [class*="lifecycle-holder"]:nth-child(2)
windowsRealeaseInformationLink = [css]:#requirements-sure-click a
supportLifeCycleHeader = [css]: [class*="lifecycle-holder"] h6
supportLifeCycleContent1 = [css]:#requirements-sure-click .support-lifecycle-holder p:nth-child(2)
supportLifeCycleContent2 = [css]:#requirements-sure-click .support-lifecycle-holder p:nth-child(4)
supportLifeCycleContent3 = [css]:#requirements-sure-click .support-lifecycle-holder p:nth-child(6)
supportLifeCycleContent5 = [css]:#requirements-sure-click .support-lifecycle-holder p:nth-child(5)
identityProtectionHeader = [css]:#requirements-sure-click > div:nth-child(4) > h6
identityProtectionDescription = [css]:#requirements-sure-click > div:nth-child(4) > p
googleChromeVersionText = [css]:#requirements-sure-click > div:nth-child(4) > ul li:first-child
microsoftEdgeVersionText = [css]:#requirements-sure-click > div:nth-child(4) > ul li:last-child