#table configuration
tableConfigurationTitle =  [xpath]://h4[@id='column-options-label']
showAdvanceFilterButton = [css]:div.vn-tableconfiguration__modal--showFilters-toggle>a

discardButton = [css]:#column-options-label+div+div button:nth-child(2)
#saveButton = [css]:#column-options-label+div+button+div button:nth-child(1)
saveButton = [css]:#column-options-label+div+div button:nth-child(1)

listOfColumnsOnPopup = [css]:#column-options-label+div div[role=option] span+span
listOfcheckedColumnsOnPopup = [xpath]://*[@id='column-options-label']//parent::div//div[@role='option']//input[@aria-checked='true']//parent::span//following::span[contains(@class,'text')]
columnCheckboxesOnPopup = [css]:#column-options-label+div div[role=option] input
selectedCheckBoxesOnPopup = [css]:#column-options-label+div div[role=option] input[aria-checked=true]
idCheckboxOfPopup = [css]:#column-options-label+div div[role=option]:first-child
priorityCheckBoxOfpopUp = [css]:#column-options-label+div div[role=option]:nth-child(5)
upArrow = [xpath]://h4[@id='column-options-label']//following-sibling::div[1]//button[1]
downArrow = [xpath]://h4[@id='column-options-label']//following-sibling::div[1]//button[2]
filterBoxesOfTable = [css]:tr:nth-of-type(2) th>div
resettodefault = [xpath]:(//h4[@id='column-options-label']//following-sibling::div//button[contains(@class,'vn-reset-to-default-button')])
selectColumnToDisplay=[xpath]://*[@id='column-options']//ul//*[contains(text(),'%s')]

selectedCheckBoxesOnPopupAfterDeselect = [css]:#column-options-label+div div[role=option] input[aria-checked=true]
deviceModel = [css]:#column-options-label+div div[role=option]:nth-child(14) label span+span
firstCheckBoxOnPopup= [css]:#column-options-label+div div[role=option]:first-child
subTypeCheckBox =[css]:#column-options-label+div div[role=option]:nth-child(3) label span+span
typeCheckBox =[css]:#column-options-label+div div[role=option]:nth-child(4) label span+span
storeNumber = [id]:storeNumber
nameColumnCheckbox = [xpath]://label[@for='name']
tableOverlay = [xpath]://div[contains(@class,'page-spinner')]//*[name()='svg']
tableConfigurationButton = [xpath]://button[@aria-label="Column Options"]
clearFilter = [xpath]://button[@aria-label="Clear Filters"]
spinner = [xpath]://svg[contains(@class,'spinner')]
#Supportcontacts
Settingsbutton=[xpath]: //button[@aria-label='Column Options']
resettodefaultoption=[xpath]: //button[contains(@class,'reset-to-default-button')]
columnoptions=[xpath]://h4[@id='column-options-label']
chkEnrolled=[xpath]://*[text()='Enrolled']/preceding-sibling::input
floatingUiLabelOrDeviceDeletePopup = [xpath]://*[(@id='floating-ui-k1nv142-label') or contains(text(),'device delete')]
