#table configuration
tableConfigurationTitle = [css]:div.vn-modal__header>h4
showAdvanceFilterButton = [css]:div.vn-tableconfiguration__modal--showFilters-toggle>a
discardButton = [id]:cancel
saveButton = [id]:save
listOfColumnsOnPopup = [css]:li.vn-multiselect__component--li label
listOfcheckedColumnsOnPopup = [css]:div.vn-tableconfiguration span.vn-checkbox__span.vn-checkbox__span--checked+span
columnCheckboxesOnPopup = [css]:li.vn-multiselect__component--li label>input
selectedCheckBoxesOnPopup = [css]:div.vn-tableconfiguration span.vn-checkbox__span.vn-checkbox__span--checked
idCheckboxOfPopup = [css]:li:nth-of-type(1).vn-multiselect__component--li>div
priorityCheckBoxOfpopUp = [css]:li:nth-of-type(5).vn-multiselect__component--li>div
upArrow = [id]:up
downArrow = [id]:down
filterBoxesOfTable = [css]:tr:nth-of-type(2)>th.vn-tableheader__cell.vn-tableheader__filter-cell
resettodefault = [id]:reset
selectedCheckBoxesOnPopupAfterDeselect = [css]:div.vn-tableconfiguration span.vn-checkbox__span
deviceModel = [id]:deviceModel
firstCheckBoxOnPopup= [css]:li:nth-of-type(1).vn-multiselect__component--li>div
subTypeCheckBox =[xpath]://*[@name="Subtype"]/ancestor::label
typeCheckBox =[xpath]://*[@name="Type"]/ancestor::label
storeNumber = [id]:storeNumber
nameColumnCheckbox = [xpath]://label[@for='name']
tableOverlay = [xpath]://div[contains(@class,'overlay-spinner')]//*[name()='svg']   
tableConfigurationButton = [css]:div[class*=tableconfiguration] button
clearFilter = [css]:button[title=Clear]
spinner = [xpath]://svg[contains(@class,'spinner')]