CATALOG_CUSTOMER1_NAME = wex_automation_customer1
CATALOG_CUSTOMER1_TENANTID = eb897df9-a5ab-4294-ab24-2559eafe4b32
CATALOG_CUSTOMER2_NAME = wex_automation_customer2
CATALOG_CUSTOMER2_TENANTID = c1ffc2eb-e86a-4c5d-971f-31a306e44602
WEX_CUSTOMER_NAME = WEP Automation Customer -
INVITE_CUSTOMER_NAME = automationpendinginvitecustomer
PENDING_REQUEST_CUSTOMER_NAME = automationpendingrequestcustomer

USER_FN = inviteuser12
USER_LN = invite
WEX_USER_EMAIL_SEARCH = inviteuser12invitenpg@hpmsqa.mailinator
COMPANY_FULLNAME = uiautomation itadmin
COMPANY_NAME = Soci�t� d'AveryTechie
INVITED_USER_EMAIL_SUBJECT = invites you to the Workforce Experience Platform
CUSTOMER_NAME = wex_automation_customer1
PARTNER_NAME = WEXPartner-95
MSP_NAME = WEX_automation_DND
EntraID_GroupName = Automation testing pulse engg grp - dont delete the grp
Membership_Type = Entra ID
Operating_Systems = Windows, Mac
Selected_GroupName = Automation testing pulse engg grp - dont delete the grp
Selected_Member_Devices = 1
ImportedGroupName = Automation Testing Pulse
Device_Count_OverviewTab = 1
Device_Name_MembershipTab = DESKTOP-6G1OKB6
EntraID_ErrorMessage = Field is required

ORDERS_EXISTING_AC_COMPANY = ordersAddDeviceExistingTenantUS.csv
ORDERS_MANDATORY_HT = ordersMandatoryHoldingTankTenant.csv
TEST_DEVICE_SERIAL_NUM = 5CD244G9WY
CUSTOMER_DEVICELIST = shcompwxp03aprusprodstd
VIRTUAL_MACHINE_SERIAL_NUMBER = 0000-0005-3222-8408-8940-0544-46

MSP_ID = mspauto
WEX_COMPANY_NAME = wexautocustomer
WEX_COMPANY_FN = wexocauto
WEX_COMPANY_LN = prod
WEX_COMPANY_ADDRESS = 123, xyz street
WEX_COMPANY_CITY = Hyderabad
WEX_COMPANY_ZIPCODE = 500081
WEX_COMPANY_STATE = Telangana
WEX_PHONE_NO = 12345
ROLE1 = IT Admin
ROLE2 = Connector Admin

WEX_OLD_PULSES_LIST_URL = https://workforceexperience.hp.com/ui/employee-engagement/pulses
WEX_NEW_PULSES_LIST_URL = https://workforceexperience.hp.com/ui/view/pulses
WEX_OLD_PULSES_CREATION_CONTENT = https://workforceexperience.hp.com/ui/view/pulses/create/custompulse/tab-content
WEX_OLD_PULSES_CREATION_SCHEDULE = https://workforceexperience.hp.com/ui/view/pulses/create/custompulse/tab-schedule
WEX_OLD_PULSES_CREATION_AUDIENCE = https://workforceexperience.hp.com/ui/view/pulses/create/custompulse/tab-audience
WEX_NEW_PULSES_CREATION_CONTENT = https://workforceexperience.hp.com/ui/view/pulses/create/custompulse/content
WEX_NEW_PULSES_CREATION_SCHEDULE = https://workforceexperience.hp.com/ui/view/pulses/create/custompulse/schedule
WEX_NEW_PULSES_CREATION_AUDIENCE = https://workforceexperience.hp.com/ui/view/pulses/create/custompulse/audience
WEX_OLD_PULSES_CREATION_SENTIMENT_CONTENT = https://workforceexperience.hp.com/ui/view/pulses/createSentimentPulse/tab-content
WEX_OLD_PULSES_CREATION_SENTIMENT_SCHEDULE = https://workforceexperience.hp.com/ui/view/pulses/createSentimentPulse/tab-schedule
WEX_OLD_PULSES_CREATION_SENTIMENT_AUDIENCE = https://workforceexperience.hp.com/ui/view/pulses/createSentimentPulse/tab-audience
WEX_NEW_PULSES_CREATION_SENTIMENT_CONTENT = https://workforceexperience.hp.com/ui/view/pulses/create/sentimentpulse/content
WEX_NEW_PULSES_CREATION_SENTIMENT_SCHEDULE = https://workforceexperience.hp.com/ui/view/pulses/create/sentimentpulse/schedule
WEX_NEW_PULSES_CREATION_SENTIMENT_AUDIENCE = https://workforceexperience.hp.com/ui/view/pulses/create/sentimentpulse/audience
WEX_NEW_PULSES_RESULTS = https://workforceexperience.hp.com/ui/view/pulses
WEX_NEW_EE_DASHBOARD_REPORT_NEW = https://workforceexperience.hp.com/ui/view/analytics/dashboard/6777497d9088ff3bbfc86bab


# Groups
Groups_FILTERS_SERIAL_NUMBER_VALUE = HPAUTO66870851
Groups_FILTERS_DEVICE_NAME_VALUE = FD-HPAUTO66870851
Groups_FILTERS_MANUFACTURER_VALUE = MICROSOFT
Groups_FILTERS_OPERATING_SYSTEM_VALUE = Microsoft Windows 10 Enterprise
Groups_FILTERS_DEVICE_MODEL_VALUE = HP ProBook 440 G5
Groups_Device_serial_number = 000377045V
WEX_ASSIGNMTN_LIST_POLICY_URL = https://workforceexperience.hp.com/ui/view/remediations/pc-policies
WEX_ASSIGNMTN_LIST_SCRIPTS_URL = https://workforceexperience.hp.com/ui/view/remediations/scripts/assignments

# HelpandSupport
WXP_GETTING_STARTED_GUIDE = https://learn.workforceexperience.hp.com/docs/wxp-getting-started-guide
WXP_KNOWLEDGE_BASE = https://learn.workforceexperience.hp.com
WXP_SOFTWARE_DOWNLOAD = https://workforceexperience.hp.com/software
WXP_SYSTEM_REQUIREMENTS = https://workforceexperience.hp.com/requirements
WXP_PRIVACY_LINK =https://www.hp.com/us-en/privacy/privacy-central.html
WXP_SLA = https://workforceexperience.hp.com/sla
WXP_TERMS_AND_CONDITIONS = https://workforceexperience.hp.com/terms-and-conditions

# ActiveCare Details
IOTDiscoveryURL = https://discovery.hpdaas.com/v2/services
# IOT Device Enrollment JSON Tushar
IOT_ENROLL_DEVICE = IOTEnrollDevice.json
#CRON job end points
hostURL = https://www.hpdaas.com/