PRODUCTION_TEST_COMPANY = Automation Company-Do Not Delete
LHADMIN_PORTAL_URL = https://admin.hpdaas.com/
WINDOWSSOFTWAREJSONDATA = https://dcefh8tp1pusz.cloudfront.net/PROD/%7bE5FB98E0-0784-44F0-8CEC-95CD4690C43F%7d/Archive/versioncatalog.json
MACSOFTWAREJSONDATA = 	  http://downloads.hpdaas.com/production/macos/APMAgentAppcast.xml
ANDROIDSOFTWAREDATA = https://play.google.com/store/apps/details?id=com.hp.apmagent
WORKFLOW_URLCHECK_DASHBOARD = https://www.hpworkflows.com/ui/view/dashboard
WORKFLOW_URLCHECK_REPORT = https://www.hpworkflows.com/ui/view/reports/type/standard
WORKFLOW_CHILD_COMPANY = AUTOMATIONCHILDCOMPANY
WORKFLOW_USER_EMAIL = workflowprodcompany00@hpmsqa.mailinator.com
WORKFLOW_TERMSCOND_URL = https://www.hpworkflows.com/terms-and-conditions
WORKFLOW_URLCHECK_SETTINGS = https://www.hpworkflows.com/ui/view/settings
DEVICE_IMPORT_COMPANY = Automation Company-Do Not Delete
IMPORT_DEVICE_COMPANY_CSV = Automation Company-Do Not Delete
STATIC_COMPANY = Automation Company-Do Not Delete
ASSIGNED_PARTNER_NAME =  Reseller Sales Admin
ASSIGNED_PARTNER_NAME_EMAIL = Reseller Sales Admin
DAAS_API_BASE_URL = https://www.hpdaas.com/
CAMPAIGN_COMPANY = Automation Company-Do Not Delete

# ActiveCare Details
IOTDiscoveryURL = https://staging-discovery.hpdaas.com/v2/services
ORDERS_NEW_AC_COMPANY = orderAddNewCustomerTenantUS.csv
ORDERS_EXISTING_AC_COMPANY = ordersAddDeviceExistingTenantUS.csv
EXISTING_DEVICE = startDateEndDateUS.csv
ORDERS_LESS_THAN_255 = ORDERS_LESS_THAN_255.csv
ORDERS_GREATER_THAN_255 = ORDERS_GREATER_THAN_255.csv
ORDERS_MANDATORY_HT = ordersMandatoryHoldingTankTenant.csv
# IOT Device Enrollment JSON Tushar
IOT_ENROLL_DEVICE = IOTEnrollDevice.json
# ActiveCare Tenant Details
ACOnlyTenantName_US = DonNotDeleteActiveCareOnlyTenant
ACOnlyTenantCPIN_US = fG4gWbQ4
INVITED_ADDUSER_EMAIL_SUBJECT = HP Active Care Service Activation
APP_NAME = HP Insights