#ActiveCare Users used in Device Transfer
ACTIVE_CARE_NAME_TENANT= DoNotDeleteActiveCareOnlyTenant
ACTIVE_CARE_PI_TENANT_ID= bc305f72-fd8e-43a7-b534-974daacc33a6
ACTIVE_CARE_NAME_TENANT_TN_DISPLAY_ID = C-58NKwngR
ACTIVE_CARE_NAME_TENANT_ID=4a748a2a-6191-4ef8-be5c-3282403c7a4f
ACTIVE_CARE_NAME_TENANT_CPIN=fG4gWbQ4
ACTIVE_CARE_PI_TENANT_CPIN= H5MUct4p
AC_PLUS_PI_NAME_TENANT=DoNotDeleteACPITenantUS
AC_PLUS_PI_NAME_TENANT_TN_DISPLAY_ID=C-QiB67ayD
AC_PLUS_PI_NAME_TENANT_CPIN=H5MUct4p
AC_PLUS_PI_NAME_TENANT_ID=bc305f72-fd8e-43a7-b534-974daacc33a6
INVALID_TENANT= InvalidTenantUS
INVALID_TENANT_TN_DISPLAY_ID = 101010

deviceReportLambdaEndPointUrl=https://internal-usstaging-api.hpdaas.com
ACOnlyTenantId_US = 4a748a2a-6191-4ef8-be5c-3282403c7a4f
optional-pc-refactor = PCE_DEVICE_CAMS_DATA
PlanId_RemoteCare = 8fc9e078-e8a8-4d39-b425-40d2d38ab41e
PlanId_ActiveCare = 61b196c4-3f37-435c-ad17-62b77744fd82

hostURL = https://usperfms.daas.hppipeline.com
hostEnviroment = usperfms
cronJobEndPointToProcessOrders=/services/carepack-service/internal/1.0/cronjob/process-new-orders
cronJobEndPointToCompleteOrders=/services/carepack-service/internal/1.0/cronjob/process-incomplete-orders
cronJobEndPointToMakeSNREntry=/services/ccc-snr/internal/1.0/snr
cronJobEndPointToDeleteSNREntry=/services/ccc-snr/internal/1.0/serialNo/
IOTDiscoveryURL = https://perf-discovery.daas.hppipeline.com/v2/services
IOT_ENROLL_DEVICE = IOTEnrollDevice.json
