CUSTOMER_NAME =  WEXAutomationCustomerDND
INVITED_USER_EMAIL_SUBJECT = invites you to the Workforce Experience Platform (WXP)!
WEX_USER_EMAIL_SEARCH = inviteuser12invitenpg@hpmsqa.mailinator
USER_FN = inviteuser12
USER_LN = invite
COMPANY_FULLNAME = wex Automation
COMPANY_NAME = US WEP Automation Stage
PARTNER_FULLNAME = wex partner
MSP_USER_NAME = US STAGE MSP USER DND
PULSE_FILTERS_LASTLOGGED_FILTER_VALUE = HPAUTO3781173@hp.com
PULSE_FILTERS_SERIAL_NUMBER_VALUE = HPAUTO94314
PULSE_FILTERS_FIELD_DEVICE_MANUFACTURER_VALUE = HP
PULSE_FILTERS_FIELD_OPERATING_SYSTEM_VALUE = Microsoft Windows 10 Pro
PULSE_FILTERS_FIELD_DEVICE_TYPE_VALUE = Notebook
CATALOG_CUSTOMER1_NAME = US WEP Automation Stage
HAS_LOCATION_CUSTOMER_NAME =  AutoPartnerActiveCustomer DND
UPDATE_LOCATION_CUSTOMER = US WEP Automation Stage
CATALOG_CUSTOMER1_TENANTID = f0a906a2-4198-40e4-9b4d-a6ab08045d2d
CATALOG_CUSTOMER2_NAME = stagecompany1us WEX Automation
CATALOG_CUSTOMER2_TENANTID = 5a88b17b-9c82-43aa-9392-059e40f44bb0
WEX_ACTIVE_CUSTOMER_NAME = WEPAutomationActiveCustomer-
WEXCOMPANY_ACTIVE = WEPAutomationNewActiveCustomer-
PENDING_INVITE_CUSTOMER_NAME = WEPAutomationPendingInviteCustomer-
Pending_Invite_Customer = AutomationPendingInviteCustomer2
PENDING_REQUEST_CUSTOMER = CompanyWithPendingRequest
ACTIVE_CUSTOMER_NAME =WEPAutomationActiveCustomer-
COMPANY_ORIGINATION = HP
INVITE_CUSTOMER_EMAIL_WEP = uiautomationinviteita-donotdeletetestusstage-2
PARTNER_NAME = WEX_automation_DND
MSP_NAME = 17febmsp25W
EntraID_GroupName = Automation testing pulse engg grp - dont delete the grp
Membership_Type = Entra ID
Operating_Systems = Windows, Mac
Selected_GroupName = Automation testing pulse engg grp - dont delete the grp
Selected_Member_Devices = 1
ImportedGroupName = Automation Testing Pulse
Device_Count_OverviewTab = 1
Device_Name_MembershipTab = DESKTOP-6G1OKB6
EntraID_ErrorMessage = Field is required

# IOT Device Enrollment JSON
IOTDiscoveryURL = https://staging-discovery.hpdaas.com/v2/services
IOT_ENROLL_DEVICE = IOTEnrollDevice.json

# Scripts enrollment data
SCRIPTS_COMPANY_NAME = US WEP Automation Stage
SCRIPTS_CPIN = Dpr54rRN
SCRIPTS_COMPANY_EMAIL = uswexautomationstage@workforceqa.ext.hp.com
SCRIPTS_SERIAL_NO = DYNGRPAUTOMATION2651
SCRIPTS_DEVICE_ID = qPSd31eas2cI3TRWoAr7TjX0kTr4q1DwUp0fvVKbYEv
SCRIPTS_TENANT_ID = 9ae553f6-bf31-453e-a2d1-fb2ac759e6ce
IOT_JOB_ID = 13243
AWS_ROLE_ARN = arn:aws:iam::614310738423:role/wxp-qa-iot-automation
AWS_EXTERNAL_ID = 123e4567-e89b-12d3-a456-426614174000

#Devices regression Data
VIRTUAL_MACHINE_SERIAL_NUMBER = 0000-0017-5509-8477-5650-2658-69
TEST_DEVICE_SERIAL_NUM = DNDAssetsTestDev62104
WPT_TEST_DEVICE_SERIAL_NUM = 9CG47702W7
PARTNER_COMPANY_TO_SELECT = WEXAutomationCustomerDND
CUSTOMER_NAME_ASSET = US WEP Automation Stage
ASSET_DEVICE_SERIAL_NUM = 000010013D

MSP_ID = mspauto
WEX_COMPANY_NAME = wexautostagecustomer
WEX_COMPANY_FN = wexocauto
WEX_COMPANY_LN = stage
WEX_COMPANY_ADDRESS = 123, xyz street
WEX_COMPANY_CITY = Hyderabad
WEX_COMPANY_ZIPCODE = 500081
WEX_COMPANY_STATE = Telangana
WEX_PHONE_NO = 12345
ROLE1 = IT Admin
ROLE2 = Connector Admin
ROLE3 = Lost Device Admin

WEX_OLD_PULSES_LIST_URL = https://usstagingms.workforceexperience.hp.com/ui/employee-engagement/pulses
WEX_NEW_PULSES_LIST_URL = https://usstagingms.workforceexperience.hp.com/ui/view/pulses
WEX_OLD_PULSES_CREATION_CONTENT = https://usstagingms.workforceexperience.hp.com/ui/view/pulses/create/custompulse/tab-content
WEX_OLD_PULSES_CREATION_SCHEDULE = https://usstagingms.workforceexperience.hp.com/ui/view/pulses/create/custompulse/tab-schedule
WEX_OLD_PULSES_CREATION_AUDIENCE = https://usstagingms.workforceexperience.hp.com/ui/view/pulses/create/custompulse/tab-audience
WEX_NEW_PULSES_CREATION_CONTENT = https://usstagingms.workforceexperience.hp.com/ui/view/pulses/create/custompulse/content
WEX_NEW_PULSES_CREATION_SCHEDULE = https://usstagingms.workforceexperience.hp.com/ui/view/pulses/create/custompulse/schedule
WEX_NEW_PULSES_CREATION_AUDIENCE = https://usstagingms.workforceexperience.hp.com/ui/view/pulses/create/custompulse/audience
WEX_OLD_PULSES_CREATION_SENTIMENT_CONTENT = https://usstagingms.workforceexperience.hp.com/ui/view/pulses/createSentimentPulse/tab-content
WEX_OLD_PULSES_CREATION_SENTIMENT_SCHEDULE = https://usstagingms.workforceexperience.hp.com/ui/view/pulses/createSentimentPulse/tab-schedule
WEX_OLD_PULSES_CREATION_SENTIMENT_AUDIENCE = https://usstagingms.workforceexperience.hp.com/ui/view/pulses/createSentimentPulse/tab-audience
WEX_NEW_PULSES_CREATION_SENTIMENT_CONTENT = https://usstagingms.workforceexperience.hp.com/ui/view/pulses/create/sentimentpulse/content
WEX_NEW_PULSES_CREATION_SENTIMENT_SCHEDULE = https://usstagingms.workforceexperience.hp.com/ui/view/pulses/create/sentimentpulse/schedule
WEX_NEW_PULSES_CREATION_SENTIMENT_AUDIENCE = https://usstagingms.workforceexperience.hp.com/ui/view/pulses/create/sentimentpulse/audience
WEX_NEW_PULSES_RESULTS = https://usstagingms.workforceexperience.hp.com/ui/view/pulses
PARTNER_FULLNAME2 = uswexautomationstagepartner stage
WEX_NEW_EE_DASHBOARD_OLD = https://usdevms-workforce.hppipeline.com/ui/employee-engagement/dashboard
WEX_NEW_EE_DASHBOARD_NEW = https://usstagingms.workforceexperience.hp.com/ui/view/analytics/dashboard/6777497d9088ff3bbfc86bab
WEX_NEW_EE_DASHBOARD_REPORT_NEW = https://usstagingms.workforceexperience.hp.com/ui/view/analytics/dashboard/6777497d9088ff3bbfc86bab
PULSE_ENTRAID_GROUP_VALUE = Engineering EU-STAGE SW_ORG
COMPANY_COUNTRY = India
# Groups
Groups_FILTERS_SERIAL_NUMBER_VALUE = 5CG8522PJK
Groups_FILTERS_DEVICE_NAME_VALUE = DESKTOP-KOLE2RH
Groups_FILTERS_MANUFACTURER_VALUE = HP
Groups_FILTERS_OPERATING_SYSTEM_VALUE = Microsoft Windows 10 Pro
Groups_FILTERS_DEVICE_MODEL_VALUE = HP ProBook 440 G5
WEX_ASSIGNMTN_LIST_POLICY_URL = https://usstagingms.workforceexperience.hp.com/ui/view/remediations/pc-policies
WEX_ASSIGNMTN_LIST_SCRIPTS_URL = https://usstagingms.workforceexperience.hp.com/ui/view/remediations/scripts/assignments

# ActiveCare Details
IOTDiscoveryURL = https://staging-discovery.hpdaas.com/v2/services
#orderAddNewCustomerTenantUS
ORDERS_NEW_AC_COMPANY = orderAddNewCustomerTenantUS.csv
#orderAddDeviceExistingTenantUS
ORDERS_EXISTING_AC_COMPANY = wepOrdersAddDeviceExistingTenantUS.csv
#Existing Device Order
EXISTING_DEVICE = startDateEndDateUS.csv
#OrdersLessThan255
ORDERS_LESS_THAN_255 = ORDERS_LESS_THAN_255.csv
#OrdersGreaterThan255
ORDERS_GREATER_THAN_255 = ORDERS_GREATER_THAN_255.csv
# IOT Device Enrollment JSON Tushar
IOT_ENROLL_DEVICE = IOTEnrollDevice.json
# ActiveCare Tenant Details
ACOnlyTenantName_US = DoNotDeleteActiveCareOnlyTenant
ACOnlyTenantName_US_TN_DISPLAY_ID = C-58NKwngR
ACPITenantName = DoNotDeleteACPITenantUS
ACOnlyTenantCPIN_US = fG4gWbQ4

#CRON job end points
hostURL = http://internal.usstaging.hpdaas.com
hostEnviroment = usstagingms
cronJobEndPointToProcessOrders=/services/carepack-service/internal/1.0/cronjob/process-new-orders
cronJobEndPointToCompleteOrders=/services/carepack-service/internal/1.0/cronjob/process-incomplete-orders
cronJobEndPointToMakeSNREntry=/services/ccc-snr/internal/1.0/snr
cronJobEndPointToDeleteSNREntry=/services/ccc-snr/internal/1.0/serialNo/

ACOnlyTenantCPIN_US = fG4gWbQ4

WPT_DEVICE_SERIALNUMBER= 9CG47702W7
USER_INVITE_FIRSTNAME=inviteuserfirst
USER_INVITE_LASTNAME=inviteuserlast
USER_INVITE_EMAIL=inviteusertest1@hpmsqa.mailinator.com
USER_RESEND_INVITE_EMAIL=pulsea1@hpmsqa.mailinator.com
WPT_SELECT_DOMAINS=gmail.com; workforceqa.ext.hp.com

#User Onboarding Details
TENANT_INIT = wex A

#Policy Group creation device serial number
Groups_Device_serial_number = 0001760HBN
Groups_Device_Inactive_serial_number = RcnXhfeHulC

#ActiveCare Users used in Device Transfer
ACTIVE_CARE_NAME_TENANT= DoNotDeleteActiveCareOnlyTenant
ACTIVE_CARE_PI_TENANT_ID= bc305f72-fd8e-43a7-b534-974daacc33a6
ACTIVE_CARE_NAME_TENANT_TN_DISPLAY_ID = C-58NKwngR
ACTIVE_CARE_NAME_TENANT_ID=4a748a2a-6191-4ef8-be5c-3282403c7a4f
ACTIVE_CARE_NAME_TENANT_CPIN=fG4gWbQ4
ACTIVE_CARE_PI_TENANT_CPIN= H5MUct4p
AC_PLUS_PI_NAME_TENANT=DoNotDeleteACPITenantUS
AC_PLUS_PI_NAME_TENANT_TN_DISPLAY_ID=C-QiB67ayD
AC_PLUS_PI_NAME_TENANT_CPIN=H5MUct4p
AC_PLUS_PI_NAME_TENANT_ID=bc305f72-fd8e-43a7-b534-974daacc33a6
INVALID_TENANT= InvalidTenantUS
INVALID_TENANT_TN_DISPLAY_ID = 101010

deviceReportLambdaEndPointUrl=https://internal-usstaging-api.hpdaas.com
ACOnlyTenantId_US = 4a748a2a-6191-4ef8-be5c-3282403c7a4f
optional-pc-refactor = PCE_CAMS_DATA
PlanId_RemoteCare = 8fc9e078-e8a8-4d39-b425-40d2d38ab41e
PlanId_ActiveCare = 61b196c4-3f37-435c-ad17-62b77744fd82