
WEX_SELFSIGNUP_COMPANY_NAME = wexocautostablecustomer
WEX_SELFSIGNUP_COMPANY_EMAIL = wexocautostablecustomer@yopmail.com
WEX_COUNTRY = India
WEX_COMPANY_FN = wexocautostable
WEX_COMPANY_LN = customer
WEX_COMPANY_ADDRESS = 123, xyz street
WEX_COMPANY_CITY = Hyderabad
WEX_COMPANY_ZIPCODE = 500081
WEX_COMPANY_STATE = Telangana
WEX_TIMEZONE = (GMT+05:30) Chennai
WEX_USER_FN = wexautouser
WEX_USER_LN = invite
WEX_USER_EMAIL = wexautouserinvite@yopmail.com
INVITED_USER_EMAIL_SUBJECT = invites you to the Workforce Experience Platform
WEX_USER_EMAIL_SEARCH = inviteuser12invitenpg@hpmsqa.mailinator
USER_FN = inviteuser12
USER_LN = invite
CUSTOMER_NAME = WEX Customer
COMPANY_FULLNAME = june25 compsso
COMPANY_NAME = june25compsso
PARTNER_FULLNAME = wex partner
CATALOG_COMPANY_NAME = Workforce Customer
PULSE_FILTERS_LASTLOGGED_FILTER_VALUE = HPAUTO10015@hp.com
PULSE_FILTERS_SERIAL_NUMBER_VALUE = HPAUTO10281
PULSE_FILTERS_FIELD_DEVICE_MANUFACTURER_VALUE = HP
PULSE_FILTERS_FIELD_OPERATING_SYSTEM_VALUE = Microsoft Windows 11 Enterprise
PULSE_FILTERS_FIELD_DEVICE_TYPE_VALUE = Desktop
PULSE_ENTRAID_GROUP_VALUE = Engineering Dev SW_ORG
IOTDiscoveryURL = https://dev-discovery.daas.hppipeline.com/v2/services
EntraID_GroupName = Automation testing pulse engg grp - dont delete the grp
Membership_Type = Entra ID
Operating_Systems = Windows, Mac
Selected_GroupName = Automation testing pulse engg grp - dont delete the grp
Selected_Member_Devices = 1
ImportedGroupName = Automation Testing Pulse
Device_Count_OverviewTab = 1
Device_Name_MembershipTab = DESKTOP-6G1OKB6
EntraID_ErrorMessage = Field is required
WEX_NEW_PULSES_CREATION_CONTENT = https://usdevms-workforce.hppipeline.com/ui/view/pulses/create/custompulse/content
WEX_NEW_PULSES_CREATION_SCHEDULE = https://usdevms-workforce.hppipeline.com/ui/view/pulses/create/custompulse/schedule
WEX_NEW_PULSES_CREATION_AUDIENCE = https://usdevms-workforce.hppipeline.com/ui/view/pulses/create/custompulse/audience

# IOT Device Enrollment JSON
IOT_ENROLL_DEVICE = IOTEnrollDevice.json

# Scripts enrollment data
SCRIPTS_COMPANY_NAME = Scripts Test QA Company
SCRIPTS_CPIN = Xctu33PH
SCRIPTS_COMPANY_EMAIL = scriptsqatenantstable@yopmail.com
SCRIPTS_SERIAL_NO = DYNGRPPRD2651
SCRIPTS_DEVICE_ID = qPSd31eas2cI3TRWoAr7TjX0kTr4q1DwUp0fvVKbYEv
SCRIPTS_TENANT_ID = 16be7827-44c1-438d-80a2-c0ef62a76718
ACOnlyTenantName_US = CUJTenantUSSTABLE01
ACOnlyTenantId_US = efb1d0f9-bf76-405f-ad75-1c5ff4618f19
optional-pc-refactor = PCE_DEVICE_CAMS_DATA

PlanId_RemoteCare = 33dafefa-4ae1-4590-9538-de432263e945
PlanId_ActiveCare = 386887ef-2775-4e73-9a71-4cf2e85895ca
#Groups
Groups_FILTERS_MANUFACTURER_VALUE = HP
Groups_FILTERS_OPERATING_SYSTEM_VALUE = Microsoft Windows 10 Pro
Groups_FILTERS_DEVICE_MODEL_VALUE = HP ProBook 440 G5
WEX_ASSIGNMTN_LIST_POLICY_URL = https://usdevms-workforce.hppipeline.com/ui/view/remediations/pc-policies
WEX_ASSIGNMTN_LIST_SCRIPTS_URL = https://usdevms-workforce.hppipeline.com/ui/view/remediations/scripts/assignments

#CRON job end points
deviceReportLambdaEndPointUrl=https://internal-api.usdev.daas.hppipeline.com
hostURL=http://internal.usdev.daas.hppipeline.com
hostEnviroment=usdevms


ACTIVE_CARE_PI_TENANT_CPIN = nvc5EAQ8

INVALID_TENANT= InvalidTenantEU

