userTitleOnDetailsPage = [xpath]://*[contains(@class,"app-bar-breadcrumbs")]//span
userTitleOnBreadcrumbs = [xpath]://*[@id="userDetails"]//li[2]
breadcrumbLink = [css]:#userDetails a
breadcrumbText = [xpath]://*[@id="userDetails"]//li[2]
toastNotification = [xpath]://*[@role="alert"]
tableOverlay=[xpath]:(//*[contains(@class,'react-loading-skeleton')])[1]
removeButton = [xpath]://*[@class='dui-dsummary-card-buttons']//button
nextButton = [css]:#btn_next
cancelButton = [css]:#btn_cancel
editNameCompanyUsers = [id]:edit-company-name
editNamePartnerUsers = [id]:edit__displayName

#details tile
detailsTitle = [xpath]://*[@id='dui-tab-panel-0-0']//*[@class="dui-dpanel-header"]
nameLabel = [css]:#namePanel div.dui-depr-label
nameEdit = [xpath]://*[@id='namePanel']//*[contains(@class,'dui-epr-edit')]
nameValue = [css]:#namePanel  span
emailLabel = [css]:#emailPanel div.dui-depr-label
emailValue = [css]:#emailPanel span
mobilePhoneLabel = [css]:#mobilePanel div.dui-depr-label
mobilePhoneValue = [css]:#mobilePanel span
companyLabel = [css]:#companyName div.dui-depr-label
companyValue = [css]:#companyName span
officePhoneLabel = [css]:#officePanel div.dui-depr-label
officePhoneValue = [css]:#officePanel span
jobTitleLabel = [css]:#jobTitlePanel div.dui-depr-label
jobTitleValue = [css]:#jobTitlePanel span
jobTitleEdit = [xpath]://*[@id="jobTitlePanel"]//*[@name="IconPencil"]
titleModelHeader = [xpath]://*[@id="jobTitle-modal-label"]
jobTitleTextKey = [css]:#jobTitle-modal-desc input
cancelButtonOnPopup = [css]:#editCancelBtn
SaveButtonOnPopup = [css]:#editSaveBtn
addressLabel = [css]:#addressPanel div.dui-depr-label
addressValue = [css]:#addressPanel span
languageLabel = [css]:#languagePanel div.dui-depr-label
languageValue = [css]:#languagePanel span
languageEditButton = [xpath]://*[@id="languagePanel"]//*[@name="IconPencil"]
languageModelHeader = [xpath]://*[@id="language-modal-label"]
selectArrowKey = [xpath]:(//*[contains(@class,"vn-select__open-button")])[1]
selectLanguage = [xpath]://*[@id="edit_modal_undefined-listbox"]//li[8]
dialogueBox = [xpath]:(//*[@aria-describedby="language-modal-desc"])[2]
userDetailsPageSpinner = [xpath]://div[@class='dui-page-spinner']//*[name()='svg']
#identity tile
userNameIdentity = [xpath]:(//*[@id="dui-container"]//div[@aria-controls='dui-dsummary-card']//span)[1]
userEmailIdentity = [xpath]://span[@title='Email Address']/..//following-sibling::div//span
userPhoneIdentity = [xpath]://span[@title='Office Phone']/..//following-sibling::div
userAccountLabel = [xpath]://span[@title='Account Type']
userAccountType = [xpath]://span[@title='Account Type']/..//following-sibling::div
userStatusType = [xpath]://*[@class='dui-icon-label']
#Roles tile
userRoleTitle = [xpath]:(//*[@class="dui-depr-label"])[5]
userRoleAssignmentDescription = [xpath]://*[@class='dui-panel-warning']
userRoleLabel = [xpath]://*[@id="rolesPanel"]//div[contains(@class,'dui-epr-label')]
userRoleValue = [xpath]://*[@id="rolesPanel"]//span
userRoleEditButton = [xpath]://div[contains(@id,'accountAndRoles')]//div[contains(@class,'edit-icon')][2]
userRoleEditButtonThroughRoot = [xpath]://div[contains(@id,'accountAndRoles')]//div[contains(@class,'edit-icon')][1]
roleCancelButtonOnPopup = [css]:#rolesCancelBtn
roleSaveButtonOnPopup =  [xpath]:(//button[@id='rolesSaveBtn'])[2]
roleModelPopupTitle = [xpath]://*[@id="rolesModal-label"]
usersDeviceTab = [xpath]://*[@id="usersDetailsDevicesPanel"]
userAccountsTitle = [xpath]://*[@id='dui-accountAndRoles']/div/div//div[@class='dui-dpanel-header']

#Users Devices tile
usersDeviceTileHeaderMessage = [xpath]://*[@id="dui-user-device-list"]//div[@class='dui-dpanel-header']
usersDeviceSerialNumber = [xpath]://*[@id="serialNumber"]//button
usersDeviceName = [xpath]://*[@id="name"]//button
usersDeviceType = [xpath]://*[@id="deviceType"]//button
usersDeviceApplicationEnrolled = [xpath]://*[@id="deviceClientApplicationName"]//button
usersDeviceLastActivity = [xpath]://*[@id="status"]//button
usersDeviceNameLinkKey = [xpath]://*[@id="dui-user-device-list"]//div/table/tbody/tr[1]/td[2]//a
userAssignedDevices = [xpath]://*[@id="dui-user-device-list"]//a
userDevicesStatus = [xpath]://*[@id="dui-user-device-list"]//tr//td[6]
deviceNameVerificationOnDetailsPageKey = [xpath]://*[@id="device-serial"]/div[2]
userManageCompanyHeader = [xpath]:(//*[@id="global-filter"]//span)[2]
companyImpersonateMatching = [xpath]://*[contains(@class,'dui-dsummary-card')]//span
totalDevicesOnAssignedDevicesTile = [xpath]://*[@aria-label="Select page size"]/following-sibling::span
companyNameOnDetailsPage = [xpath]://*[@class='dui-panel-link link']

itAdminLabel = [xpath]://*[@id="it_admin"]/label/span[2]
appAdminLabel = [xpath]://*[@id="sw_admin"]/label/span[2]
hwAdminLabel = [xpath]://*[@id="hw_admin"]/label/span[2]
ldAdminLabel = [xpath]://*[@id="ldp_admin"]/label/span[2]
reportAdminLabel = [xpath]://*[@id="reports_admin"]/label/span[2]
userLabel = [xpath]://*[@id="employee"]/label/span[2]
seviceNowAdminLabel = [xpath]://*[@id="servicenow_admin"]/label/span[2]
workflowAdminLabel = [xpath]://*[@id="workflow_admin"]/label/span[2]

msTelementryLabel = [xpath]://*[@id="ms_telemetry"]/label/span[2]
customerEngineerLabel = [xpath]://*[@id="customer_engineer"]/label/span[2]
itManagerLabel = [xpath]://*[@id="it_manager"]/label/span[2]
emmAdminLabel = [xpath]://*[@id="emm_admin"]/label/span[2]
listOfCheckboxRoleOnPopup = [xpath]://*[@class="list-item-wrapper"]//label
selectedCheckBoxesOnPopup = [css]:span.vn-checkbox__span
columnCheckboxesOnPopup = [css]:label input

#Overview tab
mobileEditButton = [css]:#mobilePanel svg
mobileTextBox = [css]:input[name=edit_modal_mobilePhone]
officeEditButton = [css]:#officePanel svg
officeTextBox = [css]:input[name=edit_modal_officePhone]

#EMM Admin Role
daasrolescheck = [xpath]: //input[@aria-checked='true']
emmAdminRole = [xpath]://*[@id="emm_admin"]//span[2]
emmAdminRoleDescription = [css]:#emm_admin div 
emmAdminRoleCheckbox = [css]:#emm_admin span.vn-checkbox__span 
EMMTooltab = [css]:#menu_emmToggle
chromeEnterpriseTab = [css]: #menu_chrome div:nth-child(2)
help&SupportTab = [css]:#menu_support div:nth-child(2)	
settingsTab = [css]:#menu_settings div:nth-child(2)
daasRoleLabels = [xpath]://*[@id="user_roles_container"]//*[@class='row-fluid']//label//input
daasUserRoleCheck = [xpath]://*[@id="dom_user_roles"]/label/a
chromeNotConfiguredString = [xpath]://*[@id='chrome-book-row']//span
emmNotConfiguredString = [css]:#chrome-book-row span
airwatchTab = [css]:#menu_airwatch
intuneEditButton=[css]:#edit-company-intune-settings
intuneTab = [css]:#menu_intune
officeEditBox = [css]:#edit_modal_officePhone

#impersonation
impersonatedText = [xpath]://a[contains(@class,'pointer')]/..
impersonatedLink = [css]:a[class*=pointer]
impersonateIcon = [xpath]://*[@class='dui-dsummary-card-buttons']//button
impersonationPopupTitle = [xpath]://*[div/@id="impersonate-user-confirmation"]//preceding-sibling::h4
impersonationPopupConfirmationText = [css]:#impersonate-user-confirmation p
impersonationSubmit = [id]:impersonate-modal-submit
impersonationCancel = [id]:impersonate-modal-cancel

searchRole = [xpath]://*[contains(@class,"search-attached")]//input[@type="search"]
listOfRoles = [xpath]://*[contains(@class,"roles-list")]//span[1]

#Account tile changes
roleHeader = [xpath]:(//*[@id="dui-accountAndRoles"]//div[contains(@class,"header")])[1]
roleMessage = [xpath]://*[@id='dui-accountAndRoles']//div[contains(@class,'panel-warning')]
roleLabel = [xpath]://*[@id='dui-accountAndRoles']//div[contains(@class,'dpanel-header')]
roleButton = [xpath]:(//*[@id="dui-accountAndRoles"]//*[contains(@class,"icon-button")])[2]
rolePopupHeader = [xpath]:(//*[@id='rolesModal-label'])[2]
rolesSave  = [xpath]:(//*[@id='rolesSaveBtn'])[2]
rolesCancel  = [xpath]:(//*[@id='rolesCancelBtn'])[2]
roleValue = [xpath]://*[@id="dui-accountAndRoles"]//div[contains(@class,"epr-label")]
toastNotificationAccountTile = [xpath]:(//div[@role='alert']//span)[1]

#preferredlanguagedropdown
danskLanguage = [xpath]://*[@id="edit_modal_undefined-listbox"]//li[1]
deutschLanguage = [xpath]://*[@id="edit_modal_undefined-listbox"]//li[2]
englishLanguage = [xpath]://*[@id="edit_modal_undefined-listbox"]//li[3]
espanolLanguage = [xpath]://*[@id="edit_modal_undefined-listbox"]//li[4]
suomalainenLanguage = [xpath]://*[@id="edit_modal_undefined-listbox"]//li[5]
francaisLanguage = [xpath]://*[@id="edit_modal_undefined-listbox"]//li[6]
italianoLanguage = [xpath]://*[@id="edit_modal_undefined-listbox"]//li[7]
norskLanguage = [xpath]://*[@id="edit_modal_undefined-listbox"]//li[9]
portuguesLanguage = [xpath]://*[@id="edit_modal_undefined-listbox"]//li[12]

#RPL Feature related locators
complianceStatusValue = [xpath]://div[@id='complianceStatus']//span
btnComplianceEdit =  [xpath]: //div[contains(@id,'compliance')]//div[@class='dui-icon dui-icon-button']
lstComplianceValues = [xpath]: //ul[@id='edit_modal_undefined-listbox']//li
dropDownCompliance =  [xpath]: //div[@id='edit_modal_undefined']
txtComplianceStatusOnTile = [xpath]:(//div[@id='dui-summary-card']//div[contains(@class,'inline')])[6]
btnDropDownArrow = [xpath]: //div[@id='edit_modal_undefined']/following-sibling::span//div
txtMsgStatusUpdate = [xpath]: //button[@aria-label ='CLOSE']/preceding-sibling::div/span
txtComplianceStatus = [xpath]:  (//div[@id='compliance-status-row']/div)[1]

loadingSpinner = [xpath]://*[@role='progressbar']
userProfiles = [xpath]://div[@data-testid='wex_menu_item_users_profile' and @id="user-profile"]
userProfilesTimeZone = [xpath]://*[@id="TimezonePanel"]
editTimeZone = [xpath]://*[@id="edit-TimezonePanel"]
timeZoneValue = [xpath]://input[@id='timezone-select']
editDateValue = [xpath]://*[@id="edit-date-time-format"]
editDateValueDrpDwn = [xpath]:(//*[@id="dateFormat-modal-desc"]//span)[2]
firstDateVal = [xpath]://*[@id="edit_modal_undefined-option-0"]/div/span
lastDateVal = [xpath]: //*[@id="edit_modal_undefined-option-1"]/div/span
editCancelBtn = [xpath]: //*[@id="editCancelBtn"]
timeZoneToggleInput = [id]:system-timezone
timeZoneToggleVisual = [xpath]:(//input[@id='system-timezone']/following::span)[1] 
timeZoneCancelBtn = [xpath]:(//input[@id='system-timezone']/following::span[contains(text(),'Cancel')])[1]
timeZoneEnabled = [id]:timezone-select
