userTab = [id]:menu_users
listTableRowCount = [xpath]://*[@id="dui-pagination"]//a//span
listTablerowsCountOptions= [xpath]://*[@id="dui-pagination"]//*[contains(@class,'vn-option')]//*[contains(@role,'option')]
listTablerowsCountOptions100= [xpath]://*[@id="dui-pagination"]//*[contains(@class,'vn-option')]//*[contains(@role,'option')][3]
listTablerowsCountOptions500= [xpath]://*[@id="dui-pagination"]//*[contains(@class,'vn-option')]//*[contains(@role,'option')][4]
appUsersTab = [id]:menu_appUsers
orderTab = [id]:menu_orders
userName = [xpath]://*[@id="users_list"]/tbody/tr/td[2]/a/div/p[1]
changePicture = [id]:change_avatar_desktop
changeAvatar = [xpath]://input[@id='user_avatar']
confirmUpload = [id]:yes
imageId = [xpath]://img[@id='avatar_image']
firstName = [xpath]://strong[@id='user_first_name_show']
lastName = [xpath]://strong[@id='user_last_name_show']
activeUserEmail = [xpath]://strong[@id='user_email_show']
addLine1 = [xpath]://strong[@id='user_address_street_line1_show']
addLine2 = [xpath]://strong[@id='user_address_street_line2_show']
country = [xpath]://strong[@id='user_address_country_show']
state = [xpath]://strong[@id='user_address_state_show']
city = [xpath]://strong[@id='user_address_city_show']
zip = [xpath]://strong[@id='user_address_postal_code_show']
countryDropDown = [xpath]://select[@id='address_country']
firstNameInput = [xpath]://input[@id='user_first_name']
lastNameInput = [xpath]://input[@id='user_last_name']
addLine1Input = [xpath]://input[@id='address_street_line1']
addLine2Input = [xpath]://input[@id='address_street_line2']
stateInput = [xpath]://input[@id='address_state']
cityInput = [xpath]://input[@id='address_city']
zipInput = [xpath]://input[@id='address_postal_code']
save = [xpath]://button[@id='save_user_profile']
edit = [xpath]://button[@id='edit_user_profile']
officePhoneInput = [xpath]://input[@id='user_telephone']
officePhoneStrong = [xpath]://strong[@id='user_telephone_show']
officePhoneError = [xpath]://p//input[@id='user_telephone']/following-sibling::label[@class='error']
mobilePhoneInput = [xpath]://input[@id='user_mobile']
mobilePhoneStrong = [xpath]://strong[@id='user_mobile_show']
mobilePhoneError = [xpath]://p//input[@id='user_mobile']/following-sibling::label[@class='error']
notificationSuccess = [xpath]://div[@class='notification success']
invisibleElement = [xpath]://strong[@class='empty'][1]
selectLanguage = [xpath]://select[@id='preferred_language']
editProfileLink = [xpath]://a[@id=edit_user_profile]
inactiveUser = [xpath]://table[@id='users_list']/tbody/tr[1]/td[2]//a
titleInput = [xpath]://input[@id='user_title']
title = [xpath]://strong[@id='user_title_show']
communicationPreferencesEdit = [xpath]://button[@id='edit_communication_preferences']
communicationPreferencesCheckBox = [xpath]://input[@id='user_settings_marketing_communications']
addUser = [xpath]://a[@id='add']
addManually = [xpath]://button[@id='manually_button']
addUserCheckBox = [xpath]://table[@id='users_list']//tbody/tr/td/input
addUserName = [xpath]://table[@id='users_list']//tbody/tr//td[2]/label[1]/input
submit = [xpath]://div[@id='purchase']//button
downloadPin = [xpath]://button[@id='download_pins_button']
inactiveEmailUser= [xpath]://a//p[text()='aaaaaaaaaaaaa']
userEmail = [xpath]://input[@id='user_email']
removeUser = [xpath]://button[@id='delete_user_desktop']
removeUser1 = [xpath]://button[@id='delete']
emailStrong = [xpath]://strong/a[@id='user_mail_show']
emailNotificationCheckbox = [id]:receive_incident_notifications
editIncidentNotificationsButton = [id]:edit_incident_notifications
saveIncidentNotificationsButton = [id]:save_incident_notifications
companyNameShow = [id]:user_company_name_show
inactiveEmail = [xpath]://input[@placeholder='E-mail']
serchBox = [xpath]://input[@id='users_list_search']
listTable = [css]:table[class*=table]
nameHeader = [css]:#col-id-name
#emm admin role
editUserRole = [xpath]://*[@id="edit_user_role"]
addRole = [xpath]://*[@id="add_role"]
roleSaveButton = [id]:save_button
roleNotifiactionPopup = [xpath]://*[@id="notification_area"]/div[2]
roleNotificationMessage = [xpath]://*[@id="notification_area"]/div[2]/p
userNameHeading = [xpath]://*[@id="users_list"]/tbody/tr/td[2]/a/div/p[1] 
userEmailHeading = [xpath]://*[@id='users_list']/tbody/tr/td[2]/a/div/p[2]
menuIcon = [css]:#toggle_side_menu
userTab = [id]:menu_users
scrollRoleAssignment = [xpath]://*[@id="user_roles_section"]
daasrolescheck = [xpath]://*[@id="dom_user_roles"]/label
#Daas User roles
emmAdminRole = [xpath]://*[@id="user_roles_container"]/div[5]/div[2]/label/h5
emmAdminRoleDescription = [xpath]://*[@id="user_roles_container"]/div[5]/div[2]/div
userSearchlist = [id]:users_list_search
#EMM Admin login
settingsTab = [id]:menu_settings
EMMTooltab = [id]:menu_emmTools
help&SupportTab = [id]:menu_support
emmToolTabMessage = [xpath]://*[@id="lighthouse-wrapper"]//*[@class='select-content']
daasRoleLabels = [xpath]://*[@id="user_roles_container"]//*[@class='row-fluid']//label//input
daasUserRoleCheck = [xpath]://*[@id="dom_user_roles"]/label/a
roleWindow = [xpath]://*[@id="show_roles_modal_window"]/div
#Workflow
workflowAdminRole = [xpath]://*[@id="user_roles_container"]/div[3]/div/label/h5

#table configuration
tableConfigurationButton = [xpath]:.//div[@class='vn-tableconfiguration']//*[@type='button']
tableConfigurationTitle = [css]:div.vn-modal__header>h4
clearfilter=[xpath]://button[@title='Clear']

titleSortArrow = [xpath]://table//thead//tr[1]//th[13]
createdBySortArrow = [xpath]://table//thead//tr[1]//th[14]
deviceModelNameSortArrow =[xpath]://table//thead//tr[1]//th[16]
updatedOnSortArrow = [xpath]://table//thead//tr[1]//th[15]
navigationItemNext = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()]/*[contains(@class,'navigation-item')]
firstPageNavigation = [css]:div.vn-table__pagination ul.vn-pagination__navigation li:nth-of-type(2) a
paginationArea = [css]:div.vn-pagination div.vn-pagination__information
tableOverlay=[xpath]://div[@class='vn-table__overlay']
recordCountOnListPage = [xpath]: //td[@headers='col-id-name']
tableOverlaySiteUp = [xpath]://div[contains(@class,'dui-tl')]//div[contains(@class,'table__overlay') and not (contains(@class,'loading')) and not (contains(@class,'spinner'))]


#pagination
paginationOptionAvailable = [xpath]://div[@id="dui-pagination"]//ul//li[@class="vn-menu__item"][1] 
showingText = [xpath]://span[@class='vn-pagination__information__showing']
paginationDropdownMenu = [xpath]://div[contains(@class,'pagination')]//a[@role='button']
paginationDropdownOptionList = [xpath]://*[@id="dui-pagination"]//div[contains(@class,'options-list')]//div[@role='option']
showingPaginationTotalCount = [xpath]://div[contains(@class,'pagination')]//a[@role='button']/span

navigationItemDiv = [xpath]://*[@class='vn-pagination__navigation']
navigationItemList = [xpath]://*[@class='vn-pagination__navigation']//li
navigationItemNext = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()]/*[contains(@class,'navigation-item')]
navigationItemPrevious = [xpath]:(//*[@class='vn-pagination__navigation']//li)[1]/*[contains(@class,'navigation-item')]
navigationItemFrist = [xpath]:(//*[@class='vn-pagination__navigation']//li)[2]
navigationItemLast = [xpath]:(//*[@class='vn-pagination__navigation']//li)[last()-1]
navigationItemDisabled = [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'disabled')]
navigationItemActivePage =  [xpath]://*[@class='vn-pagination__navigation']//li//*[contains(@class,'page--active')]

noUserDisplayText = [css]:td[class*='no-items']
clearAllFilterField = [css]:button[title=Clear] svg
noElementsDisplayTextForComboBoxColumn = [xpath]://div[@class="vn-select-content__no-results"]

#hamburger Remove and details
hamburgerIcon = [xpath]://button[contains(@class,'tablecell__menu-button-dropdown-icon')]
hamburgerRemove = [xpath]://div[contains(@data-value,'Delete')]
hamburgerPopupRemove = [xpath]://*[@id="modal-submit"]
hamburgerDetails = [xpath]://div[contains(@class,'option')]//div[contains(@data-value,'Details')]//a
selectCheckbox = [xpath]://*[@id="dui-app-scroll"]//div[contains(@class,'tablerowselector__avatar')]
selectAllCheckBox = [xpath]://input[@name='SelectAllPage']
RemovePopupMessageHeader = [xpath]://*[@id="dui-remove-user"]/h4
RemovePopupMessageConfirmation = [xpath]://*[@id="dui-remove-user"]/div[1]/p[1]
RemovePopupMessage = [xpath]://*[@id="dui-remove-user"]//div//p[2]
cancelButtonOnPopup = [xpath]://*[@id="modal-cancel"]
removeButtonOnPopup = [xpath]://*[@id="modal-submit"]


#UserListPage
userListRowAllValueKey = [xpath]://tbody//tr[1]//td
firstRowUser = [css]:td[headers=col-id-name] a
firstRowUserEmail = [css]:tr:first-child td[headers*=col-id-email]>div div[class*=content]
noItemsDisplayText = [css]:td[class*='no-items']

#Name
userNameSearchBox = [id]:users-name
userNameSearchList = [css]:td[headers*=col-id-name]

#Email		
userEmailSearchBox = [id]:users-email
userEmailSearchList = [css]:td[headers*=col-id-email]

#Roles
userRolesBox = [id]:users-roles
userRolesBoxTitle= [id]:col-id-roles
userRolesList= [css]:td[headers*=col-id-roles]
dropdownRolesCheckboxes = [css]:#users-roles button:nth-of-type(1) svg
dropdownRolesElementListLabels = [xpath]://*[@id="select-users-roles"]//a
clearRolesField = [css]:#users-roles button:nth-of-type(1)

#company column
userCompanyBox = [id]:users-company
companyBoxTitle = [id]:col-id-company
companySearchBox = [css]:#users-company div.vn-select-content__search input
companyBoxBefore = [css]:#users-company button:nth-of-type(1) svg
clearCompanyField = [css]:#users-company button:nth-of-type(1)
companyList = [css]:td[headers*=col-id-company]
companyListLink = [xpath]://*[@headers="col-id-companyName"]//div//a
companyBoxAfter = [css]:#users-company div.vn-select__button-group>button:nth-of-type(2)
companyListOnPopup = [css]:#users-company div[class*='options-list'] div[class*='option__multiple']
dropdownCheckboxes = [css]:div[class*='select'] div[class*='options-list'] div[class*='option']:nth-of-type(1) a
userCompanyResult= [css]:#select-users-company div[class*=options-list] a
#Status
userStatusBox = [xpath]://*[@id="users-status"]
StatusBoxTitle = [id]:col-id-status
userStatusList= [css]:td[headers*=col-id-status]
dropdownStatusCheckboxes = [css]:#users-status button:nth-of-type(1) svg
dropdownStatusElementListLabels = [xpath]://*[@id="select-users-status"]//a
clearStatusField = [css]:#users-status button:nth-of-type(1)

#Number Of Devices
numberOfDevicesBox = [xpath]://*[@id="users-devicesCount"]
numberOfDevicesBoxTitle = [id]:col-id-devicesCount
numberOfDevicesList= [css]:td[headers*=col-id-devicesCount]
dropdownNumberOfDevicesCheckboxes = [css]:#users-devicesCount button:nth-of-type(1) svg
dropdownNumberOfDevicesElementListLabels = [xpath]://*[@id="select-users-devicesCount"]//a
clearNumberOfDevicesField = [css]:#users-devicesCount button:nth-of-type(1)
numberOfDevicesCount = [css]:td[headers=col-id-devicesCount] div

#MobilePhone		
userMobilePhoneSearchBox = [id]:users-mobilePhone
userMobilePhoneSearchList = [css]:td[headers*=col-id-mobilePhone]

#OfficePhone		
userOfficePhoneSearchBox = [id]:users-officePhone
userOfficePhoneSearchList = [css]:td[headers*=col-id-officePhone]

#Title		
userTitleSearchBox = [id]:users-title
userTitleSearchList = [css]:td[headers*=col-id-title]

#Address		
userAddressSearchBox = [id]:users-address
userAddressSearchList = [css]:td[headers*=col-id-address]

#Language
userLanguageSearchBox = [id]:users-language
userLanguageSearchList = [css]:td[headers*=col-id-language]

userTabWorkflow = [css]:#menu_workflowUserManagement a
daasRoleLabels = [xpath]://div[@class="vn-scrollbar roles-list"]//div/label/span[2]

#notifications
notificationCount = [xpath]://*[contains(@class,'bell-button')]//div/div[2]
notificationBellIcon = [xpath]://*[contains(@class,'bell-button')]//div/button
notificationMassageTile = [xpath]:(//*[contains(@class,'notification-center-item')])[1]
notificationDismissIcon	= [xpath]:((//*[contains(@class,'notification-center-item')])//button)[1]
unreadNotification = [xpath]:(//*[contains(@class,'notification-center__panel')]/div[1][not(contains(@class,'read'))])[1]
unreadNotificationText = [xpath]:(//*[contains(@class,'notification-center__panel')]/div[1][not(contains(@class,'read'))])[1]//div[2]//div[2]
unreadNotificationHyperLink = [xpath]:(//*[contains(@class,'notification-center__panel')]/div[1][not(contains(@class,'read'))])[1]//div[2]//div[3]/a
notificationFirst = [xpath]://*[contains(@class,'notification-center__panel')]/div[1]
openLogsHyperlink = [xpath]://*[contains(@class,'notification-center__panel')]//div[1]//div[contains(@class,'extra')]//a[contains(@href,'logs')]

#Add manually
addButton = [id]:btn_user_add
dropDownArrow = [xpath]://*[@id='add-users-company-filter']//div//button//*[name()='svg']
searchBox = [xpath]://input[@id= 'search']
listOfElements = [xpath]://*[@id='add-users-company-filter']//a
dropDownBox = [xpath]://*[@id='add-users-company-filter']//div/div[1]
nextButton = [id]:btn_next
nextButtonAddUserMethod = [xpath]://*[@id= 'btn_prev']/following-sibling::button
cancelButton = [id]:btn_cancel
previousButton = [xpath]://*[contains(@class, 'row dui-padding-top-40 text-right')]//button[1]
addUserPopUpTitle = [xpath]://*[contains(@class, 'dui-user-add')]//h4
chooseCompanyLabel = [xpath]://*[contains(@class, 'dui-user-add')]//h5
addUsersTextCheck = [xpath]:(//*[contains(@class,'dui-user-add')]//div//h5)[1]
noCompanyPresent = [xpath]://*[contains(@class,'no-results')]
addManualButton = [xpath]:(//*[@id= 'dui-icon-card']//*[contains(@class, 'dui-border dui-align-center')])[1]
addAnother = [id]:add_new_user
firstNameBox = [xpath]://input[contains(@id,'new_user_first_name')]
lastNameBox = [xpath]://input[contains(@id,'new_user_last_name')]
emailBox = [xpath]://input[contains(@id,'new_user_email')]
roleBox = [xpath]://div[contains(@id,'key__new_user_role')]/div/div/div[1]
dropdownArrowRole = [xpath]://div[contains(@id,'key__new_user_role')]/div/div/div[1]
roleDropdownList = [xpath]://div[contains(@id,'key__new_user_role')]//div//a
submitButton = [id]:btn_submit
cancelButton = [id]:btn_cancel
toastNotification = [xpath]://*[contains(@class,'toast-enter-done')]//p
emailSearchBox = [id]:users-email
emailListValues = [css]:td[headers*="id-email"]
nameListValues = [css]:td[headers*="id-name"]
roleListValues = [css]:td[headers*="id-roles"]
statusListValues = [css]:td[headers*="id-status"]
selectAllCheckBox = [xpath]://*[@name="SelectAllPage"]
removeButtonListPage = [id]:btn_user_remove
removeButtonModal = [id]:modal-submit
noElementsDisplayText = [css]:td[class*="no-items"]
resendInvitationButton = [id]:btn_resend_invitation
resendModalButton = [id]:modal-submit
manuallyText = [xpath]://*[@id='btn_add_manual']//ancestor::div[2]//h5
manuallyUnderText = [xpath]://*[@id='btn_add_manual']//ancestor::div[2]//p[2]
importText = [xpath]://*[@id='btn_add_import']//ancestor::div[2]//h5
importUnderText = [xpath]://*[@id='btn_add_import']//ancestor::div[2]//p[2]
goBackPreviousLink = [xpath]://*[contains(@class,'dui-color-blue')]
notifyUserByEmail = [xpath]://*[@id='notify_by_mail']//ancestor::label/span[1]
lastCompanyOnDropdown = [css]:#add-users-company-filter div[role=option]:last-child
nextButtonManually = [xpath]://*[contains(@class, 'row dui-padding-top-40 text-right')]//button[2]

#Azure Import
userNameAzure = [xpath]://*[@name='loginfmt']
passwordAzure = [xpath]://*[@name='passwd']
nextButtonAzure = [id]:idSIButton9
importAzure = [xpath]://*[@id="add-azure"]
importAzureSync = [id]:btn_azure_sync
azureModalText = [xpath]://*[@class='azure-add-modal']//h5
azureIconText = [xpath]://*[@class='azure-add-modal']//p[2]/div[2]
checkBoxAzure = [id]:KmsiCheckboxField
backButtonAzure = [id]:idBtn_Back

#Import Multiple
importMulitipleButton = [xpath]://*[@id="add-import"]
importModalText = [id]://*[@class='dui-user-add']//div//h5
uploadButton = [id]:btn_import
cancelButton = [id]:btn_cancel
browseButton = [xpath]://*[@id='uploadUserList_container']//button
sampleDownload = [id]:download-sample
fileImport = [css]:#uploadUserList_container input
 
#Search Service of Users tab
administrativeTab = [xpath]://*[@id="menu_administrator"]/a/div[2]
usersTab = [xpath]://*[@id="menu_rootUsers"]/a/div[2]
mspsTab = [xpath]://*[@id="menu_msp"]/a/div[2]
mspsUsersTab = [xpath]://*[@id="menu_mspList"]/a/div[2]
partnersTab = [xpath]://*[@id="menu_partners"]/a/div[2]
partnersUsersTab = [xpath]://*[@id="menu_partnerUsers"]/a/div[2]
customersTab = [xpath]://*[@id="menu_partnerCompanies"]/a/div[2]
customersUserTab = [xpath]://*[@id="menu_customerUsers"]/a/div[2]

#Administrator Page
administratorTab = [id]:menu_administrator
userRootTab = [id]:menu_rootUsers
settingsRootTab=[id]:menu_rootSettings

#Admin User
addNewUserButton = [id]:btn_company_add
addUserlabel= [xpath]://*[@id="dui-container"]//h4
addFirstName= [id]:first-name
addLastName= [id]:last-name
addEmailAddress=[id]:email-address
addUserButton = [id]:btn_next
userMenuList= [xpath]://*[@id="dui-container"]//a/button
userFirstRow= [xpath]://*[@id="dui-container"]//tr[1]/td[3]//a
userRemoveBtn=  [xpath]://*[@id="btn_company_remove"]
userConfirmRemoveBtn= [id]:btn_next
userSearchText= [xpath]://*[@id="dui-container"]//td
addFirstNameErrorMsg= [xpath]://div[@class='col-md-12']//div[1]//*[@class='vn-form-field__error-message']
addLastNameErrorMsg= [xpath]://div[@class='col-md-12']//div[2]//*[@class='vn-form-field__error-message']
addEmailNameErrorMsg= [xpath]://div[@class='col-md-12']//div[3]//*[@class='vn-form-field__error-message']
userTitle =[css]:#usersList h4
userTitleOnBreadcrumbs = [css]:#usersList li
removeAllSearchFilters = [css]:button[title='Clear']

#Admin Email		
adminUserEmailSearchBox = [xpath]://*[@id="partners-email"]
userEmailSearchTextList = [css]:td[headers*=col-id-email] div[class*='tablecell__content']
userEmailSearchRow = [xpath]://*[@id="dui-container"]//table/tbody
userEmailSearchValue = [xpath]: //*[@id="dui-container"]//td[4]/div
userNameSearchValue = [xpath]://*[@id="dui-container"]//table/tbody//a
userEmptySearchResult = [css]:table>tbody td[class*='tablecell--no-items']
userRoleSearchList= [css]: td[headers*=col-id-roles] div[class*='tablecell__content']

#Admin Subscription Management tab
subscriptionManagementTab= [xpath]://*[@id="menu_subscriptionManagement"]/a/div[2]
adminPortalLabel= [xpath]://*[@id="new_user"]/div[2]/h2

#User Detail Page 
nameSearchBox = [id]:partners-name
userDetailsTitle = [css]:#userDetails h4
mspEmailTextbox = [css]:#users-email
firstUser= [css]:td[headers=col-id-name] a
mspUserLink = [css]:div[class*=primary-data] span
companyEmailTextBox = [css]:#companies-primaryAccountEmail
companyUserLink = [css]:#dui-container [class*=dui-link]
emailTextbox = [id]:users-email
firstIdName = [css]:td[headers*=name] a
firstIdRole = [css]:tbody tr:nth-child(1) td:nth-child(5) div[class*="tablecell__content"]

#Flip
numberOfLdpAdmin =[xpath]: //tbody/tr//td//div[@title="Lost Device Admin"]
lockAndEraseApprovalStatus=[xpath]: //tbody/tr[1]//td[6]//div[contains(@class,'tablecell__content')]
userCheckbox= [xpath]: //tbody[@class='vn-table-body vn-table-body__scrollable']//tr[1]/td//label[@class='vn-checkbox__label']
tableRowSelector=[xpath]: //tbody/tr[1]//td//div[@class='vn-tablerowselector__avatar'][1]
remindApproverToEnrollButton = [xpath]://button[@id='btn_remind_approvers']
remindApproverText =[xpath]: //div[@id='dui-remind-approvers']/h4
invitationToEnrollText=[xpath]: //div[@id='dui-remind-approvers']//p
cancelPopUpButton=[xpath]: //button[@id='modal-cancel']
savePopupButton =[xpath]: //button[@id='modal-submit']
toastNotification =[xpath]: //div[@id="dui-app-scroll"]/div[4]//p