userTitleOnDetailsPage = [css]:h4[class*=title]
userTitleOnBreadcrumbs = [xpath]://*[@id="dui-breadcrumbs"]/li[2]
breadcrumbLink = [css]:#dui-breadcrumbs a
breadcrumbText = [css]:#dui-breadcrumbs li[class*=item]:nth-of-type(2)
toastNotification = [xpath]://div[contains(@class,'toast-enter-done')]//p
tableOverlay=[xpath]://div[@class='vn-table__overlay']
removeButton = [css]:.identity-tile a
nextButton = [css]:#btn_next
cancelButton = [css]:#btn_cancel
editNameCompanyUsers = [id]:edit-company-name
editNamePartnerUsers = [id]:edit__displayName

#details tile
detailsTitle = [xpath]:(//*[@id="details"]//div)[2]
nameLabel = [css]:#namePanel div.dui-epr-label
nameEdit = [xpath]:(//div[@id='namePanel']//div[2]//div[2])[2]
nameValue = [css]:#namePanel h6 span
emailLabel = [css]:#emailPanel div.dui-epr-label
emailValue = [css]:#emailPanel h6 span
mobilePhoneLabel = [css]:#mobilePanel div.dui-epr-label
mobilePhoneValue = [css]:#mobilePanel h6 span
companyLabel = [css]:#companyName div.dui-epr-label
companyValue = [css]:#companyName h6 *
officePhoneLabel = [css]:#officePanel div.dui-epr-label
officePhoneValue = [css]:#officePanel h6 span
jobTitleLabel = [css]:#jobTitlePanel div.dui-epr-label
jobTitleValue = [css]:#jobTitlePanel h6 span
jobTitleEdit = [css]:#jobTitleEditBtn
titleModelHeader = [xpath]:(//*[@id="jobTitle-modal"]//div)[3]
jobTitleTextKey = [css]:#edit_modal_jobTitle
cancelButtonOnPopup = [css]:#editCancelBtn
SaveButtonOnPopup = [css]:#editSaveBtn
addressLabel = [css]:#addressPanel div.dui-epr-label
addressValue = [xpath]://*[@id="addressPanel"]/div[2]/h6/span
languageLabel = [css]:#languagePanel div.dui-epr-label
languageValue = [css]:#languagePanel h6 span
languageEditButton = [xpath]://*[@id="languageEditBtn"]
languageModelHeader = [xpath]:(//*[@id="language-modal"]//div)[3]
selectArrowKey = [xpath]:(//*[@id="language-modal"]//div[3])[1]
selectLanguage = [xpath]:(//*[@id="language-modal"]//div[@role="option"])[8]
dialogueBox = [xpath]://div[contains(@class,'modal__content')]
userDetailsPageSpinner = [xpath]://div[@class='dui-page-spinner']//*[name()='svg']
#identity tile
userNameIdentity = [xpath]://*[@id="dui-container"]//div[contains(@class,'identity-name')]
userEmailIdentity = [xpath]://*[@id="dui-container"]//div[contains(@class,'primary-data')]//p[2]
userPhoneIdentity = [xpath]://*[@id="dui-container"]//div[contains(@class,'primary-data')]//p[3]
userAccountLabel = [css]:#usersProfilePanel div.dui-user-account-container.text-center p
userAccountType = [xpath]://*[@id="dui-container"]//div[contains(@class,'footer')]//p[1]
userStatusType = [xpath]://*[@id="dui-container"]//div[contains(@class,'status')]//div
#Roles tile
userRoleTitle = [xpath]:(//*[@id="roleAssignmentPanel"]//div)[2]
userRoleAssignmentDescription = [xpath]:(//*[@id="roleAssignmentPanel"]//div[2]/div[1])[1]
userRoleLabel = [xpath]://*[@id="rolesPanel"]//div[contains(@class,'dui-epr-label')]
userRoleValue = [xpath]://*[@id="rolesPanel"]//span
userRoleEditButton = [xpath]:(//div[contains(@class,"accountAndRolesDetails")]/button)[1]
roleCancelButtonOnPopup = [css]:#rolesCancelBtn
roleSaveButtonOnPopup = [css]:#rolesSaveBtn
roleModelPopupTitle = [xpath]://*[@id="rolesModal"]//div[1]/h4
usersDeviceTab = [xpath]://*[@id="usersDetailsDevicesPanel"]
userAccountsTitle = [xpath]:(//*[@id="roleAssignmentPanel"]//div)[2]

#Users Devices tile
usersDeviceTileHeaderMessage = [xpath]://*[@id="dui-user-device-list"]//div[contains(@class,'panel__title')]
usersDeviceSerialNumber = [xpath]:(//*[@id="col-id-serialNumber"]//div)[2]
usersDeviceName = [xpath]:(//*[@id="col-id-name"]//div)[2]
usersDeviceType = [xpath]:(//*[@id="col-id-deviceType"]//div)[2]
usersDeviceApplicationEnrolled = [xpath]:(//*[@id="col-id-deviceClientApplicationName"]//div)[2]
usersDeviceLastActivity = [xpath]:(//*[@id="col-id-status"]//div)[2]
usersDeviceNameLinkKey = [xpath]://*[@id="dui-user-device-list"]//div/table/tbody/tr[1]/td[3]//a
userAssignedDevices = [xpath]://*[@id="dui-user-device-list"]//a
userDevicesStatus = [xpath]://*[@id="dui-user-device-list"]//tr//td[7]
deviceNameVerificationOnDetailsPageKey = [xpath]://*[@id="device-serial"]/div[2]
userManageCompanyHeader = [xpath]://*[@id="companyName"]/div[2]
companyImpersonateMatching = [xpath]://*[@id="company-name-row"]/div[2]
totalDevicesOnAssignedDevicesTile = [xpath]://*[@id="dui-pagination"]//a//span

itAdminLabel = [xpath]://*[@id="it_admin"]/label/span[2]
appAdminLabel = [xpath]://*[@id="sw_admin"]/label/span[2]
hwAdminLabel = [xpath]://*[@id="hw_admin"]/label/span[2]
ldAdminLabel = [xpath]://*[@id="ldp_admin"]/label/span[2]
reportAdminLabel = [xpath]://*[@id="reports_admin"]/label/span[2]
userLabel = [xpath]://*[@id="employee"]/label/span[2]
seviceNowAdminLabel = [xpath]://*[@id="servicenow_admin"]/label/span[2]
workflowAdminLabel = [xpath]://*[@id="workflow_admin"]/label/span[2]

msTelementryLabel = [xpath]://*[@id="ms_telemetry"]/label/span[2]
customerEngineerLabel = [xpath]://*[@id="customer_engineer"]/label/span[2]
itManagerLabel = [xpath]://*[@id="it_manager"]/label/span[2]
emmAdminLabel = [xpath]://*[@id="emm_admin"]/label/span[2]
listOfCheckboxRoleOnPopup = [xpath]://*[@class="list-item-wrapper"]//label
selectedCheckBoxesOnPopup = [css]:span.vn-checkbox__span
columnCheckboxesOnPopup = [css]:label input

#Overview tab
mobileEditButton = [css]:#mobileEditBtn
mobileTextBox = [css]:#edit_modal_mobilePhone
officeEditButton = [css]:#officeEditBtn
officeEditBox = [css]:#edit_modal_officePhone

#EMM Admin Role
daasrolescheck = [css]:label span.vn-checkbox__span--checked
emmAdminRole = [xpath]://*[@id="emm_admin"]//span[2]
emmAdminRoleDescription = [css]:#emm_admin div 
emmAdminRoleCheckbox = [css]:#emm_admin span.vn-checkbox__span 
EMMTooltab = [css]:#menu_emmToggle
chromeEnterpriseTab = [css]: #menu_chrome div:nth-child(2)
help&SupportTab = [css]:#menu_support div:nth-child(2)	
settingsTab = [css]:#menu_settings div:nth-child(2)
daasRoleLabels = [xpath]://*[@id="user_roles_container"]//*[@class='row-fluid']//label//input
daasUserRoleCheck = [xpath]://*[@id="dom_user_roles"]/label/a
chromeNotConfiguredString = [xpath]://*[@id='chrome-book-row']//div//h6
emmNotConfiguredString = [css]:#chrome-book-row h6
airwatchTab = [css]:#menu_airwatch
intuneEditButton=[css]:#edit-company-intune-settings
intuneTab = [css]:#menu_intune
officeEditBox = [css]:#edit_modal_officePhone

#impersonation
impersonatedText = [xpath]://a[contains(@class,'pointer')]/..
impersonatedLink = [css]:a[class*=pointer]
impersonateIcon = [id]:impersonate-user
impersonationPopupTitle = [css]:div[class*=modal] h4
impersonationPopupConfirmationText = [css]:#impersonate-user-confirmation p
impersonationSubmit = [id]:impersonate-modal-submit
impersonationCancel = [id]:impersonate-modal-cancel

searchRole = [xpath]://*[contains(@class,"search-attached")]//input[@type="search"]
listOfRoles = [xpath]://*[contains(@class,"roles-list")]//span[1]

#role assignment tile
roleHeader = [xpath]:(//*[contains(@id,'container')]//div[contains(@class,'title')])[4]
roleMessage = [xpath]:(//*[contains(@id,'roleAssignment')]//div[contains(@class,"panel__content")]/div)[1]
roleLabel = [xpath]://*[@id="dui-accountAndRolesDetails"]/div
roleValue = [xpath]://*[contains(@class,"accountAndRolesDetails")]//p
roleButton = [xpath]://*[contains(@class,"accountAndRolesDetails")]//button
rolesSave  = [id]:rolesSaveBtn
rolesCancel  = [id]:rolesCancelBtn
rolePopupHeader = [css]:#rolesModal h4

#ToastNotification
toastNotificationAccountTile = [xpath]://div[contains(@class,'toast-enter-done')]//p 