userprofiledropdown = [xpath]://div[@aria-label='User Profile']
userprofiletext= [id]:user-profile
Timezoneonuserprofile = [id]:TimezonePanel
eidttimezoneclick = [id]:edit-TimezonePanel
edittimezonelabel = [id]:timezone-modal-label
togglesystemtimezone = [xpath]:(//div[@id='system-timezone-container']//label//span)[2]
togglesystimezoneclick = [xpath]://span[contains(text(),'Detect time zone automatically')]
#togglesystimezoneclick = [id]:system-timezone
selecttimezonelabel = [id]:timezone-select-label
dropdowntimezoneselect = [id]:timezone-select
savebuttontimezone = [id]:save-timezone
cancelbuttonrimezone = [id]:cancel-timezone
togglecheckbasedonvaluefordisbaled = [xpath]://div[@id='system-timezone-container']//input[@value='false']
togglecheckbasedonvalueforEnabled = [xpath]://div[@id='system-timezone-container']//input[@value='true']

#language section

perferedlanguageuserprofile = [id]:languagePanel
editperferedlanguageclick = [id]:edit-languagePanel
perferedlanguagelabel = [id]:language-modal-label
togglesystemperferedlanguage = [xpath]:(//div[@id='language-modal-content']//label//span)[2]
togglesystemperferedlanguageclick = [xpath]://span[contains(text(),'Detect language automatically')]
selectperferedlanguagelabel = [id]:language-select-label
dropdownperferedlanguageselect = [id]:language-select
savebuttonperferedlanguage = [id]:save-language
cancelbuttonperferedlanguage = [id]:cancel-language
togglecheckbasedonvaluefordisbaledperferedlanuguage = [xpath]://div[@id='language-modal-content']//input[@value='false']
togglecheckbasedonvalueforEnabledperferedlanuguage = [xpath]://div[@id='language-modal-content']//input[@value='true']