#signInButton = [xpath]://div[contains(@class,'dui-welcome-header')]//button[contains(@class,'signin-btn')]
signInButton = [xpath]://a[@href='/idplogin'][contains(text(),'Sign in')]
signInButton_selfOnboarding = [css]:#dui-app-container
signInMicrosoftButton = [xpath]://div[contains(@class,'dui-welcome-header')]//button[1]
#welcomePageTitle = [css]:div.hp-daas-title h5
welcomePageTitle = [xpath]://h1[contains(text(),'One platform')]/following::p[contains(text(),'HP WEX')]
hpLogo = [css]:div.dui-welcome-header.container svg
welcomePageInfo = [css]:div.smart-simplified-co h3
whatsNewTitle = [css]:div.whats-new-title h3
mapOnWelcomePage = [css]:div.world-map-background
worldWide = [css]:div.release-text h3
deviceCount = [css]:#device_count
hpPlans = [css]:div.tnc-background p
welcomeFooter = [xpath]://*[@class='footer-copyright']
languageDropdown = [css]:div.change-locale
privacyLink = [xpath]://*[@class='lnk-privacy-policy dui-hyperlink']
privacyPage = [xpath]://h2[contains(text(),'OUR APPROACH TO PRIVACY')]
welcomePageDescription = [css]:div.hp-daas-desc h6
learnMoreButton = [id]:learn_more
servicesPageText = [xpath]://*[contains(text(),'TODAY, EVERY BUSINESS NEEDS A TECHNOLOGY PARTNER. MAKE YOURS HP SERVICES.')]
cookiePopUp = [css]:.ot-sdk-container .ot-sdk-row
cookieAccept = [css]:#onetrust-accept-btn-handler
whatsNewSection = [css]:div[class=whatsnew-section]
whatsNewHeader = [css]:[class=whatsnew-section] h4
whatsNewDescription = [css]:[class=whatsnew-section] p
seeMoreButton =[css]:[class=whatsnew-section] button
welcomePageFooter = [css]:[class*=welcome-footer]
termsAndConditions = [xpath]://a[contains(@href,'/terms-and-conditions/en')]
termsAndConditionsTitle = [xpath]://div[@class='tnc-modal']/div/h3
printButton = [xpath]://*[@id="printButtton"]
hpIcon = [xpath]://a[@class="row"]//*[name()='svg']
hpDaas = [xpath]://a[@class="row"]//span
language = [xpath]://div[@role='button']
service = [xpath]://a[contains(@href,'/sla/en')]
serviceTitle = [xpath]://div[@class='sla-modal']/div/h3
privacy = [xpath]://a[contains(@href,'privacy')]
privacyHp = [xpath]://a[contains(@class, 'unselectable link_metrics')]