tabAddons = [css]: #addons
addonAnyware = [css]: #anyware-addon
addonVyopta = [css]: #vyopta-addon
addonVyoptaConnectButton = [css]: #connect-service-button
addonWPT = [css]: #wpt-addon

## Product add-ons details page
productDetailsPage = [css]: #product-details
productDetailsMediaGallery = [css]: .product-media-gallery-media
productDetailsMediaGalleryModal = [css]: .product-media-gallery-modal
productDetailsMediaGalleryModalImg = [css]: .product-media-gallery-modal-media img
productDetailsBodyContent = [css]: .subscriptions-content
productDetailsSideContent = [css]: .subscriptions-details
productLink = [css]: #product-link
supportSiteLink = [css]: #support-site-link
documentationLink = [css]: #documentation-link
privacyPolicyLink = [css]: #privacy-policy-link
learnMoreLink = [css]: #requirements-link
closeModalButton = [xpath]: //button[@aria-label='Close modal']
contactSalesButton = [css]: #contact-sales-button
purchaseButton = [css]: #purchase-button
connectButton = [css]: #connect-service-button
vyoptaModalContent = [css]: .vyopta-modal
vyoptaModalSupportLink = [css]: .vyopta-modal a
### This is not optimal. Add ID for vypta modal and not just the content
vyoptaModalFooter = [css]: .vn-modal--body:has(.vyopta-modal) + div
vyoptaModalFirstButton: [css]: .vn-modal--body:has(.vyopta-modal) + div button
modalFooterButton = [css]: .vn-modal--footer button