expandBtn= [css]:#wex_sm_expand_btn
alertsMenu = [xpath]: //*[@id="menu_alerts"]/a
alertManagement = [css]:#menu_alerts_alertsManagement
alertManagementPage = [xpath]: //*[@id="alerts-management"]
alertOption = [xpath]: //li[@data-testid='menu_alerts']
activeAlert = [css]: #menu_alerts_alertsListView_link
sideMenuToggleButton = [id]:wex_sm_expand_btn
manageAlertNotification = [xpath]://div[@id='alert-management-notification-heading']
manageAlertNotificationtext = [xpath]://div[@id='alert-management-notification-subHeading']
clearDropdown = [xpath]://button[@aria-label="Clear"]
inProductNotificationLabel = [css]: #in-product-notification-label
inProductNotificationDropdown = [xpath]://*[@id="in-product-notification"]
inProductNotificationDropdownList = [xpath]://*[@id="in-product-notification-listbox"]
partnerAlertManagement : [css]:#menu_alerts

itAdminSelect = [xpath]:(//li[@role='option'])[1]
reportAdminSelect = [xpath]: (//li[@role='option'])[2]
emailNotificationaLabel =[xpath] : //*[@id="email-notification-label"]
emailNotificationDropdown = [xpath]: //*[@id="email-notification"]
emailNotificationDropdownList= [xpath]://*[@id="email-notification-listbox"]
alertManagementTitle = [xpath] ://*[contains(@class,'alert-management-title')]
alertManagementSubtitle = [xpath] : //*[contains(@class,'alert-management-subtitle')]
alertManagementColumnHeader = [xpath]://*[contains(@class,'alert-table')]//table/thead/tr//button
titleColumn = [xpath]: //*[@id="title"]
statusColumn = [xpath]: //*[@id="status"]
severityColumn =[xpath]://*[@id="severity"]
lastEditedColumn = [xpath]://*[@id="lastEdited"]
lastTriggeredColumn = [xpath]://*[@id="lastTriggered"]
columnSettingIcon = [css]: button[aria-label="Column Options"]
currentPageNumber = [css]: button[aria-label="Page 1"]
previousButton = [xpath]: (//button[@class='page'])[1]
nextButton = [xpath]: (//button[@class='page'])[2]
resetToDefaultButton = [xpath]: //button[contains(@class, "default-button")]
saveButton = [xpath]: ((//div[@aria-describedby="column-options-desc"]/div)[3] //button)[1]
cancelButton = [xpath]: ((//div[@aria-describedby="column-options-desc"]/div)[3] //button)[2]
clearfilter = [xpath]: //button[@aria-label='Clear Filters']
emailNotificationClearDropdown= [xpath]:(//button[@aria-label="Clear"])[2] 
editToastMessage = [xpath]://div[@role='status']/div
createButton = [xpath]: //button[@id="custom-alerts-create"]
disableAlertErrorPopup = [css]: #modal-workflow-label
disableAlertErrorPopupCloseBtn = [xpath]: //div[@id="modal-workflow"]/following-sibling::button

#Enable Alerts

emptyAlertList = [xpath]: //*[contains(@class,'wex-empty-state-widget-text')]
predefinedSelectAlertCheckbox =[xpath]: //table/tbody/tr/td[1]/span/label/span
alertStatus= [xpath]: //*[@id="alert-management-table"]/tbody/tr[1]/td[3]//div[2]
enableAlert = [css]: #alert-enable
disableAlert = [css]: #alert-disable
deleteAlert = [css]: #alert-delete span
titleSorting = [css]: #title button svg
statusSorting =[css]: #status div button
severitySorting = [css]: #severity div button
lastEditedSorting = [css]:#lastEdited div button
lastTriggeredSorting = [css]: #lastTriggered div button
statusSearch = [xpath]: (//*[contains(@class,'open-button')])[3]
severitySearch =[xpath]:(//*[contains(@class,'open-button')])[4]
enabledStatus = [css]: #status-search-option-0
disabledStatus= [css]: #status-search-option-1
criticalSeverity = [css]: #severity-search-option-0
highSeverity = [css]: #severity-search-option-1
mediumSeverity = [css]: #severity-search-option-2
lowSeverity = [css]: #severity-search-option-3
deleteConfirmation =[css]:#modal-delete-label
deleteText= [css]: #modal-delete
deleteButton =[css]:#modal-delete-button
cancelButton = [css]: #modal-cancel-button
deleteAlertToastMessageText = [xpath]:(//div[@role="alert"]//div)[2]
enableAlertToastMessageText = [xpath]: (//div[@role="alert"]//div)[2]
disableAlertToastMessageText = [xpath]:(//div[@role="alert"]//div)[2]
alertListcheckbox =[css]: //*[@id="alert-management-table"]/tbody/tr/td/span/label/input
toastMessage= [xpath]: //*[@id="dui-app-scroll"]/div[3]
alertSidePanel= [xpath]: (//li[contains(@id,'menu_alerts')]//div)[1]

#Edit Alert

alertClick = [xpath]:(//*[@id="alert-management-table"]/tbody/tr[1]//td[2])
editAlert = [css]:#modal-edit-alert-title
editAlertSubtitle =[xpath]: (//*[@id="modal-edit-alert-title"])[2]
editAlertSeverity = [xpath]: //*[@id="edit-alert-severity-label"]
currentSeverity = [xpath]: //*[@id="edit-alert-severity"]
editAlertTitle = [xpath]://*[@id="edit-alert-title-input-label"]
editAlertTitleInput = [xpath]: //*[@id="edit-alert-title-input"]
editAlertDescription =[xpath]: //*[@id="edit-alert-description-input-label"]
editAlertDescriptionInput =[xpath]: //*[@id="edit-alert-description-input"]
alertWhenText= [xpath]: //*[@id="when-text"]
alertWhenText2=[xpath]://div[text()='% of devices.']
editAlertThreshold=[xpath]: //*[@id="edit-alert-threshold"]
editAlertCard= [xpath]://*[@id="alert-edit-card"]
severityTag =[xpath]:(//*[@id="alert-edit-card"]//div[2])[1]
alertCardTitle =[xpath]: //*[@id="alert-card-title"]
alertCardDescription= [xpath]: //*[@id="alert-card-description"]
percentageTag = [xpath]: //*[@id="fleet-percentage-tag"]
saveEditAlert = [xpath]://*[@id="edit-save"]
editAlertToastMessageText = [xpath]: (//*[@id="dui-app-scroll"]/div[3]//div)[3]

#Bulk action
selectAllCheckbox = [xpath]://*[@id="alert-management-table"]/thead/tr[1]/th[1]/span/label/input
mousehoverDisable = [css]: #alert-disable
mousehoverEdit = [css]: #alert-edit
mousehoverDelete = [css]:#alert-delete
mouseHoverAlertOption = [xpath]: //table[@id="alert-management-table"]//td/button
mousehoverEnable = [css]: #alert-enable

#table columns
TitleHeader = [css]: #title
statusheader = [css]:#status
dataPointsHeader = [css]:#dataPoint
configurationHeader = [css]:#configuration
alertTypeHeader = [css]:#alertType
severityheader = [css]:#severity
monitoringScopeHeader = [css]:#monitoringScope
createdByHeader = [css]:#createdBy
lastEditedHeader = [css]:#lastEdited
lastTriggeredHeader = [css]:#lastTriggered
typeSearch = [css]:#title-search
searchClearButton = [xpath]://input[@id="title-search"]/following-sibling::div/button
noRecordText = [css]: .wex-empty-state-widget .state-title
statusDropdown = [css]:#status-search
severitydropdown = [css]:#severity-search
severityCriticalOption = [xpath]://li[@role='option']
severityHighOption = [xpath]:(//li[@role='option'])[2]
severityMediumOption = [xpath]:(//li[@role='option'])[3]
severityLowOption = [xpath]:(//li[@role='option'])[4]
lasEdit = [css]:#lastEdited-date
lastTriggered = [css]:#lastTriggered-date
enableOption = [xpath]://li[@role='option']
disableOption = [xpath]:(//li[@role='option'])[2]
draftOption = [xpath]:(//li[@role='option'])[3]
fleetOption = [xpath]://li[@role='option']
deviceOption = [xpath]:(//li[@role='option'])[2]
enhancedOption= [xpath]://li[@role='option']
standardOption = [xpath]:(//li[@role='option'])[2]
statuscolumnData = [xpath]://div[contains(@class, "alert-status")]/div[2]
clearFilter = [xpath]://button[@aria-label="Clear Filters"]
severitycoulmndropdown = [xpath]://div[@class="alert-severity"]
configurationColumnData = [xpath]: //*[@id="alert-management-table"]//td[5]
createdByColumnData = [xpath]: //*[@id="alert-management-table"]//td[9]//div[@class="wex-value-field-content "]

#Enable and Disable status
allAlertStatus = [css]:div.alert-status
selectAllCheckbox = [xpath]://*[@id="alert-management-table"]//thead//input[@type='checkbox']
closeButton = [xpath]://button[@aria-label="CLOSE"]

#Alert Management Table
TitleHeaderSearch = [css]: #title-search
dataPointDropdown = [css]: #dataPoint-search
configurationDropdown = [css]: #configuration-search
alertTypeDropdown = [css]: #alertType-search
severityDropdown = [css]: #severity-search
createdByHeaderSearch = [css]: #createdBy-search
lastEditedHeaderSearch = [css]: #lastEdited-date
lastTriggeredHeaderSearch = [css]: #lastTriggered-date
selectColumnCheckbox = [xpath]: //*[@id="alert-management-table"]/thead/tr/td//input
selectRowCheckbox = [xpath]: //*[@id="alert-management-table"]/tbody/tr/td//input

#Create New Alert Page
createNewAlertTitle = [css]: p.title-regular
createNewAlertSubtitle = [css]: p.subtitle-regular
progressBarText = [css]: p.body
sectionTitle = [css]: div.section-header
sectionDescription = [css]: span.section-description
newAlertTypeDropdown = [css]: #edit-alert-type
newAlertTypeHelperText = [css]: #edit-alert-type-helper-text
newAlertPageCancelBtn = [css]: #alert-rules-step_cancel-btn
setScopePageCancelBtn = [css]: #alert-scope-step_cancel-btn
configurePageCancelBtn = [css]: #alert-configure-notifications-step_cancel-btn
reviewPageCancelBtn = [css]: #alert-review-step_cancel-btn
newAlertPageNextBtn = [css]: #next_alert-rules-step_btn
setScopePageNextBtn = [css]: #next_alert-scope-step_btn
configurePageNextBtn = [css]: #next_alert-configure-notifications-step_btn
saveAsDraftBtn = [css]: #alert-rules-step_back-btn
dataPointToMonitorLabel = [css]: #data-point-monitor-label
dataPointToMonitorDropdown = [css]: #data-point-monitor
appCrashesOption = [xpath]://li[@role='option']
bsodOption = [xpath]:(//li[@role='option'])[2]
missingWindowsUpddateOption = [xpath]:(//li[@role='option'])[3]
osCrashesOption = [xpath]:(//li[@role='option'])[4]
onThisAppLabel = [css]: #data-point-option-app-crash-label
onThisAppDropdown = [css]: #data-point-option-app-crash
onThisAppHelperText = [css]: #custom-alert-app-crash-helper-text
onThisAppHelperLink = [css]: #custom-alert-app-crash-helper-text a
dropdownSearch = [css]: div[data-floating-ui-portal] input
bugCheckCodeLabel = [css]: #data-point-option-bsod-label
bugCheckCodeDropdown = [css]: #data-point-option-bsod
updateTypeLabel = [css]: #data-point-option-windows-updates-missing-label
updateTypeDropdown = [css]: #data-point-option-windows-updates-missing
alertDetailsTitle = [xpath]: (//div[contains(@class, "section-header")])[2]
alertDetailsDescription = [xpath]: (//span[contains(@class, "section-description")])[2]
alertTitleLabel = [css]: #alert-title-label
alertTitleInput = [css]: #alert-title
alertTitleHelperText = [css]: #alert-title-helper-text
severityLabel = [xpath]: ((//div[contains(@class, "container-spacing")])[4] //label)[2]
newAlertSeverityDropdown = [xpath]: ((//div[contains(@class, "container-spacing")])[4] //input)[2]
triggerConditionTitle = [xpath]: (//div[contains(@class, "section-header")])[3]
triggerConditionDescription = [xpath]: (//span[contains(@class, "section-description")])[3]
eventThresholdLabel = [xpath]: (//div[contains(@class, "container-spacing")])[5] //label
eventThresholdInput = [xpath]: (//div[contains(@class, "container-spacing")])[5] //input
eventThresholdHelperText = [xpath]: (//div[contains(@class, "container-spacing")])[5] //p
timeWindowLabel = [xpath]: ((//div[contains(@class, "container-spacing")])[5] //label)[2]
timeWindowDropdown = [xpath]: ((//div[contains(@class, "container-spacing")])[5] //input)[2]
fleetThresholdLabel = [xpath]: (//div[contains(@class, "container-spacing")])[6] //label
fleetThresholdInput = [xpath]: (//div[contains(@class, "container-spacing")])[6] //input
fleetThresholdHelperText = [xpath]: (//div[contains(@class, "container-spacing")])[6] //p
unitTypeLabel = [xpath]: ((//div[contains(@class, "container-spacing")])[6] //label)[2]
unitTypeDropdown = [xpath]: ((//div[contains(@class, "container-spacing")])[6] //input)[2]
recoveryPeriodLabel = [xpath]: (//div[contains(@class, "container-spacing")])[7] //label
recoveryPeriodDropdown = [xpath]: (//div[contains(@class, "container-spacing")])[7] //input
recoveryPeriodHelperText = [xpath]: (//div[contains(@class, "container-spacing")])[7] //p
escalationThresholdTitle = [xpath]: (//div[contains(@class, "section-header")])[4]
escalationThresholdDescription = [xpath]: (//span[contains(@class, "section-description")])[4]
escalationSeverityLabel = [css]: #escalation-severity-label
escalationSeverityDropdown = [css]: #escalation-severity
escalationSeverityHelperText = [css]: #escalation-severity-helper-text
escalationThresholdLabel = [css]: #escalation-fleet-threshold-label
escalationThresholdHelperText = [css]: #escalation-fleet-threshold-helper-text
escalationThresholdInput = [css]: #escalation-fleet-threshold
escalationUnitTypeLabel = [css]: #escalation-fleet-threshold-unit-label
escalationUnitTypeDropdown = [css]: #escalation-fleet-threshold-unit

moniterAllDeviceLabel = [xpath]: (//fieldset[@id="monitoring-scope-selection"]/label)[1]
moniterSpecificDeviceLabel = [xpath]: (//fieldset[@id="monitoring-scope-selection"]/label)[2]
newGroupCreationHelperText = [css]: div.group-link
newGroupCreationLink = [css]: div.group-link a
viewSelectedGroupsLabel = [xpath]: //input[@id="view-selected-group"]/parent::label
specificGroupTableTitle = [css]: .device-group-table #title
specificGroupTableSelectAllCheckbox = [xpath]: //div[contains(@class, "device-group-table")] //thead/tr/td
specificGroupTableTitleSearch = [css]: #title-search
specificGroupTableDataCheckbox = [xpath]: //div[contains(@class, "device-group-table")] //tbody/tr/td[1]//label
specificGroupTableDataName = [xpath]: //div[contains(@class, "device-group-table")] //tbody/tr/td[2]
selectedGroupCount = [css]: .group-selected-section

notificationTitle = [css]: .section-header
notificationTitleDescription = [css]: .section-description
inProductNotificationLabel = [css]: #in-product-notification-label
inProductNotificationDropdown = [xpath]: //input[@id='in-product-notification']
emailNoficationLabel = [css]: #email-notification-label
emailNotificationDropdown = [xpath]: //input[@id='email-notification']
teamsNotificationLabel = [css]: #teams-notification-label
teamsNotificationDropdown = [xpath]: //input[@id='teams-notification']
teamsNoficationHelperText = [xpath]: (//div[@class="custom-alert-body"]//p)[1]
repeatNotificationLabel = [css]: #repeat-notification-label
repeatNotificationDropdown = [xpath]: //input[@id='repeat-notification']
repeatNotificationHelperText = [css]: #repeat-notification-helper-text
ProductNotificationLabel = [css]:#product-notification-label
ProductNotificationDropdown = [xpath]://input[@id='product-notification']


overviewTitle = [xpath]: (//div[@class="section-header"])[1]
overviewDescription = [xpath]: (//div[@class="section-description"])[1]
reviewAlertTitleLabel = [xpath]: (//div[@class="section-header"])[2]
reviewAlertTitleValue = [xpath]: (//div[@class="section-description"])[2]
reviewTriggerConditionTitle = [xpath]: (//div[contains(@class, "title-container")] //h3)[1]
alertTypeLabel = [css]: #alert-type label
alertTypeValue = [xpath]: (//div[@id="alert-type"] //div)[2]
reviewSeverityLabel = [css]: #alert-severity label
reviewSeverityValue = [xpath]: (//div[@id="alert-severity"] //div)[2]
dataPointLabel = [css]: #alert-data-point label
dataPointValue = [xpath]: (//div[@id="alert-data-point"] //div)[2]
appsMoniteredLabel = [css]: #alert-data-point-options label
appsMoniteredValue = [xpath]: (//div[@id="alert-data-point-options"] //div)[2]
reviewFleetThresholdLabel = [css]: #alert-fleet-threshold label
reviewFleetThresholdValue = [xpath]: (//div[@id="alert-fleet-threshold"] //div)[2]
reviewEventThresholdLabel = [css]: #alert-event-threshold label
reviewEventThresholdValue = [xpath]: (//div[@id="alert-event-threshold"] //div)[2]
reviewTimeWindowLabel = [css]: #alert-time-window label
reviewTimeWindowValue = [xpath]: (//div[@id="alert-time-window"] //div)[2]
reviewRecoveryPeriodLabel = [css]: #alert-recovery-period label
reviewRecoveryPeriodValue = [xpath]: (//div[@id="alert-recovery-period"] //div)[2]
deviceGroupsLabel = [css]: #alert-device-groups label
deviceGroupsValue = [xpath]: (//div[@id="alert-device-groups"] //div)[2]
escalationThresholdTitleLabel = [xpath]: (//div[contains(@class, "title-container")] //h3)[2]
reviewEscalationSeverityLabel = [css]: #alert-escalation-severity label
reviewEscalationSeverityValue = [xpath]: (//div[@id="alert-escalation-severity"] //div)[2]
reviewEscalationThresholdLabel = [css]: #alert-escalation-fleet-threshold label
reviewEscalationThresholdValue = [xpath]: (//div[@id="alert-escalation-fleet-threshold"] //div)[2]
notificationTitleLabel = [xpath]: (//div[contains(@class, "title-container")] //h3)[3]
reviewInProductNotificationLabel = [css]: #alert-in-product-notification label
reviewInProductNotificationValue = [xpath]: (//div[@id="alert-in-product-notification"] //div)[2]
emailNotificationLabel = [css]: #alert-email-notification label
emailNotificationValue = [xpath]: (//div[@id="alert-email-notification"] //div)[2]
reviewRepeatNotificationLabel = [css]: #alert-repeat-notifications label
reviewRepeatNotificationValue = [xpath]: (//div[@id="alert-repeat-notifications"] //div)[2]
reviewTeamsNotificationLabel = [css]: #alert-teams-notification label
reviewTeamsNotificationValue = [xpath]: (//div[@id="alert-teams-notification"] //div)[2]
escalationInProductNotificationLabel = [css]: #alert-escalation-in-product-notification label
escalationInProductNotificationValue = [xpath]: (//div[@id="alert-escalation-in-product-notification"] //div)[2]
escalationTeamsNotificationLabel = [css]: #alert-escalation-teams-notification label
escalationTeamsNotificationValue = [xpath]: (//div[@id="alert-escalation-teams-notification"] //div)[2]
escalationEmailNotificationLabel = [css]: #alert-escalation-email-notification label
escalationEmailNotificationValue = [xpath]: (//div[@id="alert-escalation-email-notification"] //div)[2]
publishButton = [css]: #publish_alert-review-step_btn
toastMessage = [xpath]: //div[@role="status"]/div