planTag = [css]: #account-active-license-tag .wex-tag-content

tabLicenses = [css]: #licenses
licensesPlaceholder = [css]: .plan-placeholder
licensesPlaceholderAddLicensesButton = [css]: .plan-placeholder button
licensesHeader = [css]: .plan-list-header
licensesList = [css]: .plan-list
licensesListItemHeaderText = [css]: .wexcard-header-title > div > div:first-child
licensesAddLicensesButton = [css]: .plan-list-header button
licensesAddLicensesModalHeader = [css]: #company-subscription-key-label
licensesAddLicensesModalDesc = [css]: #company-subscription-key
licensesAddLicensesModalInput = [css]: #company-subscription-key input
licensesAddLicensesModalValidateButton = [css]: #company-name-save
licensesAddLicensesModalCancelButton = [css]: #company-subscription-cancel
