## Create company page
addCompany = [id]:btn_company_add
addCustomerHeader = [id]:modal_company_info-label
custmerSubtitle = [id]:add-customer-subtitle
custmerAddStep1 = [id]:customer-add-popup-step1
custmerAdddesc = [id]:customer-add-popup-desc
CompanyName = [id]:company-name
CompanyNameLabel = [id]:company-name-label
Address1abel = [id]:address-line-1-label
Address1 = [id]:address-line-1
Address1abelSecond = [id]:address-line-2-label
Address2 = [id]:address-line-2
city = [id]:city
cityLabel = [id]:city-label
region-label = [id]:region-label
region = [id]:region
zipcode = [id]:zipcode
ZipCodeLabel = [id]:zipcode-label
countryLabel = [xpath]://*[text()='Country']/ancestor::label
country = [id]:company-country
countrylt =[xpath]://ul[@role="listbox"]/li
custmerAddStep2 = [id]:customer-add-popup-step2
custmerITdesc = [id]:customer-add-popup-itadmin-desc
firstItadmn = [id]:first-name
firstNameLabel = [id]:first-name-label
lastItadmn = [id]:last-name
lastNameLabel = [id]:last-name-label
emailItadmin = [id]:email
emailLabel = [id]:email-label
phoneNumber = [id]:phone-number
phoneNumberLabel [id]:phone-number-label
mspInfo = [id]:modal_msp_info-label
mspDesc = [xpath]://*[@id="modal_msp_info"]//div//p
mspAssigned = [id]:MSP-Assigned
msplist =[xpath]://ul[@role="listbox"]/li
search = [xpath]://*[@placeholder="Search Items"]
mspSelect = [id]:MSP-Assigned-option-0
addCompInfo = [id]:add_company__selected_info
partnerInfoLabel = [xpath]://*[@id="modal_partner_info"]//div//h5
partnerInfo = [id]:modal_partner_info-label
partnerArrowOnPopup = [css]:#modal_partner_info-desc svg
partnerDesc = [xpath]://*[@id="modal_partner_info"]//div//p
partnerAssigned = [id]:Partner-Assigned
partnerSelectOnPopup = [id]:Partner-Assigned-option-0
createBtn = [id]:btn_create
compDetails = [id]:companyDetails
cardTitle = [id]:card-title
deleteCompBtn = [id]:delete-company-btn
overviewTab = [id]:company-information
compProfile = [id]:company-profile
bussiness = [id]:business-identification
emailComp = [xpath]:(//a[@class="dui-hyperlink text-overflow-ellipsis"])[1]
prefTab = [id]:preferences
authentication = [id]:authentication
deviceGroup = [id]:device-groups
comNetwork = [id]:company-networks
networkMonitor = [id]:network-monitor-settings
thirdParty = [id]:third-party-software-integration
mspTab = [id]:assigned-msp
assignmentSetting = [id]:assignment-settings
partnerTab = [id]:assigned-partner
commnetsTab = [id]:CompanyCommentsTab
addcomment = [id]:comments
deleteCompModal = [id]:dui-confirmation-modal-label
deleteBtn= [xpath]://button[@id="dui-confirm-save"]
CancelBtn= [xpath]://button[@id="dui-confirm-cancel"]
deleteToast = [xpath]://div[@role="status"]
compName = [xpath]://input[@id="name"]
primaryEmailColumn = [xpath]://input[@id="primaryAccountEmail"]
compRow = [xpath]:(//*[@class="dui-hyperlink text-overflow-ellipsis"])[1]
Customers = [xpath]://a[@id='menu_customers']
Companies = [xpath]://*[@id="menu_customers_partnerCompanies"]//span
cancelBtn = [id]:btn_cancel
addNxtBtn = [id]:btn_next
addPrevBtn = [id]:btn_prev
IdpTypedrop = [xpath]://*[@id="idp-dropdown"]
IDPlist = [xpath]://ul[@role="listbox"]/li
noResults = [xpath]://*[@class="state-title"]
addPart = [id]:add-partner
invitePartnerLabel = [id]:assignment-partner-label
searchPartner = [id]:assignment-partner-select-box
invButton = [id]:assignment-partner-submit
canButton = [id]:assignment-partner-cancel
partnerList = [xpath]://ul[@role ="listbox"]/li
partnerInfo = [xpath]://div[@class="dui-select-modal-content"]
pendingInvite = [xpath]://div[@id="pending-invitations"]//div[@class="dui-ddetails-content"]
companyName= [xpath]:(//*[@id="companies"]//td[2]//a)[1]
companyNameNew = [xpath]:(//*[@id="test-invite-comp-selenium-auto"])[1]
partnerInvitedCompanyName = [xpath]:(//*[@id="autoinvitecustomer"])[1]
clearFilter = [xpath]://*[@id="dui-container" ]//div/button[@aria-label="Clear Filters"]
invitedCustomer = [id]:test-invite-comp-selenium-auto
partnerInvitedCustomer = [id]:autoinvitecustomer
deleteModelDesc =[id]:dui-confirmation-modal
totalCompanies = [xpath]://*[@id="companies"]/tbody/tr
emailOnDetails = [xpath]://div[@class="wex-value-field-content "]//a
selectLanguageText = [xpath]://*[@id="modal_itAdmin_info"]//div[contains(text(), "Please select a plan.")]
premiumPlan = [xpath]://ul[@role='listbox']/li
SelectPlan = [xpath]://input[@id='subscription-plan-dropdown']
SelectLanguage = [xpath]:(//*[@id="modal_itAdmin_info"] //input[@role="combobox"])[2]
selectEngLanguage =[xpath]://ul[@role='listbox']/li
ProPlanOption =  [xpath]://*[@data-value="workforce_experience_pro_trial"]
mspDropDownArrow= [xpath]:(//div[@id='modal_msp_info']//div)[13]
firstName = [xpath]:(//table[@id="companies"]/tbody/tr[2]/td[1]//a)[1]
selectPlanText=[xpath]://*[@id="modal_itAdmin_info"]//div[contains(text(), "Please select a plan.")]

#First time Login
usePasswordButton=[id]:use-password-btn
passowrdTextBox=[id]:password
createButton=[xpath]://*[@id="create-account-btn"]
codeTextBox=[id]:code
verifyButton=[id]:submit-code
verifyOnboardingLogo =[xpath]://*[@class="wex-logo"]
verifySteps=[xpath]://*[@class="stepper-container"]
verifyOnboardingMessage =[xpath]://*[@class="dui-adminx-accountLinked container"]//div//h5
verifyOnboardingNextButton =[xpath]://*[@id="adminx_onboarding"]//div/button[2]
createAccountButton=[xpath]://*[@id="adminx_onboarding"]//div/button
clickOnCompanySizeButton =[xpath]://*[@id="companySize"]
companySize-option-0= [id]:companySize-option-0
clickOnCompanyActualSize =[xpath]:(//*[@id="companySize-listbox"]//li)[3]
termAndConditionCheckbox = [xpath]:(//*[@id="adminx_onboarding"]//div/label/span)[6]
termsCheckbox= [xpath]:(//input[@type="checkbox"])[1]
dataCollectingCheckbox= [xpath]:(//input[@type="checkbox"])[2]
termAndConditionPrivacyCheckbox = [xpath]:(//*[@id="adminx_onboarding"]//div/label/span)[6]
skipButton = [xpath]:(//*[@id="adminx_onboarding"]//div/button)[3]
welcomePopupSkipButton =[xpath]://*[@id="welcomePopup_skipTourBtn"]
tourOnboardingCoach =[xpath]://div[@aria-describedby="skipTour-body"]
closeOnboardingCoachMarkButton =[xpath]://button[@aria-label="Close coachmark"]
createaccountbuttononpreview=[xpath]://*[@id="adminx_onboarding"]//div/button[1]
createCompanyButton =[xpath]://*[@id="adminx_onboarding"]//button
finshAccountCreationTitle =[xpath]:(//*[@id="adminx_onboarding"]//p[1])[1]
companyInformationTitle =[xpath]:(//*[@id="adminx_onboarding"]//p[1])[2]
primaryContactTitle =[xpath]:(//*[@id="adminx_onboarding"]//p[1])[3]




