deviceDetailsHeader = [xpath]: //*[@id="dui-container"]//div[@class='wex-dsummary-card']
overViewTab = [id]:device-information
hardwareTab = [id]:hardware
networkTab = [id]:network
locationTab = [id]:location
softwareTab =[id]:software
hardwareTabElements = [xpath]://div[contains(@id,"tab-hardware")]
BIOSTab =[id]:bios-and-drivers
timelineTab =[id]:realtime-device-timeline
healthAndProtectionTab =[id]:health-protection
sustainabilityTab =[id]:sustainability
deleteDevicePopup = [xpath]://*[@id='dui-remove-device-label']
securityNumberLabel = [xpath]://*[@id='security-code-number']
securityNumberTxtBox = [xpath]://input[@id='security-code']
deleteSelectedDeviceFromActionsDD = [xpath]://*[@id='dui-confirm-save']
importNotification = [xpath]://div[@role='alert']/child::div
lifecycleStatusInOverview = [xpath]://*[@id='device-lifecycleStatus']/div[contains(@class,'label')]
lifecycleStatusEditIcon = [id]:device-lifecycleStatus-edit
openLifecycleStatusList = [id]:Lifecycle Status-select-box
selectLifecycleStatusFromList = [xpath]://li[@id='Lifecycle Status-select-box-option-2']
saveLifecycleStatus = [id]:Lifecycle Status-submit
cancelLifecycleStatus = [id]:Lifecycle Status-cancel
lifecycleStatusPresentInOverview = [id]:device-lifecycle-status-text
lifecycleStatusColumn = [xpath]://th[@id='lifecycleStatus']
deviceDataTimeline = [xpath]://*[contains(@class,'highchart-timeline')]
lifecycleOptionsListOptions = [xpath]://ul[@role='listbox']/descendant::*[contains(text(),*)]
lifecycleOptionsList = [xpath]://ul[@role='listbox']
closeExportToastMsg = [xpath]://button[@aria-label='close']
assetNameValue = [xpath]://*[@id='device-name']/descendant::div[@class='value']

overViewTabSerialNumberLabel = [xpath]:(//*[@id='device-serial']//div)[1]
overViewTabSerialNumberValue = [xpath]:(//*[@id='device-serial']//div)[2]
overViewTabGroupLabel = [xpath]:(//*[@id='device-group']//div)[1]
overViewTabGroupName = [xpath]:(//*[@id='device-group']//div)[2]
overViewTabAliasLabel = [xpath]:(//*[@id='device-alias']//div)[1]
overViewTabAliasName = [xpath]:(//*[@id='device-alias']//div)[2]

overViewTabEnrolledUserLabel = [xpath]:(//*[@id='device-user']//div)[1]
overViewTabEnrolledUserName = [xpath]:(//*[@id='device-user']//div)[2]
overViewTabDeviceNameValue = [xpath]:(//*[@id='device-name']//div)[2]
overViewTabDeviceNameLabel = [xpath]:(//*[@id='device-name']//div)[1]
overViewTabDeviceTagValue = [xpath]:(//*[@id='device-tag']//div)[2]
overViewTabDeviceTagLabel = [xpath]:(//*[@id='device-tag']//div)[1]
overViewTabCostCenterValue = [xpath]:(//*[@id='device-cost']//div)[2]
overViewTabCostCenterLabel = [xpath]:(//*[@id='device-cost']//div)[1]
overViewTabLastRestartValue = [xpath]:(//*[@id='last-restart']//div)[2]
overViewTabLastRestartLabel = [xpath]:(//*[@id='last-restart']//div)[1]
overViewTabDeviceRoleValue = [xpath]:(//*[@id='device-source']//div)[2]
overViewTabDeviceRoleLabel = [xpath]:(//*[@id='device-source']//div)[1]
overViewTabBYODValue = [xpath]:(//*[@id='device-byod']//div)[2]
overViewTabBYODLabel = [xpath]:(//*[@id='device-byod']//div)[1]

#SYSTEM INFO SECTION
overViewTabManufacturerLabel = [xpath]:(//*[@id='device-manufacturer']//div)[1]
overViewTabManufacturerValue = [xpath]:(//*[@id='device-manufacturer']//div)[2]
overViewTabManufactureDateValue = [xpath]:(//*[@id='device-manufacture-date']//div)[2]
overViewTabManufactureDateLabel = [xpath]:(//*[@id='device-manufacture-date']//div)[1]
overViewTabDeviceBornDateValue = [xpath]:(//*[@id='device-born-on-date']//div)[2]
overViewTabDeviceBornDateLabel = [xpath]:(//*[@id='device-born-on-date']//div)[1]
overViewTabProductValue = [xpath]:(//*[@id='device-product']//div)[2]
overViewTabProductLabel = [xpath]:(//*[@id='device-product']//div)[1]
overViewTabDeviceModelValue = [xpath]:(//*[@id='device-model']//div)[2]
overViewTabDeviceModelLabel = [xpath]:(//*[@id='device-model']//div)[1]
overViewTabDeviceTypeValue = [xpath]:(//*[@id='device-type']//div)[2]
overViewTabDeviceTypeLabel = [xpath]:(//*[@id='device-type']//div)[1]
overViewTabOSValue = [xpath]:(//*[@id='device-os']//div)[2]
overViewTabOSLabel = [xpath]:(//*[@id='device-os']//div)[1]
overViewTabAssetLocationLabel = [xpath]://*[@id="asset-location"]/div[1]
overViewTabAssetLocationValue = [xpath]://*[@id="asset-location"]/div[2]
overViewTabAssignedAreaLabel = [xpath]://*[@id="device-assigned-area"]/div[1]
overViewTabAssignedAreaValue = [xpath]://*[@id="device-assigned-area"]/div[2]
overViewTabDeploymentDateLabel = [xpath]://*[@id="device-deployment-date"]/div[1]
overViewTabDeploymentDateValue = [xpath://*[@id="device-deployment-date"]/div[2]
overViewTabRetirementDateLabel = [xpath]://*[@id="device-retirement-date"]/div[1]
overViewTabRetirementDateValue = [xpath]://*[@id="device-retirement-date"]/div[2]
overViewTabAssetTypeLabel = [xpath]://*[@id="asset-type"]/div[1]
overViewTabAssetTypeValue = [xpath]://*[@id="asset-type"]/div[2]

#WARRENTY SECTION (OVERVIEW TAB)
overViewTabWarrantyHeader = [xpath]://*[@id='warranty-header']
addWarranty = [id]:add-new-warranty
addWarrantyText = [xpath]://*[@id='add-new-warranty']/span[1]
warrantyTitle = [id]:dui-form-modal-field-0
warrantyStartDate = [id]:dui-form-modal-field-1
warrantyEndDate = [id]:dui-form-modal-field-2
warrantyDesc = [id]:dui-form-modal-field-3
saveWarranty = [id]:dui-form-modal-submit
addWarrantyStatus = [xpath]://*[@id='dui-epr-0-3-1']/descendant::div[contains(text(),'Active')]
editWarranty = [xpath]://*[@id='warranty-header']/following::button[2]
deleteWarranty = [xpath]://*[@id='warranty-header']/following::button[1]
labelWarrantyTitle = [xpath]://*[@id='warranty-header']/following::span[contains(@class,'dui-panel-title')][1]/div[1]/div[1]
deleteWarrantyConfirmation = [id]:dui-confirm-save


#HARDWARE TAB HEADERS SECTION
hardwareTabBatteryHeaderSection = [xpath]://*[@id='battery-header']
hardwareTabProcessorHeaderSection = [xpath]://*[@id='processor-header']
hardwareTabHardDriveHeaderSection = [xpath]://*[contains(@id,'hard-drive')]
hardwareTabMemoryHeaderSection = [xpath]://*[@id='memory-header']
hardwareTabGraphicsHeaderSection = [xpath]://*[@id='graphics-header']

#NETWORK TAB HEADER SECTION
networkTabInterfaceHeaderSection = [xpath]://*[@id='network-interface-header']
networkTabHealthHeaderSection = [xpath]://*[@id='network-health-header']
networkTabDisconnectionsHeaderSection = [xpath]://*[@id='network-disconnections-header']
networkTabElements = [xpath]://div[@id='wex-dp-tab-device-network']

#LOCATION TAB SECTION
locationTabMapSection = [xpath]://*[@id='google-map']
locationHeaderSection = [xpath]://*[@id='location-header']
locationTabElements = [xpath]://div[@id="wex-dp-tab-device-location-tab"]
reloadLocationElements = [xpath]://*[@class='reloadLabel wex-primary-base-default-color']


#SOFTWARE TAB SECTION
softwareTabUtilizationHeader =[xpath]://*[@id='software-utilization-header']
softwareTabTop5AppHeader =[xpath]://*[@id='top-5-applications-header']
softwareTabMissWinUpdateHeader =[xpath]://*[@id='missing-windows-updates-header']
softwareTabMissOfficeUpdateHeader =[xpath]://*[@id='missing-office-updates-header']  
softwareTabElements = [xpath]://div[@id="wex-dp-tab-device-software"]
appInventoryTabElements = [xpath]://div[@id="application-inventory-header"]
memUtilizationGraph = [xpath]://*[@id='MemUtilizationChart']
cpuUtilizationGraph = [xpath]://*[@id='CpuUtilizationChart']
memContributionGraph = [xpath]:(//*[@class="highcharts-background"])[3]
cpuContributionGraph = [xpath]:(//*[@class="highcharts-background"])[4]


#BIOS TAB SECTION
biosTabHeader =[xpath]: //*[@id='bios-header']
biosTabHistoryHeader =[xpath]: //*[@id='bios-history-header']
biosTabElements = [xpath]://div[contains(@id,"wex-dp-tab")]
biosHistoryElements = [xpath]://*[text()="Show Previously Installed Versions"]
installedHPdriverpackages = [xpath]://*[@id="installed-hp-driver-packages-header"]
driverInventory  = [xpath]: //*[@id="driver-inventory-header"]

overViewTabLastSignInUserLabel = [xpath]:(//*[@id='device-last-logged-user']//div)[1]
overViewTabLastSignInUserName = [xpath]:(//*[@id='device-last-logged-user']//div)[2]

overViewTabLifeCycleLabel = [xpath]:(//*[@id='device-lifecycleStatus']//div)[1]
overViewTabLifeCycleValue = [xpath]:(//*[@id='device-lifecycleStatus']//div)[2]

overViewTabDepartmentLabel = [xpath]:(//*[@id='device-department']//div)[1]
overViewTabDepartmentValue = [xpath]:(//*[@id='device-department']//div)[2]


timelineTabElements = [id]:wex-dp-tab-realtime-device-timeline
timelineTabHeader =[xpath]://*[@id='timeline-header']
stateTimelineTabHeader =[xpath]://*[@id='device-timeline-container']//*[contains(@class,"state-title")]


healthProtectionTabElements = [xpath]://div[@id="wex-dp-tab-device-health-protection"]
sustainabilityTabElements = [xpath]://div[@class='state-title']
sustainabilityTabValues = [id]:power_consumption_over_time
firewallAndNetworkProtection = [xpath]://*[@id="device-firewall"]
issueIndicator = [id]:issue-indicators-header
resolvedIssue = [id]:resolved-issues--header
appCrashesTab = [id]:application-crashes-&-freezes-header
securityTab = [id]:security-header
logsTab = [id]:logs-header
applicationCrashes =[id]:application-crashes-&-freezes-header
bsodCrashes =[id]:bsod-crashes-(last-90-days)-header
powerConsumption =[xpath]: //*[@id="power_consumption_over_time"]//h6
#overallExp =[xpath]://*[@class="overall-exp-label"]
overallExp =[xpath]:(//*[@id="deviceDetails-score-card"]//div[1])[6]
recommendedAction =[xpath]://*[@class="wexcard-header-title-container"]
profileTab =[xpath]://*[@id="profile-header"]
customFieldsTab =[xpath]://*[@id="custom-fields-header"]
systemHeaderTab =[xpath]://*[@id="system-header"]
enrollApp =[xpath]://*[@id="workforce-experience-enrolled-applications-header"]
warrantyHeaderTab =[xpath]://*[@id="warranty-header"]
viewHistory =[xpath]://*[@id="view-enrollment-history"]
logs =[xpath]://*[@id="view-enrollment-history"]
timelineLearnMore =[id]:view-timeline
timelineLearnMoreData =[xpath]://*[@id="wex-main-container-page-route-id"]//div[2].

labelProcessorNameValue = [xpath]://*[text()='Name']/following::span[1]
labelNoOfLogicalProcessorsValue = [xpath]://*[text()='Number of logical processors']/following::span[contains(@class, 'panel-title')][1]/div[1]
labelNoOfCoresValue = [xpath]://*[text()='Number of cores']/following::span[contains(@class, 'panel-title')][1]/div[1]
labelNoOfEnabledCoresValue = [xpath]://*[text()='Numbers of Enabled Cores']/following::span[contains(@class, 'panel-title')][1]/div[1]
labelAppNameValue = [id]:client-app-name-0
enrolledApplicationsList = [xpath]://*[@class='client-app-name']

#Actions button
actionsButton = [xpath]://button[@aria-label="More actions"]
exportDataButton = [id]:device-export
exportDataButton_asset = [id]:wex_menu_item_device-export
exportToast = [xpath]://*[contains(@id, "toast")]
notificationBellIcon = [xpath]:(//*[@id="notification-center-button"])
notificationTabInBell = [xpath]://div[@role='tablist']/div[@id='1']
deviceNameValue = [id]:device-display-name
firstNotification = [xpath]: (//*[@aria-label="Action button"])[1]
unreadNotificationText = [xpath]:((//*[@id="wex-notifications"]//ul/li)//span)[2]
downloadLinkBellIcon = [id]:download-file-btn
deleteDeviceinActionDD = [xpath]://span[contains(text(),'Delete device')]
listOfUnreadNotificationText = [xpath]:((//*[@id="wex-notifications"]//ul/li)//div/span[contains(text(),'device details')])
listOfNotificationActionButton = [xpath]://button[@aria-label="Action"]
Asset_deviceNameInDetailsPage=[xpath]://*[@id='device-name']/descendant::*[@id]

#Asset Details Page
customFieldHeaderInDetailsPage = [xpath]://*[text()='Custom Fields']
customFieldLabelsInDetailsPage = [xpath]:(//div[@id='custom-field'][1]/child::div[@class='wex-editable-row-label'])
customFieldValuesInDetailsPage = [xpath]://div[@id='custom-field']//*[contains(@id,'device-custom-field')]

#Warranty And Service Coverage
allWarrantyTiles = //*[@id="device-warranty"]//div[@class="wex-panel-content wex-panel-content-column"]
warrantyTilePlanName = //*[@class="warranty-service-coverage-planname"]
warrantyTilePlanStatus = //*[@class="warranty-plan-status"]
warrantyTileStartDate = //*[@id="plan-start-date"]//span
warrantryTileEndDate = //*[@id="plan-end-date"]//span

createCase =[xpath]://div[@id="action_button"]/button[@id="create-case-button"]


deviceStatusValue=[xpath]://div[contains(@class,'dui-list-status')]
deviceSerialNumberValue=[xpath]://*[@id='profile-device-serial-number']
planCardContainers=[xpath]://div[@id='device-warranty']//div[contains(@id,'dui-edit-panel-column-') and contains(@class,'wex-border-column')]
planCardName=[xpath]://span[contains(@id,'warranty-service-coverage-planname-')]
planCardStatus=[xpath]://span[contains(@class,'warranty-plan-status')]
planCardStartDate=[xpath]://span[contains(@id,'warranty-service-coverage-startdate-')]
planCardEndDate=[xpath]://span[contains(@id,'warranty-service-coverage-enddate-')]
planCardDescription=[xpath]://span[contains(@id,'warranty-service-coverage-description-')]