deviceAlertOption = [css]: #menu_deviceLevelalerts
deviceLevelTab = [css]: #wex_horizontal_menu_device-level-alerts
severityColumn = [css]:th#severity
deviceNamecolumn = [css]:th#deviceName
kpiColumn = [css]:th#kpi
occurencesColumn = [css]:th#ocurrences
serialNumberColumn = [css]:th#serialNumber
modelColumn = [css]:th#model
createdONColumn = [css]:th#createdOn
lastUpdatedColumn = [css]:th#lastUpdated
gearIcon = [css]: button[aria-label="Column Options"]
columnOptionHeader =  [css]: h4#column-options-label
optionLabel = [css]: div[role="option"] span.label
optionLabel2 = [xpath]: (//div[@role="option"] //span[contains(@class, "label")])[2]
optionLabel3 = [xpath]: (//div[@role="option"] //span[contains(@class, "label")])[3]
optionLabel4 = [xpath]:(//div[@role="option"] //span[contains(@class, "label")])[4]
optionLabel5 = [xpath]:(//div[@role="option"] //span[contains(@class, "label")])[5]
optionLabel6 = [xpath]:(//div[@role="option"] //span[contains(@class, "label")])[6]
optionLabel7 = [xpath]:(//div[@role="option"] //span[contains(@class, "label")])[7]
optionLabel8 = [xpath]:(//div[@role="option"] //span[contains(@class, "label")])[8]
optionCheckboxes = [css]: div[role="option"] input[type="checkbox"]
resetToDefaultButton = [xpath]: //button[contains(@class, "default-button")]
saveButton = [xpath]: ((//div[@aria-describedby="column-options-desc"]/div)[3] //button)[1]
cancelButton = [xpath]: ((//div[@aria-describedby="column-options-desc"]/div)[3] //button)[2]
kpiSearch = [css]:#kpi-search
kpiOption1 =[css]:#kpi-search-option-0
kpiOption2 = [css]:#kpi-search-option-1
kpiDropDownOption = [xpath]://div[@class="device-level-kpi"]//div[2]
kpiClear = [xpath]://button[@aria-label='Clear']
deviceSearch = [css]:#device-search
deviceSearchButton = [xpath]://input[@id="device-search"]/following-sibling::div/button
serialsSearch = [css]:#serialNumber-search
modelSearch = [css]:#model-search
firstCheckbox =[xpath]: //table/tbody/tr/td[1]/span/label/span
currentPageNumber = [css]: button[aria-label="Page 1 (Current Page)"]
previousButton = [xpath]: (//nav[@aria-label="Pagination Navigation"] //li)[1]
nextButton = [xpath]: (//nav[@aria-label="Pagination Navigation"] //li)[3]
emptyAlertList = [xpath]: //*[contains(@class,'wex-empty-state-widget-text')]
recordTable = [css]:#alert-management-table tbody tr
deviceDescription = [xpath]:(//div[@id="device-alerts-title"])[1]
printerPaperHeader = [xpath]://h4[@id='modal-delete-label']
closeButton = [xpath]:(//button[@aria-label='Close modal'])[2]
deviceID = [xpath]:(//div[@id="modal-delete-desc"]//p)[1]
osInfo = [xpath]:(//div[@id="modal-delete-desc"]//p)[2]
occurencesInfo = [xpath]:(//div[@id="modal-delete-desc"]//p)[3]
viewDeviceDetails = [css]:#modal-cancel-button