#WEXSustainabilityPage
logoutButton = [xpath]://*[contains(@class,'wex-profile-avatar ')]/div
signoutButton = [xpath]://div[@class='wex-profile-data']/button/span[contains(text(),'Sign Out')]
toggleButtonOpen = [xpath]://div[contains(@class,'wex-sidemenu-expand-btn-open')]
toggleButtonClose = [xpath]://div[contains(@class,'btn-expanded-lbl wex-txt-truncate')] 
homeButton = [xpath]://span[contains(text(),'Home')]
partnersandcompany =[xpath]://*[@class='wex-txt-truncate']
titleOpen = [xpath]://*[@class='btn-expanded-lbl wex-txt-truncate']
fleetDashboard = [xpath]:(//span[contains(text(),'Dashboard')])[1]
fleetManagement = [xpath]:(//*[contains(@id,'menu_fleetManagement')]//span[contains(@class,'side-menu__item-col-label')])[1]
fleetManagementWidget = [xpath]://*[@id="custom-dashboard-Fleet Management"]/div[2]/p
fleetManagementSiteHeader = [xpath]://span[contains(text(),'Fleet Management')]
fleetAnalytics = [xpath]://span[contains(text(),'Analytics')]
remediationsLink = [xpath]:(//li[@id='menu_remediations'])//a
listRedirection = [xpath]://nav[@aria-label='breadcrumbs']//a
loaderIcon =[xpath]://div[@class='dui-page-spinner']


groupsMenuBreadcrumb = [xpath]://nav[@aria-label='breadcrumbs']//span
groupsHeader = [xpath]://a[contains(@id,'menu_groups')]//span
addGroupBtn = [xpath]://button[@aria-label="Column Options"]/preceding-sibling::div//span
staticGroupadioBtn = [xpath]:(//input[contains(@value,'STATIC')])/following-sibling::span
dynamicGroupRadioBtn = [xpath]:(//input[contains(@value,'DYNAMIC')])/following-sibling::span
groupNameField = [xpath]://input[@id='group-name-id']
groupDescriptionField = [xpath]://textarea[@id='group-description-id']

editGroupNameField = [xpath]://input[@id='edit-group-name-id']
editGroupDescriptionField = [xpath]:(//div[@class='css-hvxvnp'])//textarea

selectDeviceListin_StaticGroup = [xpath]:(//span[normalize-space()='Select from device list'])[1]
selectCSVFileOptonin_StaticGroup = [xpath]:(//span[normalize-space()='Upload .csv file with the device list'])[1]
deviceListCheckBoxes = [xpath]:(//*[contains(@class,'vn-table__selector')]/input[not(contains(@aria-label,'Select all'))]/following-sibling::span)
device1_StaticGroup = [xpath]://tbody/tr[2]/td[1]/span[1]/label[1]/span[1]
device2_StaticGroup = [xpath]://tbody/tr[3]/td[1]/span[1]/label[1]/span[1]
assignDevice1_StaticGroup = [xpath]://*[@id="devices"]/tbody/tr[2]/td[1]/span/label/span
assignDevice2_StaticGroup = [xpath]://*[@id="devices"]/tbody/tr[3]/td[1]/span/label/span
assignDevicesToGrpBtn = [xpath]://button[@aria-label="Column Options"]/preceding-sibling::div//span
addDevicesToStaticGrpBtn = [xpath]:(//span[normalize-space()='Assign'])[2]
clearAllFiltersLink = [xpath]:(//span[normalize-space()='Clear Filters'])[1]

selectGroupProperty= [xpath]://input[@id='group-property']
selectGroupPropertyAsSerialNumber = [xpath]://li[@data-value='serialNumber']
selectGroupPropertyAsDeviceName = [xpath]://li[@data-value='name']
uploadCSVFileOptionField =[xpath]://input[@id='file-picker']


addGrpNextBtn = [xpath]://*[contains(@class, 'wep-group-footer-container')]//button[3]//span
nextBtnOnAddGroupPage = [xpath]://span[text()='Next']

addGrpCalculateBtn = [xpath]://span[normalize-space()='Calculate']
dynamicGroupDeviceCount= [xpath]: ((//div[contains(@class,'vertical-center')])//span[2]//span)[2] 
deviceCountatReviewPage= [xpath]://*[@id="wex-details-section-field-3"]/div[2]/div[1]/div[1]
overviewTabDeviceCount=[xpath]://div[@id='group-deviceCount']//span[contains(@class,'dui-hyphenate dui-panel-title')]//div//div


addBtn = [xpath]:(//*[contains(@class,'wep-group-container')]//div[2]//button)[1]
addGrpBtn = [xpath]://*[contains(@class,'wex-modal add-group')]//button[contains(@id,'add')]
createdOnHeaderSort = [xpath]://*[@id='created_ts']//button
createdOnHeader = [xpath]://*[@id='created_ts']
#//div[@class='css-1b3t3df']//div[@title='Open']//*[name()='svg']

propertyCombbobox1 = [xpath]:(//div[@id='properties-0'])[1]
propertyCombboboxItem1 = [xpath]://li[@id='properties-0-option-0']
valueCombbobox1 = [xpath]:(//div[@id='value-0'])[1]
propertyCombboboxValue1 = [xpath]://li[@id='value-0-option-0']

addRuleLink = [xpath]://span[normalize-space()='Add Rule']

propertyCombbobox2 = [xpath]:(//div[@id='properties-1'])[1]
propertyCombboboxItem2  = [xpath]://li[@id='properties-1-option-1']
valueCombbobox2 = [xpath]:(//div[@id='value-1'])[1]
propertyCombboboxValue2  = [xpath]://li[@id='value-1-option-0']

groupNameSearch = [xpath]: //input[@id='search-name']
groupNameCheck = [xpath]:(//tr[1]/td[1]/div[1]/div//a)[1]

groupMembership = [xpath]:(//div[@id='group-membership'])[1]
editGroupBtn = [xpath]://span[normalize-space()='Edit']

editAddRuleLink = [xpath]://span[normalize-space()='Add Rule']

delete1stRuleBtn = [xpath]:(//*[contains(@class,'sidebar-title-container')]/following-sibling::div//*[contains(@class,'justify-content')]//button)[last()-1]
delete2ndRuleBtn = [xpath]:(//*[contains(@class,'sidebar-title-container')]/following-sibling::div//*[contains(@class,'justify-content')]//button)[last()]

editPropertyListbox1 = [xpath]:(//div[@id='column-0'])[1]
editPropertyListItem1 = [xpath]://li[@id='column-0-option-2']
OperatorListbox1 = [xpath]:(//div[@id='operator-0'])[1]
OperatorListItem1 = [xpath]:(//li[@id='operator-0-option-1'])[1]
valueListboxInput = [xpath]:(//input[@name='valueTextBox'])[1]
editValueListbox1 = [xpath]://div[@id='value-2']
editValueListItem2 = [xpath]://li[@id='value-2-option-2']
editPropertyListbox2 = [xpath]://div[@id='column-1']
editPropertyListItem2 = [xpath]://li[@id='column-1-option-3']
editValueListbox2 = [xpath]://div[@id='value-1']
editValueListItem2 = [xpath]://li[@id='value-1-option-0']

saveGroupBtn = [xpath]://span[normalize-space()='Apply']
groupUpdateToasterMsg = [xpath]://div[normalize-space()='Group Updated']
groupAddedToasterMsg = [xpath]://div[normalize-space()='Add Group']

groupNameHeaderTitle=[xpath]://span[@class="group-name"]
groupDescription=[xpath]://*[@id="group-description"]//p[2]
groupNameTxt=[xpath]://div[@id="group-name"]//span//div
dynamicGroupMemershipType=[xpath]://*[@id="dynamic-rules"]
staticGroupMemershipType=[xpath]://*[@id="static-assignment"]


exportButton = [xpath]://button[@id="grouping-exportbtn"]
groupDeleteButton = xpath]://*[@class="dui-dsummary-card-buttons"]//button[1]//span
select1stPageDevices= [xpath]:(//span[@class='vn-checkbox__span css-198vfwn'])[1]
select1stDevice= [xpath]://tbody/tr[2]/td[1]/span[1]/label[1]/span[1]
membershipExportButton = [xpath]:(//span[normalize-space()='Export'])[2]
membershipRemoveButton = [xpath]://span[normalize-space()='Remove']
toastNotificationExport = [xpath]:(//div[@role='status']//div[1])
policyTastNotificationExport = [xpath]:(//div[@role='status']//div[1])
viewGroups = [xpath]://button[@type='button']/*[text()='View group']
editGroupButtonChk = [xpath]://div[@class='wex-panel-header-right']//button
editGroupButtonMemChk = [xpath]://div[@class='edit-button']//button
deleteGroupButtonChk = [xpath]://*[@id="grouping-deletebtn"]
clearListPageFilter = [css]:button[aria-label="Clear Filters"]
clearListPageGroupCreation = [xpath]:(//*[@aria-label="Clear Filters"])[last()]
securityCodeField = [xpath]:(//input[@id='security-code'])[1]
securityCodeNumber = [xpath]://*[@id='security-code-number']
deleteButton = [xpath]://button[@id='btn-group-delete-cancel']
cancelButton = [xpath]://button[@id='btn-group-delete']
groupsNameHeader = [xpath]://*[contains(@class,'group-name')]
deletePopupassignmentTxt = [xpath]:((//*[contains(@class,'delete-group-container-style')])[1]//div/div/div)[1]
deleteAssignment = [xpath]:(//*[contains(@class,'delete-group-container-style')])[1]//div[contains(@id,'group-assignments')]
closeModal = [xpath]:(//*[@aria-label='Close modal'])
policiesMenuItem = [xpath]:(//span[contains(text(),'Policies')])[1]deleteGroupButtonChk
policiesHeader = [xpath]:(//span[contains(text(),'Policies')])[2]
addPolicyButton = [xpath]: (//span[contains(text(),'Add')])[last()]

createPolicyNameTextBox = [xpath]://input[@data-testid='createPolicyNameTextBox']
selectBiosOptionDropdown = [xpath]:(//input[contains(@id,'vn')])[1]
biosSettingsOption = [xpath]:(//span[normalize-space()='BIOS Settings'])[1]
createPolicyDescriptionTextBox = [xpath]://input[@data-testid='createPolicyDescriptionTextBox']
policyScopeGlobalOption = [xpath]://span[contains(text(),'Global')]
nextbuttonOnPolicyCreationPage = [xpath]: (//span[contains(text(),'Next')])[1]
AccessaryUSBPortOptionOnPolicyCreationPage = [xpath]:(//input[@aria-label='Accessary USB Port'])[1]/../span


policySearch= [xpath]://input[@id='search']
policySearchItem1= [xpath]://tr/td[1]/a
policiesAssignmentTab= [xpath]:(//div[contains(text(),'Assignments')])[1]
selectGroupItem= [xpath]://tbody/tr[1]/td[1]/span[1]/label[1]/span[1]
assignGroupButton= [xpath]:(//span[normalize-space()='Assign'])[1]
assignGroupStatusButton= [xpath]:(//div[contains(text(),'Assigned')])[1]
actionmenuItemOnPolicy=[xpath]:(//*[contains(@class,'inactive')])[last()]
groupItem1=[xpath]://tr/td[1]
unAssignedPolicyMenuOption=[xpath]:(//span[normalize-space()='Unassign Group'])[1]
unAssignedBtn=[xpath]:(//span[normalize-space()='Unassign'])[1]
textGroupNameTobeFetched = [xpath]:(//*[contains(@class,'modal__close')]/following-sibling::div/div)[1]

groupPoliciesAssigned= [xpath]://div[@id='group-policiesAssigned']//div[@id='1']
groupScriptsAssigned= [xpath]://div[@id='group-scriptsAssigned']//div[@id]

idKey= [xpath]://tr[*]/td[3]/div/div
deviceNameSearchBox = [xpath]://input[@id='search-deviceName']
groupNameColumn = [xpath]://*[@id="name"]/div/button
groupNamelistkey= [xpath]://tr[*]/td[1]/div/div
modelNameSearchBox = [xpath]://input[@id='search-deviceModel']
noItemsAvailable = [xpath]://*[@class='wex-empty-state-widget']//h3
sortingAscendingArrowKey = [xpath]://span[text()='ascending sorted']
sortingArrowKey = [xpath]://span[text()='descending sorted']
listkey= [xpath]: //div[contains(@class,'wex-value-field-content')]/div[contains(@class,'wex-value-field-truncated')]/div[contains(@class,'wex-value-field-content')]/span/a
selectAllCheckBox = [xpath]://*[@name='SelectAllPage']


navigationItemDiv = [xpath]://*[@aria-label="Pagination Navigation"]
navigationItemList = [xpath]://*[@aria-label="Pagination Navigation"]//li
navigationItemNext = [xpath]://*[@aria-label="Pagination Navigation"]//button[@aria-label="Next"]
navigationItemPrevious = [xpath]://*[@aria-label="Pagination Navigation"]//button[@aria-label="Previous"]
navigationItemFrist = [xpath]://*[@aria-label="Pagination Navigation"]//li[2]
navigationItemLast = [xpath]:(//*[@aria-label="Pagination Navigation"]//li)[last()-1]
navigationItemActivePage =  [xpath]://*[contains(@aria-label,'Current Page')]
roomNameSearchList=[xpath]://table[@id='roomList']//tbody//tr//td[2]
propertyListOptions= [xpath]://li[@role='option']

groupTab = (//span[contains(text(),'Groups')])[1]
enterGroupName = [xpath]://*[@id="search-name"]
selectGroupName= [xpath]://a[contains(text(),'Automation Testing Pulse Engg Team - Don')][1]
groupCount=[xpath]://div[@id='1']
membershipTab = [xpath]://*[@id="group-membership"]
getDevice = [xpath]://div[@class='wex-value-field-content '][normalize-space()='DESKTOP-6G1OKB6']
entraIDRadioBtn = [xpath]://input[contains(@value,"ENTRAID")]/following-sibling::span
entraIDDropdownBox = [xpath]://div[@aria-controls="select-entra-group-listbox"]
groupNameDropdown = [xpath]://span[contains(text(),'Automation testing pulse engg grp - dont delete th')]
addGrpNextBtnEntraID = [xpath]://*[contains(@class,'wex-modal add-group')]//button[@id='next_profile-step_btn']
groupSearch = [xpath]://input[@placeholder="Search Group"]
dropdownOpen = [xpath]:(//div[@aria-label="Open"])[2]
windowsCheckBox = [xpath]://input[@id="chk-Windows"]
macCheckBox = [xpath]://input[@id="chk-Mac"]
membershipTypeCheck = [xpath]:(//div[text()="Entra ID"])[3]
selectedMemberDevicesCheck = [xpath]:(//div[text()='1'])[1]
selectedGroupCheck = [xpath]://div[contains(text(),'Automation testing pulse engg grp - dont delete th')]
entraIDErrorMessage = [xpath]://div[@class='info']
entraIDOption = [xpath]://li[@data-value='ENTRAID']
entraIDHeaderText = [xpath]://input[contains(@value,"ENTRAID")]/following-sibling::span[2]/p[1]
noResults = [xpath]://*[@class='state-title']

propertyListOptions= [xpath]://li[@role='option']
searchText = [css]:#search-type
devicesCountEntraGroup = [xpath]:(//*[contains(@id,'group-name')]/div[last()]//div)[last()-1]
groupsSelection = [xpath]://*[contains(@class,'wex-value-field-content')]/a
groupOptions = [xpath]://*[@id='search-type-listbox']/li//span


dynamicGroupsValueCreation = [xpath]://*[contains(@class,'radio-groups')]//span[contains(@class,'label')]/p[1]
dynamicGroupsDescriptionCreation = [xpath]://*[contains(@class,'radio-groups')]//span[contains(@class,'label')]/p[2]
staticGroupsValueCreation = [xpath]://*[contains(@class,'radio-groups')]//span[contains(@class,'label')]/p[3]
staticGroupsDescriptionCreation = [xpath]://*[contains(@class,'radio-groups')]//span[contains(@class,'label')]/p[4]
EntraGroupsValueCreation = [xpath]://*[contains(@class,'radio-groups')]//span[contains(@class,'label')]/p[5]
EntraGroupsDescriptionCreation = [xpath]://*[contains(@class,'radio-groups')]//span[contains(@class,'label')]/p[6]
DynamicGroupsRadioButton = [xpath]:(//*[contains(@class,'radio-groups')]//span[contains(@class,'radio-button')])[1]
StaticGroupsRadioButton = [xpath]:(//*[contains(@class,'radio-groups')]//span[contains(@class,'radio-button')])[3]
EntraGroupsRadioButton = [xpath]:(//*[contains(@class,'radio-groups')]//span[contains(@class,'radio-button')])[5]
OptionsList = [xpath]://li[contains(@id,'option')]
searchItems = [xpath]://*[contains(@placeholder,'Search Items')]
headersTextInStepper = [xpath]:(//*[@class='subtitle-regular'])[last()]
dynamicDescStep2 = [xpath]:(//*[@class='group-body']//p)[1]
propertyValueDropDown = [xpath]:(//*[contains(@id,'properties')])[last()]
operatorValueDropDown = [xpath]:(//*[contains(@id,'operator')])[last()]
selectedOperator = [xpath]:(//*[contains(@id,'operator')])[last()]
devicesActive = [xpath]://*[contains(@class,'text')]/span
valueDropDown = [xpath]:(//*[contains(@id,"value")])[last()]
selectedValue = [xpath]:(//*[contains(@id,"value")])[last()]
outerArea= [xpath]://div[contains(@id,'floating')]
calculateButton = [xpath]:(//*[text()='Recalculate']/..)[2]
activeDevicesHeader = [xpath]://*[text()='Active Devices']
addRuleButton = [xpath]://*[text()='Add Rule']
undeterminedStateText = [xpath]://*[text()='Undetermined']
reachNoteText = [xpath]://*[text()='You can calculate active devices after you add at least one rule']
progressBarDynamic = [xpath]:(//*[@role='progressbar'])[2]
RecalculateButtonEnabled = [xpath]:(//*[text()='Recalculate']/..)[2]/../button[contains(@type,"button") and @aria-disabled="false"]
selectedProperty = [xpath]:(//*[contains(@id,'properties')])[last()]
reviewGroupNameValue = [xpath]:(//*[contains(@id,'wex-details-section-field')]//div)[2]
reviewGroupDescValue = [xpath]:((//*[contains(@class,'group-description')])/p)[2]
reviewMemberShipValue = [xpath]:(//*[contains(@id,'wex-details-section-field-2')]//div)[4]
reviewPropertyValue = [xpath]:(//*[contains(@class,'dynamicrule-table')]//td)[2
reviewOperatorValue = [xpath]:(//*[contains(@class,'dynamicrule-table')]//td)[3
reviewValue = [xpath]:(//*[contains(@class,'dynamicrule-table')]//td)[4
reviewDeviceCount = [xpath]:(//*[contains(@id,'wex-details-section-field-3')]//div)[4]
reviewRulesHeader = [xpath]:(//*[text()='Dynamic Rules'])[last()]
notificationIcon = [css]:#notification-center-button
notificationOption = [xpath]://*[@id='wex-notifications']//*[@id='1']
topNotificationHeader = [xpath]:(//*[contains(@class,'notification-center-item')])[1]//*[@id='wex-value-id']
topNotificationValue = [xpath]:(//*[contains(@class,'notification-center-item')])[1]//*[contains(@class,'notification_item_content')]//span

assignmentTab = [css]:#group-assignments
noAssignments = [xpath]://*[@class='wex-empty-state-widget-text']/div[1]
noAssignmentsInnerSection = [xpath]://*[@class='wex-empty-state-widget']/div[2]
assignButton = [xpath]://div[contains(@class,'wex-empty')]//button
policyOption = [xpath]:(//*[contains(@id,'wex-menu-list-item')])[1]
scriptsOption = [xpath]:(//*[contains(@id,'wex-menu-list-item')])[2]
assignmentEntry = [xpath]://*[contains(@class,'device-list-container')]//tbody/tr[position()=1]

#LDKProd
groupAddTitle = [xpath]://*[@id="grouping-addbtn"]
groupNameColumn = [xpath]://*[@id="name"]
groupNumberColumnValues = [xpath]:(//*[@class="dui-hyperlink text-overflow-ellipsis"])[1]
groupDetailsName = [xpath]://*[@class="summarycard-group-title"]
groupinformation = [xpath]://div[@id="group-information"]
groupmembership = [xpath]: //div[@id="group-membership"]
groupAssignments = [xpath]://div[@id="group-assignments"]
groupDelete = [xpath]://button[@id="grouping-deletebtn"]
groupExport = [xpath]://button[@id="grouping-exportbtn"]

groupNameTitle = [xpath]: (//div[starts-with(@id, 'floating-ui-')]//div)[7]
dynamicRules = [xpath]:(//input[@id='grouping-radiobutton-dynamic-groups']/following-sibling::span/p)[1]
staticAssignment= [xpath]:(//input[@id='grouping-radiobutton-static-groups']/following-sibling::span/p)[1]
entraID = [xpath]:(//input[@id='grouping-radiobutton-entraid-groups']/following-sibling::span/p)[1]
groupNextButton = [xpath]://*[@id="next_profile-step_btn"]
groupcancelButton = [xpath]://button[@id="profile-step_cancel-btn"]