signInButton = [id]:btn-idplogin-signin
cookieAccept = [css]:#onetrust-accept-btn-handler
hpLogo = [xpath]://div[@class='wex-onboarding-header']/img
languageHeader = [css]:div.wex-onboarding-lang-header
signinTitle = [css]:.wex-onboarding-title
signinBelowText = [css]:.wex-onboarding-desc
emailInputBox = [css]:#email
remeberMeText = [css]:.vn-checkbox__span--text
remenbermecheckBox = [xpath]://div[@class='wex-onboarding-rememberme']//label//span[1]
continueButton = [css]:button.wex-onboarding-button
sliderImg = [css]: .wex-onboarding-slider-item img
sliderHeaderText = [css]:.wex-onboarding-slider-title
sliderDescText = [css]:.wex-onboarding-slider-desc
belowfootersection = [css]: span.wex-onboarding-footer-text
leftSliderBtn = [xpath]: (//div[@class="wex-onboarding-slider-btn-bg"]/button)[1]
rightSliderBtn = [xpath]: (//div[@class="wex-onboarding-slider-btn-bg"]/button)[2]
sliderCircleBtn = [css]: button.wex-onboarding-slider-btn-circle
termsAndConditionLink = [xpath]: (//span /a)[1]
privacyLink = [xpath]: (//span /a)[2]


#new login page elements
Hplogologinpage = [xpath]://img[@alt='logo']
languagedropdown = [css]:div.wex-header-lang-selection
applicationheading = [id]:application-header
createaccounttext = [id]:create-account
createaccountlink = [xpath]://span[@id='create-account']//a
emailtextbox1 = [id]:email
signinbutton1 = [id]:sign-in-button
remembermetext = [id]:remember-me
termsandconditionlink1newpage = [xpath]://a[contains(text(),'Terms and Conditions')]
privacylinknewpage = [xpath]://a[contains(text(),'Privacy')]




