addButton = [xpath]://div[@class='action-area']/button
addButtonOptions = [xpath]://div[@class="orders-list-table"]//div[@class="action-area"]//ul[@role="menu"]//li
newOrderOption = [xpath]://span[contains(text(),"New Order - Active Care")]//parent::li[@role="menuitem"]
deviceTransferOption =[xpath]://button/span[contains(text(),"Device Transfer")]
resellerUpdateOption =[xpath]://button/span[contains(text(),"Reseller Update")]
removeLicenseOption =[xpath]://button/span[contains(text(),"Remove License")]
dataCollectionOption =[xpath]://button/span[contains(text(),"Data Collection")]
resellerUploadLabel= [xpath]://*[@id="order-file-input-label"]

addOrderTitle = [xpath]://div[@aria-modal="true"]/h4
addOrderSubtitle = [xpath]://div[@aria-modal="true"]//div[@class="add-orders"]/p[1]
addOrderDescription = [xpath]://div[@aria-modal="true"]//div[@class="add-orders"]/p[2]
addDeviceTransferTitle=[xpath]://div[@aria-modal="true"]/h4
downloadSampleFileLink = [id]:download-sample
cancelOrderButton = [id]:cancel-order
importOrderButton = [id]:import-order
fileImport = [xpath]://input[@type="file"]
columnHeaderNames = [xpath]://table//tr/th/div
allRowCount = [xpath]://div[@class="orders-list-table"]//table//tbody/tr
eachRowValues = [xpath]://table//tbody/tr[%s]/td
eachRowFileName = [xpath]://table//tbody/tr[%s]/td/a
eachRowDateTime = [xpath]://div[@class='orders-list-table']//table//tbody/tr[%s]/td[2]
eachRowNumberOfOrders = [xpath]://div[@class='orders-list-table']//table//tbody/tr[%s]/td[3]
firstRowNumberOfOrders = [xpath]://div[@class='orders-list-table']//table//tbody/tr[%s]/td[3]
eachRowStatus = [xpath]://div[@class='orders-list-table']//table//tbody/tr[%s]/td[4]
firstRowStatus = [xpath]://div[@class='orders-list-table']//table//tbody/tr[1]/td[4]
eachRowSource = [xpath]://div[@class='orders-list-table']//table//tbody/tr[%s]/td[5]
eachRowState = [xpath]://div[@class='orders-list-table']//table//tbody/tr[%s]/td[5]
firstRowState = [xpath]://div[@class='orders-list-table']//table//tbody/tr[1]/td[8]
eachRowSummaryFile = [xpath]://div[@class='orders-list-table']//table//tbody/tr[%s]/td[6]/span
defaultPaginationButton = [xpath]://button[@aria-label='Select page size']
PaginationOptions = [xpath]://div[@class='orders-list-table']//div[@role='presentation']//ul[@role='menu']/li
paginationNextButton = [xpath]://nav[@aria-label='Pagination Navigation']//li/button[@aria-label="Next"]
paginationPreviousButton = [xpath]://nav[@aria-label='Pagination Navigation']//li/button[@aria-label="Previous"]
orderssummary =[xpath]:(//table//tbody/tr/td[text()='Completed'])[1]//following-sibling::td[3]
eachrowOrderSummaryFile =[xpath]://tr[%s]//span[contains(@class,"table-item-button")]
downloadToastMessage = [xpath]://div[@role='alert']
searchField = [xpath]://input[@id="search"]
dateTimeField = [xpath]://input[@id="date_picker"]
statusDropdown =[xpath]://tr[2]//th[4]//div[@role="combobox"]
statusDropdownOptions = [xpath]://ul[@role="listbox"]//li
sourceDropdwon =[xpath]://tr[2]//th[5]//div[@role="combobox"]
clearfilters =[xpath]://button[@aria-label="Clear Filters"]
typeDropdown = [xpath]://tr[2]//th[6]//div[@role="combobox"]
#typeDropdownOptions = [xpath]://ul[@id="vn-select-21-listbox"]//li
firstRowOrderType=[xpath]://div[@class='orders-list-table']//table//tbody/tr[1]/td[3]
DTStateDescriptionMsg=[xpath]://table//tbody//tr//td[5]
DTSubStateMsg=[xpath]://table//tbody//tr//td[4]
DTStateMsg=[xpath]://table//tbody//tr//td[3]

orderDetailsFileType =[xpath]://*[@id="orderType"]
orderDetailsState =[xpath]://td[3]/span
firstRowFileName = [xpath]://table//tbody/tr[1]/td/a
returnToOrderListPageButton = [xpath]://span[contains(text(),"File List")]/ancestor::button[@type="button"]