PartnerMenu= [xpath]://*[@id="menu_partners"]
Partners= [xpath]://*[@id="menu_partners_partners"]
countryDropdown= [id]:select-country
countryList= [xpath]://ul[@role="listbox"]
idpDropdown= [xpath]://*[@placeholder="Select IDP"]
idpList= [xpath]://*[contains(@id,"floating-ui")and(@role="listbox")]/li[1]
createButton= [xpath]://*[@id="oobe-sign-up-submit"]
Customers= [xpath]://li[@role="Companies"]
Companies= [xpath]://*[@id="menu_customers_partnerCompanies"]