#LicenseTier
EliteCustomer= [id]:dndelite
CustomerLicense= [id]:licenses-customer
TierUpgrade= [xpath]:(//*[@id="extended-licenses-customer"]//button)[2]
DNDStandard= [id]:dndstandard
DNDPro=[id]:dndpro
TierUpgradeHeading =[xpath]: //*[@id="license-upgrade-tier-modal-label"]
TierUpgradeDesc= [xpath]://*[@id="license-upgrade-tier-modal"]/div[1]
CustomerSearch= [id]:customerName-search
CustomersTab = [id]:menu_companies
StandardHeading=[xpath]: //*[@id="standard-card-content"]//div/h6
StandardDescription1=[xpath]: //*[@id="standard-card-content"]//div/p[1]
StandardDescription2=[xpath]://*[@id="Hardware and Software Inventory"]
StandardDescription3=[xpath]://*[@id="Windows 11 Readiness"]
StandardDescription4=[xpath]://*[@id="API Access"]
StandardDescription5=[xpath]://*[@id="Remediations & Automations (BIOS policy only)"]
StandardDescription6=[xpath]://*[@id="Experience Analytics (Limited)"]
StandardDescription7=[xpath]://*[@id="Employee Surveys and Notifications (Limited)"]
StandardDescription8=[xpath]://*[@id="Third-Party Integrations (Limited)"]
ProHeading=[xpath]://*[@id="pro-card-content"]//div/h6
ProDescription2=[xpath]://*[@id="pro-card-content"]//div/p[2]
ProDescription3=[xpath]://*[@id="Experience Analytics"]
ProDescription4=[xpath]://*[@id="Employee Surveys and Notifications"]
ProDescription5=[xpath]://*[@id="Configurable Monitoring and Alerting"]
ProDescription6=[xpath]://*[@id="Smart Device Refresh"]
ProDescription7=[xpath]://*[@id="Natural Language Search (Limited) "]
ProDescription8=[xpath]://*[@id="AI-enabled"]
EliteHeading=[xpath]://*[@id="elite-card-content"]//div/h6
EliteDescription1=[xpath]://*[@id="elite-card-content"]//div/p[1]
EliteDescription2=[xpath]://*[@id="elite-card-content"]//div/p[2]
EliteDescription3=[xpath]://*[@id="Natural Language Search (Unlimited)"]
EliteDescription4=[xpath]://*[@id="Free Text Sentiment Analysis "]
EliteDescription5=[xpath]:(//*[contains(@id, 'AI-enabled')])[2]
SeeDetailsButton=[xpath]://*[@id="license-upgrade-tier-modal"]//button





