liscenceAndSubscriptionSideMenu = [id]:menu_partnerLicenses
SelectedCustomer = [xpath]://*[@id="wex_cs_btn_expanded"]/span/div/div
whatsNewPopupClosedButton= [xpath]: //button[@aria-label="Close"]
subscriptiontab =[id]:wex_horizontal_menu_partnerSubscriptions
assignSubscriptionButton =[xpath]://button[.//span[text()='Assign subscription']]
assignSubscriptionTitle =[xpath]://h4[@id='assign-subscription-label']
assignSubscriptionsubTitle =[xpath]://*[contains(text(),'Assign a subscription')]
customertitle = [xpath]://label[span[text()='Customer']]
ChoosecustomerDropdown = [css]:input[placeholder='Choose customer']
customernameoption =[xpath]:(//ul[@role='listbox']//li[@role='option'])[1]
PlanText =[xpath]://label[span[text()='Plan']]
planDropdown = [css]:input[placeholder='Choose plan']
planoption =[xpath]://div[contains(@class,'_vn-card')]//li[contains(@class,'vn-option')]
StartDateText =[xpath]://label[span[text()='Start date']]
StartDateInput=[xpath]:(//input[@id='date_picker'])[1]
EndDateText =[xpath]://label[span[text()='End date (Optional)']]
EndDateInput=[xpath]:(//input[@id='date_picker'])[2]
EndpointText =[xpath]://label[span[text()='Endpoints']]
EndpointInput=[xpath]://input[@placeholder='Enter number']
Savebutton =[xpath]://button[.//span[text()='Save']]
Cancelbutton =[xpath]://button[.//span[text()='Cancel']]
Revokebutton =[id]:revoke-subscription-contract
RevokeTitle=[xpath]://h4[@id='revoke-subscription-label' and text()='Revoke Subscription']
RevokesubTitle=[xpath]://p[contains(text(),'Are you sure you want to delete this subscription?')]
Securitycode =[id]:security-code-number
securitycodeinput =[xpath]://input[@id='security-code']
revokebuttoninside =[xpath]://div[contains(@class,'vn-modal')]//span[text()='Revoke']/parent::button
firstcheckbox =[xpath]://input[@aria-label='0']/ancestor::label[1]
revokesubscriptitle =[xpath]://div[@data-toast='true']//div[contains(text(),'Subscription Revoked')]
revokesubtext = [xpath]://div[@data-toast='true']//div[contains(text(),'Subscription revoked successfully')]
subassignedtitle = [xpath]://div[@data-toast='true' and .//div[text()='Subscription Assigned']]
subassignedtext =[xpath]://div[@data-toast='true']//div[@class='css-1d27zd4' and text()='Subscription assigned successfully']
editcompanysub = [xpath]://span[normalize-space(text())='DNDAutomationcompany1311']
CustomerSearchBox = [xpath]:(//input[@id='table-name-filter'])[2]
searchresultfirstrow = [xpath]://input[@aria-label='0']/ancestor::label[1]
editSubscButton =[id]:edit-subscription-contract
editsubscriptiontext =[xpath]://h4[normalize-space()='Edit Subscription']
editsubscriptionsubtext =[xpath]://div[normalize-space()='Update the subscription details.']
EndpointInputedit =[xpath]://input[@placeholder='Enter number']
editSavebutton =[xpath]://button[normalize-space()='Save']
editToastNotification =[xpath]://div[@data-toast='true' and @aria-hidden='false']
subscriptiontabaccount=[id]:subscription-customer
companytabsidemenu=[id]:menu_companies
companysearchboxcustomer=[xpath]://input[@id='customerName-search']
companynametocheck=[id]:tsubscribitiondonotdeleteaccount1711
subscrpTitle=[xpath]://h3[text()='Subscriptions']
subscriptionCard=[xpath]://div[contains(@class,'wexcard-container') and contains(@class,'bordered-card')]
SubscriptionDetailheader=[xpath]:(//h3[normalize-space(.)='Subscription Details'])[1]
Activestatus=[xpath]://div[text()='Active'][1]
clearfiltercust=[xpath]://button[@aria-label='Clear Filters']
arrowcust =[xpath]://input[@placeholder='Choose customer']/following::div[1]
Planarrow=[xpath]://input[@placeholder='Choose plan']/following::div[1]