PulselistBanner =  [xpath]://div[@class='pulses-header']/*[last()]
CreateButton = [xpath]://div[@class='pulse-surveys-list-card']//button
CustomPulseContextualMenuSection = [id]:custom_pulse
Createfromscratch = [xpath]://h3[text()='Create from scratch']//parent::div
SentimentPulseContextualMenuSection = [id]:sentiment_pulse
CustomPulseContextHeader = [xpath]:((//div[contains(@class,'contextual-menu')])[1]//li//div/*[position()=1])[1]
SentimentPulseContextHeader = [xpath]:((//div[contains(@class,'contextual-menu')])[1]//li//div/*[position()=1])[2]
CustomPulseContextDescription = [xpath]:((//div[contains(@class,'contextual-menu')])[1]//li//div/*[position()=2])[1]
SentimentPulseContextDescription = [xpath]:((//div[contains(@class,'contextual-menu')])[1]//li//div/*[position()=2])[2]
firstLatestPulselist = [xpath]:(//a[contains(@class,'dui-hyperlink')])[1]
#CreationtoastNotification = [xpath]://*[@id="dui-app-scroll"]/div[2]/div/div[1]/div
CreationtoastNotification = [xpath]://div[@role='status']//div[contains(@id,'toast-title')]
CreationtoastNotificationViewButton = [xpath]:(//*[@id="dui-app-scroll"]/div[3]/div/div)[2]/button/*
creatFrmScratchButton = [xpath]://[@id='pulse_template_btn_create_from_scratch']/div/div[2]

sentimentScore = [xpath]://*[@id="ee_dashboard_sentimentScore"]/div/div[1]
sentimentExpScoreOvertime = [xpath]://*[@id="wex-score-over-time"]//h6//div[1]
topIssueImpactingSentiment = [xpath]://*[@id="top_issue_impacting_sentiment"]/div[1]/div[1]
allPulses = [xpath]://*[@id="ee_dashboard_EmployeeEngPulses"]/div/div[1]
allPulsesData = [xpath]://*[@id="ee_dashboard_EmployeeEngPulses"]
sentimentProgressBar = [xpath]://*[@class='sentiment-score-progress-title']
responseSentimentPulse = [xpath]://*[@class='employee-eng-response-item-right']
empEngagemendDashboard =[xpath]://*[@id="menu_employeeEngagement_employeeEngagementDashbaord_link"]/span
firstPulseSelectionCheckbox = [xpath]:(//*[contains(@class,'table__selector')])[2]
duplicateButtonListingPage = [xpath]:(//*[contains(@id,'btn_pulse_duplicate')])[2]
firstRow = [xpath]:(//table//tr)[2]
firstRowElipsce = [xpath]:(//table//tr//td//button)[1]
duplicateButtonElipsceSelection = [xpath]://*[@id='wex_menu_item_duplicate']
deleteButtonElipsceSelection = [xpath]://*[@id='wex_menu_item_delete']
resultsActionButton = [xpath]://button[@aria-label="Actions"]
resultsStatusText = [css]:.status-label
#deleteButtonListingPage = [xpath]:(//*[contains(@id,'btn_pulse_delete')])[2]
deleteButtonListingPage = [xpath]:(//*[contains(@id,'btn_pulse_delete')])
DuplicateButton = [xpath]:(//*[text()='Duplicate'])[last()]
deleteButton = [xpath]:(//*[text()='Delete'])[last()]
pulseTypeHeader = [css]:#pulseType
firstValuePulseType = [xpath]://tr[1]//td[last()-4]
checkBoxSelectionList = [xpath]:(//*[contains(@class,'table__selector')]/span)[position()>1 and position()<4]
allSelectionCheckbox = [xpath]:(//*[contains(@class,'table__selector')]/span)[position()=1]
editButtonListingPage = [xpath]:(//*[@id='btn_pulse_edit'])[2]
pulseListPageBreadCrumbsNew = [xpath]:(//*[contains(@class, 'breadcrumb-text')])[2]
pulsesBreadCrumbsNew = [xpath]://*[contains(@class, 'wex-breadcrumb')]//div[2]
pulsesBreadCrumbsOldEMPENGMT = [xpath]://*[contains(@class, 'wex-breadcrumbs')]//li[1]
pulsesBreadCrumbsOld = [xpath]://*[contains(@class, 'wex-breadcrumbs')]//li[2]