PartnerTopMenu = [xpath]://*[@id="menu_partners"]
PartnersInMenu = [xpath]://*[@id="menu_partners_partners"]
ClearFilterbutton= [xpath]: //button[@aria-label='Clear Filters']
partnerNameSearch =[xpath]:(//a[contains(@class,'wex-link') and contains(@class,'text-overflow-ellipsis')])[1]
subscriptionAuthorizedSection=[xpath]://div[@id='contract-authorized']
EmailSerchBox =[xpath]:(//*[@id="email"])[2]
subscriptionAuthorizedTogglepartner=[xpath]://div[@id='contract-authorized']//input[@type='checkbox']
subscriptionContract =[id]:PartnerSubscriptionContracts
AddButtonSub=[xpath]://button[.//span[text()='Add']]
AddSubscriptionTitle=[id]:contract-add-modal-label
AddSubscriptionSubTitle=[xpath]://h4[text()='Enter the contract information']
contractId =[id]:text
CountryIDDropdown =[id]:country
IndOption =[xpath]:(//li[@role='option' and @aria-disabled='false'])[1]
PaymentTerm =[id]:paymentTerms
ContractdateTitle =[xpath]://h6[text()='Select contract dates']
StartDate =[id]:startDate
ContractNextbutton =[id]:contract-save
SubTitlesteptwo =[xpath]://div[@id='contract-add-modal']//h4[contains(text(),'Select plans and their cost per seat')]
PlanIDSearch =[xpath]:(//input[@id='planId'])[INDEX]
PaymentTermTitle =[id]:paymentTerms-label
PlanIDOption =[xpath]://span[normalize-space()='SKU-WXP-PRO-DAAS-TEST - Workforce Experience Pro']
SeatsInput =[id]:costPerSeat
SavebuttonContract =[id]:contract-save
CancelbuttonContract =[id]:contract-cancel
BackbuttonContract =[id]:contract-previous
Menubutton =[xpath]:(//button[@aria-label='action menu'])[1]
Editbutton =[xpath]://div[@id='wex_menu_item_edit']//button
Deletebutton =[xpath]://div[@id='wex_menu_item_remove']//button
deletetitlecontract =[xpath]://h4[@id='contract-remove-modal-label']
deletesubtitlecontract =[xpath]://div[@id='contract-remove-modal']//p
securitycodecontract =[id]:security-code-number
securitycodecontractinput =[xpath]://input[@id='security-code']
revokeButtoncontract =[id]:contract-remove
cancelbuttoncontract =[id]:contract-cancel
RenueCheckbox =[xpath]://input[@type='checkbox']/parent::label
AddAnotherPlanButton =[xpath]://a[contains(text(), 'Add another plan')]
EndDateInput =[id]:expires
seatcostinput =[id]:costPerSeat
SeatsInput1 =[xpath]:(//input[@id='costPerSeat'])[1]
SeatsInput2 =[xpath]:(//input[@id='costPerSeat'])[2]
SeatsInput3 =[xpath]:(//input[@id='costPerSeat'])[3]
PlanInput1 =[xpath]:(//div[contains(@class,'ComboboxTrigger')])[2]
PlanInput2 =[xpath]:(//input[@id='planId'])[2]
PlanInput3 =[xpath]:(//input[@id='planId'])[3]
Planoption2 =[xpath]:(//li[@role='option' and @aria-disabled='false'])[2]
Planoption3 =[xpath]:(//li[@role='option' and @aria-disabled='false'])[3]   
Planoption4 =[xpath]:(//li[@role='option' and @aria-disabled='false'])[4]