customerFilter = [id]:wex_cs_btn_expanded
SelectedCustomer = [xpath]://*[@id="wex_cs_btn_expanded"]/span/div/div
SelectedCustomerLowResolution = [id]:wex-menu-list-item
whatsNewPopupClosedButton= [xpath]: //button[@aria-label="Close"]
searchBox = [xpath]://*[@id="search"]
customerFilterCompany = [xpath]: (//*[contains(@id, "wex_menu_item")]/li)[2]

# Customer Table
customerNameColumn = [xpath]: (//*[text()='Customer Name'])[1]
experienceScoreColumn = [xpath]://*[@class="wexScore"]
proEndpointsColumn = [xpath]://*[text()='Pro Endpoints']
locationColumn = [xpath]://*[@class="location"]
statusColumn = [xpath]://*[@class="status"]

# Customer Filters
customerNameFilterDropdown1 =[xpath]:(//div[@aria-label='Open' and @title='Open'])[1]
clearAllFilterButton =[xpath]://*[@class="wexcard-header-action"]/button
customerNameFilterDropdown =[xpath]:(//*[@id="select-multiple-usage"])[1]
customerNameSearchBox =[xpath]://input[@placeholder="Search Items"]
SelectCustomerName =[xpath]://*[@id="select-multiple-usage-option-0"]
listDropdown = [xpath]://ul[@id='select-multiple-usage-listbox']/li

customerNameValue = [xpath]://div[contains(@class,"wex-company-list-item-title")]
customerPlanValue = [xpath]: (//div[@class="wex-tag-content multiple"])[1]
customerExperienceScoreValue =[xpath]:(//div[@class="wex-score-column-icon-title"])[1]
customerProEndpointsValue =[xpath]:(//div[@class="wex-list-default wex-list-item-container"]/div[3])[1]
customerLocationValue =[xpath]:(//span[@class="wex-company-list-location"])[1]
statusValue =[xpath]://*[contains(@class,"status-icon")]/following::div[1]
ellipsisButton =[xpath]://*[@class="contextualMenuIcon"]/button
viewCustomerDashboardButton =[xpath]:(//*[@id="wex_menu_item_1"]/li)[1]
viewCustomerProfileButton =[xpath]:(//*[@id="wex_menu_item_2"]/li)[1]
updateLocationButton =[xpath]:(//*[@id="wex_menu_item_1"]/li)[2]
deleteCustomerButton =[xpath]:(//*[@id="wex_menu_item_2"]/li)[2]


# Customer Details
customerNameOnDetailsPage = [xpath]: //h2[@class="dui-dsummary-card-title"]
cityValueOnDetailsPage = [xpath]: (//*[@id="namePanel"]//div)[6]
stateValueOnDetailsPage = [xpath]: (//div[@class="dui-summary-card-icons"]//div)[3]
deleteCustomerButtonOnDetailsPage = [xpath]: //*[@id="delete-tenant-btn"]
removeCustomerButtonOnDetailsPage = [xpath]: //*[@id="delete-tenant-btn"]
resendInviteButtonOnDetailsPage = [xpath]: //*[@id="re-send-invite-btn"]
overviewTab = [xpath]: //*[@id="overview"]/div
companyProfileheader = [xpath]: //*[@id="company-profile-header"]
customerId = [xpath]: //*[@id="display-id"]/div[1]
customerIdValue = [xpath]: (//*[@id="display-id"]//div)[7]
CustomerName = [xpath]: //*[@id="company-name"]/div[1]
customerNameVal = [xpath]: (//*[@id="company-name"]//div)[7]
companySize = [xpath]: //*[@id="company-size"]/div[1]
companySizeVal = [xpath]: (//*[@id="company-size"]//div)[7]
createdOn = [xpath]: //*[@id="createdOnPanel"]/div[1]
createdOnVal = [xpath]:(//*[@id="createdOnPanel"]//div)[7]
preferredTimezone = [xpath]: //*[@id="company-timezone"]/div[1]
preferredTimezoneVal = [xpath]: (//*[@id="company-timezone"]//div)[7]

editComanyNameButton = [xpath]://*[@id="edit-company-name"]
CompanyNameOnPopUp= [xpath]://*[@id="dui-text-modal-label"]
CompanyNameLabelOnPopUP=[Id]:dui-text-modal-text-box-label


# Customer Dashboard Page from partner login
customerNameOnAccountManagement =[xpath]: //h2[@class="dui-dsummary-card-title"]
customerNameOnAccountManagementPage =[xpath]: //h2[@class="dui-dsummary-card-title"]
planOnCustomerPage =[id]: summary-card-plan-value
customerStatusOnCustomerPage =[xpath]: //div[text()='Active']
cityOnCustomerPage =[xpath]: (//*[@id="namePanel"]//div)[6]
accountManagerTab =[id]: menu_accountManagement_link
CustomerSelected= [xpath]: (//*[@id="wex-menu-list-item"])[2]

searchCompany =[xpath]://input[@placeholder="Search Items"]
valueCompany =[xpath]://*[@id="select-multiple-usage-option-0"]


CustomerSideMenu = [id]:menu_companies
customerTextOnCustomerTab=[xpath]://*[@id="companiesList"]//nav//span
CustomerTextOnCustomerTable= [xpath]: //div[@class="customerName"]
ExpScoreTextOnCustomerTable= [xpath]: //div[@class="wexScore"]
ProEndPntTextOnCustomerTable=[xpath]: //div[@class="proEndpoints"]
LocationTextOnCustomerTable=[xpath]: //div[@class="location"]
StatusTextOnCustomerTable=[xpath]: //div[@class="status"]
Invitees=[id]:invites
AddButtonCustomers=[xpath]:(//*[@id="customer-list-tabs-customers"]//div/button)[1]
Step1=[id]:customer-add-popup-step1
CompanyNameLabel=[id]:company-name-label
Addressline1=[id]:address-line-1-label
Addressline2=[id]:address-line-2-label
CityLabel=[id]:city-label
RegionLabel=[id]:region-label
ZipCodee=[xpath]://*[@id="zipcode-label"]
CountryLabel=[id]:company-country-label
CustomerSubject=[id]:customers
AddCustomerModal= [id]:modal_company_info-label
CompanyName=[xpath]://*[@id="company-name-label"]/span
CancelPopup=[id]:btn_cancel
InviteButton=[xpath]:(//*[@id="customer-list-tabs-invites"]//div/button)[1]
SendInviteLabel=[id]:modal_company_invite-label
InviteesDescription=[xpath]://*[@id="modal_company_invite"]//div/p
CustomerIDInput=[id]:customer-id-input-label
ModalInviteButton=[id]:btn_invite
ModalCancelInvite=[id]:btn_cancel

CustomerColumn=[id]:customerName
PlanColumn=[id]:customerplans
StatusColumn=[id]:status
ExperienceScoreColumn=[id]:wexScore
LocationColumn=[id]:location
CustomerSearch1= [id]:customerName-search
EliteCustomers= [id]:dndelite
ActiveStatus=[xpath]://*[@id='active-company-list-table']//td[3]/div

#PartnerDashboard
sideMenuToggleButton = [id]:wex_sm_expand_btn
toggleButtonOpen = [id]:wex_sm_collapse_btn
toggleButtonClose = [id]:wex_sm_expand_btn
smallResolutionFilterButton = [id]:wex_cs_btn_collapsed
#Invitation Popup on login 
invitationPopupModalTitle = [id]:partner-invite-modal
invitationPopupModalClose = [xpath]: //div[@id='partner-invite-modal']/following-sibling::button[@aria-label='Close modal']


