SelectedCustomer = [xpath]://*[@id="wex_cs_btn_expanded"]/span/div/div
whatsNewPopupClosedButton= [xpath]: //button[@aria-label="Close"]
settingsideMenu =[id]:menu_settings
CustomizeHelpandSupportPageTab =[id]:customization
CustomerHelpandSupportPageTitle =[id]:customer-help-&-support
submitHelpToggle = [id]:custom-help
CustomURLBox =[id]:supportURLOptionSelected
SupportRequestBox =[id]:supportEmailOptionSelected
SupportTeamEmailLabel =[id]:support-team-email-label
SupportURLLabel =[id]:support-url-label
SupportURLedit =[id]:support-url-edit-icon
SupportTeamedit =[id]:support-team-email-edit-icon
SupportTeamEmailHeader =[id]:support-team-email-modal-heading
SupportTeamEmailSubHeader =[id]:support-team-email-modal-subdescription
CustomerSupportHeader =[id]:support-team-email-textbox-label
SupportTeamEmailText =[id]:support-team-email-textbox
CustomURLHeader =[id]:custom-url-modal-heading
CustomSubHeader =[id]:custom-url-modal-subdescription
CustomerURlHeader =[id]:custom-url-textbox-label
CustomTextBox =[id]:custom-url-textbox
SaveButtonCustom = [xpath]://button[.//span[text()='Save']]
CancelButtonCustom = [xpath]://button[.//span[text()='Cancel']]
HelpandSupportMenu =[id]:help-support-button
NeedAssistanceText =[id]:needs-assistance-heading
NeedAssistanceSubText =[id]:settings-custom-support-desc
GetSupportButton =[id]:get-support-button
SupportTeamMainHeader =[id]:partner-help-and-support-header
SubjectHeader =[id]:email-subject-input-label
SubjectTextBox =[id]:email-subject-input
CategoryHeader=[id]:select-service-label
CategoryDropdown =[xpath]://input[@id='select-service']
DropDownSecondOption = [xpath]:(//li[@role='option' and @aria-disabled='false'])[2]
CategoryOptionOther =[xpath]://li[@role='option']//span[normalize-space()='Other']
SupportTypeHeader =[id]:select-support-type-label
SupportTypeDropdown =[xpath]://input[@id='select-support-type']
SeverityHeader =[id]:select-severity-label
SeverityDropdown =[xpath]://input[@id='select-severity']
SupportTypeOptionTechnical =[xpath]://li[@role='option']//span[normalize-space()='Onboarding & setup']
UploadFileHeader =[id]:email-file-picker-label
DescriptionHeader =[id]:email-desc-label
DescriptionTextBox =[id]:email-desc
SubmitRequestButton =[id]:submit-hp-email
passowrdTextBox=[id]:password