#Partner Subscription



wepSubscriptionTab = [css]: #subscription > div
currentPlan = [css]: #current-plan
currentPlanName = [css]: #current-plan-name
usedSeats = [css]: #seats-used
planstatus = [css]: #plan-status
future-wep-offerings = [css]: #future-wep-offerings
future-wep-subtext = [css]: #future-wep-offerings-subtext
basicPlan = [css]: #plan-basic
basicPlanCost = [css]: #plan-basic-cost
wepBasicPlanIncludes = [css]: #plan-basic-include-text
assetInventory = [css]: #plan-basic-module-text-0
warrantyStatus = [css]: #plan-basic-module-text-1
PCBIOSPolicy = [css]: #plan-basic-module-text-2
PCWindows11Upgradestatus = [css]: #plan-basic-module-text-3
antivirusStatus = [css]: #plan-basic-module-text-4
proPlan = [css]: #plan-pro
proPlanCost = [css]: #plan-pro-cost 
proPlanText= [css]: #plan-pro-include-text
PCInsightstoActions = [css]: #plan-pro-module-text-0
EnterprisePrintTelemetry = [css]: #plan-pro-module-text-1
collaborationTelemetry = [css]: #plan-pro-module-text-2
peripheralInventory = [css]: #plan-pro-module-text-3
automatedPulses = [css]: #plan-pro-module-text-4
configurableScoring = [css]: #plan-pro-module-text-5
actionableChoices = [css]: #plan-pro-module-text-6
wepEnterprise = [css]: #plan-enterprise
wepEnterprisetext = [css]: #plan-enterprise-include-text
contact-hp-sales  = [css]: #contact-hp-sales
subscriptionMgt  = [css]: #subscription-mgt
subscription-mgt-title  = [css]: #subscription-mgt-title
subscriptionMgtSubtitle  = [css]: #subscription-mgt-subtitle
go-to-aws-marketplace  = [css]: #go-to-aws-marketplace