SelectedCustomer=[xpath]://*[@id="wex_cs_btn_expanded"]/span/div/div
whatsNewPopupClosedButton=[xpath]://button[@aria-label="Close"]
experienceSnapshotHeader=[xpath]://div[normalize-space()='Experience Snapshot']
GreatExperienceTab=[id]:wex-scores-content-Great
FairExperienceTab=[id]:wex-scores-content-Fair
PoorExperienceTab=[id]:wex-scores-content-Poor
GreatExperienceCount=[xpath]://*[@id='wex-scores-content-Great']//div[contains(@class,'wex-score-company-count')]//h3
FairExperienceCount=[xpath]://*[@id='wex-scores-content-Fair']//div[contains(@class,'wex-score-company-count')]//h3
PoorExperienceCount=[xpath]://*[@id='wex-scores-content-Poor']//div[contains(@class,'wex-score-company-count')]//h3
GreatTotalCustomers=[xpath]://*[@id='wex-scores-content-Great']//p[contains(text(),'customers')]
FairTotalCustomers=[xpath]://*[@id='wex-scores-content-Fair']//p[contains(text(),'customers')]
PoorTotalCustomers=[xpath]://*[@id='wex-scores-content-Poor']//p[contains(text(),'customers')]
RemainingInfoButton=[xpath]:(//div[contains(@class,'wexcard-header-trailing')]//button)[1]
ExperienceTableRows =[xpath]://tbody//tr
ExperienceTable = [id]:active-company-list-table
HomePageTab =[id]:menu_home
CustomerTab=[id]:menu_companies
ClearfilterExperience =[xpath]://button[@aria-label='Clear']