planRows = [xpath]://div[@class='plan-list']/div
planName = [xpath]:.//h2[contains(@class,'wexcard-header-title')]/div/div[1]
usedSeats = [xpath]:.//div[contains(@class,'wexcard-content')]//div[contains(text(),'of') and contains(text(),'endpoints')]
overEnrollmentBannerName = [xpath]://div[contains(@class,'notification-title')]
nextArrow = [xpath]:(//div[@class='slider-actions']/div/*[local-name()='svg'][contains(@class,'chevron-icon') and not(contains(@class,'disabled-chevron'))]/*[local-name()='path'])[last()]
printersTab = [id]:wex_horizontal_menu_printers
proxiesTab = [id]:wex_horizontal_menu_print-proxies
pendingPrintersTab = [id]:wex_horizontal_menu_pendingPrinters
printersGroupTab = [id]:wex_horizontal_menu_Printer
printersPolicyTab = [id]:wex_horizontal_menu_Printer
printerAssignments = [id]:wex_horizontal_menu_Assignments
addPrinters = [xpath]://button[@data-testid='table-add-device-add-button']
exportPrintersButton = [id]:export-btn
printersTableGrid = [xpath]://div[@data-testid='devices-table-wex-section']
printerRows = [xpath]://table[@data-testid='devices-table-wex']/tbody/tr
addProxiesButton = [xpath]://button[@data-testid='add-proxy-button']
printerStatusOverview = [xpath]://div[@data-testid='printer-status-overview-title']
printersGroupAddButton = [xpath]://button[@data-testid='group-table-header']
importPolicyButton = [id]:importPolicy
addAssignmentPolicyButton = [id]:addPolicy-btn
fleetManagementTab = [id]:custom-dashboard-fleet-management
printerInventoryWidget = [xpath]://div[contains(@class,'widget-printer-inventory')]
fleetSecurityWidget = [xpath]://div[contains(@class,'widget-printer-fleet-security')]
fleetComplianceWidget = [xpath]://div[contains(@class,'widget-printer-fleet-compliance')]
printersTable = [xpath]://table[@data-testid='devices-table-wex']
