expandBtn= [css]:#wex_sm_expand_btn
alertsMenu = [xpath]: //*[@id="menu_alerts"]/a
alertManagement = [css]:#menu_alerts_alertsManagement
alertManagementPage = [xpath]: //*[@id="alerts-management"]
alertOption = [xpath]: //li[@data-testid='menu_alerts']
activeAlert = [css]: #menu_alerts_alertsListView_link
sideMenuToggleButton = [id]:wex_sm_expand_btn
manageAlertNotification = [xpath]://div[@id='alert-management-notification-heading']
manageAlertNotificationtext = [xpath]://div[@id='alert-management-notification-subHeading']
clearDropdown = [xpath]://button[@aria-label="Clear"]
inProductNotificationLabel = [css]: #in-product-notification-label
inProductNotificationDropdown = [xpath]://*[@id="in-product-notification"]
inProductNotificationDropdownList = [xpath]://*[@id="in-product-notification-listbox"]
partnerAlertManagement : [css]:#menu_alerts

itAdminSelect = [xpath]://*[@id="in-product-notification-option-0"]
reportAdminSelect = [xpath]: //*[@id="in-product-notification-option-1"]
emailNotificationaLabel =[xpath] : //*[@id="email-notification-label"]
emailNotificationDropdown = [xpath]: //*[@id="email-notification"]
emailNotificationDropdownList= [xpath]://*[@id="email-notification-listbox"]
itAdminEmailSelect = [xpath]: //*[@id="email-notification-option-0"]
reportAdminEmailSelect = [xpath] : //*[@id="email-notification-option-1"]
alertManagementTitle = [xpath] ://*[contains(@class,'alert-management-title')]
alertManagementSubtitle = [xpath] : //*[contains(@class,'alert-management-subtitle')]
alertManagementColumnHeader = [xpath]://*[contains(@class,'alert-table')]//table/thead/tr//button
titleColumn = [xpath]: //*[@id="title"]
statusColumn = [xpath]: //*[@id="status"]
severityColumn =[xpath]://*[@id="severity"]
lastEditedColumn = [xpath]://*[@id="lastEdited"]
lastTriggeredColumn = [xpath]://*[@id="lastTriggered"]
columnSettingIcon = [css]: button[aria-label="Column Options"]
currentPageNumber = [css]: button[aria-label="Page 1"]
previousButton = [xpath]: (//nav[@aria-label="Pagination"] //li)[1]
nextButton = [xpath]: (//nav[@aria-label="Pagination"] //li)[3]
resetToDefaultButton = [xpath]: //button[contains(@class, "default-button")]
saveButton = [xpath]: ((//div[@aria-describedby="column-options-desc"]/div)[3] //button)[1]
cancelButton = [xpath]: ((//div[@aria-describedby="column-options-desc"]/div)[3] //button)[2]
clearfilter = [xpath]: //button[@aria-label='Clear Filters']
emailNotificationClearDropdown= [xpath]:(//button[@aria-label="Clear"])[2] 

#Enable Alerts

emptyAlertList = [xpath]: //*[contains(@class,'wex-empty-state-widget-text')]
predefinedSelectAlertCheckbox =[xpath]: //table/tbody/tr/td[1]/span/label/span
alertStatus= [xpath]: //*[@id="alert-management-table"]/tbody/tr[1]/td[3]//div[2]
enableAlert = [css]: #alert-enable
disableAlert = [css]: #alert-disable
deleteAlert = [css]: #alert-delete span
titleSorting = [css]: #title button svg
statusSorting =[css]: #status div button
severitySorting = [css]: #severity div button
lastEditedSorting = [css]:#lastEdited div button
lastTriggeredSorting = [css]: #lastTriggered div button
statusSearch = [xpath]: (//*[contains(@class,'open-button')])[3]
severitySearch =[xpath]:(//*[contains(@class,'open-button')])[4]
enabledStatus = [css]: #status-search-option-0
disabledStatus= [css]: #status-search-option-1
criticalSeverity = [css]: #severity-search-option-0
highSeverity = [css]: #severity-search-option-1
mediumSeverity = [css]: #severity-search-option-2
lowSeverity = [css]: #severity-search-option-3
deleteConfirmation =[css]:#modal-delete-label
deleteText= [css]: #modal-delete
deleteButton =[css]:#modal-delete-button
cancelButton = [css]: #modal-cancel-button
deleteAlertToastMessageText = [xpath]:(//div[@role="alert"]//div)[2]
enableAlertToastMessageText = [xpath]: (//div[@role="alert"]//div)[2]
disableAlertToastMessageText = [xpath]:(//div[@role="alert"]//div)[2]
alertListcheckbox =[css]: //*[@id="alert-management-table"]/tbody/tr/td/span/label/input
toastMessage= [xpath]: //*[@id="dui-app-scroll"]/div[3]
alertSidePanel= [xpath]: (//li[contains(@id,'menu_alerts')]//div)[1]

#Edit Alert

alertClick = [xpath]:(//*[@id="alert-management-table"]/tbody/tr[1]//td[2])
editAlert = [css]:#modal-edit-alert-title
editAlertSubtitle =[xpath]: (//*[@id="modal-edit-alert-title"])[2]
editAlertSeverity = [xpath]: //*[@id="edit-alert-severity-label"]
currentSeverity = [xpath]: //*[@id="edit-alert-severity"]/span
editAlertTitle = [xpath]://*[@id="edit-alert-title-input-label"]
editAlertTitleInput = [xpath]: //*[@id="edit-alert-title-input"]
editAlertDescription =[xpath]: //*[@id="edit-alert-description-input-label"]
editAlertDescriptionInput =[xpath]: //*[@id="edit-alert-description-input"]
alertWhenText= [xpath]: //*[@id="when-text"]
alertWhenText2=[xpath]://div[text()='% of devices.']
editAlertThreshold=[xpath]: //*[@id="edit-alert-threshold"]
editAlertCard= [xpath]://*[@id="alert-edit-card"]
severityTag =[xpath]: //*[@id="severity-tag"]
alertCardTitle =[xpath]: //*[@id="alert-card-title"]
alertCardDescription= [xpath]: //*[@id="alert-card-description"]
percentageTag = [xpath]: //*[@id="fleet-percentage-tag"]
saveEditAlert = [xpath]://*[@id="edit-save"]
editAlertToastMessageText = [xpath]: (//*[@id="dui-app-scroll"]/div[3]//div)[3]

#Bulk action
selectAllCheckbox = [xpath]://*[@id="alert-management-table"]/thead/tr[1]/th[1]/span/label/input
mousehoverDisable = [xpath]: //*[@id="wex_menu_item_Disable"]/li
mousehoverEdit = [xpath]: //*[@id="wex_menu_item_Edit"]/li
mousehoverDelete = [xpath]://*[@id="wex_menu_item_Delete"]/li
mouseHoverAlertOption = [xpath]: //*[@id="alert-management-table"]/tbody/tr[1]/td[8]/button
mousehoverEnable = [xpath]: //*[@id="wex_menu_item_Enable"]

#table columns
typeSearch = [xpath]://*[@id='edit-alert-title-input']
searchButton = [xpath]://input[@id="title-search"]/following-sibling::div/button
noRecordText = [css]: .wex-empty-state-widget .state-title
statusDropdown = [css]:#status-search
severitydropdown = [css]:#severity-search
severityCriticalOption = [css]:#severity-search-option-0
severityHighOption = [css]:#severity-search-option-1
severityMediumOption = [css]:#severity-search-option-2
severityLowOption = [css]:#severity-search-option-3
lasEdit = [css]:#lastEdited-date
lastTriggered = [css]:#lastTriggered-date
enableOption = [css]:#status-search-option-0
disableOption = [css]:#status-search-option-1
statuscolumndropdown = [xpath]://div[contains(@class, "alert-status")]/div[2]
statusheader = [css]:#status
clearFilter = [xpath]://button[@aria-label="Clear Filters"]
severitycoulmndropdown = [xpath]://div[@class="alert-severity"]
severityheader = [css]:#severity

#Enable and Disable status
allAlertStatus = [css]:div.alert-status
selectAllCheckbox = [xpath]://*[@id="alert-management-table"]//thead//input[@type='checkbox']
closeButton = [xpath]://button[@aria-label="CLOSE"]
popupCloseBtn = [xpath]:(//button[contains(@class,'sign-in-btn')])[3]

#Partner Alerts

partnerAdminSelect = [xpath]://*[@id="in-product-notification-option-0"]
partnerServiceSpecialistSelect = [xpath]: //*[@id="in-product-notification-option-1"]
partnerSalesSpecialistSelect = [xpath]: //*[@id="in-product-notification-option-2"]
emailNotificationaLabel =[xpath] : //*[@id="email-notification-label"]
emailNotificationDropdown = [xpath]: //*[@id="email-notification"]//span
emailNotificationDropdownList= [xpath]://*[@id="email-notification-listbox"]
partnerAdminEmailSelect = [xpath]: //*[@id="email-notification-option-0"]
partnerServiceSpecialistEmailSelect = [xpath] : //*[@id="email-notification-option-1"]
partnerSalesSpecialistEmailSelect = [xpath] : //*[@id="email-notification-option-2"]
lastModified = [xpath]: //*[contains(@class,'edit-alert-last-modify-label')]
lastModifiedPartnerName= [xpath]: //*[contains(@class,'modified-by-text')]
customerWarningMessage = [xpath]: //*[contains(@class,'customer-warning-content')]
selectCustomerEditAlert= [xpath]: //*[@id="edit-alert-customer-label"]
customerSelected= [xpath]: //*[@id="edit-alert-customer"]
teamNotificationLabel= [xpath] : //*[@id="teams-notification-label"]
teamNotificationDropdown = [xpath]: //*[@id="teams-notification"]

#Duplicate Alerts
mouseHoverDuplicate= [xpath]: //*[@id="wex_menu_item_Duplicate"]
duplicateAlert = [xpath]: (//*[@id="modal-edit-alert-title"])[1]
duplicateAlertSubtitle =[xpath]: (//*[@id="modal-edit-alert-title"])[2]
duplicateAlertSeverity = [xpath]: //*[@id="edit-alert-severity-label"]
currentSeverity = [xpath]: //*[@id="edit-alert-severity"]/span
duplicateAlertTitle = [xpath]://*[@id="edit-alert-title-input-label"]
duplicateAlertTitleInput = [xpath]: //*[@id="edit-alert-title-input"]
duplicateAlertDescription =[xpath]: //*[@id="edit-alert-description-input-label"]
duplicateAlertDescriptionInput =[xpath]: //*[@id="edit-alert-description-input"]
alertWhenText= [xpath]: //*[@id="when-text"]
alertWhenText2=[xpath]://div[text()='% of devices.']
duplicateAlertThreshold=[xpath]: //*[@id="edit-alert-threshold"]
duplicateAlertCard= [xpath]://*[@id="alert-edit-card"]
severityTag =[xpath]: //*[@id="severity-tag"]
alertCardTitle =[xpath]: //*[@id="alert-card-title"]
alertCardDescription= [xpath]: //*[@id="alert-card-description"]
percentageTag = [xpath]: //*[@id="fleet-percentage-tag"]
saveDuplicateAlert = [xpath]://*[@id="edit-save"]
duplicateAlertToastMessageText = [xpath]:(//*[@role="alert"]//div)[2]
editThresholdValue = [css]: #edit-alert-threshold
searchAlertMgmt = [xpath]: //*[@id="title-search"]
searchButton= [xpath]: //button[@aria-label="Search"]
allCustomerDropdown =[xpath]://*[@id="edit-alert-customer"]//span
closeScreen- [xpath]:(//*[@aria-label='Close modal'])

ColumnData = [xpath]: //*[contains(@id,"alertdetails_")]
noAlertMessage = [xpath]://*[contains(@class,'wex-empty-state-widget-text')]/h3
noAlertSubText = [xpath]://div[@class='state-subtitle']
homeNoAlertMessage = [css]: div.home-no-alerts-container .state-title
homeNoAlertSubText = [css]: div.home-no-alerts-container .state-subtitle
breadcrumbsAlertHeader = [xpath]: (//nav[@aria-label="breadcrumbs"] //li)[1]
breadcrumbsActiveAlertHeader = [xpath]: (//nav[@aria-label="breadcrumbs"] //li)[2]
breadcrumbsAlertTitle = [xpath]://nav[@aria-label="breadcrumbs"] //span[@aria-current="page"]
onboardingButton = [css]: div.wex-onboarding-checklist
helpButton = [css]: #help-support-button
notificationButton = [css]: #notification-center-button
profileButton = [xpath]: //*[contains(@class,"wex-avatar wex-profile-avatar")]
searchInput = [css]: input#search
searchButton = [xpath]://input[@id="search"]/following-sibling::div/button
alertColumn = [css]: th#title
createdColumn = [css]: th#created
updatedColumn = [css]: th#updated
lastTriggeredColumn = [css]: th#lastTriggered button
deviceImpactedColumn = [css]: th#devicesImpacted button
fleetColumn = [css]: th#fleetPercentage button
alertImpactedDevices = [xpath]:(//div[@id='wex-main-container-id']//h6)[2]
alertImpactedDevicesText = [xpath]:(//div[@id='wex-main-container-id']//small)[2]
alertFleet = [xpath]:(//div[@id='wex-main-container-id']//h6)[3]
alertFleetText = [xpath]:(//div[@id='wex-main-container-id']//small)[3]
remediationGuide = [xpath]:(//div[@id="remediation-guide"]//p)[1]
remediationGuideDownPara = [xpath]:(//div[@id="remediation-guide"]//p)[2]
viewMoreButton = [xpath]://button[@id="remediation-guide-view-more-btn"]
exportButton = [xpath]:(//button[@id="export-btn"] | //button[@id="generate-xls"])[2]
toastNotificationExport = [xpath]:(//div[@role='alert']//div[1])[1]
closeScreen= [xpath]:(//*[@aria-label='Close modal'])
customerList  = [xpath]: //*[@id="edit-alert-customer-listbox"]/li
selectCustomerDuplicate = [xpath]: //*[@id="edit-alert-customer-option-0"]
duplicateAlertName= [xpath]: //*[@id="alert-management-table"]//tbody//tr/td[2]
selectAllCheckbox= [xpath]: //table/thead/tr[1]/td/span/label









