sideRootMenuCollapseState = [xpath]://button[@name="Collapse Side Menu"]
sideRootMenuExpandButton = [css]:#wex_sm_expand_btn
Administartive =[xpath]://a[@id='menu_administrator']
Administrative =[xpath]://a[@id='menu_administrator']
Users = [xpath]://a[@id="menu_administrator_rootUsers"]
Orders =[xpath]://a[@id="menu_administrator_cams-orders"]
MspMenu = [xpath]://a[@id='menu_msp']
Msps = [xpath]://a[@id='menu_msp_msp']
PartnerMenu = [xpath]://a[@id='menu_partners']
Partners = [xpath]:///a[@id="menu_partners_partners"]
Customers = [xpath]://a[@id='menu_customers']
Companies = [xpath]://*[@id="menu_customers_partnerCompanies"]//span
UserHeading = [xpath]:(//*[@id="rootUsers"]//span)[1]
InviteButton = [xpath]://button[@id="btn_company_add"]
firstNamelabel = [id]:user-first-name-label
lastNamelabel = [id]:user-last-name-label
emailAddresslabel = [id]:user-email-address-label
firstName = [xpath]://input[@id="user-first-name"]
lastName = [xpath]://input[@id="user-last-name"]
emailAddress = [xpath]://input[@name="email-address"]
IdpTypedrop = [xpath]://input[@id="idp-dropdown"]
IDPlist = [xpath]://li[@data-value='HPID']
InvUserBtn = [id]:btn_add
cancelBtn = [id]:btn_cancel
addNxtBtn = [id]:btn_next
addPrevBtn = [id]:btn_prev
clearFilter = [xpath]://*[@id="dui-container" ]//div/button[@aria-label="Clear Filters"]
toastMessage = [xpath]://div[@role="status"]
toastmessageuser = [xpath]:(//div[@role="status"])[2]
emailInput = [xpath]://input[@aria-label="Email search"]
userNameValue = [xpath]:(//*[contains(@class,'wex-value-field')]//a)[1]
noResults = [xpath]://*[@class="state-title"]
predefinedSelectAlertCheckbox =[xpath]:(//table/tbody/tr/td[1]/span/label)[1]
checkBoxSecond = [xpath]:(//table/tbody/tr/td[1]/span/label/span)[2]
delete = [xpath]://button[@id='btn_company_remove']
deleteBelowText = [xpath]://div[@class='content']/p
deleteButton = [xpath]://button[@id='btn_remove']
cancelButton = [xpath]://button[@id='btn_cancel']
## Impersonate User
companyNameInput = [xpath]://input[@id="name"]
companyName= [xpath]:(//*[@id="companies"]//td//div)[1]
companyDetails = [xpath]://*[@id="dui-dsummary-card-header"]
deleteCompBtn = [xpath]://*[@id="delete-company-btn"]
compSummaryDesc = [xpath]:(//*[@class="dui-dsummary-card-desc-content-value"])[4]/span
compSummaryCard = [xpath]://*[@class="wex-dsummary-card"]
impersonateBtn= [xpath]://*[@class="wex-dsummary-card"]//button
confirmText = [xpath]://*[@id="impersonate-user-confirmation"]
impersonateSubBtn = [id]:impersonate-modal-submit
impersonateCancBtn = [id]:impersonate-modal-cancel
goBackLink= [xpath]://a[@class="dui-hyperlink dui-pointer"]
partnerName= [xpath]:(//*[@class="dui-partners"]//td[2]//a)[1]
mspName= [xpath]:(//*[@class="dui-msps"]//td[2]//a)[1]
companySummaryDesc = [xpath]:(//*[@class="dui-dsummary-card-desc-content-value"]//div/a)[1]

## Add MSP User
inviteUser = [id]:btn_user_add
chooseMsp = [xpath]://div[@id='add_breadcrumbs.msp.users']/h6
mspBelowText = [xpath]://div[@id='add_breadcrumbs.msp.users']//p
mspDropdwn = [id]:assignment-msp
search = [xpath]:(//input[@placeholder='Search'])[3]
selectMsp = [xpath]://ul[@role='listbox']
cancelMsp = [id]:root-createMSP-mspSelect-cancel
nextMsp = [id]:root-createMSP-mspSelect-next
role = [id]:MSP-User-Infor
mspRoles = [xpath]://li[@data-value='support_admin']
header = [xpath]:(//div[@class="dui-sub-title-container"])[1]
fnMsp = [xpath]://*[@name="firstName"]
lnMsp = [xpath]://*[@name="lastName"]
email = [xpath]:(//input[@name="email"])[2]
phone = [xpath]://*[@name="phone"]
prevMsp = [id]:root-createMSP-userDetails-previous
addMsp = [id]:root-createMSP-userDetails-add
toastMsp = [xpath]://div[@role="alert"]//div/span

## Add MSP Page
mspDropDown = [xpath]:(//li[@role='MSPs']//button)[2]
MspUsers = [xpath]://*[@id="menu_msp_mspUsers"]
MSPBreacrumpsClick = [xpath]://nav[@aria-label='breadcrumbs']//a
mspUserHeading = [xpath]://*[@id="mspUsers"]//div/span
mspheading = [xpath]://*[@id="mspList"]//li/span
addMspBtn = [xpath]:(//*[@id="add-msp-btn"]/span)[2]
mspId = [xpath]://input[@name="partner_id"]
compName = [xpath]://input[@name="partner_name"]
mspfirstName = [xpath]://input[@name="primary_admin_fname"]
msplastName = [xpath]://input[@name="primary_admin_lname"]
mspemailAddress = [xpath]://input[@name="primary_admin_email"]
mspIdpTypedrop = [xpath]:(//div[@role="combobox"])[4]
mspIDPlist = [xpath]://ul[@role="listbox"]/li
countryMsp = [xpath]://div[@id="select-country"]
countryList = [xpath]://ul[@id="select-country-listbox"]/li
saveBtn = [id]:save-btn
editMsp = [id]:icon-edit-name
editname = [xpath]://*[@name="edit_modal_name"]
editSaveBtn = [id]:editSaveBtn
toastMspSave = [xpath]://div[@role='alert']//div/div
updatedName = [xpath]:(//div[@class='dui-panel-container']/span//div)[5]
mspDetails = [xpath]://*[@id = "dui-dsummary-card-header"]
delMsp = [id]:removePartner
mspSubmenu = [id]:menu_msp_msp_link
mspDeleteButton = [xpath]://button[@id='btn_user_remove']
mspDeleteBelowText = [xpath]://div[@class='dui-modal-content']//p
mspdelete = [xpath]:(//button[@id='modal-submit'])
mspCancel = [xpath]://button[@id='modal-cancel']

#Resend Invite
inviteStatus = [xpath]://*[@id="inviteStatus"]
inviteStatusdropdown = [xpath]:(//*[@id="inviteStatus"])[2]
selectInv = [xpath]://li[contains(@id,"option-1")]
partnerUsers = [xpath]://a[@id="menu_partners_partnerUsers"]
partnerUserHeading = [xpath]://*[@id="partnerUsers"]//li/span
customerUsers = [xpath]://a[@id="menu_customers_customerUsers"]
customerUserHeading = [xpath]://*[@id="customerUsers"]//li/span

userMgmt = [id]:user-management-header
idpInfo = [id]:hpid
editRole = [id]:edit-role
assignRole = [xpath]:(//*[@id="rolesModal-label"])[2]
rolesSave = [xpath]: (//button[@id="rolesSaveBtn"]/span)[2]
rolesCancel = [xpath]:(//button[@id="rolesCancelBtn"]/span)[2]

Administrativenameedit = [xpath]:(//*[@id='namePanel']//div)[6]