#WEXSustainabilityPage
logoutButton = [xpath]://*[contains(@class,'wex-profile-avatar ')]/div
signoutButton = [xpath]://div[@class='wex-profile-data']/button/span[contains(text(),'Sign Out')]
toggleButtonOpen = [xpath]://div[contains(@class,'wex-sidemenu-expand-btn-open')]
toggleButtonClose = [xpath]://div[contains(@class,'btn-expanded-lbl wex-txt-truncate')] 
homeButton = [xpath]://a[@id='menu_home_link']
partnersandcompany =[xpath]://*[@class='wex-txt-truncate']
titleOpen = [xpath]://*[@class='btn-expanded-lbl wex-txt-truncate']
remediationsLink = [xpath]://li[@id='menu_remediations']/a
loaderIcon =[xpath]://div[@class='dui-page-spinner']


bitLocketActiveAlert = [xpath]:(//div[@class='aa-alert-title'])[1]//div
#bitLocketActiveAlert = [xpath]://*[contains(@id,"active_alert_fleet_BITLOCKER_ENCRYPTION_NOT_ENABLED")]
#//div[@id='enable-bit-locker-encryption']
firstDeviceInAlertDetails = [xpath]://*[@id="dui-container"]//tr[2]/td[1]/span/label
RemediateBtnInAlertDetails = [xpath]://button[@id='btn-remediation']
breadcrumbsAlertHeader = [xpath]: //nav[@aria-label="breadcrumbs"] //div[1]//a
breadcrumbsActiveAlertHeader = [xpath]://nav[@aria-label="breadcrumbs"] //div[2]//span
breadcrumbsAlertTitle = [xpath]://nav[@aria-label="breadcrumbs"] //span[@aria-current="page"]
remediateHeader = [xpath]://div[@class='wx-font-title-small']
hpGalleryHeader = [xpath]:(//div[@data-testid='functional-area'])[1]/preceding-sibling::div//div[2]//h3
myLibraryHeader = [xpath]:(//div[@data-testid='functional-area'])[2]/preceding-sibling::div//div[2]//h3
selectScriptInRemediateWizard = [xpath]:(//*[@id="modal-id"])//tr[2]/td[1]/label[1]/span
scriptNameInRemediateWizard = [xpath]:(//*[@id="modal-id"]//tbody/tr[2])/td[2]/div/b
synopsisNameInRemediateWizard = [xpath]:(//*[@id="modal-id"]//tbody/tr[2])/td[2]/div/p
helpLinkOnRemediateWizard = [xpath]:(//span[normalize-space()='Help'])[1]
toastNotificationExport = [xpath]: //div[@role='status']//div[contains(@id,'toast-title')]

remediateHeaderOnHelp=[xpath]://div[@class="wex-lib-sidebar-title"]
helpTextOnremediateHelpWindow=[xpath]:(//div[contains(@class,'wex-lib-sidebar-content-container')])//div
closeBtnOnremediateHelpWindow=[xpath]:(//button[@id='sideBar_done'])//span
cancelBtnOnRemediateWindow=[xpath]:(//span[contains(text(),'Cancel')])[1]
nextButtonRemediateWizard=[xpath]:(//span[contains(text(),'Next')])[1]


reviewHeaderOnRemediateWizard = [xpath]://div[@class="wx-font-subtitle-regular"]
synopsisName=[xpath]://div[@class="wx-font-body section-val"]
scriptName=[xpath]://*[@id="script-name"]/div[2]/div[1]/div[1]
selectedDevicesCount=[xpath]://*[@id="selected-devices"]/div[2]/div[1]/div[1]
remediateButton=[xpath]:(//span[contains(text(),'Remediate')])[1]


activityTabInScriptDetailPage = [xpath]://div[@id='tab-script-details-activity']
noDataInActivityTabInAssignmentDetailsPage = [xpath]://h3[@class="state-title"]
scriptsActivitieSInScriptDetailPage = [xpath]://table[@id='scriptsActivities']/tbody/tr[1]
activityMenuOnScriptActivityPage = [xpath]:(//button[@aria-haspopup="menu"])[1]
detailsActivityMenuOnScriptActivityPage = [xpath]:(//button[@id='wex-menu-list-item'])[1]


scriptNameOnHPGallery = [id]:scriptName
scriptAuthorName = [id]:scriptAuthorName
scriptVersion = [id]:scriptVersion
sourceType = [id]:source
subType = [id]:subType
subTypeOnMyLibraryPage = [id]:scriptUsage


hpGalleryTypeListbox = [xpath]:(//input[contains(@class,"ComboboxTrigger")])[1]
hpGalleryTypeListboxOption1 =[xpath]://li[@data-value='Script']

hpGallerySubtypeListbox = [xpath]:(//input[contains(@class,"ComboboxTrigger")])[2]
hpGallerySubtypeListboxOption1 =[xpath]://li[@data-value='Action']
hpGallerySubtypeListboxOption2 =[xpath]://li[@data-value='Evaluation']

missingBiosUpdateActiveAlert = [xpath]://div[contains(@id,'active_alert_fleet_MISSING_CRITICAL_BIOS_UPDATES')]
selectAllCheckbox = [xpath]://input[contains(@aria-label, 'Select all')]
getFirstDeviceSerialNo = [xpath]://*[@id="active-alert-details-table"]/tbody/tr/td[5]//a
applyPolicyBtn = [xpath]://button[@id='btn-apply-policy']
applyPolicyHeaderOnPopUp = [xpath]://div[contains(@class, 'wex-modal')]//h4
selectBiosPolicyHeaderOnPopUp = [xpath]://div[@class="apply-policy-modal"]//p
keepBiosUptoDateOption = [xpath]:(//div[@class="apply-policy-modal"])//div//label[1]//span[2]
updateCriticalBiosUptoDateOption = [xpath]:(//div[@class="apply-policy-modal"])//div//label[2]//span[2]
saveBtnOnApplyPolicyPopup = [xpath]:(//button[@id='apply-policy-btn'])[1]
cancelBtnOnApplyPolicyPopup = [xpath]:(//button[@id='apply-policy-cancel-btn'])[1]
deviceSearchOnMembershipTab = [xpath]://input[@id='search-serialNumber']
deviceSNOnMembershipTab = [xpath]:(//a[contains(@class,"device-serial-number")])[1]
clearFiltersOnMembershipTab = [xpath]://button[@aria-label="Clear Filters"]

tabAISuggestion = [id]:tab-ai-suggestion
tabScripts = [id]:tab-scripts
tabPolicies = [id]:tab-policies
tabWorkflow = [id]:tab-workflow
tabGuide = [id]:tab-guide

remediationScriptHPGallerySegment = [id]:remediation-script-hp-gallery-segment
remediationScriptMyLibrarySegment = [id]:remediation-script-my-library-segment
remediationScriptSearchBox = [id]:remediation-script-search-box

alertOrRATitleNameOnHeader = [xpath]://div[@class="wex-lib-sidebar-title"]//h2

remediationAIGuideTabContent = [xpath]://*[@id="unified-remediation-tab-guide"]/div/div/div/div[1]
remediationSidebarDone = [id]:remediation_sidebar_done
remediationAIGuideTabHeader = [xpath]://*[@id="unified-remediation-tab-guide"]//h5
noDataMsg = [xpath]://h3[normalize-space()='No data to display']  

scriptsHeaderOnScriptsTab = [xpath]://*[@id="unified-remediation-tab-scripts"]//ul/li
selectFirstScriptsOnHPGalleryScriptsTab = [xpath]://*[@id="remediation-list-select-0"]
firstScriptTitleOnHPGalleryScriptsTab = [xpath]:(//div[contains(@class,'wex-list-title')])[1]
firstScriptCaptionOnHPGalleryScriptsTab = [xpath]:(//div[@class='wx-font-caption'])[1]


scriptsHeaderOnAISuggestionTab = [xpath]://*[@id="unified-remediation-tab-ai-suggestion"]/div/div/div/div/ul/div[1]
policiesHeaderOnAISuggestionTab = [xpath]://*[@id="unified-remediation-tab-ai-suggestion"]/div/div/div/div/ul/div[2]
scriptsAndPoliciesOnAISuggestionTab = [xpath]://*[@id="unified-remediation-tab-ai-suggestion"]/div/div/div/div/ul/li[*]
firstScriptsOnAISuggestionTab = [xpath]://*[@id="remediation-list-select-0"]
firstScriptTitleOnAISuggestionTab = [xpath]:(//div[contains(@class,'wex-list-title')])[1]
firstScriptCaptionOnAISuggestionTab = [xpath]:(//div[@class='wx-font-caption'])[1]
firstScriptRecommendationReasonOnAISuggestionTab = [xpath]:((//div[@class='list-recommendationReason-section'])//div[2])[1]
scriptTitleOnSelectgroupPageAISuggestionTab = [xpath]://div[@class='wx-font-subtitle-regular']
scriptCaptionOnSelectgroupPageAISuggestionTab = [xpath]://div[@class='wx-font-caption']
scriptAppliedConfirmationPageAISuggestionTab = [xpath]://div[contains(@class,'common-info-title')]
scriptexecutionOnSelectedGroupRadioBtn = [xpath]://input[@id="on-group-id"]/following-sibling::span [1]
scriptexecutionOnSelectedDevicedRadioBtn = [xpath]://input[@id="on-device-id"]/following-sibling::span [1]
selectFilterGroupsCheckbox = [xpath]://input[@aria-label="select all items in the current page"]/following-sibling::span
schdeuleFrequencyRemediationListBox = [xpath]://input[@aria-label="schdeule-frequency"]
schdeuleFrequencyOption = [xpath]://li[@data-value="ONCE"]
remediationSidebarNextBtn = [id]:remediation-sidebar-next
runNowId = [id]:run-now-id
runScheduledId = [xpath]://input[@id="run-scheduled-id"]/following-sibling::span [1]
remediationSidebarReviewBtn = [id]:remediation-sidebar-review
remediationSidebarBackBtn = [id]:remediation-sidebar-back
remediationSidebarRunBtn = [id]:remediation-sidebar-run
remediationSidebarCancelBtn = [id]:remediation-sidebar-cancel
remediationListLikeBtn = [id]:remediation-list-like-button
remediationListDislikeBtn = [id]:remediation-list-dislike-button
remediationActivityRedirectLink = [id]:remediation-activity-redirect-link
tableFilterName = [id]:table-filter-Name


firstPolicyOnAISuggestionTab = [xpath]:(//div[text()='Policies'])[2]/following::label/span
firstPolicyTitleOnAISuggestionTab = [xpath]:(//div[text()='Policies'])[2]/following::div[contains(@class,'wex-list-title')]
firstPolicyCaptionOnAISuggestionTab = [xpath]:(//div[text()='Policies'])[2]/following::div[@class='wx-font-caption']


labsMenu= [id]:menu_labs
labsRemediationwithAICard = [xpath]://*[@id="labs-remediation-with-ai-card"]
labsRemediationwithAICardTitle = [xpath]://*[@id="labs-remediation-with-ai-card"]/div/div/h2
labsRemediationwithAICardDesc = [xpath]://*[@id="labs-remediation-with-ai-card"]/div/div[2]/p
RemediationwithAIButton = [xpath]://button[@id="remediation-with-ai-learn-more-button"]
labDetailsRemediationwithAICardTitle = [xpath]: //*[@data-testid="wex-summary-card"]//h3
labDetailsRemediationwithAICardDesc = [xpath]: //*[@data-testid="wex-summary-card"]//p
remediationAIEnableDisableBtn = [xpath]://*[@id="remediation-ai-enable-disable-btn"]
remediationAIEnableDisableStatusBtn = [xpath]://*[@class="remediation-ai-status-container"]//div//div[2]