#WEXSustainabilityPage
logoutButton = [xpath]://*[contains(@class,'wex-profile-avatar ')]/div
signoutButton = [xpath]://div[@class='wex-profile-data']/button/span[contains(text(),'Sign Out')]
toggleButtonOpen = [xpath]://div[contains(@class,'wex-sidemenu-expand-btn-open')]
toggleButtonClose = [xpath]://div[contains(@class,'btn-expanded-lbl wex-txt-truncate')] 
homeButton = [xpath]://span[contains(text(),'Home')]
partnersandcompany =[xpath]://*[@class='wex-txt-truncate']
titleOpen = [xpath]://*[@class='btn-expanded-lbl wex-txt-truncate']
fleetDashboard = [xpath]:(//span[contains(text(),'Dashboard')])[1]
fleetManagement = [xpath]:(//*[contains(@id,'menu_fleetManagement')]//span[contains(@class,'side-menu__item-col-label')])[1]
fleetManagementWidget = [xpath]://*[@id="custom-dashboard-fleet-management"]/div[2]/p
fleetManagementSiteHeader = [xpath]://span[contains(text(),'Fleet Management')]
fleetAnalytics = [xpath]://span[contains(text(),'Analytics')]
sustainabilityLink = [xpath]:(//a[contains(text(),'Sustainability')])[1]
sustainabilityHeader = [xpath]:(//span[contains(text(),'Sustainability')])[1]
loaderIcon =[xpath]://div[@class='dui-page-spinner']


powerConsumptionWidgetTitle = [xpath]:(//div[contains(text(),'Power Consumption Over Time')])[1]
powerConsumptionWidgetTitleOnFM = [xpath]:(//div[contains(text(),'Power Consumption over Time')])[1]
powerConsumptionWidgeViewdetailsLink = [xpath]://button[@id='view_details_sustain']
powerConsumptionWidgeViewReportLink = [xpath]: //div[contains(@class,'widget-power-consumption-over-time')]//button[@title='View Report']
powerConsumptionValueTitleOnGraph = [xpath]:(//div[contains(text(),'Power Consumption')])[3]

powerConsumptionByModelTitle = [xpath]:(//div[contains(text(),'Power Consumption by Model')])[1]

powerConsumptionByLocationTitle = [xpath]:(//div[contains(text(),'Power Consumption by Location')])[1]

exportButton = [xpath]:(//span[contains(text(),'Export')])
exportXLSXFileLink = xpath]:(//span[contains(text(),'XLSX')])
toastNotificationExport = [xpath]: //div[@role='status']//div[contains(@id,'toast-title')]

deviceGrid = [xpath]: //div[contains(@class,'wex-card-content')]//a
deviceSNO = [xpath]:( //div[contains(@class,'wex-card-content')]//a)[1]
sustainabilityTab = [xpath]:(//div[contains(text(),'Sustainability')])
sustainabilityGraph = [xpath]: (//*[@class='sc-cHqXqK fEqnYj'])

helpTextLink = [xpath]:(//span[normalize-space()='Help'])[1]
sustainabilityHelperHeader = [xpath]: //p[@class='sustainability-helper-heading']
sustainabilityHelpText = [xpath]: //*[@id="dui-sustainability-sidebar"]//div[1]//div//div//p[3]
KBArticleLink = [xpath]: (//a[contains(text(),'Learn More')])[1]
LearnmoreLink = [xpath]: (//a[contains(text(),'Learn more')])[1]
sustainabilityLastUpdatedHelpText =[xpath]: (//span[@class='date-last-updated'])/following-sibling::span
sustainabilityInfoMsgHeader = [xpath]: //p[@class='dui-margin-left-5 info-message']/b
sustainabilityInfoMsgSubHeader = [xpath]: //span[@class='info-subheader wex-foreground-medium-color']
clearFilterButtonOnDeviceGrid = [xpath]://button[@aria-label="Clear Filters"]




idKey= [xpath]://tr[*]/td[3]/div/div
deviceNameSearchBox = [xpath]://input[@id='search-deviceName']
deviceNameColumn = [xpath]://*[@id="deviceName"]/div/button
modelNameSearchBox = [xpath]://input[@id='search-deviceModel']
noItemsAvailable = [xpath]://*[text()='No results']
sortingAscendingArrowKey = [xpath]://span[text()='ascending sorted']
sortingArrowKey = [xpath]://span[text()='descending sorted']
listkey= [xpath]: //div[contains(@class,'wex-card-content')]//tbody//tr[*]//td[3]
selectAllCheckBox = [xpath]:"//*[@name='SelectAllPage']";


navigationItemDiv = [xpath]://*[@aria-label="Pagination Navigation"]
navigationItemList = [xpath]://*[@aria-label="Pagination Navigation"]//li
navigationItemNext = [xpath]://*[@aria-label="Pagination Navigation"]//button[@aria-label="Next"]
navigationItemPrevious = [xpath]://*[@aria-label="Pagination Navigation"]//button[@aria-label="Previous"]
navigationItemFrist = [xpath]://*[@aria-label="Pagination Navigation"]//li[2]
navigationItemLast = [xpath]:(//*[@aria-label="Pagination Navigation"]//li)[last()-1]
navigationItemActivePage =  [xpath]://*[contains(@aria-label,'Current Page')]
roomNameSearchList=[xpath]://table[@id='roomList']//tbody//tr//td[2]


globalFilter = [xpath]:(//span[contains(text(),'Filters')])
clearAllGlobalFilter = [xpath]:(//span[contains(text(),'Clear All')])
globalFilterCancel = [xpath]://*[@id="dui-sustainability-sidebar"]/div[2]/div[2]/button/span
globalFilterSave = [xpath]:(//span[contains(text(),'Apply')])
timeFilterDropdown=[xpath]://*[@id='duration']
timeFilterDropdownValue=[xpath]://span[normalize-space()='Last 12 weeks']
deviceModelFilterDropdownCheck = [xpath]:(//input[@id='deviceModel'])[1]
deviceModelFilterDropdown = [css]:input[id='deviceModel']
deviceModelFilterDropdownValue =  [xpath]://*[contains(@id,'floating-ui-') and contains(@id,'-option-0')]
deviceModelHeader =  [xpath]:(//strong[normalize-space()='Devices'])[1]
mfgYearFilterDropdown = [css]:input[id='mfgYear']
mfgYearFilterDropdownValue = [xpath]://*[contains(@id,'floating-ui-') and contains(@id,'-option-0')]
mfgYearHeader = [xpath]:(//div[contains(text(),'Manufacture Year')])
deviceManufacturerFilterDropdown = [css]:input[id='deviceManufacturer']
deviceManufacturerFilterDropdownValue = [xpath]://li[@data-value='HP']
deviceManufacturerHeader = [xpath]:(//div[contains(text(),'Manufacturer')])[1]
memoryFilterDropdown =  [css]:input[id='memory']
memoryFilterDropdownValue = [xpath]://*[contains(@id,'floating-ui-') and contains(@id,'-option-0')] 
memoryHeader = [xpath]:(//div[contains(text(),'Memory')])
powerMeasurementFilterDropdown = [css]:input[id='powerMeasurement']
powerMeasurementHeader =  [xpath]:(//div[contains(text(),'Measurement type')])
powerMeasurementDropdownValue = [xpath]://*[contains(@id,'floating-ui-') and contains(@id,'-option-0')]
filterCount = [xpath]:(//span[contains(text(),'Filters')])//span
clearLocation1Filter = [css]:#location1 [class*=location-clear]
noDataDisplay = [xpath]:(//div[@class='state-title'][normalize-space()='No data to display'])[2]
noResultMsg = [xpath]://div[contains(text(),'No results')]

deviceListTblrow1= [xpath]://div[@class='wex-card-container table-grid-content']//tbody//tr[1]
firstDeviceModelName= [xpath]:(//div[@class='apps-with-issues-row pointer'])[1]
deviceModelGraphFilter = [xpath]: //div[contains(@class,'active-clear-icon')]
tooltipHoverDeviceByType = [xpath]:(//*[name()='path'][@class='highcharts-point'])
tooltipTextDeviceByType = [xpath]:(//span[normalize-space()='Total Devices'])[1]
tooltipHoverDevice = [xpath]://*[@id="details-list-component-power_consumption_by_model"]/div/div[2]/div/div/div/div/div[2]
helpCloseButton = [id]:sustainability-cancel-btn
powerConsumptionWidgetTitleOnFMDB = [xpath]:(//div[starts-with(@class, 'wexcard-container tile-chart-content custom-widget widget-power-consumption-over-time')])//div/h2
powerConsumptionWidgeViewReportLink1 = [xpath]:(//div[starts-with(@class, 'wexcard-container tile-chart-content custom-widget widget-power-consumption-over-time')])//*[@title="View Report"]


searchReport = [id]:search
modernReports = [id]:modern-reports