telephonesTab = [id]:wex_horizontal_menu_VideoEndpoints
devicesPageTitleFleetManagement = [link]:Fleet Management
devicesPageTitleDevices=[xpath]://li//span[@aria-current = 'page']
telephonesPageTitle = [xpath]://li//span[@aria-current = 'page']
telephonesPageList = [xpath]://table[@id='vyoptaTelephones']/tbody
telephonesPageTableRows=[xpath]://table[@id='vyoptaTelephones']/tbody//tr
telephonesPageTableCount=[xpath]://button[@aria-label='Select page size']/following-sibling::div[@role='presentation']/following-sibling::span
telephonesPageTableColumns=[xpath]://table[@id='vyoptaTelephones']//tr[1]/th[@scope='col']
telephonesTitle=[xpath]:(//div[@id = 'telephones']//following::span)[1]
nameCol = [xpath]://th[@id="endpointname"]/div/button
clearFilters = [xpath]: //button[@aria-label='Clear Filters']
leftPaneHomePageButton= [id]:menu_home_link
showingPaginationTotalCount = [xpath]://button[@aria-label="Select page size"]/following-sibling::span
firstManufacturerLegendIcon=[xpath]:(//div[@class="highcharts-legend"]//span)[2]
secondManufacturerLegendIcon=[xpath]:(//div[@class="highcharts-legend"]//span)[3]
telephonesPageFirstRowData = [xpath]://table[@id='vyoptaTelephones']/tbody/tr/td[1]

#Widget
fleetInventoryTitle = [xpath]:(//div[@id="fleet-inventory-label"]//div[contains(text(),'Fleet')])[1]
telephonePill= [id]:telephones
centerWidgetValue = [xpath]: //*[@class="highcharts-br"]/preceding-sibling::*
telephonesWidget = [xpath]:(//div[@class="highcharts-legend"]//span)
chartCircle = [xpath]: //*[@class='highcharts-point highcharts-color-0']