videoEndpointsTab = [id]:wex-menu-list-item
devicesPageTitleFleetManagement = [link]:Fleet Management
devicesPageTitleDevices=[xpath]://li//span[@aria-current = 'page']
tablelist=[xpath]://table[@id='vyoptaVideoEndpoints']
videoEndpointPageTitle = [xpath]://li//span[@aria-current = 'page']
videoEndpointPageList = [xpath]://table[@id='vyoptaVideoEndpoints']/tbody
videoEndpointPageTableRows=[xpath]://table[@id='vyoptaVideoEndpoints']/tbody//tr
videoEndpointPageTableCount=[xpath]://button[@aria-label='Select page size']/following-sibling::div[@role='presentation']/following-sibling::span
videoEndpointsTableColumns= [xpath]://table[@id='vyoptaVideoEndpoints']//tr[1]/th[@scope='col']
videoEndpointPageFirstRowData = [xpath]://table[@id='vyoptaVideoEndpoints']/tbody/tr/td[1]
endpointNameCol = [xpath]://th[@id="endpointname"]/div/button
clearFilters = [xpath]: //button[@aria-label='Clear Filters']
fleetInventoryTitle = [xpath]:(//div[@id="fleet-inventory-label"]//div[contains(text(),'Fleet')])[1]
centerWidgetValue = [xpath]: //*[@class="highcharts-br"]/preceding-sibling::*
videoEndpointsPill = [id]:videoEndpoints
videoEndpointsWidget = [xpath]:(//div[@class="highcharts-legend"]//span)
chartCircle = [xpath]: //*[@class='highcharts-point highcharts-color-0']
showingPaginationTotalCount = [xpath]://button[@aria-label="Select page size"]/following-sibling::span
leftPaneHomePageButton= [id]:menu_home_link

#Meeting Quality
meetingQualityTitle =[xpath]:(//div[@id="wex-score-label"]//div[contains(text(),'Meeting')])[1]
totalMeetingsLabel = [xpath]://div[@class="chart-Vyopta-subTitle"]//div[contains(text(),'Total')]
meetingsList = [xpath]:(//div[@class="vyopta-meetings-list"]//span)
totalMeetingsCount = [xpath]://div[@class="chart-Vyopta-subTitle"]//h5

videoVyoptaEndpointsLink=[xpath]: //table[@id='vyoptaVideoEndpoints']/tbody//tr/td
videoEndPionttitle =[xpath]://div[@id='videoEndpoints']//descendant::h1
vyoptaEmailInput=[xpath]://input[@id='email']
vyoptaEmailNextbtn=[xpath]://*[@id="page"]/login-widget//button[1]