leftSideMenuExpandBtn = [id]:wex_sm_expand_btn
leftSideMenuCollapseBtn = [id]:wex_sm_collapse_btn
WolfProtectandTraceColumnName = [xpath]://th[@id='lockAndErase']//button
WEPWptApproverCountSetting = [xpath]://*[contains(@class,'anchorMenu')]//ul/li[8]
DeviceHPWolfProtectandTracePrefSettings = [xpath]://*[contains(@containerid,'tab-preferences')]//*[8]
DeviceHPWolfProtectandTracesettings = [xpath]://*[@id="device-hp-wolf-protect-and-trace-settings"]
DeviceHPWolfProtectandTracesettingsheader = [xpath]://*[@id="device-hp-wolf-protect-and-trace-settings"]
DeviceHPWolfProtectandTracesettingsSubheader = [xpath]: //div[@id="device-lock-and-erase"]/div[@class="dui-epr-label"]
ActionexportDataButton = [xpath]://*[@id='wex_menu_item_device-export']
ActionRefreshDataButton = [xpath]://*[@id='wex_menu_item_device-refresh']
ActiondeleteDataButton = [xpath]://*[@id='wex_menu_item_device-remove']
ActionCollectnewlogsButton = [xpath]://*[@id='wex_menu_item_device-collect-new-logs']
ActionLockButton = [xpath]://*[@id='wex_menu_item_device-lock']
ActionEraseButton = [xpath]://*[@id='wex_menu_item_device-erase']
WolfProtectandTraceColumnNameonuserpage = [xpath]://th[@id='lockAndEraseApproversStatus']//button
WPTActionButton1 = [xpath]:(//div[contains(@class,"card-buttons")]/button/span)[2]
clearfilter = [xpath]: //button[@aria-label='Clear Filters']
firstSerialNumberText = [xpath]: //table[@id="devices"]/descendant::a[1]
HPWolfProtectandTraceheader = [xpath]://*[@id="hp-protect-&-trace-with-wolf-connect-header"]
HPWPTServiceActiavationStatus = [xpath]://*[@id="service-activation-status"]/div[@class="wex-editable-row-label"]
HPWPTServiceStatus = [xpath]://*[@id="service-status"]/div[@class="wex-editable-row-label"]
HPWPTModuleSupported = [xpath]://*[@id="module-supported"]/div[@class="wex-editable-row-label"]
hardwareTab = [xpath]://*[@id="hardware"]
HPWPTModuleActivationStatus = [xpath]://*[@id="module-activation-status"]/div[@class="wex-editable-row-label"]
HPWPTMModuleIMEI =  [xpath]://*[@id="module-imei"]/div[@class="wex-editable-row-label"]
HPWPTModuleFirmwareVersion =  [xpath]://*[@id="module-firmware-version"]/div[@class="wex-editable-row-label"]
HPWPTMModuleeSIMID =  [xpath]://*[@id="module-esim-id"]/div[@class="wex-editable-row-label"]
hpWPTEditToggleValue = [xpath]://input[@id="webconfig-toggle"]
hpWPTEditThesholdValue = [xpath]://*[@id='device-lock-and-erase' and @class='dui-ddetails-container']//*[@name='IconPencil']
hpWPTApproverCount = [xpath]://*[@name="approvalsRequired"]
hpWPTApproverCountSaveButton = [xpath]:(//*[@name="approvalsRequired"]/following::button[@type="button"]/span)[1]
hpWPThesholdState = [xpath]://div[@id='enabled-']
licenseTab = [xpath]://div[@id="licenses"]
wptLicense = [xpath]://div[@class='plan-list']//h2/div
wptThresholdToggle = [xpath]:(//input[@aria-label="toggle"]/following::span)[1]
wptToastNotification = [xpath]:(//*[@id="dui-app-scroll"]/div[2]/div//div)[2]
addOnTab = [xpath]://div[@id="addons"]
wepWPTaddOnlable = [xpath]://div[@id="wpt-addon"]/div//div/h3



wptAccountOverviewPage = [xpath]://div[@id="overview"]
wptCompanyProfile = [xpath]://div[@id="company-profile-header"]
wptCustomerID  = [xpath]:(//div[@id="display-id"]/div)[1]
wptCompanysize = [xpath]:(//div[@id="company-size"]/div)[1]
wptCompanyname = [xpath]:(//div[@id="company-name"]/div)[1]
wptCreatedon  = [xpath]:(//div[@id="createdOnPanel"]/div)[1]
wptPrimaryadministrator = [xpath]://div[@id="primary-administrator-header"]
wptPrimaryadministratorName = [xpath]:(//div[@id="admin-name"]/div)[1]
wptPrimaryadministratorPhone = [xpath]:(//div[@id="admin-contact-number"]/div)[1]
wptPrimaryadministratorEmail = [xpath]:(//div[@id="emailPanel"]/div)[1]
wptCompanyAddress = [xpath]://div[@id='company-address-header']
wptCompanyAddressCountry = [xpath]:(//div[@id='country']/div)[1]
usersTab = [xpath]://div[@id="users"]
wptCompanyAddressAddressLine1 = [xpath]:(//div[@id='address-line-1']/div)[1]
wptCompanyAddressAddressLine2 = [xpath]:(//div[@id='address-line-2']/div)[1]
wptCompanyAddressState = [xpath]:(//div[@id='state']/div)[1]
wptCompanyAddressCity = [xpath]:(//div[@id='namePanel']/div)[1]
wptCompanyAddressZipCode = [xpath]:(//div[@id='postalCode']/div)[1]

wptThresholdStateEnabled = [id]:enabled-
wptThresholdStateDisabled = [id]:disabled-
Preferencestab = [id]:preferences
perferencestaboldmenu = [id]:company-preferences
addonWPT = [css]: #wpt-addon


#data collection
datacollectionsection = [xpath]://*[contains(@containerid,'tab-preferences')]//*[7]
dataCollectionHeader = [xpath]://*[@id="data-collection"]
datacollectionsubheading = [id]:data-collection-subheading
antivirusFirewallLabel = [id]:antivirus-firewall-label
BlueScreenCrashDumpsrowm = [id]:crash-dumps-label
devicelogsrow = [id]:device-logs-label
companylocationrow = [id]:company-location-label
networkidentifire = [id]:network-identifiers-label
softwareinventory = [id]:software-inventory-label
userprofileinformation = [id]:user-personal-info-label
webapplicationUsage = [id]:web-application-usage-label

mySupportCase=[id]:my-support-cases

settingsMenu= [xpath]://*[@id='menu_settings']
preferencesTab = [id]:preferences
CompanyPinHeading=[id]:company-pin
CompanyPinLink= [xpath]://a//span[text()='Company PIN']
CompanyPinSubHeading=[id]:company-pin-subheading
CompanyPinHideAndShow=[id]:show-company-pin
CompanyPinShow=[id]:hide-company-pin
companyPin= [xpath]://div[@id="company-wide-pin-row"]//div[@id]
CompanyPinExpiryDate = [xpath]://div[@id="company-wide-pin-row"]//p

domainNameLink= [xpath]://a//span[text()='Domain Name']
domainNameHeading= [id]:domain-name
domainNameSubHeading= [id]:domain-name-subheading
domainName=[xpath]://*[@id='company-domains-row']//div[@id='domain-name']/following::p[1]
domainNameEdit= [xpath]://*[@id="edit_domain_name"]/parent::div
domainNameEditModal= [xpath]://div[@id='dui-text-modal']
domainNameEditModalInputText= [xpath]://input[@id='dui-text-modal-text-box']
domainNameEditModalSaveButton=[xpath]: //button[@id='dui-text-modal-submit']
domainNames=[xpath]://*[@id="company-domains-row"]/div[2]/div[1]/div/div/p



leftSideMenuCollapseBtn = [id]:wex_sm_collapse_btn
leftSideMenuExpandBtn = [id]:wex_sm_expand_btn
clearfilter = [xpath]: //button[@aria-label='Clear Filters']
firstSerialNumberText = [xpath]: //table[@id="devices"]/descendant::a[1]
searchDeviceSerialNumberTextBox=[xpath]: //*[@name='serialNumber']
deviceNameColumn=[xpath]: (//table[@id="devices"]/tbody/tr/td)[2]


dataCollectionLink= [xpath]://a//span[text()='Data Collection']
companyLableLocation = [id]:company-location-label
locationEnabled = [xpath]: //*[@id="company-location-row"]/div[2]/div[1]/div/div
locationTab= [id]:location
locationMap= [xpath]: //div[@id='google-map']
locationDetailsDiv= [xpath]: //div[contains(@class,'all location-deails')]
locationToggle=[xpath]://input[@type='checkbox' and contains(@aria-label, 'Toggle Location')]/../span
locationToggleInput=[xpath]://input[@type='checkbox' and contains(@aria-label, 'Toggle Location')]
locationSource=[xpath]://div[@class='wex-editable-row-label' and normalize-space(text())='Source']
locationSourceValue=[xpath]://div[@class='wex-editable-row-label' and normalize-space(text())='Source']/following-sibling::div//div[@id='cellular-location']
locationReloadBtn=[xpath]://div[contains(@class,'reloadLabel')]

logsTab= [xpath]://div[@id='logs']
logsTabLink= [xpath]://a//span[text()='Logs']
logsHeader= [xpath]://h3[@id='logs']
logsWarning= [xpath]://div[@class='wex-logs-warn']
logsType= [xpath]://div[@id='type']//span
logsTypeInput= [xpath]://input[@name='type']
logsTypeInputOptions=[xpath]://ul[contains(@id,'type-listbox')]//li
logsSubType= [xpath]://div[@id='source']
logsSubTypeInputOptions=[xpath]://*[@id="source-listbox"]/li
clearfilter=[xpath]: //button[@aria-label='Clear Filters']//span[2]
dateAndTimeSorting=[xpath]://button[contains(@aria-label,'sort by Date and Time')]
inputeDescription=[xpath]://input[@id='description']
calenderStartSelect=[xpath]://input[@id='date_picker-start-input']
calenderEndSelect=[xpath]://input[@id='date_picker-end-input']
logTableFirstRow=[xpath]://table[@id='logs']/tbody/tr[1]
logTableFirstRowDateAndTime=[xpath]://table[@id='logs']/tbody/tr[1]/td[2]
logTableFirstRowDescription=[xpath]://table[@id='logs']/tbody/tr[1]/td[5]
logTableFirstRowAllColumns=[xpath]://table[@id='logs']/tbody/tr[1]/td


accountMenu=[xpath]://a[@id='menu_accountManagement']				
userTab=[xpath]://div[@id='users']
inviteUserButton=[xpath]://button[@id='btn_user_add']
addUser_addManually=[xpath]://div[@id='card_addUser_addManually']
addManually=[xpath]://div[@id='add_manually']
newUserFirstName=[xpath]://input[@id='new_user_first_name_0']
newUserLastName=[xpath]://input[@id='new_user_last_name_0']
newUserEmail=[xpath]: //input[@id='new_user_email_0']
newUserSelectIDP=[xpath]: //div[contains(@class, 'vn-select__placeholder')]//span[text()='Select IDP']
newUserSelectHPID=[xpath]://ul//li[@data-value='HPID']
newUserSelectHPIDNextbtn=[xpath]://button[@id='btn_submit']
newUserAssignRole=[id]:user_role
newUserAssignRoleSearch= [xpath]://input[@placeholder='Search Items']
newUserLDARole=[xpath]://*[@id="user_role-option-0"]
inviteUserFinishBtn=[xpath]://button[@id='btn_submit']
inviteUserBackBtn=[xpath]://button[@id='btn_prev']
inviteUserAlert=[xpath]://div[@role='alert']/div
createdUserSearch=[xpath]://input[@id='email']


newcreatedUserEmail=[xpath]://input[@id='email']
newcreatedUserCheckbox=[xpath]://*[@id="Users"]/tbody/tr/td[1]/span/label/input
deleteUserLink=[xpath]://button[@id='btn_user_remove']
deleteUserPopup=[xpath]://div[@id='dui-remove-user']
deleteUserSecurityCode=[xpath]://h6[@id='security-code-number']
deleteUserSecurityCodeinput=[xpath]://input[@id='security-code']
deleteUserPopupCancel=[xpath]://button[@id='modal-cancel']
deleteUserPopupSubmit=[xpath]://button[@id='modal-submit']
deleteUserAlert=[xpath]://div[@role='alert']


assignRoleLink=[xpath]://button[@id='btn_assign_roles']
rolesModal-label=[id]:rolesModal-label
rolesModal=[id]:rolesModal
assignRoleInput=[xpath]://input[@id='search']
itAdminCheckbox=[xpath]://input[@name='it_admin']
rolesCancelBtn=[id]:rolesCancelBtn
rolesCancelBtn=[id]:rolesSaveBtn
roleAssignAlert=[xpath]://div[@role='alert']


remindApproverLink=[xpath]://button[@id='btn_remind_approvers']
remindApproverSubTitle=[xpath]://div[@id='dui-remind-approvers']
remindApproverSubmit=[xpath]://button[@id='modal-submit']
remindApproverCancel=[xpath]://button[@id='modal-cancel']
remindApproverAlert=[xpath]://div[@role='alert']

resendInvitaionLink=[id]:btn_resend_invitation
resendInvitaionPopup=[xpath]://div[@id='dui-remove-device']
resendInvitaionButton=[xpath]://button[@linkid='ResendInvitation_ResendBtn']
resendInvitaionCancelButton=[xpath]://button[@id='modal-cancel']
resendInvitaionAlert=[xpath]://div[@role='alert']


biosDataTable=[xpath]://table [@class='css-19wo2yk']
driverDataTable=[xpath]://table [@class='css-4mb5rm']
biosDataTableFirstRow=[xpath]://table[@class='css-19wo2yk']/tbody/tr[1]
driverDataTableFirstRow=[xpath]://table[@class='css-4mb5rm']/tbody/tr[1]

selectAllDevice=[xpath]://input[@type='checkbox' and contains(@aria-label,'Select all')]
changePlanButton=[xpath]://*[@id='change-plan']
changePlanTitle=[xpath]://*[contains(@class,'vn-modal--title')]
changePlanSelect=[xpath]://div[@id='change_plan_select_company_container']
changePlanSelectOptions=[xpath]://*[@id='change_plan_select_company_container-listbox']/li
changePlanBtn=[xpath]://button[@id='save-plan-btn']
cancelPlanBtn=[xpath]://button[@id='cancel-plan-btn']
changePlanAlert=[xpath]://div[@role='alert']/div/div
planColumnHeader=[xpath]://button[contains(@aria-label,'HP Wolf Protect and Trace')]
#planColumnHeaderText=[xpath]://button[contains(@aria-label,'HP Wolf Protect and Trace')]/span[1]
planColumnHeaderTextValue=[xpath]://*[@id="devices"]/tbody/tr/td[8]/div/div/div[2]
planEnrollmentHeader=[xpath]://div[@id='plan-enrollment-header']/h3
editPlanEnrollment=[xpath]://button[@id='edit-enrollment']
editPlanTitle=[xpath]://*[contains(@class,'vn-modal--title')]
editPlanText=[xpath]://*[contains(@class,'dui-modal-content')]/div/p
editPlanDelete=[xpath]://*[@id='remove-another-device-1']
