cookieAccept = [css]:#onetrust-accept-btn-handler
whatsNewTabRoot = [xpath]://*[@id="menu_whatsNew_link"]
whatsNewTabMspRA = [id]:menu_whatsNew
whatsNewTitle = [xpath]://span[@aria-current='page']
whatsNewDraftButton = [xpath]://*[@id="draft-new-release-btn"]
whatsNewTitleOnBreadcrumbs = [css]:#whatsNew li
draftNewReleaseButton = [xpath]://*[@class='dui-action-bar']//button
draftNewReleaseButtonFirst = [id]:secondary-id
dateField = [name]:date
platformChoice = [xpath]://*[@id="platform-input"]//span
platformWorkForceExp = [xpath]://*[@id="platform-input-option-0"]
platformDaas = [xpath]://*[@id="platform-input-option-1"]
platformBoth = [xpath]://*[@id="platform-input-option-2"]
releaseVersion = [xpath]://*[@id="release-version-input"]
selectDatepicker = [xpath]://*[@id="date_picker"]
customerNotes = [xpath]://*[@id="customer-notes"]
partnerNotes = [xpath]://*[@id="partner-notes"]
saveDraftButton = [id]:save-new-draft-btn
whatsNewHeading = [xpath]:(//*[@id="dui-container"]//div//h3)[1]
whatsNewtile = [xpath]://*[@id="whats-new"]
helpIcon = [css]:#help-support-button
WhatsNewIcon = [id]:menu_whatsNew
DraftButton = [id]:draft-new-release-btn
DraftNewText = [xpath]://h4[text()='Draft a New Release']
SelectDropDown = [xpath]://input[@id='platform-input' ]
WFXDropDown = [xpath]:(//ul[@id='platform-input-listbox']//li)[1]
DaasDropDown = [xpath]:(//ul[@id='platform-input-listbox']//li)[2]
BothDropDown = [xpath]:(//ul[@id='platform-input-listbox']//li)[3]
ReleaseVersionText = [id]:release-version-input-label
SelectdateText = [id]:date_picker-label
CustomerNotesText = [id]:customer-notes-label
PartnerNotesText = [id]:partner-notes-label
PartnernoteTextbox = [id]:partner-notes
partnernotesbold = [xpath]://div[@id='partner-notes']//span[@title='Bold']
SaveButton = [id]:save-new-draft-btn
CancelButton = [id]:cancel-new-draft-btn
catorgorydropdownlistboxwhatsnew = [xpath]:(//ul[@role='listbox']//li[@role='option'])[3]
releaseversiontextbox = [id]:release-version-input
customernotestextbox = [id]:customer-notes
partnernotestextbox = [id]:partner-notes
releasesuccessfulpopup = [xpath]://div[text() ='A new release version was added.']
editbutton = [xpath]:(//button[.//span[text()='Edit']])[1]
deletebutton = [xpath]:(//button[.//span[text()='Delete']])[1]
DeleteRelease = [xpath]://h4[text()='Delete Release']
deletepopup = [xpath]://div[@class='content']
DeleteReleaseDeletebutton = [id]:btn_remove
DeleteReleaseCancelbutton = [id]:btn_cancel
ReleaseText = [xpath]://h4[contains(@class, 'vn-modal') and contains(@class, 'title') and starts-with(text(), 'Release ')]
platformtext = [id]:platform-input-label
updatedtext = [xpath]://div[starts-with(text(), 'Release ') and contains(text(), 'was updated')]
