companyHome = [xpath]://span[contains(text(),'Home')]
wexScore = [xpath]://div[@id='wex-score-label']//h2[@class='wexcard-header-title']
wexScoreOverTime = [xpath]://div[@id='wex-score-over-time']//h2[@class='wexcard-header-title']
recommendedActions = [css]:div.recommended-actions
fleetInventory = [xpath]://div[@id='fleet-inventory-label']//h2[@class='wexcard-header-title']
appsWithMostCrashes=[xpath]://div[@id='installed-apps-most-crashes']//h2[@class='wexcard-header-title']
sendFeedback = [css]:#send-feedback h6>div>div
######String
wexScoreString = Experience Score
wexScoreOverTimeString = Experience Over Time
recommendedActionsString = Recommended Actions
fleetInventoryString = Fleet Inventory
appsWithMostCrashesString = Top App Crashes
sentimentPersonaString = Send Feedback

devicesChartDashboard = [xpath]:(//div[@id='wex-score-devices-title'])
secChartDashboard = [xpath]:(//div[@id='wex-score-security-title'])
reactSkelaton = [xpath]://div[@class='dui-page-spinner']//*[name()='svg']
fleetSecurityTab = [xpath]:(//h6[@class='wex-tile-header-title'])[1]

onboarding = [xpath]:(//*[@class='dui-item-vertical-center']//div[2])[1]
onboardingCount = [xpath]://*[@class="wex-checklist-count"]
onboardingTitle = [xpath]://*[@id="daas_routes_wrapper"]//header//ul//div[1]/p
onboardingTitleCount = [xpath]:(//*[@class='wex-checklist-sub-list'])[1]
firstStep = [xpath]:(//*[@class="wex-checklist-menu-section-title"]/li)[1]
discoverMore = [xpath]:(//*[@class="wex-checklist-menu-section-title"]/li)[2]
monitorDevice = [xpath]://*[@id="wex_checklist_item_monitorIssues"]/li
improveExpScore = [xpath]://*[@id="wex_checklist_item_improveExpScore"]/li
deviceAddedNotification = [xpath]://*[@id="wex_checklist_item_addDevices"]//li
exploreFleetMgmt = [xpath]://*[@id="wex_checklist_item_exploreFleetManagementInsights"]/li
monitorIssue = [xpath]://*[ @id="wex_checklist_item_monitorIssues"]/li
recommendationActions = [xpath]://*[@id="wex_checklist_item_recommendedActions"]
customePulse = [xpath]://*[@id="wex_checklist_item_createCustomPulse"]//li
sentimentPulse = [xpath]://*[@id="wex_checklist_item_createSentimentPulse"]//li
moreFeedback = [xpath]://*[@id="wex_checklist_item_getHelp"]//li
addDevice = [xpath]:(//*[@id="download-client-software"])[1]
addUser = [xpath]://*[@id="users"]
notificationPopUp = [xpath]://*[@id="dui-app-scroll"]/div[4]
userAddNotification = [xpath]://*[@id="wex_checklist_item_addUser"]//li
profileCompNotification = [xpath]://*[@id="wex_checklist_item_completeCompanyProfile"]//li
setupInteNotification = [xpath]://*[@id="wex_checklist_item_setupIntegrations"]//li
customizeAlerts = [xpath]://*[@id="wex_checklist_item_customizeAlerts"]//li
deviceIssues = [xpath]://*[@id="wex_checklist_item_deviceIssues"]//li

experienceScore = [xpath]://*[@id="wex-score-label"]/div/div[1]
experienceOverTime = [xpath]://*[@id="wex-score-over-time"]/div/div[1]
recommendedActionTab = [xpath]://*[@class="dui-dex-recommended-container"]
fleetInventoryTab = [xpath]://*[@id="fleet-inventory-label"]/div/div[1]
appWithMostCrashes = [xpath]://*[@id="installed-apps-most-crashes"]/div/div[1]
sendFeedbackTab = [xpath]://*[@id="send-feedback"]/div/div[1]

overallScore = [xpath]:(//*[@id="wex_menu_item_value"]/li)[1]
overallScoreVal = [xpath]:(//*[@id="wex_menu_item_value"]//span[2]/div/span)[1]
sentimentScore = [xpath]://div/span[contains(text(),'Sentiment')]
sentimentScoreVal = [xpath]://div/span[contains(text(),'Sentiment')]/ancestor::span/following-sibling::span/div/span[@class='score']

sysHealthScore = [xpath]://div/span[contains(text(),'System Health')]
sysHealthScoreVal = [xpath]://div/span[contains(text(),'System Health')]/ancestor::span/following-sibling::span/div/span[@class='score']
osPerfScore = [xpath]://div/span[contains(text(),'OS Performance')]
osPerfScoreVal = [xpath]://div/span[contains(text(),'OS Performance')]/ancestor::span/following-sibling::span/div/span[@class='score']
networkHealthScore = [xpath]://div/span[contains(text(),'Network Health')]
networkHealthScoreVal = [xpath]:(//div/span[contains(text(),'Network Health')]/following::span[@class='score'])[1]
securityScore = [xpath]://div/span[contains(text(),'Security')]
securityScoreVal = [xpath]://div/span[contains(text(),'Security')]/ancestor::span/following-sibling::span/div/span[@class='score']
applicationScore = [xpath]://div/span[contains(text(),'Applications')]
applicationScoreVal = [xpath]://div/span[contains(text(),'Applications')]/ancestor::span/following-sibling::span/div/span[@class='score']

expOvrTimeImp = [xpath]:(//*[@class="wex-empty-state-widget-img"])[1]
expOvrTimeGraph = [xpath]://*[@id="wex-score-over-time"]/div/div[2]
fleetInventoryCount = [xpath]://*[@id="pc"]/div[2]
experienceScoreNoData = [xpath]://div[@id='wex-score-label']//div[@class='wex-empty-state-widget']
appWithCrashNoData = [xpath]://div[@id='apps-most-crashes']//div[@class='wex-empty-state-widget']
appWithCrashData = [xpath]:(//div[@id='apps-most-crashes']//div[1])[1]
sendFeedbackLink = [xpath]://*[@id="send-feedback-button"]
sendFeedbackForm = [xpath]://section[1]//strong

viewListOfPCDevices = [xpath]:(//*[@id="fleet-inventory-label"]//button)[2]/span
overviewAccMgmt = [xpath]://*[@id="overview"]/div
timezoneAccMgmt = [xpath]://*[@id="company-timezone"]
dateFormatAccMgmt = [xpath]://*[@id="createdOnPanel"]
usersAccMgmt = [xpath]:(//div[@id='users']/div)
inviteUsersAccMgmt = [id]:btn_user_add
emailUsers = [id]:email
userProfile = [id]:user-profile
editTimeZone = [xpath]://*[@id="edit-timezone"]
editTimeZoneVal = [xpath]://*[@id="dui-company-timezone-select-box"]/span
cancelBtn = [xpath]://*[@id="dui-company-timezone-cancel"]
editDateValueDrpDwn = [xpath]://*[@id="edit_modal_undefined"]

fleetInventoryTitle = [xpath]:(//div[@id="fleet-inventory-label"]//div[contains(text(),'Fleet')])[1]
fleetInventoryWidget = [xpath]://div[@class="highcharts-legend"]//div//span
firstManufacturerLegendIcon=[xpath]:(//div[@class="highcharts-legend"]//span)[2]//div
secondManufacturerLegendIcon=[xpath]:(//div[@class="highcharts-legend"]//span)[4]//div
valueExtractor = [xpath]:(//*[@class="highcharts-subtitle"]/child::*)[1]
mfgCount = [xpath]:(//*[@class="highcharts-subtitle"]/descendant::*)[2]
chartCircle = [xpath]: //*[@id='pc_content']/descendant::*[@class="highcharts-series-group"]
accountManagement = [xpath]://span[contains(text(),'Account Management')]
integrations = [xpath]://a[@id="menu_integrations_link"]
clickOnWidget = [xpath]://*[@class='highcharts-series-group']/descendant::*[@role='img' and @aria-label='MSI, 12. Status.']

integrationTab=[xpath]://a[@id='menu_integrations']
serviceNow=[xpath]:(//div[contains(@data-testid,'connector-card')])[1]
tablue= [xpath]:(//div[contains(@data-testid,'connector-card')])[2]
entraIDAccount=[xpath]:(//div[contains(@data-testid,'connector-card')])[3]
powerAutomate=[xpath]:(//div[contains(@data-testid,'connector-card')])[4]
entraIdGroup=[xpath]:(//div[contains(@data-testid,'connector-card')])[5]
splunk=[xpath]:(//div[contains(@data-testid,'connector-card')])[6]
powerBi=[xpath]:(//div[contains(@data-testid,'connector-card')])[7]
connectorFrame=[xpath]://iframe[@id='iframe-fastn-widget']

#Experience Over Time
experienceOverTime = [xpath]:(//h2[@class="wexcard-header-title"])[2]/div/div[1]
experienceOverTimeGraph = [xpath]:(//*[@class="highcharts-series-group"])[1]
great = [xpath]:(//button[contains(@aria-label,'Show Series')])[1]
fair = [xpath]:(//button[contains(@aria-label,'Show Series')])[2]
poor = [xpath]:(//button[contains(@aria-label,'Show Series')])[3]
experienceOverTimeXaxis = [xpath]:(//*[@class="highcharts-axis-labels highcharts-xaxis-labels"])[1]
experienceOverTimeYaxis = [xpath]:(//*[@class="highcharts-axis-labels highcharts-yaxis-labels"])[1]
experienceOverTimeGraph1 = [xpath]://*[@id="wex-score-over-time"]//div[@class="wexcard-content"]
experienceOverTimeGraph2 =  [xpath]://*[@id="wex-score-over-time"]//div[@class="wexcard-content-area"]
experienceOverTimeGraph3 =  [xpath]://*[@id="wex-score-over-time"]//div[@class="wex-score-overtime"]
expOverTImeframeworkFilter = [xpath]://div[@class="dui-display-flex"]
expOverTimeFilter = [xpath]:(//div[@id='wex-score-over-time']//div/span)[1]
last30Days = [xpath]://*[contains(@id,"option-0")]
last60Days = [xpath: //*[contains(@id,"option-0")]/following-sibling::li[1]
last90Days = [xpath]: //*[contains(@id,"option-2")]

#FleetInventory
fleetInventoryContent= [xpath]://ul[contains(@class,'fleet-inventory')]/li//div[@class='fleet-inventory-content-row-title']
categoryNamePC= [xpath]:(//ul[contains(@class,'fleet-inventory')]/li//div[@class='fleet-inventory-content-row-title'])[1]
categoryNamePrint= [xpath]:(//ul[contains(@class,'fleet-inventory')]/li//div[@class='fleet-inventory-content-row-title'])[2]
categoryNameVM= [xpath]:(//ul[contains(@class,'fleet-inventory')]/li//div[@class='fleet-inventory-content-row-title'])[3]
categoryNameVE= [xpath]:(//ul[contains(@class,'fleet-inventory')]/li//div[@class='fleet-inventory-content-row-title'])[4]
categoryNameTP= [xpath]:(//ul[contains(@class,'fleet-inventory')]/li//div[@class='fleet-inventory-content-row-title'])[5]
categoryName= [xpath]://ul[contains(@class,'fleet-inventory')]/li//div[@class='fleet-inventory-content-row-title']
chartColorBarsPC = [xpath]://div[@id='pc_content']//div[starts-with(@id,'highcharts-')]//*[local-name()='path' and contains(@class,'highcharts-point')]
chartColorBarsPrint = [xpath]://section[contains(@id,'printers-inventory')]//div[starts-with(@id,'highcharts-')]//*[local-name()='path' and contains(@class,'highcharts-point')]
#chartColorBarsPrint = [xpath]://*[@data-testid='inventory-chart-online-chart-1']//*[local-name()='path' and contains(@class,'highcharts-point')]
chartColorBarsVM = [xpath]://div[@id='virtualMachine_content']//div[starts-with(@id,'highcharts-')]//*[local-name()='path' and contains(@class,'highcharts-point')]
chartColorBarsVE = [xpath]://div[@id='videoEndpoints_content']//div[starts-with(@id,'highcharts-')]//*[local-name()='path' and contains(@class,'highcharts-point')]
chartColorBarsTP = [xpath]://div[@id='telephones_content']//div[starts-with(@id,'highcharts-')]//*[local-name()='path' and contains(@class,'highcharts-point')]

chartToolTip = [xpath]://div[contains(@class,'highcharts-tooltip')]//span//span
appsWithMostCrashesTitle = [xpath]://*[@id='installed-apps-most-crashes']//h2/div/div[1]
pcContent = [xpath]://*[@id="pc_content"]//button[contains(@class,'view-list-button')]