Overviewcompanyname = [xpath]://h1[@class='dui-dsummary-card-title']
PlanName = [id]:summary-card-plan-value
companystatus = [xpath]://div[@class="dui-dsummary-card-desc-content-icon"]
Overviewtab = [xpath]://div[@id='overview']
overviewTabSelected = [xpath]://*[@id="overview"][@aria-selected="true"]
accountManagement =[id]:menu_accountManagement
#company profile 
companyprofileheader = [id]:company-profile-header
customerid = [id]:display-id
companyname = [id]:company-name
companynameeditbutton = [id]:edit-company-name
companynamelabel = [id]:dui-text-modal-label
companynametextboxlabel = [id]:dui-text-modal-text-box-label
companynametextbox = [id]:dui-text-modal-text-box
companynamesubmitbutton = [id]:dui-text-modal-submit
companynamecancelbutton = [id]:dui-text-modal-cancel
companysize = [id]:company-size
companysizeeditbutton = [id]:edit-company-size
Companysizeheader = [id]:dui-company-size-label
Companysizelistbox = [id]:dui-company-size-select-box
companysizedropdown = [xpath]://div[@id="dui-company-size"]//ul//li
companysizesavebutton = [id]:dui-company-size-submit
companysizecancelbutton = [id]:dui-company-size-cancel

companycreatedon = [id]:createdOnPanel
companytimezone = [id]:company-timezone
companytimezoneeditbutton = [id]:edit-timezone
companytimezonelabel = [id]:dui-company-timezone-label
companytimeselectboxlabel = [id]:dui-company-timezone-select-box-label
companytimezoneselectbox = [id]:dui-company-timezone-select-box
companytimezonesubmitbutton = [id]:dui-company-timezone-submit
companytimezonecancelbutton = [id]:dui-company-timezone-cancel


#primary administrator
primaryadministratorheader = [id]:primary-administrator-header
adminname = [id]:admin-name
Adminemail = [id]:emailPanel
amdincontactnumber : [id]:admin-contact-number
primaryadministratoreditbutton = [id]:edit-company-primary-account
primaryadministratorheaderpopup = [id]:dui-company-owner-modal-label
primaryadministratorselectbox = [id]:dui-company-owner-modal-select-box
primaryadministratorsavebutton = [id]:dui-company-owner-modal-submit
primaryadministratorcancelbutton = [id]:dui-company-owner-modal-cancel

#company address
companyaddressheader = [id]:company-address-header
companycountry = [id]:country
companystate = [id]:state
companyaddress1 = [id]:address-line-1
companyaddress2 = [id]:address-line-2
companycity =  [id]:namePanel
companyzipcode = [id]:postalCode
Companyaddresseditbutton = [id]:edit-address
companyaddresslabel = [id]:dui-company-address-label
companycountrylabel = [id]:dui-form-modal-field-0-label
companycountrytextbox = [id]:dui-form-modal-field-0
companyaddressline1label = [id]:dui-form-modal-field-1-label
companyaddressline1textbox = [id]:dui-form-modal-field-1
companyaddressline2label = [id]:dui-form-modal-field-2-label
companyaddressline2textbox = [id]:dui-form-modal-field-2
companycitylabel = [id]:dui-form-modal-field-3-label
companycitytextbox = [id]:dui-form-modal-field-3
companystatelabel = [id]:dui-form-modal-field-4-label
companystatetextbox = [id]:dui-form-modal-field-4
companyzipcodelabel = [id]:dui-form-modal-field-5-label
companyzipcodetextbox = [id]:dui-form-modal-field-5
companysavebutton = [id]:dui-company-address-submit
companycancelbutton = [id]:dui-company-address-cancel


#toaste notification
toastNotification = [xpath]://div[@class='css-6zjv1s']
