nameEdit = [xpath]:(//*[@id='namePanel']//div)[6]
roleEdit = [id]:edit-role
editFirstName = [name]:edit_modal_firstName
editLastName = [name]:edit_modal_lastName
saveButtonUserName = [id]:editSaveBtn
cancelButtonUserName = [id]:editCancelBtn
roleSearch = [id]:search
roleResultCheckBox = [xpath]://*[contains(@class,'roles-list')]//span[1]
rolesSaveBtn = [id]:rolesSaveBtn
rolesCancelBtn = [id]:rolesCancelBtn
toastMessageonUserRole = [xpath]://div[@role="status"]
#[xpath]://div[@role='alert']//div/div
Firstcheckbox= [xpath]://input[contains(@aria-label,'Select user')]
resendinvitation= [id]:btn_resend_invitation
resendbutton = [xpath]://button[@linkid='ResendInvitation_ResendBtn']
nameUpdatedValue = [xpath]://*[@id='namePanel']//div[contains(@class,'editable-value')]
usePasswordButton=[id]:use-password-btn
passowrdTextBox=[id]:password
codeTextBox=[id]:code
verifyButton=[id]:submit-code
createButton=[xpath]://*[@id="create-account-btn"]
roleUpdatedValue  = [xpath]://*[@id='dui-accountAndRoles']//span/div
userDetailsPageTitle = [xpath]://*[@id="summary-card-title"]
userEmailDetails = [xpath]: //*[contains (@class,'summary-card-desc-content-wex-desc')]
userStatus = [xpath]: //*[contains (@class, 'summary-card-desc-icon-status')]
userProfile = [xpath]://*[@id="user-profile"]
userProfileHeader = [xpath]://div[@id='user-profile']//h3
userProfilePageManagement = [xpath]://*[@id="user-management-header"]
userProfilePageManagementHeader = [xpath]://*[@id="user-management-header"]/h3
userManagement = [xpath]://*[@id="user-management"]
userManagementHeader = [xpath]://*[@id="user-management"]//div//h3
userRoles= [xpath]://div[@id='dui-accountAndRoles']
userRolesHeader = [xpath]://div[@id='dui-accountAndRoles']//h3
assignedDevices =[xpath]://*[@id="usersDetailsDevicesPanel"]
assignedDevicesHeader = [xpath]://*[@id="assigned-devices-header"]
assignedDevicesContent = [xpath]://*[contains(@class,'wex-panel-content-wrapper')]
checkbox = [xpath]:(//span[contains(@class,'checkbox__span')])[2]
assignRolesText = [xpath]://h4[@id='rolesModal-label']
assignbutton = [xpath]://*[@id="rolesSaveBtn"]
assigncancelbutton = [xpath]://*[@id="rolesCancelBtn"]
deleteBtn = [id]:remove-role-btn
editrole = [id]:edit-role
idpValue = [xpath]:(//*[@id="idp"]//div//div)[2]
idpSection = [xpath]://*[@id="idp"]
passwordSection = [xpath]://*[@id="passwordPanel"]






