usersTab = [css]:#users
usersTabSelected = [xpath]://*[@id="users"][@aria-selected="true"]
InviteButton = [id]:btn_user_add
addUserTitle = [xpath]://div[@class='row']//h4
addManualText = [xpath]:(//div/div/p[@class='user-content-desc'])[2]
upLoadCSVText = [xpath]:(//div/div/p[@class='user-content-desc'])[3]
addAADText = [xpath]:(//div/div/p[@class='user-content-desc'])[1]
cancelButtonText = [xpath]://button[@id='btn_cancel']
InviteTitle = [xpath]://h4[@id='add_manually-label']
stepInformation = [xpath]://*[@class='add-manually-stepper']
userInformationText = [xpath]://h6[contains(@class ,'add-user-information')]
subHeadingAddUser = [id]:add-manually-description
addAnotherUserBtn = [id]:add_new_user
#addAnotherUserBtn = [id]:btn_user_add
addUserCancelBtn = [xpath]://*[@id='btn_cancel']
addUserBackBtn = [id]:btn_prev
addUserNextBtn = [id]:btn_submit
firstNameTextBox = [id]:new_user_first_name_0
lastNameTextBox = [id]:new_user_last_name_0
emailTextBox = [id]:new_user_email_0
idpTypeDropDown = [xpath]://input[@placeholder='Select IDP']
idTypeDropDownList = [xpath]:(//ul[@role='listbox']/li)[1]
userRoleDropDown = [id]:new_user_role_0
roleClearButton = [xpath]:(//button[@title='Clear'])[2]
roleSearchInput = [xpath]://div//input[@placeholder='Search Items']
customeRole = [xpath]://li[@role='option']
selectRoleOption = [xpath]://li[@role='option']
searchInput = [xpath]://*[@aria-describedby='add_manually-desc']/following-sibling::div[2]//input
roleDropDownList = [xpath]://*[@aria-describedby='add_manually-desc']/following-sibling::div[2]//li
roleDropResult = [id]:new_user_role_0
toastMessage = [xpath]://*[contains(@id,"toast-title")]
emailInput= [name]:email
emailInputValue = [xpath]:(//*[contains(@class,'wex-value-field')]//a)[1]
roleListValue = [xpath]://table/tbody/tr//td[4]
roleListValue_partner = [xpath]:(//*[@class="wex-tag-content"])[1]
userNameValue = [xpath]:(//*[contains(@class,'wex-value-field')]/span)[2]
role = [xpath]://div[@id='dui-accountAndRoles']//h3
inviteTab = [xpath]://div[contains(text(),'Invited')]
roleValue = [xpath]://*[@id="it-admin"]
partnerRoleValue = [xpath]:(//*[@id="dui-accountAndRoles"]//div[2])[2]
emailPanel = [xpath]://*[@id="emailPanel"]
roleListValues = [xpath]://*[contains(@class,'wex-tag-item')]/div
invitestatus = [xpath]:(//*[@id="inviteStatus"])[1]
userstatusdropResult = [xpath]://input[@id='inviteStatus']
#status-listbox
acceptedStatus = [xpath]://li[@data-value = 'ACCEPTED']
nameCol =  [xpath]:(//*[@id="name"])[1]

invitedStatus = [xpath]://li[@data-value = 'INVITED']
userlistEmailField=[xpath]://*[@id="Users"]/tbody/tr[1]/td[3]/div/div[1]//a
firstUserlistEmail=[xpath]://*[@id="Users"]/tbody/tr[1]/td[3]/div[1]/div/a
tableOverlay=[css]:div[class*='table__overlay--loading']
accountManagementHeader = [xpath]:(//div[contains(@class,'wex-header')]//a)[2]
noItemsAvailable = [xpath]://h3[@class='state-title']
statusList = [xpath]://ul[@id="inviteStatus-listbox"]

usersListName = [xpath]:(//table[@id="Users"]/tbody/tr[1]/td[2]//span)[2]
mspUserListName = [xpath]://table[@id="MSPUsers"]/tbody/tr[1]/td[2]//a
mspUserSecondListName = [xpath]://table[@id="MSPUsers"]/tbody/tr[2]/td[2]//a
partnerUserListName = [xpath]://table[@id="partnerUsers"]/tbody/tr[1]/td[2]//a
rootUserListName = [xpath]://table/tbody/tr[1]/td[2]//a
usersListCheck = [xpath]://*[@id="Users"]/tbody/tr[1]/td[1]
checkbox = [xpath]:(//span[contains(@class,'checkbox__span')])[2]
secondCheckbox = [xpath]:(//span[contains(@class,'checkbox__span')])[3]
checkrole = [xpath]:(//*[@id='roles-modal-list']//div//span)[1]
resendInvite = [id]:btn_resend_invitation
popuptext = [xpath]://div[@role='dialog']/h4
rootUserPopUPText = [xpath]://div[@role='dialog']/h4
resendpopup= [xpath]://div[@id='dui-remove-device']
resendCancel= [xpath]://button[@id='modal-cancel']
resendsubmit = [id]:modal-submit
userstatuscol  = [xpath]://input[@id="inviteStatus"]
resendMessage = [xpath]:(//div[@role='status'])[2]
resendmessagerootuser = [xpath]://div[@role='status']

enterFnameErr = [xpath]://*[@id="new_user_first_name_0-helper-text"]/span[2]
enterLnameErr = [xpath]://*[@id="new_user_last_name_0-helper-text"]/span[2]
enterEmailErr = [xpath]://*[@id="new_user_email_0-helper-text"]/span[2]
enterIDPErr = [xpath]:(//span[contains(@class,"caption text") and text()='Select IDP'])[1]

importFromAAD = [xpath]:(//*[@class='add-user-content'])[1]
addManually = [xpath]://*[@class='add-user-content']//p[text()='Add Manually']
addCSV = [xpath]://*[@class='add-user-content']//p[text()='Upload CSV']
clearRole = [xpath]://*[@id="add_manually-desc"]//span/button
selectRole = [xpath]://*[@id="new_user_role_0"]
searchRole = [xpath]://*[@placeholder="Search Items"]
roleValues = [xpath]://*[@id="new_user_role_0-option-0"]
roleVals = [xpath]:(//*[@id="dui-accountAndRoles"]//div[2]//div)[1]
nameText = [xpath]:(//*[@id="name"])[1]
emailText = [xpath]:(//*[@id="email"])[1]
roleText = [xpath]:(//*[@id="roles"])[1]
deleteText = [id]:btn_user_remove
assignRoles =[id]:btn_assign_roles
deleteparaText = [xpath]://div/p[@class='remove-user-desc']
assignRolesText = [xpath]://h4[@id='rolesModal-label']
assignbutton = [xpath]://button[@id='rolesSaveBtn']
assigncancelbutton = [xpath]:(//button[@id='rolesCancelBtn'])[2]
rolesCancelButton = [xpath]://button[@id='rolesCancelBtn']
clearFilter = [xpath]://*[@id="extended-users"]//button/span[2]

##CSV and AAD popup 
addUsers = [xpath]://div[@role='dialog']/h4
uploadCSV = [xpath]://h6[contains(@class,'dui-padding-bottom')]
importBtn = [id]:btn_import
uploadFile = [xpath]://*[@id='uploadUserList-label']
downloadBtn = [xpath]://*[@id='container_uploadUserList']//div/button
uploadFileBtn = [xpath]://*[@id='uploadUserList']
CSVUploadToastMsg = [xpath]://div[@role='status']//div
selectAllCheckbox = [xpath]:(//span[contains(@class,'checkbox__span')])[1]
selectedCount = [xpath]://span[contains(@class,'label-small') and contains(text(),'selected')]
usePasswordButton=[id]:use-password-btn
Lastname = [xpath]://input[@value='LastNameUser']
lastnametext = [id]:lastName
passowrdTextBox=[id]:password
createBtn = [id]:create-account-btn
signinBtn = [id]:sign-in
codeTextBox=[id]:code
verifyButton=[id]:submit-code
termAndConditionCheckbox =[id]:terms-agreement-checkbox
AcceptBtn = [xpath]://button[contains(@class,'accept')]
welcomePopupSkipButton =[xpath]://*[@id="welcomePopup_skipTourBtn"]
csvInvitedUsers = [xpath]://*[@class="wex-value-field-content "]
selectTyp = [xpath]://*[@class='dui-user-add']/h6
users = [xpath]:(//p[@class='user-content-desc'])[1]
groups = [xpath]:(//p[@class='user-content-desc'])[2]
noResults = [xpath]://*[@class="wex-empty-state-widget-img"]
partnerPopup = [xpath]://*[@class ="partner-opt-in-content-center"]
closePopup = [xpath]://button[contains(@class,'sign-in-btn')]/span

roleColumn = [xpath]://input[@id="roles"]
roleinput = [xpath]:(//*[@placeholder="Search"])[3]
ITRole = [xpath]://li[@data-value='connector_admin']
roleSearch = [xpath]://input[@id='search']

#Overview tab
overviewTab = [xpath]://*[@id="overview"]/div
compProfileheader = [xpath]://div[@id='company-profile-header']/h3
primAdmin = [id]:primary-administrator-header
compAddre = [id]:company-address-header
customId = [xpath]:(//div[@id='display-id']/div)[1]
compNm = [xpath]:(//div[@id='company-name']/div)[1]
compSz = [xpath]://div[@id='company-size']/div
createdOn = [xpath]:(//div[@id='createdOnPanel']/div)[1]
adminNm = [xpath]://div[@id='admin-name']/div
mailId = [xpath]://div[@id='emailPanel']/div
countryNm = [xpath]://div[@id='country']/div
stateNm = [xpath]://div[@id='state']/div
cityNm = [xpath]://div[@id='namePanel']/div
zipCode = [xpath]://div[@id='postalCode']/div
phoneNo = [xpath]://div[@id='admin-contact-number']/div
address1 = [xpath]://div[@id='address-line-1']/div
address2 = [xpath]://div[@id='address-line-2']/div

assignedPartner = [css]:#assigned-partner
assignmentHeader = [xpath]:(//div[contains(@class,'wex-panel-header')])[1]
invitationsHeader = [xpath]:(//div[contains(@class,'wex-panel-header')])[2]
deleteIcon = [id]:unassign-partner-btn
#User Profile
profile = [xpath]://div[@class="profileCard-section"]
userProfileOption = [xpath]://div[@data-testid='wex_menu_item_users_profile']//button
profileTitle = [id]:userDetails
compProfile = [xpath]://*[@class="dui-dsummary-card-desc-content-view"]
userProfile = [id]:-user-profile-header
namePanel = [xpath]://div[@id='namePanel']/div
mobilePanel= [xpath]://div[@id='mobilePanel']/div
languagePanel = [xpath]://div[@id='languagePanel']/div
TimezonePanel= [xpath]://div[@id='TimezonePanel']/div
emailPanel = [xpath]://div[@id='emailPanel']/div
officePanel= [xpath]://div[@id='officePanel']/div
title = [xpath]://div[@id='jobTitlePanel']/div
usermanageHeader = [id]:user-management-header
idp = [xpath]://div[@id='idp']/div
passwordPanel = [xpath]:(//div[@id='passwordPanel']/div)[1]
rolesHeader = [id]:roles-header
idpValue = [css]:#hpid
switchAccount = [xpath]://div[@id="switch-account"]//li//button
switchTitle = [id]:switchAccount-select-label
switchButton = [id]:switchAccount-select-submit
cancelSwitch = [id]:switchAccount-select-cancel
switchSelectdropDown = [id]:switchAccount-select-select-box
switchUserName =  [xpath]://div[@id="switch-account"]//li
listOfSwitchUser = [xpath]://ul[@role="listbox"]/li
currentUserName =  [xpath]://input[@id="switchAccount-select-select-box"]
currentAccountName = [xpath]://div[@class='wex-profile-desc']
HelpAndSupportTab = [id]:help-support-button
userManagementHeader = [xpath]://div[@id='user-management-header']//h3
userRolesHeader = [xpath]: //div[@id='roles-header']//h3
securityCode = [id]:security-code-number
securityInput = [xpath]://input[@id='security-code']

selecRole = [xpath]://li[@data-value='testrole45erxl']