#WEX score widget

WEXScoreWidgetHeader = [xpath]: //*[@id="wex-score-label"]
ExperienceScoreWidget = [xpath]: //*[@id='wex-score-label']
ExperienceScoreParameters = [xpath]: //*[@id='wex_menu_item_value']

WEXviewDetail = [xpath]: //*[@id='wex_menu_item_value']//span[contains(text(),'Overall Score')]//following-sibling::span/div[contains(@class,'score-title-value')] 
ExperienceDetailPage = [xpath]: //*[@id='Employment Engagement Details']

topIssueimpactSentiment = [xpath]: //*[@id="top_issue_impacting_sentiment"]
TopIssueSentimentChart = [xpath]: //*[@id='top_issue_impacting_sentiment']//*[@class='highcharts-series-group']

TopDigitalIssuesHealth = [xpath]: //*[@id='top_digital_issues_health']
TopDigitalIssuesHealthEmpState = [xpath]: //*[@id='top_digital_issues_health']//*[@class='wex-empty-state-widget']

TopDigitalIssuesPerformance = [xpath]: //*[@id='top_digital_issues_top-os-performance-issues']
TopDigitalIssuesPerformanceEmpState = [xpath]: //*[@id='top_digital_issues_top-os-performance-issues']//*[@class='wex-empty-state-widget']


DeviceScoreGraph = [xpath]: //div[@class= "undefined fleet-score-card"]

ExperiencePills = [xpath]: //div[@class= "employees-experience-pills"]

ExperienceOverTime = [xpath]: //*[@id="wex-score-over-time"]
ExperienceOverTimeGraphLines = [xpath]: //*[@class='wex-score-overtime']//*[contains(@class,'highcharts-markers')] 

ExperienceDetailstabList = [xpath]: //*[@aria-label='Tab Navigation' and @role='tablist']/div

XaxisOptionsTIIS = [xpath]: //div[@id="top_issue_impacting_sentiment"]//span[@class="axis-label"]
We
