
PulseStatus = [xpath]: //*[@class="status-pill-container"]
FirstSentimentPulse = [xpath]: //*[@class ="pulse-survey-list"]//a[contains(text(), 'Sentiment Pulse')]
filterIcon = [xpath]: //button[@type="button"]/child::span[2][contains(text(), 'Filters')]
pulseresultpageTitle = [xpath]: //*[@aria-current='page']
pulseName = [xpath]: //*[@class='pulse-title']/h5
PulseResultTabs = [xpath]: //*[contains(@aria-controls, 'extended')]
ActionButton = [xpath]: //*[@class='pulse-actions' ]/div[@class=' action-btn']/button
ActionButtonOptions = [xpath]: //*[@role='menu']/li/span

AudienceTab = [xpath]: //*[@id='audience' and @role='tab']
AudienceTabTitle = [xpath]: //*[@class='audience-title']
AudienceLabels = [xpath]: //*[@class='method-label wex-neutral-base-default-color']
AudienceMethodType = [xpath]: //*[@class='method-type']

ScheduleTab = [xpath]: //*[@id='schedule' and @role='tab']
SceduleLabels = [xpath]: //*[@class='method-label wex-neutral-base-default-color']
ScheduleMethodType = [xpath]: //*[@class='method-type']
ScheduletabTitleDuration = [xpath]: (//*[@class='audience-title'])[1]
ScheduletabTitleFrequency = [xpath]: (//*[@class='audience-title'])[2]
ScheduletabPriority = [xpath]: //*[@class='audience-title priority']/div/span
ScheduletabPriorityIcon = [xpath]: //*[@class='audience-title priority']//button
PriorityIconSubHeaders = [xpath]: //*[@class="priority-sidebar-section-title"]
PriorityIconHeader = [xpath]: //*[@class="pulse-report-section-header overview-tooltip-side-bar-header" and text()="Priority definitions"]

Overviewtitle = [xpath]: //*[@class= 'overview-info-icon'] 
OverViewKPIs = [xpath]: //*[@class= 'pulse-count-label']
OverviewKPIicon = [xpath]: //*[@class='result-count-icon kpi-count']
OverviewKPIcount = [xpath]: //*[@class='pulse-count-label']/following-sibling::h5
overviewTooltip = [xpath]: //*[contains(@class, "over-view-section")]/child::button
OverviewDefinationtitle = [xpath]: //*[@class= 'pulse-report-section-header overview-tooltip-side-bar-header']
overviewTooltipKPItitle = [xpath]: //*[@class= 'kpi-title']
overviewTooltipKPIicon = [xpath]: //*[@class= 'kpi-icon result-count-icon']
overviewTooltipKPIcontent = [xpath]: //*[@class= 'kpi-info']
overviewTooltipclosebtn = [xpath]: //*[@id="new-pulse-report-sidebar"]//*[contains(@class, 'overview-tooltip-sidebar-close-btn')]/button

ResultTitle = [xpath]: //*[contains(@class, 'pulse-report-result-label')]
QuestionTitle = [xpath]: //*[@class= 'pulse-question-title']
ResponsePill = [xpath]: //*[contains(@class, 'wex-spotlight')]
PulseDetailPills = [xpath]: //*[@class='pulse-details-pills wex-stroke-default-border-all']

HighChartsGraph = [xpath]: //*[@class='highcharts-series-group']
AxisLabel = [xpath]: //*[@class='highcharts-axis-title']
YaxisLabels = [xpath]: //*[@class='highcharts-axis-labels highcharts-xaxis-labels']//*[ contains(text(),' Star')]
YaxisLabelstitle = [xpath]: ((//*[@class='highcharts-axis-labels highcharts-xaxis-labels'])[2])//text()
StarRatingValue = [xpath]: //*[@class='rating-value star-rating-val']
ResultCountIcon = [xpath]: //*[@class='star-section']//div[@class ='result-count-icon']
AverageRatingValue = [xpath]: //*[@class='rating-value']//span
RatingTitletext = [xpath]: //*[contains(@class,'rating-title wex-neutral-base-default-color')]

SecondCommentTitle = [xpath]: (//*[@class="free-text-comment-title"])[1]
ThirdCommentTitle = [xpath]: (//*[@class="free-text-comment-title"])[2]