hardwareSupportIcon = [xpath]: //*[@id="menu_newHardwareSupport"]/div
createCase = [xpath]: //button[@id="create-case-button"]
viewIncidents =[xpath] ://span[normalize-space()='View incidents']
generateXls =[xpath] ://button[@id='export_exl']
widgetList = [xpath] : //div[contains(@id, 'custom-dashboard')]//div/h2
createCaseModule = [xpath] : //*[@id="dui-wizard-modal"]
createCaseText=[xpath]://div[@id='dui-wizard-modal']//h5
incidentPageBreadcrumbXpath = [xpath]: //div[@id='incidentList']//li
#All Incidents by type
allIncidentsByTypeTitle = [xpath]: //*[normalize-space(text())='All Incidents by Type']/ancestor::div[1]/div[1]
allIncidentsByTypeViewDetaillink = [xpath]: //*[normalize-space(text())='All Incidents by Type']/following::button[normalize-space(.)='View Report'][1]
#createCase Modal
deviceSearchTextField = [xpath]://input[@placeholder="Search Items"]
dropdownBoxAfterSelection = [xpath]://input[@id="active-careDevices"]
deviceDropdownOptions = [xpath]://ul[@role="listbox"]//li
nextButtonCaseCreation = [xpath]://button[@id="dui-create-case-select-device-next"]
nextButtonIssueCaseCreation = [xpath]://button[@id="dui-create-case-select-issue-next"]
issueDropdownButton = [xpath]://input[@id="select-issue-create-case"]
issueDropdownOptions = [xpath]://ul[@id="select-issue-create-case-listbox"]/li
locationDropdownButton = [xpath]://input[@id="dui-create-case-select-location"]
locationDropdownOptions = [xpath]://ul[@role="listbox"]//li
nextButtonLocationCaseCreation = [xpath]://button[@id="dui-create-case-select-location-next"]
requestFromEndUser = [xpath]://ul//li[@data-value="REQUEST_FROM_USER"]
addressOption = [xpath]://ul[@id="dui-create-case-select-location-listbox"]//li[3]
reviewSubmitScreen = [xpath]://div[contains(text(),"Review and Submit")]
reviewSubmitButton =[xpath]://button[@id="dui-create-case-review-submit"]
requestLocationMessage = [xpath]://textarea[@name="requestLocationMessage"]
countryDropdownbutton = [xpath]://input[@id="country"]
countryDropdownOptions = [xpath]://ul[@role="listbox"]//li
nextButtonNewLocationCaseCreation = [xpath]://button[@id="dui-create-case-location-add-next"]
nextButtonPersonalInfoCaseCreation = [xpath]://button[@id="dui-create-case-personal-info-next"]
addressLine1 = [xpath]://input[@id="addressLine1"]
addressLine2 = [xpath]://input[@id="addressLine2"]
city = [xpath]://input[@id="city"]
state = [xpath]://input[@id="state"]
postalCode = [xpath]://input[@id="postalCode"]
firstName = [xpath]://input[@id="firstName"]
lastName = [xpath]://input[@id="lastName"]
emailId = [xpath]://input[@id="emailId"]
phoneNumber = [xpath]://input[@id="phoneNumber"]
deliveryInstruction = [xpath]://textarea[@id="delivery-instructions"]
clearAllFilterButton =[xpath]://button[@aria-label="Clear Filters"]
deviceSerialNumberSearch =[xpath]://input[@id="deviceSerial"]
#typecolumn
typeBox = [xpath]://input[@id='type']
typeListOptions = [xpath]://ul[contains(@id, 'floating-ui')]//li[@role='option']

#sub type column
subTypeBox = [xpath]://input[@id='subtype']
subTypeList = [xpath]://ul[contains(@id, 'floating-ui')]//li[@role='option']
selectedIncidentTitle = [css]:tr:nth-child(1) td:nth-of-type(2) a
caseInformationTileTitle = [css]:#dui-incident-case-details-panel h3[class*=dui-dpanel-header]
caseIDLabel = [css]:#dui-incident-case-id div[class*=label]
caseStatusLabel = [css]:#dui-incident-case-status div[class*=label]
caseSubmissionDate = [css]:#dui-incident-case-date div[class*=label]
caseLocation = [css]:#dui-incident-case-location div[class*=label]
caseContact = [css]:#dui-incident-case-contact div[class*=label]
caseCreatedSuccessToastMessage = [xpath]://div[contains(@id,'toast-title')]

#device serial number		
deviceSerialNumberSearchBox = [xpath]://input[@id='deviceSerial']
nextButton=[xpath]://div[@class='dui-create-case-buttons dui-margin-top-20 text-right']//button[2]
analyticsMenuOption = [xpath]: //*[@id="menu_reports"]
#analytics
hardwareSupport = [xpath]: //*[@id="custom-dashboard-hardware-support"]
#home
homeIcon = [xpath] : //a[@id='menu_home']
hardwareSupportIncidentTitle = [xpath]: //div[@id='hardware-support-incidents']//h2
typeColumn = [xpath]: //div[@class="wexcard-content-area"]//th[contains(text(),'Type')]
subType = [xpath]://div[@class="wexcard-content-area"]//th[contains(text(),'Subtype')]
deviceCount = [xpath]://div[@class="wexcard-content-area"]//th[contains(text(),'Device Count')]
#incidents
firstIdCheckBox = [css]:table#incidents tbody > tr:first-of-type input[type='checkbox']

#clearAllfilter
clearAllFilter = [xpath]://button[@aria-label='Clear Filters']
firstCheckBox = [css]:tbody>tr:nth-of-type(1) span input

incidentPopupHeading = [css]:div[class*=header] h4
incidentDropdownOption = [xpath]://ul[@role="listbox"]//li

assignToButton = [id]:assign_to
assignToInput = [id]:icm-assign-to-popup-select-box
assignToSaveButton = [id]:icm-assign-to-popup-submit

assignPriority = [id]:assign_priority
assignPriorityInputBox = [id]:icm-assign-priority-popup-select-box
assignPrioritySubmitButton = [id]:icm-assign-priority-popup-submit

changeState = [id]:change_status
changeStateInputBox = [id]:icm-change-status-popup-select-box
changeStateSubmitButton = [id]:icm-change-status-popup-submit

firstSerialNumberFromHardwareSupportIncidents = [xpath]://tr[contains(@class,'TableRow')][1]/td[10]//div[@class='wex-value-field-content ']
incidentTypeTooltipIcon = [xpath]://div[@id='dui-incident-type']//div[contains(@class,'dui-depr-edit-icon-tooltip')]
incidentDeviceTooltipIcon = [xpath]://div[@id='dui-incident-device']//div[contains(@class,'dui-depr-edit-icon-tooltip')]
tooltipMessage = [xpath]://div[contains(@class,'Tooltip') and @role='tooltip']//div[contains(@class,'root-Tooltip')]

descriptionSectionTitle = [xpath]://h3[@id='description']
detailsSectionTitle = [xpath]://h3[@id='details']

incidentIdNumberValue = [xpath]://div[@id='dui-incident-code']//div[@class='dui-depr-value']
incidentOccurredAtValue = [xpath]://div[@id='dui-incident-occured-at']//div[@class='dui-depr-value']//div[not(@class)]
incidentCreatedByValue = [xpath]://div[@id='dui-incident-created-by']//div[@class='dui-depr-value']//div[not(@class)]
incidentAssignedToValue = [xpath]://div[@id='dui-incident-assigned-to']//div[@class='dui-depr-value']//div[not(@class)]
incidentRepeatedValue = [xpath]://div[contains(@id,'dui-incident-repeated')]//div[@class='dui-depr-value']//div[not(@class)]
incidentWarrantyValue = [xpath]://div[contains(@id,'dui-incident-warranty')]//div[@class='dui-depr-value']//div[not(@class)]
incidentStateValue = [xpath]://div[@id='dui-incident-event']//div[@class='dui-depr-value']//div[not(@class)]
incidentPriorityValue = [xpath]://div[@id='dui-incident-priority']//div[@class='dui-depr-value']//div[not(@class)]
incidentTypeValue = [xpath]://div[@id='dui-incident-type']//div[@class='dui-depr-value']//div[not(@class)]
incidentSubTypeValue = [xpath]://div[@id='dui-incident-type']//p[@class='dui-hyphenate dui-panel-description']
incidentSerialNumberValue = [xpath]://div[@id='dui-incident-device']//p[@class='dui-hyphenate dui-panel-description']

summaryPriorityValue = [xpath]://div[contains(@class,'dui-dsummary-card-desc-content-title') and text()='Priority']/following-sibling::div[@class='dui-dsummary-card-desc-content-value']
summaryCreatedOnValue = [xpath]://div[contains(@class,'dui-dsummary-card-desc-content-title') and text()='Created on']/following-sibling::div[@class='dui-dsummary-card-desc-content-value']
summaryStateValue = [xpath]://div[contains(@class,'dui-dsummary-card-desc-content-title') and text()='State']/following-sibling::div[@class='dui-dsummary-card-desc-content-value']
summaryIdNumberValue = [xpath]://div[contains(@class,'dui-dsummary-card-desc-content-title') and text()='ID Number']/following-sibling::div[@class='dui-dsummary-card-desc-content-value']
summaryProblemCodeValue = [xpath]://div[contains(@class,'dui-dsummary-card-desc-content-title') and text()='Problem Code ']/following-sibling::div[@class='dui-dsummary-card-desc-content-value']
summaryOccurrencesValue = [xpath]://div[contains(@class,'dui-dsummary-card-desc-content-title') and text()='Occurrences']/following-sibling::div[@class='dui-dsummary-card-desc-content-value']
summaryRepeatedValue = [xpath]://div[contains(@class,'dui-dsummary-card-desc-content-title') and text()='Repeated']/following-sibling::div[@class='dui-dsummary-card-desc-content-value']
summaryDeviceNameValue = [xpath]://div[contains(@class,'dui-dsummary-card-desc-content-title') and text()='Device Name']/following-sibling::div[@class='dui-dsummary-card-desc-content-value']
summaryWarrantyValue = [xpath]://div[contains(@class,'dui-dsummary-card-desc-content-title') and text()='Warranty']/following-sibling::div[@class='dui-dsummary-card-desc-content-value']
summarySerialNumberValue = [xpath]://div[contains(@class,'dui-dsummary-card-desc-content-title') and text()='Serial Number']/following-sibling::div[@class='dui-dsummary-card-desc-content-value']
summaryDeviceOSValue = [xpath]://div[contains(@class,'dui-dsummary-card-desc-content-title') and text()='Device OS']/following-sibling::div[@class='dui-dsummary-card-desc-content-value']

caseIDValue = [xpath]://div[@id='dui-incident-case-id']//div[@class='dui-depr-value']
caseStatusValue = [xpath]://div[@id='dui-incident-case-status']//div[@class='dui-depr-value']
caseSubmissionDateValue = [xpath]://div[@id='dui-incident-case-date']//div[@class='dui-depr-value']
caseContactValue = [xpath]://div[@id='dui-incident-case-contact']//div[@class='dui-depr-value']
selectedIncidentDetailsTitle = [xpath]://div[@class='dui-dsummary-card-title-view dui-dsummary-card-title']
caseLocationValue = [css]:#dui-incident-case-location span

stateDropDownField =[xpath]://input[@name="status"]
caseStatusDropDownField =[xpath]://input[@name="caseStatus"]
progressTab = [xpath]://*[@id="progress"]
incident1 =[xpath]://*[@id="incidents"]/tbody/tr[1]/td[2]//a