HelpAndSupportTab = [id]:help-support-button
NeedassistancewithWEX = [id]:partner-help-and-support-header
emailIcon = [id]:IconEnvelope
emailLabel = [id]:user-email-label
EmailDescription = [xpath]://div[@class='dui-dsummary-card-desc-content-wex-desc']//h6
EmailSupporButton = [xpath]://span[text()='Contact us']
LookingForSomethingTitle = [xpath]://div[@class='partner-section-panel']//h3[@class='dui-margin-bottom-10']
lookingSomethingDescription = [xpath]://div[@class='partner-section-panel']//p[@class='section-description dui-margin-bottom-10']

GettingStartedLabel = [id]:get-started
SoftwareDownloadLabel = [id]:software-download
KnowledgeBaseLabel = [id]:academy
whatsNewTileLabel = [xpath]: //*[@id="whats-new"]
SystemRequirementsLabel = [xpath]://*[@id="system-requirements"]

LegalInformationLabel = [id]:legal-information-text
PrivacyLink = [xpath]://*[@id="legal-link-privacy"]/a
TermsandConditionsLink = [xpath]://*[@id="legal-link-tnc"]/a
ServiceLevelAgreementLink = [xpath]://*[@id="legal-link-sla"]/a
UseofCookiesLink = [xpath]://*[@id="legal-link-useOfCookies"]/a
PrivacyLinkPartner = [xpath] : //a[@href="https://www.hp.com/us-en/privacy/privacy-central.html"]
TermsandConditions =[xpath] : //a[@href="https://usstagingms.workforceexperience.hp.com/terms-and-conditions/en"]
printButton = [id]:printButtton
HpWEXLogo = [id]:hp-wex-logo
HPheaderOn = [id]:tnc-header-1
userProfileIcon = [xpath]://*[@class="profileCard-section"]
SLAHeader= [id]:sla-header
HelpAndSupportHeaderSection = [xpath]://*[@id="customer-section-header"]
HelpAndSupportPartnerSection = [xpath]://*[@class="partner-section-panel"]//h3
HelpAndSupportSendFeedbackTile = [xpath]:(//*[@class="cardCustomized"])[2]
HelpAndSupportFeedbackSubheading = [xpath]://*[@id="wexFeedback-label"]
HelpAndSupportFeedbackDescription = [xpath]://*[@id="wexFeedback-desc"]
HelpAndSupportSendFeedbackBtn = [xpath]://*[@id="wex-send-feedback-support-btn"]

#Email support pop-up
EmailSupportlabel = [css]:.wex-lib-sidebar-title
EmailSupportquestion = [id]:modal-question-text
Myselfradiobutton = [id]:user-option
Anotheruserradiobutton = [id]:other-user-option
Myselflabel: [xpath]://span[text()='Myself']
Anotheruserlabel: [xpath]://span[text()='Another User']
NeedHelpdrdopdowntext= [xpath]://*[@id='select-service']//ancestor::div/label
emailcategorydropdown = [css]:#select-service
categorydropdownlistboxaccount = [xpath]:(//ul[@role='listbox']//li)[1]
categorydropdownlistbox= [xpath]:(//ul[@role='listbox']//li)[13]
categorydropdown = [xpath]://*[@id='select-service']
emaillabel = [id]:user-email-label
emailtextbox= [id]:user-email
Emailsubjectlabel = [id]:email-subject-input-label
supportDropdown = [xpath]://*[@id='support-type']
supportDropdownList = [xpath]://ul[@role='listbox']//li
Emailsubjecttextbox = [xpath]://input[@id='email-subject-input']
Emaildescriptionlabel = [id]:email-desc-label
EmailDescriptiontextarea = [css]:#email-desc
EmailSupportSubmitButton = [id]:submit-hp-email
EmailSupportCancelButton = [id]:cancel-button-text

whatsnewtile = [xpath]://div[@id="whats-new"]//h3//div
wahtsNewTileBelowText = [xpath]://div[@id="whats-new"]//p
mysupporttile = [xpath]://div[@id="my-support-cases"]//h3//div
MysupportTileBelowText = [xpath]://div[@id="my-support-cases"]//p
getsupporttile = [xpath]://div[@id='get-started']//h3//div
getSupporttileBelowText = [xpath]://div[@id='get-started']//p
systemrequirementstile = [xpath]://div[@id="system-requirements"]//h3//div
systemRequirementstileBelowText = [xpath]://div[@id="system-requirements"]//p
knowledgebasetile = [xpath]://div[@id="academy"]//h3//div
knowledgebasetileBelowText = [xpath]://div[@id="academy"]//p
softwaredownload = [xpath]://div[@id="software-download"]//h3//div
softwareDownloadbelowText= [xpath]://div[@id="software-download"]//p
#Toast Notification
toastNotification = [xpath]://*[contains(@id,'toast-title')]
#email for help and support for anaother user
Email_Address_for_Another_User = ateamaddmsp22May23us@hpmsqa.mailinator.com
feedbacktile = [id]:send-feedback
Supportcase=[xpath]: //*[@id="my-support-cases"]
SupportCaseTile= [xpath]: (//*[@id="my-support-cases"]//h3/span[1]//div)[2]