logTab = [xpath]:(//*[@id="logs"])[1]
logs = [xpath]:(//*[@id="logs"])[1]
logsSiteHeader = [xpath]:(//*[@id="logs"])[3]
logTitleOnBreadcrumbs = [xpath]://*[@id="logsList"]//span[@aria-current="page"]
logcolumnsLabelList=[xpath]://*[@id='column-options-label']/..//ul/div//span[contains(@class,'label vn-checkbox__span--text')]
firstCheckbox = [xpath]://tbody//tr[1]//td[1]//div
selectFirstCheckbox = [xpath]:(//tbody//tr[1]//*[contains(@class, 'checkbox')])[1]
expandedLogDesc = [xpath]:(//*[contains(@class,'wex-value-field')]//a)[1]
whatsNewPopupClosedButton= [xpath]: (//button[@aria-label="Close"])[2]
clearFilter = [css]: button[aria-label="Clear Filters"]

selectAllCheckbox = [xpath]:(//*[@id="dui-container"]//label//span)[1]
exportButton = [xpath]://*[contains(@class,'table')]/button[@id='export-device']
exportNotification = [xpath]://div[@role='status']
notificationButton = [xpath]://button[contains(@class,'wex-notification-button')]
hamburgerMenuOnNotification = [css]:#wex-notifications button
notificationButtonforlogs = [xpath]://li[contains(@class,'notification-content')][1]//button
downloadLogsFile = [xpath]://li[contains(@class,'DOWNLOAD FILE')])[6]
listTable = [xpath]:(//*[contains(@class, 'table-container')]//div)[2]
dateAndTimeHeader = [css]:#createdAt

logEntries = [xpath]://div[@id="logDetails"]//span[contains(text(),'Log Entries')]
firtcheckboxEntries = [xpath]:(//tbody//tr[1]//*[contains(@class, 'checkbox')])[1]

resettodefault = [xpath]:(//h4[@id='column-options-label']//following-sibling::div//button)[3]
saveButton = [css]:#column-options-label+div+div button:nth-child(1)
clearFilter = [xpath]://button[@aria-label="Clear Filters"]
tableOverlay = [xpath]://*[@id="logs"]

#type column
typeheader = [xpath]://*[@id="type"]/div/button
typeDropdown = [xpath]://input[@id="type"]
typeListSearch= [xpath]://*[@role="listbox"]/..//input[@placeholder='Search']
typeList = [xpath]://li[contains(@role,'option')]//div/span
logTableTypeColumn = [xpath]://*[@id="logs"]/tbody//td[3]

#subtype column
subtypeheader = [xpath]://*[@id="source"]/div/button
subtypeDropdown = [xpath]://input[@id="source"]
subtypelist = [xpath]://li[contains(@role,'option')]//div/span
subTypeListSearch= [xpath]://*[@role="listbox"]/..//input[@placeholder='Search']
logTableSubTypeColumn = [xpath]://*[@id="logs"]/tbody//td[4]

#level column
levelheader = [xpath]://*[@id="severity"]/div/button
levelDropdown = [xpath]://input[@id="severity"]
levellist = [xpath]://li[contains(@role,'option')]//div/span
levelListSearch= [xpath]://*[@role="listbox"]/..//input[@placeholder='Search']
logTableLevelColumn = [xpath]://*[@id="logs"]/tbody//td[6]/div

#Description column
descriptionHeader = [css]: th#description button
descriptionSearch = [css]: input#description

#row level data
firstRowDateAndTime = [xpath]: ((//table[@id="logs"]/tbody/tr[1])/td[2] //a)[1]
firstRowDescription = [xpath]: (//table[@id="logs"]/tbody/tr[1])/td[5]/div
firstRowType = [xpath]: (//table[@id="logs"]/tbody/tr[1])/td[3]
firstRowSubType = [xpath]: (//table[@id="logs"]/tbody/tr[1])/td[4]
firstRowLevel = [xpath]: (//table[@id="logs"]/tbody/tr[1])/td[6]/div

#Log details
logEntries = [id]:logDetails
loginfo = [xpath]://div[@id='dui-summary-card']
typeinfo = [xpath]:(//div[@class='dui-summary-card-desc-row']/div)[2]
subtypeinfo = [xpath]:(//div[@class='dui-summary-card-desc-row']/div)[4]
levelinfo = [xpath]://div[@id='Information']//div[@class="dui-icon-label"]

#logstab
logstabsnavigation: [id]:logs
logsHeaderDesc = [xpath]:(//div[@class='wex-logs-warn']//div)[4]
previewAndExport = [id]:expandedView_toggle
backButton = [id]:expandedView_back
exportLogsHeader = [xpath]://h4[@id='modal-id-label']
currentSelectionRadioButton = [xpath]://div[@id='modal-id']//input
currentSelectionOfLogs = [xpath]:(//div[@id="modal-id"]//span)[2]
entireListRadioButton = [xpath]:(//div[@id='modal-id']//span)[3]
exportEntireList = [xpath]:(//div[@id="modal-id"]//div)[2]
exportListDesc = [xpath]:(//div[@id="modal-id"]//div)[3]
exportButtonPopup = [xpath]:(//div[contains(@class,'vn-modal--footer')]//button)[1]
cancelButtonPopup = [xpath]:(//div[contains(@class,'vn-modal--footer')]//button)[2]
pageCount = [xpath]://*[@aria-label='Select page size']//following-sibling::span
itemsSelectedLabel = [css]: span.label-small
notification = [xpath]://div[@id='1']/div
notficationTitle = [css]: #wex-notifications #wex-value-id
notificationContent = [css]: #wex-notifications span.vn-notification_item_content
downloadFileButton = [id]:download-file-btn
markAsRead = [id]:mark-notification-as-read-btn
dismiss = [id]:clear-btn