UsersTabOnPartner = [id]:users
AddUserButtonOnPartner = [id]:btn_user_add
addUsersTitle = [id]:add_manually-label
stepInformation = [xpath]://*[@class='add-manually-stepper']
userInformationText = [xpath]://*[@class='add-user-information']
subHeadingAddUser = [xpath]://*[contains(@class,'dui-margin-bottom')]
addAnotherUserBtn = [id]:add_new_user
addUserCancelBtn = [id]:btn_cancel
addUserBackBtn = [id]:btn_prev
addUserNextBtn = [id]:btn_submit
firstNameTextBox = [id]:new_user_first_name_0
lastNameTextBox = [id]:new_user_last_name_0
emailTextBox = [id]:new_user_email_0
idpTypeDropDown = [xpath]://*[contains(@class,'add-manually-frame')]//span
idTypeDropDownList = [xpath]://*[@aria-describedby='add_manually-desc']/following-sibling::div//li
userRoleDropDown = [id]:new_user_role_0
searchInput = [xpath]://*[@aria-describedby='add_manually-desc']/following-sibling::div[2]//input
roleDropDownList = [xpath]://*[@aria-describedby='add_manually-desc']/following-sibling::div[2]//li
roleDropResult = [xpath]://*[@id='new_user_role_0']/span
toastMessage = [xpath]://div[@role='alert']//div/div[2]
emailInput= [name]:email
emailInputValue = [xpath]://tr/td[3]
roleListValue = [xpath]://*[contains(@class,'wex-tag-item')]
userNameValue = [xpath]:(//*[contains(@class,'wex-value-field')]//a)[1]
roleListValues = [xpath]://*[contains(@class,'wex-tag-item')]/div
accountManagementHeader = [xpath]:(//div[contains(@class,'wex-header')]//a)[2]
noItemsAvailable = [xpath]://*[@id='salesTeam']//td//span
tableOverlay=[css]:div[class*='table__overlay--loading']