whatsNewPopupClosedButton= [xpath]: (//button[@aria-label="Close"])[2]
SelectCustomer = [id]:wex_cs_btn_expanded
SelectedCustomer = [xpath]://div[text()='All Customers']
HomeTab= [id]:menu_home
CustomersTab = [id]:menu_companies
AccountManagementTab = [id]:menu_accountManagement
CertificationsTab= [id]:certifications


CertificationsCard1= [xpath]:(//*[@id="extended-certifications"]//div[@class='feature-card-small'])[1]
CertificationsCard2=[xpath]:(//*[@id="extended-certifications"]//div[@class='feature-card-small'])[2]
CertificationsCard3=[xpath]:(//*[@id="extended-certifications"]//div[@class='feature-card-small'])[3]
CertificationsCard4=[xpath]:(//*[@id="extended-certifications"]//div[@class='feature-card-small'])[4]
HPLearningTile= [xpath]: //*[@id="default-tile"]//div[@class="footer-desc-title"]
ClearFilterButton= [xpath]: //button[@aria-label='Clear Filters']
EmailSerchBox= [xpath]: (//*[@id="email"])[2]
USPartner= [xpath]: (//*[@id="uswexautomationstagepartnerwithnodata"])[1]
EUPartner= [xpath]: (//*[@id="euwexautomationstagepartnerwithnodata"])[1]
CertificationsRoot= [xpath]: //*[@id="certifications"]/div
Toggle2=[id]:certification-hpAnyware-toggle
Toggle3= [id]:certification-hpSupportManage-toggle
Toggle4= [id]:certification-hpSupportManagerDeliver-toggle
Toggle5= [id]:certification-hpWpt-toggle
CertifiedTitle1= [xpath]: (//div[@id='extended-certifications']//div[2])[1]
CertifiedTitle2= [xpath]: (//div[@id='extended-certifications']//div[2])[4]
CertifiedTitle3= [xpath]: (//div[@id='extended-certifications']//div[2])[6]
CertifiedTitle4= [xpath]: (//div[@id='extended-certifications']//div[2])[8]
DisableCertificate=[xpath]://*[@id="confirm-remove-hpSupportManage-modal-label"]
DisableCertificateDescription=[xpath]://*[@id="security-confirmation-description"]
SecurityCodeCertificate=[xpath]://*[@id="security-code-number"]
securitycodecertificateinput=[xpath]://*[@id="security-code"]
cancelbuttoncertificate=[xpath]://*[@id="confirm-remove-hpSupportManage"]
DisableCertificateMonitorToggle=[id]:confirm-remove-hpSupportManage-modal-label
DisableCertificateDeliverToggle=[id]:confirm-remove-hpSupportManagerDeliver-modal-label
DisableCertificateDescriptionDeliverToggle=[id]:security-confirmation-description
deleteButtonCertificateToggleManage=[xpath]://*[@id="confirm-remove-hpSupportManage"]
deleteButtonCertificateToggleDeliver=[xpath]://*[@id="confirm-remove-hpSupportManagerDeliver"]
securitycodecertificateinputdelivertoggle=[xpath]://*[@id="security-code"]