nameEdit = [xpath]:(//*[@id='namePanel']//div)[6]
roleEdit = [xpath]://*[@id='dui-accountAndRoles']//button
editLastName = [name]:edit_modal_lastName
saveButtonUserName = [id]:editSaveBtn
cancelButtonUserName = [id]:editCancelBtn
roleSearch = [id]:search
roleResultCheckBox = [xpath]://*[contains(@class,'roles-list')]//span[1]
rolesSaveBtn = [id]:rolesSaveBtn
rolesCancelBtn = [id]:rolesCancelBtn
toastMessageonUserRole = [xpath]://div[@role='alert']//div/div
nameUpdatedValue = [xpath]://*[@id='namePanel']//span/div
roleUpdatedValue  = [xpath]://*[@id='dui-accountAndRoles']//span/div