SelectCustomer = [id]:wex_cs_btn_expanded
SelectedCustomer = [xpath]://div[text()='All Customers']
whatsNewPopupClosedButton= [xpath]: (//button[@aria-label="Close"])[2]

# Catalog
CatalogTab= [id]:wex_horizontal_menu_catalogs
customeronlist=[xpath]://div[@class="wex-company-list-item-title"]
addCatalogButton=[id]:add-catalog-btn
addCatalogButtonText=[xpath]://*[@id="add-catalog-btn"]/span
addTitle= [xpath]:/html/body/div[23]/div/div/h4
downloadCatalogSample = [id]:download-sample
dropDownOpen = [id]:add_asset_select_company
dropDownOpen1 = [xpath]://*[@id='add_asset_select_company']/parent::div
companySearch = [xpath]://*[@id="add_asset_select_company-listbox"]/preceding-sibling::div/input
selectCompany = [css]:li[id=add_asset_select_company-option-0]
selectCompany2 = [css]:li[id=add_asset_select_company-option-1]
importButton = [id]:global_import_button
notificationBellIcon = [xpath]://*[@id="products"]/header/div[2]/div/div[1]/div/button
unreadNotificationText = [css]:#dui-notifications li:first-child div:nth-child(2) span:first-child
browseButton = [id]:asset_file
browseInput= [xpath]: //input[@id="asset_file"]
addCatalogTitle = [id]:catalog_add_title-label
addCatalogSubtitle = [id]:add_update_catalog_download
sampleCatalogFile = [id]:download-sample
importCatalogClosedButton = [xpath]://*[@id="catalog_add_title-label"]/parent::div/button
importCatalogCancelButton = [id]:global_cancel_button
ImportToastNotification= [xpath]://div[contains(text(),'Import is in progress.')]
bellNotification1 = [xpath]://*[@id="dui-notifications"]/preceding-sibling::button
bellNotification = [id]:notification-center-button
setAsDefaultCheckBox = [id]:set_as_default
setAsDefaultCheckBoxLabel = [xpath]://*[@id="set_as_default"]/following-sibling::span[2]
importedCatalogNotificationTitle = [xpath]:(//li[@tenantid="TenantId"]//div[@id="wex-value-id"])[1]
importedCatalogNotificationMessage = [xpath]:(//li[@tenantid="TenantId"]//span)[2]
importedCatalogNotificationDate =  [xpath]://li[@tenantid="TenantId"]//span//div[2]
notificationHambergerButton =  [xpath]://li[@tenantid="TenantId"]//button
catalogNotification = [xpath]://li[@tenantid="TenantId"]
clearNotificationButton = [id]:clear-btn
markAllAsReadButton = [id]:mark-notification-as-read-btn
openLogsButton = [id]:open-logs-btn
catalogList = [id]:wex-catalogs-list-item-title-catalog
catalogFirstCompany = [xpath]:((//*[@id="wex-catalogs-list-tag-container-catalog"])[ind]//div[@class="wex-tag-content"])[1]
catalogSecondCompany = [xpath]:((//*[@id="wex-catalogs-list-tag-container-catalog"])[ind]//div[@class="wex-tag-content"])[2]
catalogProductCount = [xpath]:(//*[@id="wex-catalogs-list-tag-container-catalog"]/parent::div/following-sibling::div[1])[ind]
catalogUpdatedOn = [xpath]:(//*[@id="updated-on"])[ind]
catalogType = [xpath]:(//*[@id="updated-on"])[ind]/parent::div/following-sibling::div/div/div[2]
catalogThreeDotButton = [xpath]:(//*[@class="wex-list-default wex-list-item-container"]//button)[ind]
catalogDeleteButtonList = [xpath]://*[@id="delete-catalog-btn"]//button
deleteCatalogTitle = [id]:Delete Product Catalogs-label
deleteCatalogMessage = [xpath]://*[@class="modal-contant del-catalog-modal"]
deleteCatalogButton = [id]:dui-confirm-save
deleteCatalogCancelButton = [id]:dui-confirm-cancel
deleteCatalogClosedButton = [xpath]://*[@id="Delete Product Catalogs-label"]/parent::div/button
deleteCatalogtoastNotification= [xpath]://div[contains(text(),'Catalogs deleted successfully')]
removeCatalogButton = [xpath]://*[@id="dui-container"]//button[@label="Remove"]

# Customer Page
customers = [id]:menu_companies
invite = [xpath]://*[@id="btn_company_invite"]
sendInviteTitle = [id]:modal_company_invite-label
sendInviteSubtitle = [xpath]://*[@id="modal_company_invite"]//p
customerIdLabel = [id]:customer-id-input-label
buttonInvite = [id]:btn_invite
sendInviteCancelButton = [xpath]:(//*[@id="btn_cancel"])
invitePopupCloseButton = [xpath]://*[@id="modal_company_invite-label"]/parent::div/button
addCustomer = [xpath]://*[@id="btn_company_add"]
activeCheckbox = [xpath]://input[@id='checkbox']/../span
companyName= [xpath]://input[@id='company-name']
addressLine= [xpath]://input[@name='address']
nextButton= [id]:btn_next
city= [xpath]://input[@placeholder='City']
state= [xpath]://input[@placeholder='State/Province']
zipCode= [xpath]://input[@placeholder='2586']

firstname= [xpath]://input[@placeholder="Enter first name"]
emailAddress= [xpath]://*[@id="email"]
lastname= [xpath]://input[@placeholder='Enter last name']
selectIdp= [id]:idp-dropdown
idpList= [css]:#idp-dropdown-listbox>li
selectPlan= [xpath]://*[@placeholder="Choose a Plan"]
proTrialPlanOption= [xpath]://li[@data-value="workforce_experience_pro_trial"]
planList= [xpath]://ul[contains(@id, 'listbox')]/li
addButton= [id]:btn_create
tenantTitle= [xpath]: //*[contains(@class,'card-title')]
selectidpvalue = [xpath] : //div[@class="css-hyqgz1"]/ul[contains(@id,'listbox')]/li
emailId=[xpath] ://*[@id="emailPanel"]/div[1]
emailIdValue=[xpath] ://div[starts-with(@id, 'autoinvitecustomer')]
emailIdValueNew=[xpath] ://div[starts-with(@id, 'autocustomerdnd')]
companyProfile= [id]:company-profile-header
addCustomerTitle = [id]:modal_company_info-label
addCustomerSubtitle = [id]:add-customer-subtitle
addCustomerStep1 = [id]:customer-add-popup-step1
addCustomerPopupDescription = [id]:customer-add-popup-desc
companyNameLabel = [id]:company-name-label
addressLine1Label = [id]:address-line-1-label
addressLine2Label = [id]:address-line-2-label
cityLabel = [id]:city-label
stateLabel = [id]:region-label
zipCodeLabel = [id]:zipcode-label
countryLabel = [id]:company-country-label
cancelPopupButton = [xpath]://*[@id="btn_next"]/preceding-sibling::button
addCustomerStep2Subtitle = [id]:add-customer-subtitle
addCustomerStep2 = [id]:customer-add-popup-step2
addCustomerStep2Description = [id]:customer-add-popup-itadmin-desc
firstNameLabel = [id]:first-name-label
lastNameLabel = [id]:last-name-label
emailLabel = [id]:email-label
phoneLabel = [id]:phone-number-label
idpLabel = [id]:idp-dropdown-label
backButton = [id]:btn_prev

activeStatus = [xpath]://div[text()='Active']
pendingStatus = [xpath]://div[text()='Pending invite']
deleteBtn = [id]:delete-tenant-btn
compName = [xpath]://div[@class="dui-dsummary-card-title"][3]
confirmDeleteComp = [id]:dui-confirm-save
cancelDeleteComp = [id]:dui-confirm-cancel
deleteConfirmToast = [xpath]://*[@id="dui-app-scroll"]/div[3]/div/div/div
deleteConfirmToasts = [xpath]://*[@id="dui-app-scroll"]/div[3]//div[2]
overview= [xpath]://*[@id="overview"]
invitationSuccessToast = [xpath]://*[@id="dui-app-scroll"]/div[3]/div
customerID = [xpath]://*[@id="display-id"]//span/div
companyValue = [xpath]://*[@id="company-name"]//span/div
assignPartner = [xpath]://*[@id="assigned-partner"]
InvitesTab =[id]:invites
searchItem =[id]:customerName-search
searchCompany =[xpath]://input[@placeholder="Search Items"]
valueCompany =[xpath]://*[@id="select-multiple-usage-option-0"]
editCompany =[xpath]://*[@id="edit-company-name"]
editCompanyValue =[xpath]://*[@id="dui-text-modal-text-box"]
cancel =[xpath]://*[@id="dui-text-modal-cancel"]
clear =[xpath]://*[@id="default-tile"]//button/span
noDataToDisplay =[xpath]://div[@class="state-title"]

timezoneSelectBox= [xpath]://*[@id="dui-company-timezone-select-box"]
primaryadministratorselectbox = [xpath]://*[@id="dui-company-owner-modal-select-box"]


filterCompany =[xpath]://*[@id="default-tile"]/div//div[1]//div[2]
clearCompany =[xpath]:(//*[@id="default-tile"]//div[1]/div[2])[2]
optionChoice =[xpath]://*[@class="contextualMenuIcon"]/button
resendInvite =[xpath]:(//*[@id="wex_menu_item_1"])[1]
deleteInvite =[xpath]://button[@id='wex-menu-list-item' and contains(@class, 'customer-list-delete')]
viewCustomerProfile =[id]:wex_menu_item_view_customer_profile
viewCustomerDashboad =[xpath]:(//*[@id="wex_menu_item_1"])[1]
deleteCustomer =[xpath]:(//*[@id="wex_menu_item_2"])[2]

invitePartner = [xpath]://*[@id="company-partner-row"]//*[local-name()='svg' and @name='IconPlus']
searchPartner = [id]:assignment-partner-select-box
searchPartnerDropdown = [xpath]://input[@placeholder="Search"]
valuePartner = [xpath]://ul[@role='listbox']/li
submitInvitePartner = [xpath]://*[@id="assignment-partner-submit"]
listDropdown = [xpath]://ul[@role='listbox']/li
pendingRequestStatus = [xpath]://div[contains(text(),'Pending request')]
declineCustomer = [id]:wex_menu_item_decline_request
acceptRequest = [xpath]://*[contains(@class,'wex-menu-item customer-list-accept-request')]
confirmAcceptRequest = [id]:dui-confirm-save
clickPending=[xpath]://span[contains(text(),'Pending')]/../span
totalInvitedCustomer = [id]:test-invite-comp-selenium-auto
oldInvitedCustomer = [id]:test-comp-selenium-auto
oldInvitedCustomer1 = [id]:uiautomationinviteita-donotdeletetestusstage
pendingCustomerPopupDescription = [xpath]://*[@id="Delete Invitation"]//p
activeCustomerPopupDescription =  [xpath]://*[@id="Remove customer?"]//div[contains(@class,'confirmation-content')]

HPID= [xpath]://*[@data-value="HPID"]

#Home tab
home = [id]:menu_home
invitesTab = [id]:invites
inviteSearchBox = [id]:customerName-search
inviteSearchElement = [xpath]://*[@id="customer-list-tabs-invites"]//tbody/tr
threeDotElementInvites =  [xpath]://*[@id="invite-company-list-table"]//tbody/tr/td[4]/button
customersSearchElement = [xpath]://*[@id="customer-list-tabs-customers"]//tbody/tr
threeDotElementCustomers = [xpath]://*[@id="customer-list-tabs-customers"]//tbody/tr/td[7]/button
activeStatusNew = [xpath]:(//*[@id="customer-list-tabs-customers"]//tbody/tr/td[3]/div/div)[2]
viewProfile = [id]:wex_menu_item_view_customer_profile
navToDashboard = [id]:wex_menu_item_view_customer_dashboard
updateLocation = [id]:wex_menu_item_update_location
removeCustomer = [xpath]://*[contains(@class,'wex-menu-item customer-list-delete-customer')]
customersTab = [xpath]://div[@aria-controls='customer-list-tabs-customers']
toastNotification = [xpath]://*[contains(@id,"toast-title")]

unassignedDevicesSiteHeader = [xpath]:(//span[contains(text(),'Unassigned Devices')])[2]

