systemRequirement=[xpath]://*[@id="dui__software_container"]/div/a                      
androidApplication = [id]:list-item-label-andriod
macApplication = [id]:list-item-label-mac
windowsApplication = [id]:list-item-label-windows
networkReadinessTool = [id]:list-item-label-assessment_tools
wolfConnect = [id]:list-item-label-admincentral
downloadButtonMac = [id]:download-button-mac
downloadButtonWindows = [id]:download-button-windows
downloadButtonAssessmentTools = [id]:download-button-assessment_tools
downloadButtonWolfConnect = [id]:download-button-admincentral