#Subscription

subscriptionTab = //*[@id="subscription"]/div
currentPlan = //*[@id="current-plan"]
currentPlanName = //*[@id="current-plan-name"]
usedSeats = //*[@id="seats-used"]
planStatus = //*[@id="plan-status"]

subscriptionMgmt = //*[@id="subscription-mgt"]
subscriptionMgmtTitle = //*[@id="subscription-mgt-title"]
subscriptionMgmtsubTitle = //*[@id="subscription-mgt-subtitle"]
gotoAwsMarketplace = //*[@id="go-to-aws-marketplace"]
futurewexOfferings = //*[@id="extended-subscription"]//div[3]
basicPlan = //*[contains(@class,"dui basic-plan-card-padding")]
proPlan = //*[contains(@class,"dui pro-plan-card-padding")]
enterprisePlan = //*[contains(@class,"dui pro-plan-card-padding")]//*[@id="plan-enterprise"]

