# Get Started Screen
getStartedHeading = [xpath]://div/h3
signUpSubHeading = [xpath]://div/h3/following-sibling::p
companyFullNameLabel = [id]:companyName-label
companyFullNameInput = [id]:companyName
countryLabel = [id]:country-label
countryDropDown = [xpath]://*[@id='country']
countryInput = [css]:[role='presentation'] input
countryValues = [css]:[role='presentation'] ul li
emailLabel = [id]:email-label
emailInput = [id]:email
signInWithText = [xpath]://*[text()='Sign in with']
microsoftRadioButton = [id]:radio-aad
microsoftRadioButtonText = [xpath]://*[@id='radio-aad']/../following-sibling::span
hpidRadioButton = [id]:radio-hpid
hpidRadioButtonText = [xpath]://*[@id='radio-hpid']/../following-sibling::span
termsConditionCheckBox = [xpath]://*[contains(@class,'checkbox-get-started')]//input
termsConditionText = [xpath]://span[contains(@class,'createCompany-termsText')]
cancelButton = [xpath]://button/*[contains(text(),'Cancel')]
nextButton = [xpath]://button/*[contains(text(),'Next')]

# Account Linked Screen
accountLinkedHeading = [xpath]://*[contains(@class,'dui-adminx-accountLinked')]//h5
accountLinkedSubHeading = [xpath]://*[contains(@class,'dui-adminx-accountLinked')]//p
signOutButton = [xpath]://button/*[contains(text(),'Sign out')]
createButton = [xpath]://button/*[contains(text(),'Create')]

firstName = [xpath]://*[@id='name']
lastName = [xpath]://*[@id='lastName']
companyName = [xpath]://*[@id='companyName']
emailAddress = [xpath]://*[@id='emailId']
phoneNumber= [xpath]://*[@id='phoneNumber']
timeZone= [xpath]://*[@id='timeZone']
companySize= [xpath]://*[@id='companySize']
companySizelistvalues = [css]:[role='presentation'] ul li
country = [xpath]://*[@id='country']
address1 = [xpath]://*[@id='street']
address2 = [xpath]://*[@id="street1"]
city = [xpath]:(//*[@id='zipCode-label']/parent::div/../..//label/following-sibling::div/input)[1]
zipcode = [xpath]://*[@id='zipCode-label']/following-sibling::div/input
state = [xpath]://*[@id='state-label']/following-sibling::div/input
timeZoneDropDown = [css]:#timeZone-listbox>li[id*='timeZone-option']:first-child
nextBtn_accountLink = [xpath]://button/span[text()='Next']
signoutBtn_accountLink = [xpath]://button/span[text()='Sign out']
tncCheckBox = [xpath]://label/span[contains(@class,'checkbox')]/input
countryValueText = [xpath]://*[@id='country']//span

companyLoadingMsgHeading = [xpath]://*[@id='modal-id-desc']//h5
companyLoadingMsgText = [xpath]://*[@id='modal-id-desc']//p

companyCreateSucc = [xpath]://*[@class='dui-app-adminx-companySuccess']//h5
companyCreateSuccText = [xpath]://*[@class='dui-app-adminx-companySuccess']//p
companyCreateSuccNextBtn = [xpath]://*[@class='dui-app-adminx-companySuccess']//button

inviteUsersHeading = [xpath]://div[contains(@class,'adminx-createCompany')]//h5
inviteUsersText = [xpath]: (//*[contains(@class,'adminx-createCompany')]//p)[1]
firstNameText = [xpath]:(//div[contains(@class,'createCompany-addUser')]//label)[1]
lastNameText = [xpath]:(//div[contains(@class,'createCompany-addUser')]//label)[2]
emailText = [xpath]:(//div[contains(@class,'createCompany-addUser')]//label)[3]
firstNameOnUsersPage = [xpath]:(//div[contains(@class,'createCompany-addUser')]//input)[1]
lastNameOnUsersPage = [xpath]:(//div[contains(@class,'createCompany-addUser')]//input)[2]
emailOnUsersPage = [xpath]:(//div[contains(@class,'createCompany-addUser')]//input)[3]
editRoleIcon = [xpath]:(//div[contains(@class,'adminx-createCompany')]//button)[2]
noneAssignedText = [xpath]:(//div[contains(@class,'dui-admix-roles')]//span)[1]
rolesText = [xpath]:(//*[contains(@class,'adminx-createCompany')]//p)[2]
selectRoleDropDown = [xpath]://*[@id='select-multiple-usage']
roleDropDownList = [xpath]://ul[@id='select-multiple-usage-listbox']/li
doneButton = [xpath]:(//div[contains(@class,'modal--footer')]//button)[1]
cancelBtn = [xpath]:(//div[contains(@class,'modal--footer')]//button)[2]
deleteButton = [xpath]:(//div[contains(@class,'createCompany')])[4]//button
addAnotherUser = [xpath]:(//div[contains(@class,'adminx-createCompany')]//button)[3]
skipButton = [xpath]:(//div[contains(@class,'adminx-createCompany')]//button)[4]
nextBtn = [xpath]:(//div[contains(@class,'adminx-createCompany')]//button)[5]
selectidpType = [xpath]://*[@id='select']
idpTypeValues = [xpath]://*[@id='select-listbox']/li
assignRoles = [xpath]://*[contains(@class,'assign-roles')]//h4
roledropdownoption = [xpath]://*[@id='select-multiple-usage-listbox']/..//input

CustomizedHeading = [xpath]://*[@id='adminx_onboarding']//h5
customizedText = [xpath]:(//div[contains(@class,'adminx-previewInvite')]//p)[2]
optionalMessageHeading = [xpath]://*[@id='adminx_onboarding']//h5//following-sibling::p
subject = [xpath]:(//*[@id='subject-section']/p)[1]
toEmail = [xpath]:(//*[@id='subject-section']/p)[2]
sampleText = [xpath]://*[@id='create-invite']
characterLimit = [xpath]://*[@id='create-invite-helper-text']//span[2]
helperText = [xpath]://*[contains(@class,'adminx-previewInvite')]//p[3]
signInButton = [xpath]://*[contains(@class,'sign-in-button')]/span
helloText = [xpath]://*[contains(@class,'adminx-previewInvite')]//p
inviteText = [xpath]://*[contains(@class,'adminx-previewInvite')]//p[2]
signInLink = [xpath]://*[contains(@class,'sign-in-button')]/../following-sibling::div
backBtnEmail = [xpath]:(//*[contains(@class,'button-group')]//button/span)[2]
skipBtnEmail = [xpath]:(//*[contains(@class,'button-group')]//button/span)[3]
sendBtnEmail = [xpath]:(//*[contains(@class,'button-group')]//button/span)[4]
thankYou = [xpath]://*[contains(@class,'adminx-previewInvite')]//p[4]
wexTeam = [xpath]://*[contains(@class,'adminx-previewInvite')]//p[5]

emailSentMessage = [xpath]://div[contains(@class,'adminx-sendInvite')]//h5
emailSentText = [xpath]://div[contains(@class,'adminx-sendInvite')]//p
logoutBtn_emailsend = [xpath]:(//div[contains(@class,'adminx-sendInvite')]//button)[1]
nextBtn_emailsend = [xpath]:(//div[contains(@class,'adminx-sendInvite')]//button)[2]

welcomeToWFheading = [xpath]://div[@id='welcome_adminx-desc']//h4
welcomeToWFtext = [xpath]://div[@id='welcome_adminx-desc']//p
getStartedBtn = [xpath]://div[@class='adminx-intro-footer']//button
closeBtn = [xpath]://button[contains(@class,'modal__close')]