#Company Setting information

companyname = [xpath]://div[@class='css-tfliml']
PreferredTimeZone = [xpath]://span[@title='Preferred Time Zone']
PrimaryAdministrator = [xpath]://span[@title='Primary Administrator']
PrimaryAdministratorEmail = [xpath]://span[@title='Primary Administrator Email']
PrimaryContactNumber = [xpath]://span[@title='Primary Contact Number']
SettingLogo = [xpath]://div[@class ='avatar profile-tile']
SettingCompanyStatus = [id]:company-status


#Shipping location

Shippinglocationtab = [id]:locations
Shippinglocationheader = [id]:shipping-locations
shippingLocationTileTitle = [css]:#dui-locations [class*=panel-header]
shippinglocationaddbutton = [id]:add-location
addLocationPopupTitle = [xpath]://div[@class="dui-add-location-modal"]//ancestor::div[@role="presentation"]//h4
addLocationPopupSubtitle = [css]:div[class*=add-location] h5
countryLabel = [css]:#country-label
addressLine1Label = [xpath]://label[@id="address-line-1-label"]
addressLine2Label = [xpath]://label[@id="address-line-2-label"]
cityLabel = [xpath]://label[@id="city-label"]
stateLabel = [xpath]://label[@id="region-label"]
zipcodeLabel = [xpath]://label[@id="zip-code-label"]
countryDropdown = [xpath]://input[@id="country"]
countryOptions = [xpath]://ul[@role="listbox"]/li
addressLine1Textbox = [css]:[name=addressLine1]
addressLine2Textbox = [css]:[name=addressLine2]
cityTextbox = [css]:[name=city]
stateTextbox = [css]:[name=province]
zipcodeTextbox = [css]:[name=zipcode]
nextLocationButton = [css]:div[class*=new-location-buttons] button:nth-child(1)
cancelLocationButton = [css]:div[class*=new-location-buttons] button:nth-child(2)
countryErrorMessage = [xpath]://*[@id="country-helper-text"]/span[2]
addressLine1ErrorMessage = [xpath]://*[@id="address-line-1-helper-text"]/span[2]
cityErrorMessage = [xpath]://*[@id="city-helper-text"]/span[2]
stateErrorMessage = [xpath]://*[@id="region-helper-text"]/span[2]
zipcodeErrorMessage = [xpath]://*[@id="zip-code-helper-text"]/span[2]
firstNameLabel = [xpath]://label[@id="first-name-label"]
lastNameLabel = [xpath]://label[@id="last-name-label"]
emailLabel = [xpath]://label[@id="email-id-label"]
phoneNumberLabel = [xpath]://label[@id="phone-number-label"]
firstNameTextbox = [css]:[name=firstName]
lastNameTextbox = [css]:[name=lastName]
emailTextbox = [css]:[name=email]
phoneTextbox = [css]:[name=phone]
deliveryInstructionsLabel = [xpath]://label[@id="delivery-instructions-label"]
instructionsTextbox = [css]:[name=instructions]
setDefaultLabel= [css]:[class*=new-location-second] [class*=span--text]
previousLocationButton = [css]:div[class*=new-location-buttons] button:nth-of-type(1)
addLocationButton = [css]:div[class*=new-location-buttons] button:nth-of-type(2)
cancelLocationButton = [css]:div[class*=new-location-buttons] button:nth-of-type(3)
firstNameErrorMessage = [xpath]://*[@id="first-name-helper-text"]/span[2]
lastNameErrorMessage = [xpath]://*[@id="last-name-helper-text"]/span[2]
emailErrorMessage = [xpath]://*[@id="email-id-helper-text"]/span[2]
phoneErrorMessage = [xpath]://*[@id="phone-number-helper-text"]/span[2]
#addressSearchBox = [id]:location-address-search
addressSearchBox = [id]:search-address
removeLocationButton = [id]:remove-location
removeLocationTitle = [css]:div[aria-hidden="false"] h4[class*="vn-modal--title"]
removeLocationSubtitle = [css]:div[aria-hidden="false"] div[class*="dui-remove-location-warn"]
removeLocationPopupButton = [css]:div[aria-hidden="false"] div[class="vn-button-group--horizontal"]>button:nth-of-type(1)
removeLocationPopupCancelButton = [css]:div[aria-hidden="false"] div[class="vn-button-group--horizontal"]>button:nth-of-type(2)
locationTableHeaders = [css]:thead tr:first-child th button
hamburger = [css]:tbody tr:first-child td:last-child button
setAsDefaultActionOnHamburger = [xpath]://ul/div[@id="wex_menu_item_setAsDefault"]/li/button[@role='menuitem']
defaultLocationPopupTitle = [xpath]:((//div[@role='presentation'])//h4)
defaultLocationPopupSubtitle = [css]:div[class*=default-location-warn]
cancelSetToDefaultButton = [xpath]:(//div[@role='presentation'])[17]//button[2]
setToDefaultButton = [css]:div[aria-hidden="false"] div[class*=vn-button-group--horizontal] button:nth-of-type(1)
defaultTag = [css]:span[class*=default-location]
successAddShipLocation = [xpath]://div[@role="status"]/div
noItemsAvailable = [xpath]://*[@id="dui-container"]//table/tbody/tr/td/div/span
firstCheckBox = [css]:tbody>tr:nth-of-type(1) span input


#Preferences:

Preferencestab = [id]:preferences
perferencestaboldmenu = [id]:company-preferences

#Archive devices:
ArchivedDevicesheader = [id]:archived-devices
ArchivedDevicessubheader = [id]:archived-devices-subheading
archivedevicesubtitle = [id]:archive-device-subtitle
archivedeviceeditbutton = [id]:edit-archive-device
Archivedevicespopheader = [id]:dui-archived-devices-label
Archivedevicespopupselectbox = [id]:dui-archived-devices-select-box
Archivedevicespopupselectboxlabel= [id]:dui-archived-devices-select-box-label
Archivedevicespopupselectboxvalue =[xpath]://li[@role='option' and @data-value='60 Days']
Archivedevicespopupsavebutton = [id]:dui-archived-devices-submit
Archivedevicespopupcancelbutton = [id]:dui-archived-devices-cancel
Archvieddevicetoastenotification = [xpath]://div[@class='css-v02i7i']

#Authentication:
Authenticationsection = [xpath]://span[text() ='Authentication']
Authenticationheader = [id]:authentication
Authenticationsubheader = [id]:auth-sub-heading
Authenticationeditbutton = [id]:edit-authentication

Authenticationheaderpopup = [id]:Authentication-label
Authenticationsubheaderpopup = [id]:Authentication-desc
Authenticationselectboxlabel = [id]:Authentication-select-box-label
Authenticationselectbox = [id]:Authentication-select-box
Authenticationsubmitbutton = [id]:Authentication-submit
Authenticationcancelbutton = [id]:Authentication-cancel

#Company PIN
companypinsection = [xpath]://span[text() ='Company PIN']
companypinheader = [id]:company-pin
companypinsubheader = [id]:company-pin-subheading
companypinrowvalidation = [id]:company-wide-pin-row
companydeletepinicon = [id]:delete-company-pin
companyeditpinicon = [id]:edit-company-pin


#Fleet Score Preferences
fleetscorepreferencessection = [xpath]://span[text() ='Experience Score Preferences']
fleetscorepreferencesheader = [id]:experience-score-preferences
fleetscorepreferencesdescription = [id]:fleet-score-preferences-description


#Device Groups
Devicegroupssection = [xpath]://span[text() ='Device Groups']
Devicegroupheader = [id]:device-groups
switchtomultilevelbutton = [id]:button.multilevelCompany
companylocatiorow = [id]:company-locations-row

#Custom fields for devices
customefieldsfordevicessection = [xpath]://span[text() ='Custom Fields for Devices']
customfieldsheader = [id]:custom-fields-for-devices
customfieldssubheader = [id]:custom-fields-for-devices-subheading
customefieldsvalidation = [id]:custom-fields-row


#Lifecycle status
lifecyclesection = [xpath]://span[text() ='Lifecycle Status']
lifecycleheader = [id]:lifecycle-status
lifecyclerow = [id]:lifecycle-fields-row


#data collection
datacollectionsection = [xpath]://span[text() ='Data Collection']
datacollectionheader = [id]:data-collection
datacollectionsubheading = [id]:data-collection-subheading
companyfirwallrow = [id]:company-firewall-row
BlueScreenCrashDumpsrowm = [id]:win-client-upload-config
devicehealthrow = [id]:company-device-health-row
devicelogsrow = [id]:logs-collection-device-logs
companylocation = [id]:company-location-row
networkidentifire = [id]:company-network-identifiers-row
softwareinventory = [id]:company-software-inventory-row
userprofileinformation = [id]:company-user-personal-info-row
webapplicationusage = [id]:web-application-usage


#domain name
domainnamesection = [xpath]://span[text() ='Domain Name']
domainnameheader = [id]:domain-name
domainnamesubheader = [id]:domain-name-subheading
domainnamerow = [id]:company-domains-row


#company network
companynetworksection = [xpath]://span[text() ='Company Networks']
companynetworkheader = [id]:company-networks
companynetworksubheader = [id]:company-networks-subheading
companynetworkrow = [id]:company-product-catalog-row


#Third Party Software Integration
ThirdPartysoftwareIntegrationsection = [xpath]://span[text() ='Third Party Software Integration']
thirdpartysoftwareintegrationsection = [id]:third-party-software-integration
chromebookrow = [id]:chrome-book-row
companytunerow = [id]:company-intune-rest-api-row
servicenowrow = [id]:company-service-now-row
companyairwatchrow = [id]:company-airwatch-rest-api-row



#Roles And Permission
rolesandpermissiontab = [id]:company-roles
rolesheader = [id]:roles
addrolebutton = [id]:btn_role_add


#Assigned partner

assignedpartnertab = [xpath]://div[@id="assigned-partner"]
assignmentsettingheader = [id]:assignment-settings
companypartnerrow = [xpath]://div[@id="company-partner-row "]
invitationsection = [xpath]://span[text() ='Invitations']
invitatiossectionheader = [id]:invitations

#Notification
Notificationtab = [id]:notifications
devicenotificationheader = [id]:device-notifications
deviceNotificationHeader = [xpath]: //*[@id="device-notifications" and @class='dui-dpanel-header']
devicenotificationsubheader = [id]:device-notifications-subheading
serviclocationlabel = [id]:service-location-label
selfServiceAlertsToggleInput = [xpath]: //div[@id="device-self-service-alerts"]//input
selfServiceAlertsToggle = [css]: #device-self-service-alerts span[aria-hidden="true"]
selfServiceAlertsHeader =[css]:#self-service-alerts div[class*=dui-dpanel-topView]
selfServiceAlertsLabel = [css]:#device-self-service-alerts div[class*=label]
revertAllAlertsToDefaultButton =[xpath]://button[@id="reset-to-default"]

#Hardware Health List :
hardwareHealth=[xpath]: //span[@id='hw_health']
batteryNeedsAttention : [xpath]: //div[@id='dui_self_service_hw_health_battery_needs_attention']
biosOutOfDate =[xpath]: //*[@id="dui_self_service_hw_health_company_wide_bios_outofdate"]
fanWarning = [xpath] ://*[@id="dui_self_service_hw_health_fan_warning"]
hddPredictiveFailure = [xpath] ://div[@id='dui_self_service_hw_health_hdd_predictive_failure']
systemErrorThermal=[xpath] ://*[@id="dui_self_service_hw_health_system_error_thermal"]

#ActiveCareList
activeCareDropDown =[xpath]://span[@id='manually_created']
battery:[xpath]://div[@id='dui_self_service_activecare_battery']
hdd :[xpath]://div[@id='dui_self_service_activecare_hdd']
ioDevice :[xpath]://div[@id='dui_self_service_activecare_io_device']
motherBoard:[xpath]: //div[@id='dui_self_service_activecare_motherboard']
other:[xpath]://div[@id='dui_self_service_activecare_other']
power:[xpath]://div[@id='dui_self_service_activecare_power']
#batteryEditToggleButton= [css]:#edit_battery_needs_attention
batteryEditToggleButton = [css]:#dui_self_service_hw_health_battery_needs_attention .dui-icon-button svg
customFieldsPopupTitle = [css]:#self-service-modal-label
enableAlertButton = [xpath] ://input[@id='enable-alert-toggle']
customFieldsSave = [xpath]://*[@id="save-alert"]
hardwareList = [xpath]: //div[@id='dui_self_service_hw_health']
selfServiceAlertSubtypeSpecificStatus = [xpath]://div[@id='dui_self_service_hw_health']//span
selfServiceAlertSubtypeStatus = [css]:div[id*='dui_self_service'] span.dui-hyphenate.dui-panel-title
hardwareHealthCategoriesTitle = [xpath] ://*[@id='dui_self_service_hw_health']//*[contains(@class, 'dui-epr-label')]
activeCareList =[xpath]://*[@id='manually_created_0']/div
activeCareCategoriesTitle = [css] :#dui_self_service_manually_created .dui-epr-label

#logs tab
logstabs = [id]:logs







