# Customer
tabTelemetryData = [id]:telemetry
telemetryTitle = [id]:telemetry-data-header
telemetrySubTitle = [xpath]://div[@id='telemetry_data']//div[contains(text(), 'Per the EU')]
requestData = [id]:button_request
requestId = [xpath]://button[@aria-label='sort by Request ID ascending']
status = [xpath]://*[@id="status"]/div/button/span
createdOn = [xpath]://*[@id="created_date"]/div/button/span
downloadToastNotification= [xpath]://div[contains(text(),'Requested data generation is in progress.')]
requestIdColumn= [xpath]:(//*[@class='telemetry-table-list']//tbody/tr/td)[1]
requestIdStatus= [xpath]:(//*[@class='telemetry-table-list']//tbody/tr/td)[2]
requestIdCreatedtedOn= [xpath]:(//*[@class='telemetry-table-list']//tbody/tr/td)[3]
clearFilter= [xpath]://button[@aria-label='Clear Filters']
whatsNewPopupClosedButton= [xpath]: (//button[@aria-label="Close"])[2]

requestIdSearch = [id]:search-sequence
pagination= [xpath]://button[@aria-label="Select page size"]

requestIdSortBtn = [xpath]://button[contains(@aria-label,'sort by Request')]
requestIdRows = [xpath]://*[@class='telemetry-table-list']//tbody/tr[1]

statusDropdown = [id]:search-status
statusInitiated = [xpath]://div[contains(@class, "wex-panel-content-wrapper   ")]//div/ul/li[1]
statusInprogress = [xpath]://div[contains(@class, "wex-panel-content-wrapper   ")]//div/ul/li[2]
statusCompleted = [xpath]://div[contains(@class, "wex-panel-content-wrapper   ")]//div/ul/li[3]
statusExpired = [xpath]://div[contains(@class, "wex-panel-content-wrapper   ")]//div/ul/li[4]
statusFailed = [xpath]: //div[contains(@class, "wex-panel-content-wrapper   ")]//div/ul/li[5]
statuscolumndropdown = [xpath]://div[contains(@class, "wex-value-field-content ")]/div

noRecordText = [css]:.wex-empty-state-widget .state-title

threeDot = [xpath]:(//div[@class="telemetry-table-list"]//td/button)[1]
downloadButton = [id]:wex-menu-list-item

dataCollectionLink = [xpath]://div[@class='wex-panel-content ']//a

# Partner Admin
SelectCustomer = [id]:wex_cs_btn_expanded

logs = [xpath]:(//*[@id="logs"])[1]
typeDropdown = [xpath]://input[@id="type"]
typeListSearch= [xpath]://*[@role="listbox"]/..//input[@placeholder='Search']
subtypeDropdown = [xpath]://input[@id="source"]
subtypelist = [xpath]://li[contains(@role,'option')]//div/span
levelDropdown = [xpath]://input[@id="severity"]
typeList = [xpath]://li[contains(@role,'option')]//div/span
levellist = [xpath]://li[contains(@role,'option')]//div/span
logEntries = [xpath]:(//div[@id='logDetails']//div)[2]/div/span
dateAndTimeHeader = [css]:#createdAt
firstRowDateAndTime = [xpath]: ((//table[@id="logs"]/tbody/tr[1])/td[2] //a)[1]

logEntries = [id]:logDetails
loginfo = [xpath]://div[@id='dui-summary-card']
typeinfo = [xpath]:(//div[@class='dui-summary-card-desc-row']/div)[2]
subtypeinfo = [xpath]:(//div[@class='dui-summary-card-desc-row']/div)[4]
levelinfo = [xpath]://div[@id='Information']//div[@class="dui-icon-label"]
