whatsNewTabRoot = [id]:menu_whatsNew
whatsNewTabMspRA = [id]:menu_whatsNew
whatsNewTitle = [css]:#whatsNew h4
whatsNewTitleOnBreadcrumbs = [css]:#whatsNew li
draftNewReleaseButton = [xpath]://*[@class='dui-action-bar']//button
draftNewReleaseButtonFirst = [id]:secondary-id
releaseVersion = [name]:version
dateField = [name]:date
customerNotes = [name]:customer
partnerNotes = [name]:partner
save = [xpath]://*[contains(@class,'saveDraftModal')]
cancel = [xpath]://*[contains(@class,'cancelDraftModal')]
arrowRight = [css]:[class*=DayPickerNavigation] div[aria-label*=next] button
arrowLeft = [css]:[class*=DayPickerNavigation] div[aria-label*=previous] svg
todayButton = [xpath]://*[contains(@class,'CalendarMonth_table')]//tr//td[contains(@class,'CalendarDay__highlighted')]
versionDisabledCheck = [xpath]:(//*[@name='date']/ancestor::div[contains(@class,'draft_new_modal')]//label)[1]
dateDisabledCheck = [xpath]:(//*[@name='date']/ancestor::div[contains(@class,'draft_new_modal')]//label)[2]
days = [xpath]://*[contains(@class,'CalendarMonth ') and @data-visible='true']//table//tr[2]/td
successMessage = [xpath]://*[@role="alert"]
listOfTotalVersions = [xpath]://h3[@class='release-version']
listOfCustomerNotes = [xpath]://*[@class='release-product customersData']/div//p
listOfPartnerNotes = [xpath]://*[@class='release-product partnersData']/div//p
latestReleaseTag = [xpath]:(//*[contains(@class,'release-status')])[1]
partnerTitle = [css]:h4.dui-app-bar-title
partnerTab = [id]:menu_partners
menuIcon = [id]:dui-side-menu
removeButton = [xpath]://*[contains(@class,'draft_remove')]
editButton = [xpath]://*[contains(@class,'draft_edit')]
removeMessageModal = [xpath]://*[contains(@class,'modal--body')]//div[@class='content']
removeButtonModal = [id]:btn_remove
cancelButtonModal = [id]:btn_cancel
modalHeader = [xpath]://*[contains(@class,'modal--content')]/h4
whatsNewDecriptionHeader = [id]:whatsNew-description
administratorTab = [id]:menu_administrator
whatsNewTitlePartner =[css]:#dui-container div.row h4

#What's new popup locators
whatsNewPopup = [xpath]:(//*[contains(@class, 'whatsnew-model')]//div)[2]
whatsNewPopupCloseButton = [css]:[class*=release-whatsnew] div[class*=modal--dialog] button
whatsNewTitleOnPopup = [css]:[class*=release-whatsnew] div[class*=modal--dialog] h4
whatsNewDescriptionOnPopup = [css]:[class*=release-whatsnew] div[class*=sectionHeader] p
releaseVersionOnPopup = [css]:#scrollableDiv > div > div > div:nth-child(1) [class=release-version]
customersNotes = [css]:#scrollableDiv > div > div > div:nth-child(1) [class*=customersData] span
partnersNotes = [css]:#scrollableDiv > div > div > div:nth-child(1) [class*=partnersData] span
partnersProductEnhancementData = [css]:#scrollableDiv > div > div > div:nth-child(1) [class*=partnersData] p
customersProductEnhancementData = [css]:#scrollableDiv > div > div > div:nth-child(1) [class*=customersData] p
manageNotificationLink = [css]:[class*=manage-notication] a
popupAlertText = [css]:#whatsNewAlert [class*=label]
emailAlertsText = [css]:#whatsNewMail [class*=label]
emailAlertsToggleText = [css]:#whatsNewMail [class*=panel-title]
popupAlertsToggleText = [css]:#whatsNewAlert [class*=panel-title]
popupAlertToggle = [css]:#whatsNewAlert [class*=toggle] span
emailAlertToggle = [css]:#whatsNewMail [class*=toggle] span
tableOverlay = [xpath]://*[@role='progressbar']
hpIcon = [xpath]://a[@class="row"]//*[name()='svg']
hpDaas = [xpath]://a[@class="row"]//span
languageDropDown = [xpath]://div[@role='button']
signInButton = [id]:button-signIn
whatsNewSectionHeader = [css]:#targeted-scrollable-container h3
whatsNewDescription = [css]:#targeted-scrollable-container p[class*=section-description]
whatsNewLink = [css]:#scrollableDiv * div[class='release-product customersData'] >* div:nth-child(1)>p>a