whatsNewTabRoot = [id]:menu_whatsNew
whatsNewTabMspRA = [id]:menu_whatsNew
whatsNewTitle = [css]:#whatsNew h4
whatsNewTitleOnBreadcrumbs = [css]:#whatsNew li
draftNewReleaseButton = [xpath]://*[@class='dui-action-bar']//button
draftNewReleaseButtonFirst = [id]:secondary-id
releaseVersion = [id]:version
dateField = [name]:date
customerNotes = [id]:customer
partnerNotes = [id]:partner
save = [xpath]://*[contains(@class,'saveDraftModal')]
cancel = [xpath]://*[contains(@class,'cancelDraftModal')]
arrowRight = [xpath]://*[contains(@class,'DayPickerNavigation_button')]//*[name()='svg' and contains(@class,'next')]
arrowLeft = [xpath]://*[contains(@class,'DayPickerNavigation_button')]//*[name()='svg' and contains(@class,'prev')]
todayButton = [xpath]://*[@id="button"]
versionDisabledCheck = [xpath]://*[@id='version']//preceding::label
dateDisabledCheck = [xpath]://*[@name='date']/ancestor::div[contains(@class,'form-field')]//label
days = [xpath]://*[contains(@class,'CalendarMonth ') and @data-visible='true']//table//tr[2]/td
successMessage = [xpath]://*[contains(@class,'toast-container--bottom')]/div/p
listOfTotalVersions = [xpath]://h2[@class='release-version']
listOfCustomerNotes = [xpath]://*[@class='release-product customersData']/div//p
listOfPartnerNotes = [xpath]://*[@class='release-product partnersData']/div//p
latestReleaseTag = [xpath]://*[contains(@class,'latest-release')]
partnerTitle = [css]:h4.dui-app-bar-title
partnerTab = [id]:menu_partners
menuIcon = [id]:dui-side-menu
removeButton = [xpath]://*[contains(@class,'draft_remove')]
editButton = [xpath]://*[contains(@class,'draft_edit')]
removeMessageModal = [xpath]://*[contains(@class,'modal__body')]/div
removeButtonModal = [id]:btn_remove
cancelButtonModal = [xpath]:(//*[contains(@class,'modal__content')]//button)[3]
modalHeader = [xpath]://*[contains(@class,'modal__header')]/h4
whatsNewDecriptionHeader = [id]:whatsNew-description
administratorTab = [id]:menu_administrator
whatsNewTitlePartner =[css]:#dui-container div.whats-new-panel  h5

#What's new popup locators
whatsNewPopup = [css]:[class*=modal__content]
whatsNewPopupCloseButton = [css]:[class*=modal__dialog] button[class*=modal__close]:nth-child(1)
whatsNewTitleOnPopup = [css]:[class*=modal__content] h5
whatsNewDescriptionOnPopup = [css]:[class*=whats-new-panel] p
releaseVersionOnPopup = [css]:#scrollableDiv h2[class*=release-version]
customersNotes = [css]:#scrollableDiv [class*=customersData] span
partnersNotes = [css]:#scrollableDiv [class*=partnersData] span
partnersProductEnhancementData = [css]:#scrollableDiv [class*=partnersData] > div
customersProductEnhancementData = [css]:#scrollableDiv [class*=customersData] > div
manageNotificationLink = [css]:[class*=manage-notication] a
popupAlertText = [css]:#whatsNewAlert [class*=label]
emailAlertsText = [css]:#whatsNewMail [class*=label]
emailAlertsToggleText = [css]:#whatsNewMail h6
popupAlertsToggleText = [css]:#whatsNewAlert h6
popupAlertToggle = [id]:whatsNewAlertEditBtn
emailAlertToggle = [id]:whatsNewMailEditBtn
tableOverlay = [css]:div[class*='dui-page-spinner'] svg
hpIcon = [xpath]://div[contains(@class,'content')]/div[contains(@class,'content--left')]//*[name()='svg']
hpDaas = [xpath]://span[contains(@class,'vn-color--primary-tint-05 app-name-short')]
languageDropDown = [xpath]://div[@role='button']
signInButton = [id]:button-signIn
whatsNewSectionHeader = [css]:div[class=whats-new-panel] h5
whatsNewDescription = [css]:div[class=whats-new-panel] p