termsAndConditions = [css]:#tnc
wexLogo = [id]:hp-wex-logo
hpWorkforceMainHeader = [id]:tnc-header-1
hpWorkforceMainHeaderBelowPara1 = [xpath]:(//h3[@id="tnc-header-1"]/following-sibling::p)[1]
howTermApplyYouHeader = [id]:tnc-sub-heading-1
howTermApplyYouHeaderBelowPara = [xpath]:#tnc-sub-heading-1+ul
serviceUseTermsHeader = [id]:tnc-sub-heading-2
additionalTermsHeader = [id]:tnc-sub-heading-3
documentText = [css]:div.document
printButton = [id]:printButtton
notificationBell = [classname]:wex-notification-button
profieIcon = [css]:div.wex-profile-avatar
softwareHrefLink = [xpath]://a[@href="https://workforceexperience.hp.com/software"]
privacyHrefLink = [xpath]://a[@href="www.hp.com/go/privacy"]
cookieAccept = [css]:#onetrust-accept-btn-handler
helpAndSupport = [css]:#help-support-button, #menu_support_link
documentText = [css]:div.document
langaugeDrodown = [xpath]://div[@role="combobox"]