serviceHeader = [id]:sla-header
wexLogo = [id]:hp-wex-logo
printButton = [id]:printButtton
lastUpdated = [id]:sla-last-updated
lastUpdatedBelowPara = [css]: #sla-last-updated + p
definationsHeader = [id]:sla-definitions
definationHeaderBelowPara = [css]: #sla-definitions + ol
serviceCommitment = [id]:sla-service-commitment
serviceCommitmentBelowPara1 =[css]: #sla-service-commitment + p
serviceCommitmentBelowPara2 =[css]: #sla-service-commitment + p + p
exclusionsHeader = [id]:sla-exclusions
exclusionsHeaderBelowPara1 =[css]: #sla-exclusions + p
exclusionsHeaderBelowPara2 =[css]: #sla-exclusions + p + p
helpAndSupport = [css]:#help-support-button, #menu_support_link
cookieAccept = [css]:#onetrust-accept-btn-handler
notificationBell = [classname]:wex-notification-button
profieIcon = [xpath]://div[@class='profileCard-section']
slaLink = [xpath]://a[text()='Service Level Agreement']
langaugeDrodown = [xpath]://input[@role='combobox']