WorkforceLogo = [css]:#header .logo 
Platform = [xpath]:(//ul[@class="nav"] //li/*/a)[1]
Partners = [css]:.nav>li>a
Resources = [xpath]:(//ul[@class="nav"] //li/*/a)[2]
AboutUs = [css]:ul.nav>li:nth-child(3) li:nth-child(1) a
Blog = [css]:ul.nav>li:nth-child(3) li:nth-child(2) a
Signin = [css]:.btns-wrap a.btn.btn-sm:nth-child(1)
UpLearnMore = [css]:.btns-wrap a.btn.btn-sm:nth-child(2)
cookieAccept = [css]:#onetrust-accept-btn-handler

learnMore = [xpath]: //*[@id="header"]/div/div[2]/div/a[1]
iWantToSign = [xpath]://select[@id='iWantToSignUpOrTalk']
aboutU = [xpath]: //*[@id="field0"]/div/label
firstName = [xpath]: //*[@id="field1"]/div[1]/label
lastName = [xpath]: //*[@id="field1"]/div[2]/label
email = [xpath]: //*[@id="field2"]/div/label
CountryRegion = [xpath]: //*[@id="field3"]/div/label
state = [xpath]: //*[@id="field4"]/div/label
company = [xpath]: //*[@id="field5"]/div/label
jobTitle = [xpath]: //*[@id="field6"]/div/label
titleFrame = [xpath]: //*[@title="Form"]
