systemRequirementLabel = [id]:system-requirements
belowDesc = [id]:system-requirements-desc
systemLearnMorebtn = [id]:system-requirements-btn
systemRequirementTitle = [id]:sys-requirements-title
titleBelowDesc = [id]:sys-requirements-desc
pcOperatingLabel = [id]:pc-operating-sys-label
pcBelowDesc = [id]:pc-operating-sys-desc
windowsLabel = [id]:windows-sys-label
windows10Label = [id]:windows-10-label
windows11Label = [id]:windows-11-label
macOslabel = [id]:macOS-label
macOsDesc = [id]:macOS-catalina-label
chromeLabel = [id]:chromeOS-label
chromeDesc = [id]:chromeOS-desc
mobileOsLabel = [id]:mobile-os-label
MobileOSDesc = [id]:mobile-os-desc
andriodLabel = [id]:andriod-updated
iosLabel = [id]:ios-updated
mobileBelowText = [id]:mobile-device-note
networkLabel = [id]:network-requirements-label
networkBelowDesc = [id]:network-requirements-desc
webBrowserLabel = [id]:web-browser-label
webBrowserDesc = [id]:web-browser-desc
pcLabel = [id]:pc-web-browser
mobileLabel = [id]:mobile-web-browser
googleLabel = [id]:google-chrome-label
msEdgeLabel = [id]:ms-edge-label
pcBelowNote = [id]:support-for-internet-explorer-note
uninstallTitle = [id]:uninstall-disable-title
uninstallLabel = [id]:uninstall-label
uninstallDesc = [id]:uninstall-desc
manualliuninstallLink = [css]:a[id=manual-uninstall-link] 
uninstallLink = [css]:a[id=uninstall-with-sccm-link]
uninstallGroupLink = [css]:a[id=uninstall-with-grp-policy-link]
disableLabel = [id]:disable-service-label
disableServiceDesc = [id]:disable-service-desc
disableServiceLink = [id]:disable-service-link
hpReatilLabel = [xpath]:(//h5[@id='hp-retail-label'])[1]
hpretaillabel2 = [xpath]:(//h5[@id='hp-retail-label'])[2]
hpretaillabel3 = [xpath]:(//h5[@id='hp-retail-label'])[3]
hpretailist1 = [xpath]:(//li[@id='hp-retail-label'])[1]
hpretailist2 = [xpath]:(//li[@id='hp-retail-label'])[2]
hpretailist3 = [xpath]:(//li[@id='hp-retail-label'])[3]
hpretailist4 = [xpath]:(//li[@id='hp-retail-label'])[4]
Windows11 = [id]:hp-retail-hp-rp9
11Enterprise = [id]:hp-retail-hp-mp9
11IotEnt = [id]:hp-retail-hp-rp5
Windows10pro = [id]:hp-engage-one
Windows10ent = [id]:hp-engage-pro
10IotEnt = [id]:hp-engage-pro-c
hpRposNotes1=[xpath]://*[@id="requirements-rpos"]/p[1]
printProxyTitle = [id]:print-fleet-proxy
printProxyText1 = [xpath]:(//*[@id='requirements-printer-fps']//div/p[1])[1]
printProxyText2 = [xpath]:(//*[@id='requirements-printer-fps']//div/p[2])[1]
serverHeaderTitle = [id]:fleet-proxy-server-hardware
serverText1 = [xpath]:(//*[@id='requirements-printer-fps']//div/p[1])[2]
serverText2 = [xpath]:(//*[@id='requirements-printer-fps']//div/p[2])[2]
serverId1 = [id]:server-hardware-hp-sh1
serverId2 = [id]:server-hardware-hp-sh2
serverId3 = [id]:server-hardware-hp-sh3
serverId4 = [id]:server-hardware-hp-sh4
networkHeader = [id]:fleet-proxy-network-and-firewall
networkText1 = [xpath]:(//*[@id='requirements-printer-fps']//div/p[1])[3]
networkText2 = [xpath]:(//*[@id='requirements-printer-fps']//div//ul//p)[1]
networkText3 = [xpath]:(//*[@id='requirements-printer-fps']//div//ul//p)[2]
networkText4 = [xpath]:(//*[@id='requirements-printer-fps']//div//ul//p)[3]
networkLink1 = [css]:a[href ="https://services.cloud.mongodb.com"]
networkLink2 = [css}:a[href= "https://www.mongodb.com/docs/atlas/setup-cluster-security"]
systemWexLogo = [id]:hp-wex-logo
systemHelpAndSupport = [css]:#help-support-button, #menu_support_link
cookieAccept = [css]:#onetrust-accept-btn-handler
SystemPrintButton = [id]:printButtton
systemNotificationBell = [classname]:wex-notification-button
systemProfieIcon = [xpath]://div[@class='profileCard-section']
langaugeDrodown = [xpath]://input[@role="combobox"]
WindowsServer=[id]:windows-server-label
ChromeDesc=[id]:chromeOS-desc1
SupportPlatform=[xpath]:(//h6[@id="hp-retail-label"])[1]
SupportPeripheral=[xpath]:(//h6[@id="hp-retail-label"])[2]
NetworkText=[xpath]://h6[@id="fleet-proxy-network-and-firewall"]/following-sibling::p[1]