addCustomer= [id]:btn_company_add
companyName= [xpath]://input[@id='company-name']
addressLine= [xpath]://input[@name='address']
nextButton= [id]:btn_next
city= [xpath]://input[@placeholder='City']
state= [xpath]://input[@placeholder='State/Province']
zipCode= [xpath]://input[@placeholder='2586']
firstName= [xpath]: //input[@placeholder='Enter First Name']
lastName= [xpath]://input[@placeholder='Enter Last Name']
emailAddress= [xpath]: //input[@placeholder='username@email.com']
selectIdp= [id]:idp-dropdown
idpList= [css]:#idp-dropdown-listbox>li
addButton= [id]:btn_create
tenantTitle= [xpath]: //h1[@class='dui-dsummary-card-title']
selectidpvalue = [xpath] : //div[@class="css-hyqgz1"]/ul[contains(@id,'listbox')]/li
emailIdValue=[xpath] :((//span[@class="dui-hyphenate dui-panel-title"])[7]/div)[1]
companyProfile= [id]:company-profile-header
planList= [xpath]://ul[contains(@id, 'listbox')]/li