# Collaborationspace
collaborationspace =[xpath]://div[@id="custom-dashboard-collaboration-spaces"]
collaborationspacepagetitle =[xpath]://span[text()="Collaboration Spaces"]
SpacesOverviewwidget = [xpath]:(//div[text()="Spaces Overview"])[1]
RoomUtilizationwwidget = [xpath]:(//div[text()="Room Utilization by Building"])[1]
OccupiedRoomwidget = [xpath]:(//div[text()="Occupied Room Minutes by Location"])[1]
RoomActivityTypewidget = [xpath]:(//div[text()="Room Activity Type - Total Minutes"])[1]
SpacesbyTypewidget = [xpath]:(//div[text()="Spaces by Type"])[1]
SpacesbyRoomwidget = [xpath]:(//div[text()="Spaces by Room System"])[1]
BookedMeetingswidget = [xpath]:(//div[text()="Booked Meetings by Location"])[1]
MissedMeetingswidget = [xpath]:(//div[text()="Missed Meetings by Location"])[1]
HighlyUtilizedwidget = [xpath]:(//div[text()="Highly Utilized Spaces"])[1]
Underutilizedspacewidget= [xpath]:(//div[text()="Underutilized Spaces"])[1]
MissedMettingsbydepartmentwidget = [xpath]:(//div[text()="Missed Meetings by Department"])[1]
Spacesover100%widget = [xpath]:(//div[text()="Spaces with over 100% Occupancy"])[1]
Allwidgets=[xpath]://h2[@class="wexcard-header-title"]
Menu = [xpath]:(//div[@id='main-content']//button[@aria-haspopup='menu'])[1]
DuplicateDashboard =[xpath]://span[text()="Duplicate Dashboard"]
EditDashboard = [xpath]://span[text()="Edit Dashboard"]
CopyCreated =[xpath]://div[text()="Copy of dashboard created successfully"]
CopyCollaboartionSpacestitle =[xpath]://span[text()="Copy Collaboration Spaces"]
DeleteMenu =[xpath]://span[text()="Delete Dashboard"]
DeleteDashboard =[xpath]://h4[text()="Delete Dashboard"]
DeleteButton =[xpath]://span[text()="Delete"]
DeleteSuccessfully = [xpath]://div[text()="Dashboard deleted successfully"]
RenameEditbutton = [xpath]://div[@class="dui-margin-right-10 dui-pointer"]
Renamefield =[xpath]://input[@value="Copy Collaboration Spaces"]
Editfield =[xpath]:(//input[@type="text"])[1]
EditSavebutton = [xpath]:(//div[@class="dui-margin-right-10 dui-pointer"])[1]
NameUpdate =[xpath]://div[text()="Dashboard name updated successfully"]
UpdatedTitle = [xpath]://span[@aria-current="page"]
CustomCollaborationSpaces=[xpath]://p[text()="CustomCollaborationSpaces"]
AnalyticsTab = [xpath]://a[@href="/ui/view/analytics"]
SelectWidgets=[xpath]://div[@class="dui-fleet-details-title dui-item-vertical-center title-regular"]
SelectCollaborationspace = [xpath]:(//span[text()="Collaboration Spaces"])[2]
UncheckSpacesOverviewwidget = [xpath]:(//div[@class="wexcard-content-area"])[1]
UncheckRoomUtilizationwwidget =[xpath]:(//div[@class="wexcard-content-area"])[2]
UncheckOccupiedRoomwidget =[xpath]:(//div[@class="wexcard-content-area"])[3]
Dashboardupdate =[xpath]: //div[text()="Dashboard updated successfully"]
CopyDashboardSpace =[xpath]://div[@id="custom-dashboard-copy-collaboration-spaces"]
Savebutton =[xpath]://span[text()="Save"]
Widgetsmenu =[xpath]://button[@data-testid="custom-dashboard-widget-action-menu-1"]
Removebutton =[xpath]:(//button[@aria-label="Remove widget"])[1] 
Widgetremovedsuccessfully =[xpath]://div[text()="Widget removed successfully"]
RoomActivityTypeMenu =[xpath]:(//button[@aria-label="More options"])[4]
ExportPNGButton =[xpath]://span[text()="Export as PNG"]
PNGdownload =[xpath]://div[text()="PNG exported successfully"]
ExportData =[xpath]://span[text()="Export"]
XLSXFile =[xpath]://span[text()="XLSX"]
NotificationCenter =[xpath]://button[@aria-label="Open Notification Center"]
NotificationTab =[xpath]://span[text()="Notifications"]
DownloadFile =[xpath]://span[text()="Download File"]
Report =[xpath]: //span[text()="You have a new CustomCollaborationSpaces xls report available for download."]
VideoButton =[xpath]://button[@aria-label="Show Video Only"]
AudioButton =[xpath]://button[@aria-label="Show Audio Only"]
NoDataDisplay =[xpath]://*[@class="highcharts-label highcharts-no-data"]
GraphBar =[xpath]:(//*[@class="highcharts-grid highcharts-yaxis-grid"])[2]
SpaceRoomDetails =[xpath]:(//*[@class="highcharts-series-group"])[2]
AverageRoom =[xpath]://div[text()="Average Room Utilization"]
Workspaces =[xpath]://span[@aria-current="page"]
CreateNew =[xpath]://div[@class="create-new"]
CollaborationSpace =[xpath]://span[text()="Collaboration Spaces"]
Create =[xpath]://span[text()="Create"]
NewDashboardCreated =[xpath]://div[text()="New dashboard created successfully"]
NewCollaborationSpace =[xpath]://p[text()="NewCustomCollaborationSpaces"]
ClearNewDashboard =[xpath]:(//input[@type="text"])[1]
Source =[xpath]:(//div[@class="dashboard-drag-icon"])[1]
Destination =[xpath]:(//div[@class="dashboard-drag-icon"])[2]
collaborationExperience = [xpath]: //p[text()="Collaboration Experience"]
collaborationExperienceHover = [xpath]://div[text()="Created by HP"]
collaborationExperiencePageTitle = [xpath]://span[text()="Collaboration Experience"]
ViewDetails= [xpath]:(//span[text()="View Details"])[1]
Loginimage =[xpath]://h1[text()="Log In"]
username =[xpath]://input[@name="username"]
Nextbutton=[xpath]://button[text()="Next"]
Passwordbutton=[xpath]://input[@name="password"]
Loginbutton =[xpath]://button[text()="Log In"]
Customcollaborationexperience =[xpath]://p[text()="CustomCollaborationExperience"]
RenamefieldExperience =[xpath]://input[@value="Copy Collaboration Experience"]
MeetingSummary =[xpath]:(//div[text()="Meetings Summary"])[1]
MeetingPlatform =[xpath]:(//div[text()="Meetings by Platform over Time"])[1]
MeetingTeams =[xpath]:(//div[text()="Meeting Quality - MSFT Teams"])[1]
MeetingZoom =[xpath]:(//div[text()="Meeting Quality - Zoom"])[1]
MeetingCisco =[xpath]:(//div[text()="Meeting Quality - Cisco Webex"])[1]
RemoteParticipant =[xpath]:(//div[text()="Remote Participant Quality of Experience"])[1]
CorporateNetwork =[xpath]:(//div[text()="In-Office/Corporate Network Quality of Experience"])[1]
BadQuality =[xpath]:(//div[text()="Bad Quality of Experience by Network"])[1]
VideoEndpointQuality =[xpath]:(//div[text()="Video Endpoint Quality of Experience"])[1]
EndUserDeviceQuality =[xpath]:(//div[text()="End User Device Quality of Experience"])[1]
CommonEndUser =[xpath]:(//div[text()="Common End User Issues"])[1]
BadQualityofExperience =[xpath]:(//div[text()="Bad Quality of Experience by Device"])[1]
CopyCollaborationExperiencetitle =[xpath]://span[text()="Copy Collaboration Experience"]
Collaboration =[xpath]://div[@id="custom-dashboard-widget-lib-COLLABORATION-category"]
MeetingTeamscollaboartionpage =[xpath]://div[text()="Meeting Quality - MSFT Teams"]
BadQualitycollaboartionpage =[xpath]://div[text()="Bad Quality of Experience by Network"]
CorporateNetworkcollaboartionpage =[xpath]://div[text()="In-Office/Corporate Network Quality of Experience"]
VideoEndpointQualitycollaboartionpage =[xpath]://div[text()="Video Endpoint Quality of Experience"]
NewCollaborationExperience =[xpath]://p[text()="NewCustomCollaborationExperience"]
CopyCollaborationExperience =[xpath]://p[text()="Copy Collaboration Experience"]
Sourceelement =[xpath]:(//div[@class="wexcard-header-title-container"])[1]
Destinationelement =[xpath]:(//div[@class="wexcard-header"])[2]
StageVypota =[xpath]://div[text()="Created by Stage Vyopta"]
MeetingSummaryContentUpper =[xpath]:(//div[@class="meetingssummary-widget-content"])[1]
MeetingSummaryContentLower =[xpath]:(//div[@class="meetingssummary-widget-content"])[2]
MeetingSummarymenu =[xpath]://button[@data-testid="custom-dashboard-widget-action-menu-1"]
MSFTTeams =[xpath]://button[@aria-label="Show MSFT Teams"]
Zoom =[xpath]://button[@aria-label="Show Zoom"]
CiscoWebex =[xpath]://button[@aria-label="Show Cisco Webex"]
Grapline =[xpath]:(//*[@class="highcharts-grid highcharts-yaxis-grid"])[1]
CopyasPNG =[xpath]://button[@aria-label="Copy as PNG"]
MeetingPlatfrommenu =[xpath]://button[@data-testid="custom-dashboard-widget-action-menu-2"]
Meetings =[xpath]://nav[@aria-label="breadcrumbs"]
NetworkWigdet =[xpath]:(//div[@class="wexcard-content-area"])[8]
BadQualityViewButton =[xpath]:(//span[text()="View Details"])[7]
BadQualitymenu =[xpath]://button[@data-testid="custom-dashboard-widget-action-menu-8"]
BadQualityExperience =[xpath]://button[@data-testid="custom-dashboard-widget-action-menu-12"]
BadQualityExperienceContent =[xpath]:(//div[@class="wexcard-content-area"])[12]
CommonEndUserContent =[xpath]:(//div[@class="wexcard-content-area"])[11]
CommonEndUsermenu =[xpath]://button[@data-testid="custom-dashboard-widget-action-menu-11"]
GreatButton =[xpath]://button[@aria-label="Show Great"]
FairButton =[xpath]://button[@aria-label="Show Fair"]
PoorButton =[xpath]://button[@aria-label="Show Poor"]
Bargraph =[xpath]:((//div[@aria-label="Chart. Highcharts interactive chart."])[2]//*[@role="img"])[2]
MSFTTeamsviewdetails =[xpath]:(//span[text()="View Details"])[2]
DonutGreat =[xpath]:(//*[text()="Great: "])[1]
DonutFair =[xpath]:(//*[text()="Fair: "])[1]
DonutPoor =[xpath]:(//*[text()="Poor: "])[1]
Donut =[xpath]:(//div[@class="wexcard-content-area"])[6]//*[@role="img"]
RemoteParticipantDonut =[xpath]:(//div[@class="wexcard-content-area"])[6]
RemoteParticipantViewDetails =[xpath]:(//span[text()="View Details"])[5]
collaborationExperiencetitle = [xpath]:(//*[text()="Collaboration Experience"])[2]
Subtitle =[xpath]://span[text()="Average Meeting Quality by Platform"]
Infobutton =[xpath]://div[@class="meetings-summary-widget-title wex-foreground-medium-color"]//*[contains(@class, '-base-Icon')]
InfoText =[xpath]://div[text()="Meeting quality is between 1-3."]
Drilldownbutton =[xpath]://div[text()="MSFT Teams"]
Participantsbutton =[xpath]://span[text()="Participants"]
MeetingTeamsviewdetails =[xpath]:(//span[text()="View Details"])[3]
MeetingZoomviewdetails =[xpath]:(//span[text()="View Details"])[4]
MeetingCiscoviewdetails =[xpath]:(//span[text()="View Details"])[6]
VideoEndpointviewdetails =[xpath]:(//span[text()="View Details"])[8]
Endpointviewdetails =[xpath]:(//span[text()="View Details"])[9]
Endpointvyopta =[xpath]://*[@aria-label="breadcrumbs"]