# Locators for WXPIntegrationsPage
# Example:
integrationsPageIframe = [xpath]://iframe[@id='fastn-widget-iframe']
integrationsPageConnectorCard = [xpath]://div[@data-testid='connector-card-%CONNECTOR_ID%']
integrationsPageConnectorUpgradeCard = [xpath]:(//*[@id='fastn_widget']//h2[@data-testid=''])[last()]
integrationsPageViewAllButton = [xpath]://button[@data-testid='connector-filter-all-button']
integrationsPageActiveButton = [xpath]://button[@data-testid='connector-filter-active-button']
integrationsPageInactiveButton = [xpath]://button[@data-testid='connector-filter-inactive-button']
integrationsPageConnectorConnectButton = [xpath]://div[@data-testid='connector-card-%CONNECTOR_ID%']//button[normalize-space(text())='Connect']
integrationsPageConnectorConfigureButton = [xpath]://div[@data-testid='connector-card-%CONNECTOR_ID%']//button[normalize-space(text())='Configure']
integrationsPageConnectorDisconnectButton = [xpath]://div[@data-testid='connector-card-%CONNECTOR_ID%']//button[normalize-space(text())='Disconnect']
integrationsPageConnectorStatus = [xpath]://div[@data-testid='connector-card-%CONNECTOR_ID%']//span[contains(@class,'status')]
TextofbuttoninConnectorCard = [xpath]://div[contains(@data-testid,'connector-card-%CONNECTOR_ID%')]//button[1]
titleofopenmodal = [xpath]://div[@role='dialog']//h2[contains(@data-testid,'connector-modal-title')]
Connectbuttoninmodal = [xpath]://button[contains(@data-testid,'connector-modal-action-button-connect')]
cancelbuttoninmodal = [xpath]://button[contains(@data-testid,'connector-modal-cancel-button')]
connectedstatusofconnector= [xpath]://div[@data-testid='connector-card-%CONNECTOR_ID%']//span[@data-testid='connector-card-label-badge' and normalize-space()='Connected']