HWWarrantyDetails.Summary = summary:Graph
HWWarrantyDetails.Details = details:Grid

HWbiosInventoryDetails.Summary = summary:Graph
HWbiosInventoryDetails.UniqueBIOS = unique_bios:Graph
HWbiosInventoryDetails.ByWeek = by_week:Graph
HWbiosInventoryDetails.Details = details:Grid

HWBatteryReplDetails.Summary = summary:Graph
HWBatteryReplDetails.DeviceManufacturer = by_device_manufacturer:Graph
HWBatteryReplDetails.ManufactureYear = by_manufacture_year:Graph
HWBatteryReplDetails.Details = details:Grid

HWBlueScreenerrorDetails.Details = details:Grid

HWBlueScreenerrortdwe.Summary = summary:Graph
HWBlueScreenerrortdwe.Details = details:Grid

HWBlueScreenerrortopError.MonthlySummary = monthly_summary:Graph
HWBlueScreenerrortopError.WeeklySummary = weekly_summary:Graph
HWBlueScreenerrortopError.ErrorsSummary = errors_summary:Graph
HWBlueScreenerrortopError.DriverSummary = driver_summary:Graph
HWBlueScreenerrortopError.Details = details:Grid

HWDiskCapaPlngDetails.Summary = summary:Graph
HWDiskCapaPlngDetails.DiskCapacity = by_disk_size:Graph
HWDiskCapaPlngDetails.DiskModel = by_disk_model:Grid
HWDiskCapaPlngDetails.Details = details:Grid

HWDeviceutilDetails.Summary = summary:Graph
HWDeviceutilDetails.ManufactureYear = by_manufacture_year:Graph
HWDeviceutilDetails.SoftPerf = windows_software_performance:Graph
HWDeviceutilDetails.SoftPerfMac = windows_software_performance_mac_os:Graph
HWDeviceutilDetails.Details = details:Grid

HWDiskReplcDetails.Summary = summary:Graph
HWDiskReplcDetails.DiskSize = by_disk_size:Graph
HWDiskReplcDetails.DeviceManufacturer = by_device_manufacturer:Graph
HWDiskReplcDetails.ManufactureYear = by_manufacture_year:Graph
HWDiskReplcDetails.Details = details:Grid

HWBatterySwellProbabilityDetails.Summary = summary:Graph
HWBatterySwellProbabilityDetails.Details = details:Grid

HWWin11ReadinessDetails.Summary = summary:Graph
HWWin11ReadinessDetails.Details = details:Grid

HWGradeDetails.Summary = summary:Graph
HWGradeDetails.Details = details:Grid

HWHealthDetails.Summary = summary:Graph
HWHealthDetails.Details = details:Grid

HWInventoryDetails.ByLocation = hwinv_by_location:Graph
HWInventoryDetails.ByDeviceCongiguration = hwinv_by_device_configurations:Graph
HWInventoryDetails.ByDeviceModel = hwinv_by_device_model:Graph
HWInventoryDetails.ByOperatingSystem = hwinv_by_device_os:Graph
HWInventoryDetails.Details = details:Grid

HWInventoryMonthlySmry.MonthlySummary = monthly_summary:Graph
HWInventoryMonthlySmry.Details = details:Grid

HWInventoryAllData.Details = details:Grid

HWThermalGradingDetails.Summary = summary:Graph
HWThermalGradingDetails.Details = details:Grid

HWThermalEvents.Summary = summary:Graph
HWThermalEvents.Details = details:Grid

HWHealthNewMonthlySmry.healthSummary = health_summary:Graph
HWHealthNewMonthlySmry.resourceHealthSummary = resources_health_summary_new:Graph
HWHealthNewMonthlySmry.Details = details:Grid

HWReplacementDetails.Summary = summary:Graph
HWReplacementDetails.Details = details:Grid

#HWMSTelemetry.DeviceHealth = msft_device_health:Graph
#HWMSTelemetry.UpgradeReadiness = msft_upgrade_readiness:Graph
HWMSTelemetry.UpdateCompliance = msft_update_compliance:Graph

HWDeviceutilByTime.Summary = summary:Graph
HWDeviceutilByTime.ByHour = by_hour:Graph
HWDeviceutilByTime.ByDay = by_day:Graph
HWDeviceutilByTime.Details = details:Grid

HWBIOSHistoryUpdate.Details = details:Grid

#Battery Usage Optimization
HWBatteryOptimizationDetails.Summary = summary:Graph
HWBatteryOptimizationDetails.ByModel = by_model:Graph
HWBatteryOptimizationDetails.ByWarranty = by_battery_warranty:Graph
HWBatteryOptimizationDetails.Details = details:Grid
HWBatteryOptimizationDetails.BHMBIOSUpdatesDetails = bhmBiosUpdate:Grid

#Batter Replacement & Risk factor
HWBatteryReplacementRiskFactor.Summary = summary:Graph
HWBatteryReplacementRiskFactor.ByModel = by_model:Graph
HWBatteryReplacementRiskFactor.ByWarranty = by_device_warranty:Graph
HWBatteryReplacementRiskFactor.Details = details:Grid
HWBatteryReplacementRiskFactor.BHMBIOSUpdatesDetails = bhmBiosUpdate:Grid

#GPU Health/Performance
HWGPUHealthPerformance.ByWeek = by_week:Graph
HWGPUHealthPerformance.Details = details:Grid

#All Data - Software Performance by Applications (Utilization Bins)
HWDeviceutilAllData.Details = details:Grid

#Security

SecSCACliProtStateDetails.Summary = summary:Graph
SecSCACliProtStateDetails.Details = details:Grid

SecSCAThreatProtDetails.Summary = summary:Graph
SecSCAThreatProtDetails.Details = details:Grid

SecSCAThreatSumDetails.Summary = summary:Graph
SecSCAThreatSumDetails.Details = details:Grid


SecSCASecurity.devices = devices:Graph
SecSCASecurity.threats = threats:Graph
SecSCASecurity.deviceDetails = device_protection_details:Grid
SecSCASecurity.threatDetails = threat_protection_details:Grid


SecWDEPSecurity.Summary = summary:Graph
SecWDEPSecurity.deviceDetails = device_protection_details:Grid
SecWDEPSecurity.threatDetails = threat_protection_details:Grid:Grid

SecSSASecurity.devices = devices:Graph
SecSSASecurity.threats = threats:Graph
SecSSASecurity.deviceDetails = device_protection_details:Grid
SecSSASecurity.threatDetails = event_and_file_protection_details:Grid

SecSSProSecurity.devices = devices:Graph
SecSSProSecurity.threats = threats:Graph
SecSSProSecurity.deviceDetails = device_protection_details:Grid
SecSSProSecurity.threatDetails = threat_details:Grid

SecCompSecComplMonthly.endpointProtection = endpoint_protection:Graph
SecCompSecComplMonthly.Details = details:Grid

SecCompSecCompl24Hourly.Summary = endpoint_protection:Graph
SecCompSecCompl24Hourly.Details = details:Grid

SecDevCompProDetails.Summary = summary:Graph
SecDevCompProDetails.Details = details:Grid

SecDevSecCompMonthly.endpointProtection = endpoint_protection:Graph

SecDevSecCompl24hourly.antivirusApps = antivirus_applications:Graph
SecDevSecCompl24hourly.firewallApps = firewall_applications:Graph
SecDevSecCompl24hourly.Summary = endpoint_protection:Graph
SecDevSecCompl24hourly.Details = details:Grid

SecLostDevProtDetails.Summary = summary:Graph
SecLostDevProtDetails.Details = details:Grid

SecLostDevProtDetails.topDevices = top_devices:Graph

SecNonRepoDevDetails.Summary = summary:Graph
SecNonRepoDevDetails.Details = details:Grid

SecPatchComplDetails.Details = details:Grid

SecPatchComplPatchDaysDevice.PatchDaysDevice = patches_days_by_device:Graph

SecPatchComplPatchDaysProduct.PatchDaysProduct = patches_days_by_product:Graph

SecPatchComplPatchesByDevice.PatchesByDevice = patches_by_device:Graph

SecPatchComplPatchesByProduct.PatchesByProduct = patches_by_product:Graph

SecSureRecoverSettings.Summary = summary:Graph
SecSureRecoverSettings.Details = details:Grid

#Software & User

SWCatalogComplianceDetails.Summary = summary:Graph
SWCatalogComplianceDetails.Details = details:Grid

SWErrors24HourSummaryDetails.HoursSummary = hours_summary:Grid

SWErrorsTopDevicesWithErrorsDetails.Summary = summary:Graph
SWErrorsTopDevicesWithErrorsDetails.Details = details:Grid

SWErrorsTopErrorsDetails.MonthlySummary = monthly_summary:Graph
SWErrorsTopErrorsDetails.ErrorsbyOperatingSystem = error_by_os_build:Graph
SWErrorsTopErrorsDetails.ErrorsSummary = errors_by_application:Graph
SWErrorsTopErrorsDetails.Details = details:Grid

SWInventoryDetails.Summary = summary:Graph
SWInventoryDetails.Details = details:Grid

SWInventoryrecdetappDetails.Summary = summary:Graph
SWInventoryrecdetappDetails.Details = details:Grid

SWInventorySummaryDetails.Summary = summary:Graph
SWInventorySummaryDetails.Details = details:Grid

SWUtilizationSummary.TopUsedWindowsApplications = top_used_windows_applications:Graph
SWUtilizationSummary.TopUsedAndroidApplications = top_used_android_applications:Graph
SWUtilizationSummary.TopUsedMacApplications = top_used_mac_applications:Graph
SWUtilizationSummary.Details = details:Grid

SoftwareUtilizationByDevice.Details = details:Grid

SWWindowsPerf.StartPerf = startup_performance:Graph
SWWindowsPerf.ShutdownPerf = shutdown_performance:Graph
SWWindowsPerf.WakeupPerf = wakeup_performance:Graph
SWWindowsPerf.ByModel = by_model:Graph
SWWindowsPerf.Reboots = reboots:Graph
SWWindowsPerf.Details = details:Grid

SWDriverInventory.Summary = summary:Graph
SWDriverInventory.Drivers = drivers:Graph
SWDriverInventory.DriversTable = driversTable:Grid
SWDriverInventory.Details = details:Grid

SWWindowsUpdates.ByModel = by_model:Graph
SWWindowsUpdates.ByOSRelease = by_os_release:Graph
SWWindowsUpdates.ByWeek = by_week:Graph
SWWindowsUpdates.ByUpdate = by_update:Grid
SWWindowsUpdates.Details = details:Grid
SWWindowsUpdates.Summary = summary:Grid

SWChromeAUE.Summary = summary:Graph
SWChromeAUE.Details = details:Grid

UserMobilityFactorDetails.Summary = summary:Graph
UserMobilityFactorDetails.Details = details:Grid

IncidentManagementResolution.Summary = summary:Graph
IncidentManagementResolution.Details = details:Grid

DeviceEnrollmentStatus.MonthlySummary = monthly_summary:Graph
DeviceEnrollmentStatus.Summary = summary:Graph
DeviceEnrollmentStatus.Details = details:Grid

BaseUnitPerInvReport.Summary = summary:Graph
BaseUnitPerInvReport.Details = details:Grid

PerInvReport.Summary = summary:Graph
PerInvReport.PeripheralManufacturerandModel = peripheral_manufacture_and_model:Grid
PerInvReport.Details = details:Grid

PerChangeReport.Summary = summary:Graph
PerChangeReport.Details = details:Grid
PerChangeReport.KeyChangeActivity = key_change_activity:Grid

PerUsageStatsReport.Printers = printers:Graph
PerUsageStatsReport.Scanners = scanners:Graph
PerUsageStatsReport.MagneticStripeReaders = magnatic_stripe_readers:Graph
PerUsageStatsReport.Cashdrawers =cash_drawer:Graph
PerUsageStatsReport.Details = details:Grid


PerThresholdReport.Printers = printers:Graph
PerThresholdReport.Scanners =scanners:Graph
PerThresholdReport.MagneticStripeReaders = magnatic_stripe_readers:Graph
PerThresholdReport.Details = details:Grid

PeripheralMaintenanceReport.PrintheadMaintenance = printhead_maintenance:Grid
PeripheralMaintenanceReport.PrinterKnifeMaintenance = printer_knife_maintenance:Grid
PeripheralMaintenanceReport.MSRMaintenance = MSR_maintenance:Grid

BaseunitusagehoursanalyticsReport.Summary = summary:Graph
BaseunitusagehoursanalyticsReport.Details = details:Grid

PeripheralKeyActivityReport.CashDrawerActivity = cash_drawer_activity:Grid
PeripheralKeyActivityReport.PeripheralClaimingErrors = peripheral_claiming_errors:Grid
PeripheralKeyActivityReport.USBDevice = unknown_USB_device:Grid
PeripheralKeyActivityReport.PeripheralThresholdMet = peripheral_threshold_met:Grid

JobsCompletedperTechnicianDetails.Summary = summary:Graph
JobsCompletedperTechnicianDetails.Details = details:Grid

TimeToFixRateDetails.Summary = summary:Graph
TimeToFixRateDetails.Details = details:Grid

JobStatusPerServiceTypeDetails.Summary = summary:Graph
JobStatusPerServiceTypeDetails.Details = details:Grid

ServiceCallTypesDetails.Summary = summary:Graph
ServiceCallTypesDetails.Details = details:Grid

FormsUsageDetails.Summary = summary:Graph
FormsUsageDetails.Details = details:Grid

CallDropReasonsDetails.Summary = summary:Graph
CallDropReasonsDetails.Details = details:Grid

MobilityFactorDeviceMobility.Summary = summary:Graph
MobilityFactorDeviceMobility.Details = details:Grid

Win10HwComptbl.Summary = summary:Graph
Win10HwComptbl.Details = details:Grid

ReWorkServiceOrdersDetails.Summary = summary:Graph
ReWorkServiceOrdersDetails.Details = details:Grid

TotalServiceCallsCompletedDetails.Summary = summary:Graph
TotalServiceCallsCompletedDetails.Details = details:Grid

ExpertAnalyticsDetails.Summary = summary:Graph
ExpertAnalyticsDetails.Details = details:Grid

TechnicianAnalyticsDetails.Summary = summary:Graph
TechnicianAnalyticsDetails.Details = details:Grid

TechnicianAndExpertAnalyticsDetails.Summary = summary:Graph
TechnicianAndExpertAnalyticsDetails.Details = details:Grid

WebApplication.utilizationsummary = utilization_summary:Graph
WebApplication.Details = details:Grid

#Subscription
SubscriptionExpiration.Summary = summary:Graph
SubscriptionExpiration.Details = details:Grid

TotalInvoicePerServiceTypeDetails.Summary = summary:Graph
TotalInvoicePerServiceTypeDetails.Details = details:Grid

TechWorkVsSoBillableTimeDetails.Summary = summary:Graph
TechWorkVsSoBillableTimeDetails.Details = details:Grid

LabourHoursDetails.Summary = summary:Graph
LabourHoursDetails.Details = details:Grid

CostPerInstallDetails.Summary = summary:Graph
CostPerInstallDetails.Details = details:Grid

DaysToCloseASoDetails.Summary = summary:Graph
DaysToCloseASoDetails.Details = details:Grid

DaysAServiceCallIsOpenDetails.Summary = summary:Graph
DaysAServiceCallIsOpenDetails.Details = details:Grid

FirstTimeFixRateDetails.Summary = summary:Graph
FirstTimeFixRateDetails.Details = details:Grid

PartsSoldViaSODetails.Summary = summary:Graph
PartsSoldViaSODetails.Details = details:Grid

RevenuePerTechPerPeriodOfTimeDetails.Summary = summary:Graph
RevenuePerTechPerPeriodOfTimeDetails.Details = details:Grid

TravelTimePerTechDetails.Summary = summary:Graph
TravelTimePerTechDetails.Details = details:Grid

ServiceCallFailureTypesDetails.Summary = summary:Graph
ServiceCallFailureTypesDetails.Details = details:Grid

LaborConsumptionCostDetails.Summary = summary:Graph
LaborConsumptionCostDetails.Details = details:Grid

SecSureStartIntegrity.Summary = summary:Graph
SecSureStartIntegrity.Details = details:Grid

SecSureRecoverActivity.Summary = summary:Graph
SecSureRecoverActivity.Details = details:Grid

#Deployment Data Health
DeploymentDataHealth.Summary = summary:Graph
DeploymentDataHealth.Details = details:Grid

#Deployment Status
DeploymenetStatus.ByInstallationStatus = by_installation_status:Graph
DeploymentStatus.ByProxyConfigurationStatus = by_proxy_configuration_status:Graph
DeploymentStatus.Details = details:Grid

#HWWarrantyV2
HWWarrantyDetailsV2.Summary = summary:Graph
HWWarrantyDetailsV2.Details = details:Grid

#HWDevUtilAlldata
DeviceUtilAllData.Details = details:Grid

#SubscriptionSeatsEntitledbyDeviceEnrollment
SubSeatsEntitledbyDevEnrol.MonthlySummary = monthly_summary:Graph
SubSeatsEntitledbyDevEnrol.WeeklySummary = weekly_summary:Graph
SubSeatsEntitledbyDevEnrol.Details = details:Grid

#HWBiosSettings
HWBiosSettingsDetails.Summary = summary:Graph
HWBiosSettingsDetails.SettingsChangeHistory = settings_change_history:Grid
HWBiosSettingsDetails.Details = details:Grid

#Network
wirelessNetworkingCardInventory.Summary = summary:Graph
wirelessNetworkingCardInventory.Details = details:Grid

#HWDisplay
HWDisplay.Overview = Global.componentInv.overview:Graph
HWDisplay.ByDisplayMFG = by_DisplayMfg:Grid
HWDisplay.ByDisplayModel = Global.graphHeaders.byDisplayModel:Grid
HWDisplay.ByDevice = Global.graphHeaders.byDevice:Grid
HWDisplay.Details = details:Grid

#DockingStation
HWCompInvDockingStation.Summary = summary:Graph
HWCompInvDockingStation.Details = details:Grid

#HW Performance Comparison
hwPerfComparison.Details = details:Grid

#HWWeeklyComparisonToTechPulseBenchmark
HWPerfWeeklyComparisonToTechPulseBenchmark.CpuUtilization =graphHeaders.Hardware_Health_new.monthly_summary.cpu_utilization:Graph
HWPerfWeeklyComparisonToTechPulseBenchmark.MemoryUtilization = graphHeaders.Device_Utilization.Summary.title.memory_utilization:Graph
HWPerfWeeklyComparisonToTechPulseBenchmark.BlueScreenErrors = graphHeaders.Hardware_Health_new.monthly_summary.blue_screen_error:Graph
HWPerfWeeklyComparisonToTechPulseBenchmark.StartupPerformance = startup_performance:Graph
HWPerfWeeklyComparisonToTechPulseBenchmark.ShutDownPerformance = shutdown_performance:Graph
HWPerfWeeklyComparisonToTechPulseBenchmark.Details = details:Grid

#NetworkHealth
NWHealth.Summary = summary:Graph
NW.Details = details:Grid
NWOutage.Details = network outage details:Grid

RoomUtilizationSummary.Summary = summary:Graph
RoomUtilizationSummary.ByWeek = by_week:Graph
RoomUtilizationSummary.ByDay = by_day:Graph
RoomUtilizationSummary.Details = details:Grid
