#Analytics LIST page
selectPageSize=[xpath]://*[@aria-label="Select page size"]
size100=[xpath]:(//button[@role="menuitem"])[4]
totalReports=[xpath]:(//*[@aria-label="Select page size"]/following::span)[1]
win11=[xpath]://*[@id="classic-report-Windows_11_Readiness_Assessment"]
hwInventory=[xpath]://*[@id="classic-report-Hardware_Inventory_Details"]
biosInventory=[xpath]://*[@id="classic-report-BIOS_Inventory_Details"]
deviceUtilization=[xpath]://*[@id="classic-report-Device_Utilization"]
driverInventory=[xpath]://*[@id="classic-report-Driver_Inventory"]
reportTabslist=[xpath]://div[@aria-label='Tab Navigation']/div
blueScreenErrors=[xpath]://*[@id="classic-report-Blue_Screen_Errors"]   
softPaqInsights = [xpath]://a[@id='modern-report-softpaqDashboard']
#analytics = [xpath]://*[@id='customdashboard']//a
analytics = [xpath]://div[@id='customdashboard']//li/span
ApplicationExperience = [xpath]://*[@id="classic-report-Application_Experience"]
applicationInventory = [xpath]://*[@id="modern-report-appinv"]
experienceScore= [xpath]://*[contains(text(), "Device Utilization")]
osPerformanceScore= [xpath]://*[@id="modern-report-osperformancescore"]
securityScore= [xpath]://*[@id="modern-report-securityscore"]
systemHealthScore= [xpath]://*[@id="modern-report-systemhealthscore"]
applicationScore = [xpath]://*[@id="app_score_chart"]/div/div[1]
appWithMostCrashes = [xpath]://*[@id="installed-apps-most-crashes"]/div/div[1]
appWithMostFreezes = [xpath]://*[@id="installed-apps-most-freezes"]/div/div[1]
crashesAndFreezesOverTime = [xpath]://*[@id="installed_applications_crashesandfreezes"]/div/div[1]
topInstalledApps = [xpath]://*[@id="top-installed-apps"]/div/div[1]
appMostInstalledVersions = [xpath]://*[@id="apps_with_most_installed_versions"]/div/div[1]
biosSumary = [xpath]://*[@id="0"]
uniqueBios = [xpath]://*[@id="1"]
byWeek = [xpath]://*[@id="2"]
details = [xpath]://*[@id="3"]
biosVersionByDeviceModel = [xpath]://*[@id="biosInventorySummaryByModel0"]/div
topModelsAffected = [xpath]://*[@id="topDetails_topModelsAffected"]/div/div[1]
topDriversCausing = [xpath]://*[@id="topDetails_topDriversCausing"]/div/div[1]
topBugCheckCodes = [xpath]://*[@id="topDetails_topBugCheckCodes"]/div/div[1]
bsodOverTime = [xpath]://*[@id="bsod_over_time_widget"]/div/div[1]
byManufacturerYear = [xpath]://*[@id="1"]
windowsSoftwarePerformance = [xpath]://*[@id="2"]
macOSSoftPerf = [xpath]://*[@id="3"]
deviceUtiDetails = [xpath]://*[@id="4"]
cpuUtilizationSummary = [xpath]://*[@id="cpuUti0"]/div[1]
memoryUtilizationSummary = [xpath]://*[@id="memUti0"]/div[1]
drivers = [xpath]://*[@id="1"]
driversTable = [xpath]://*[@id="2"]
driverStatus = [xpath]://*[@id="driverByStatus0"]/div[1]
outdatedDriverByCritically = [xpath]://*[@id="driverByCriticality0"]/div[1]/div
experienceScores = [xpath]://*[@id="wex-score-label"]/div/div[1]
overallScores = [xpath]://*[@id="wex_menu_item_value"]
overallScoresContainer = [xpath]://*[@id="dui-container"]/div/div/div[1]
experienceOverTime = [xpath]://*[@id="wex-score-over-time"]/div/div[1]
topIssueImpactingSentiment = [xpath]://*[@id="top_issue_impacting_sentiment"]/div/div[1]
devicesScore = [xpath]://*[@id="ee_devices_score"]/div/div[1]
deviceModel = [xpath]://*[@id="0"]
operatingSystem = [xpath]://*[@id="1"]
siteName = [xpath]://*[@id="2"]
byLocation = [xpath]://*[@id="0"]
byDeviceConfiguration = [xpath]://*[@id="1"]
byDeviceModel = [xpath]://*[@id="2"]
byOS = [xpath]://*[@id="3"]
byDetails = [xpath]://*[@id="4"]
hwInventoryByLocation = [xpath]://*[@id="deviceByLocation0"]/div
osSystemHealth = [xpath]://*[contains(text(),"System Health")]
osPerformance = [xpath]://*[contains(text(),"OS Performance")]
osPerformancesScore = [xpath]://*[@id="fleet_score_chart_performance"]/div/div[1]
osPerformancesSummary = [xpath]://*[@id="fleet_summary_performance"]/div/div[1]
topOSPerfIssue = [xpath]:(//div[contains(text(),"Top OS Performance Issue")])[1]
osPerfOverTime = [xpath]://*[@id="fleet_over_time_performance"]/div/div[1]
osPerfChangeOverTime = [xpath]://*[@id="changesLastWeek_performance"]/div/div[1]
osPerfByModel = [xpath]://*[@id="device_by_modal_performance"]/div/div[1]
securityScores = [xpath]://*[@id="fleet_score_chart_security"]/div/div[1]
securitySummary = [xpath]://*[@id="fleet_summary_security"]/div/div[1]
topSecurityIssue = [xpath]://*[@id="top_digital_issues_security"]/div/div[1]
securityOverTime = [xpath]://*[@id="fleet_over_time_security"]/div/div[1]
securityChecksLastWeek = [xpath]://*[@id="changesLastWeek_security"]/div/div[1]
securityByModel = [xpath]://*[@id="device_by_modal_security"]/div/div[1]
securityRA = [xpath]://*[@class="recommended-actions"]
systemHealthScores = [xpath]://*[@id="fleet_score_chart_health"]/div/div[1]
systemHealthSummary = [xpath]://*[@id="fleet_summary_health"]/div/div[1]
topSystemHealthIssue = [xpath]://*[@id="top_digital_issues_health"]/div/div[1]
systemHealthOverTime = [xpath]://*[@id="fleet_over_time_health"]/div/div[1]
systemHealthChangeLastWeek = [xpath]://*[@id="changesLastWeek_health"]/div/div[1]
systemHealthByModel = [xpath]://*[@id="device_by_modal_health"]/div/div[1]
sysRecommendationAction = [xpath]://*[@class="dui-dex-recommended-container dui-exp-padding"]
overview = [xpath]://*[@id="win11UpgradeStatusKpi0"]/div[1]
updateBreakdown = [xpath]://*[@id="win11compatibilityIssue0"]/div[1]
topDeviceModel = [xpath]://*[@id="win11Top5DeviceModel0"]/div[1]
uniqueBIOSVersionModel =[xpath]://*[@id="biosInventoryByModel1"]/div[1]
biosStatusWeek =[xpath]://*[@id="biosInventoryByWeek2"]/div[1]
deviceUtiDeviceYear = [xpath]://*[@id="cpuUti1"]/div[1]
memoryUtiDeviceYear = [xpath]://*[@id="memUti1"]/div[1]
appCauseCPUOverUtilization = [xpath]://*[@id="softwarePerfByCpu2"]/div[1]
appCauseMacCPUOverUtilization = [xpath]://*[@id="softwarePerfByCpu3"]/div[1]
appCauseMemOverUtilization = [xpath]://*[@id="softwarePerfByMem2"]/div[1]
appCauseMacMemOverUtilization = [xpath]://*[@id="softwarePerfByMem3"]/div[1]
driversByModel = [xpath]://*[@id="driverByModel1"]/div[1]
devicesModel = [xpath]://*[@id="deviceModel"]
driverName = [xpath]://*[@id="driverName"]
driverVersion = [xpath]://*[@id="driverVersion"]
msrcSecurity = [xpath]://*[@id="criticalityStatus"]
driverStat = [xpath]://*[@id="driverStatus"]
noOfDevices = [xpath]://*[@id="noOfDevices"]
lastSignUser = [xpath]://*[@id="lastSignedUser"]
serialNumber = [xpath]://*[@id="deviceSn"]
deviceName = [xpath]://*[@id="deviceName"]
deviceModels = [xpath]://*[@id="deviceModel"]
deviceOS = [xpath]://*[@id="deviceOs"]
deviceOSReleases = [xpath]://*[@id="deviceOsRelease"]
deviceOSVersion = [xpath]://*[@id="deviceOsVersion"]
reportListSort =  [xpath]://*[contains(text(),"Report")]
lastSignedUser = [xpath]://*[@id="lastSignedUser"]
serialNumbers = [xpath]://*[@id="deviceSn"]
deviceNames = [xpath]://*[@id="deviceName"]
deviceType = [xpath]://*[@id="deviceType"]
deviceAge = [xpath]://*[@id="deviceAge"]
deviceManufacturer = [xpath]://*[@id="deviceMfg"]
devicModel = [xpath]://*[@id="deviceModel"]
devicMfgDate = [xpath]://*[@id="mfgDate"]
devicePlatformId = [xpath]://*[@id="devicePlatformId"]
cpuUsageScoreCategory = [xpath]://*[@id="cpuUsageScoreCategory"]
memoryUsageScoreCategory = [xpath]://*[@id="memoryUsageScoreCategory"]
hwInvDeviceTypeSummary = [xpath]://*[@id="hwInvDeviceTypeSummary1"]/div[1]
deviceByModel = [xpath]://*[@id="deviceByModel2"]/div[1]
deviceByOS = [xpath]://*[@id="deviceByOS3"]/div[1]
deviceOsOriginal = [xpath]://*[@id="deviceOsOriginal"]
osRelease = [xpath]://*[@id="osRelease"]
deviceSerialNumber = [xpath]://*[@id="deviceSerialNumber"]
deviceManufacturers = [xpath]://*[@id="deviceManufacturer"]
devicesOS = [xpath]://*[@id="deviceOS"]


insightsPageBSOD= [xpath]: //span[text()='Blue Screen Errors']
topModelAffected=  [xpath]: //div[@id='topDetails_topModelsAffected']
topDriverAffected= [xpath]: //div[@id='topDetails_topDriversCausing']
topBugCheckCode= [xpath]: //div[@id='topDetails_topBugCheckCodes']
bsodOverTimeWidget= [xpath]: //div[@id='bsod_over_time_widget']
exportButton = [xpath]: //button[@type='button']//span[text()='Export']
exportBsodDevices = [xpath] : //button[@id='wex-menu-list-item']
toastNotificationExport = [xpath]://div[@role='status']//div[1]

#softpaq Insights

softPaqOverTime= [xpath]: //div[contains(@class, 'widget-missing-softpaqs-over-time')]
impactedDeviceByWeek = [xpath]: //div[contains(@class, 'widget-impacted-devices-by-week')]
softPaqByCriticality = [xpath]: //div[contains(@class, 'widget-missing-softpaqs-by-criticality')]
softPaqByCategory = [xpath]: //div[contains(@class, 'widget-missing-softpaqs-by-category')]
softPaqTableColumns = [xpath]: //div[contains(@class,'softpaq-analytics-grid')]//thead//tr//th[@id]


#Apps Inventory
applicationInventoryButton = [xpath]://div[@id='custom-report-modern-reports']//a[text()='Application Inventory']
toastNotificationExportApplicationInventory = [xpath]:(//div[@role='alert']/div/div[1])
firstAppNameLinkApplicationInventoryDashboard = [xpath]:(//*[@class='dui-hyperlink'])[1]
appInventoryDetailsPage = [xpath]:(//*[@id='applicationInventory']//li//a)[2]
topInstalledAppsTitle = [xpath]:(//*[@id="top-installed-apps"]//h2[@class='wexcard-header-title']//div)[2]
topInstalledAppsProgressBars = [xpath]://*[@id="top-installed-apps"]//div[contains(@class,'wex-progress-bar')]
sortedNoOfDevices = [xpath]://*[@id='deviceCountSum']//span
noOfDevicesHeader = [xpath]://*[@id='deviceCountSum']//button
topAppNameList = [xpath]://*[@id='top-installed-apps']//*[contains(@class,'app-with-issue-label')]
topAppCountList = [xpath]://*[@id='top-installed-apps']//*[contains(@class,'count')]
listofApplicationCountGrid = [xpath]://table//tbody//td[2]//div[@class='table-ellipsis ']
listOfAppNames = [xpath]://div[@class='table-ellipsis ']//a[@class='dui-hyperlink']
appsWithMostInstalledVersionsTitle = [xpath]:(//*[@id="apps_with_most_installed_versions"]//h2[@class='wexcard-header-title']//div)[2]
appsWithMostInstalledVersionsList = [xpath]://*[@id='apps_with_most_installed_versions']//*[contains(@class,'app-with-issue-label')]
appsWithMostInstalledVersionssProgressBars = [xpath]://*[@id="apps_with_most_installed_versions"]//div[contains(@class,'wex-progress-bar')]
appsWithMostInstalledVersionssCountList = [xpath]://*[@id='apps_with_most_installed_versions']//*[contains(@class,'count')]
applicationScoreValue=[xpath]://div[@id="application_fleet_score"]//span[contains(text(),'Application Score')]
appNameColumn = [id]:appName
latestVersionColumn = [id]:latestVersionMax
totalVersionsInstalledColumn = [id]:appVersionCountDistinct
appPublisherColumn = [id]:appPublisherMax
lastSignedInUser = [id]:lastSignedInUser
appVersion = [id]:appVersion
appInstallDate = [id]:appInstallDate
osVersion = [id]:osVersion
location1 = [id]:location1
mfgYear = [id]:mfgYear
firstDeviceCounttextApplicationInventoryGrid = [xpath]:(//table//tbody//td[2]//div[@class='table-ellipsis '])[1]
installedVersiontitle = [xpath]:(//*[@id="installed_versions"]//h2[@class='wexcard-header-title']//div/div[1])
firstappVersionCount = [xpath]:(//table//tbody//td[4]//div[@class='table-ellipsis '])[1]
firstinstalledVersionDeviceCount = [xpath]:(//*[@class="apps-with-issues-row data"]//div//div[contains(@class, 'flex-content-sb-center count')])[1]
reactSkelaton = [xpath]://div[@class='dui-page-spinner']//*[name()='svg']
paginationCount = [xpath]://*[@aria-label='Select page size']//following-sibling::span
appInventoryGridNoData = [xpath]://div[@class='scim-table ']//div[contains(@class,'empty-state-widget-text')]
xlsxButtonInExport =[xpath]://*[@id="wex-menu-list-item"]//span


#dashboard
customDashboard= [xpath]:  //div[@id='create-custom-dashboard']
application= [xpath]: //div[@id='custom-dashboard-widget-lib-APPLICATION-category']
allWidgets= [xpath]: //div[@id="chart-widget-list"]/div
createDashboard = [xpath]: //div[@class='page-header']//button
dashboardName = [xpath]: //span[starts-with(text(), 'New Dashboard')]
systemHealth = [xpath]: //div[@id='custom-dashboard-widget-lib-SYSTEM-category']
dashboardellipis= [xpath]:(//*[@id="dui-container"]//div/button)[1]
deleteDashboard = [xpath]://div[@id='custom-dashboard-delete-button']
deleteDashboardButton = [xpath]: //div[contains(@class,'vn-modal')]//button[2]

#Reports
duplicateReportButton = [xpath]: //div[@id='wex_menu_item_duplicate']
duplicateReportPage =   [xpath]: //span[starts-with(text(), 'Copy')]
deleteReporteellipis = [xpath]: //div[@id='wex_menu_item_delete']
deleteReportButton = [xpath]:(//*[@id='modal-id']/following-sibling::div//button)[last()]
toastNotificationDelete = [xpath]: (//div[@role='alert']//div[1])[2]
scrollView = [xpath]://p[contains(@class,'report-header')]
modernReports = [xpath]: //div[@id='modern-reports']
classicReports = [xpath]: //div[@id='classic-reports']
businessInsights = [xpath]: //div[@id='business-insights']

customName= [xpath]: //p[@class='text-overflow-ellipsis-flex']
searchBox= [xpath]: //input[@id='search']
analyticsMenu = [xpath]: //a[@id='menu_reports']
searchResult = [xpath]: //div[@id='custom-report-modern-reports']//a
reportTable = [xpath]: //div[@class='reports-table']
editButton = [xpath]: //*[local-name()='svg' and @id='title']
customReportTitle= [xpath]://div[contains(@class,'custom-report-name-input')]//input

employeeEngagement= [xpath]: //div[@id='custom-report-modern-reports']//a[text()='Employee Engagement']
labs= [xpath]: //a[@id='menu_labs']
labsFleetExplorerCard= [xpath]://div[@id='labs-fleet-explorer-card']
tryNowFleetExplorer=[xpath]://button[@aria-label="Try Now Fleet Explorer"]
helloOnFE=[xpath]://h1[@class='title']
labsSubtitleOnFleetExplorer=//h1[@class='title']/following-sibling::p[1]
fleetExplorerChatBox=[xpath]://textarea[@id='fleex-explorer-chat-box']
suggestedQuestionsFE=[xpath]://div[@class='suggested-question']
answerWidgets=[xpath]://div[@class='answer-container']
answerRespText=[xpath]://div[@class='answer-container']//p
answerRespTable=[xpath]://div[contains(@class,'fleet-explorer-pinned')]//table
answerRespTableRow=[xpath]://div[contains(@class,'fleet-explorer-pinned')]//tr[2]
fleetExplorerChatBoxSendButton=[xpath]://button[@id='send-question']
employeeEngagementDashboard=[xpath]://*[@id='custom-dashboard-employee-engagement']
SentimentScoreWidget= [xpath]://div[contains(@class,'sentiment-score')]
SentimentScoreEmptyWidget= [xpath]: //div[@class='wex-empty-state-widget']
SentimentScoreEmptyWidgetTxt= [xpath]://div[@class='wex-empty-state-widget-text']
overviewMetricsWidget=[xpath]://div[contains(@class,'overview-metrics-for-pulses')]
viewPulseDetails=[xpath]://button[@title='View Details']
PulselistBanner =  [xpath]://div[@class='pulses-header']/*[last()]
CreateButton = [xpath]://button//span[text()='Create']
YaxisOptionsTIIS = [xpath]: //*[@class='topIssueImpcSentiment-score']//span[@class="axis-label"]
collaborationExperience=[xpath]://div[@id='custom-dashboard-collaboration-experience']
colExperienceWidgetsTitle=[xpath]://*[@class='wexcard-header-title']
meetingsSummaryCols=[xpath]://div[contains(@class,'wex-meeting-widget')]
MeetByPlatformYaxis=[xpath]: //div[contains(@class, 'meetings-by-platform-over-time')]//*[contains(@class,'yaxis-labels')]
MeetByPlatformXaxis=[xpath]: //div[contains(@class, 'meetings-by-platform-over-time')]//*[contains(@class,'xaxis-labels')]
MeetByPlatformCharts=[xpath]://div[contains(@class, 'meetings-by-platform-over-time')]//*[contains(@class,'highcharts-series-group')]
MeetByPlatformoverTime=[xpath]://div[contains(@class,'meetings-by-platform-over-time')]//div[contains(@id,'highcharts')]//*[name()='svg']
MeetQualityMSFTTeams=[xpath]://div[contains(@class,'msft-teams')]//div[contains(@id,'highcharts')]//*[name()='svg']
MeetingQualityZoom=[xpath]://div[contains(@class,'zoom')]//div[contains(@id,'highcharts')]//*[name()='svg']
MeetingQualityCiscoWebex=[xpath]://div[contains(@class,'cisco-webex')]//div[contains(@id,'highcharts')]//*[name()='svg']
remoteParticipantQOE=[xpath]://div[contains(@class,'remote-participant-quality-of-experience')]//div[contains(@id,'highcharts')]//*[name()='svg']
corporateNetworkQOE=[xpath]://div[contains(@class,'corporate-network-quality-of-experience')]//div[contains(@id,'highcharts')]//*[name()='svg']
badQOEByNetwork=[xpath]://div[contains(@class,'bad-quality-of-experience-by-network')]//div[contains(@id,'highcharts')]//*[name()='svg']
videoEndpointQOE=[xpath]://div[contains(@class,'video-endpoint')]//div[contains(@id,'highcharts')]//*[name()='svg']
endUserDeviceQOE=[xpath]://div[contains(@class,'end-user-device')]//div[contains(@id,'highcharts')]//*[name()='svg']

collaborationSpaces=[xpath]://div[@id='custom-dashboard-collaboration-spaces']
colSpacesWidgetsTitle=[xpath]://*[@class='wexcard-header-title']
spaceOverviewCols=[xpath]://div[@class='space-overview-widget']
roomMinByLocation=[xpath]://div[contains(@class,'occupied-room-minutes-by-location')]
roomMinByLocationXaxis=[xpath]://div[contains(@class,'occupied-room-minutes-by-location')]//*[contains(@class,'xaxis-labels')]
roomMinByLocationYaxis=[xpath]://div[contains(@class,'occupied-room-minutes-by-location')]//*[contains(@class,'yaxis-labels')]
roomMinByLocationXaxisLocation=[xpath]://div[contains(@class,'occupied-room-minutes-by-location')]//ul/li
roomActivityType=[xpath]://div[contains(@class,'room-activity-type')]
roomActivityTypeYaxis=[xpath]://div[contains(@class,'room-activity-type')]//*[contains(@class,'xaxis-labels')]
roomActivityTypeXaxis=[xpath]://div[contains(@class,'room-activity-type')]//*[contains(@class,'yaxis-labels')]
spacesByType=[xpath]://div[contains(@class,'spaces-by-type')]
spacesByRoomSystem=[xpath]://div[contains(@class,'spaces-by-room-system')]
bookMeetByLocation=[xpath]://div[contains(@class,'booked-meetings-by-location')]
missedMeetByLocation=[xpath]://div[contains(@class,'missed-meetings-by-location')]
highlyUtilizedSpace=[xpath]://div[contains(@class,'highly-utilized-spaces')]
hwDetailsRow=[xpath]://div[@id='reportGrid4']//tr[3]
hwDetailsPageSize=[xpath]://button[@aria-label='Select page size']
hwDetailsTotalSize=[xpath]://button[@aria-label='Select page size']/following::span[1]

modalViewButton=[xpath]:(//button[starts-with(@id,"partner-ra-all-list-item-resolve-button")])[1]
modalCompanyName=[xpath]://*[@id="partner-ra-all-list-item-name-0"]
