rolesAndPermissionTab = [css]:#rbac
addButton = [id]:add-custom-role
roleName = [xpath]://th[@id='name']
description = [css]:#description
roleType = [css]:#type
rolenameSearch = [xpath]://input[@id='name']
descriptionSearch = [xpath]://input[@id='description']
typeSelect = [xpath]: //*[@id='roleLevel']
customType = [xpath]://span[text()='Custom']
moduleType = [xpath]://span[text()='Module']
basicType = [xpath]://span[text()='Basic']
clearButton = [xpath]://button[@title='Clear']
mouseHoverOptions = [xpath]://*[@id="extended-rbac"]//tbody/tr[1]/td[5]/button
mouserHoverDetails = [id]:wex_menu_item_details
mouseHoverDelete = [id]:wex_menu_item_delete
mouseHoverDuplicate = [id]:wex_menu_item_duplicate
mouserHoverTestRole = [id]:wex_menu_item_testRole
revertTestingRole = [xpath]://button[@title='Revert Testing Role']
createCustomeRoleHeader = [xpath]://div[@class='rbac-details-content']//h5
testRole = [xpath]://span[text()='Test Role']
stepOf1 = [xpath:(//p)[1]
customRoleName = [id]:role-name-label
roledecription = [id]:role-desc-label
rolesearch = [xpath]://input[@id='role-name']
descriptionsearch = [xpath]://input[@id='role-desc']
selectPermissionHeader = [xpath]://div[@class ='rbac-details-selection-header']//h6
belowPara = [xpath]://div[@id='wrapper-step-one-role-selection']/div[3]//p
templatesCardsHeader = [xpath]:(//div[@class='rbac-details-template-cards-container']//h6)[i]
templatesDescription = [xpath]:(//div[@id='templates-description'])[i]
templatesCards = [xpath]://div[@class='rbac-details-template-cards']
templatescard1 = [xpath]://div[@class='rbac-details-template-cards'][1]
permissions = [xpath]:(//div[@class="rbac-details-groups-layout"])/div
permissionsHeader = [xpath]:(//div[@class="rbac-details-groups-layout"])/div[i] //button/div[1]
permissionsLabel = [xpath]:(//div[@class="rbac-details-groups-layout"])/div[i] //button/div[2]
permissionToggle = [xpath]:(//div[@class="rbac-details-groups-layout"])/div[i]//div[@class="rbac-details-group-card-layout"] //h4
permissionToggleHeader = [xpath]:((//div[@class="rbac-details-groups-layout"])/div[i]//div[@class="rbac-details-group-card-layout"] //h4)[j]
permissionToggleButton = [xpath]:((//div[@class="rbac-details-groups-layout"])/div[i]//div[@class="rbac-details-group-card-layout"] //label)[j]
rbacSearch = [css]: #rbac-search
rbacSearchResult = [css]: .rbac-details-search-container div.wex-tag-content
accountsHeader = [xpath]://div[@id='header-0']
alertsHeader = [xpath]://div[@id='header-1']
analyticsHeader = [xpath]://div[@id='header-2']
devicesHeader = [xpath]://div[@id='header-3']
devicesandPrinterHeader = [xpath]://div[@id='header-4']
groupsHeader = [xpath]://div[@id='header-5']
helpAndSupportHeader = [xpath]://div[@id='header-6']
homePageHeader = [xpath]://div[@id='header-7']
integrationsHeader = [xpath]://div[@id='header-8']
labsHeader = [xpath]://div[@id='header-9']
miscHeader = [xpath]://div[@id='header-10']
partnerHeader = [xpath]://div[@id='header-11']
printerHeader = [xpath]://div[@id='header-12']
pulsesHeader = [xpath]://div[@id='header-13']
remeditationsActivitesHeader = [xpath]://div[@id='header-14']
remeditationPoliciesHeader = [xpath]://div[@id='header-15']
remeditationScriptsHeader = [xpath]://div[@id='header-16']
remeditationScretesHeader = [xpath]://div[@id='header-17']
remeditationWorkFlowHeader = [xpath]://div[@id='header-18']
settingsHeader = [xpath]://div[@id='header-19']
defaultHeader = [xpath]://div[@id='header-20']
saveAndContinueButton = [id]:next-button
cancelButton = [css]:#cancel-button
roleOption = [xpath]:(//div[@id='role-name-data'])[1]
descriptionOption = [xpath]://*[@id="extended-rbac"]//tbody/tr[1]/td[2]/div/div[1]
roleNameSearchButton = [xpath]://input[@id="name"]/following-sibling::div/button
recordsInTable = [css]:#extended-rbac tbody tr
noRecordText = [css]: .wex-empty-state-widget .state-title
account = [css]:#Account
accountBreadcrumb = [xpath]://div[@id='Account']//a
rolesBreadcrumb = [xpath]:(//div[@id='Account']//span)[1]
toastmessage = [xpath]://div[@role='status']
deleteButton = [id]:delete-role-button
roleCancelButton = [id]:cancel-role-button
deletePopupHeader = [css]:#remove-role-modal-label
deletemessage = [css]: #remove-role-modal
clearFilter = [xpath]://button[@name="button"]
noResults = [xpath]://h3[@class='state-title']
rbacDetailsPageHeader = [css]: h5.rbac-details-assign-users-title-text
rbacDetailsPageLabel = [css]: .rbac-details-assign-users-title-section p
rbacDetailsPageExistingUserTitle = [xpath]: (//h5[@class="rbac-details-assign-users-title-text"])[2]
userNameColumn = [css]: #userName span
emailColumn = [css]: #email span
userNameSearch = [css]: #name-search
emailSearch = [css]: #email-search
addUserButton = [xpath]://button[@id="add-custom-role"]
removeButton = [xpath]:(//button[@id="add-custom-role"])[2]
finishButton = [css]:#next-button
assignUsersLabel = [css]:#rbac-assign-users-label
userRoleSearch = [css]:#name-search
userSearch = [css]:#rbac-search-users
usersConfirm = [css]:#assign-users-confirm-button
usersCancel = [css]:#assign-users-cancel-button
checkbox = [xpath]://div[@id='scroll-check']//label
firstCheckbox = [xpath]://table/tbody/tr/td[1]/span/label/span
firstColumn = [xpath]:(//tbody/tr/td/div)[1]
typeColumn = [xpath]://tbody//td[3]
usersSearch = [xpath]://input[@id='name-search']
#Partner_Roles
partnerBasic = [id]:role-type-search-option-1