tablelist=[xpath]://table[@id='vyoptaVideoEndpoints']
videoEndpointPageTitle = [xpath]://span[@aria-current="page"]
videoEndpointPageList = [xpath]://table[@id='vyoptaVideoEndpoints']/tbody
videoEndpointPageTableRows=[xpath]://table[@id='vyoptaVideoEndpoints']/tbody//tr
videoEndpointPageTableCount=[xpath]://button[@aria-label='Select page size']/following-sibling::span
videoEndpointsTableColumns= [xpath]://table[@id='vyoptaVideoEndpoints']//tr[1]/th[@scope='col']
videoEndpointPageFirstRowData = [xpath]://table[@id='vyoptaVideoEndpoints']/tbody/tr/td[1]
endpointNameCol = [xpath]://th[@id="endpointname"]/div/button
showingPaginationTotalCount = [xpath]://button[@aria-label="Select page size"]/following-sibling::span
VideoEndpointcontent =[xpath]://div[@class="dui-table-list dui-es-table-with-config"]
Firstrow =[xpath]:(//a[@class="wex-link default  dui-hyperlink text-overflow-ellipsis "])[1]
Firstrowtitle =[xpath]://nav[@aria-label="breadcrumbs"]
Profile =[xpath]://*[text()="Profile"]
Description =[xpath]://div[text()="Description"]
AltName =[xpath]://label[text()="Alt Name"]
Price =[xpath]://label[text()="Price"]
Devicetag =[xpath]://label[text()="Device Tags"]
Roomname =[xpath]://label[text()="Room Name"]
Building =[xpath]://label[text()="Building"]
Loaction =[xpath]://label[text()="Location"]
Peripheralstatus =[xpath]://*[text()="Peripheral Status"]
Peripheralstatusdetails=[xpath]://div[@class="video-endpoint-details-peripheral-status"]
Hardware =[xpath]://*[text()="Hardware"]
HArdwaredetails =[xpath]://div[@id="video-endpoint-hardware"]
Software=[xpath]://*[text()="Software"]
Softwaredetails =[xpath]://div[@id="video-endpoint-software"]
NetworkButton =[xpath]://*[text()="Network"]
Networkdetails =[xpath]://div[@id="video-endpoint-network"]
Manufacturerdropdown =[xpath]:(//div[contains(@class, 'base-pill-ComboboxTrigger')])[1]
HP =[xpath]://span[text()="HP"]
ViewVyoptaButton =[xpath]://span[text()="View in Vyopta"]
EditViewButton =[xpath]:(//button[@class="btn btn-primary btnPadding"])[2]
Titlepage =[xpath]://span[@aria-current="page"]
HardwareDetails =[xpath]:(//div[@class="box-header with-border"])[1]
Network =[xpath]: (//div[@class="box box-primary"])[2]
Manufacturebutton =[xpath]://div[text()="Manufacturer"]
HPbutton =[xpath]://div[text()="HP"]
SerialNumber =[xpath]://div[text()="Serial Number"]
Serial =[xpath]://div[@data-bind="html: serial"]
Categorybutton =[xpath]://div[text()="Category"]
Category =[xpath]://div[@data-bind="html: category"]
Microsoft =[xpath]://span[text()="Microsoft"]
Model =[xpath]://div[text()="Model"]
Modelname =[xpath]://div[@data-bind="html: model"]
Configurationdevice =[xpath]:(//div[@class="box box-primary"])[5]
Endpointtilepage =[xpath]://nav[@aria-label="breadcrumbs"]
Checkbox =[xpath]:(//label[contains(@class, 'vn-table__selector')])[2]
ExportButton =[xpath]://button[@id="export-device"]
ExportTitle =[xpath]://*[@id="video-endpoint-export-modal-label"]
Cancelbutton =[xpath]://span[text()="Cancel"]
FullDialog =[xpath]://div[@aria-labelledby="video-endpoint-export-modal-label"]
CurrentTable =[xpath]://div[text()="Current field from table"]
ExportNotification =[xpath]://div[text()="Export is in progress"]
ImportExportAction =[xpath]:(//div[@id="wex-value-id"])[1]
XLSXFile =[xpath]://span[text()="XLSX"]
NotificationCenter =[xpath]://button[@aria-label="Open Notification Center"]
NotificationTab =[xpath]://span[text()="Notifications"]
DownloadFile =[xpath]:(//button[@aria-label="Download file"])[1]
Clearfilterbutton =[xpath]://span[text()="Clear Filters"]
Sortingbutton =[xpath]://*[contains(@class,"base-active-ascending-Icon")]
VyoptaPageIframe =[xpath]://iframe[@title='WXP Collaboration']
Calltab =[xpath]://span[text()="Calls"]
TimeDisplay =[xpath]://button[@class="timeDisplayButton"]
LiveValue =[xpath]:(//span[@class="liveValue"])[7]
Endpointis =[xpath]:(//div[@class="newFilter"])[1]
Quality =[xpath]:(//div[@class="newFilter"])[2]
Calltype =[xpath]:(//div[@class="newFilter"])[3]
CallHeader =[xpath]://div[@class="tabulator-header"]
CallContent =[xpath]://div[@class="tabulator-tableHolder"]
OverView =[xpath]://div[text()="Overview"]
TotalCall =[xpath]://div[text()="Total Calls"]
TotalMin =[xpath]://div[text()="Total Minutes"]
TotalPoorCall =[xpath]://div[text()="Poor Calls"]
CallView =[xpath]://div[@id="tab-video-endpoint-details-calls"]
CallHistoryTab =[xpath]://*[text()="Call History"]
setting =[xpath]://button[@aria-label="Column Options"]
Qualitybutton =[xpath]:(//span[text()="Quality"])[1]
SaveButton	=[xpath]://span[text()="Save"]
ResetButton =[xpath]://span[text()="Reset to default"]
DetailscallHistorypage =[xpath]://*[@id="vyoptaVideoEndpointsDetailsCalls"]
UserSettings =[xpath]://div[@aria-label="User Profile"]
DarkMode =[xpath]://li[@aria-label="Dark"]
LightMode =[xpath]://li[@aria-label="Light"]