package com.daasui.constants;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class WorkflowVariables {
	// Workflow Company Details
	public static final String STABLE_WORKFLOW_USERNAME = "automation_workflow_testing_stable@mailinator.com";
	public static final String STAGING_WORKFLOW_USERNAME = "wfstagetest00@yopmail.com";
	public static final String PRODUCTION_WORKFLOW_USERNAME = "hpworkflowservicecenter@outlook.com";
	public static final String PRODUCTION_WORKFLOW_COMPNAME = "HPServiceCenter";
	public static final String WORKFLOW_PASSWORD = "Testing123";
	public static final String WORKFLOW_ADMIN_ROLE = "workflow_admin";
	public static final String PRODUCTION_HELP_LIGHTNING_ID = "HP Service Center"; 
	public static final String PRODUCTION_HP_FORMS_ID = "HP Service Center";
	public static final String HPWORKEXPERT = "HP WorkExpert";
	public static final String USER = "Workflow Reportadmin";
	public static final ArrayList<String> TOTALAIRCHARTORDER = new ArrayList<String>(Arrays.asList("workflow.dashboard.charts.title.tech_work_vs_billable_time","workflow.dashboard.charts.title.average_invoice_per_service_type","workflow.dashboard.charts.title.total_calls_run","workflow.dashboard.charts.title.revenue_per_tech","workflow.dashboard.charts.title.labour_hours","workflow.dashboard.charts.title.service_callback","workflow.dashboard.charts.title.travel_time_per_technician","workflow.dashboard.charts.title.time_to_fix_rate","workflow.dashboard.charts.title.service_call_types","workflow.dashboard.charts.title.accessories_usage_per_service","workflow.dashboard.charts.title.form_usage_per_technician","workflow.dashboard.charts.title.forms_created","workflow.dashboard.charts.title.parts_sold","workflow.dashboard.charts.title.days_servicecall_open","workflow.dashboard.charts.title.first_time_fix_rate","workflow.dashboard.charts.title.cost_per_install","workflow.dashboard.charts.title.service_call_fail","workflow.dashboard.charts.title.labour_consumption","workflow.dashboard.charts.title.days_to_close"));
	public static final String DEVICENAME = "AutomationTest";
	public static final String MANUFACTURERNAME = "HP-Automation";
	public static final String MODELNAME = "HP-Automator07";
	public static final String SERIAL_NUMBER = "AutomationDeviceWf";
	public static final String ALIAS = "AliasWfAutomation";
	public static final String USERFNAME = "SelAutoWf";
	public static final String USERLNAME = "User";
	public static final String USEREMAIL = "automationwfuser";
	public static final String USERWFROLE = "Workflow Admin";
	public static final String[] DAASROLESFORWF = {"User","IT Admin","Report Admin","Workflow Admin"};
	public static final String YAXISLABELSJSPST = "Inspection Repair Unknown Extended Warranty Installation Warranty Maintenance";
	public static final String LABELSJSPST = "Allocated Cancelled Closed Completed InReview InWork OnHold Planned ReOpen Resolved Stop Work Unallocated";
	public static final ArrayList<String> REPORT_NAME_LIST = new ArrayList<String>(Arrays.asList("Travel Time per Technician","Job Status per Service Type","Total Service Calls Completed","Technician Work vs SO Billable Time","Re-Work Service Orders","Labor Consumption Cost","First Time Fix Rate","Revenue per Tech per Period of Time","Call Drop Analytics","Parts Sold via Service Order","Jobs Completed per Technician","Service Call Types","Service Call Failure Types","Total Invoice per Service Type","Days a Call Is Open","Forms Usage","Days to Close Service Order","Cost per Install","Labor Hours","Technician Analytics","Expert Analytics","Technician and Expert Analytics","Time to Fix Rate"));
	public static final String USERSEARCHFORWORKFLOWROLE = "reportadminuser00@hpmsqa.mailinator.com";
	public static final String DYNAMICPINNINGTOGGLE = "workflow-dashboard-redesign";
	public static final List<String> HPFORMSCHARTIDLIST = Arrays.asList("mostusedforms","averagetraveltimepertechnician","formtimetofix","dayssrvcallopen","partssold","workstatusbyservicetype","firstimefixrate","daystoclose","labourconsumption","newformscreated","usagepertechnician","revenuepertech","totalcallrun","costPerInstall","techbillablevsworkedtime","avginvoiceperservicetype","labourhours","servicecallback","servicecallfail");
	public static final List<String> HPINSTANTHELPCHARTIDLIST = Arrays.asList("hlcalldrop","hltechniciancalls","hlCallCount","hlexpertcallduration","hltechexpert","hlexpertcalls","hltechniciancallduration");
	public static final ArrayList<String> HPINSTANTHELPCHARTORDER = new ArrayList<String>(Arrays.asList("workflow.dashboard.charts.title.calls_by_expert","workflow.dashboard.charts.title.calls_duration_per_technician","workflow.dashboard.charts.title.calls_end_types","workflow.dashboard.charts.title.calls_by_technician","workflow.dashboard.charts.title.calls_made_by_all_employees","workflow.dashboard.charts.title.calls_duration_per_expert","workflow.dashboard.charts.title.call_pair"));
	public static final String SwaggerURL = "https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json";
	public static final String TargetURL = "https://seatence-teams.atlassian.net/rest/api/3/issue";
	public static final String key = "x-sn-apikey";
	public static final String Value = "now_96WtFaOoerdvtxTSrMjLu9Mbzh4Wzk_f97UARSKaOsw2OqkLjsv_zPnqxFRq4D06R0RVO6_IaReJt2USIP0qJA";
	public static final String WEBHOOKNAME= "Regerssion_Webhook";
	public static final String WORKFLOWNAME= "Webhook_Automation_IST";
	public static final String workflowname = "Regression_workflow_timestamp";
	public static final String serialnumber = "CND2410152"; 
	public static final String Inactivserialnumber = "CND2203RV6";
	public static final String CompletedWorkflowname = "Webhook_workflow_regression";
	public static final String ActiveWorkflowname = "Active_Webhook_workflow_regression";
	public static final String ActiveWorkflownamecopy = "Active_Webhook_workflow_regression-Copy";
	public static final String latestGroup_Name = "BS_Static_New_Group";
	public static final String GroupName = "BS_static_group_creations";
	public static final String Group_Name = "BS_Static_New_Policy_Group";
	public static final String PostMethod = "POST /rest/api/3/issue";
	public static final String Username = "n9r5x2xr0@mozmail.com";
	public static final String AlertWorkflow = "Alert_Workflow_IST";
	public static final String windowsSecurity = "Windows Security";
	public static final String ScriptWorkflow = "Script_Workflow_IST";
	public static final String ScriptOutputWorkflow = "Script_Output_Workflow_IST";
	public static final String ScriptSearch = "Enable Windows Credential Guard";
	public static final String BitLockerScript = "Enable BitLocker Drive Encryption";
	public static final String SecureBootscript = "Enable Secure Boot";
	public static final String windowsfirewallscript = "Enable Windows Firewall";
	public static final String InvokeRestartScript = "Invoke Restart Reminder";
	public static final String FaststartupScript = "Enable Google Chrome Memory Saver";
	public static final String DiskCleanupcript = "Invoke Disk Cleanup";
	public static final String HealthManager = "Set HP Battery Health Manager to Default";
	public static final String RepairTask = "Repair System Files";
	public static final String InvokeMgr = "Invoke CleanMgr";
	public static final String MSEdge = "Enable Microsoft Edge Sleeping Tabs";
	public static final String PowerMode= "Set Windows Power Mode Best Performance";
	public static final String AppDeploy = "Invoke CM App Deploy Eval Cycle";
	public static final String ImageAssistant = "Run HP Image Assistant";
	public static final String Repairzoom = "Repair Zoom installation";
	public static final String Dellcommand = "Run Dell Command Update";
	public static final String ReuseWorkflow = "Reuse_Workflow_IST";
	public static final String Password = "ATATT3xFfGF00kmn9SBXz44TPX4o0ZQ-0ZSsSVhhI9_IZcTXl4sg-vvqKxXEoC-oWWAoK6TnB3QtWW640v-qKWIo5Y_Lj9JdcwoOSg1lz3eAqyEU5K8GrwPHVvxXNDQMLFBmWrwMGqh8WDdm5sLF6i-D1KXcAwZAJyATROLEzKnoi-DOo6_lmzE=A17F0BB1";
	public static final ArrayList<String> ExpectedResults =  new ArrayList<String>(Arrays.asList("BS_Static_Group_Assign_Policy","BS_Workflow_Static_Group"));
	public static final ArrayList<String> updatedExpectedResults = new ArrayList<String>(Arrays.asList("BS_Static_Group_Assign_Policy", "BS_Static_Group_latest", "BS_Static_New_Group", "BS_static_group_creations"));
	public static final String FleetAlertWORKFLOWNAME = "FleetAlert_Automation";
	public static final String DraftWorkflowname = "DRAFT";
	public static final String ExecutionValidationAlert = "SampleForAutomation_DND";
}
